### ISSUE TITLE
Handle nodes with "status obsolete" statement

### ISSUE THREAD

**Issue by luowei-eric** [CESNET/libyang#10]
Hi,

In function read_yin_common(...), the "status" statement is parsed. If a node's status is "obsolete", its flag is set to LYS_STATUS_OBSLT.
According to RFC6020, "obsolete" means the definition is obsolete and SHOULD NOT be implemented and/or can be removed from implementations.
But I don't find any operation or validation are done for the obsoleted node. It is handled as normal node.Shouldn't the obsoleted node be treated as an unsupported node? Just similar with a node defined by if-feature and the feature is disabled.

Thanks,
Wei

**Comment by rkrejci** [comment]
Fixed in 0.4.10.

**Comment by rkrejci** [comment]
Note to the committed solution - the first part implements checking according to the last three paragraphs in RFC6020 sec 7.19.2 and it affects only parsing of schemas.

The second commit somehow deals with that "SHOULD NOT" you have mentioned. Remember that libyang is supposed to serve to diffirent implementation and "SHOULD NOT" is not the same as "MUST NOT", Therefore, libyang has to be able to work even with obsolete data instances. We decided to keep this as a default approach. But now, there is `LYD_OPT_OBSOLETE` option for data parseing (via e.g. `lyd_parse_data()`) and validation (via `lyd_validate()`) so you can specify that your application do not accept instances of the obsolete data nodes.
