### ISSUE TITLE
devel branch does not build in Release mode

### ISSUE THREAD

**Issue by muscariello** [CESNET/libyang#1001]
i.e. cmake -DCMAKE_BUILD_TYPE:String="Release"

[  7%] Building C object CMakeFiles/yangobj.dir/src/hash_table.c.o
/workdir/extras/libyang/src/hash_table.c: In function 'lyht_dbgprint_ht':
/workdir/extras/libyang/src/hash_table.c:637:60: error: 'LY_LDGHASH' undeclared (first use in this function); did you mean 'LYP_WD_MASK'?
     if ((LY_LLDBG > ly_log_level) || !(ly_log_dbg_groups & LY_LDGHASH)) {
                                                            ^~~~~~~~~~
                                                            LYP_WD_MASK
/workdir/extras/libyang/src/hash_table.c:637:60: note: each undeclared identifier is reported only once for each function it appears in
/workdir/extras/libyang/src/hash_table.c:634:17: warning: variable 'i_len' set but not used [-Wunused-but-set-variable]
     uint32_t i, i_len;
                 ^~~~~
/workdir/extras/libyang/src/hash_table.c:631:53: warning: unused parameter 'info' [-Wunused-parameter]
 lyht_dbgprint_ht(struct hash_table *ht, const char *info)
                                                     ^~~~
/workdir/extras/libyang/src/hash_table.c: In function 'lyht_dbgprint_value':
/workdir/extras/libyang/src/hash_table.c:667:60: error: 'LY_LDGHASH' undeclared (first use in this function); did you mean 'LYP_WD_MASK'?
     if ((LY_LLDBG > ly_log_level) || !(ly_log_dbg_groups & LY_LDGHASH)) {
                                                            ^~~~~~~~~~
                                                            LYP_WD_MASK

**Comment by michalvasko** [comment]
Hi,
sorry about that, should work now.

Regards,
Michal

**Comment by muscariello** [comment]
Thanks you
