### ISSUE TITLE
libyang2: null pointer dereference in lys_compile_node_leaflist due to referenced missing type

### ISSUE THREAD

**Issue by jvijtiuk** [CESNET/libyang#1004]
Hello,

the following file crashes yanglint on the libyang2 branch:

```
module a {
  yang-version 1.1;
  namespace "a";
  prefix a;

  leaf-list A {
    type pt8;
    default 0;
  }
}
```

The issue is caused by a null pointer dereference in tree_schema_compile.c:3883, as llist->type is null. A null check there would fix the issue, however I guess that the issue is actually caused somewhere else, e.g. I'm not sure if yanglint should exit once lys_compile_type detects that the pt8 type is missing.

Regards,
Juraj

**Comment by michalvasko** [comment]
Hi Juraj,
quite a complex fix was required but it should work now.

Regards,
Michal

**Comment by jvijtiuk** [comment]
Thanks, I've confirmed that 6a044b2 fixes this so I'm closing the issue.
