### ISSUE TITLE
Printing a list and its keys without value for NETCONF retrieval

### ISSUE THREAD

**Issue by syyyr** [CESNET/libyang#1007]
Hello,
I'm using libyang to print XML trees for use in NETCONF \<get-config\>. Specifically, I need to create a tree for retrieving a list and all of its keys, but without any other data, so for this list:
```yang
list car {
  key 'name';
  leaf name {
    type string;
  }
  leaf color {
    type string;
  }
}
```
I only want to retrieve the `name` leaf, but NOT the `color` leaf. In the NETCONF specification ([here](https://tools.ietf.org/html/rfc6241#section-6.2.4)), it says, that it should be possible with this XML:
```xml
<car>
  <name />
</car>
```
How would I go about doing this? Libyang won't let me insert a leaf with an empty value, but that's exactly what I need (I think). Am I missing something? Is this the right approach? 
```cpp
libyang::Data_Node node(ctx, "/module:car", nullptr, LYD_ANYDATA_CONSTSTRING, 0);
node->print_mem(LYD_XML, 0); // this gives me <car></car>
// how to add <name /> ?
```

**Comment by michalvasko** [comment]
Hi,
yes, this is possible but like you said, you want to also create the leaf `name` without a value. That is only possible if you explicitly tell *libyang* that is what you really want to do. In your case
```C++
libyang::Data_Node node(ctx, "/module:car/name", nullptr, LYD_ANYDATA_CONSTSTRING, LYD_PATH_OPT_EDIT);
```
should work.

Regards,
Michal

**Comment by syyyr** [comment]
This works for me, thank you. I was kind of confused about the `LYD_PATH_OPT_EDIT` flag, because it specifically says "These leaves are valid if used in a NETCONF edit-config with delete/remove operation." and nothing about NETCONF \<get-config\>.
