### ISSUE TITLE
Valid default identityref values should derive all the base identities

### ISSUE THREAD

**Issue by fredgan** [CESNET/libyang#1009]
Hi,
As described in [RFC7950 9.10.2](https://tools.ietf.org/html/rfc7950#page-163)
```
   Valid values for an identityref are any identities derived from all
   the identityref's base identities.  On a particular server, the valid
   values are further restricted to the set of identities defined in the
   modules implemented by the server.
```
Valid values for an identityref is **not** any identities derived from **all the identityref's base identities**. However, yanglint(version 1.2.7) will report some errors. The module is as following:
`a.yang`
```
module a {
  yang-version 1.1;
  namespace "urn:cesent:a";
  prefix aa;

  identity id1;
  identity id4;
  identity id7;

  identity id2 {
    base id1;
  }

  identity id3 {
    base id2;
  }

  identity id5 {
    base id4;
  }

  identity id6 {
    base id5;
  }

  identity id8 {
    base id7;
    base id6;
  }

  leaf le1 {
    type identityref {
      base id1;
      base id4;  
    }
    default "id8";  // "id8" is derived from "id4" 
  }
}
```
`The actual result :`
```
$ yanglint -f yang mod1.yang
module mod1 {
  yang-version 1.1;
  namespace "urn:cesent:mod1";
  prefix aa;

  identity id1;

  identity id4;

  identity id7;

  identity id2 {
    base id1;
  }

  identity id3 {
    base id2;
  }

  identity id5 {
    base id4;
  }

  identity id6 {
    base id5;
  }

  identity id8 {
    base id7;
    base id6;
  }

  leaf le1 {
    type identityref {
      base id1;
      base id4;
    }
    default "id8";  // "id8" is derived from "id4" 
  }
}
```
The expected is like that:
```
error: the value "id8" does not match its base type - identityref not derived from id1
```

**Comment by michalvasko** [comment]
Hi,
identity derivation is [transitive](https://tools.ietf.org/html/rfc7950#section-7.18.2), it works as it should.

Regards,
Michal

**Comment by fredgan** [comment]
Yeah, I know. `id8` derived from  {id6, id7}, total base is {id6, id7, id5, id4}
but the type of `le1` has two base {id1, id4}, so `id8` doesn't derive from `id1`,  violate the rule `Valid values for an identityref are any identities derived from all
   the identityref's base identities`

I also questioned Martin for this rule. You may refer: https://github.com/mbj4668/pyang/issues/540

**Comment by michalvasko** [comment]
Hi,
hm, it seems you are right then and loading the module should now display an error.

Regards,
Michal
