### ISSUE TITLE
lyd_parse_mem errors with "unknown element" on valid JSON

### ISSUE THREAD

**Issue by pieterlexis** [CESNET/libyang#1014]
Hi,

I have this json:

```json
{
  "pdns-server:zones": {
    "zones": [
      {
        "name": "slave.example.",
        "rrset-state": [
          {
            "owner": "slave.example.",
            "rdata": {
              "SOA": {
                "expire": 604800,
                "minimum": 3600,
                "mname": "ns1.example.net",
                "refresh": 10800,
                "retry": 3600,
                "rname": "hostmaster.slave.example",
                "serial": 1
              }
            },
            "ttl": 3600,
            "type": "SOA"
          }
        ]
      }
    ]
  }
}
```

Here's the relevant parts of the schemas:

```yang
        list rrset-state {
            config false;
            if-feature "rrset-management";
            when "../zonetype = 'slave'";
            uses rrset;
            key "owner type";
        }
```
```yang
    grouping rrset {
        uses dnszc:owner-field;
        leaf ttl {
            type dnszc:time-interval;
            mandatory "true";
            description
              "Time-To-Live of the RR.";
        }
        leaf type {
            type dnsct:rr-type;
        }
        container rdata {
            uses rdata;
        }
    }
```
```yang
  grouping owner-field {
    description
      "This grouping defines the RR owner field.";
    leaf owner {
      type domain-name;
      mandatory "true";
      description
        "Owner of the RR."
    }
  }
```

When trying to parse this with lyd_parse_mem (using the c++ bindings, flags are `LYD_OPT_DATA | LYD_OPT_TRUSTED`), libyang errors like this:

```
Unknown element "owner". (path: /pdns-server:zones/zones[name='slave.example.']/rrset-state[owner='slave.example.']/owner)
```

The same error is also seen when inserting this with `sysrepocfg`.

For non-master zones, the `rrset` element exists in the tree:

```yang
        list rrset {
            if-feature "rrset-management";
            when "../zonetype = 'master' or ../zonetype = 'native'";
            uses rrset;
            key "owner type";
        }
```

When I insert the same json as `rrset` into sysrepo using `sysrepocfg` for a master zone, no such error is produced. Is this a problem with libyang or am I missing something here? I guess it is more of a combined sysrepo/libyang question: how can i publish changes to the operational datastore by only providing the changed nodes?

Using libyang 1.0.109

Thanks in advance.

PS, is there a libyang mailinglist that can be used for these kind of questions?

**Comment by michalvasko** [comment]
Hi,
I cannot really help you with *libyang* unless you provide all the schemas and data, there are too many `when` and `if-feature` statements to test this blindly. As for *sysrepo*, you can try using [push operational data](http://www.sysrepo.org/static/doc/html/index.html#oper_data).

Also, *libyang* does not have any mailing list, we communicate only using these issues and it works fine, I'd say.

Regards,
Michal

**Comment by pieterlexis** [comment]
Fixed after the discussions in https://github.com/sysrepo/sysrepo/issues/1804
