### ISSUE TITLE
err : Trying to dereference an unresolved leafref or instance-identifier.

### ISSUE THREAD

**Issue by kwatsen** [CESNET/libyang#1020]
The following script:

  1) downloads all test files
  2) runs validation (no errors)
  3) modifies a YANG module
  4) runs validation again (aye, errors!)

**Please be sure to put the script into an empty directory before running it!**

FWIW, I did verify that `yanglint` works with [the `deref()` example in RFC 7950](https://tools.ietf.org/html/rfc7950#section-10.3.1.1), which I started tweaking, but couldn't isolate the issue...

Thanks,
Kent

```
#!/bin/sh

DATE=`date +%Y-%m-%d`

fetch_file() {
  echo "fetching file $2..."
  curl -sO https://raw.githubusercontent.com/netconf-wg/$1/master/$2
}
fetch_file    trust-anchors          refs/ex-truststore.xml
fetch_file    keystore               refs/ex-keystore.xml 
fetch_file    ssh-client-server      refs/ietf-origin.yang
fetch_file    ssh-client-server      refs/ietf-netconf-acm@2012-02-22.yang
fetch_file    ssh-client-server      refs/iana-crypt-hash@2014-08-06.yang
fetch_file    ssh-client-server      refs/ex-ssh-server-keystore.xml


fetch_module() {
  echo "fetching module $2..."
  curl -sO https://raw.githubusercontent.com/netconf-wg/$1/master/$2.yang
  sed -e"s/YYYY-MM-DD/$DATE/" $2.yang > $2\@$DATE.yang
  rm $2.yang
}
fetch_module  crypto-types           ietf-crypto-types
fetch_module  crypto-types           iana-symmetric-algs
fetch_module  crypto-types           iana-asymmetric-algs
fetch_module  trust-anchors          ietf-truststore
fetch_module  keystore               ietf-keystore
fetch_module  ssh-client-server      ietf-ssh-common
fetch_module  ssh-client-server      ietf-ssh-server


command="yanglint -V -m -s ietf-origin.yang ietf-crypto-types\@*.yang ietf-truststore\@*.yang ietf-keystore\@*.yang ietf-ssh-common\@*.yang ietf-ssh-server\@*.yang ex-truststore.xml ex-keystore.xml ex-ssh-server-keystore.xml"

# this converts the grouping to a container so there is a protocol-accessible node
sed -i "" 's/^}/container ssh-server { uses ssh-server-grouping; }}/' ietf-ssh-server\@*.yang
echo
echo This works:
echo $command
`$command`

# this reveals the the bug
sed -i "" 's#//YANGLINT_TEST##' ietf-ssh-server\@*.yang
echo
echo This fails:
echo $command
`$command`


# cleanup
rm *.yang
rm *.xml
```

**Comment by kwatsen** [comment]
To whomever looks at this issue:

1. the files on the GitHub server will change over time.  I'm holding off making any changes that will affect this issue for now, but please post here after having fetched the files so I can safely start making changes again.

2. when looking at the `ietf-ssh-server\@*.yang` file, you'll notice numerous "FIXME" comments.  Please ignore them all, they are for me, not you!  I put the FIXMEs in there as placeholders for where all the new "must" statements should go; I ran into the issue while trying to add the first "must" statement, and simply checked-in the files that way...

3. I'm aware that the YANG contains an almost mind-numbing number of groupings, I highly recommend exporting the tree diagram to see how all the groupings stitches together.

4. FWIW, when I mentioned above about having tweaked [the deref() example in RFC 7950](https://tools.ietf.org/html/rfc7950#section-10.3.1.1), one of the tweaks I made was to add a grouping layer, which `yanglint` was still okay with...

5) the "command" in the script uses a single "-V" parameter, but I also ran it with multiple "-V" parameters and noticed a number of messages like `verb: There is no leafref "/ietf-keystore:keystore/ietf-keystore:asymmetric-keys/ietf-keystore:asymmetric-key/ietf-keystore:name" with the value "ssh-rsa-key", but it is not required.`.  I don't fully understand the algorithm, but since these messages are also printed when the validation test succeeds, I take them to be innocuous...

**Comment by michalvasko** [comment]
Hi Kent,
I have tried your script with this output
```
fetching file refs/ex-truststore.xml...
fetching file refs/ex-keystore.xml...
fetching file refs/ietf-origin.yang...
fetching file refs/ietf-netconf-acm@2012-02-22.yang...
fetching file refs/iana-crypt-hash@2014-08-06.yang...
fetching file refs/ex-ssh-server-keystore.xml...
fetching module ietf-crypto-types...
fetching module iana-symmetric-algs...
fetching module iana-asymmetric-algs...
fetching module ietf-truststore...
fetching module ietf-keystore...
fetching module ietf-ssh-common...
fetching module ietf-ssh-server...
sed: can't read s/^}/container ssh-server { uses ssh-server-grouping; }}/: No such file or directory

This works:
yanglint -V -m -s ietf-origin.yang ietf-crypto-types@2020-02-24.yang ietf-truststore@2020-02-24.yang ietf-keystore@2020-02-24.yang ietf-ssh-common@2020-02-24.yang ietf-ssh-server@2020-02-24.yang ex-truststore.xml ex-keystore.xml ex-ssh-server-keystore.xml
err : Unknown element "ssh-server". (/)
sed: can't read s#//YANGLINT_TEST##: No such file or directory

This fails:
yanglint -V -m -s ietf-origin.yang ietf-crypto-types@2020-02-24.yang ietf-truststore@2020-02-24.yang ietf-keystore@2020-02-24.yang ietf-ssh-common@2020-02-24.yang ietf-ssh-server@2020-02-24.yang ex-truststore.xml ex-keystore.xml ex-ssh-server-keystore.xml
err : Unknown element "ssh-server". (/)
```
and I do not think it is the expected output. Have you perhaps done any changes to the `ietf-ssh-server` module?

Regards,
Michal

**Comment by kwatsen** [comment]
No recent changes.  I just ran the script again and it works okay for me...

I'm on MacOS and, apparently, something is different with your `sed`:

```sed: can't read s/^}/container ssh-server { uses ssh-server-grouping; }}/: No such file or directory```

My guess is that the `-i ""` parameter is not understood.  This parameter says "replace the in-place and do not create a backup".  It is functionally equivalent to `sed 's/a/b/' x > tmp; mv tmp x`

Another thing you could try is to add the implicit `-e` parameter.  That is, `sed -i "" 's/a/b/' x` --> `sed -i "" -e 's/a/b/' x`.

Please be aware that `sed` is used twice in the script.
  - the first instance makes the last two lines of the `ietf-ssh-server` yang file look like this:
```
  } // grouping ssh-server-grouping
container ssh-server { uses ssh-server-grouping; }}
```

  - the second instance uncomments the three lines in `ietf-ssh-server` beginning with "//YANGLINT_TEST"

**Comment by michalvasko** [comment]
Hi Kent,
firstly, I do not have much experience with `sed` but with your hints I learned that my version does not like the space after `-i` so after I changed `-i ""` to `-i""`, it worked fine.

As for the issue, there were 2 problems. The data validation error was not valid as you knew but the problem was connected to how leafref targets are stored in data nodes and what happens if their target is no longer available after the validation. Anyway, that should be fixed now. But even then the validation did not pass because of the schema warning
```
warn: Schema node "public-key-format" not found (deref(.)/../public-key-format) with context node "/ietf-ssh-server:ssh-server/server-identity/host-key/host-key-type/public-key/public-key/local-or-keystore/keystore/keystore-reference".
```

It is my fault but I debugged it until I actually got to the exact line that compares the module of the context node with the module of `public-key-format` and fails. Correctly, I may add because the path should be
```
deref(.)/../ks:public-key-format
```

It is even fairly obvious from the nice message `yanglint` prints but I did not even bother checking whether it really is a false-positive warning. But anyway, after fixing the schema, validation passes.

> the "command" in the script uses a single "-V" parameter, but I also ran it with multiple "-V" parameters and noticed a number of messages like verb: There is no leafref "/ietf-keystore:keystore/ietf-keystore:asymmetric-keys/ietf-keystore:asymmetric-key/ietf-keystore:name" with the value "ssh-rsa-key", but it is not required.. I don't fully understand the algorithm, but since these messages are also printed when the validation test succeeds, I take them to be innocuous...

These messages inform about exactly what they print. Meaning, the target was searched and does not exist but since its `require-instance` is not `true` (or some special validation option is used), it does not matter.

Regards,
Michal

**Comment by kwatsen** [comment]
Hi Michal,

Sorry for being so dense when it comes to prefixes!  Yes, yanglint's messages are nice, but maybe a "hint: are prefixes needed?" for `must` expressions would help? 

Yes, the fix (both) work - thank you!

FWIW, there are no "require-instance false" anywhere in the models.   The "innocuous" " validation warning occur when validating instance data.  Specifically, the "ssh-rsa-key" in ex-ssh-server.xml refers (via leafref) to a value in ex-keystore.xml.  I know that it's the correct value because when I change "ssh-rsa-key" to "worng-rsa-key" in ex-ssh-server.xml, then a proper "leafref not found" error is generated.  I contend that something fishy is going on, but since it's not blocking me, I'll leave it to you to decide to investigate why the "innocuous" messages are generated...

Thanks again!
Kent

**Comment by michalvasko** [comment]
Hi Kent,
then the messages will be because of the fishy albeit handy `-m` option that you used. It causes all the data files to be loaded separately first, merged, and only then properly validated. The initial file loading must skip certain validation steps (such as checking leafrefs pointing to other modules - obviously, the target are not available at that time) and that is when the messages are printed. Note that this will work much better in the new *libyang* and there will be no such redundant confusing messages.

Regards,
Michal
