### ISSUE TITLE
deviation does not parse namespace prefix in default value

### ISSUE THREAD

**Issue by pschoenm** [CESNET/libyang#1022]
Please see following example:
https://gist.github.com/pschoenm/0e688d7ab855445b2ea9d58fe2e05a5c

The yang model defines a default value for a leaf, referencing ietf-syslog-types with prefix syslogtypes (syslogtypes:local7).  A deviation model, tries to delete the default value for the leaf, with the same value as the original model, "default syslogtypes:local7", this results in an error of 'Invalid value "syslogtypes:local7" of "default".'

If the deviation is changed to the module name, "default ietf-syslog-types:local7" it is properly parsed.

**Comment by michalvasko** [comment]
Hi,
sadly, you must consider this a feature. The original value is not preserved in this case so you are not able to deviate it. Fixing it would break ABI, which we would like to avoid. It will be correctly fixed (with other similar use-cases) in the new *libyang* we are currently working on, sorry.

Regards,
Michal

**Comment by pschoenm** [comment]
It is possible to resolve the the space in the deviation, before applying the deviation?  in the deviation yang model it does import ietf-syslog-types, so in theory "default syslogtypes:local7" could be resolved to the actual module name, "ietf-syslog-types:local7", requiring no need to maintain the original name.

**Comment by michalvasko** [comment]
Hi,
okay, it should cover the most common use-cases I suppose. Just note that it does not and never will cover all of them.

Regards,
Michal
