### ISSUE TITLE
Issue in module-name of an element in submodule yang

### ISSUE THREAD

**Issue by amandeepsethi** [CESNET/libyang#1023]
Hi,

I have a model and its submdel which are defined as follows:
**model.yang**
```
module model {
namespace "urn:test:params:xml:ns:yang:model";
prefix model;

  include submodel {
    revision-date 2014-12-10;
  }
}
```
**submodel.yang**
```
submodule submodel {

  belongs-to model {
    prefix mod;
  }

  revision 2014-12-10 {
  }

  leaf test {
    type string;
  }
}
```

Now I have the data which is as follows:
`<test xmlns=\"urn:test:params:xml:ns:yang:model\">A string</test>`

In debugging I observed that the module-name for the **test** element is printed to be that of the submodule. 

As per RFC 6020:
> A module may be divided into submodules, based on the needs of the module owner. The external view remains that of a single module, regardless of the presence or size of its submodules.

Shouldn't elements within a submodule should inherit the namespace etc. of the top module and not the submodule?

**Comment by fredgan** [comment]
Hi,

I use `yanglint` to check your model and test.xml, The output is as following:

```
root@40451b3ae48f:/data/data# yanglint -t config -f xml model.yang test.xml
<test xmlns="urn:test:params:xml:ns:yang:model">A string</test>
```
However, this output is correct as what the RFC said. 

>  In debugging I observed that the module-name for the test element is printed to be that of the submodule.

I am not quite sure what do you mean. Are you printing the intermediate value? Or what do you expect the output?

**Comment by amandeepsethi** [comment]
Hi Gan,

Thanks for responding. I am trying to fetch and print module-name for "test" element.
Attached is the code zip for your reference that I am using.

I am printing this value
`result->schema->module->name`
which is printing submodule name which is "submodel" while ideally it should print top module name i.e. model.

That's why I quoted the statement in above comment from RFC.

[Code.zip](https://github.com/CESNET/libyang/files/4270045/Code.zip)

**Comment by fredgan** [comment]
Hi,
I consider this as an implementation. It doesn't violate this rule from the **external view** of the model.
Because C has no class or Inheritance system, in libyang, there are two structure,  `struct lys_module`    and `struct lys_submodule`. 

Here, `result->schema->module` points to a structure `struct lys_submodule` actually. You can cast this pointer to `lys_submodule` type. 
```
 ((struct lys_submodule*)result->schema->module)->belongsto->name
```
If you want to print which model it belongs-to, this maybe what you want. Firstly, you should get the value of the `type` property. ` 1` for submodule, `0` for the main module.

**Comment by amandeepsethi** [comment]
Thanks Gan, I reached to the same code implementation but suspected if this is an issue as all elements of the submodule should point to top module-name.

**Comment by michalvasko** [comment]
@amandeepsethi If you want to get the RFC-defined module, always use `lyd_node_module(node)`.

Regards,
Michal

**Comment by amandeepsethi** [comment]
Yeah, that's really helpful to use library defined API. Thanks Michal.
I wrote the same in an if-else check in my stack code but will change to this, once doing any modification around.
