### ISSUE TITLE
An action MUST NOT have any ancestor node that is a list node without a "key" statement.

### ISSUE THREAD

**Issue by fredgan** [CESNET/libyang#1026]
Hi,
As described in [RFC 7950 Chapter 7.15](https://tools.ietf.org/html/rfc7950#page-119)
```
An action MUST NOT have any ancestor node that is a list node without a "key" statement.
```
As far as I know, it should throw some errors if a 'list' node without a 'key' statement contains an 'action' node. However, there are two situations where the libyang doesn't meet the requirements:

1) When the action is in a grouping, then a list node without a key uses this grouping.
2) When an augment statement including an action, and the target node is a list node without a key.

`version is yanglint SO 1.6.7`

YANG module:
```
module mod2 {
  yang-version 1.1;
  namespace "urn:mod2";
  prefix m2;

  container con1 {

    grouping gg1 {

      leaf le2 {
        type boolean;
      }
      action act1 {
        description
          "test description";
      }

      notification not1 {
        description
          "test description";
      }
    }
    list lst1 {
      key "name";
      config false;
      leaf name {
        type string;
      }

      list lst2 {
        container con2 {
          uses gg1;
        }

        container con3 {
          leaf le2 {
            type int8;
          }
        }
      }
    }
  }

  augment "/con1/lst1/lst2/con3" {
    action act2 {
      description
        "test description";
    }
  }
}
```

It's expected to report an error like : an action node cannot have an ancestor list node without a key

**Comment by michalvasko** [comment]
Hi,
fine, should work now.

Regards,
Michal

**Comment by fredgan** [comment]
The fix is pretty quick!
