### ISSUE TITLE
libyang2: invalid pointer dereference in lyd_path probably due to type confusion

### ISSUE THREAD

**Issue by jvijtiuk** [CESNET/libyang#1027]
Hello,

The following file causes yanglint to crash due to use of a invalid pointer:

```
module d{
	namespace "";
	prefix d;
	leaf f {
		type string;
		must ":e";
		default "";
	}
}
```

The issue appears because iter->schema is equal to 0x4, so dereferencing iter->schema->module accesses memory at 0xC in src/tree_data.c:1821.

The schema variable was set to 0x4 previously by parse_leaf in src/parser_yang.c:2090, as LYS_LEAF is 4, which is later interpreted as a pointer to 0x4. The issue seems to be that iter is used as a lyd_node, and the data was previously set through a pointer to lysc_node. Also, the node is actually a part of a lyxp_set which is passed through the call stack, and lyxp_set has a union which can be interpreted as lyd_node or lysc_node.

Changing xpath.c:5179 from LY_VLOG_LYD to LY_VLOG_LYSC seems to fix the issue, but I'm not sure whether that fix is entirely appropriate, or if the issue should be fixed somewhere else. 
Running yanglint with the fix applied produces the following output for the crashing input:
```
err : Unknown module "". (/d:f)
err : Invalid must restriction ":e". (/d:f)
```
If the fix is appropriate I can open a PR with the fix.

Regards,
Juraj

**Comment by michalvasko** [comment]
Hi Juraj,
it should always be possible to determine whether `ctx_node` or `ctx_scnode` can be used based on some function context, that is why this information is not stored directly in the set. It is true for this function as well except it was not done. Should work now.

Regards,
Michal

**Comment by jvijtiuk** [comment]
That makes sense, thanks for the explanation. 
2104e9f fixed this so I'm closing the issue.
