### ISSUE TITLE
libyang[0]: Module "ietf-inet-types" parsing failed.

### ISSUE THREAD

**Issue by sukesh21r** [CESNET/libyang#1028]
Hi,

I downloaded the latest release libyang 1.0.130. I did a cross platform compilation. when I run yanglint I am getting the following error
No saved history.
libyang[0]: Regular expression "(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\p{N}\p{L}]+)?" is not valid ("p{N}\p{L}]+)?)$": support for \P, \p, and \X has not been compiled).
libyang[0]: Module "ietf-inet-types" parsing failed.
Failed to create context.

When I run netopeer2-cli, I am getting the following error
ly ERROR: Regular expression "(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\p{N}\p{L}]+)?" is not valid ("p{N}\p{L}]+)?)$": support for \P, \p, and \X has not been compiled).
ly ERROR: Module "ietf-inet-types" parsing failed.
load_config: Failed to create context.
load_config: Unable to load configuration due to the previous error.
> ;1R;223R;1R;116R

Can you please help me resolving this issue.

Regards,
Sukesh.R

**Comment by michalvasko** [comment]
Hi,
right, you are by far the first person asking this so I have added the question into FAQ. So, please update *libyang* and look there.

Regards,
Michal

**Comment by sukesh21r** [comment]
Hi Michal,

I followed your process mention in FAQ. Still I am getting the same error.
Actually I am getting error while parsing ietf-inet-types not the yang .

} internal_modules[LY_INTERNAL_MODULE_COUNT] = {
    {"ietf-yang-metadata", "2016-08-05", (const char*)ietf_yang_metadata_2016_08_05_yin, 0, LYS_IN_YIN},
    {"yang", "2017-02-20", (const char*)yang_2017_02_20_yin, 1, LYS_IN_YIN},
    {"ietf-inet-types", "2013-07-15", (const char*)ietf_inet_types_2013_07_15_yin, 0, LYS_IN_YIN},
in src/context.c" line 65

Yang is successfully parsed, after parsing yang, next ietf-inet-types is failing.

Regards,
Sukesh.R

**Comment by sukesh21r** [comment]
Hi Michal,

I was able to solve the issue. The problem was with pcre library with centos. which needs to be compiled with --enable-unicode-properties enabled.
I was able to continue with this error but I am getting errors at later part. which I will try to resolve, if not possible I will post it later.

Regards,
Sukesh.R

**Comment by michalvasko** [comment]
Hi,
that is exactly what I wrote in the FAQ (referenced commit 1b44389a53a3b5eb80c2256f7f04cae9c0a80e9e).

Regards,
Michal

**Comment by sukesh21r** [comment]
Hi Michal,

Ohh Really, I could not see it. I think web page is not updated with those changes.

![FAQ](https://user-images.githubusercontent.com/16076278/76196642-a0808f00-6210-11ea-8119-e4750a7290c7.PNG)

The last commit visible for FAQ.d in webpage is c382959 on Aug 21, 2019

However the latest checkout code also doesn't contain those changes.

Regards,
Sukesh.R

**Comment by michalvasko** [comment]
Hi Sukesh,
well, you must switch to `devel` branch to see it.

Regards,
Michal

**Comment by sukesh21r** [comment]
Hi Michal,

Sorry I didn't knew it. Thanks for your support.

Regards,
Sukesh.R

**Comment by sukesh21r** [comment]
Resolved
