### ISSUE TITLE
normal leaf mandatorycheck failed in  master branch

### ISSUE THREAD

**Issue by ZhaoGuangYue** [CESNET/libyang#103]
In our test module ,thirdLevelLeaf_1 and thirdLevelLeaf_2 both are mandatory leaf, when we only create   thirdLevelLeaf_1 in our edit xml data ,it return success. in our opinion ,it should failed.

@rkrejci 

the edit xml data and the module like the follows:

**Edit xml data:**
`<RootContainer xmlns="urn:ietf:params:xml:ns:yang:fox" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
  <secondLevelContainer xc:operation="create">
    <thirdLevelLeaf_1>test-thirdLevelLeaf</thirdLevelLeaf_1>
  </secondLevelContainer>
</RootContainer>`

**Module :**
`module TestLeafInContainer {
  namespace "urn:ietf:params:xml:ns:yang:fox";
  prefix TestLeafInContainer;
  revision 2016-05-10;
  container RootContainer {
    presence "Real MO RootContainer";
    container secondLevelContainer {
      leaf thirdLevelLeaf_1 {
	    mandatory true;
        type string;
      }
	  leaf thirdLevelLeaf_2 {
	    mandatory true;
        type string;
      }
    }
  }
}`

**Comment by rkrejci** [comment]
I'm not able to reproduce the issue. With the current master (0.9.178) I'm getting `Validation of the changes failed` from the sysrepo and `Missing required element "thirdLevelLeaf_2" in "secondLevelContainer". (path: /TestLeafInContainer:RootContainer/secondLevelContainer)` in yanglint.
