### ISSUE TITLE
deviate delete fails with config attribute

### ISSUE THREAD

**Issue by maniowy** [CESNET/libyang#1031]
Libyang fails with an `Invalid keyword "config"` error when parsing a `delete` deviation removing the `config` attribute.

Input modules:

```
module test {
  namespace "http://www.example.com/test";
  prefix test;

  container root {
    config false;
  }
}
```

```
module test-dev {
  namespace "http://www.example.com/test-dev";
  prefix test-dev;
  import test { prefix "test"; }

  deviation "/test:root" {
    deviate delete {
      config "false";
    }
  }
}
```

Lint output:
```
$ lint test-dev.yang 
err : Invalid keyword "config".
err : Module "test-dev" parsing failed.
```

`replace` deviation works:

```
deviation "/test:root" {
  deviate replace {
    config "true";
  }
}
```

Tested on latest libyang master rev `1b7d73d4`.

Regards
Mateusz

**Comment by michalvasko** [comment]
Hi Mateusz,
this is not allowed per YANG 1.1 RFC, look at [deviate-delete-stmt](https://tools.ietf.org/html/rfc7950#page-201) ABNF grammar rule.

Regards,
Michal

**Comment by maniowy** [comment]
Hi Michal,

I have missed that, you are correct. YANG 1.0 RFC 6020 actually says the same.

Thank you for clarification, have to correct the model.

Regards
Mateusz
