### ISSUE TITLE
err : Invalid keyword "require-instance".

### ISSUE THREAD

**Issue by mjethanandani** [CESNET/libyang#1032]
Much like the script that Kent used, the following script:

1. downloads all test files
2. downloads the YANG module
3. downloads all imported/included YANG models from IANA site
4. runs validation and prints out error.

**Please be sure to put the script into an empty directory before running it!**

FWIW, I did verify that 

> require-instance

 is a valid keyword according to RFC 7950.

Note, the files in the repository are subject to change, though I will try to keep them as much as possible so that the issue can be reproduced.

Thanks. 

```
#!/bin/sh

DATE=`date +%Y-%m-%d`

fetch_file() {
  echo "fetching file $2..."
  curl -sO https://raw.githubusercontent.com/netconf-wg/$1/v02/src/yang/$2
}
fetch_file    https-notif            example-https-notif-7.1.xml

fetch_module() {
  echo "fetching module $2..."
  curl -sO https://raw.githubusercontent.com/netconf-wg/$1/v02/src/yang/$2.yang
  sed -e"s/YYYY-MM-DD/$DATE/" $2.yang > $2\@$DATE.yang
  rm $2.yang
}
fetch_module  https-notif            ietf-https-notif

# fetch all dependent modules
rsync -avz --delete rsync.ietf.org::iana/yang-parameters .

command="yanglint -s -i -t auto -p yang-parameters ietf-https-notif@$(date +%Y-%m-%d).yang example-https-notif-7.1.xml"


echo This fails:
echo $command
`$command`

# cleanup
rm *.yang
rm *.xml
rm -rf yang-parameters
```

**Comment by michalvasko** [comment]
Hi,
this was already discussed in https://github.com/CESNET/libyang/issues/881 and the conclusion was that you cannot put `require-instance` in a derived type based on [this](https://tools.ietf.org/html/rfc7950#section-9.9.3) text.

Regards,
Michal
