### ISSUE TITLE
Unable to retrieve path of data in date-and-time error

### ISSUE THREAD

**Issue by amandeepsethi** [CESNET/libyang#1034]
I am working on a Yang model where I am unable to fetch the path of node at fault in the data where the issue exits. The leaf having the issue is of date-and-time type imported from ietf-yang-types.yang file. If I do the same error-validation with leaf of other type then able to get the error-path.

For example:-
If leaf is of type int32 and data passed is a string then following error is seen:
`Invalid value "test" in "num" element. Path is /model:num`

And, when the leaf is of type date-and-time and value passed in not in correct format then following error is seen:
`Invalid character '-'[8] in date-and-time value "2020-03--4T10:20:30Z", a digit expected. Path is (null)`

Issue is that path shouldn't be Null but should display the correct hierarchy of the issue node as displayed in earlier example.

Attached is the code which displays the above said behavior.
[Code.zip](https://github.com/CESNET/libyang/files/4323585/Code.zip)

**Comment by michalvasko** [comment]
Hi,
the path should now be included.

Regards,
Michal

**Comment by amandeepsethi** [comment]
Thanks Michal for the quick fix, it works.
