### ISSUE TITLE
libyang2: null dereference in plugins_types.c

### ISSUE THREAD

**Issue by jvijtiuk** [CESNET/libyang#1040]
Hello,

the following file causes yanglint to segfault on the libyang2 branch.

```
module a {
  namespace "a";
  prefix a;

  container c {
    leaf r {
      type leafref{
        path "../p";
      }
      default false;
    }
  }
}
```

The issue is that at plugins_types.c:2378, type_lr->realtype is null. I am pretty sure that adding a check before line 2378 for null realtype is not the appropriate solution, as that just causes yanglint to segfault due to other null dereferences of realtype further along the execution, and fixing those reveals other null dereferences.

The issues seems to have something to do with erroneous parsing of the leafref, when the original lysc_type struct is parsed. The leafref seems to never be resolved, as the path it is referring to isn't valid.

Regards,
Juraj

**Comment by michalvasko** [comment]
Hi Juraj,
okay, this will require some minor default resolution refactoring and since I have other work with higher priority, it will be fixed later.

Regards,
Michal

**Comment by jvijtiuk** [comment]
613bc03 fixes this, so I'm closing the issue.
