### ISSUE TITLE
Segfault on lyd_insert()

### ISSUE THREAD

**Issue by rwestphal** [CESNET/libyang#1046]
This is similar to issue #898 I opened last year. This time my `lyd_replace()` function is crashing in one very specific case: when I add the `/frr-isisd:isis/instance/multi-topology/ipv6-unicast` leaf to the candidate configuration (which is then committed to the running configuration). Anything else seems to work fine.

I wrote this small test program that is able to reproduce the problem: https://gist.github.com/rwestphal/a2db45ac3d69d9b103c4f4f5011fa8de

Here's the crash and the backtrace:
```
Program received signal SIGSEGV, Segmentation fault.
lyd_insert_setinvalid (node=0x5555555aa530) at /mnt/renato/git/northbound/lang-c/libyang/src/tree_data.c:4249
(gdb) bt
#0  lyd_insert_setinvalid (node=0x5555555aa530) at /mnt/renato/git/northbound/lang-c/libyang/src/tree_data.c:4249
#1  0x00007ffff7f348ee in lyd_insert_common (parent=0x5555555a78f0, sibling=0x0, node=0x5555555aa530, invalidate=1) at /mnt/renato/git/northbound/lang-c/libyang/src/tree_data.c:4561
#2  0x00007ffff7f34a2c in lyd_insert (parent=0x5555555a78f0, node=0x5555555aa530) at /mnt/renato/git/northbound/lang-c/libyang/src/tree_data.c:4593
#3  0x00005555555552f7 in lyd_replace (target=0x5555555580b0 <running>, source=0x555555593cd0) at lyd_replace2.c:26
#4  0x0000555555555478 in commit (xpath=0x5555555560f0 "/frr-isisd:isis/instance[area-tag='1']/multi-topology/ipv6-unicast", value=0x0) at lyd_replace2.c:72
#5  0x00005555555555a1 in main (argc=1, argv=0x7fffffffe938) at lyd_replace2.c:99
(gdb) l
4244                    if (elem->parent == node->parent) {
4245                        /* we are done, back in start node */
4246                        break;
4247                    }
4248                    /* parent was actually already processed, so go to the parent's sibling */
4249                    next = elem->parent->next;
4250                }
4251            }
4252        }
4253    
(gdb) p elem
$1 = (struct lyd_node *) 0x555555593680
(gdb) p elem->parent
$2 = (struct lyd_node *) 0x0
```

Yang module: https://raw.githubusercontent.com/FRRouting/frr/master/yang/frr-isisd.yang

This time the problem happens even with `-DENABLE_CACHE=off`. I'm using libyang 1.0.130 but the problem also occurs using the latest version from `devel`.

Any help would be appreciated!

**Comment by michalvasko** [comment]
Hi Renato,
should work now.

Regards,
Michal

**Comment by rwestphal** [comment]
I confirm the problem is gone. After opening this issue I found dozens of similar crashes using the FRR CLI fuzzer, now it's all clear. Thank you very much!
