### ISSUE TITLE
lyd_diff() issue comparing identical data trees

### ISSUE THREAD

**Issue by rwestphal** [CESNET/libyang#1048]
I think I've encountered a bug in libyang while investigating this FRR issue: https://github.com/FRRouting/frr/issues/5718

The problem is that under some very specific conditions `lyd_diff()` is returning a pair of DELETED/CREATED changes when comparing identical configurations.

I've written this test program to reproduce the issue (it more or less simulates what FRR does): https://gist.github.com/rwestphal/2663b33c9b13a6c14ab5f0fd247c0280

And here's the test output:
```
# ./lyd_diff_issue
Editing candidate: /frr-interface:lib/interface[name='eth0'][vrf='default']
Committing candidate...
 LYD_DIFF_CREATED: xpath: /frr-interface:lib/interface[name='eth0'][vrf='default']

Editing candidate: /frr-interface:lib/interface[name='eth1'][vrf='default']
Committing candidate...
 LYD_DIFF_CREATED: xpath: /frr-interface:lib/interface[name='eth1'][vrf='default']

Editing candidate: /frr-interface:lib/interface[name='eth2'][vrf='default']
Committing candidate...
 LYD_DIFF_CREATED: xpath: /frr-interface:lib/interface[name='eth2'][vrf='default']

Editing candidate: /frr-interface:lib/interface[name='eth3'][vrf='default']
Committing candidate...
 LYD_DIFF_CREATED: xpath: /frr-interface:lib/interface[name='eth3'][vrf='default']

Updating the running configuration directly...
Regenerating the candidate config from the running config...

Comparing running vs candidate (identical configs)...
 LYD_DIFF_DELETED: xpath: /frr-interface:lib/interface[name='eth0'][vrf='vrf0']
 LYD_DIFF_CREATED: xpath: /frr-interface:lib/interface[name='eth0'][vrf='vrf0']

Exiting...
```

What this program does is the following:
1 - Create four interfaces in the running configuration (each of them committed separately through a candidate configuration);
2 - Edit the VRF of the first interface directly in the running configuration (bypassing the normal transactional process). The `lyd_change_leaf()` API is used for that purpose.
3 - Regenerate the candidate configuration from the running configuration.
4 - Compare the running and candidate configurations.

In the fourth step, we expect `lyd_diff()` to return nothing since both configurations are identical. However, that's not what happens as you can see in the output above.

This problem doesn't happen when libyang is built with `-DENABLE_CACHE=OFF`. Curiously, the problem doesn't happen as well if we create less than four interfaces in the running configuration.

Step nº 2 is certainly what's triggering the problem. It's an ugly thing we need to do in FRR to handle configuration changes coming from the kernel (in which case a transaction wouldn't make sense, since the configuration change already happened and can't be rejected).

I'm using the latest libyang from the `devel` branch, but the problem also occurs on 0.16-r3.

Any help would be appreciated!

**Comment by michalvasko** [comment]
Hi Renato,
right, there was a problem with hashes and it does not manifest with less than 4 interfaces because hashes are used only when there are at least 4 children. But it should be fixed now.

Regards,
Michal

**Comment by rwestphal** [comment]
Thanks a lot Michal! I confirm the issue is gone using the latest changes.
