### ISSUE TITLE
require-instance error

### ISSUE THREAD

**Issue by miroslavKovacPantheon** [CESNET/libyang#1049]
Hi,

if I am parsing [ietf-notification-capabilities@2020-03-23.yang](https://raw.githubusercontent.com/YangModels/yang/699c35ba907669dc4185ef6f9767b84b1202053c/experimental/ietf-extracted-YANG-modules/ietf-notification-capabilities@2020-03-23.yang) yang module using yanglint it gives me an error err : Invalid keyword "require-instance". this is the output of yanglint

> err : Invalid keyword "require-instance".
> err : Module "ietf-subscribed-notifications" parsing failed.
> err : Importing "ietf-subscribed-notifications" module into "ietf-yang-push" failed.
> err : Module "ietf-yang-push" parsing failed.
> err : Importing "ietf-yang-push" module into "ietf-notification-capabilities" failed.
> err : Module "ietf-notification-capabilities" parsing failed.
> warn: String "Enables objects to be added to a configured stream
> subscription." not freed from the dictionary, refcount 1
> warn: String "If there is at least one event in the replay buffer
> prior to 'replay-start-time', this gives the time of
> the event generated immediately prior to the
> 'replay-start-time'.
> 
> If a receiver previously received event records for
> this configured subscription, it can compare this time
> to the last event record previously received.  If the
> two are not the same (perhaps due to a reboot), then a
> dynamic replay can be initiated to acquire any missing
> event records." not freed from the dictionary, refcount 1
> warn: String "configured-replay" not freed from the dictionary, refcount 1
> warn: String "yang:date-and-time" not freed from the dictionary, refcount 1
> warn: String "empty" not freed from the dictionary, refcount 1
> warn: String "target/stream" not freed from the dictionary, refcount 2
> warn: String "../replay-start-time" not freed from the dictionary, refcount 1
> warn: String "The presence of this leaf indicates that replay for
> the configured subscription should start at the
> earliest time in the event log or at the publisher
> boot time, whichever is later." not freed from the dictionary, refcount 1
> warn: String "This augmentation adds additional parameters specific to a
> 'subscription-started' notification." not freed from the dictionary, refcount 1
> warn: String "replay-previous-event-time" not freed from the dictionary, refcount 1

 This error comes from the (recursive) imported modules and I believe it is [this](https://raw.githubusercontent.com/YangModels/yang/699c35ba907669dc4185ef6f9767b84b1202053c/standard/ietf/RFC/ietf-subscribed-notifications@2019-09-09.yang) module that has some problems. The typedef stream-ref

```
  typedef stream-ref {
    type leafref {
      path "/sn:streams/sn:stream/sn:name";
    }
    description
      "This type is used to reference a system-provided
       event stream.";
  }
```
derives a leafref this type is then used in the grouping leaf statement 
```
 leaf stream {
          type stream-ref {
            require-instance false;
          }
          mandatory true;
          description
            "Indicates the event stream to be considered for
             this subscription.";
        }
```

and require-instance is set to false which is I guess wrongly evaluated as error since type is not leafref or instance-identifier but stream-ref. 

it looks like it is similar to issue #881. But since that is closed and I think we are using yanglint where this fix was already implemented I am opening a new one. our version is `yanglint SO 1.4.1`

**Comment by michalvasko** [comment]
Hi,
it is [being discussed](https://mailarchive.ietf.org/arch/msg/netconf/GD_-iW3HWSqkWfyLjsH5U5W8agY/). After the errata are accepted, *libyang* will be changed and this module should be possible to load.

Regards,
Michal

**Comment by miroslavKovacPantheon** [comment]
So I ve heared after I opened this issue. thank you at least you can track your change on the github as well. Sorry for opening this issue. :)

**Comment by michalvasko** [comment]
Supported now based on the discussion in the mailing list.

Regards,
Michal
