### ISSUE TITLE
APIs lyd_parse_path()/lyd_parse_fd()/lyd_parse_mem() returns NULL in case of an error not exact failure cause code

### ISSUE THREAD

**Issue by shishirpandey29** [CESNET/libyang#1050]
Hello,

APIs lyd_parse_path()/lyd_parse_fd()/lyd_parse_mem() returns NULL and does not return exact failure cause code that caused problem.

is this possible to know exact failure cause code by the application when these API returns NULL. 

My requirement is :
if application calls  lyd_parse_path() and lyd_parse_path() returns NULL then I would like to know exact failure cause code like it failed because number of instances  in a list  are more than MAX_ELEMENT of a list.

**Comment by fredgan** [comment]
You can use `ly_vecode` to get the exact error.

```c
LY_VECODE err_code = ly_vecode(ctx);
```
ENUM type `LY_VECODE` is defined in `src/libyang.h.in`

**Comment by michalvasko** [comment]
Hi,
that is not exact. You should first check `ly_errno` and you will learn the error code of the problem. If it is `LY_EVALID`, there was a validation problem that you can learn more about by learning the exact validation error code as @fredgan mentioned, for example.

Regards,
Michal
