### ISSUE TITLE
support for old glibc

### ISSUE THREAD

**Issue by MruRhe** [CESNET/libyang#1053]
Dear libyang team,

I would like to build and link libyang (Linking C executable yangre) on an old system with no support for:

- libyang.so.1.6.7: undefined reference to `le64toh'

- libyang.so.1.6.7: undefined reference to `htole64'

It would be very helpful If you could implement a switch for an old glibc.

configured with:
export CMAKE_PREFIX_PATH=/opt/pcre-latest/
DIR=$(pwd)/inst
export DESTDIR=$DIR
cmake   -DCMAKE_INSTALL_PREFIX="/usr" \
        -DPLUGINS_DIR:PATH="/usr/src/extensions/" \
        -DCMAKE_VERBOSE_MAKEFILE=TRUE \
        ../

Thx in advance!

**Comment by michalvasko** [comment]
Hi,
so I have added our own implementation of these functions because there is no even remotely portable alternative available anyway.

Regards,
Michal

**Comment by MruRhe** [comment]
Thx a lot, the devel branch can be build with no probs.
