### ISSUE TITLE
XML parsing error

### ISSUE THREAD

**Issue by CC-vga** [CESNET/libyang#1057]
Hello, 

I'm using netopeer2-server (v 1.1.7) that is called by a ncclient from a Windows environment. 
  When I try to make an RPC edit-config request I get the following error (I'll add also some info lines if relevant):
...
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: LN: Accepted a connection on 0.0.0.0:830.
[INF]: SR: Session 2 (user "root") created.
[2020/04/07 08:16:30.195402, 2] ssh_pki_import_privkey_base64:  Trying to decode privkey passphrase=false
[2020/04/07 08:16:30.210890, 1] ssh_server_connection_callback:  SSH client banner: SSH-2.0-paramiko_2.4.2
[2020/04/07 08:16:30.211127, 1] ssh_analyze_banner:  Analyzing banner: SSH-2.0-paramiko_2.4.2
[2020/04/07 08:16:30.336840, 2] ssh_server_ecdh_init:  SSH_MSG_KEXDH_REPLY sent
[2020/04/07 08:16:30.337054, 2] ssh_server_ecdh_init:  SSH_MSG_NEWKEYS sent
[2020/04/07 08:16:30.341247, 2] ssh_packet_newkeys:  Received SSH_MSG_NEWKEYS
[INF]: LN: Received an SSH message "request-service" of subtype "ssh-userauth".
[INF]: LN: Received an SSH message "request-auth" of subtype "password".
[INF]: LN: User "mnc" authenticated.
[INF]: LN: Received an SSH message "request-channel-open" of subtype "session".
[INF]: LN: Received an SSH message "request-channel" of subtype "subsystem".
[2020/04/07 08:16:30.357744, 2] grow_window:  growing window (channel 43:0) to 1280000 bytes
[INF]: SR: Session 3 (user "root") created.
[INF]: SR: There are no subscribers for "ietf-netconf-notifications" notifications.
[INF]: NP: Generated new event (netconf-session-start).
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Session 4 (user "root") created.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" with ID 1 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:get-config" "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: There is no leafref "/ietf-keystore:keystore/ietf-keystore:asymmetric-keys/ietf-keystore:asymmetric-key/ietf-keystore:name" with the value "genkey", but it is not required.
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Finished processing "rpc" event with ID 1 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 1 priority 0 succeeded.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: NP: Session 1: thread 0 event new RPC.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Session 5 (user "root") created.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" with ID 1 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:edit-config" "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
[ERR]: LY: Internal error (/home/voga/netopeer-server/libyang/src/parser.c:1180).
[ERR]: SR: Failed to truncate shared memory (Invalid argument).
Could you help me please to isolate the problem or even solve it? I have the impression that the XML is well formatted; all elements are prefixed with their namespace prefix. Unfortunately  from the error message I cannot see what goes wrong. 

All best
Voica

**Comment by michalvasko** [comment]
Hi,
could you try running the server with `-c MSG` so that the actual XML is seen? Thanks.

Regards,
Michal

**Comment by CC-vga** [comment]
Hi, 

This was a quick reaction, thanks!
When I run the server with any type of category I get segmentation fault after loading the yang models...

All best
Voica

**Comment by michalvasko** [comment]
Hi,
then I can only assume you have something really broken in your installation and I cannot help you with that.

Regards,
Michal

**Comment by CC-vga** [comment]
Sorry, now the stack looks like this:
...
[INF]: NP: Session 1: thread 3 event new RPC.
[DBG]: LN: PS 0x0x7fffeb085dc0 TID 140292220978944 queue: added 0, head 0, lenght 1
[DBG]: LN: PS 0x0x7fffeb085dc0 TID 140292220978944 queue: removed 0, head 0, lenght 0
[DBG]: LN: PS 0x0x7fffeb085dc0 TID 140292212524800 queue: added 0, head 0, lenght 1
[DBG]: LN: PS 0x0x7fffeb085dc0 TID 140292212524800 queue: removed 0, head 0, lenght 0
[DBG]: LN: PS 0x0x7fffeb085dc0 TID 140292299491072 queue: added 0, head 0, lenght 1
[DBG]: LN: PS 0x0x7fffeb085dc0 TID 140292299491072 queue: removed 0, head 0, lenght 0
[DBG]: LN: Session 1: received message:
<?xml version="1.0" encoding="UTF-8"?><nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:dot1q="urn:ieee:std:802.1Q:yang:ieee802-dot1q-bridge" xmlns:sfsg="urn:ieee:std:802.1Q:yang:ieee802-dot1q-stream-filters-gates" xmlns:psfp="urn:ieee:std:802.1Q:yang:ieee802-dot1q-psfp" message-id="urn:uuid:2acf1dbe-27d8-4438-ba97-b1e4b6608a75"><nc:edit-config><nc:target><nc:candidate/></nc:target><nc:error-option>rollback-on-error</nc:error-option><nc:config><dot1q:bridges><dot1q:bridge><dot1q:name>Sw1</dot1q:name><dot1q:address>00-95-f8-ce-a1-01</dot1q:address><dot1q:bridge-type>customer-vlan-bridge</dot1q:bridge-type><dot1q:component><dot1q:name>ES1-Sw1</dot1q:name><dot1q:type>c-vlan-component</dot1q:type><sfsg:stream-filters><sfsg:stream-filter-instance-table><sfsg:stream-filter-instance-id>0</sfsg:stream-filter-instance-id><sfsg:stream-handle>1</sfsg:stream-handle><sfsg:priority-spec>one</sfsg:priority-spec><sfsg:filter-specification-list><sfsg:index>0</sfsg:index><sfsg:maximum-sdu-size>1500</sfsg:maximum-sdu-size><sfsg:stream-blocked-due-to-oversize-frame-enabled>true</sfsg:stream-blocked-due-to-oversize-frame-enabled></sfsg:filter-specification-list><sfsg:filter-specification-list><sfsg:index>1</sfsg:index><psfp:flow-meter-ref>0</psfp:flow-meter-ref></sfsg:filter-specification-list></sfsg:stream-filter-instance-table></sfsg:stream-filters><psfp:flow-meters><psfp:flow-meter-instance-table><psfp:flow-meter-instance-id>0</psfp:flow-meter-instance-id><psfp:committed-information-rate>666</psfp:committed-information-rate><psfp:committed-burst-size>4500</psfp:committed-burst-size><psfp:excess-information-rate>800</psfp:excess-information-rate><psfp:excess-burst-size>5400</psfp:excess-burst-size><psfp:coupling-flag>zero</psfp:coupling-flag><psfp:color-mode>color-aware</psfp:color-mode><psfp:drop-on-yellow>false</psfp:drop-on-yellow></psfp:flow-meter-instance-table></psfp:flow-meters></dot1q:component><dot1q:component><dot1q:name>ES2-Sw1</dot1q:name><dot1q:type>c-vlan-component</dot1q:type><sfsg:stream-filters><sfsg:stream-filter-instance-table><sfsg:stream-filter-instance-id>0</sfsg:stream-filter-instance-id><sfsg:stream-handle>2</sfsg:stream-handle><sfsg:priority-spec>two</sfsg:priority-spec><sfsg:stream-gate-ref>0</sfsg:stream-gate-ref><sfsg:filter-specification-list><sfsg:index>0</sfsg:index><sfsg:maximum-sdu-size>4500</sfsg:maximum-sdu-size><sfsg:stream-blocked-due-to-oversize-frame-enabled>true</sfsg:stream-blocked-due-to-oversize-frame-enabled></sfsg:filter-specification-list></sfsg:stream-filter-instance-table></sfsg:stream-filters><sfsg:stream-gates><sfsg:stream-gate-instance-table><sfsg:stream-gate-instance-id>0</sfsg:stream-gate-instance-id><sfsg:gate-enable>true</sfsg:gate-enable><sfsg:admin-gate-states>closed</sfsg:admin-gate-states><sfsg:admin-ipv>two</sfsg:admin-ipv><psfp:admin-control-list-length>4</psfp:admin-control-list-length><psfp:admin-control-list><psfp:index>1</psfp:index><psfp:operation-name>set-gate-and-ipv</psfp:operation-name><psfp:parameters><psfp:gate-state-value>open</psfp:gate-state-value><psfp:ipv-value>two</psfp:ipv-value><psfp:time-interval-value>1</psfp:time-interval-value><psfp:interval-octet-max>4500</psfp:interval-octet-max></psfp:parameters></psfp:admin-control-list><psfp:admin-control-list><psfp:index>2</psfp:index><psfp:operation-name>set-gate-and-ipv</psfp:operation-name><psfp:parameters><psfp:gate-state-value>closed</psfp:gate-state-value><psfp:ipv-value>two</psfp:ipv-value><psfp:time-interval-value>10241</psfp:time-interval-value></psfp:parameters></psfp:admin-control-list><psfp:admin-control-list><psfp:index>3</psfp:index><psfp:operation-name>set-gate-and-ipv</psfp:operation-name><psfp:parameters><psfp:gate-state-value>open</psfp:gate-state-value><psfp:ipv-value>two</psfp:ipv-value><psfp:time-interval-value>29758</psfp:time-interval-value><psfp:interval-octet-max>4500</psfp:interval-octet-max></psfp:parameters></psfp:admin-control-list><psfp:admin-control-list><psfp:index>4</psfp:index><psfp:operation-name>set-gate-and-ipv</psfp:operation-name><psf
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[DBG]: LN: PS 0x0x7fffeb085dc0 TID 140292307945216 queue: added 0, head 0, lenght 1
[DBG]: LN: PS 0x0x7fffeb085dc0 TID 140292307945216 queue: removed 0, head 0, lenght 0
[DBG]: LN: PS 0x0x7fffeb085dc0 TID 140292402579328 queue: added 0, head 0, lenght 1
[DBG]: LN: PS 0x0x7fffeb085dc0 TID 140292402579328 queue: removed 0, head 0, lenght 0
[ERR]: LY: Internal error (/home/voga/netopeer-server/libyang/src/parser.c:1180).

All best
Voica

**Comment by michalvasko** [comment]
Hi,
okay, I think I know what the problem is. Please use the latest *libyang* from `devel` and try again, the exact error should now be printed. Note that there is an issue in the XML received and not in *libyang* or *netopeer2*.

Regards,
Michal

**Comment by CC-vga** [comment]
Thank you very much, it tells me now the problematic XML fragment :)

All best
