### ISSUE TITLE
EOVERFLOW with yangre

### ISSUE THREAD

**Issue by apropp-molex** [CESNET/libyang#1061]
When running the following command `yangre --verbose -p 'te.*xt' text_text`, I get the following output (changed strerror to errno):
```sh
libyang[1]: Unable to get information about "proc" file in "/" when searching for (sub)modules (79)
libyang[1]: Unable to get information about "proc" file in "/" when searching for (sub)modules (79)
libyang[1]: Unable to get information about "proc" file in "/" when searching for (sub)modules (79)
pattern  1: te.*xt
matching 1: regular
string    : text_text
result    : matching
```
79 corresponds to `EOVERFLOW`. This makes sense as the `proc` directory is quite large as evidenced by this `ls -ll`:
```
# ls -ll
total 2033350
drwxr-xr-x   2 0         0                40 Apr 13  2020 bin
drwxr-xr-x   2 0         0                10 Apr 13  2020 dev
drwxr-xr-x   2 0         0                20 Apr 13  2020 lib
dr-xr-xr-x   2 0         0         1041072128 Jan 01 00:04 proc
drwxr-xr-x   2 0         0                10 Apr 13  2020 sbin
lrwxrwxrwx   1 0         0                10 Apr 13  2020 tmp -> /dev/shmem
drwxr-xr-x   2 0         0                10 Apr 13  2020 usr
```
The root of this issue is because `yangre` executed in the root directory `/` and therefore appended `proc` to its search path while executing the function `lys_search_localfile`. It also doesn't help that the system is ARM 32-bit. My question is would it be possible to suppress this warning specifically by not appending files to the search path if they are overly large? Looking forward to hearing your thoughts on this.

**Comment by michalvasko** [comment]
Hi,
the warning you see is generated by a call to `stat(2)` and it is impossible to determine whether the call will fail beforehand. The only fix I can think of would be to ignore this specific `errno` but I am not sure what the purpose would be. You can disable warnings if you do not want them but I think the warning is simply relevant. You probably should not be executing `yangre` in root.

Regards,
Michal

**Comment by apropp-molex** [comment]
Hi Michal,

I agree, probably shouldn't be executing `yangre` in root. Thanks for your reply.
