### ISSUE TITLE
how to change xml to lyb format(yanglint)?

### ISSUE THREAD

**Issue by zyboy2000** [CESNET/libyang#1064]
how to change xml to lyb format using yanglint?thanks!

**Comment by michalvasko** [comment]
Hi,
just load the file and print it in a different format. The command is
```
data -t config -F lyb -f xml -o datastore.xml datastore.lyb
```
It will basically convert LYB configuration file `datastore.lyb` to XML file `datastore.xml`.

Regards,
Michal
