### ISSUE TITLE
lytype_store_clb set a default value

### ISSUE THREAD

**Issue by LoveCPro** [CESNET/libyang#1069]
In ietf-ipv4-unicast-routing.yang, I give the destination-prefix is "192.168.10.0/24", but,after lytype_find() and store_clb->lytype_store_clb(in plugins.c),it  has changs to "255.255.255.0/24",I donot know how it is to chang this.

**Comment by michalvasko** [comment]
Hi,
what *libyang* version are you using? I think this was fixed quite some time ago.

Regards,
Michal
