### ISSUE TITLE
Whether to replace malloc with calloc or zero memory allocated?

### ISSUE THREAD

**Issue by foxge** [CESNET/libyang#1075]
https://github.com/CESNET/libyang/blob/1b7d73d442dc58e1feec6d518372e0aaccebca37/src/tree_data.c#L5301

**Comment by michalvasko** [comment]
Hi,
I guess it may have potentially caused some problems because `value` was left uninitialized. Should be fine now and please be a bit more verbose next time.

Regards,
Michal
