### ISSUE TITLE
Sometimes, attr->name is null pointer in myself application

### ISSUE THREAD

**Issue by foxge** [CESNET/libyang#1076]
https://github.com/CESNET/libyang/blob/1b7d73d442dc58e1feec6d518372e0aaccebca37/src/parser_xml.c#L353

unfortunately, I could not find out bug and fix it, did everyone have same problems ?

**Comment by michalvasko** [comment]
Hi,
if you could provide the XML that caused it, it should be easy to reproduce.

Regards,
Michal
