### ISSUE TITLE
Notification with colon(:) in key/name attribute do cause a segfault   

### ISSUE THREAD

**Issue by berstrob** [CESNET/libyang#1077]
Hi,
i tried the notification feature for Netopeer2 with a fairly recent devel , it works as expect as long as i did not change properties like this: 
`/openconfig-platform:components/component[name='CHN-1-3:PORT']/properties/property[name='adminstate']/config/value`

without the ":" does work:
`
/openconfig-platform:components/component[name='CHN-1-3PORT']/properties/property[name='adminstate']/config/value`

I tried a bit to track it down and it seemed to be caused by something in [_transform_json2xml_subexp](https://github.com/CESNET/libyang/blob/devel/src/common.c)

it only uses this if  `else if ((exp->tokens[i] == LYXP_TOKEN_LITERAL) && (end = strnchr(cur_expr, ':', exp->tok_len[i])))` with the colon in it and then some how does mess up the size counting, i have to admit i did not try to understand the code more at this point.

I hope it helps to narrow it down, the core dump /gdb was not  very helpful but maybe a few of my added prints they even got me a "better error":

```
[INF]: LY: inst: /openconfig-platform:components/component[name='CHN-1-3:PORT']/properties/property[name='adminstate']/config/value
[INF]: LY: curr_expre: /openconfig-platform:components/component[name='CHN-1-3:PORT']/properties/property[name='adminstate']/config/value
[INF]: LY: else outused 0 0 1
[INF]: LY: curr_expre: openconfig-platform:components/component[name='CHN-1-3:PORT']/properties/property[name='adminstate']/config/value
[INF]: LY: if 2
[INF]: LY: curr_expre: /component[name='CHN-1-3:PORT']/properties/property[name='adminstate']/config/value
[INF]: LY: else outused 23 31 1
[INF]: LY: curr_expre: component[name='CHN-1-3:PORT']/properties/property[name='adminstate']/config/value
[INF]: LY: if 2
[INF]: LY: curr_expre: [name='CHN-1-3:PORT']/properties/property[name='adminstate']/config/value
[INF]: LY: else outused 45 41 1
[INF]: LY: curr_expre: name='CHN-1-3:PORT']/properties/property[name='adminstate']/config/value
[INF]: LY: if 2
[INF]: LY: curr_expre: ='CHN-1-3:PORT']/properties/property[name='adminstate']/config/value
[INF]: LY: else outused 62 46 1
[INF]: LY: curr_expre: 'CHN-1-3:PORT']/properties/property[name='adminstate']/config/value
[INF]: LY: if 3
[INF]: LY: curr_expre: ]/properties/property[name='adminstate']/config/value
[INF]: LY: else outused 77 61 1
[INF]: LY: curr_expre: /properties/property[name='adminstate']/config/value
[INF]: LY: else outused 78 62 1
[INF]: LY: curr_expre: properties/property[name='adminstate']/config/value
[INF]: LY: if 2
netopeer2-server: malloc.c:3723: _int_malloc: Assertion `(unsigned long) (size) >= (unsigned long) (nb)' failed.
Aborted (core dumped)


```

The if are numbered toplevel in the   `for (i = 0; i < exp->used; ++i)`  (at the start curr_expre is printed) and the else (would be "if 4")  is `LOGVRB("else outused %zu %zu %zu",*out_used,exp->expr_pos[i],exp->tok_len[i]);`

good:
```
[INF]: LY: inst: /openconfig-platform:components/component[name='CHH-1-3PORT']/properties/property[name='adminstate']/config/value
[INF]: LY: curr_expre: /openconfig-platform:components/component[name='CHH-1-3PORT']/properties/property[name='adminstate']/config/value
[INF]: LY: else outused 0 0 1
[INF]: LY: curr_expre: openconfig-platform:components/component[name='CHH-1-3PORT']/properties/property[name='adminstate']/config/value
[INF]: LY: if 2
[INF]: LY: curr_expre: /component[name='CHH-1-3PORT']/properties/property[name='adminstate']/config/value
[INF]: LY: else outused 23 31 1
[INF]: LY: curr_expre: component[name='CHH-1-3PORT']/properties/property[name='adminstate']/config/value
[INF]: LY: if 2
[INF]: LY: curr_expre: [name='CHH-1-3PORT']/properties/property[name='adminstate']/config/value
[INF]: LY: else outused 45 41 1
[INF]: LY: curr_expre: name='CHH-1-3PORT']/properties/property[name='adminstate']/config/value
[INF]: LY: if 2
[INF]: LY: curr_expre: ='CHH-1-3PORT']/properties/property[name='adminstate']/config/value
[INF]: LY: else outused 62 46 1
[INF]: LY: curr_expre: 'CHH-1-3PORT']/properties/property[name='adminstate']/config/value
[INF]: LY: else outused 63 47 13
[INF]: LY: curr_expre: ]/properties/property[name='adminstate']/config/value
[INF]: LY: else outused 76 60 1
[INF]: LY: curr_expre: /properties/property[name='adminstate']/config/value
[INF]: LY: else outused 77 61 1
[INF]: LY: curr_expre: properties/property[name='adminstate']/config/value
[INF]: LY: if 2
[INF]: LY: curr_expre: /property[name='adminstate']/config/value
[INF]: LY: else outused 100 72 1
[INF]: LY: curr_expre: property[name='adminstate']/config/value
[INF]: LY: if 2
[INF]: LY: curr_expre: [name='adminstate']/config/value
[INF]: LY: else outused 121 81 1
[INF]: LY: curr_expre: name='adminstate']/config/value
[INF]: LY: if 2
[INF]: LY: curr_expre: ='adminstate']/config/value
[INF]: LY: else outused 138 86 1
[INF]: LY: curr_expre: 'adminstate']/config/value
[INF]: LY: else outused 139 87 12
[INF]: LY: curr_expre: ]/config/value
[INF]: LY: else outused 151 99 1
[INF]: LY: curr_expre: /config/value
[INF]: LY: else outused 152 100 1
[INF]: LY: curr_expre: config/value
[INF]: LY: if 2
[INF]: LY: curr_expre: /value
[INF]: LY: else outused 171 107 1
[INF]: LY: curr_expre: value
[INF]: LY: if 2
```

Best regards Bernd

**Comment by michalvasko** [comment]
Hi,
best would be some simple way of reproducing it, from what you wrote I am not sure I understand what you did. Simply used the string as instance-identifier in a notification? Also, `valgrind` output may be all that is needed as it should tell exactly where the problem occurs.

Regards,
Michal

**Comment by michalvasko** [comment]
Hi,
right, thanks for the hint to use the `netconf-config-change` notification, it is not used much. But I managed to reproduce it easily, so please update *libyang* and it should work then.

Regards,
Michal

**Comment by berstrob** [comment]
Hi,

yes works perfect now, thank you very much.

Regards,
Bernd

**Comment by dylan1019** [comment]
hi michalvasko and berstrob,
Could you please share which version fixes this issue, I am using 2.1.80, encountered an issue, when the key "mac-address" contains ':', then the below error reported.

Failed to add attribute /bbf-l2-forwarding:forwarding-state/forwarding-databases/forwarding-database[name='bridge-1-FWD-DATABASE']/mac-addresses/mac-address[mac-address=00:10:94:16:01:01]/mac-address. 

and the type of yang leaf "mac-address" is as below
  typedef mac-address {
    type string {
      pattern '[0-9a-fA-F]{2}(:[0-9a-fA-F]{2}){5}';
    }

**Comment by michalvasko** [comment]
I do not know what you are doing exactly but it seems you need to enclose `00:10:94:16:01:01` in `'`.

**Comment by dylan1019** [comment]
Hi michalvasko,
I think that is the reason causing the problem, thank you.
