### ISSUE TITLE
Schematree lookup fails when deviations reference an augmented container 

### ISSUE THREAD

**Issue by robshakir** [CESNET/libyang#1081]
Tested Versions:
* `yanglint 0.16.105`
* `yanglint SO 1.7.10` (`devel`@ `0599d13c142854215139580ba778ff2cbd23eb53`)

When a module augments the schema tree to add a subtree, and then references a node in the "augmented" subtree in a `deviation` statement, yanglint fails to resolve the augmented subtree. To concretise this example:

* module `deviation-base` defines a container `root`.
* module `deviation-add` augments `/root` with `/root/child`.
* module `deviation-add` subsequently deviates `/root/child` to mark a child `leaf a` `not-supported`.

The deviation statement fails stating that `/root/child` cannot be found in the schema tree. Other YANG toolchains - goyang and pyang - both handle this scenario correctly. 

This can be reproduced with the following minimal modules:

* filename: `deviate-base.yang`
```yang
module deviate-base {
	prefix "d";
	namespace "urn:d";
	
	container root {
	}
}
```

* filename: `deviate-add.yang`
```yang
module deviate-add {
	prefix "da";
	namespace "urn:da";

	import deviate-base { prefix "db"; }

	grouping top {
		container child { 
			leaf target { type string; }
		}
	}

	augment "/db:root" {
		uses top;
	}

	deviation "/db:root/da:child/da:target" {
		deviate not-supported;
	}
}
```

(Note, removing the `da` prefixes in the `deviation` statement does not fix this issue, even though they should not be required.)

**`yanglint` output:`**:
```
root@628efa18400b:~/yanglintbugs# yanglint deviate-base.yang deviate-add.yang 
err : Schema node not found. (/deviate-base:root/child)
err : Invalid value "/deviate-base:root/child/target" of "deviation".
err : Module "deviate-add" parsing failed.
```
This issue was discovered as part of a compatibility analysis project that we have been running in OpenConfig, led by @wenovus. Please let us know if there's any further details we can supply.

**Comment by michalvasko** [comment]
Hi,
I can only repeat what I wrote in #1080, we will not fix this as the cause is the same, you are effectively deviating nodes form your own module. But it should, again, work in *libyang* version 2.

Regards,
Michal
