### ISSUE TITLE
Module prefixes are not correctly resolved from a typedef.

### ISSUE THREAD

**Issue by robshakir** [CESNET/libyang#1082]
Tested Versions:
* `yanglint 0.16.105`
* `yanglint SO 1.7.10` (`devel`@ `0599d13c142854215139580ba778ff2cbd23eb53`)

If a module defines a `typedef` that has a `leafref` which references its own contents - and subsequently this `typedef` is used in a second module, `yanglint` cannot resolve the `path` in the `leafref`.

Minimum reproduction:
* filename: `typedef.yang`
```yang
module typedef {
	namespace "urn:t";
	prefix "t";
	
	container a {
		list b {
			key "c";
			leaf c { type string; }
		}
	}

	typedef cref {
		type leafref {
			path "/a/b/c";
		}
	}
}
```

* filename: `ref.yang`
```yang
module ref {
	namespace "urn:ref";
	prefix "r";

	import typedef { prefix t; }

	leaf reference {
		type t:cref;
	}
}
```

**`yanglint` output**:
```
root@628efa18400b:~/yanglintbugs# yanglint ref.yang 
err : No resolvents found for leafref "/a/b/c". (/ref:reference)
err : Module "ref" parsing failed.
```

This can be worked around by adding prefixes in the `path` for the `leafref` - but this should not be required. i.e., applying this patch:

```patch
--- typedef.yang	2020-05-07 06:01:22.957366356 +0000
+++ typedef-ok.yang	2020-05-07 06:03:22.216717333 +0000
@@ -11,7 +11,7 @@ module typedef {
 
 	typedef cref {
 		type leafref {
-			path "/a/b/c";
+			path "/t:a/t:b/t:c";
 		}
 	}
 }
```

Other YANG toolchains (goyang, pyang) resolve this leafref without the need for the prefixes in the path.

This problem was discovered as part of a compatibility check in OpenConfig, led by @wenovus. Please let us know if there are additional details we can provide.

**Comment by michalvasko** [comment]
Hi,
okay, should work in the latest `devel` version.

Regards,
Michal

**Comment by robshakir** [comment]
Thanks for the fix here, much appreciated.

Kind regards,
r.

**Comment by iwanb** [comment]
Wasn't the previous behavior the correct one?

The Yang 1.1 RFC says:
```
   The "path" XPath expression is conceptually evaluated in the
   following context, in addition to the definition in Section 6.4.1:

   o  If the "path" statement is defined within a typedef, the context
      node is the leaf or leaf-list node in the data tree that
      references the typedef.
```

and section 6.4.1 also confirms it:
```
   o  Names without a namespace prefix belong to the same namespace as
      the identifier of the current node.  Inside a grouping, that
      namespace is affected by where the grouping is used (see
      Section 7.13).  Inside a typedef, that namespace is affected by
      where the typedef is referenced.  If a typedef is defined and
      referenced within a grouping, the namespace is affected by where
      the grouping is used (see Section 7.13).
```

I'd expect it's to support something like this:

typedef.yang:
```
module typedef {
	namespace "urn:t";
	prefix "t";

	typedef cref {
		type leafref {
			path "../c/d";
		}
	}
}
```

ref.yang:
```
module ref {
	namespace "urn:ref";
	prefix "r";

	import typedef { prefix t; }

	list c {
		key "d";
		leaf d {
			type string;
		}
	}

	leaf reference {
		type t:cref;
	}
}
```

You should be able to move a type to a typedef in any module, this breaks that property.

**Comment by michalvasko** [comment]
It [works now](https://github.com/CESNET/libyang/blob/master/tests/utests/schema/test_tree_schema_compile.c#L1840) the way you described it, seems I have reverted by fix in the meantime. But note that the general agreement how this should behave is different from what is implied by the specs. Currently, it should work in the following way. Names **with a prefix** in typedef are resolved in the context of where the typedef is **defined**, meaning the module whose import prefixes are used to resolve the identifier is the one where the typedef is defined. Names **without a prefix** are resolved in the context of where the typedef is **used**. The former goes against the first spec snippet you cited.
