### ISSUE TITLE
"Refcount overflow detected, duplicating dictionary record" , when  libyang parsed netconf xml.

### ISSUE THREAD

**Issue by RogerYaozhenyu** [CESNET/libyang#1084]
hi, recently , i faced a hard reproduced issue. sometimes. after  a  long time netconf protocol security scanning by Synopsys defensics software, when we send a get-config rpc,  netconf server returned "unknown elment running"  , then i fund there were some logs such as below:
"Refcount overflow detected, duplicating dictionary record"
 i checked the file dict.c history.   i fund that dict.c had been replaced by hash_table.c   and  some bug had been fixed . so , i want to confirm , do you run into my issue before? thanks .

**Comment by michalvasko** [comment]
Hi,
I think you are using a really old *libyang* version and even though I do not think we have fixed any issue similar to what you described, it works differently in the current *libyang* so there is a good chance it would not occur.

Regards,
Michal

**Comment by RogerYaozhenyu** [comment]
yes, it's a  old libyang version which we are using.  
BTW, if we start to upgrade libyang. to solve this issue. which branch you prefer to suggest we choose?  thanks.

**Comment by michalvasko** [comment]
Hi,
that is up to you but currently they are almost the same, `master` and `devel`. If you want to always have the latest bugfixes you should use `devel` and pull regularly, that will also allow you to report any current issues as you encounter them. But if you simply want to avoid this one problem and use a stable version without any changes until the next release, take `master`.

Regards,
Michal

**Comment by RogerYaozhenyu** [comment]
Thanks for help.
