### ISSUE TITLE
grouping having a list w/o key (because it's intended to be used in a CF setting) fails validation, even when it's only used by a CF context.

### ISSUE THREAD

**Issue by kwatsen** [CESNET/libyang#1097]
Background: this came from my using the `errors` grouping from `ietf-restconf.yang`, where it is currently only used by a `yang-data` extension.  I'm using this grouping because I want to validate RESTCONF error messages now...

**Note:** using today's `devel` branch (i.e.:`yanglint SO 1.8.1`)

Given "test.yang":
```
module test {
  yang-version 1.1;
  namespace "urn:ietf:params:xml:ns:yang:test";
  prefix t;
  grouping g {
    list l1 {
      leaf l2 {
        type string;
      }
    }
  }
  uses g {
    refine l1 {
      config false;
    }
  }
}
```

`yanglint test.yang` generates this output:
``` 
err : Missing keyword "key" as a child to "list". (/test:l1)
err : Invalid value "g" of "uses". (/test:g)
err : Copying data from grouping failed. (/test:g)
err : Module "test" parsing failed.
```

Firstly, please note that simply removing the `uses` statement resolves the validation issue:
```
$ cat test.yang 
module test {
  yang-version 1.1;
  namespace "urn:ietf:params:xml:ns:yang:test";
  prefix t;
  grouping g {
    list l1 {
      leaf l2 {
        type string;
      }
    }
  }
}

$ yanglint test.yang
$ echo $?
0
```

Before for actually fixing the issue, I had to manually add `config false` into the grouping's definition:
```
$ cat test.yang 
module test {
  yang-version 1.1;
  namespace "urn:ietf:params:xml:ns:yang:test";
  prefix t;
  grouping g {
    list l1 {
      config false;
      leaf l2 {
        type string;
      }
    }
  }
  uses g;
}

$ yanglint test.yang
$ echo $?
0
```

**Comment by michalvasko** [comment]
Hi,
okay, should work now, I just hope I have not broken something else.

Regards,
Michal

**Comment by kwatsen** [comment]
The fix is good!   (but I'll let you close this issue...)

IDK about potential breakage, but I have a lot of models I compile periodically, so we'll see...

**Comment by michalvasko** [comment]
I looked at it a bit more afterwards and I think it should be okay.
