### ISSUE TITLE
lyd_parse_xml report no errors when the xml to be parsed without models

### ISSUE THREAD

**Issue by lumanyu180** [CESNET/libyang#1105]
Hi,  
    lyd_parse_xml return NULL , because the xml to be parsed without models. But it has no error infomations. So I don't know why it return NULL .  If it can report some error or warnings for debugging ?

  Thanks very much!

**Comment by michalvasko** [comment]
Hi,
please read the [docs](https://netopeer.liberouter.org/doc/libyang/master/group__parseroptions.html#gac946f3f23c3629ad83eb67d235624c3a).

Regards,
Michal

**Comment by lumanyu180** [comment]
Hi ,
   I use LYD_OPT_STRICT   flag, and it is ok now, i can get error msg with ly_errmsg.

  Thanks very much!
