### ISSUE TITLE
Possible leak with lyd_free_withsiblings ?

### ISSUE THREAD

**Issue by vishalearnz** [CESNET/libyang#1113]
Hi Michal,

I am trying to check the memory leaks in our codebase which uses libnetconf2 and libyang.
Libyang Version - 1.0.35
LibnetConf2 Version - 0.12.55
Os Used - Qnx

I tried to use get request of open-config system wherein the new nodes gets constructed using yang model and libnetconf/libyang api's and the details are mapped to database value and send back as a response to the get-request.

Although get request is working fine, but whenever I invoke the request , heap memory gets increased(consumed) but doesnot return back to previous state once get request execution is completed.
Once the data is sent back to the client using libnetconf api 'nc_server_reply_data' with flag NC_PARAMTYPE_CONST. I am using lyd_free_withsiblings for the node to get destructed and wipe out the data tree.

I also tried to check if its with the code issue at my end , wherein , I commented out the api's and subsequent code for creating of datatree , I saw no issue with respect to memory , it was not getting altered.

Can you pl tell me if I should use any other API of libnetconf2/libyang for this purpose? Also is there a way I can check on using which libyang api, leaks may be happening.

I used a simple shell script which runs at every 5 secs and displays the memory structure
Following is the result of running the shell script before and after get-request
Process listing (Total, Code, Data, Heap, Stack, Other)
 29708288   23674880     978944    4448256     143360     462848  1126191145 netconfAgentQnx
Shared shared objects (Total, Code, Data, Heap, Stack, Other)
Process listing (Total, Code, Data, Heap, Stack, Other)
 29741056   23674880     978944    4481024     143360     462848  1126191145 netconfAgentQnx

Thanks & Regards,
Vishal

PS: I cant attach any debugger/memory leak tool as the OS is a little old with no support of any tool

**Comment by michalvasko** [comment]
Hi Vishal,
I am not sure I can help you much but I think the problem may have been fixed in recent *libnetconf2* (such as [this](https://github.com/CESNET/libnetconf2/commit/5a2c716e7c16ea525ed511273f28e689773bdc6e) commit). Generally, if you are using these obsolete versions, you are on your own.

Regards,
Michal
