### ISSUE TITLE
Problems encountered during cross compilation.

### ISSUE THREAD

**Issue by kuailedeluojie-sudo** [CESNET/libyang#1117]
When I configure the cross environment, I will be prompted:
![image](https://user-images.githubusercontent.com/60098441/85198166-f50bce00-b318-11ea-9ebb-c4623d53fa73.png)
Appears when using the make command:
![image](https://user-images.githubusercontent.com/60098441/85198176-1076d900-b319-11ea-8513-9e8d623709b3.png)
I don't know why. I see these functions in the source code.
![image](https://user-images.githubusercontent.com/60098441/85198193-3d2af080-b319-11ea-82e9-86c89aab5760.png)

**Comment by michalvasko** [comment]
Hi,
I am not able to help you with cross-compilation at all.

Regards,
Michal
