### ISSUE TITLE
Question about instance-identifier

### ISSUE THREAD

**Issue by gitter-runner** [CESNET/libyang#1123]
Hi!

When trying to edit an _instance-identifier_ with a value of an _instance-identifier_ node, libyang throws an error (probably the XML parser).

Is this working as intended (an _instance-identifier_ shouldn't have the value of another _instance-identifier_), or is this a bug?

I tried to decypher _RFC7950_, if there's a restriction like this on the _instance-identifier_ type, but to me it seemed like the standard allows it. Thought it's worth a question, maybe I just misinterpreted it.

How to reproduce:
(I attached the relevant YANG files)

After enabling the 'advanced-testing' feature in the test module send the following RPC:

```
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:t2="urn:com:test2"
xmlns:t3="urn:com:test3"
     message-id="1">
  <edit-config>
    <target>
      <running/>
    </target>
    <config>
      <basics xmlns="urn:com:test">
        <subbasics>
          <link xmlns="urn:com:test2"
xmlns:t="urn:com:test">/t:advanced/t3:double_indirection</link>
        </subbasics>
      </basics>
    </config>
  </edit-config>
</rpc>

```
I've received the following results:

```
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="20">
  <rpc-error>
    <error-type>application</error-type>
    <error-tag>operation-failed</error-tag>
    <error-severity>error</error-severity>
    <error-path>/test:basics/subbasics/test2:link</error-path>
    <error-message xml:lang="en">Invalid value "/t:advanced/t3:double_indirection" in "link" element.</error-message>
  </rpc-error>
</rpc-reply>
```

This is reproducable with the latest devel sysrepo, libyang, libnetconf2, netopeer2 versions.

[test_yang.txt](https://github.com/CESNET/libyang/files/4825972/test_yang.txt)
[test2_yang.txt](https://github.com/CESNET/libyang/files/4825973/test2_yang.txt)
[test3_yang.txt](https://github.com/CESNET/libyang/files/4825974/test3_yang.txt)

Thanks!

**Comment by michalvasko** [comment]
Hi,
there was a problem with copying all the XML namespaces correctly, should work now.

Regards,
Michal
