### ISSUE TITLE
assert in yanglint

### ISSUE THREAD

**Issue by alex4747-pub** [CESNET/libyang#1130]
I had  a few yanglint crashed in older no-debug built.

I cloned libyang today, built it with debug, run 'yanglint --check' got assert:

yanglint: /home/ar/build_for_install/libyang/src/tree_schema.c:4928: lys_make_implemented_r: Assertion `module->augment[i].target' failed.

Update: the underlying reason is that there is an augmentation for a non-existing table. IMHO, it should be handled - I am using yanglint exactly with the purpose of finding such issues.

**Comment by michalvasko** [comment]
Hi,
please provide the module so that we can reproduce it but I am not sure about your `--check` parameter, to my knowledge there is no such parameter and never was.

Regards,
Michal

**Comment by alex4747-pub** [comment]
Sorry I could not share private modules - and regardless of modules the thing should not crash.

**Comment by michalvasko** [comment]
Hi,
I asked for the modules so that I can reproduce it and based on that fix the problem, I am unable to do so without it and am not saying it is the modules' fault, of course it isn't. But if you cannot even send me the modules by mail then I cannot help you, there is little information to go on.

Regards,
Michal

**Comment by alex4747-pub** [comment]
Sorry, it will take time to prepare modules. However, it seems to me that it is relatively easy to fix it - you have to check for this condition in the caller and simply raise an error or raise an error and exit from linter.

**Comment by michalvasko** [comment]
There is enough time and it maybe as simple to fix as you say but maybe the situation should not even occur at all and there is some underlying problem that needs to be fixed, I cannot know unless I can reproduce it.

**Comment by alex4747-pub** [comment]
I believe it is some screw up in the modules - e.g. I am augmenting non-existing node so exiting on this error is enough. Ok will try to figure out test modules.

**Comment by alex4747-pub** [comment]
Files
[libynag-fix.tar.gz](https://github.com/CESNET/libyang/files/4858091/libynag-fix.tar.gz)

**Comment by michalvasko** [comment]
Hi,
okay, should not crash anymore.

Regards,
Michal

**Comment by alex4747-pub** [comment]
Thank you.
