### ISSUE TITLE
libyang2: invalid free in lyd_parse_xml_data cleanup

### ISSUE THREAD

**Issue by jvijtiuk** [CESNET/libyang#1131]
Hello,

the file attached below causes an invalid free and crashes the lyd_parse_mem harness in #1126.
[crash2.zip](https://github.com/CESNET/libyang/files/4848802/crash2.zip)

The issue seems to be related to the union inside lyxml_ctx, with value and prefix fields.

In lyxml_parse_qname, *prefix is set to NULL at src/xml.c:302. After the first lyxml_parse_identifier call (at src/xml.c:305) *prefix/value are still NULL, however after the second call to lyxml_parse_identifier (src/xml.c:312) the union is set to the address which is later invalidly freed in lyd_parse_xml_data, by lyxml_ctx_free.

Regards,
Juraj

**Comment by michalvasko** [comment]
Hi Juraj,
right, a macro was used where it should not have been, in this one single instance. Should work now.

Regards,
Michal

**Comment by jvijtiuk** [comment]
I've confirmed that f55ae20 fixes the crash, so I'm closing the issue.
