### ISSUE TITLE
libyang2: read of uninitialized variable in lyxml_parse_value

### ISSUE THREAD

**Issue by jvijtiuk** [CESNET/libyang#1132]
Hello,

the file attached below causes uninitialized reads in the xml parser.
[crash3.zip](https://github.com/CESNET/libyang/files/4848920/crash3.zip)

Here is the valgrind output:
```
==48216== Conditional jump or move depends on uninitialised value(s)
==48216==    at 0x1B8642: lyxml_parse_value (xml.c:420)
==48216==    by 0x1B92A1: lyxml_next_attr_content (xml.c:749)
==48216==    by 0x1B8C32: lyxml_open_element (xml.c:671)
==48216==    by 0x1B9A36: lyxml_ctx_new (xml.c:879)
==48216==    by 0x1284F8: lyd_parse_xml_data (parser_xml.c:724)
==48216==    by 0x11C7F1: lyd_parse_mem (tree_data.c:316)
==48216==    by 0x110747: LLVMFuzzerTestOneInput (lyd_parse_mem.c:68)
==48216==    by 0x1107E2: main (main.c:36)
```
it looks like xmlctx->input isn't properly terminated and that causes the issue, as printing it in the function causes the same complaint to appear by valgrind, in the printf call when strlen is called.

Regards,
Juraj

**Comment by jvijtiuk** [comment]
The following file seems to cause similar issues, and while removing parts of it the issue mentioned above appears, so I'm adding it to this issue
[uninitialized.zip](https://github.com/CESNET/libyang/files/4848956/uninitialized.zip)

**Comment by jvijtiuk** [comment]
This one causes a similar issue at a different point.

[uninitialized2.zip](https://github.com/CESNET/libyang/files/4849001/uninitialized2.zip)

**Comment by michalvasko** [comment]
Duplicate of #1129
