### ISSUE TITLE
Should libyang.pc be generated?

### ISSUE THREAD

**Issue by fxie00** [CESNET/libyang#1144]
Hi,

I am compiling frrouting, which depends on libyang. I built libyang v1.0.167 from the git hub. I can see libyang related libraries installed in /usr/lib:

/usr/lib/x86_64-linux-gnu# ls -al *libyang*
lrwxrwxrwx 1 root root      12 Jul 10 14:19 libyang.so -> libyang.so.1
lrwxrwxrwx 1 root root      17 Jul 10 14:19 libyang.so.1 -> libyang.so.1.7.11
-rw-r--r-- 1 root root 1079240 Jul 10 14:08 libyang.so.1.7.11

libyang:
total 80
drwxr-xr-x   4 root root  4096 Jul 10 14:19 .
drwxr-xr-x 103 root root 69632 Jul 10 14:46 ..
drwxr-xr-x   2 root root  4096 Jul 10 14:19 extensions
drwxr-xr-x   2 root root  4096 Jul 10 14:19 user_types

However, the configure script in frrouting complains that libyang was not found. 

Frrouting configure.ac uses PKG_CHECK_MODULES to find required libraries. It seems that this utility may require a libyang.pc file be generated and installed. I can't find such a file in my host. 

So the question is that whether libyang installation process should generate libyang.pc? Thanks.

Feng Xie

**Comment by rkrejci** [comment]
Hi, `libyang.pc` is being generated and installed into `<libdir>/pkgconfig/`, check the output of the `make install` command.
