### ISSUE TITLE
yanglint: no file/line information on errors

### ISSUE THREAD

**Issue by alex4747-pub** [CESNET/libyang#1145]
I am running yanglint of a set of definitions that passed pyang --strict check. I am getting errors without file and line information (and it is also not parsable by emacs)

How can I find offending file/line?

err : Invalid keyword "module".
err : Submodule parsing failed.

**Comment by rkrejci** [comment]
You can try `-VV` for more verbose output, but lines are not included. To check if it is a bug in libyang, you will have to provide more information to reproduce the issue.

**Comment by alex4747-pub** [comment]
This is the output from the attached script.

make
Running pyang
pyang --strict test.yang
test-inc.yang:12: error: type "xstring" not found in module "test-inc"
make: [Makefile:8: check] Error 1 (ignored)

Runing yanglint
yanglint --strict -VV test.yang
Validating test.yang schema file.
verb: Searching for "test-inc" in /home/ar/test_yang.
verb: Loading schema from "/home/ar/test_yang/test-inc.yang" file.
verb: Resolving derived type "xstring" failed, it will be attempted later.
verb: Resolving "test-inc" unresolved schema nodes and their constraints...
err : No resolvents found for type "xstring".
err : Module "test-inc" parsing failed.
err : Importing "test-inc" module into "test" failed.
err : Module "test" parsing failed.
make: [Makefile:11: check] Error 1 (ignored)

[test_yang.tar.gz](https://github.com/CESNET/libyang/files/4925431/test_yang.tar.gz)

**Comment by michalvasko** [comment]
Hi,
you will have to do with this information, for now. Last `Module XX parsing failed.` is the (sub)module (file) with the problem. Then you see that type `xstring` was not found so you just search the file for the use of this type.

Regards,
Michal

**Comment by alex4747-pub** [comment]
This is an intentionally trivial example. People (especially emacs users) will like you much more if you would fix it. E.g. I had just typed in ~7K of yang definitions if have to do manually typed search for every typo I made I would not (and I did not) use yanglint.

**Comment by michalvasko** [comment]
Well, the line will be (already is) included in *libyang* version 2 so it will be fixed, eventually. No point in implementing it also for the current *libyang*.

**Comment by alex4747-pub** [comment]
Seems fair.
