### ISSUE TITLE
is it possible to provide plain c++ library without swig?

### ISSUE THREAD

**Issue by alex4747-pub** [CESNET/libyang#1151]
c++ is really popular

**Comment by fredgan** [comment]
Emmmm, you know, libyang is a pure C project. If you want a pure cpp project, it should be another project. It will be a big project.
I am curious about what' the difference between plain c++ library with swig cpp library?

**Comment by alex4747-pub** [comment]
Existing c++ swig wrappers are pretty useful there is no need in a big project.

I do not know about difference. I tried to build libyang-cpp and it complained about swig library missing. I installed swig (*), built libyang-cpp and I am using  to build a custom parser without problems.

It will be nice to have libyang-cpp to be built by default and without swig dependency.

**Comment by rkrejci** [comment]
C++ binding library is done without SWIG in libyang 2. 

Actually even in current version, the SWIG is not necessary for C++, but since the C++ binding is used as a base for other SWIG bindings, it is covered by cmake in a single bundle and SWIG is required.

**Comment by alex4747-pub** [comment]
Can you at least add a note to the README?
