### ISSUE TITLE
cannot retrieve enum information using c++

### ISSUE THREAD

**Issue by alex4747-pub** [CESNET/libyang#1156]
Sorry going through enum representation problems and notices this

https://github.com/CESNET/libyang/blob/2aa0eb4c1a555d9f62690843e6a037dbaab57b99/swig/cpp/src/Tree_Schema.cpp#L143

LY_NEW_LIST is using 'size' field from info_enums and there is no such field, how this even compiles?

https://github.com/CESNET/libyang/blob/2aa0eb4c1a555d9f62690843e6a037dbaab57b99/swig/cpp/src/Internal.hpp#L42

**Comment by michalvasko** [comment]
Hi,
what exactly is the problem, is there a specific use-case that does not work? It compiles meaning it is fine, `size` is a macro parameter so it gets textually replaced with `count` in this case.

Regards,
Michal

**Comment by alex4747-pub** [comment]
If I copy info_enums from inside Type_Info_Enums (see below)- it works fine, If I use raw_enums.enm() method, it creates pretty random vectors, say for enum with count 3 it created vector with size 5, I had bad data inside the enum etc  - I did not debug it extensively.

BTW, I am c-programming from 1985 and never saw macro programming that is so creative - what is wrong with passing 'size' as a value instead of field name?

`    libyang::Type_Info_Enums raw_enums = *target_type->info()->enums();

    if (raw_enums.count() != 0) {
      // There is a bug in libyang that does not allow to extract                                                                                                                                                                                                             
      // enum data. Here is a workaroun we got pointer to date                                                                                                                                                                                                                
      // from the class (using a pretty bad hack) and then                                                                                                                                                                                                                    
      // this pointer to figure out enums                                                                                                                                                                                                                                     
      lys_type_info_enums* ptr = nullptr;

      memcpy(&ptr, &raw_enums, sizeof(ptr));

      for (size_t ii = 0; ii < ptr->count; ii++) {
	const char* name = ptr->enm[ii].name;
        int32_t value = ptr->enm[ii].value;
        std::cout << "    node->AddEnumValue(\"" << name << "\", " << value
                  << ");\n";
      }
`

**Comment by michalvasko** [comment]
Hi,
okay, please try again now, I think it was (quite an interesting) memory management issue.

As for the macro, I agree that it is somewhat confusing but it will not be changed right now, maybe when the bindings are ported to *libyang* 2. Anyway, it was written by another developer that is no longer working on the project for quite some time now.

Regards,
Michal

**Comment by alex4747-pub** [comment]
Thank you, I did not try it yet and I had looked at the fix. I will try it later today and let you know.

I suppose 'info' points to some data build from yang that are not going to change, I would make it a pointer to const. And I never used unions in c++ does it really require explicit 'union' ?

**Comment by alex4747-pub** [comment]
Yes the fix worked. Thank you again.

**Comment by michalvasko** [comment]
Hi,
all of these objects are supposed to be just wrappers for C structures. The problem here was that it was not just a wrapper (having a pointer to the C structure) but an actual copy (had the C structure/union itself). And when it was freed once no longer needed (during the vector construction), all the derived objects became invalid. And yes, they all should probably be `const` pointers.

Regards,
Michal
