### ISSUE TITLE
[Question] 'input' in xpath expression

### ISSUE THREAD

**Issue by fredgan** [CESNET/libyang#1158]
Hi Michal,
I encountered an issue, but I don't find any docs about it.

I have an yang model,
```yang
module mod1 {
  yang-version 1.1;
  namespace "urn:mod1";
  prefix m;

  rpc myrpc {
    input {
      container ic {
        leaf inputnode {
          type string;
        }
      }
    }
    output {
      leaf outputnode {
        type string;
      }
    }
  }

  augment /myrpc/input/ic {
     leaf il {
       type leafref {
         path "/myrpc/ic/inputnode";  // HERE
       }
     }
  }
}
```

It's accepted by yanglint. But if I add "input" to the path statement above, like `path "/myrpc/input/ic/inputnode"; ` it will report an error.
But you can see, the `augment /myrpc/input/ic` has an "input", ` path "/myrpc/ic/inputnode";` has no "input".

Do you know any documents describe it? I don't find it. Thanks

**Comment by michalvasko** [comment]
Hi,
it is all described in the [YANG 1.1 RFC](https://tools.ietf.org/html/rfc7950) but you must dig there a bit. Ultimately, you will learn that `leafref` `path` is a subset of XPath (hence no schema-only nodes such as input are allowed) while `augment` argument is a *Schema Node Identifier*. Hence the difference.

Regards,
Michal

**Comment by fredgan** [comment]
@michalvasko I get it, Thanks for the tips!
