### ISSUE TITLE
libyang 2 API documentation

### ISSUE THREAD

**Issue by gitter-runner** [CESNET/libyang#1162]
Hi!

I'm looking forward to the new libyang2 changes, and was just wondering, is the API documentation to be expected in the near future?

I'm interested in how the new changes will affect past implementation (e.g., struct lyxml_* changes might require changing the get RPC callbacks), and a documentation similar to the current version's would help out a lot!
Also, do you plan to create a migration guide from libyang to libyang2?

Thanks for the help!

**Comment by rkrejci** [comment]
Hi

API documentation in the form of the functions, structures, etc. description is already done and can be generated using `make doc` from the libyang2 branch. Just note that the API is still not set in stone. What is not yet written is some high-level overview (the How-To pages present in the libyang 1.x documentation), which would provide some guide on how to use all those pieces together. And yes, I want to have some migration notes as part of it. I expect that this part could be available during the September.

**Comment by rkrejci** [comment]
Hi, documentation for libyang 2.0 should be now complete, including the transition manual. You can generate it on your own from the `libyang2` branch using `make doc`, or you can check the hourly built docs:

https://netopeer.liberouter.org/doc/libyang/libyang2/html/
