### ISSUE TITLE
libyang2: decimal64 type compilation crash

### ISSUE THREAD

**Issue by michalvasko** [CESNET/libyang#1164]
Loading the *ietf-microwave-radio-link* causes a crash. All needed modules attached.

[modules.tar.gz](https://github.com/CESNET/libyang/files/5035013/modules.tar.gz)

**Comment by awesomenode** [comment]
Hi,

I would like to test libyang2. I have models with decimal64 type. Do you have possibility to fix this crash or should I wait with testing?

Thanks

**Comment by michalvasko** [comment]
It seems this was fixed some time ago already (branch `libyang2`).
