### ISSUE TITLE
Validating

### ISSUE THREAD

**Issue by wlupton** [CESNET/libyang#1174]
I'm interested in validating YANG package instances, starting with the examples in [draft-rwilton-netmod-yang-packages Appendix A](https://tools.ietf.org/html/draft-rwilton-netmod-yang-packages#appendix-A). But I don't even know whether I should expect `yanglint` to be able to do this. (Does #1128 suggest not?)

Here's my command (I've played with various `--type` values). 

```
% /usr/local/bin/yanglint --version
yanglint SO 1.9.5
```

```
% make
/usr/local/bin/yanglint \
--path=../../../yang-external/ --verbose --allimplemented  --strict --type=data --merge --format=xml --default=all-tagged \
--output=example-ietf-network-device-pkg.json.out \
../../../yang-external//ietf-datastores.yang \
../yang/ietf-yang-structure-ext@2019-03-07.yang \
../yang/ietf-yang-instance-data@2020-04-02.yang \
example-ietf-network-device-pkg.json
err : Unknown element "instance-data-set".
```

The JSON is as in the ID but with the first two lines removed. These are the first few lines:

```
 {
  "ietf-yang-instance-data:instance-data-set": {
    "name": "example-ietf-network-device-pkg",
    "pkg-schema": {
       package: "ietf-yang-package-defn-pkg@0.1.0.json"
    },
```

**Comment by michalvasko** [comment]
Missed this issue and it is likely not relevant anymore, but current *libyang* does support the `structure` extension for several months now.
