### ISSUE TITLE
Potential leak in parse_text

### ISSUE THREAD

**Issue by preetbhansali** [CESNET/libyang#1178]
#undef BUFSIZE

    if (o) {
        if (result) {
            size = size + o;
            **aux = realloc(result, size + 1);**
            result = aux;
        } else {
            size = o;
            result = malloc((size + 1) * sizeof *result);
        }
        LY_CHECK_ERR_RETURN(!result, LOGMEM(ctx), NULL);
        memcpy(&result[size - o], buf, o);
    }

isn't aux = realloc(result, size + 1); should be aux = ly_realloc(result, size + 1); ?

**Comment by michalvasko** [comment]
Hi,
yeah, I guess. Fixed.
