### ISSUE TITLE
libyang2: log refactoring

### ISSUE THREAD

**Issue by michalvasko** [CESNET/libyang#1188]
Suggested changes:
  - `LOGVAL` macro should allow to specify both the line and the path of the error, automatically handle situations when line/path is not available
  - for a clean implementation this will likely require to add this information into schema/data contexts
  - it would also be nice if the path generation in schema compile is refactored - so that it is not necessary to generate the path for all the nodes even though it may not be needed and so that there do not have to be 2 calls to `lysc_update_path` in almost every function, one at the start, one at the end

**Comment by rkrejci** [comment]
The `LOGVAL` was modified in #1325.
