### ISSUE TITLE
Problem with identities and features in when statements

### ISSUE THREAD

**Issue by wlupton** [CESNET/libyang#1196]
When running yanglint (the latest from the devel branch) on the YANG shown below we see the following:

```
% yanglint -v
yanglint SO 1.9.10
% yanglint -V my-mod.yang
warn: Invalid value "identity-1" in "identities" element. (/my-mod:identities[.='my-mod:identity-1'])
warn: Identity "identity-1" is disabled by its if-feature condition. (/my-mod:identities[.='my-mod:identity-1'])
warn: Previous warning generated by XPath subexpression[11] "identities='my-mod:identity-1'".
```

Note that the problem goes away if we move the `if-feature` from `identity-1` to `identity-base`, but we don't see why this should be necessary (and it's not what we want to do).

YANG:

```
module my-mod {
  yang-version 1.1;
  namespace "http://www.example.com/ns/yang/my-mod";
  prefix my-mod;

  feature feature-1;

  identity identity-base {}

  identity identity-1 {
    if-feature feature-1;
    base identity-base;
  }

  container top {
    config false;
    leaf-list identities {
      type identityref {
        base identity-base;
      }
    }
    container child {
      when
        "boolean(../identities='my-mod:identity-1')";
      if-feature feature-1;
    }
  }
}
```

**Comment by michalvasko** [comment]
Hi,
right, please try again, should work correctly now and do not display any warning in this case.

**Comment by wlupton** [comment]
Fantastic! This gets rid of the warning.

But I'm afraid that there's a related error shown by the attached [my-module.yang](https://github.com/CESNET/libyang/files/5208457/my-module.yang.txt) (the module that I provided earlier is a cut-down version of this one, because I was trying narrow the problem ... but I guess I made it too narrow).

```
lewa:software% yanglint -v
yanglint SO 1.9.11
lewa:software% yanglint -V my-module.yang 
warn: Invalid value "doing-something" in "state" element. (/my-module:state)
warn: Enum "doing-something" is disabled by its 1. if-feature condition. (/my-module:state)
warn: Previous warning generated by XPath subexpression[111] "my-module:state!='doing-something'".
```

**Comment by wlupton** [comment]
By the way, I was wondering why some of the warnings look like this (from yesterday):

```
warn: Identity "identity-1" is disabled by its if-feature condition. (/my-mod:identities[.='my-mod:identity-1'])
```

and some like this (with a `1.`):

```
warn: Enum "doing-something" is disabled by its 1. if-feature condition. (/my-module:state)
```

**Comment by michalvasko** [comment]
Hi,
right, there was another different bug that just manifested this way, should be fixed. The if-feature messages were just inconsistent, should also be fixed.

**Comment by wlupton** [comment]
Yes that fixes it (and the problem in the original even more complicated module). Thanks again!

**Comment by wlupton** [comment]
It seems that this fix (or possibly a different recent fix) may have broken something else?

The problem is shown by the published version of the `bbf-qos-policing.yang` module. I checked out `YangModels/yang` (including the `bbf` submodule) and (from the top-level directory) ran this command:

```
% yanglint --verbose --path standard/ietf/RFC --path standard/bbf/standard/common \
    --path standard/bbf/standard/equipment --path standard/bbf/standard/interface \
    --path standard/bbf/standard/networking standard/bbf/standard/networking/bbf-qos-policing.yang
```

In master:

```
lewa:yang% yanglint -v
yanglint SO 1.9.2
lewa:yang% <command>
<no output>
```

In devel:

```
lewa:yang% yanglint -v
yanglint SO 1.9.12
lewa:yang% <command>
warn: Failed to resolve identityref "bbf-qos-policing:flow-color". (/bbf-qos-classifiers:action-type)
warn: Previous warning generated by XPath subexpression[3] "bbf-qos-classifiers:action-type="bbf-qos-policing:flow-color"".
warn: Failed to resolve identityref "bbf-qos-policing:bac-color". (/bbf-qos-classifiers:action-type)
warn: Previous warning generated by XPath subexpression[3] "bbf-qos-classifiers:action-type="bbf-qos-policing:bac-color"".
warn: Failed to resolve identityref "bbf-qos-policing:discard". (/bbf-qos-classifiers:action-type)
warn: Previous warning generated by XPath subexpression[3] "bbf-qos-classifiers:action-type="bbf-qos-policing:discard"".
warn: Failed to resolve identityref "bbf-qos-policing:policing". (/bbf-qos-classifiers:action-type)
warn: Previous warning generated by XPath subexpression[3] "bbf-qos-classifiers:action-type="bbf-qos-policing:policing"".
```

**Comment by wlupton** [comment]
@michalvasko I just wanted to check that you saw that I'd reopened this issue. Thanks.

**Comment by michalvasko** [comment]
Hi,
I was on a vacation last week, that is why I did not reply. So, it should be fixed now, the previous fixes exposed another bug.

**Comment by wlupton** [comment]
Thanks @michalvasko. It was my turn to be on vacation last week!

This fixes the `bbf-qos-policing.yang` problem but unfortunately there's still a (similar?) problem in some other unpublished YANG. If necessary I'll try to supply a cut-down example but I'm hoping that the snippets below may be sufficient to pinpoint the problem.

```
% yanglint -v
yanglint SO 1.9.13
```

```
% /usr/local/bin/yanglint --path=../types --path=../interfaces --path=../../../yang-external/ --verbose --allimplemented bbf-ancp-fastdsl-access-extensions.yang
warn: Failed to resolve identityref "bbf-ancp-fastdsl-access-extensions:fastdsl". (/bbf-ancp:technology)
warn: Previous warning generated by XPath subexpression[12] "bbf-ancp:technology = 'bbf-ancp-fastdsl-access-extensions:fastdsl'".
warn: Failed to resolve identityref "bbf-ancp-fastdsl-access-extensions:fastdsl". (/bbf-ancp:technology)
warn: Previous warning generated by XPath subexpression[12] "bbf-ancp:technology = 'bbf-ancp-fastdsl-access-extensions:fastdsl'".
```

```
module bbf-ancp-fastdsl-access-extensions {
  yang-version 1.1;
  namespace "urn:bbf:yang:bbf-ancp-fastdsl-access-extensions";
  prefix bbf-ancp-fastdsl-acc-ext;

  import bbf-ancp {
    prefix bbf-ancp;
  }

  ...

  identity fastdsl {
    base bbf-ancp:access-line-technology;
    description
      "Indicates that the access line technology is FastDSL.";
  }

  ...

  augment "/bbf-ancp:ancp"
        + "/bbf-ancp:partitions"
        + "/bbf-ancp:partition"
        + "/bbf-ancp:sessions"
        + "/bbf-ancp:session"
        + "/bbf-ancp:topology-discovery"
        + "/bbf-ancp:port-up" {
    when "../../../../bbf-ancp:technology = "
       + "'bbf-ancp-fastdsl-acc-ext:fastdsl'";
```

**Comment by michalvasko** [comment]
Hi,
I do not think these modules are publicly available, at least I failed to find them. Could you please provide them/send a link if there is one?

**Comment by wlupton** [comment]
No, they're not yet publicly available. I was hoping that the snippets would be sufficient to indicate the problem. Please let me know if not, and if I should try to reproduce it in a simple module.

**Comment by michalvasko** [comment]
Okay, there should be no warning anymore. This was a completely unrelated problem to the previous ones (although it is possible it manifested because of the original fix). The local module for the expression was considered `bbf-ancp` (the module of the context node, as defined by the RFC) and not `bbf-ancp-fastdsl-access-extensions` (as later clarified on the mailing list).

**Comment by wlupton** [comment]
Thanks very much. That fixed it.

I didn't fully understand the explanation. I would naively expect the qualified name `bbf-ancp-fastdsl-acc-ext:fastdsl` to be valid in any context. I guess I need to go back and read the mailing list discussion!

**Comment by michalvasko** [comment]
Well, it was some time ago but you should be able to find it.

> I would naively expect the qualified name bbf-ancp-fastdsl-acc-ext:fastdsl to be valid in any context.

That is how it worked before but now the actual imports of the local module are searched and a match must be found.

**Comment by wlupton** [comment]
Sorry (I know this is off-topic) but in this case the `fastdsl` identity is defined in the local module so it's never going to be found in an imported module. Furthermore, surely `bbf-ancp-fastdsl-acc-ext:fastdsl` is explicitly saying "this is defined in the local module"?

**Comment by michalvasko** [comment]
All I meant was that now the rules are explicitly checked. Yes, in this case there is no import and you want to reference an identity in your local module, you can achieve that in 2 ways. Either specify no prefix or use the prefix of your module. Using `bbf-ancp-fastdsl-acc-ext:fastdsl` is the latter solution and the local prefix is actually checked now (it was a bit different before the original fix in this issue).

**Comment by wlupton** [comment]
Great! Using no prefix gives a warning, right?

```
/usr/local/bin/yanglint --path=../types --path=../interfaces --path=../../../yang-external/ --verbose --allimplemented bbf-ancp-fastdsl-access-extensions.yang
warn: Identityref "technology" comparison with identity "fastdsl" without prefix, consider adding a prefix or best using "derived-from(-or-self)()" functions.
warn: Previous warning generated by XPath subexpression[12] "bbf-ancp:technology = 'fastdsl'".
```

We're fine with always using a prefix. In this case (checking for equality) I don't think we could have used `derived-from(-or-self)()` could we?

**Comment by michalvasko** [comment]
This warning is a direct result of another mailing list discussion. Ideally, you should always use one of those XPath functions because

1) it makes it explicit that the argument is an identity (*libyang* has fairly good heuristics to detect when a string is expected to be an identity so you should be fine, but there is no such distinction for general XPath),
2) it allows also any future identities derived from the specific one (`fastdsl` in your case) to match the condition because that is the intentional usage of identities. If you do not use these functions, the functionality is basically limited to one value, as if the leaf was an `enumeration` and not an `identityref`.

**Comment by wlupton** [comment]
Got it! We'll definitely take this advice on board. I should have checked the arguments of these functions before commenting (I had it in my head that they were only needed for things like "when interface is ethernet-like").

Thanks again for your fast action and for the follow-up discussion. I'll now close this issue.
