### ISSUE TITLE
lyd_print_mem method convert leaf-list lyd_node to json is null

### ISSUE THREAD

**Issue by yanjunxi** [CESNET/libyang#121]
load all data by lyd_new_path to build a lyd_node layered tree in memory.
use lyd_print_mem with parameter LYD_FORMAT=LYD_JSON, then the output is like this:
`{"normalTest:root":{"aa":{"l1":5,"l2":"xxx","ll":null,"cc":{"i1":4},"bb":[{"name":"abc","value":5}]}}}`
where leaf-list node ll is null.

module is:
```
module normalTest {
	namespace "urn:ietf:params:xml:ns:yang:zte";
	prefix normalTest;
	
  container root{
		container aa{
			leaf l1{
				type int8;
				default 3;
			}
			leaf l2{
				type string;
			}
			leaf-list ll{
				type string;
			}
			
			container cc{
				leaf i1{
					type int8;
				}
			}
			
	    list bb{
	    	key name;
	    	leaf name{
	    		type string;
	    	}
	    	leaf value{
	    		type int8;
	    	}
	    }
    }
	}
}
```

data is:
```xml
<root xmlns="urn:ietf:params:xml:ns:yang:zte">
	<aa>
		<l1>5</l1>
		<l2>xxx</l2>
		<ll>111</ll>
		<ll>222</ll>
		<ll>333</ll>
		<cc>
			<i1>4</i1>
		</cc>
		<bb>
			<name>abc</name>
			<value>5</value>
		</bb>
	</aa>
</root>
```

**Comment by michalvasko** [comment]
Hi,
I failed to reproduce the problem. In my testing application I loaded the schema, then the data from file and printed it. The leaf-list `ll` was printed correctly. Did you really use `lyd_new_path()` for building the data tree? If it is not a typo then this function is meant to build data trees from scratch, when you have no full data tree available. But you have in your case, the XML file you posted here, so just use `lyd_parse_path()` on it and it should work.

Regards,
Michal

**Comment by yanjunxi** [comment]
I print xml and json to compare, like the follow:

    char* json;
    char* xml;
    if (root) {
        rc = lyd_print_mem(&json, root, LYD_JSON, 0);
        rc = lyd_print_mem(&xml, root, LYD_XML, 0);
    }
    printf("************json:%s.\r\n", json);
    printf("************xml:%s.\r\n", xml);

and the result in screen is : 
************json:{"normalTest:root":{"aa":{"l1":5,"l2":"xxx","ll":null,"cc":{"i1":4},"bb":[{"name":"abc","value":5}]}}}.
************xml:<root xmlns="urn:ietf:params:xml:ns:yang:zte"><aa><l1>5</l1><l2>xxx</l2><ll>111</ll><ll>222</ll><ll>333</ll><cc><i1>4</i1></cc><bb><name>abc</name><value>5</value></bb></aa></root>.


xml data is right, and json data is wrong.

build tree code like this:
    ly_errno = LY_SUCCESS;
    while (sr_get_item_next(ds, iter, &value) == SR_ERR_OK) {
        if (value->type == SR_CONTAINER_T) {
            /* useless to create containers, we would have to check later that there is
             * really something inside */
            sr_free_val(value);
            continue;
        }

        node = lyd_new_path(*root, lyCtx, value->xpath, getSysrepoValue(lyCtx, value, buf), LYD_PATH_OPT_UPDATE);
        sr_free_val(value);
        if (ly_errno) {
            sr_free_val_iter(iter);
            return -1;
        }

        if (!(*root)) {
            *root = node;
        }

        if (rc) {
            assert(node);
            while (node->schema->nodetype & (LYS_CONTAINER | LYS_LIST)) {
                node = node->child;
                assert(node);
            }
            assert(node->schema->nodetype == LYS_LEAF);
            node->dflt = 1;
        }
    }

**Comment by yanjunxi** [comment]
![print](https://cloud.githubusercontent.com/assets/20453804/18465276/845d5ba2-79c8-11e6-8dbe-0472d7f02fb4.png)

**Comment by michalvasko** [comment]
Hi,
you should have mentioned you are using sysrepo in the very first post, this is only libyang issue tracker. So you are using netopeer2-server to communicate with sysrepo (correct me if I am wrong)? What neotpeer2 and sysrepo versions (branches) are you using?

Regards,
Michal

**Comment by yanjunxi** [comment]
because I can't load a lyd_node tree directly, so I load lyd_node one by one.
any way, besides of how to create lyd_node tree, the xml print indicate the lyd_node layered tree is standard libyang data tree, and then json result is wrong.
Indeed ,I can't show all my memory of the node tree, so I show it by xml print.

Best Regards.

**Comment by yanjunxi** [comment]
leaf-list has no child, so flag_empty is 1,then attach "null" and return.
but, why deal child of leaf-list node?

Thanks.

static void
json_print_leaf_list(struct lyout *out, int level, const struct lyd_node *node, int is_list, int toplevel)
{
    const char *schema = NULL;
    const struct lyd_node *list = node;
    int flag_empty = 0, flag_attrs = 0;

    if (!list->child) {
        /* empty, e.g. in case of filter */
        flag_empty = 1;
    }

    if (toplevel || !node->parent || nscmp(node, node->parent)) {
        /* print "namespace" */
        schema = lys_node_module(node->schema)->name;
        ly_print(out, "%*s\"%s:%s\":", LEVEL, INDENT, schema, node->schema->name);
    } else {
        ly_print(out, "%*s\"%s\":", LEVEL, INDENT, node->schema->name);
    }

    if (flag_empty) {
        ly_print(out, "%snull", (level ? " " : ""));
        return;
    }

**Comment by rkrejci** [comment]
Please confirm the fix in your case. Despite we were not able to replicate the issue, there was the bug you have described.
