### ISSUE TITLE
memleak of var 'msg' when return -1

### ISSUE THREAD

**Issue by limboash** [CESNET/libyang#1212]
https://github.com/CESNET/libyang/blob/6defee4cab9e76bdd736bb3f751de396b4bf5a4b/src/printer.c#L106

in case LYOUT_MEMORY
'msg' is already allocated memory by 'vasprintf'
before return -1，need 'free(msg)' ?

**Comment by michalvasko** [comment]
If memory allocation fails, a memory leak will be the least of your problems, but fine, fixed.
