### ISSUE TITLE
How to get libyang version 1.9.0

### ISSUE THREAD

**Issue by tcnyambira** [CESNET/libyang#1213]
I encountered the followimg while compiling sysrepo. I cant figure out how to get to the required version
 
Could NOT find LibYANG: Found unsuitable version "1.2.6", but required is
  at least "1.9.0" (found /usr/local/lib/libyang.so)

**Comment by michalvasko** [comment]
That means you were trying to compile *sysrepo* from `devel`, you will find a sutiable *libyang* version also in its [devel](https://github.com/CESNET/libyang/tree/devel) branch.

**Comment by tcnyambira** [comment]
Thank you Michal.

I compiled the libyang devel branch and I was able to compile sysrepo
