### ISSUE TITLE
Additional unwanted characters in pattern

### ISSUE THREAD

**Issue by DineshReddyK** [CESNET/libyang#1214]
Hi,
My yang model has the pattern constraint as  `[a-zA-Z0-9!$%\\^()\\[\\]_\\-~{}.+]*` 
When libyang is parsing it, there is additional `%` symbol is seen. it is becoming like `[a-zA-Z0-9!$%%\^()\[\]_\-~{}.+]*`
Is this some pattern parsing error in libyang? 

```
  typedef password {
    type string {
      length "8..128";
      pattern "[a-zA-Z0-9!$%\\^()\\[\\]_\\-~{}.+]*" {
        error-message "Password content does not meet the requirements";
      }
    }
  }


[ERR]: LY: Value "q@we^rt([]+y+ui" does not satisfy the constraint "[a-zA-Z0-9!$%%\^()\[\]_\-~{}.+]*" (range, length, or pattern). 
```

**Comment by michalvasko** [comment]
Hi,
I have tried your example with the `yangre` tool of *libyang* with this [input.txt](https://github.com/CESNET/libyang/files/5296969/input.txt).

```
> ./yangre -f ../input.txt
yangre error: Value "q@we^rt([]+y+ui" does not satisfy the constraint "[a-zA-Z0-9!$%\^()\[\]_\-~{}.+]*" (range, length, or pattern).
```

Seems okay to me. Also, I have used the current `devel` version.

**Comment by DineshReddyK** [comment]
I have `libyang.so.1.9.2`, does this have the problem?

**Comment by michalvasko** [comment]
Right, the problem was only in the message that was printed by *netopeer2*, that should be fixed now. But any values were being matched with the correct pattern.

**Comment by DineshReddyK** [comment]
That's great. thanks for the quick fix.
Now logs won't confuse us :)
