### ISSUE TITLE
YANG Schema Mount support?

### ISSUE THREAD

**Issue by awesomenode** [CESNET/libyang#1225]
Hi,

Do you have plan to support YANG Schema Mount? https://tools.ietf.org/html/rfc8528
I saw that L3 related IETF RFCs started to use it.

Thanks

**Comment by michalvasko** [comment]
Hi,
yeah, we have planned to support it for quite some time now but there always seem to be some higher priority tasks. Unfortunately, this has not changed so I am not able to tell you anything more.

**Comment by awesomenode** [comment]
Thanks for the info. It is good to know that this feature is planned.

**Comment by michalvasko** [comment]
Duplicate of #691
