### ISSUE TITLE
lyd_find_path() can't find leaf node by specifying peer leaf-list value

### ISSUE THREAD

**Issue by tad-ashlock** [CESNET/libyang#1233]
**libyang version:** 1.0.167

**Model (t.yang):**
```
module t {
    namespace "urn:t";
    prefix t_mod;

    revision 2020-10-14 {
        description "version 1";
    }
    container c {
        list l {
            key "name";
            leaf name {
                type string;
            }
            leaf-list ll {
                type string;
            }
        }
    }
}
```
**Instance Data (t.yang.xml):**
```
<?xml version='1.0' encoding='UTF-8'?>
<c xmlns="urn:t">
  <l>
    <name>n1</name>
    <ll>ll-A</ll>
  </l>
  <l>
    <name>n2</name>
    <ll>ll-B</ll>
    <ll>ll-C</ll>
  </l>
</c>
```

**XPath:** `/t:c/l[ll[.='ll-C']]/name`

When I call `lyd_find_path()` with the above configuration I expect it to return a set with a single element of the "name" node with the value "n2".  But instead, it returns an empty set.

If I call `lyd_find_path()` with `/t:c/l[ll[.='ll-C']]/*` ("name" replaced with "*"), it correctly returns the three elements from inside the matching l node.

I tested `/c/l[ll[.='ll-C']]/name` xpath (removing the "t:" prefix) at [https://www.freeformatter.com/xpath-tester.html](https://www.freeformatter.com/xpath-tester.html) and it returned the expected value of "n2".

If this is not a bug, is there a supported xpath that would return the "n2" node given the "ll-C" value?

**Comment by tad-ashlock** [comment]
Update: I just discovered that yanglint can also test xpaths.  The xpath in question above (/t:c/l[ll[.='ll-C']]/name) works as expected with yanglint.

**Comment by michalvasko** [comment]
If `yanglint` works correctly, you must be doing something wrong because it also uses [lyd_find_path()](https://github.com/CESNET/libyang/blob/master/tools/lint/commands.c#L969). You should be able to figure it out by comparing your and `yanglint` code.

Just a note, using 2 predicates is redundant, you could have used `/t:c/l[ll='ll-C']/name` just as well.

**Comment by tad-ashlock** [comment]
Thank you!  That hint was the key to helping me find my problem.  I was using `sr_get_data()` to populate the node tree being searched by `lyd_find_path()`.  But I was accidentally passing the same xpath to both functions.  While this approach works for all of my other xpaths, it fails when the xpath contains a predicate referencing a value not gathered by `sr_get_data()`, of course.
