### ISSUE TITLE
Libyang error prompted upon sending Hello message RPC from netopeer2-cli

### ISSUE THREAD

**Issue by aswin19996** [CESNET/libyang#1234]
Hi 
I wanted to observe the capability exchange operation between the netopeer2-server and netopeer2-cli.
Hence i sent an RPC as follows:

```
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
     <capabilities>
        <capability>
            urn:ietf:params:xml:ns:netconf:base:1.0
          </capability>
          <capability>
            urn:ietf:params:netconf:capability:startup:1.0
          </capability>
          <capability>
            urn:ietf:params:netconf:capability:notification:1.0
          </capability>
       </capabilities>
     <session-id>4</session-id>
</hello>
```

Error that was prompted after sending this RPC using user-rpc option was:
`ly ERROR: Unknown element "hello". (/)`

I would like to understand why this error occurred.

Thanks.

**Comment by michalvasko** [comment]
Hi,
you cannot send `hello` once the session is established, no such RPC is defined in the `urn:ietf:params:xml:ns:netconf:base:1.0` namespace, it is just a special opening message. To see the hello message (and any other NETCONF messages sent), just set such parameters for either the server or CLI. For *netopeer2-server* it is `-c MSG` and for CLI it is a special command `verb` with value `debug` (this will also cause it to print a lot of other information).

**Comment by aswin19996** [comment]
So I tried giving the command: `netopeer2-server -c MSG`
I am unable to open the netopeer2 server back in debug mode?

**Comment by michalvasko** [comment]
Um, just use `netopeer2-server -d -v MSG`.

**Comment by aswin19996** [comment]
Sorry Michael, 
Looks like the server is getting terminated.
But still i am able to get response for 'status' command from netopeer2-cli
The error log is as follows:

> [ERR]: NP: Subscribing for providing "ietf-netconf-monitoring" state data failed (Invalid argument).
> [ERR]: NP: Server data subscribe failed.
> [INF]: NP: Server terminated.

**Comment by michalvasko** [comment]
Yeah, most likely because you have *netopeer2-server* running already when you run it without `-d`. You need to stop it first. Just do not ask how to do that, if you don't know, search for how to terminate a daemon process.

**Comment by aswin19996** [comment]
Sure. :+1: 
Thanks for the response Michal.
