### ISSUE TITLE
Not able to find RPC parameter

### ISSUE THREAD

**Issue by masif-cs** [CESNET/libyang#1239]
Hi,

I am using ly_ctx_get_node to find a node using xpath. It is able to find all kind of path except for RPC parameters. It gives error:

`<next-update-at xmlns="urn:o-ran:supervision:1.0">2020-07-07T12:00:00Z</next-update-at>`
libyang[0]: Schema node not found. (path: /o-ran-supervision:next-update-at)

```
rpc supervision-watchdog-reset {
    description
      "rpc to reset the watchdog timer";
    input {
      uses watchdog-input;
    }

          output {
      uses watchdog-output;
          }
  }

grouping watchdog-output {
    leaf next-update-at {
      type yang:date-and-time;
      description
        "Indicates the time when the next supervision notification is expected.";
    }
  }
```

Can you please let me know if this is an issue or I am not doing it right?

**Comment by michalvasko** [comment]
It is not an issue, you must set the last parameter correctly for these use-cases.

**Comment by masif-cs** [comment]
Hi @michalvasko ,

What should be the value of last parameter? I am sending 0 as of now for all paths of any type of node.
How would I know what values to be send to this func?

**Comment by michalvasko** [comment]
Is there something you do not understand about the [parameter description](https://netopeer.liberouter.org/doc/libyang/master/group__context.html#gabce6ff4f82d0ce7786d0a89cb70fb369)?

**Comment by masif-cs** [comment]
I have already gone through the description and the function in the code too. But what exactly these value contain? I see it defined as int, but used as a bool in if conditions. Even the statement "Search operation output instead input" is little confusing to me.

My question is, if it contains value 0/1 then how we are going to decide which node it will be 0 and which node it will be 1? Like for all nodes output=0 and for RPC output parameters it should be output=1?

**Comment by michalvasko** [comment]
In *libyang* we are using `int` as a boolean, there is a special type in the new version. So, it is a boolean value and if you set it to `true`, it will "Search operation output instead input." Operation can be both an RPC or an action.

**Comment by masif-cs** [comment]
Using Value true also I am getting same error.
<?xml version="1.0"?>
<next-update-at xmlns="urn:o-ran:supervision:1.0">2020-07-07T12:00:00Z</next-update-at>
libyang[0]: Schema node not found. (path: /o-ran-supervision:next-update-at)

Is the xpath not correct? Does it need to have RPC name also in xpath like below?
/o-ran-supervision:supervision-watchdog-reset/next-update-at

Because sysrepo is returning only this "/o-ran-supervision:next-update-at"

**Comment by michalvasko** [comment]
Oh, right, to find the node, the operation name must also be present.

> Because sysrepo is returning only this "/o-ran-supervision:next-update-at"

You mean `sr_rpc_send()` in its `output` values? You are better off using `sr_rpc_send_tree()` to avoid this problem.

**Comment by masif-cs** [comment]
Actually I am using cpp code, so I changed from rpc to rpc_tree. Still same xml I am getting.

**Comment by michalvasko** [comment]
What XML?

**Comment by masif-cs** [comment]
On Client side we are receiving this information:

`<next-update-at xmlns="urn:o-ran:supervision:1.0">2020-07-07T12:00:00Z</next-update-at>`

but it should be
<supervision-watchdog-reset xmlns="urn:o-ran:supervision:1.0">
<next-update-at>2020-07-07T12:00:00Z</next-update-at>
</supervision-watchdog-reset>

**Comment by michalvasko** [comment]
Please include more details, I am not able to guess everything. You are using a NETCONF client and this is the XML answer for the RPC invocation?

**Comment by masif-cs** [comment]
So I am triggering RPC request from Client to Server and getting the response. We are using netopeer-server and netopeer-client to test this.
Below is how the RPC is defined:

 ```
rpc supervision-watchdog-reset {
    description
      "rpc to reset the watchdog timer";
    input {
      uses watchdog-input;
    }

          output {
      uses watchdog-output;
          }
  }

grouping watchdog-output {
    leaf next-update-at {
      type yang:date-and-time;
      description
        "Indicates the time when the next supervision notification is expected.";
    }
  }
grouping watchdog-input {
    leaf supervision-notification-interval {
      type uint16;
      units seconds;
      default 60;
      description
        "The interval in seconds at which supervision notifications are sent.
        If not specified the default value of 60 seconds shall apply.";
    }
    leaf guard-timer-overhead {
      type uint16;
      units seconds;
      default 10;
      description
        "This is overhead added to the supervision timer used to calculate the
         supervision wathcdog timer. i.e.,

         supervision timer = notification timer + guard-timer-overhead

         If not specified the default value of 10 seconds shall apply.

         Failure to send this rpc again within the timeout sets the radio into
         'loss of supervision' state.

         NOTE - The supervision timer MUST not be less that the confimed
         timeout timer (when the feature is supported).

         This type of constraint (using an RPCs input) cannot be formally
         expressed in YANG.";
    }
  }
```
While pushing from client we are pushing:
```
<?xml version="1.0"?>
<supervision-watchdog-reset xmlns="urn:o-ran:supervision:1.0">
  <supervision-notification-interval>60</supervision-notification-interval>
</supervision-watchdog-reset>
```

In response we are getting below:
`<next-update-at xmlns="urn:o-ran:supervision:1.0">2020-07-07T12:00:00Z</next-update-at>`

But what I want is to know what RPC it is because it is not printing the RPC name. Expecting something like this:
```
<supervision-watchdog-reset xmlns="urn:o-ran:supervision:1.0">
<next-update-at>2020-07-07T12:00:00Z</next-update-at>
</supervision-watchdog-reset>
```

**Comment by michalvasko** [comment]
You are able to match the response to the sent request, the order is enforced. The reply [must](https://tools.ietf.org/html/rfc7950#section-7.14.4) look the way it does, without the RPC element.

**Comment by masif-cs** [comment]
So you mean to say we will not get the RPC name in the response? Is there any other way to know the name of the RPC?

**Comment by michalvasko** [comment]
Yes, that is what I am saying because that is how NETCONF defines it. You can only get it the way I told you, to remember the request you sent. That is how *netopeer2-cli* (or rather *libnetconf2*) knows what output parameters it should expect.

**Comment by masif-cs** [comment]
Using just the leaf name **next-update-at**, can we find the RPC name or Node element?

**Comment by michalvasko** [comment]
Well, you can find **a** node element but you can never be sure it is the correct one. I have told you everything there is, you cannot hack your way around, it is just not possible.

**Comment by masif-cs** [comment]
On server side I am printing XML which server is sending, that includes RPC name with the output parameters. That means somewhere in Netopeer and libnetconf they are removing the RPC name.

Let me see if I can do something.
