### ISSUE TITLE
lyp_check_date failed when setting timezone to certain value

### ISSUE THREAD

**Issue by LonelyDave** [CESNET/libyang#1242]
Hi,

    We use netconf with netopeer2+libnetconf+sysrepo+libyang and it worked.
    When we change timezone to certain value,maybe 12 zone offset, sysrepoctl/sysrepocfg/netopeer2-server will not work.
    We can simply validate the problem by `TZ='<SDfas+4>+4<CST-8>-8' sysrepoctl -l`
    How to resolve the problem?
![lyp_check_date](https://user-images.githubusercontent.com/52650179/96538614-80976a80-12cb-11eb-80e7-afb58cfea126.jpg)

    The problem is caused in lyp_check_date or parser.c
    `memcpy(&tm_, &tm, sizeof tm);
    mktime(&tm_); /* mktime modifies tm_ if it refers invalid date */
    if (tm.tm_mday != tm_.tm_mday) { /* e.g 2018-02-29 -> 2018-03-01 */
        /* checking days is enough, since other errors
         * have been checked by strptime() */
        goto error;
    }`

**Comment by michalvasko** [comment]
Right, should work now.

**Comment by LonelyDave** [comment]
It works~ 

Thank you
