### ISSUE TITLE
Possible issue with keyless list. Wrong order and missing elements

### ISSUE THREAD

**Issue by jabilmplane** [CESNET/libyang#1246]
Hello,

During usage of keyless list I have faced some issues. I am not sure whether it is limitation or the actual bug.

The original idea was to fill keyless list with data from, let say, map<string, struct Data> object. In the map a key is the string representation of int value ("1", "2" ect). The map value is a structure where data for keyless list are stored. As far as I know, keyless list could be filled from the code using integer indexes as keys replacement. And it is worked to some extent, however I've found several issues.

So to illustrate the problem I've prepared a very simple example. Just to be clear, I am using the latest devel branch.
Test model:
```
module keyless-demo {
  yang-version 1.1;
  namespace "urn:keyless-demo";
  prefix e;

  list oper-list {
    config false;
    leaf data1 {
      type string;
    }
        leaf data2 {
      type string;
    }
  }
}
```

The callback function to fill the list:
```
static int
module_operlist_state_cb(sr_session_ctx_t *session, const char *module_name, const char *xpath, const char *request_xpath,
uint32_t request_id, struct lyd_node **parent, void *private_data)
{
    // set node 1 leafs
    *parent = lyd_new_path(NULL, sr_get_context(sr_session_get_connection(session)),
                           "/keyless-demo:oper-list[1]/data1", (void *)"node1",
                           LYD_ANYDATA_CONSTSTRING, 0);
    lyd_new_path(*parent, NULL,
                           "/keyless-demo:oper-list[1]/data2", (void *)"node1",
                           LYD_ANYDATA_CONSTSTRING, 0);

    // set node 3 leafs before node 2
    lyd_new_path(*parent, NULL,
                           "/keyless-demo:oper-list[3]/data1", (void *)"node3",
                           LYD_ANYDATA_CONSTSTRING, 0);
    lyd_new_path(*parent, NULL,
                           "/keyless-demo:oper-list[3]/data2", (void *)"node3",
                           LYD_ANYDATA_CONSTSTRING, 0);

    // set node 2 leafs
    lyd_new_path(*parent, NULL,
                           "/keyless-demo:oper-list[2]/data1", (void *)"node2",
                           LYD_ANYDATA_CONSTSTRING, 0);
    lyd_new_path(*parent, NULL,
                           "/keyless-demo:oper-list[2]/data2", (void *)"node2",
                           LYD_ANYDATA_CONSTSTRING, 0);


    return SR_ERR_OK;
}
```

Cli output:
```
> get --filter-xpath /keyless-demo:oper-list
DATA
<oper-list xmlns="urn:keyless-demo">
  <data1>node1</data1>
  <data2>node1</data2>
</oper-list>
<oper-list xmlns="urn:keyless-demo">
  <data1>node3</data1>
  <data2>node2</data2>
</oper-list>
<oper-list xmlns="urn:keyless-demo">
  <data2>node3</data2>
</oper-list>
```

Could you please clarify for me the following issues I see there:
1) Integer indexes are used as replacements for key in keyless list. So it is expected to see either the same order in set and cli output (1, 3, 2) or sorted data in the output (1, 2, 3) But, as you can see from the example, leaves from node2 and node3 in the output are out of order.
2) Also you can see that leaf "data1" from node2 is completely missing in the cli output.

Is my example is valid at all? Do indexes reflect expected order in cli output? Is possible to indexes like 1,3,2 or 1,4,5,6?

I understand that the issue is not seen if the data is set to keyless list using straight order of indexes. But there always might be the cases where such additional adjustments hard to add. That's why I need clarification from your side to be prepared to possible cases.

Thank you for your help!

**Comment by michalvasko** [comment]
Hi,
yes, this works correctly (as I would expect it to). The main issue here is that the indices are **relative**, not **absolute** (for that we would have to track each instance "absolute" index and keep them in order).

So, when you are creating instance `[1]`, everything works as you would expect. However, when using `[3]/data1`, it is adjusted to `[2]` since there is only one instance and that is the last possible index. And when using `[3]/data2`, the second instance exists, so `[3]` is really used. You get
```xml
<oper-list xmlns="urn:keyless-demo">
  <data1>node1</data1>
  <data2>node1</data2>
</oper-list>
<oper-list xmlns="urn:keyless-demo">
  <data1>node3</data1>
</oper-list>
<oper-list xmlns="urn:keyless-demo">
  <data2>node3</data2>
</oper-list>
```
Finally, for `[2]/data1`, this node already exists and since you have not used `LY_PATH_OPT_UPDATE`, it actually fails (you should check return values). And `[2]/data2` is normally created, which gets you the result you see.

**Comment by jabilmplane** [comment]
Hello,

So, if I've understood you right, the following rules are applied on attempt to set data to keyless list:
1. If the node with given index already exists - add the data to that node (or replace the data if this leaf exists and appropriate option is set). 
2. If the node does not exist - add data to the new list node. The node is created with the first available index instead of the given one.

Assuming the rules, the following three examples of setting data
 
```
"/keyless-demo:oper-list[1]/data1", (void *)"node1",
"/keyless-demo:oper-list[1]/data2", (void *)"node1",

"/keyless-demo:oper-list[2]/data1", (void *)"node2",
"/keyless-demo:oper-list[2]/data2", (void *)"node2",

"/keyless-demo:oper-list[3]/data1", (void *)"node3",
"/keyless-demo:oper-list[3]/data2", (void *)"node3",
```

```
"/keyless-demo:oper-list[4]/data1", (void *)"node1",
"/keyless-demo:oper-list[1]/data2", (void *)"node1",

"/keyless-demo:oper-list[4]/data1", (void *)"node2",
"/keyless-demo:oper-list[2]/data2", (void *)"node2",

"/keyless-demo:oper-list[4]/data1", (void *)"node3",
"/keyless-demo:oper-list[3]/data2", (void *)"node3",
```

```
"/keyless-demo:oper-list[1]/data1", (void *)"node1",
"/keyless-demo:oper-list[2]/data1", (void *)"node2",
"/keyless-demo:oper-list[3]/data1", (void *)"node3",

"/keyless-demo:oper-list[3]/data2", (void *)"node3",
"/keyless-demo:oper-list[2]/data2", (void *)"node2",
"/keyless-demo:oper-list[1]/data2", (void *)"node1",
```

should give the same result:

```
<oper-list xmlns="urn:keyless-demo">
  <data1>node1</data1>
  <data2>node1</data2>
</oper-list>
<oper-list xmlns="urn:keyless-demo">
  <data1>node2</data1>
  <data2>node2</data2>
</oper-list>
<oper-list xmlns="urn:keyless-demo">
  <data1>node3</data1>
  <data2>node3</data2>
</oper-list>
```

Am I right in my assumptions ?
Is there any additional limitations or corner cases that I should be aware of?

**Comment by michalvasko** [comment]
Yes, I believe that is correct. Generally, only the out-of-bounds index is a specific behavior, all the rest should fully follow the [documentation](https://netopeer.liberouter.org/doc/libyang/master/group__datatree.html#ga31b3de84e33ece1022738f15fcac4242) and the options description.

**Comment by jabilmplane** [comment]
Okay. The situation seems clear for me. I am going to close the issue.
Thank you for your help!
