### ISSUE TITLE
Anyway to pre-merge XML-based input files?

### ISSUE THREAD

**Issue by kwatsen** [CESNET/libyang#1272]
The `yanglint` command-line supports the following parameter:
```
    -m, --merge           Merge input data files into a single tree and validate at once,
                                  has no effect for the auto, rpc, rpcreply and notif TYPEs.
```
This is **needed** for XML, but not for JSON, because the XML format doesn’t allow more than one top-level node, whereas it is possible in JSON format.

My question is, is there anyway to pre-construct a “pre-merged” XML document (e.g., using some dummy top-level node that yanglint will discard), that is effectively equivalent to passing multiple XML files on the commend line?

**Comment by rkrejci** [comment]
Hi Kent, `yanglint` should work correctly even with XML files with multiple top-level elements, so it doesn't matter if the data comes from a single file or from multiple files with the `--merge` option. The rules are the same, the only case when you need a top-level envelope is when you want to use the content autodetection.

In contrast to the cases described above, you can also specify multiple data files without the `--merge` option. In that case the contents of those files are validated separately while with the `--merge` option it is validated all together.
