### ISSUE TITLE
lyd_insert_sibling overwrites sibling

### ISSUE THREAD

**Issue by lukasmacko** [CESNET/libyang#129]
If I understand it correctly `lyd_insert_sibling` function is supposed to append a tree as a last sibling. However, in the code below one node gets overwritten is this bug or should I call this function only with the last sibling to avoid overwriting?

```C
#include <stdio.h>
#include <stdlib.h>
#include <libyang/libyang.h>

int sibling_count(struct lyd_node *n)
{
   int i = 0;
   while (n) {
      n = n->next;
      i++;
   }
   return i;
}

int main(int argc, char **argv)
{
   struct ly_ctx *ctx = ly_ctx_new(".");
   ly_ctx_load_module(ctx, "referenced-data", NULL);
   ly_ctx_load_module(ctx, "cross-module", NULL);

   struct lyd_node *node = NULL;
   struct lyd_node *dep = NULL;

   char *cm = "<reference xmlns=\"urn:cm\">abcd</reference><links xmlns=\"urn:cm\"><number>42</number></links>";
   char *rd = "<list-b xmlns=\"urn:rd\"><name>abcd</name><value>100</value></list-b><magic_number xmlns=\"urn:rd\">42</magic_number>";

   node = lyd_parse_mem(ctx, cm, LYD_XML, LYD_OPT_TRUSTED | LYD_OPT_CONFIG, ctx);
   dep = lyd_parse_mem(ctx, rd, LYD_XML, LYD_OPT_TRUSTED | LYD_OPT_CONFIG, ctx);

   printf("node: %d, dep: %d\n", sibling_count(node), sibling_count(dep));

   lyd_insert_sibling(&node, dep);

   printf("together: %d\n", sibling_count(node));
   //LINKS container is overwritten

   lyd_free_withsiblings(node);
   ly_ctx_destroy(ctx, NULL);
}
```

referenced-data.yang
```YANG
module referenced-data {

   namespace "urn:rd";
   prefix rd;

   list list-b {
      key name;
      leaf name {
         type string;
      }

      leaf value {
         type uint32;
      }
   }

   leaf magic_number {
      type uint8;
   }
}
```

cross-module.yang
```YANG
module cross-module {

   namespace "urn:cm";
   prefix cm;

   import referenced-data {
      prefix rd;
   }

   leaf reference {
      type leafref {
         path "/rd:list-b/rd:name";
      }
   }

   container links {
      leaf number {
         type uint8;
      }

      leaf value_in_list {
         type leafref {
            path "/rd:list-b/rd:value";
         }
      }

      must 'number = /rd:magic_number' {
         error-message "Number must be equal to magic_number";
      }
   }

   leaf universe_question {
      type string;
      when "/rd:magic_number = 42" {
         description "The answer is not correct";
      }
   }
}
```

**Comment by michalvasko** [comment]
Hi,
please read the documentation of `lyd_insert_sibling()`, default values (empty NP container, specifically) are causing the confusion here. What I hope you would now deduce from the documentation is that you want to use `lyd_merge()` instead with the flag `LYD_OPT_EXPLICIT`. I referenced a bug that occurred in `lyd_merge()` with this example.

Regards,
Michal

**Comment by lukasmacko** [comment]
Hi,

okey I'll try to use lyd_merge. 

I am just curious: What element did you mean by empty NP container? 
```XML
<links xmlns=\"urn:cm\">
   <number>42</number>
</links>
```
 It is not empty non-presence container thus I thought there should be no problem.

Thanks,
Lukas

**Comment by rkrejci** [comment]
yes, but `links` is defined as NP container and because it is missing in the `rd`, it was automatically created in `dep` tree as default empty NP container (because YANG requires these elements to be part of the accessible tree). And because `lyd_insert*()` believes that you know exactly what you are inserting and that you really want to insert it, that default empty `links` container replaced that explicit one present in `node` tree.

**Comment by lukasmacko** [comment]
I see. 
Thanks.
