### ISSUE TITLE
failed to parse get-config request, by using lyd_parse_xml()

### ISSUE THREAD

**Issue by a10222012** [CESNET/libyang#1294]
I am using lyd_parse_xml() with OPT: LYD_OPT_GETCONFIG|LYD_OPT_DESTRUCT, but always an error.
The Yang-module is like:
```yang
{
  list test {
    key id;
    leaf id {
        uint16;
    }
  }
}
```
The get-config XML:
```xml
<test xmlns="https://hillstone.com/yang/5.5R9/hc">
  <id/>
</test>
```
error message is Invalid value "" in "id" element.
Is there any way to parse the request XML, or my request XML is wrong?

**Comment by michalvasko** [comment]
The XML request is wrong, you must set the `id` to a valid value, `""` is not a valid `uint16` value.
