### ISSUE TITLE
The Regular Expression about certain block names

### ISSUE THREAD

**Issue by danikova** [CESNET/libyang#1299]
I am using yanglint SO 1.9.20 (devel branch).

References:

- [Unicode block Names](https://www.w3.org/TR/xsd-unicode-blocknames/)

Given three cases:

1. valid block names

> IsBasicLatin, IsLatin-1Supplement

pattern-IsBasicLatin-error.yang
```
module pattern-error {
  yang-version 1;
  namespace "http://pattern";
  prefix pattern;

  revision 2020-12-01 {
    description
      "Initial revision.";
  }

  leaf elem {
      type string {
          pattern '[\p{IsBasicLatin}]+';
      }
  }
}
```
yanglint output
```
# yanglint -s pattern-IsBasicLatin-error.yang
# echo $?
0
```

2. block names with `character value in \x{} or \o{} is too large` error

> IsLatinExtended-A, IsLatinExtended-B, IsIPAExtensions, etc...

pattern-IsLatinExtended-A-error.yang
```
module pattern-error {
  yang-version 1;
  namespace "http://pattern";
  prefix pattern;

  revision 2020-12-01 {
    description
      "Initial revision.";
  }

  leaf elem {
      type string {
          pattern '[\p{IsLatinExtended-A}]+';
      }
  }
}
```
yanglint output
```
# yanglint -s pattern-IsLatinExtended-A-error.yang
err : Regular expression "[\p{IsLatinExtended-A}]+" is not valid ("}-\x{017F}]+)$": character value in \x{} or \o{} is too large).
err : Module "pattern-error" parsing failed.
# echo $?
1
```

3. block names with `unknown block name` error

> IsSpecials, IsNKo, IsSamaritan, etc...

pattern-IsSpecials-error.yang
```
module pattern-error {
  yang-version 1;
  namespace "http://pattern";
  prefix pattern;

  revision 2020-12-01 {
    description
      "Initial revision.";
  }

  leaf elem {
      type string {
          pattern '[\p{IsSpecials}]+';
      }
  }
}
```
yanglint output
```
# yanglint -s pattern-IsSpecials-error.yang
err : Regular expression "[\p{IsSpecials}]+" is not valid ("Specials}]+)$": unknown block name).
err : Module "pattern-error" parsing failed.
# echo $?
1
```

**Comment by michalvasko** [comment]
Right, all those patterns should now work.

**Comment by danikova** [comment]
Thanks for your fast response.
Everything works fine.

If it helps, there is the other missing patterns with their ranges in .csv format:
[missing-blocks.zip](https://github.com/CESNET/libyang/files/5624107/missing-blocks.zip)

**Comment by michalvasko** [comment]
We support only the minimal set of classes (as the support is not native to PCRE/PCRE2), their list is [here](https://www.w3.org/TR/2004/REC-xmlschema-2-20041028/#charcter-classes). That is the document that RFC 7950 references.

**Comment by danikova** [comment]
Okay, i see. Thanks for your help.
