### ISSUE TITLE
lyd_parse_xml failed when parse edit-config  rpc of delete an int leaf but without value

### ISSUE THREAD

**Issue by qmm161** [CESNET/libyang#130]
For example, this rpc xml body will be parsed succfully:
`<Root xmlns="xxx" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
  <leafA xc:operation="delete">100</leafA>
</Root>`

but this will fail:
`<Root xmlns="xxx" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
  <leafA xc:operation="delete"></leafA>
</Root>`

**Comment by rkrejci** [comment]
can you also share how you use `lyd_parse_xml()`?

**Comment by rkrejci** [comment]
and also the model defining `leafA` would be helpful

**Comment by qmm161** [comment]
I run the test with netopeer2-server and the model (
[testdelleaf.txt](https://github.com/CESNET/libyang/files/488648/testdelleaf.txt)
), the op_editconfig function in netopeer2-server call  lyd_parse_xml to parse the edit-config rpc body. I guess you have source code of netopeer2-server,  so you can review it and check if the usage is right.

**Comment by qmm161** [comment]
and how can i commit code if i want to help fix bug, fork and pull request?

**Comment by rkrejci** [comment]
yes, pull request is the best way.

**Comment by rkrejci** [comment]
Note that besides updating libyang, your use case also needs to update netopeer2-server, there was also miner issue related to this.
