### ISSUE TITLE
lyd_merge_to_ctx can be further optimized

### ISSUE THREAD

**Issue by preetbhansali** [CESNET/libyang#1306]
Hi 

lyd_merge_to_ctx() can be optimized and a flag can be passed, if that flag is enabled, duplicity of 'source' and 'target' shall not be done and merged as it is.
Also, we can have an optimized version of lyd_merge(), if we have the top parent of source and target same. or if top parent is different. in the later one we can directly manage the sibling pointer. however in the former we may have to consider list/container merge.

**Comment by michalvasko** [comment]
It is possible some optimizations can be performed but I do not think they would have too significant impact on the actual performance. Also, *libyang* development (which includes optimizations as well) is mostly finished and we now focus on *libyang* version 2 while still providing support for this *libyang*. But we always accept pull requests so feel free to improve the data merge, best backing it up with some numbers showing that you did improve it and then we can discuss it more.

**Comment by preetbhansali** [comment]
Hi 

Thanks for your comment. We will try to find out if we are able to optimize it by ourselves.
Also could you please let me know, if such optimization are considered in libyang2 and how stable libyang2 is when compared to libyang1.
Also is libyang2 is backward compatible (like compatibility with libnetconf2).

**Comment by michalvasko** [comment]
Yes, if you raise an issue for *libyang2* that something seems slow while providing a benchmark showing that, we will take a look. It is not stable yet (even though we do not expect the main API to change anymore) but should be fully working at this point. The public release is planned for January after which we will start properly versioning it. For now you can download it to get familiar with it or do some tests. It is not backwards compatible.
