### ISSUE TITLE
ietf-schema-mount

### ISSUE THREAD

**Issue by som-1981** [CESNET/libyang#1314]
Hello,

Want to understand what does this error mean?
**_error: there cannot be any data nodes defined when 'mount-point' is used._**
How to correct this?

   yangmnt:mount-point children-of-SubNetwork {
      description "Mountpoint for ManagedElement";
      reference "RFC8528 YANG Schema Mount";
    }

Thanks,

**Comment by michalvasko** [comment]
Um, where did you get this error from? Are you sure it is from *libyang*? In any case, it does not support `schema-mount` so it will not work.
