### ISSUE TITLE
Hi, about the deviation_size of lys_module and lys_submodule

### ISSUE THREAD

**Issue by Tanco-K** [CESNET/libyang#1316]
Hi, about the deviation_size of lys_module and lys_submodule, it max num is 255 , if can change it to uint16_t I think is better.
Becase I just reach the max-num of deviation_size ....

**Comment by fredgan** [comment]
Hi @Tanco-K , Refer to #1000

**Comment by Tanco-K** [comment]
@fredgan ok. That's good. May I ask how long libyang2 will be released?

**Comment by michalvasko** [comment]
The plan is for this month so in a few weeks, most likely.

**Comment by Tanco-K** [comment]
@michalvasko ：）   look forward to (๑•̀ㅂ•́)و✧！

**Comment by Tanco-K** [comment]
Hi,  may I ask  lys_deviation   -->  deviate_size's type  need to change to uint16_t?
@michalvasko

**Comment by michalvasko** [comment]
Yes, but that change on its own will not be enough, all the use in the code must be adjusted accordingly (the iterators enlarged as well). As for *libyang2*, the release will probably get slightly delayed but you can use it even without one, for testing and learning what new is there, it should be fully working. It is found in `libyang2` branch.

**Comment by Tanco-K** [comment]
@michalvasko Thanks!
