### ISSUE TITLE
lyd_path (ly2)

### ISSUE THREAD

**Issue by choppsv1** [CESNET/libyang#1317]
lyd_path changed it's signature it is not clear that it has the same functionality from the documentation (it doesn't say the output is usable as a path value). Perhaps clarifying this and a mention in the transition is worthwhile.

**Comment by rkrejci** [comment]
Thanks for reporting! I have clarified names and mainly the description of the path types being passed to `lyd_path()`. Also the transition manual was slightly updated. Please check if it is clear now.
