### ISSUE TITLE
Unknown element for an if-feature

### ISSUE THREAD

**Issue by Brahemya** [CESNET/libyang#1324]
I have a libyang error with unknown element for a notification name(not1), which is conditioned by the if-feature statement. I would like to ask that the unknown element error could be due to the if-feature, I mean the server does not support featureX and because of that could appear the unknown element error for not1?

```
notification  not1
{
  if-feature "featureX"
  leaf l1 
 {
  default:
 }
}
```

**Comment by michalvasko** [comment]
Yes, if the feature is not enabled, the `not1` notification is treated as non-existing.

**Comment by Klara2143121** [comment]
Thank you!
