### ISSUE TITLE
 lyd_parse_mem() returns NULL when input xml string is too long

### ISSUE THREAD

**Issue by ankit7gup** [CESNET/libyang#1330]
Hi, 
I am using  lyd_parse_mem() API to parse the data and use it as an input to sr_edit_batch() API for sysrepo.
However I am observing some issue, where while passing an xml of bit long data, the mentioned API returns as NULL, while it works fine when data size is less.

data = lyd_parse_mem((struct ly_ctx *)ctx, xmldata.c_str(), LYD_XML, LYD_OPT_EDIT);

I am using libyang latest version from the "master" branch.

Thanks in Advance!

Regards,
Ankit

**Comment by michalvasko** [comment]
Please provide more information. What size succeeds and what fails? What is the error on failure?

**Comment by ankit7gup** [comment]
Hi Michal, 

There are no errors on screen except, the API returns NULL.
Specific to my test case the API fails when the xml string has 33936 characters, while works when xml has 18151 characters. 

Regards,
Ankit

**Comment by michalvasko** [comment]
I would need the exact input you have used and the corresponding YANG modules so that it can be loaded. I tried it with some testing module and data and it worked fine for file size 38893.

**Comment by ankit7gup** [comment]
Hi Michal, Please find attached the yang modules and the xml used for the test. Please refer README for the details. 

[libyang.zip](https://github.com/CESNET/libyang/files/5794492/libyang.zip)

**Comment by michalvasko** [comment]
This is the error message:
```
libyang[0]: Unknown element "measConfigAnr". (path: /gnb_vs_config:gnbvs/gnbCuConfig[id='0']/gnbCellCuVsConfig[id='0']/measConfigSA/measConfigAnr)
```
The reason why you do not see the message is because *sysrepo* sets *libyang* logging for its purposes when direct logging is turned off and all errors are read from the *libyang context*. You can try doing that, too, with `ly_err_first()` and `ly_err_print()`.

**Comment by ankit7gup** [comment]
Thanks Michal, Great help!

I shall enable the libyang logging and then try the same.
