### ISSUE TITLE
Sporadic crashes when running libyang2 on multiple pthreads

### ISSUE THREAD

**Issue by rwestphal** [CESNET/libyang#1344]
Code to reproduce the problem: https://pastebin.com/raw/5mFVYx0M

In this code, a thousand pthreads are created in a loop. A separate libyang context is created for each pthread and YANG modules are loaded into them in parallel. Running this code causes libyang to crash more often than not with backtraces like this: https://pastebin.com/raw/Ssc2eeQN

Those crashes don't happen if `thread_main()` is called sequentially instead of in parallel (using pthreads). I suspect there's a data race going on somewhere which might explain the unpredictable behavior with pthreads.

@michalvasko Opening this issue as per your request so that we can keep track of this problem.

**Comment by rkrejci** [comment]
Should be solved now in libyang2 branch, thanks!

**Comment by rwestphal** [comment]
I confirm the crashes were fixed. Now I can run yang2-rs's unit tests in parallel :) Thanks very much!
