### ISSUE TITLE
Skip parsing extension

### ISSUE THREAD

**Issue by fanchanghu** [CESNET/libyang#1345]
Hi,
We need skip some extensions in our modules for saving memory. Then I found that the return value `2` of `lyext_check_position_clb` could be suitable for this case as decribed in its comment. However, this feature does not be supported now. So I want to do it myself in libyang1, is it OK or any suggestion?

**Comment by rkrejci** [comment]
Well, it's a bug that the value `2` is not handled as described, but I'm not sure that using it for your purpose will help you. It just avoids instantiating the extension in the module, the plugin is still present. Wouldn't be the solution just to avoid loading the plugin at all? Or is the intention to avoid instantiating the extension only in specific places/modules, so there will be some places where the extension is supposed to be instantiated?

**Comment by fanchanghu** [comment]
What we need is just avoiding instantiating the extension in the module. We have some extensions which are used to describe the node, such as chinese description, short name and so on, these extensions are only used by the NETCONF client. So we hope avoiding instantiating them in the server.

**Comment by rkrejci** [comment]
ok, then I have no problem with accepting the fix to correctly handle the return values of this callback
