### ISSUE TITLE
ly2: LYS_CONFIG_W not being set for "case" statements in the compiled schema tree

### ISSUE THREAD

**Issue by rwestphal** [CESNET/libyang#1350]
While the [documentation](https://netopeer.liberouter.org/doc/libyang/libyang2/html/group__scnodeflags.html) states that the `LYS_CONFIG_W` flag can be set for "case" statements in the compiled schema tree, that's not the behavior I've observed in my tests.

Here's a code snippet to reproduce the problem: https://gist.githubusercontent.com/rwestphal/51593172a1a7e4dd702022628796492e/raw/98b05c2277e8d84f62fcb80067e69b76b53e15a0/ly2-snode-flags.c

And here's its output:
```
/ietf-routing:routing/control-plane-protocols/control-plane-protocol/ietf-isis:isis/preference/granularity/detail/internal: 1
/ietf-routing:routing/control-plane-protocols/control-plane-protocol/ietf-isis:isis/preference/granularity/detail: 0
/ietf-routing:routing/control-plane-protocols/control-plane-protocol/ietf-isis:isis/preference/granularity: 1
/ietf-routing:routing/control-plane-protocols/control-plane-protocol/ietf-isis:isis/preference: 1
/ietf-routing:routing/control-plane-protocols/control-plane-protocol/ietf-isis:isis: 1
/ietf-routing:routing/control-plane-protocols/control-plane-protocol: 1
/ietf-routing:routing/control-plane-protocols: 1
/ietf-routing:routing: 1
```

Notice how the `LYS_CONFIG_W` flag is set for all nodes ("internal" and its ancestors) except for the "detail" case statement.

One other minor issue I'd like to report is that `lysc_path()` requires the user-supplied buffer to be zero-initialized, which has performance implications. Wouldn't it possible to make that function more user-friendly by making it add a trailing null character to the generated path?

**Comment by rkrejci** [comment]
well, the `case` statement does not have the `config` substatement, so it is a question what is the bug here - if we should add the correct config flag into the compiled case node or if we should fix the documentation.

Do you see some benefits from having the flag there?

**Comment by rkrejci** [comment]
At least for now, I have fixed the docs. If you will come up with some use cases why it would be good to have the flags there, please reopen the issu.

**Comment by rwestphal** [comment]
> At least for now, I have fixed the docs. If you will come up with some use cases why it would be good to have the flags there, please reopen the issu.

Sorry for the late response, I was traveling.

My use case is an auto-rendered CLI that generates configuration commands from YANG modules. This CLI iterates over all schema trees and skips read-only subtrees. I noticed there was something wrong when some configuration commands were missing in the CLI, and it took me a while to find the culprit (`LYS_CONFIG_W` not being set for "case" statements).

I think the documentation fix should be enough to avoid further confusion in the future.

> well, the case statement does not have the config substatement

Even though the "case" statement doesn't have the "config" substatement, it inherits that property from its parent node. Ideally it'd be nice to have that reflected in the code, but it's easy to work around that problem on the user side (just add an exception to "case" statements when checking the RW flags).

Regarding `lysc_path()`, do you have any thoughts on my suggestion?

**Comment by michalvasko** [comment]
> Even though the "case" statement doesn't have the "config" substatement, it inherits that property from its parent node. 

Yeah, we missed the part in the specification, it should be inherited now.

> Regarding lysc_path(), do you have any thoughts on my suggestion?

Right, it was a bug since it was not even mentioned in the docs. Should work properly now.

**Comment by rwestphal** [comment]
Thanks Michal!!
