### ISSUE TITLE
ly2: confused about lysc_node_children() and lysc_node_children_full()

### ISSUE THREAD

**Issue by rwestphal** [CESNET/libyang#1352]
According to the documentation, the difference between these two functions is that the first skips RPC/Action input and output nodes while the second doesn't. Looking at the code, however, they seem to equivalent. Both have a `flags` parameter that is used to control the behavior for RPC/Action nodes, which aren't skipped in any case.

**Comment by rkrejci** [comment]
There is a difference, but I also missed it the first time. The `lysc_node_children_p()` returns pointer to the output's/input's data member while `lysc_node_children_full()` returns the output/input themselves. I'm going to rewrite it to avoid code duplication and to make the difference more clear.
