### ISSUE TITLE
libyang2 schema parsing error

### ISSUE THREAD

**Issue by awesomenode** [CESNET/libyang#1355]
Hi!

When using libyang2 I ran into the following issue when I tried loading schemas with
multiple augments:
```
libyang[1]: Container "conditional" changed to presence because it has a meaning from its "must" condition.
libyang[0]: Invalid absolute-schema-nodeid value "/t:basics/t:subbasics" - target node not found. (path: /test3:{augment='/t:basics/t:subbasics/t2:decision'})
ly_parse_error: Invalid absolute-schema-nodeid value "/t:basics/t:subbasics" - target node not found
```

Seems like there are some issues with parsing schemas with augments? This worked before
with libyang1.

I attached the code of the test software I used to parse the schemas into context, and the
YANG files.

libyang2 version: 3e1f655e054ad017edb72611fb523f4595f91309

Thanks!
[ly2_parse.tar.gz](https://github.com/CESNET/libyang/files/5830569/ly2_parse.tar.gz)

**Comment by rkrejci** [comment]
Thanks, should be fixed in current libyang2
