### ISSUE TITLE
question: why rpc module and xml data must be in same order?

### ISSUE THREAD

**Issue by yanjunxi** [CESNET/libyang#136]
We may need use common json object which is in alphabetical order to deal the process data.
The previous version doesn't limit the order.

Thanks.

**Comment by michalvasko** [comment]
Hi,
I am not sure what exactly are you asking, but RPC input/output must be ordered because it is written [here](https://tools.ietf.org/html/rfc7950#section-7.14.4). However, this is only defined for XML, not JSON. Are you communicating using RESTCONF or why do you use JSON?

Regards,
Michal

**Comment by rkrejci** [comment]
Can you be more specific? When the ordering problem appears?

**Comment by yanjunxi** [comment]
We will research to solve the problem during json deal object.

Thanks.
