### ISSUE TITLE
ly2: using when causes presence set

### ISSUE THREAD

**Issue by choppsv1** [CESNET/libyang#1367]
With libyang2 use of when statements is causing containers to be marked as presence containers, this seems wrong. In FRR it is causing failures b/c FRR expects callbacks to be defined for all presence containers and is failing b/c the containers are having their presence status changed automatically by libyang2.

For example, why is the container ```ipv4-flowspec``` being changed to a presence container in the below module? It is not a presence container.

```
module main {
  yang-version 1.1;
  namespace "http://example.com/main";
  prefix m;

  leaf afi-safi-name {
    type string;
  }
  container ipv4-flowspec {
    when "../afi-safi-name = 'ipv4-flowspec'";
    leaf flowspec-config {
      type uint8;
    }
  }
}
```

**Comment by michalvasko** [comment]
This is our solution (indirectly supported on the netmod mailing list) for amending the insufficient `container` specification in RFC 7950. Specifically, it is mentioned that the existence of the container in data has no semantic meaning. So in cases where there is a meaning (such as this one), we change the container to `presence`, which then gives it meaning even according to the specs.

I do not know what exactly FRR does but *libyang2* behavior will remain this way (it solves many cases of weird or unexpected behavior) so it should adapt.

**Comment by choppsv1** [comment]
So the interpretation is that the semantic meaning of the presence of ```ipv4-flowspec``` container is that it implies that the ```afi-safi-name``` value is ```ipv4-flowpsec```?

**Comment by choppsv1** [comment]
FWIW I think this might be an incorrect interpretation. The ```when``` statement is modifying the schema, but it does make the schema conditional based on the data store value though. If there was no ```flowspec-config``` data present, then the parent container being non-presence would not be present in the datastore either. Consider what the schema looks like when the ```when``` statement is not present. IOW the only thing that should change is the schema, not the instance data I think.

Do you have a pointer to the thread that supported this on netmod, by any chance? I'd like to read through it.

**Comment by michalvasko** [comment]
We do not even have to talk about some theoretical problems, *libyang* needs to solve all practical problems. Imagine this situation. There are no data on a server and these data should be created:
```xml
<afi-safi-name xmlns="http://example.com/main">name</afi-safi-name>
<ipv4-flowspec xmlns="http://example.com/main">
</ipv4-flowspec>
```
Should an error be printed because of the unsatisfied `when`? No matter what you answer, I can find references in RFC 7950 that will contradict your answer. That is what we are solving in *libyang2*.

**Comment by choppsv1** [comment]
Yes, an error should be reported b/c the when is not statisfied. That's the point of the when after all, to modify the schema and there is no ipv4-flowpec in the schema as the when statement is not satisfied.

From 7950: 7.5.1.  Containers with Presence

   YANG supports two styles of containers, those that exist only for
   organizing the hierarchy of data nodes and those whose presence in
   the data tree has an explicit meaning.

You are talking about "implicit" meaning here, not explicit. that is not what 7950 says. Further on in that section:

   YANG calls this style a "presence container", and it is indicated
   using the "presence" statement, which takes as its argument a text
   string indicating what the presence of the node means.

How can there be a value for the presence statement when it has not been supplied?

**Comment by choppsv1** [comment]
FWIW I sent an email to yang-doctors@ietf.org for their thoughts.

**Comment by michalvasko** [comment]
> Yes, an error should be reported b/c the when is not statisfied.

RFC 7950 7.5.1:
```
In particular, the presence of the
container node with no child nodes is semantically equivalent to the
absence of the container node.
```
So this means that whether you create the `ipv4-flowspec` container or not, it must be semantically equivalent meaning you cannot in one case report an error and not report it in the other, I would definitely not call that semantic equivalence.

> FWIW I sent an email to yang-doctors@ietf.org for their thoughts.

Oh don't, there were so many threads discussing this already. It takes some time to find anything there so I am reluctant to search it for you but you can do it yourself. Look at the `yang-next` tracker, [this issue](https://github.com/netmod-wg/yang-next/issues/88), for example.

**Comment by choppsv1** [comment]
I believe you are conflating 2 different things here. "When" makes conditional schema. Presence is an attribute of containers which are defined by the schema. The text you quote from 7.5.1 exists outside of the "when" conditionalization. You would apply the presence logic after you determine the schema itself through using the "when" logic. In this case there is no problem. Directly, if the when is not satisfied there is *no* ipv4-flowspec container in the schema so 7.5.1 doesn't apply as there is no container schema node to talk about, and someone trying to add a value for it to the datastore should receive an error.

**Comment by michalvasko** [comment]
We are now starting to talk about our interpretations of what is said there so I am not sure any agreement is possible. I can argue that when you are trying to create any NP container without children, it can simply be ignored since it has no meaning and return no error. I suppose you can say that in this case I do not even know that `ipv4-flowspec` is a `container` because it is "not in the schema". Then let me modify your YANG to make it even more interesting:
```yang
module main {
  yang-version 1.1;
  namespace "http://example.com/main";
  prefix m;

  container afi-safi-name {
    leaf l {
      type string;
    }
  }
  container ipv4-flowspec {
    when "../afi-safi-name";
    leaf flowspec-config {
      type uint8;
    }
  }
}
```

**Comment by choppsv1** [comment]
Aha, I had actually thought about this as I looked into the errors I was seeing -- I was thinking this was what you were doing originally b/c it made more sense to me. This is a case where the when *refers* to another node, and does that when then have an affect on the *referred to* node? I think your case is stronger there. b/c the presence of the referred to node has explicit meaning (it enables or disables other schema).

**Comment by michalvasko** [comment]
Okay, so ideally `ipv4-flowspec` should not be made presence in your original case and in my modified case, it is actually `afi-safi-name` container that should be made presence. However, detecting all these various use-cases seems like a waste of effort so we simplified it to the functionality you see.

I am not sure what exactly FRR does but as long as it is relevant to some extent, we can discuss possible solutions.

**Comment by choppsv1** [comment]
I can work around the problem by a hack. The code requires that all presence nodes have callbacks to manage them in FRR. I have to create a bunch of no-op callbacks I guess. The bigger issue though is the affect on the datastore as it will look very wrong with all these when toggled nodes that shouldn't be there.

For the second example you gave the ```afi-safi-name``` contains no when statement, is the code actually marking it as presence container due to the when referring to it? That is what we think is the case it makes sense, but I don't think the code is doing that.

FWIW, I received a reply from @mbj4668 (Martin Bjorklund) on yang-doctors:

> > My key point in that thread was that the when statement modifies the schema prior to the presence attribute logic being applied. This prsence logic in particular from 7.5.1 that says there must be no semantic difference based on the presence of the container or not for it to be a NP container. I'm claiming if the when is false then the container is not logically in the schema for one to talk about it's presence semantics or not.

> I agree with you.

> > That thread also then raises the point about when statements that refer *to* another node and does that make that other *referred to* node now have presence semantics. :)

> Well, in the last example in that thread, the when expression will always evaluate to true.
```

**Comment by michalvasko** [comment]
> For the second example you gave the afi-safi-name contains no when statement, is the code actually marking it as presence container due to the when referring to it? That is what we think is the case it makes sense, but I don't think the code is doing that.

Yes, the code is always putting `presence` to the `container` with the `when`. Like I said previously, it is a simplification but it solves all the problems. We did not really think it may cause any issues.

**Comment by choppsv1** [comment]
Can we add an additional flag to indicate this implicit setting of the presence bit? Then when FRR is looking to make sure all presence containers have a create/destroy callback (frr code) it can check this flag an not require those callbacks in this case. I was adding no-op functions but it is turning into a ridiculously large number of them.

**Comment by choppsv1** [comment]
> We are now starting to talk about our interpretations of what is said there so I am not sure any agreement is possible. I can argue that when you are trying to create any NP container without children, it can simply be ignored since it has no meaning and return no error. I suppose you can say that in this case I do not even know that `ipv4-flowspec` is a `container` because it is "not in the schema". Then let me modify your YANG to make it even more interesting:
> 
> ```yang
> module main {
>   yang-version 1.1;
>   namespace "http://example.com/main";
>   prefix m;
> 
>   container afi-safi-name {
>     leaf l {
>       type string;
>     }
>   }
>   container ipv4-flowspec {
>     when "../afi-safi-name";
>     leaf flowspec-config {
>       type uint8;
>     }
>   }
> }
> ```
> 
> and the data being set can be
> 
> ```
> <afi-safi-name xmlns="http://example.com/main">
> </afi-safi-name>
> <ipv4-flowspec xmlns="http://example.com/main">
> </ipv4-flowspec>
> ```
> 
> or
> 
> ```
> <ipv4-flowspec xmlns="http://example.com/main">
> </ipv4-flowspec>
> ```

FWIW, isn't the secon example you give here wrong? There's no afi-safi node so the when statement is false so the ipv4-flowspec is not valid.

**Comment by michalvasko** [comment]
No, it is not wrong because for XPath, the NP container is always treated as [existing](https://tools.ietf.org/html/rfc7950#page-51). The main problem with these container is probably something else, specific to *libyang* although in our experience the only reasonable thing to do. In *libyang* the NP container always exist according to the rule in the XPath meaning they are treated as a specific kind of a default value. But when they have a `when`, they do not have to always exist, which causes additional problems so the container is simply made presence. I am not sure, maybe it would be possible to solve without it, I do not remember the exact issue we had with it but I hope that now that should not be a problem.
