### ISSUE TITLE
ly2: yanglint fails with yang library error

### ISSUE THREAD

**Issue by choppsv1** [CESNET/libyang#1371]
Trying this simple example fails with a warning about yang library content-id missing:

data.xml:
```
<afi-safi-name xmlns="http://example.com/main">a</afi-safi-name>
```
main.yang:
```
module main {
  yang-version 1.1;
  namespace "http://example.com/main";
  prefix m;

  leaf afi-safi-name {
    type string;
  }
}
```
Fails:
```
$ yanglint --format=json data.xml
libyang err : Mandatory node "content-id" instance does not exist. (Schema location /ietf-yang-library:yang-library/content-id.)
YANGLINT[E]: Failed to parse input data file "data.xml".
```

**Comment by michalvasko** [comment]
This was actually correct and I assume you expected a different result because the old `yanglint` behaves differently. So, the new `yanglint` now behaves the same way, with some improvements in the parameters description.

**Comment by choppsv1** [comment]
> This was actually correct and I assume you expected a different result because the old `yanglint` behaves differently. So, the new `yanglint` now behaves the same way, with some improvements in the parameters description.

So how do I make it work? Does using yanglint now requirie writing a yang library?

**Comment by michalvasko** [comment]
No, the default behavior of the non-interactive `yanglint` should now be the same so you do not have to do anything. But, there is now an option to put the `ietf-yang-library` module into the context. Also, the new `yanglint` has `--presence` option, which you should take a look at. It should probably be used for most cases, except with the latest changes it should not really matter anymore.
