### ISSUE TITLE
libyang2 parsing issue when augmenting grouping

### ISSUE THREAD

**Issue by awesomenode** [CESNET/libyang#1377]
Hi!

By fixing the [previous example](https://github.com/CESNET/libyang/issues/1370) following your instructions, I got a new parse error with ietf-keystore module:

```
libyang[0]: Augment target node "key-type" in grouping "symmetric-key-grouping" was not found. (path: /ietf-keystore:generate-symmetric-key/output/{uses='ks:symmetric-key-
grouping'}/{uses='ct:symmetric-key-grouping'})
```

There's seems to be an issue with the symmetric-key-grouping augmenting the grouping with the same name from ietf-cypto-types?

I'll attach the parser software (now using lys_parse()), and the necessary files.

libyang2 version: 770d3fc1c22a8e6445b28cb8a910c0e8c9f7c1d4
[ks_error.tar.gz](https://github.com/CESNET/libyang/files/5872879/ks_error.tar.gz)

Thanks!

**Comment by michalvasko** [comment]
Please try it with the latest *libyang2*, it seems to have been fixed by the other changes.

**Comment by awesomenode** [comment]
Seems to be working fine now, thanks!
