### ISSUE TITLE
Requirement about validating data based on difference

### ISSUE THREAD

**Issue by fanchanghu** [CESNET/libyang#1382]
Hi,
We have a big data tree in use, which has been validated, and users only change a small part of it usually. But now we have to validate all the data tree in such case, which needs lots of time. So I hope libyang can support validating data based on the difference between changed data and used data.

**Comment by michalvasko** [comment]
Current *libyang* does this, specifically it caches what parts of the data were validated and are still valid and what were changed and need to be validated again. As it turned out, because of YANG high complexity, this is a bad idea and *libyang* version 2 does no caching like that.

**Comment by fanchanghu** [comment]
So this means libyang2 will always validate all the data tree? will it be more slow than libyang1?

And even for libyang1, I have an issue about poor performance of `when` when the `when` is defined in a list, which has thousands of instances, even if the changed data has nothing to do with the list.

**Comment by michalvasko** [comment]
> So this means libyang2 will always validate all the data tree?

Yes, it will always validate the whole tree presented for validation-

> will it be more slow than libyang1?

One may think so but preliminary measurements show it is faster and we have not even performed real benchmarks and any optimizations based on them. Again, the complexity of YANG is much higher than it seems so the intuitive ideas usually do not work.

> And even for libyang1, I have an issue about poor performance of when when the when is defined in a list, which has thousands of instances, even if the changed data has nothing to do with the list.

That is possible but *libyang* version 1 will not change in this aspect. But once there is an official release of *libyang* version 2, try to use it an if you think it is slow, create an issue with your exact use-case (YANG module and validated data) and we can talk about possible improvements.
