### ISSUE TITLE
Duplicate Values NOT accepted in a leaflist of a NOTIFICATION

### ISSUE THREAD

**Issue by Spoorthi-kr** [CESNET/libyang#1387]
RFC 7950 allows the duplicate Values in the non-config data.  
https://tools.ietf.org/html/rfc7950#section-7.7
* In configuration data, the values in a leaf-list MUST be unique. 

But when I tried to parse the values of a leaflist I got the following error:
**libyang[0]: Duplicated instance of "stats-table" leaf-list ("0"). (path: /stats/object='xyz']/stat-result[id='0']/stats-table[.='0'])**

Could you please help.

**Comment by michalvasko** [comment]
i have just tested it in `yanglint`, works fine, so there is some problem in your use-case. Is the leaf-list really defined as `config` `false`? Are you validating the data with the correct options?

**Comment by Spoorthi-kr** [comment]
The Yang Model I have used for parsing is the below one, it is a list with config=false .
stats-table should also be considered as a non configurable parameter right?
But stats-table is being considered by libyang as a configurable parameter.

list stat-result {
      key "id";
      config false;
      leaf id{
        type uint32;
      }
      leaf-list stats-table {
        type uint32;
      }
    }

**Comment by michalvasko** [comment]
I think there is some confusion. I did not manage to find anything in [the specs](https://tools.ietf.org/html/rfc7950#section-7.8) that would allow duplicate state list instances with keys so I would say this is correctly forbidden.

**Comment by Spoorthi-kr** [comment]
Adding to my comment, This is a "notification" type. I tried to run the below exampIe with Yanglint and was able to reproduce the issue. Please check with this one.

[yang-notif-issue.zip](https://github.com/CESNET/libyang/files/5964621/yang-notif-issue.zip)

**Comment by michalvasko** [comment]
Right, should be fixed now.
