### ISSUE TITLE
Not found issue

### ISSUE THREAD

**Issue by Brahemya** [CESNET/libyang#1397]
Hello,

I would like to ask why the regarded error appear when urn:ietf:params:netconf:capability:writable-running:1.0 is supported, what other capabiliy is needed to  modify running configuration datas. Thank you in advance

**Comment by michalvasko** [comment]
No other capability should be required but be careful, NETCONF capabilities are one thing, enabled YANG features another. I do not know exactly what your use-case is but I would say you do not have `writable-running` feature enabled in your `ietf-netconf`.
