### ISSUE TITLE
libyang2 segfault while parsing schema

### ISSUE THREAD

**Issue by awesomenode** [CESNET/libyang#1403]
Hi!

I made a dummy YANG module, which augments ietf-interfaces. Libyang segfaults, when I
try to parse it using lys_parse().

The error appeared after I inserted some dummy description to each leaf, if I remove them,
the libyang successfully proceeds.

Here is the backtrace from the core dump:

> #0  0x00007fdfb032aff0 in lys_compile_unres_xpath (ctx=0x7ffe520f78e0, node=0x5590a9e85390, unres=0x7ffe520f89c0) at libyang/src/schema_compile.c:998
> #1  0x00007fdfb032c1f0 in lys_compile_unres_glob (ctx=0x5590a9e43260, unres=0x7ffe520f89c0) at libyang/src/schema_compile.c:1351
> #2  0x00007fdfb0350e9d in lys_parse (ctx=0x5590a9e43260, in=0x5590a9e64a60, format=LYS_IN_YANG, features=0x0, module=0x0) at libyang/src/tree_schema.c:1278
> #3  0x00005590a8251098 in add_yang_files (ctx=0x5590a9e43260) at ly_test.c:48
> #4  0x00005590a825115c in main () at ly_test.c:61

I attached the YANG files and the parser code.

libyang2 version: 2d5f6df73b8ed263c80bf5027bc5b569cc29962a
[if_error.tar.gz](https://github.com/CESNET/libyang/files/5905337/if_error.tar.gz)

Thanks!

**Comment by michalvasko** [comment]
Should work properly now.

**Comment by awesomenode** [comment]
Yes, it works fine now, thanks!
