### ISSUE TITLE
XML name char check

### ISSUE THREAD

**Issue by fanchanghu** [CESNET/libyang#1404]
Hi, this condition `c >= 0x2030f && c <= 0x2040` could never be true.

https://github.com/CESNET/libyang/blob/8c254b2b5d89d15244941bdfcff28aef141efd9f/src/xml_internal.h#L36-L44

**Comment by rkrejci** [comment]
the same bug is also in libyang2, it is just a typo - the expected value defined by [XML standard](https://www.w3.org/TR/xml/#NT-NameChar) is `0x203f`

**Comment by rkrejci** [comment]
Thanks, should be fixed now in `devel` and `libyang2` branches.
