### ISSUE TITLE
Invalid value "*" in "access-operations" element.(/ietf-netconf-acm:access-operations)

### ISSUE THREAD

**Issue by ravac1** [CESNET/libyang#1405]
Hello,

In version 1.0.215, when reading schema from ietf-netconf-acm.yang, this error appears:
**Invalid value "*" in "access-operations" element.(/ietf-netconf-acm:access-operations)**

The file looks like this: https://tools.ietf.org/html/rfc8341 (see leaf access-operations)

The error did not appear in version 1.0.167. Both versions were built and used in the same way.

Could you tell if this is an issue introduced by the new version or something else is wrong?

Thank you!

**Comment by michalvasko** [comment]
Please provide a way to reproduce this, tested with `yanglint` and the attached files, no problems found.

**Comment by ravac1** [comment]
thank you for answer . I will try to find a way to reproduce it that can be provided

**Comment by michalvasko** [comment]
Can you attach your `/ram/yangmodel/ietf-netconf-acm.yang`?

**Comment by ravac1** [comment]
Attached:
[ietf-netconf-acm.zip](https://github.com/CESNET/libyang/files/5931022/ietf-netconf-acm.zip)

**Comment by michalvasko** [comment]
Okay, seems there is nothing wrong with the module. Note that I am using *libyang* from `devel`, which has some fixes, I doubt any of them are related to this but please try it anyway. Then you must provide the exact steps of reproducing the problem, otherwise I cannot help you.

As for the *netopeer2* output, what exactly is the scenario? You have a fresh install of *sysrepo* and *netopeer2*, you run it and see the error?

**Comment by ravac1** [comment]
Using libnetconf2 1.1.36 and libyang 1.0.215 on netconf client side.
The error happens immediately after capabilities exchange (the hello from server contains urn:ietf:params:xml:ns:yang:ietf-netconf-acm and does not contain yang-library) when reading schema from local file.
I'll give it a try with devel too. Thanks!

**Comment by ravac1** [comment]
Hi. same result with devel. However, the cause appears to be this change in parser.c:

v1.0.167:
    precomp = pcre_compile(perl_regex, PCRE_ANCHORED | PCRE_DOLLAR_ENDONLY | PCRE_NO_AUTO_CAPTURE,

v1.0.215:
    precomp = pcre_compile(perl_regex, PCRE_UTF8 | PCRE_ANCHORED | PCRE_DOLLAR_ENDONLY | PCRE_NO_AUTO_CAPTURE,

By changing back as it was in 1.0.167, everything works fine in my case.
Am I missing some dependencies or is this an issue in the current version?

**Comment by michalvasko** [comment]
Well, I think UTF8 support does not have to be enabled in *pcre* (meaning it may be off, maybe even by default) but I would hope at least for some obvious error (it did print something like that on another occasion). You can look into that, try to compile it on your own with this feature enabled.

**Comment by rkrejci** [comment]
Hi, pcre is definitely supposed to be compiled with the unicode support, see the [README.md](https://github.com/CESNET/libyang/blob/master/README.md)

**Comment by ravac1** [comment]
It works with UTF support on pcre. 
Thanks a lot for your time and support!
