### ISSUE TITLE
'Invalid keyword' for bare + sign standing alone as unquoted string

### ISSUE THREAD

**Issue by toanle** [CESNET/libyang#1410]
test.yang
```
module main {
  yang-version 1.1;
  namespace "http://example.com/main";
  prefix m;
  container timezone {
    description
      "Configure time zone";
    leaf offset {
      type enumeration {
        enum +;
        enum -;
      }
    }
  }
}
```
Note of no double-quotes around + sign in the statement  `enum +;`
```
$ LIBYANG_EXTENSIONS_PLUGINS_DIR="`pwd`/src/extensions" LIBYANG_USER_TYPES_PLUGINS_DIR="`pwd`/src/user_types" ./yanglint ~/work/yang_issue_with_enum/test.yang
err : Invalid keyword "+".
err : Module "main" parsing failed.
```
The `enum +;` is valid according to below quote "Martin Björklund <mbj+ietf@4668.se>" replied to me

> Hi,
> 
> 6.1.3 says:
> 
>    An unquoted string is any sequence of characters that does not
>    contain any space, tab, carriage return, or line feed characters, a
>    single or double quote character, a semicolon (";"), braces ("{" or
>    "}"), or comment sequences ("//", "/*", or "*/").
> 
> So, with:
> 
>   +
> 
> we have a sequence (of one character) that matches this rule.
> 
> From this text alone follows that + is a legal unquoted string.
> 
> 6.1.3 further says:
> 
>    If a quoted string is followed by a plus character ("+"), followed by
>    another quoted string, the two strings are concatenated into one
>    string
> 
> this is clearly not the case in:
> 
>   enum +;
> 
> 
> /martin

It looks like something is not correct at libyang parser. How do you think?

**Comment by fredgan** [comment]
According to my understanding of the RFC about the sign `+`,  a sign `+ `without quotation indicates strings concatenated,  `+`  within the quotation(`''` or `""`)  is a plus character string("+"),  otherwise,  it maybe impossible to distinguish the two(`+`, `"+"`). 

The plus sign(`+`) in `enum +` cannot be used as a character string , you can add a quotaion(`'+'` or `"+"`), it's ok, so  I think the implemetation about the sign `+`  is no problem.

**Comment by michalvasko** [comment]
@toanle I would say you are right and this `enum` value should be accepted. However, *libyang* YANG parser is quite difficult to maintain and do any changes, it will not be fixed (unless someone provides a patch). A workaround was mentioned by @fredgan, change the string a quoted one and it will work.

I have tested the module with *libyang* version 2 (which will be officially released within a month or so) and it was loaded successfully.
