### ISSUE TITLE
ly2: missing support for absolute paths in lysc_path()

### ISSUE THREAD

**Issue by rwestphal** [CESNET/libyang#1411]
The [1.x -> 2.x transition manual](https://netopeer.liberouter.org/doc/libyang/libyang2/html/transition.html) says that `lys_path()` and `lys_data_path()` were replaced by `lysc_path()`, and there's a related note about "redesigned functionality" without further details.

While `lysc_path()` with the `LYSC_PATH_LOG` and `LYSC_PATH_DATA` options should cover most uses cases, I miss libyang1's `lys_path()` ability to generate absolute schema paths (which I need for a tool that generates YANG deviations). Any chance that functionality could be made available in libyang2 (e.g. by adding a new `LYSC_PATH_TYPE` option)?

**Comment by michalvasko** [comment]
What makes you think `LYSC_PATH_LOG` does not generate absolute schema paths?

**Comment by rwestphal** [comment]
Sorry, I should've been more clear. What I meant is absolute schema paths where all nodes have a prefix.

Example: `/ietf-routing:routing/ietf-routing:control-plane-protocols/ietf-routing:control-plane-protocol/ietf-mpls-ldp:mpls-ldp/ietf-mpls-ldp:global`

Instead of: `/ietf-routing:routing/control-plane-protocols/control-plane-protocol/ietf-mpls-ldp:mpls-ldp/global`

libyang1 was capable of generating such paths with `lys_path()` (without the `LYS_PATH_FIRST_PREFIX` option), whereas libyang2 can't do that right now.

It turns out, however, that YANG deviations don't actually need fully-specified schema paths as I previously thought. So using `lysc_path()` with the `LYSC_PATH_LOG` option is sufficient to address my use case.

I'll close this issue since I can't think of any scenario where fully-specified schema paths would be necessary.

**Comment by michalvasko** [comment]
Well, deviations expect a YANG schema path, which is actually something different altogether. You are right with the example and it is a hybrid of a schema and JSON path. You are then manually replacing module names with module prefixes? Still, the paths do need to be fully prefixed (unless you are deviating a node in your own module) so I am surprised it works for you.

**Comment by rwestphal** [comment]
> Well, deviations expect a YANG schema path, which is actually something different altogether. You are right with the example and it is a hybrid of a schema and JSON path. 

Indeed, that makes sense after re-reading the RFC. In that case, would it be possible to extend `lysc_path()` to support generating fully-prefixed schema paths?

> You are then manually replacing module names with module prefixes? 

The fully-prefixed schema path I've shown in my example was generated using libyang1's `lys_path()`.

> Still, the paths do need to be fully prefixed (unless you are deviating a node in your own module) so I am surprised it works for you.

Please ignore that. I've made a mistake while testing deviations using yanglint, which led me to a wrong conclusion.

The only issue I found is that printing a module in the tree format doesn't take into account the deviations that were applied to that module. Is that the expected behavior in libyang2? IIRC libyang1 was different in this regard.

**Comment by michalvasko** [comment]
> Indeed, that makes sense after re-reading the RFC. In that case, would it be possible to extend lysc_path() to support generating fully-prefixed schema paths?

So what exactly do you need? For all the nodes to have their module name as prefix? Because for deviations there should be the module prefix instead.

**Comment by rwestphal** [comment]
> So what exactly do you need? For all the nodes to have their module name as prefix? Because for deviations there should be the module prefix instead.

Using the module prefix would be ideal, but if that's not possible I can change the module prefix to its name when importing it, so that the deviations work ([example](https://pastebin.com/raw/Q3s5cfPS)).

**Comment by michalvasko** [comment]
So we decided not to use the prefixes in the path because they may not be unique and this way we have one unified path format for both schema and data.

But now that I think about it, I am not really sure you need a new format, you should be able to simply use the `LYSC_PATH_LOG`. You must go node-by-node, if it has prefix, remember it and print its module prefix instead, if it does not, print the remembered module prefix. If there is a new format that prints prefixes for all the nodes, it will only save you the module inheritance, a minor detail.

**Comment by rwestphal** [comment]
> So we decided not to use the prefixes in the path because they may not be unique and this way we have one unified path format for both schema and data.

Fair enough.

> But now that I think about it, I am not really sure you need a new format, you should be able to simply use the `LYSC_PATH_LOG`. You must go node-by-node, if it has prefix, remember it and print its module prefix instead, if it does not, print the remembered module prefix. If there is a new format that prints prefixes for all the nodes, it will only save you the module inheritance, a minor detail.

What I ended up doing is to construct the fully-prefixed path by hand with the following function (Rust code):
```rust
fn gen_fully_prefixed_path(snode: &SchemaNode) -> String {
    let mut path = String::new();

    for snode in snode.inclusive_ancestors().iter().rev() {
        // Append node name prefixed by its module prefix.
        write!(path, "/{}:{}", snode.module().prefix(), snode.name()).unwrap();
    }

    path
}
```

That code is of course susceptible to prefix collisions but I'm not worried about that for the time being.

Thanks for your help! Closing...
