### ISSUE TITLE
assertion error while parsing JSON data tree

### ISSUE THREAD

**Issue by rjarry** [CESNET/libyang#1419]
Hi Michal,

When compiled in `debug` mode (with cache enabled), I get an assertion error while parsing JSON data:

```
src/tree_data.c:6665: lyd_find_sibling: Assertion `target->hash' failed.
```

Looking at the core dump and with `git bisect`, I found that it happens since commit 7e462e28078432784a3dee8d7375ad741a04b9b9 (#1385).

Indeed, the `result` node has no `hash` computed yet at this point which causes the assertion to fail:

https://github.com/CESNET/libyang/blob/7e462e28078432784a3dee8d7375ad741a04b9b9/src/tree_data.c#L6665

I don't know what is the best course of action to fix the problem. Can this check for key duplicity be made after the hash has been computed?

Thanks in advance for your help.

**Comment by michalvasko** [comment]
Okay, now the fix should not cause any failed assertions.
