### ISSUE TITLE
error path is wrong when creating a leaf defined in grouping

### ISSUE THREAD

**Issue by fanchanghu** [CESNET/libyang#1428]
Hi,
When I create a leaf defined in a grouping with an invalid value, libyang can report an error, but the error path returned by `ly_errpath` is not expected. This issue could be reproduced with following code:
```
#define plog(fmt, args...) printf(fmt"\n", ##args)

int main()
{
    struct ly_ctx *ctx = ly_ctx_new(NULL, 0);
    assert(ctx != NULL);

    const struct lys_module *m = lys_parse_path(ctx, "A.yang", LYS_IN_YANG);
    assert(m != NULL);

    struct lyd_node *d = lyd_new(NULL, m, "T");
    assert(d);

    struct lyd_node *f1 = lyd_new_leaf(d, NULL, "f1", "123456");
    assert(!f1);

    plog("%s, %s", ly_errmsg(ctx), ly_errpath(ctx));

    lyd_free_withsiblings(d);

    ly_ctx_destroy(ctx, NULL);

    return 0;
}
```

A.yang
```
module A{
yang-version 1.1;
prefix a;
namespace "urn:a";

grouping f1g {
	leaf f1{
		type string { length 0..5; }
	}
}

container T{
	uses f1g;
	leaf f2{
		type string { length 0..5; }
		default "a";
	}
}

}
```
the output error path is `/A:f1`, and I think it shoud be `/A:T/f1`.

**Comment by michalvasko** [comment]
Right, fixed.

**Comment by fanchanghu** [comment]
This path shoud be a data xpath, right? but when I change the container `T` to list, and change the code like following:
```
    struct lyd_node *d = lyd_new(NULL, m, "T");
    assert(d);

    struct lyd_node *k = lyd_new_leaf(d, NULL, "k", "1");
    assert(k);

    struct lyd_node *f1 = lyd_new_leaf(d, NULL, "f1", "123456");
    assert(!f1);

    plog("%s, %s", ly_errmsg(ctx), ly_errpath(ctx));
```
however, the path is `/A:T/f1` but not `/A:T[k='1']/f1`. (`k` is key of `T`)

**Comment by michalvasko** [comment]
I have changed it to schema path because, obviously, the data path could not be properly generated. The data node does not exist (it party does but definitely does not know about its parent) at that point so schema path is the best we can do.

**Comment by fanchanghu** [comment]
Hi,
Using schema path is not very convenient to find out where the error occurs, especially when parsing the `edit-config` or `copy-config` data.  So, how about just using schema path when `!node->parent && lys_parent(node->schema)` ?

**Comment by michalvasko** [comment]
I am not sure that is really a better solution than simply using the schema path, you would not know which path to expect.

**Comment by fanchanghu** [comment]
How about linking it to its parent before parsing the value? then we can get the correct data path if the parsing failed.

**Comment by fanchanghu** [comment]
I have changed the code like above and it could pass all tests and return correct data path for `lyd_new_leaf`.  the code is in here: https://github.com/fanchanghu/libyang/commit/0245868a4ca4aab959c4b8e3b5ed7e31edba69e7 .

**Comment by michalvasko** [comment]
Well, I do not really like this change because it completely breaks the logic of first creating node and then inserting it. That may cause various problem including then inserting it twice (which you are doing in your fix).

**Comment by fanchanghu** [comment]
I agree it breaks the simple logic as you say, but I think it is deserved because it achieves the feature "return a data path for error path", which is valuable for the user.
And I don't think it will cause any problem now, because the difference with before is only in the function `lyd_create_leaf` which is a static method. However, it really should be more careful when we change it later, and maybe we could refact this code at that time.

**Comment by michalvasko** [comment]
> And I don't think it will cause any problem now

Like I said, the changes you made are already wrong (the leaf is inserted twice but it is possible the insert function can detect it so it does not actually manifest) and we will not risk such a major internal change for so little gain. *libyang* is in support-only mode now and keeping the schema path there seems like the safest solution, which is the primary concern.
