### ISSUE TITLE
deviations can produce a model where child nodes of config: false are config: true

### ISSUE THREAD

**Issue by jktjkt** [CESNET/libyang#1429]
I'm trying to modify an entire model to make it read-only, like this:
### `example.yang`
```yang
module example {
  namespace "x:example:example";
  prefix "ex";

  container a {
    leaf aa {
      type uint8;
    }
  }
}
```
### `aug.yang`
```yang
module aug {
  namespace "x:example:aug";
  prefix "aug";

  import example {
    prefix "ex";
  }

  deviation "/ex:a" {
    deviate add {
      config false;
    }
  }
}
```
However, when I look at the result, I see that `/ex:a/aa` is marked as a config node, while `/ex:a` is read-only.
```console-session
$ yanglint -f tree aug.yang example.yang 
module: aug

module: example
  +--ro a
     +--rw aa?   uint8
```
That is in violation of [RFC 7950](https://tools.ietf.org/html/rfc7950#page-135) which says:
> If a node has "config" set to "false", no node underneath it can have "config" set to "true".

Discovered by @peckato1.

**Comment by lePici** [comment]
Hello, the bug should now be fixed.

**Comment by jktjkt** [comment]
Thanks, confirming that it's fixed also for our particular model. We cannot immediately upgrade due to https://github.com/sysrepo/sysrepo/issues/2341, though (I just rechecked, it's still the case).
