### ISSUE TITLE
Add 'debian/1.0.184-2' tag to 	806a5ee8a79

### ISSUE THREAD

**Issue by nickbroon** [CESNET/libyang#1430]
It would be useful to have debian/<version> tags available.
There are a few older ones, but recent tags are missing.

debian/1.0.176-2
debian/1.0.176-1

cc: @oerdnj

**Comment by michalvasko** [comment]
Added.

**Comment by oerdnj** [comment]
Yeah, I forgot to push the tags. It should be there along with the new release packaged.
