### ISSUE TITLE
libyang[0] Failed to resolve identityref "ietf-datastores:running"

### ISSUE THREAD

**Issue by som-1981** [CESNET/libyang#1435]
NETCONF server populates both data-trees: NMDA supporting "/yang-library" and non-NMDA-supporting "/modules-states". NETCONF client is non-NMDA-supporting client and tries to parse NMDA supporting "/yang-library" tree which includes following data:
 
<datastore>
<name xmlns:ds="urn:ietf:params:xml:ns:yang:ietf-datastores">ds:running</name>
<schema>complete</schema>
</datastore>
<datastore>
<name xmlns:ds="urn:ietf:params:xml:ns:yang:ietf-datastores">ds:candidate</name>
<schema>complete</schema>
</datastore>
<datastore>
<name xmlns:ds="urn:ietf:params:xml:ns:yang:ietf-datastores">ds:startup</name>
<schema>complete</schema>
</datastore>
<datastore>
<name xmlns:ds="urn:ietf:params:xml:ns:yang:ietf-datastores">ds:operational</name>
<schema>complete</schema>
</datastore>

libyang[0] Identity found, but in a non-implemented module "ietf-datastores".
libyang[0] Failed to resolve identityref "ietf-datastores:running".

We are seeing the above error.

Legacy "/modules-state" does NOT populate this data, so if NETCONF client parsed that tree it probably would not get that error, and this is what described in the RFC
 
The old YANG library definitions have been retained (for backwards- compatibility reasons), but the definitions have been marked as deprecated. For backwards compatibility, an NMDA-supporting server SHOULD populate the deprecated "/modules-state" tree in a backwards- compatible manner. The new "/yang-library" tree will be ignored by legacy clients but will provide all the data needed for NMDA-aware clients (which will ignore the "/modules-state" tree).

Can you provide your input here? Why there is no backward compatilibilty? As I said NETCONF server supports NMDA but NETCONF client does not?
Any solution other than upgrading NETCONF client?

**Comment by michalvasko** [comment]
> NETCONF server populates both data-trees: NMDA supporting "/yang-library" and non-NMDA-supporting "/modules-states". NETCONF client is non-NMDA-supporting client and tries to parse NMDA supporting "/yang-library" tree which includes following data:

This is a wrong understanding. This has nothing to do with NMDA support, we are simply talking about the revision of `ietf-yang-library` a particular client/server supports. Since the new data were parsed, the client supports the new revision. But since it seems it is not implementing `ietf-datastores`, it cannot actually load the data - a bug in the client, nothing else.
