### ISSUE TITLE
How to add one attribute to a xml node

### ISSUE THREAD

**Issue by koala027** [CESNET/libyang#1440]
Hi michalvasko, we are referencing your code in our project to implement netconf protocol. great thanks to you in the firstly.

One question confuse me a long time. when netconf client send edit-config message to netconf server, the payload follow xml schema, we want to add one custom attirbute in a xml node, like as below:

<user-plane-configuration xmlns="urn:o-ran:uplane-conf:1.0" **xvendor="du"**>
  <tx-array-carriers **xvendor="du"**>
    <name>tx-array-carrier-4</name>
  <tx-array-carriers>
</user-plane-configuration>

xvendor attribute that we want to set in xml node, but we find this content cann't be apply in sysrepo. 
==> Invalid attribute "xvendor"

if the attribute name change to "xmlns:xvendor", the xml can be parsed correctly, but in module_change callback function, we still can not retrieve the native xml, "xmlns:xvendor" attribute will be discarded.

So, michalvasko, is there any way? i can send xml with custom attribute to netconf server, and it can be reterived in model_change callback. thanks your take care my issue and look forware your response.

**Comment by michalvasko** [comment]
You cannot simply write a new attribute, you must properly define it in YANG first. What you want is define a new [metadata](https://tools.ietf.org/html/rfc7952). Note that there still may be some problems because this feature is not used or tested that much, let us know if you encounter some problems.
