### ISSUE TITLE
ly2: issue with applying multiple diffs on the same data tree

### ISSUE THREAD

**Issue by rwestphal** [CESNET/libyang#1445]
I wrote a program that does the following:
1 - Create one empty candidate config and one empty running config;
2 - Change the candidate config;
3 - Compute a diff between the running config and the candidate config;
4 - Apply that config diff to the running config.

Steps 2-4 are done twice. The first time it works normally, but in the second time the program fails with the following message:
```
libyang[0]: Internal error (/mnt/renato/git/northbound/lang-c/libyang2/src/diff.c:922).
lyd_diff_issue: lyd_diff_apply_all(): Internal error (/mnt/renato/git/northbound/lang-c/libyang2/src/diff.c:922).
```

Tarball containing a sample program and all required files necessary to reproduce the problem: [lyb_issue.tar.gz](https://github.com/CESNET/libyang/files/6086204/lyb_issue.tar.gz)

Any help would be appreciated!

**Comment by michalvasko** [comment]
The attached files were reproducing issue #1447 I believe but it should no longer crash.

**Comment by michalvasko** [comment]
Oh, I thought you had switched the attachments but you have only uploaded the wrong one here, so please provide the one that reproduces this issue.

**Comment by rwestphal** [comment]
> Oh, I thought you had switched the attachments but you have only uploaded the wrong one here, so please provide the one that reproduces this issue.

Silly me ^^

Here's the correct tarball for this issue: [lyd_diff_issue.tar.gz](https://github.com/CESNET/libyang/files/6090665/lyd_diff_issue.tar.gz)

**Comment by michalvasko** [comment]
Okay, this one was a bit more complex but did not require any code changes to fix. But I have added documentation that should clearly explain why you encountered the problem. Also, I have tested both possible solutions (using `LYD_DIFF_DEFAULTS` or validating the data) and did not get any errors.

**Comment by rwestphal** [comment]
> Okay, this one was a bit more complex but did not require any code changes to fix. But I have added documentation that should clearly explain why you encountered the problem. Also, I have tested both possible solutions (using `LYD_DIFF_DEFAULTS` or validating the data) and did not get any errors.

Thanks Michal! The doc updates were clarifying.

> I was considering several other solutions but this one should be the best. The possibility to create a diff without the flag was kept for possible use-case when the diff is not applied (just printed, for example), in general. Otherwise it is always best to use it to avoid the validation. Also, I wanted to perform all the required validation tasks when applying the diff but that is far from trivial and I think it would be useless, anyway.

I agree it makes sense to keep `LYD_DIFF_DEFAULTS` as an optional flag, even though its absence can be problematic in some cases. The "Caution" section in the API documentation should be enough to warn users about that.
