### ISSUE TITLE
edit-config must statement evaluation

### ISSUE THREAD

**Issue by dmcpriv** [CESNET/libyang#145]
Hi there,

When supplying XML data in an edit-config, the must statements are being evaluated and rejected.  This is expected since the data tree is incomplete (it is part of the edit-config).  Is there a setting to supply to the parse_xml call to bypass must statement evaluation?

**Comment by michalvasko** [comment]
Hi,
have you checked documentation for the function, `lyd_parse_xml`? Among parser options there is `LYD_OPT_EDIT`, should do the trick.

Regards,
Michal

**Comment by dmcpriv** [comment]
Yes.  I was indeed trying the edit option bit it seems it is not respected when the must statements get evaluated.  Would an example help?

**Comment by michalvasko** [comment]
Hi,
it should be fixed now, please verify.

Regards,
Michal

**Comment by dmcpriv** [comment]
Thanks, I will take a look.
