### ISSUE TITLE
Deviation replace config false -> config true keeps children nodes config false

### ISSUE THREAD

**Issue by maniowy** [CESNET/libyang#1462]
Say we have an example container that is `config false` and try to `deviate` the `config` statement to `true`. Container's child leaf stays read only. I believe the children nodes should share the `config` statement with the parent when there's no separate `config` specified for the child.

`example.yang`

```yang
module example {
  namespace "x:example:example";
  prefix "ex";

  container a {
    config false;
    leaf aa {
      type uint8;
    }
  }
}
```

`aug.yang`

```yang
module aug {
  namespace "x:example:aug";
  prefix "aug";

  import example {
    prefix "ex";
  }

  deviation "/ex:a" {
    deviate replace {
      config true;
    }
  }
}
```

Here's the result:

```
$ yanglint -f tree aug.yang example.yang 
module: aug

module: example
  +--rw a
     +--ro aa?   uint8
```

There was a similar issue recently: #1429.

Best regards
Mateusz

**Comment by fredgan** [comment]
Besides I test this for `ly2`(the latest version), the container still stays read only, It's not changed from `config false` to `config true`  by deviation.

the result in ly2:
```
$ yanglint -f tree aug.yang example.yang 
module: aug
module: example
  +--ro a
     +--ro aa?   uint8
```

**Comment by michalvasko** [comment]
Okay, should be fixed now.

@fredgan As for the new *libyang*, all of these use-cases should either work or not independently of any changes made by deviations because of the way it works there. But you cannot use `tree` printer for verifying this (for now) because it prints only the parsed tree of the module, with nothing compiled in it including any foreign deviations.

**Comment by maniowy** [comment]
Thank you, picked up the fix and it works. However, I have noticed it works only for `yang`s. Does not work when the model is defined in `yin` modules:

```
$ for mod in {aug,example}; do yanglint -f yin ${mod}.yang -o ${mod}.yin; done
$ yanglint -f tree aug.yin example.yin
module: aug

module: example
  +--rw a
     +--ro aa?   uint8
```

**Comment by michalvasko** [comment]
Fine, done.

**Comment by maniowy** [comment]
> Fine, done.

Now it's perfect, thanks a lot!
