### ISSUE TITLE
Augmentation to RPC input should be in any order but not

### ISSUE THREAD

**Issue by fanchanghu** [CESNET/libyang#1464]
Hi,
If two augmentation is added to the RPC input, as the [RFC](https://tools.ietf.org/html/rfc7950#section-7.17.2) says, they could be in any order. However, libyang raises an error for this.

>   When a node is augmented, the augmenting child nodes are encoded as
>   subelements to the augmented node, in any order.

**Comment by michalvasko** [comment]
Could you at least paste the actual error please?

**Comment by fredgan** [comment]
I try to reproduce this problem with the latest devel branch ,  the error is reported as 
```
$ yanglint -t rpc mod.yang data.xml -f xml
err : Invalid order of elements "l2" and "l3". (/mod:rpc_test/cc/l2)
```

my test module `mod.yang` as follows:
```
module mod {
    namespace "urn:cesnet:mod";
        prefix m;
    yang-version 1.1;

    rpc rpc_test {
        input {
            container cc {
                leaf l {
                    type string;
                }
            }
        }
        output {
            leaf test{
                type empty;
            }
        }
    }
    augment "/rpc_test/input/cc" {
        leaf l2 {
            type string;
        }
    }
    augment "/rpc_test/input/cc" {
        leaf l3 {
            type string;
        }
    }
}
```
data xml `data.xml` as follows:
```
<rpc_test xmlns="urn:cesnet:mod">
   <cc>
       <l>test</l>
       <l3>test3</l3>
       <l2>test2</l2>
   </cc>
</rpc_test>
```

**Comment by michalvasko** [comment]
Right, well, there seems to be an ambiguity in the RFC then because we check the order since [it is required](https://tools.ietf.org/html/rfc7950#section-7.14.4).

**Comment by fanchanghu** [comment]
I think [RFC 7.14.4](https://tools.ietf.org/html/rfc7950#section-7.14.4) is required for the nodes which defined in the `input` or `output` node directly, it does not consider augment. For augment, you can not known the order of them because they could be defined in different modules, so [RFC 7.17.2](https://tools.ietf.org/html/rfc7950#section-7.17.2) says, they can be in any order.

**Comment by michalvasko** [comment]
I am not sure I agree with you but we are just discussing different interpretations. I believe the ordering requirement for RPCs was introduced so that NETCONF clients have it easier to parse the parameters, whether any mandatory ones are missing and so on (not sure why else would the order be enforced). And in that case the order must be enforced even with any augments.

**Comment by fanchanghu** [comment]
Consider that the RPC is defined in module A, module B augments an argument `f1` to its input, and module C augments another argument `f2` to its input, then, how could we define the order of `f1` and `f2`?

**Comment by michalvasko** [comment]
> how could we define the order of f1 and f2

In *libyang*, it is the order in which the modules are loaded. But in general it is a question for the NETMOD mailing list, I suppose.

**Comment by fanchanghu** [comment]
After I read the RFC again, I still think it is written for input/output, which require their children are ordered. In other cases, the children are not required to be ordered, so this words will be nonsense if it is also not for input/output.

**Comment by michalvasko** [comment]
So can you tell me why the children are required to be ordered for input/output? It is impossible to decide this in either way without this information.

**Comment by llhotka** [comment]
In my view, RFC 7950 is contradictory in this respect. On one hand, the order in which augmenting modules are loaded/processed isn't defined, so there is no way to find which order of input/output parameters is correct.On the other hand, it would be difficult to have a subset of parameters with fixed order, and another (augmented) subset with arbitrary order.

**Comment by llhotka** [comment]
> So can you tell me why the children are required to be ordered for input/output? It is impossible to decide this in either way without this information.

I think the idea was that the receiving side may process the parameters step by step, without loading the whole message first. If you ask me, I'd always been against this CLR.

**Comment by llhotka** [comment]
FWIW, [Yangson](https://github.com/CZ-NIC/yangson) ignores the order in input/output, because in JSON it is just out of question.

**Comment by michalvasko** [comment]
Right, then it is just like I said and unless @fanchanghu can present any argument that carries some weight (probably only a reply from the mailing list or even better, an accepted errata) it will remain the way it is now.

**Comment by llhotka** [comment]
@michalvasko, I think I don't agree with this:

> And in that case the order must be enforced even with any augments.

If a server rejects an RPC request due to the order, it is IMO not good - the client may just have loaded the modules in a different order.

**Comment by michalvasko** [comment]
Strictly speaking, we do not care about the order in any of our use-cases for *libyang* but the order is required because the RFC says it should be required. I do not think we can simply ignore it, what if there are some NETCONF clients built with *libyang* that rely on the order?

**Comment by fanchanghu** [comment]
> Right, then it is just like I said and unless @fanchanghu can present any argument that carries some weight (probably only a reply from the mailing list or even better, an accepted errata) it will remain the way it is now.

I have found [RFC 7758](https://tools.ietf.org/html/rfc7758)  which augments a leaf `scheduled-time` to input of `edit-config`. in its [example](https://tools.ietf.org/html/rfc7758#section-5.1), the augmented argument is placed between the argument `target` and `config`:
```
   <rpc message-id="101"
       xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
     <edit-config>
       <target>
         <running/>
       </target>
       <scheduled-time
          xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-time">
           2015-10-21T04:29:00.235Z
       </scheduled-time>
       <config>
         <top xmlns="http://example.com/schema/1.2/config">
           <interface>
             <name>Ethernet0/0</name>
             <mtu>1500</mtu>
           </interface>
         </top>
       </config>
     </edit-config>
   </rpc>
```
its schema is defined [here](https://tools.ietf.org/html/rfc7758#appendix-A).

**Comment by llhotka** [comment]
I think the only way how to satisfy both requirements of RFC 7950 is to implement it like the *interleave* pattern in RELAX NG, as described here: http://books.xmlschemata.org/relaxng/relax-CHP-6-SECT-7.html

Then, the input/output parameters defined in place would have a fixed order, and those coming from augments would have arbitrary order and could also be arbitrarily intermingled with the in-place parameters.

**Comment by rkrejci** [comment]
Hi, I agree with @llhotka that interleaving is probably the best solution for interoperability. There is also another option I would like to mention - the parser accepts various validation flags, so we could add one saying 'switch off the input/output order checking'. libyang itself (yanglint(1)) could still check the order as it does now, but the caller (NETCONF server) could switch it completely off for interoperability with clients.

@michalvasko is going to ask on IETF mailing list, so we will see. But right now I would prefer the interleaving solution.
