### ISSUE TITLE
lyd_print_mem print string when using leafref to integer type

### ISSUE THREAD

**Issue by yanjunxi** [CESNET/libyang#147]
[issue.txt](https://github.com/CESNET/libyang/files/518962/issue.txt)

**Comment by michalvasko** [comment]
Hi,
I tried it with version 0.10.212 and it worked as expected, please verify.

Regards,
Michal

**Comment by yanjunxi** [comment]
I use version 0.10.214 and it doesn't work as my expectation.
I expect it is {"Sub:Root":{"a":4,"f":4}}, 
and actual result is {"Sub:Root":{"a":4,"f":"4"}}.

Thanks!

**Comment by michalvasko** [comment]
Hi,
please try it again and make sure you are really using version 0.10.212 or higher, it works as expected. Try removing all older versions from your system and run `# ldconfig`.

Regards,
Michal
