### ISSUE TITLE
Access violation in function ‘parse_schema_json_predicate’ 

### ISSUE THREAD

**Issue by ahiqun** [CESNET/libyang#1490]
```
Thread 37 "ntf-worker-2" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 4987]
0x0000555557a86b10 in parse_schema_json_predicate (id=0x7fffdcff4d9c "\\']/TimeZone",
    id@entry=0x7fffdcff4d96 "[Fid='\\']/TimeZone", mod_name=mod_name@entry=0x7fffdcff4638,
    mod_name_len=mod_name_len@entry=0x7fffdcff4624, name=name@entry=0x7fffdcff4630,
    nam_len=nam_len@entry=0x7fffdcff4620, value=value@entry=0x7fffdcff4628, val_len=0x7fffdcff461c,
    has_predicate=0x7fffdcff4618) at /mnt/e/code/git/libyang-master1.0.225/src/resolve.c:1158
1158                for (ptr = id; ptr && ptr[0] != quote; ++ptr) {
(gdb) print ptr
$7 = 0x7fffdcffa000 ""
(gdb) print ptr[0]
$8 = 0 '\000'
(gdb) print quote
$9 = 39 '\''
(gdb) print ptr
$10 = 0x7fffdcffa000 ""
(gdb) print id
$11 = 0x7fffdcff4d9c "\\']/TimeZone"
(gdb) print quote
$12 = 39 '\''
```

**Comment by michalvasko** [comment]
Should be fixed now.

**Comment by ahiqun** [comment]
The SEGV is fixed，yet another bug still exists. Xpath such as "/a:l[key1='11'][key2='\\']/value" for 'lyd_new_path' returns NULL.  There is something wrong in function ‘parse_schema_json_predicate’ .

           for (ptr = id; ptr[0] && ptr[0] != quote; ++ptr)
		   	{
                if (ptr[0] == '\\') {
                    ++ptr;
                }
            }
            if (!ptr[0]) {
                return -parsed;
            }

**Comment by michalvasko** [comment]
Actually, the xpath `/a:l[key1='11'][key2='\']/value` is wrong. It is a C string, where `\` marks the beginning of a special character. If you want to write the character `\`, it must actually be `\\`.
