### ISSUE TITLE
Can lyd_new_path API can create duplicate value for leaf-list nodes in notifications?

### ISSUE THREAD

**Issue by namphuonghoanges** [CESNET/libyang#1495]
I'm trying to add value to a read-only leaf-list in the o-ran-performance-management:
leaf-list frequeny-table {
        type uint32;

        description
          "frequency-table for the measurment-object are included per bin.
           The configuration parameters for this frequency-table are defined
           by bin-count, lower-bound and upper-bound";
      }
This leaf-list in 2 place: 
+ in the modules struct so i can get with get command in cli
+ in the notifications struct that i can get with the subcribe in cli.

Both i am using the same source and parametter (not xpath) but only get can having the duplicate value in leaf-list, the notification cannot. Is this a bug?
sysrepo: 1.4.122 and libyang: 1.0.225

There is another isues, i create in sysrepo project by this link: https://github.com/sysrepo/sysrepo/issues/2393

**Comment by namphuonghoanges** [comment]
It's good now. Can you merge this onto the next release?

**Comment by michalvasko** [comment]
Naturally, it will be present in the next release.

**Comment by namphuonghoanges** [comment]
Thank you :D
