### ISSUE TITLE
ly2: Question regarding Leaf-list predicate

### ISSUE THREAD

**Issue by awesomenode** [CESNET/libyang#1497]
Hi,

One of my modules uses the following XPath to set configuration data:
/ietf-interfaces:interfaces/interface[name='eth0']/description[.="eth0desc1"]
As you can see the XPath contains the value to be set. 

Example Sysrepo call:
int rc = sr_set_item_str(session, "/ietf-interfaces:interfaces/interface[name='eth0']/description[.=\"eth0desc1\"]", "", NULL, 0);

It works well with libyang/sysrepo but I have a problem using it with libyang2/sysrepo.

Here is the libyang2 error log:
[ERR]: Leaf-list predicate defined for leaf "description" in path.
[ERR]: Invalid datastore edit.

Is it a planned behavior in libyang2?

Sysrepo: 2dec6b2263dcca062a3eeca60a249b27da4021cb
Libyang: 91b349dec6f7c98a2c95dee27cc39cb6b8391ebc

YANG module:

ietf-interfaces            | 2018-02-20

Thanks

**Comment by michalvasko** [comment]
Yes, that will no longer work and for a leaf you must always set the value as the separate argument.
