### ISSUE TITLE
Order of transactions in lyd_diff? 

### ISSUE THREAD

**Issue by TribuneX** [CESNET/libyang#1502]
Reading through the [docs of lyd_diff](https://netopeer.liberouter.org/doc/libyang/master/html/group__datatree.html#ga7bf9e3cac695c98fc655662e07b7f09b) I wonder why the transactions of type `LYD_DIFF_CREATED` should be applied last. Especially, in cases where the transactions for changed nodes (`LYD_DIFF_CHANGED`) include `leafrefs` to nodes which must be created first. 
It seems that the order of transactions does not honor those references between nodes. Is that correct?

I would expect the transactions of type `LYD_DIFF_CREATED` not only to be applied before all other transaction, but also to have a specific order within these transactions of type `LYD_DIFF_CREATED`, since they might also include `leafrefs` which impact the required order of transactions.

**Comment by michalvasko** [comment]
Well, there is no transaction order that would make the data tree valid after each transaction so I am not sure what the problem is. After you are done applying the whole diff, you validate your data and they should be valid. The strict order is required because some changes may require some other nodes as anchors (`LYD_DIFF_MOVEDAFTER1`) and they were generated after all the previous changes were performed.

**Comment by TribuneX** [comment]
Thanks for clarification. We currently use the generated transactions from `lyd_diff` to construct changesets, which we apply via gNMI on a per transaction basis. Therefore, it would help a lot if these transaction would be ordered based on their `leafrefs` (of course this is not  a trivial task).
I guess the best option we have here is to build a sort of dependency graph from the yang schema based on the different leafrefs and order the transactions genereated by `lyd_diff` ourselves.

**Comment by michalvasko** [comment]
If you are trying to have the data valid after every transaction, then like I said, that may easily be impossible in some cases and I would strongly advise you not to try this (I am quite certain you would fail). I would suggest you look at *libyang* version 2 (branch `libyang2`), which should be released soon. There the format of the diff was completely changed and should make it much simpler to send all the changes of a diff in a single RPC. That is what you should be doing, I think.

**Comment by TribuneX** [comment]
Thanks for the pointer. We'll take a look at version 2 and revisit our strategy of sending individual RPC requests vs a single RPC.
