### ISSUE TITLE
ly2: infinite loop while loading deviations module before deviated module

### ISSUE THREAD

**Issue by rwestphal** [CESNET/libyang#1516]
I think I found a regression in libyang2 while upgrading the library. In short, an infinite loop happens if I try to load a deviations module before the corresponding deviated module. That used to work as of commit 0aa1f7090ca814f6df6131a6a7ab77db83f0bc57 (the version I was using before).

The steps to reproduce this problem are simple:
```
# yanglint 
> add ietf-interfaces@2018-01-09.yang 
> add ietf-mpls-ldp-deviations.yang
```

Curiously, this problem only happens if the ietf-interfaces module is loaded first, otherwise I can load the LDP deviations module before the base LDP module.

Tarball containing the aforementioned YANG modules: [modules.tar.gz](https://github.com/CESNET/libyang/files/6351396/modules.tar.gz)

**Comment by michalvasko** [comment]
Right, it was an ordering problem that should be solved now, I hope.

**Comment by rwestphal** [comment]
@michalvasko Thank you! Closing...
