### ISSUE TITLE
lyd_parse_fd adds empty top-level leaf-list in some cases

### ISSUE THREAD

**Issue by milanlenco** [CESNET/libyang#152]
After changing [this YANG module](https://github.com/sysrepo/sysrepo/blob/devel/tests/yang/test-module.yang) into [this](https://github.com/milanlenco/sysrepo/blob/devel/tests/yang/test-module.yang), i.e. adding another import and some when/must statements referencing data from it, I have observed that lyd_parse_fd adds "empty" top-level leaf-list into the data tree.

Specifically, for data:
```
<leafref-chain xmlns="urn:ietf:params:xml:ns:yang:test-module">
  <D>final-leaf</D>
  <C>final-leaf</C>
</leafref-chain>
<university xmlns="urn:ietf:params:xml:ns:yang:test-module">
  <students>
    <student>
      <name>nameA</name>
      <age>19</age>
    </student>
    <student>
      <name>nameB</name>
      <age>17</age>
    </student>
    <student>
      <name>nameC</name>
      <age>18</age>
    </student>
  </students>
  <classes>
    <class>
      <title>CCNA</title>
      <student>
        <name>nameB</name>
        <age>17</age>
      </student>
      <student>
        <name>nameC</name>
      </student>
    </class>
  </classes>
</university>
<list xmlns="urn:ietf:params:xml:ns:yang:test-module">
  <key>k2</key>
  <id_ref>id_2</id_ref>
  <union>infinity</union>
</list>
<list xmlns="urn:ietf:params:xml:ns:yang:test-module">
  <key>k1</key>
  <id_ref>id_1</id_ref>
  <union>42</union>
  <wireless/>
</list>
```
It adds `<ordered-numbers xmlns="urn:ietf:params:xml:ns:yang:test-module"/>` which it wouldn't do for the original version of the module. Even though it is printed only if `LYP_WD_ALL` is provided, it gets picked up by lyd_find_xpath for xpath `/test-module:ordered-numbers` (one leaf-list with value "0") which in effect negatively affects the behaviour of sysrepo getters.

Is it somehow related to empty containers?

**Comment by rkrejci** [comment]
The most important difference is making the later module YANG 1.1. Anyway it seems as a bug, I'm going to look at that. It seems that it is wrongly detected that there is a default value of the `ordered-numbers` leaf-list. That's why it is being printed only with `LYP_WD_ALL`.

**Comment by milanlenco** [comment]
Yes, correct, after testing all the changes incrementally it turned out that the import and cross-module data dependencies are irrelevant here and the issue starts with making the module YANG 1.1.
