### ISSUE TITLE
Openconfig yang type validation

### ISSUE THREAD

**Issue by przemyslawnogiecEx** [CESNET/libyang#1527]
Hi, 
I'm using libyang in my project. I have field from openconfig-yang-types:

typedef date {
    type string {
      pattern '`^[0-9]{4}\-[0-9]{2}\-[0-9]{2}$`';
    }
    description
      "A full UTC date, expressed in the format described in RFC3339.
      That is to say:

      YYYY-MM-DD

      where YYYY is the year, MM is the month expressed as a two-digit
      month (zero padding if required), DD is the day of the month,
      expressed as a two digit value.";

    reference
      "RFC3339 - Date and Time on the Internet: full-date";
  }

In my code I put value "2021-04-20" but I have an error:
[error] [LN] Value "2021-04-20" does not satisfy the constraint "^[0-9]{4}\-[0-9]{2}\-[0-9]{2}$" (range, length, or pattern)

Can anyone help?

**Comment by jktjkt** [comment]
I suspect that the snippet you've shown is incorrect because that pattern doesn't contain the `^` and `$` chars. Anyway, this is due to https://github.com/openconfig/public/issues/44 .

**Comment by przemyslawnogiecEx** [comment]
Sorry, yang pattern is 
typedef date {
type string {
pattern '^[0-9]{4}\-[0-9]{2}\-[0-9]{2}$';
}

I removed ^ and $ because Im trying to start it to work

**Comment by michalvasko** [comment]
You keep contradicting yourself but if you use `pattern '[0-9]{4}-[0-9]{2}-[0-9]{2}';`, it should work.

**Comment by przemyslawnogiecEx** [comment]
The regex is provided in openconfig-yang-types.yang and I should not modify yang

**Comment by michalvasko** [comment]
Right, then @jktjkt has provided the answer. In short, you cannot use *libyang* with this module.

**Comment by odoochina-dev** [comment]
> You keep contradicting yourself but if you use `pattern '[0-9]{4}-[0-9]{2}-[0-9]{2}';`, it should work.

@michalvasko, @przemyslawnogiecEx yes if change pattern to `'[0-9]{4}-[0-9]{2}-[0-9]{2}'`,  
`"2021-04-20"` is a valid value (this is expected); 
but, 
`"any2021-04-20any"` also a valid value (against the pattern), but it shall NOT.
