### ISSUE TITLE
XPath filtering derived-from and derived-from-or-self function transitive usecase

### ISSUE THREAD

**Issue by awesomenode** [CESNET/libyang#1530]
Hi,

Consider the following identity hierarchy:
```
module test {
  identity color;

  identity green {
    base color;
  }

  identity yellow {
    base green;
  }

  leaf wall {
    type identityref {
      base "test:color";
    }
  }
}
```

The value for wall is set to test:yellow without any issue.

If I add the following function to the xpath filter in a get the result is true as expected:
`derived-from(test:wall, 'test:green')`

However if I try to get transitive usecase the result is false:
`derived-from(test:wall, 'test:color')`

So in the xpath function the base of the base is not checked.

libyang version: 1.0.229

Thanks

**Comment by michalvasko** [comment]
Fixed.
