### ISSUE TITLE
compiler error while trying to build the library with gcc 4.8.5 or 5.3.0 on Red Hat Enterprise Linux 7

### ISSUE THREAD

**Issue by eddsanity** [CESNET/libyang#1542]
I am trying to build the library on a Red Hat Enterprise Linux 7 system.

Running `make`, I get a giant pile of compiler errors which can be found in [this pastebin](https://pastebin.com/pzgpk3Hz).

Where do I go from here? I don't really get what's wrong, as I have built the library before without issue on an Ubuntu 20.04 machine with gcc 9.3.0, so the errors aren't making a whole lot of sense to me.

**Comment by michalvasko** [comment]
So what was the problem? Seems to me like a problem with the compiler.

**Comment by eddsanity** [comment]
> So what was the problem? Seems to me like a problem with the compiler.

Yes, make and CMake were invoking different versions of GCC and I hadn't noticed so the build was failing. Once I resolved this issue it compiled just fine.
