### ISSUE TITLE
ly2: logging calls itself to log when it runs out of memory.

### ISSUE THREAD

**Issue by choppsv1** [CESNET/libyang#1546]
```
        if (vasprintf(&msg, format, args) == -1) {
            LOGMEM(ctx);
```

**Comment by michalvasko** [comment]
Okay, should be fixed.

**Comment by Tanco-K** [comment]
1、Does this bug exist in earlier versions？ 1.0.184 or 1.0.225
2、Whether the modification solution is applicable to earlier versions？
@michalvasko

**Comment by michalvasko** [comment]
Yes, it exists in all 1.x versions and the same fix should work.

**Comment by Tanco-K** [comment]
> Yes, it exists in all 1.x versions and the same fix should work.

ok，thks ：）
