### ISSUE TITLE
require-instance for leafref is not handled

### ISSUE THREAD

**Issue by abhikeshav** [CESNET/libyang#155]
Having a require-instance statement for a leafref causes the below error.

```
leaf refleaf {
  type string;
}

  leaf l {
    type leafref {
      path "/refleaf";
      require-instance true;
    }
  }
```

```
libyang[0]: Invalid keyword "require-instance".
libyang[0]: Module "f" parsing failed.
```
Any idea how to fix this?

**Comment by michalvasko** [comment]
Hi,
require-instance for leafref is a new feature in YANG 1.1, did you specify this version in your module?

Regards,
Michal

**Comment by abhikeshav** [comment]
Thanks for your response. I didn't have the version statement in the yang file. Is this mandatory?

**Comment by michalvasko** [comment]
Hi,
version statement is not mandatory, but then it defaults to YANG 1.0. If you want to use YANG 1.1, it is mandatory.

Regards,
Michal

**Comment by abhikeshav** [comment]
Once I add the yang-version 1.1, this error goes away. Feel free to close this. Thanks
