### ISSUE TITLE
ly2: Unexpected data state node found

### ISSUE THREAD

**Issue by awesomenode** [CESNET/libyang#1556]
Hi,

I ran into the following problem on libyang2 branch:

```
[ERR]: Unexpected data state node "counter" found.
[ERR]: Validation failed.
```

I attached a test application to reproduce the issue.
[reprod.zip](https://github.com/CESNET/libyang/files/6452937/reprod.zip)

After the last successful transaction all `sr_apply_changes` and `sr_copy_config` attempts will fail with this issue:

```
$ sysrepoctl -i ./yang/ietf-interfaces@2018-02-20.yang
$ sysrepoctl -i ./yang/ietf-interface-protection@2018-06-30.yang
$ sysrepoctl -i ./yang/iana-if-type@2018-07-03.yang
$ sysrepoctl -i ./yang/ietf-microwave-types@2018-10-03.yang
$ sysrepoctl -i ./yang/ietf-microwave-radio-link@2018-10-03.yang
$ sysrepoctl -i ./yang/test-ct@2021-05-10.yang
$ sysrepoctl -i ./yang/test-rlt@2021-05-10.yang
$ ./main 
[ERR]: Unexpected data state node "counter" found.
[ERR]: Validation failed.
Validation failed
```

On devel version it works without any issue.                

libyang version: dcfac2c080eb1aeb02e362cd6267243163f327e6
sysrepo version: 87bfd1497e304debc16e8e7b2dddb5675ea75cf3

Thanks!

**Comment by awesomenode** [comment]
Thank you for the fix, the issue is gone with config false leaf, but I met the issue again with container.
I attached the example with modified test yang models:
[reprod2.zip](https://github.com/CESNET/libyang/files/6466432/reprod2.zip)

```
$ sysrepoctl -i ./yang/ietf-interfaces@2018-02-20.yang
$ sysrepoctl -i ./yang/ietf-interface-protection@2018-06-30.yang
$ sysrepoctl -i ./yang/iana-if-type@2018-07-03.yang
$ sysrepoctl -i ./yang/ietf-microwave-types@2018-10-03.yang
$ sysrepoctl -i ./yang/ietf-microwave-radio-link@2018-10-03.yang
$ sysrepoctl -i ./yang/test-ct@2021-05-10.yang
$ sysrepoctl -i ./yang/test-rlt@2021-05-10.yang
$ ./main 
[ERR]: Unexpected data state node "c1" found.
[ERR]: Validation failed.
Validation failed
```

libyang version: 36f210e7de95743bd04162d27c20027283b5455a
sysrepo version: ed713e17ad016838c4d6b0f3349b2b8557f57f48

**Comment by michalvasko** [comment]
Should be fixed as a side-effect of latest push operational data changes.

**Comment by awesomenode** [comment]
It works on the latest version, thanks!
