### ISSUE TITLE
lys_is_key not detecting notification keys.

### ISSUE THREAD

**Issue by masif-cs** [CESNET/libyang#1557]
I have a yang which is somewhat like below:
```
grouping alarm {
    description
      "Gropuping which can uniquely identify alarm";
list affected-objects {
      key name;
      leaf name {
        type string {
          length "1..255";
        }
        mandatory true;

        description
          "Represents the Object or source that is suspected to be affected by this fault";
      }
      min-elements 1;
      max-elements 100;

      description
        "List of affected-objects";
    }
}
notification alarm-notif {
    uses alarm;

    description
      "Notification sent on initial alarm creation, as well as any time the alarm changes state, including clear";
  }
```
I want to verify whether  the "name" is a key parameter of list. I am using the api lys_is_key. But it is not returning success for that.
if((node = ly_ctx_get_node(ctx, NULL, path.c_str(), 0)) == NULL)
if(NULL != lys_is_key((struct lys_node_leaf *)node, NULL))
Passing the path as "/o-ran-fm:alarm-notif/affected-objects/name". I have a key which has leafref in another yang notification, it works fine with same code. Please let me know if I am not doing it right.
Tried using GDB and it says it is LYS_LEAF
path = "/o-ran-fm:alarm-notif/affected-objects/name"
$1 = {name = 0x7fffe4034410 "**name**", dsc = 0x7fffe416fa60 "Represents the Object or source that is suspected to be affected by this fault", ref = 0x0, flags = 64, ext_size = 0 '\000', iffeature_size = 0 '\000', 
  padding = "\000\000\000", ext = 0x0, iffeature = 0x0, module = 0x7fffe416ac80, nodetype = **LYS_LEAF**, parent = 0x7fffe4171190, child = 0x0, next = 0x0, prev = 0x7fffe4171240, priv = 0x0, hash = "\000\000\000"}
(

**Comment by michalvasko** [comment]
Hm, possibly, I have tested it using the latest `devel` (1.0.233) as always.

**Comment by masif-cs** [comment]
I tried my yang with ur test.c file, it is giving not key. But with your yang it is giving as key.
Couldnt find any different in yang. Can you please check once with my yang(attached)

[o-ran-fm.zip](https://github.com/CESNET/libyang/files/6458485/o-ran-fm.zip)

**Comment by masif-cs** [comment]
My bad. Used two different version of yang where name is not defined as key :(
