### ISSUE TITLE
leafrefs in openconfig-bgp models fail to resolve

### ISSUE THREAD

**Issue by abhikeshav** [CESNET/libyang#156]
When parsing [this openconfig model](https://github.com/openconfig/public/blob/bfb2695faed5a2bc0dd2ce14b2fc15f6abc713ae/release/models/bgp/openconfig-bgp.yang) using `libyang`, the leafrefs fail to resolve and below errors are seen.

```
 libyang[1]: No resolvents found for leafref "/bgp/peer-groups/peer-group/peer-group-name". (path: /peer-group)
libyang[1]: No resolvents found for leafref "/bgp/peer-groups/peer-group/peer-group-name". (path: /peer-group)
libyang[1]: No resolvents found for leafref "../config/neighbor-address". (path: /bgp/neighbors/neighbor/neighbor-address)
libyang[1]: No resolvents found for leafref "../config/peer-group-name". (path: /bgp/peer-groups/peer-group/peer-group-name)
libyang[1]: No resolvents found for leafref "../config/neighbor-address". (path: /bgp/neighbors/neighbor/neighbor-address)
libyang[1]: No resolvents found for leafref "../config/peer-group-name". (path: /bgp/peer-groups/peer-group/peer-group-name)
libyang[1]: No resolvents found for leafref "../config/neighbor-address". (path: /bgp/neighbors/neighbor/neighbor-address)
libyang[1]: No resolvents found for leafref "../config/peer-group-name". (path: /bgp/peer-groups/peer-group/peer-group-name)
libyang[1]: No resolvents found for leafref "../config/neighbor-address". (path: /bgp/neighbors/neighbor/neighbor-address)
libyang[1]: No resolvents found for leafref "../config/peer-group-name". (path: /bgp/peer-groups/peer-group/peer-group-name)
```

Any idea of a fix for this?

**Comment by michalvasko** [comment]
Hi,
I tried loading those modules, but there are several problems with them and I don't want to spend too much time fixing them until I get to your error. Have you checked that those leafrefs are really correct? My bet is they are not.

Regards,
Michal

**Comment by abhikeshav** [comment]
Hey Michal,

I agree there are multiple issues when loading this (and other) openconfig models. However I'm able to validate these models using other tools like pyang. Just FYI these models are widely used in the industry as they are created by network operators like google and are meant to be vendor-neutral. Check out openconfig.net

Do you have any plans to test libyang with these openconfig models?

Thanks,
Abhi

**Comment by abhikeshav** [comment]
Created a simplified yang containing the failing case. Below is valid yang, but causes errors in libyang. 

```
module s
{
    prefix s;
    namespace "s:s";

  grouping address-group {
    leaf n-address {
        type string; 
    }
  }
  grouping name-group {
    leaf p-name {
      type string;
    }
  }
  grouping nameref-group {
    leaf p-nameref {
      type leafref {
        path "/b/ps/p/p-name";
      }
    }
  }

  grouping config-group { 
    container config {
    }
  }

  grouping n {
    list n {
      key "address";
      leaf address {
        type leafref {
          path "../config/n-address";
        }
      }
      uses config-group;
    }
  }
  
  grouping p {
    list p {
      key "p-name";
      leaf p-name {
       type leafref {
        path "../config/p-name";
       }
      }
      uses config-group; 
    }
  }

  grouping top {
      container b 
      {
        container ns {
          uses n; 
        }
        container ps {
          uses p;
        }
      }
  }

  uses top;
  
  augment /b/ns/n/config {
    uses address-group; 
  }
  
  augment /b/ps/p/config {
    uses name-group; 
  }

  augment /b/ns/n/config {
    uses nameref-group; 
  }
}

```

**Comment by abhikeshav** [comment]
Sorry, but the above in fact does not cause any issue, however, the [openconfig-bgp model](https://github.com/openconfig/public/blob/bfb2695faed5a2bc0dd2ce14b2fc15f6abc713ae/release/models/bgp/openconfig-bgp.yang) mentioned in the original post only has 2 unresolved leaf errors now with the latest libyang code.

**Comment by michalvasko** [comment]
Hi,
yes, and these are actually valid errors, the leafref targets really do not exist and if it passes pyang validation it only means it does not check it.

Regards,
Michal
