### ISSUE TITLE
Query:  Is this harmful?  libyang[1]: Missing status in deprecated subtree

### ISSUE THREAD

**Issue by starx1000** [CESNET/libyang#1561]
Hi,
  l am using the latest libyang1 with netopeer2-server,
  it is prints something like

libyang[1]: Missing status in deprecated subtree (/ietf-yang-library:{grouping}[module-list]/{grouping}[schema-leaf]/schema), inheriting.

  When call libyang to import schemas.. 

  Is this log harmful?  do I need some actions? 

 thanks. 

Brs

**Comment by michalvasko** [comment]
No, just ignore it. It is the result of minor inconsistencies between `status` spec and how it is used in practice.

**Comment by starx1000** [comment]
thanks!
