### ISSUE TITLE
Query: Performance difference between ly1 and ly2

### ISSUE THREAD

**Issue by sriramkandukuri** [CESNET/libyang#1565]
Hi,

Is there any readily available data on performance difference between old libyang and latest libyang2?

Thanks,
Sriram.K

**Comment by michalvasko** [comment]
No, not yet. There is a plan to create some common test-cases for this purpose and then optimize *libyang* 2 based on that. However, not sure if it will be worth it to make the test cases work with *libyang* 1 as well, although I cannot imagine it would be difficult to adjust, the APIs are very similar. So we may do that as well, just to have a comparison.

**Comment by sriramkandukuri** [comment]
Hi Michal,

Thank you very much for the info. 

Another query, Do libyang1 is actively supported?

Thanks,
Sriram.K

**Comment by michalvasko** [comment]
Yes, *libyang* 1 will continue to be supported, just no new features will be added.

**Comment by sriramkandukuri** [comment]
Hi Michal,

Thank you for the info

Thanks,
Sriram.K
