### ISSUE TITLE
Circular leafref error occurs

### ISSUE THREAD

**Issue by abhikeshav** [CESNET/libyang#157]
Hi,
I'm seeing below error on latest origin/master with attached models. This issue was not seen with commit 5302a1241c47369601239d7ba755d27953b30c4d (maybe introduced in https://github.com/CESNET/libyang/commit/4cf7dbaa5e93730f599cd95ff863221716110c2a).

```
libyang[2]: Resolving "openconfig-interfaces" unresolved schema nodes and their constraints...
libyang[0]: A circular chain of leafrefs detected. (path: /interfaces/interface/name)
libyang[0]: Module "openconfig-interfaces" parsing failed.
```

[models.zip](https://github.com/CESNET/libyang/files/531379/models.zip)

Any idea how to fix this? Thanks

**Comment by michalvasko** [comment]
Hi,
this issue should be fixed. However, I also tried loading `openconfig-bgp.yang` before and that still fails with what I believe is a valid error, there are some wrong leafref paths.

Regards,
Michal

**Comment by abhikeshav** [comment]
Thanks for fixing this issue, Michal! About `openconfig-bgp.yang`, [pyang](https://github.com/mbj4668/pyang) is able to validate it without any problems and these models are used in various implementations. Can you let me know which leafref paths could be wrong?

**Comment by michalvasko** [comment]
Hi,
I replied in #156.

Regards,
Michal
