### ISSUE TITLE
Run "sysrepoctl -l" failed

### ISSUE THREAD

**Issue by XiaYong123** [CESNET/libyang#1570]
Hi,
 
I tried to run sysrepoctl -l. But it is always failture. The log is as below:
```
[ERR]: Failed to create a new libyang context.
sysrepoctl error: Failed to connect (Internal error)
```
Then, i tried to check the code. It seems it is caused by libyang. You can check it.
```C
API struct ly_ctx *
ly_ctx_new(const char *search_dir, int options)
{
    FUN_IN;
    ...

    for (i = 0; i < ctx->internal_module_count; i++) {
        module = (struct lys_module *)lys_parse_mem(ctx, internal_modules[i].data, internal_modules[i].format);
        if (!module) {


           //It will enter this part and goto error.


            goto error;
        }
        module->implemented = internal_modules[i].implemented;
    }

    ...
}
```
Would you please help me to check it? Thanks a lot!

Best Regards,
Yong

**Comment by michalvasko** [comment]
Does running `yanglint` fail with the same error? In any case, it is most likely a problem with your library setup, so I would suggest completely uninstall (remove) everything and then install some compatible versions of the libraries and tools (the latest releases or `devel` branches).

**Comment by XiaYong123** [comment]
Dear,

     Thanks for your quick response! I tried to use the devel version. Unfortunately there is same error. In addition, i run the execution file in virtual box. The version and environment are below:

cat /proc/version
Linux version 4.15.0-142-generic (buildd@lgw01-amd64-036) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #146-Ubuntu SMP Tue Apr 13 01:11:19 UTC 2021


Best Regards,
Yong

**Comment by michalvasko** [comment]
You have not provided any more information so I cannot help you more. At least try running `yanglint` like I said before.

**Comment by XiaYong123** [comment]
Hi,

    I am sorry! I tried to run the command "yanglint". Then, the trace is as below:

*****************************************************
root@yoxia-VirtualBox:/home/yoxia/netconfig/libyang/libyang-master/build# yanglint
Configuration directory "/root/.yanglint" does not exist, creating it.
No saved history.
libyang[0]: Regular expression "(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\p{N}\p{L}]+)?" is not valid ("((([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\p{N}\p{L}]+)?)$": this version of PCRE is compiled without UTF support).
libyang[0]: Module "ietf-inet-types" parsing failed.
Failed to create context.
***********************************************************


Best Regards,
Yong

**Comment by XiaYong123** [comment]
Hi，

    I re-install the pcre lib and enable --enable-utf8 and --enable-unicode-properties. Then everything is good. Thanks for your support!

Best Regards,
Yong
