### ISSUE TITLE
ly2 yanglint -f tree doesn't expand groupings

### ISSUE THREAD

**Issue by idryzhov** [CESNET/libyang#1572]
I can't find any flag to pass to yanglint to expand `uses grouping` when printing trees. ly1 did this by default.

**Comment by michalvasko** [comment]
Update your `libyang2` branch, it does expand it by default now (for some weeks already).

**Comment by idryzhov** [comment]
I am using a package provided by FRR which should be using the v2.0.0 tag.
I'll try to build it from source and check again. Thanks.

**Comment by idryzhov** [comment]
I rebuilt it from the latest libyang2 branch and the result is the same:
```
module: frr-staticd

  augment /frr-rt:routing/frr-rt:control-plane-protocols/frr-rt:control-plane-protocol:
    +--rw staticd
       +--rw route-list* [prefix afi-safi]
          +--rw prefix                       inet:ip-prefix
          +--rw afi-safi                     identityref
          +---u staticd-prefix-attributes                                <--- here
          +--rw src-list* [src-prefix]
             +--rw src-prefix                   inet:ipv6-prefix
             +---u staticd-prefix-attributes                             <--- and here
```

**Comment by michalvasko** [comment]
I see, you should have been more specific because some uses in augments are not resolved, that is true. But if you print the target module with prefix `frr-rt`, you will see all the nodes there correctly. And you can filter the print to only a subtree, for example.

**Comment by idryzhov** [comment]
Thanks for the explanation.
