### ISSUE TITLE
Parsing valid YANG modules fails with: Invalid keyword "revision", it cannot appear after "(null)"

### ISSUE THREAD

**Issue by jean-christophe-manciot** [CESNET/libyang#1573]
yanglint: 2.0.0
```
yanglint openconfig-network-instance-types\@2016-12-15.yang
libyang err : Invalid keyword "revision", it cannot appear after "(null)". (Line number 24.)
YANGLINT[E]: Processing schema module from openconfig-network-instance-types@2016-12-15.yang failed.

yanglint openconfig-interfaces\@2018-01-05.yang 
libyang err : Invalid keyword "revision", it cannot appear after "(null)". (Line number 55.)
YANGLINT[E]: Processing schema module from openconfig-interfaces@2018-01-05.yang failed.
```

Could this issue be related with how libyang is configured with:
```
cmake -D CMAKE_INSTALL_PREFIX:PATH=/usr -D CMAKE_BUILD_TYPE:String="Release" -D GEN_LANGUAGE_BINDINGS=ON -D GEN_CPP_BINDINGS=ON -D GEN_PYTHON_BINDINGS=ON -D ENABLE_BUILD_TESTS=ON -D ENABLE_CACHE=ON -D ENABLE_LYD_PRIV=ON ..
```

**Comment by michalvasko** [comment]
Right, the message was mangled so that should be fixed now. But the problem remains, extension instance is part of `body-stmts` which cannot be followed by `revision-stmts` ([ref](https://datatracker.ietf.org/doc/html/rfc7950#section-14)).

**Comment by iljatab** [comment]
Hi Michal,

We are getting similar error:

libyang err : Invalid keyword "revision", it cannot appear after "extension instance". (Line number 55.)

Similar error comes from all OpenConfig YANG models, I am not sure how could one switch to libyang 2.x.

Ilja.

**Comment by michalvasko** [comment]
Switching to *libyang* v2 is up to you but sooner or later *libyang* v1 will stop being supported. This is a problem of the OpenConfig YANG modules that they do not conform to the [YANG grammar](https://datatracker.ietf.org/doc/html/rfc7950#section-14).
