### ISSUE TITLE
libyang2: invalid dependency in debian package

### ISSUE THREAD

**Issue by mwinter-osr** [CESNET/libyang#1577]
I think the Debian package (the devel subpackage) has a incorrect dependency: It requires libpcre3-dev instead of (correct) libpcre2-dev

The resulting packages are missing the libpcre2-dev and will complain. libpcre3-dev was used in libyang 1.* and is no longer used in libyang2 (replaced by libpcre2-dev)

**Comment by michalvasko** [comment]
You are correct, should be fixed.
