### ISSUE TITLE
cmake error with libyang2 branch

### ISSUE THREAD

**Issue by ankit7gup** [CESNET/libyang#1582]
Hi Michal,

After taking latest pull, just now, getting below errors now..

CMake Error at tests/CMakeLists.txt:22 (target_sources):
  Unknown CMake command "target_sources".
Call Stack (most recent call first):
  tests/utests/CMakeLists.txt:17 (ly_add_utest)

**Comment by michalvasko** [comment]
Right, that statement should no longer be used anywhere.

**Comment by ankit7gup** [comment]
It worked with latest pull.
