### ISSUE TITLE
Please tag versions

### ISSUE THREAD

**Issue by choppsv1** [CESNET/libyang#1594]
Could the version bumps please also be tagged? (i.e., 2.0.6 etc..)

**Comment by michalvasko** [comment]
Um, what for exactly? We tag only release versions (which should happen soon, actually).

**Comment by choppsv1** [comment]
> Um, what for exactly? We tag only release versions (which should happen soon, actually).
> 
Ok, dunno what the version bumps are for or how to use them then. We’ll just keep using v2.0.0 I guess.

**Comment by michalvasko** [comment]
That was the strategy for *libyang* version 1 as well so if you want a stable version, you should probably just use a specific tag and after a new release when it is tested and working, update to the new tag.
