### ISSUE TITLE
Feature request: C++ bindings for libyang2

### ISSUE THREAD

**Issue by pieterlexis** [CESNET/libyang#1596]
Hi folks,

Libyang 1.0.x had C++ bindings to the API. It would be great if there would be C++ bindings for libyang2 as well. Preferably using RAII and smart pointers.

Cheers!

**Comment by michalvasko** [comment]
Yes, but we are unable to maintain any bindings so for the new projects they will be left up to the community. As for libyang C++ bindings, some time ago @jktjkt said that they should be able to migrate them from *libyang* 1 and improve them. So maybe he can provide some more details.

**Comment by jktjkt** [comment]
Cc @syyyr because Vaclav is in that sweet spot of an overlap of the C++ and libyang knowledge. @syyyr , please feel free to chime in here.

**Comment by syyyr** [comment]
I have started working on the C++ bindings. I am not sure how long will it take to produce something that's usable, but hopefully not too long. RAII will be included.

**Comment by pieterlexis** [comment]
Development seems to be happening [here](https://github.com/cesnet/libyang-cpp)
