### ISSUE TITLE
Parsing RPC into a different libyang context

### ISSUE THREAD

**Issue by awesomenode** [CESNET/libyang#1599]
Hi!

I'm using 2 separate libyang contexts for the server and the datastore (an "internal" and
an "external" context, so to speak).

In the case of edit-config, printing the config using lyd_print_mem() and parsing it again
using lyd_parse_data_mem() works mostly fine, but when I'm calling an RPC or an action
this trick doesn't work. lyd_parse_op() doesn't seem like an option either, because it
expects the whole RPC tree, not the one the callback (set by nc_set_global_rpc_clb())
receives.

My question is, if there's a solution to this problem, can I parse an RPC into another
context?

Thanks!

**Comment by michalvasko** [comment]
Note that you can call `lyd_parse_op()` with either `LYD_TYPE_RPC_YANG` or `LYD_TYPE_RPC_NETCONF` and one of them should be suitable. And you should be always able to print an RPC into the `YANG` format.

In any case, why are you using 2 contexts? It is the common problem of having some internal modules that you do not want exposed and accessible by NETCONF?

**Comment by awesomenode** [comment]
Yes, I need 2 contexts because of the need for internal modules, which are only accessible by other apps on the device. So the server context is the subset of the datastore context.

`lyd_parse_op()` works fine now using the `LYD_TYPE_RPC_YANG` format.
Thank you!
