### ISSUE TITLE
Unknown keyword "�"

### ISSUE THREAD

**Issue by mkarthig** [CESNET/libyang#160]
/home/mkarthig/ncserver/libyang/build # ./yanglint 
> add bbf-fast.yang
libyang[0]: Invalid keyword "�".
libyang[0]: Submodule parsing failed.
libyang[0]: Including "bbf-fast-line-status-body" module into "bbf-fast" failed.
libyang[0]: Submodule "bbf-fast-read-test-body" parsing failed.
libyang[0]: Including "bbf-fast-read-test-body" module into "bbf-fast" failed.

when i tried to add yang, i got the above error.

**Comment by rkrejci** [comment]
can you provide link to the module?

**Comment by mkarthig** [comment]
Hi
 
please refer the following links. In the first link, i was used bbf-fast yang files. Also used some dependency yang files from 2nd link(IETF) . Thanks in advance.


https://github.com/BroadbandForum/yang/tree/master/standard

https://github.com/YangModels/yang/tree/master/standard/ietf/RFC
