### ISSUE TITLE
wrong parameter when logging?

### ISSUE THREAD

**Issue by lyzliyuzhi91** [CESNET/libyang#1600]
https://github.com/CESNET/libyang/blob/0f3dc6381c4968968273cbd36fe97f31d9463ca9/src/resolve.c#L2358

 here should be 
```
LOGVAL(ctx, LYE_PATH_MISSMOD, LY_VLOG_STR, str);
```
? Otherwise the variable str is unused.

**Comment by michalvasko** [comment]
Of course, fixed.

**Comment by lyzliyuzhi91** [comment]
OK
