### ISSUE TITLE
does if-feature statement not support logical operator?

### ISSUE THREAD

**Issue by lyzliyuzhi91** [CESNET/libyang#1602]
I define a module containing
```
  feature f2;
  container topb {
    container seca {
      if-feature "not f2"; // Invalid value "not f2" of "if-feature"
    } 
  } 
```
libyang return error:  【libyang[0]: Invalid value "not f2" of "if-feature".】. But I think it is grammatical according to RFC7950‘s section [7.20.2.  The "if-feature" Statement]
I am using libyang1.0.130.
Thanks

**Comment by michalvasko** [comment]
Is your module YANG 1.1? YANG 1.0 does not support such statements.

**Comment by lyzliyuzhi91** [comment]
You are right, my negligence. Thanks
