### ISSUE TITLE
Compile libyang fail

### ISSUE THREAD

**Issue by alexjiao2021** [CESNET/libyang#1604]
Hi,
When trying to compile libyang with 'sudo make' command on Ubuntu 18.04, there is an error shown in attached pic.
Could you please help? Thanks!
![libyang_make_fail](https://user-images.githubusercontent.com/84055495/120616707-05ff1200-c48c-11eb-82a6-ec66f33d5f33.PNG)

**Comment by michalvasko** [comment]
It seems you have static library installation of PCRE2 for some reason, you need a shared library. You should be fine with the package of the library, not sure how you got to have the static library but I am not really able to help. It is a problem of your build environment.

**Comment by alexjiao2021** [comment]
Changed PCRE2 to shared lib, compile is OK, thanks.
