### ISSUE TITLE
Question: How to free memory after lyxml_print_mem

### ISSUE THREAD

**Issue by rabhat31** [CESNET/libyang#1605]
Hi,
We are using libyang v 1.0.225. Within the application, we use lyxml_print_mem like so:

char *xml_str;
lyxml_print_mem(&xml_str, reply_error->err->other[i], LYXML_PRINT_SIBLINGS);
...
...
err_msg << "request failed. Error details: " << xml_str;

How do we free the memory allocated to xml_str? I don't seem to be able to access the xml pages.

Thanks

**Comment by michalvasko** [comment]
I am confused by your code snippet and not sure what exactly are doing. You print the XML into a string (`char *`) that needs to be freed. Any error is available separately with `ly_errmsg()`, for example.

**Comment by rabhat31** [comment]
To give you a little more context:

We get a reply from a netconf server using this API:

ssend_and_receive_rpc(&reply, rpc, session);

Using "reply", we want to validate whether our transaction went through fine or not.

if (reply_error->err) {
...
...
if (reply_error->err->other_count > 0) {
    for (int i = 0; i < reply_error->err->other_count; i++) {
        if (strcmp(reply_error->err->other[i]->name,"detail") == 0){
            char *xml_str;
            lyxml_print_mem(&xml_str, reply_error->err->other[i], LYXML_PRINT_SIBLINGS);
            err_msg << "<edit-config> request failed. Error details: " << xml_str;
        }
    }
}

**Comment by michalvasko** [comment]
I still do not get it, just free the string
```C
            char *xml_str;
            lyxml_print_mem(&xml_str, reply_error->err->other[i], LYXML_PRINT_SIBLINGS);
            err_msg << "request failed. Error details: " << xml_str;
            free(xml_str);
```

**Comment by rabhat31** [comment]
I've tried this but it seems to be causing some weird behavior in our application with valgrind. Bytes that were previously reachable suddenly show up as lost (to the tune of around 45MB). I just have question about the implementation of lyxml_print_mem in this regard.

https://github.com/CESNET/libyang/blob/libyang1/src/xml.c

In lyxml_print_mem, we declare a local variable "struct lyout out". We then assign *strp = out.method.mem.buf. So when we return from the lyxml_print_mem, that would make strp point to the memory within a local variable. Could this be causing some issues?

**Comment by rabhat31** [comment]
Hi Michal,

Sorry it took a while for me to get back. There was an issue with our application. The method you suggested works and there is no bug in libyang. You can close this issue.

Thanks.
