### ISSUE TITLE
Unable to install libyang 2.0.7 "-make" fails

### ISSUE THREAD

**Issue by vani2699** [CESNET/libyang#1606]
> /usr/bin/ld: /usr/local/lib/libpcre2-8.a(pcre2_compile.c.o): relocation R_X86_64_PC32 against symbol `_pcre2_utt_size_8' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: final link failed: Bad value
> collect2: error: ld returned 1 exit status

> CMakeFiles/yang.dir/build.make:201: recipe for target 'libyang.so.2.1.4' failed
> make[2]: *** [libyang.so.2.1.4] Error 1
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/yang.dir/all' failed
> make[1]: *** [CMakeFiles/yang.dir/all] Error 2
> Makefile:129: recipe for target 'all' failed
> make: *** [all] Error 2

how to proceed further?

**Comment by michalvasko** [comment]
You have a static version of PCRE2 installed. So you can either build static *libyang* (`cmake -DENABLE_STATIC=ON ..`) or install a dynamic library of PCRE2.

**Comment by vani2699** [comment]
built static libyang (cmake -DENABLE_STATIC=ON ..) in a libyang v 2.0.7 and tried to "make" 

> tools/lint/CMakeFiles/yanglint.dir/build.make:460: recipe for target 'yanglint' failed
> make[2]: *** [yanglint] Error 1
> CMakeFiles/Makefile2:207: recipe for target 'tools/lint/CMakeFiles/yanglint.dir/all' failed
> make[1]: *** [tools/lint/CMakeFiles/yanglint.dir/all] Error 2

> Makefile:129: recipe for target 'all' failed
> make: *** [all] Error 2

make fails at 96%, how to proceed?

**Comment by michalvasko** [comment]
Okay, I tried to improve what I could and I managed to build `yanglint` with static *libyang*.

**Comment by davehouser1** [comment]
I am running into the same 96% issue that @vani2699 is running into.
How do we install with static libraries? 
Might make sense to share instructions on how to install the specific libraries required to be dynamic. I ran into a lot of issues trying to get PCRE2 installed. I assume others that run into issue did the same as me and just installed from dpkg, which installs version 8.39, which does not work. Then I downloaded a package off line and compiled with a make install. The processes are disparate and I know that is the source if my problem.

**Comment by michalvasko** [comment]
Did you try to compile the latest `devel` branch of *libyang*?

**Comment by davehouser1** [comment]
@michalvasko, oh, yeah I am dumb. I just tried on that branch, and it works.
wow, I cant believe I didn't understand what you meant by `devel` branch. Sorry for making you repeat yourself!

**Comment by michalvasko** [comment]
I generally do not close issues and leave it up to the creator. And no, not sure what more would I write about building *libyang* statically (specific to *libyang*), you simply have to have static PCRE2 installed.

**Comment by JanAlbr-FhG** [comment]
i had the same issue. I solved it by editing CMakeLists.txt and setting

SET(BUILD_SHARED_LIBS OFF CACHE BOOL "Build shared libraries.") 
to 
SET(BUILD_SHARED_LIBS ON CACHE BOOL "Build shared libraries.")

Kind Regards

**Comment by hothotstreet** [comment]
> You have a static version of PCRE2 installed. So you can either build static _libyang_ (`cmake -DENABLE_STATIC=ON ..`) or install a dynamic library of PCRE2.
I solved the problem by setting cmake-denable_static =ON, thank you very much
