### ISSUE TITLE
`lys_parse_mem()` can't detect input format

### ISSUE THREAD

**Issue by syyyr** [CESNET/libyang#1610]
Hello, the documentation for `lys_parse_mem()` says that passing `0` as the `format` argument makes it detect the input type. However, that doesn't seem to be the case. Looking at `tree_schema.c:1504`, it seems that the "detect function" is not at all supported.

So, I think either the detection function should be implemented, or the documentation shouldn't mention it (I'm fine with whatever).

Thanks.

**Comment by michalvasko** [comment]
Right, copy-paste error, there is no input handler, only for `lys_parse()`. Fixed.

**Comment by syyyr** [comment]
Thanks.
