### ISSUE TITLE
`lyd_parse_data_mem()`: Mandatory node "content-id" instance does not exist. (path: Schema location /ietf-yang-library:yang-library/content-id, line number 5.)

### ISSUE THREAD

**Issue by syyyr** [CESNET/libyang#1612]
Hello, I have a program that tries to parse JSON data:
```cpp
#include <libyang/libyang.h>
const auto my_module = R"(
module my_module {
    yang-version 1.1;
    namespace "http://example.com/";
    prefix coze;

    leaf leafInt32 {
        description "A 32-bit integer leaf.";
        type int32;
    }
})";

const auto data = R"(
{
    "my_module:leafInt32": 420
}
)";
int main()
{
    ly_ctx* ctx;
    ly_ctx_new(NULL, 0, &ctx);
    lys_parse_mem(ctx, my_module, LYS_IN_YANG, nullptr);
    lyd_node* node;
    lyd_parse_data_mem(ctx, data, LYD_JSON, 0, 0, &node);
    ly_ctx_destroy(ctx);
}
```
However, the parsing fails with this error message:
```
libyang[0]: Mandatory node "content-id" instance does not exist. (path: Schema location /ietf-yang-library:yang-library/content-id, line number 5.)
```
I remember that in libyang1 you needed to use some sort of an option to skip these "yang-library" error, but it seems that there is no such thing in libyang. How should parse those data?

Thanks.

**Comment by michalvasko** [comment]
Just look at the current flags. You probably want to use `LYD_PARSE_ONLY` or `LYD_VALIDATE_PRESENT`, which I cannot decide. In this specific case even `LYD_VALIDATE_NO_STATE` would help but it is likely not what you want to do.

**Comment by syyyr** [comment]
It seems that `LYD_VALIDATE_PRESENT` is what I need. I understand that `lyd_parse_data_mem()` always considers all modules, so if I had loaded a module that had a mandatory node for example, I would also need this flag (because `lyd_parse_data_mem()` by default considers ALL modules). It is confusing to me why "something from `ietf-yang-library`" is also considered when I'm parsing my own data. Isn't `ietf-yang-library` something that's pretty much internal to libyang (YANG)?

**Comment by syyyr** [comment]
Okay, thank you.

**Comment by savnishsingh** [comment]
@syyyr I am facing the exact same issue where i have to validate data within an RPC. Were you able to find a workaround for this? Some dummy data that can be added to the RPC XML or in the libyang code?

**Comment by savnishsingh** [comment]
Thanks for the quick reply. But, with validate_present i am receiving errors for other mandatory leaves which i have not implemented 😆  . So basically no solutions 👍

**Comment by syyyr** [comment]
Well, if there are mandatory leaves, then you have to supply them, there is no workaround for that. Other than making them non-mandatory.

**Comment by michalvasko** [comment]
So you are trying to validate invalid data? Yes, that is going to fail. You can skip validation altogether with `LYD_PARSE_ONLY` that I have also mentioned before.

**Comment by savnishsingh** [comment]
No No... its not like Invalid data, its just that for the RPC i am not able to pass the `content-id` which is required for the `STRICT` flag to work. Rest works perfectly fine with `PARSE_ONLY` flag

**Comment by savnishsingh** [comment]
I never tried the two flags together. Looks like it works perfectly as required now. Thanks Michal 😄

**Comment by michalvasko** [comment]
Generally, everything called flags or options is meant to be combined.
