### ISSUE TITLE
libyang 2.0.7 installation error

### ISSUE THREAD

**Issue by mrsugaranil** [CESNET/libyang#1615]
Hi Michal,

I would like to share the error while I'am trying to compile libyang 2.0.7 version. Previously, I successfully compiled;
-libyang 1.0.225
-sysrepo 1.4.122
-netopeer2 1.1.70
-libnetconf2 1.1.43

Than I test them on ARM based embedded system. It was OK. But with the new versions, I cant compile them on Yocto based linux system. The libyang 2.0.7 info says in the page;
- libpcre2 => 10.21 is enough

My system has libcpre 10.33 so I expect that there is no problem. But, I have got the error below:
- **Could NOT find PCRE2: Found unsuitable version. "--should-not-have-used- /usr/bin/pcre2-config", but required at least "10.21". CmakeModules/FindPCRE2.cmake:19 (FIND_PACKAGE_HANDLE_STANDARD_ARGS). CMakeLists.txt:307 (find_package).**

Do you have any idea about this error? 

Thank you

**Comment by jktjkt** [comment]
Looks like your build find the host's PCRE2 instead of the one built for the target.

**Comment by michalvasko** [comment]
Please try the current `devel`, I have changed it so that no binary is executed and it should be read from the actual found header.
