### ISSUE TITLE
tailf:meta-value in CESNET

### ISSUE THREAD

**Issue by som-1981** [CESNET/libyang#1629]
Hello,
The confd supports tailf:meta-value but what is the similar thing in CESNET(netopeer2). There is some talk about extensions. Can we use them here? Can you share an example?

Thanks,

**Comment by michalvasko** [comment]
I do not know what `tailf:meta-value` is but assuming from the name it is some implementation of metadata, we do not support that currently in any way. Meaning you cannot store your own metadata in datastores.
