### ISSUE TITLE
Check if lysc_node* is a presence container

### ISSUE THREAD

**Issue by syyyr** [CESNET/libyang#1631]
Hi, in my app I need to know whether a schema node is a container and whether it's `presence true;`. Is this possible with just a `lysc_node_container*`? I can see the `presence` field in `lysp_node_container`, but not in `lysc_node_container`. Is this a limitation of the compiled modules? Can I somehow find out if a container is `presence true;` (possibly by retrieving a `lysp_node_container`)?

**Comment by michalvasko** [comment]
The point here is that while the `presence` statement has a string parameter, the string is useless in the compiled module. But to answer your question, look at `lysc_is_np_cont()` macro in `tree_schema.h`. Not sure if you can use it directly, probably not, but you will understand how to check for presence.

**Comment by syyyr** [comment]
I missed the `lysc_is_np_cont` macro. It seems like I can use it directly. Thanks.
