### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by mjethanandani** [CESNET/libyang#1632]
Encountering this assertion failure while compiling the ietf-bgp YANG module.

Assertion failed: (v < LY_ARRAY_COUNT(idents_p)), function lys_compile_identities_derived, file ~/libyang/src/schema_compile.c, line 470.
Abort trap: 6

$ yanglint -v
yanglint 2.0.7

Is there a way to also get line numbers in the YANG file for when it reports errors and warnings?

**Comment by michalvasko** [comment]
Try latest *libyang* from `devel`, it should be fixed there. Also, you should see line numbers in errors by default but it depends on when the error is generated because after the module is parsed, line number information is lost.

**Comment by mjethanandani** [comment]
It is fixed in devel branch. Thanks.
