### ISSUE TITLE
 YANG version 1.1 expects all includes in main module, includes in submodules are not necessary.

### ISSUE THREAD

**Issue by mjethanandani** [CESNET/libyang#1633]
This is one of the warning messages printed when trying to validate the IETF BGP YANG module. That module does make use of sub-modules, and its sub-modules do include other sub-modules. 

However, if the includes are removed, then validation starts failing for submodules that were including other sub-modules.  As an example:

Validating ../bin/ietf-bgp@2021-06-21.yang
../bin/submodules/ietf-bgp-rib-tables@2021-06-21.yang:93: error: identity "invalid-route-reason" not found in module "ietf-bgp-rib-tables"

In this case, the sub-module ietf-bgp-rib-tables includes ietf-bgp-rib-attributes, which in turn includes ietf-bgp-rib-types, and it is in ietf-bgp-rib-types that there is a definition for "invalid-route-reason".

**Comment by michalvasko** [comment]
Have you tried it with the latest `devel`? If so, please provide all the modified modules and I will take a look, the includes must be needed only in the main module.

**Comment by mjethanandani** [comment]
Some more details on how to reproduce the problem. I will give you a tar file for what needs to be used to reproduce the problem, and then the command I used. And yes, I am using the latest devel branch from GitHub to compile yanglint/libyang.

The tar ball should contain all the modules, all the sub-modules, and all the modules it depends on to compile. That way we share a common debug environment.

The command I am using is:

yanglint -p bin/dependent/ -p bin/submodules -p bin bin/ietf-bgp@2021-06-22.yang -i

And here is the tarball.

[bgp.tar.gz](https://github.com/CESNET/libyang/files/6697368/bgp.tar.gz)

**Comment by michalvasko** [comment]
So I have tried it with latest `devel` of *libyang* and after removing all the submodules for both 2020 and 2021 revisions, all the warnings are gone and the main module was loaded fine. As for the status warning, you can mostly ignore it. All it says is that there is a node with changed status (`obsolete`) and some of its descendants do not have this status set explicitly. While YANG does not specify that it is inherited to all the descendants (so ideally should be specified for all the children, too), it was discussed on the mailing and the intention was for status to be inherited, so it is.

**Comment by mjethanandani** [comment]
Hi Michal, thanks for sharing your observation. I will say that I had removed the include in some of the sub-modules but not all based on what I saw reporting as an error. Let me try removing in all of them.

**Comment by michalvasko** [comment]
I removed the includes one-by-one and not encountered any error. Just attach the exact modules causing the error, I simply cannot reproduce it.

**Comment by mjethanandani** [comment]
My bad. The error is being reported by pyang and not libyang. I use both to validate the model.
