### ISSUE TITLE
question: why lyd_new_path must contain quotes inside the predicate when creating list?

### ISSUE THREAD

**Issue by lyzliyuzhi91** [CESNET/libyang#1639]
```
(gdb) p (lyd_node_t *)lyd_new_path(0, g_schema_ctx, "/ietf-interfaces:interfaces/interface[name='kkk']", 0, 0, 0)   
$47 = (lyd_node_t *) 0xaaab1aff28e0
(gdb) p (lyd_node_t *)lyd_new_path(0, g_schema_ctx, "/ietf-interfaces:interfaces/interface[name=\"kkk\"]", 0, 0, 0) 
$48 = (lyd_node_t *) 0xaaab1afed750
(gdb) p (lyd_node_t *)lyd_new_path(0, g_schema_ctx, "/ietf-interfaces:interfaces/interface[name=kkk]", 0, 0, 0)     
$49 = (lyd_node_t *) 0x0
```
why lyd_new_path must contain quotes inside the predicate when creating list? I am using libyang1.0.130.
thanks

**Comment by michalvasko** [comment]
To be a subset of XPath, which requires them there, in short.

**Comment by lyzliyuzhi91** [comment]
Are there some rfcs or standards that specific such grammar?

**Comment by michalvasko** [comment]
Naturally, XPath has its specification, which [YANG 1.1](https://datatracker.ietf.org/doc/html/rfc7950#section-6.4) references.

**Comment by lyzliyuzhi91** [comment]
But I cannot find any description that we must wrap a pair of quotes around the value.

**Comment by michalvasko** [comment]
Well, that is buried somewhere deep in the specification. It all comes down to this. If you write
```
/model:container/list[key=value]
```
what you are specifying is a `list` instance with its `key` node value equal to its `value` node value. Which is completely different from
```
/mode:container/list[key='value']
```
which means `list` value with its `key` node value equal to a literal (string) `value`.

**Comment by lyzliyuzhi91** [comment]
thanks so much!
