### ISSUE TITLE
Miss nodes under an LYS_ACTION node when use lyd_merge

### ISSUE THREAD

**Issue by lyzliyuzhi91** [CESNET/libyang#1642]
https://github.com/CESNET/libyang/blob/10a1f0f038014ddd6fffa967486cfdfec99d06d4/src/tree_data.c#L2806

I think this line shoud consider the LYS_ACTION condition ？

**Comment by michalvasko** [comment]
Okay, changed.

**Comment by lyzliyuzhi91** [comment]
OK
