### ISSUE TITLE
`ly_ctx_load_module` returns const value

### ISSUE THREAD

**Issue by syyyr** [CESNET/libyang#1645]
Hi, `ly_ctx_load_module` returns `const lys_module*`. Afaik right after the call I can retrieve a non-const version with `ly_ctx_get_module`. Could `ly_ctx_load_module` also return a non-const version? Or is there another reason it's this way?

**Comment by michalvasko** [comment]
There was quite a chaos, it was inherited from v1. So I have unified it to non-const, should cause no problems.

**Comment by syyyr** [comment]
Thanks!

**Comment by syyyr** [comment]
Could `lys_parse_path` and `lys_parse_mem` (and possibly similar) output params be changed to also return non-const lys_module?

**Comment by michalvasko** [comment]
Okay, it makes sense for it all to be unified.

**Comment by syyyr** [comment]
Thanks!
