### ISSUE TITLE
Config disappears when using lyd_parse_op()

### ISSUE THREAD

**Issue by awesomenode** [CESNET/libyang#1647]
Hi!

Using libnetconf2 I've faced the issue of sometimes receiving empty config in my edit- config callback, so I've checked the libnetconf2 code and saw that probably lyd_parse_op() somehow "swallows" the config.

I could reproduce the issue in a simple example I've attached.

libyang version is the latest devel (2.0.28)

Thanks!
[parse_op_fault.tar.gz](https://github.com/CESNET/libyang/files/6764419/parse_op_fault.tar.gz)

**Comment by michalvasko** [comment]
The container was only not printed because code deciding that was not written well, should be fixed now.

**Comment by awesomenode** [comment]
Yes, it works fine now, thanks!
