### ISSUE TITLE
yanglint: No module with namespace error

### ISSUE THREAD

**Issue by davehouser1** [CESNET/libyang#1648]
Every time I try to compare a yang module against a xml file, I get this error:

```
libyang[0]: No module with namespace "urn:ietf:params:xml:ns:netconf:base:1.0" in the context. (path: Line number 1.)
YANGLINT[E]: Failed to parse input data file "data1.xml".
```

First line of each xml file reads:

```
$ head -n1 data1.xml
<ns0:data xmlns:ns0="urn:ietf:params:xml:ns:netconf:base:1.0">
```

Why does yanglint not like this entry? How can I fix this?

**Comment by michalvasko** [comment]
Well, what is the `data` element in this namespace supposed to represent, where is it defined?

**Comment by hjensas** [comment]
I have a similar issue:

```
yanglint \
  --path ./yang-models-flat \
  ./yang-models-flat/openconfig-mpls-types.yang \
  ./yang-models-flat/openconfig-vlan-types.yang \
  ./yang-models-flat/openconfig-vlan.yang \
  ./yang-models-flat/openconfig-network-instance.yang  \
  ./yang.xml
```

> libyang err : No module with namespace "urn:ietf:params:xml:ns:netconf:base:1.0" in the context. (Line number 1.)
> YANGLINT[E]: Failed to parse input data file "./yang.xml".

**yang.xml**:
```
<config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
  <network-instances xmlns="http://openconfig.net/yang/network-instance">
    <network-instance>
      <name>default</name>
      <config>
        <name>default</name>
      </config>
      <vlans>
        <vlan xc:operation="remove">
          <vlan-id>113</vlan-id>
          <config>
           <vlan-id>113</vlan-id>
            <name>5d3a9c397cb14bd3b67cbb471d01cbeb</name>
            <status>ACTIVE</status>
          </config>
        </vlan>
      </vlans>
    </network-instance>
  </network-instances>
</config>
```

**Comment by jktjkt** [comment]
If you add `--not-strict`, then libyang ignores "unknown" data. In your case, it will probably ignore (i.e., silently skip validation for) the root `<config>`, which is probably not what you want :). Are you using a correct `--type` option? This looks like a reply to some NETCONF command, and these need special handling.

**Comment by michalvasko** [comment]
Without details, just omit the `config` element (what is it supposed to be?) and the `operation`, too (it is invalid without a prefix in YANG).
```xml
  <network-instances xmlns="http://openconfig.net/yang/network-instance">
    <network-instance>
      <name>default</name>
      <config>
        <name>default</name>
      </config>
      <vlans>
        <vlan>
          <vlan-id>113</vlan-id>
          <config>
           <vlan-id>113</vlan-id>
            <name>5d3a9c397cb14bd3b67cbb471d01cbeb</name>
            <status>ACTIVE</status>
          </config>
        </vlan>
      </vlans>
    </network-instance>
  </network-instances>
```

**Comment by hjensas** [comment]
My reason for looking into yanglib/yanglint is to use it in CI testing of a netconf client application. The idea is to use yanglint to validate that the netconf get|get-config|edit-config etc operations we create is correct according to the yang model.

I belive, despite working with the servers I am testing against, the current RPC's  are not strictly correct. `<config>` should be `<nc:config>` or ` <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">` and `operation` should have a prefix i.e `nc:operation="merge|remove|replace"`. When I look at an actual RPC, the `nc` prefix is defined in `<edit-config>`, I belive the correct prefix for operation is `nc:operation` in this case.

```
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"
        message-id="urn:uuid:7ecb058a-c9dc-4574-812c-361e3fec5dd9">
<edit-config xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
<target>
<running/>
</target>
<config>
<network-instances xmlns="http://openconfig.net/yang/network-instance">
<network-instance>
<name>default</name>
<config>
<name>default</name>
</config>
<vlans>
<vlan nc:operation="remove">
<vlan-id>113</vlan-id>
<config>
<vlan-id>113</vlan-id>
<name>5d3a9c397cb14bd3b67cbb471d01cbeb</name>
<status>ACTIVE</status>
</config>
</vlan>
</vlans>
</network-instance>
</network-instances>
</config>
</edit-config>
</rpc>
```

Ideally I would like not to have to remove the `operation` before linting the data, if I try to lint this RPC with commandline:

```
yanglint \
  --type rpc \
  --path ./yang-models-flat \
  ./yang-models-flat/openconfig-mpls-types.yang \
  ./yang-models-flat/openconfig-vlan-types.yang \
  ./yang-models-flat/openconfig-vlan.yang \
  ./yang-models-flat/openconfig-network-instance.yang  \
  ./yang_rpc.xml
```

libyang err : Missing the operation node. (Line number 54.)
YANGLINT[E]: Failed to parse input data file "./yang_rpc.xml".

Error reported at Line number 54, in a file with 29 lines. I don't understand where operation node is missing.

**Comment by hjensas** [comment]
> To validate NETCONF messages, use `--type nc-rpc`. There is a difference between NETCONF and plain YANG data.

Ok, so I moved away from the package in fedora since `--type nc-rpc` is not in the version packaged. I compiled the devel branch instead.

**XML data:** *yang4.xml*
```
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:7ecb058a-c9dc-4574-812c-361e3fec5dd9">
  <edit-config xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
    <target>
      <running/>
    </target>
    <config>
      <network-instances xmlns="http://openconfig.net/yang/network-instance">
        <network-instance>
          <name>default</name>
          <config>
            <name>default</name>
          </config>
          <vlans>
            <vlan nc:operation="remove">
              <vlan-id>113</vlan-id>
              <config>
                <vlan-id>113</vlan-id>
                <name>5d3a9c397cb14bd3b67cbb471d01cbeb</name>
                <status>ACTIVE</status>
              </config>
            </vlan>
          </vlans>
        </network-instance>
      </network-instances>
    </config>
  </edit-config>
</rpc>
```

```
yanglint \
  --type nc-rpc \
  --path ./yang-models-flat \
  ./yang-models-flat/openconfig-mpls-types.yang \
  ./yang-models-flat/openconfig-vlan-types.yang \
  ./yang-models-flat/openconfig-vlan.yang \
  ./yang-models-flat/openconfig-network-instance.yang \
  ./yang4.xml
```

Result:
```
libyang err : Missing the operation node. (Line number 52.)
YANGLINT[E]: Failed to parse input data file "./yang4.xml".
libyang warn: String "" not freed from the dictionary, refcount 4
libyang warn: String "urn:ietf:params:xml:ns:netconf:base:1.0" not freed from the dictionary, refcount 4
libyang warn: String "target" not freed from the dictionary, refcount 1
libyang warn: String "5d3a9c397cb14bd3b67cbb471d01cbeb" not freed from the dictionary, refcount 1
libyang warn: String "running" not freed from the dictionary, refcount 1
libyang warn: String "edit-config" not freed from the dictionary, refcount 1
libyang warn: String "ACTIVE" not freed from the dictionary, refcount 1
libyang warn: String "config" not freed from the dictionary, refcount 1
libyang warn: String "113" not freed from the dictionary, refcount 2
```

**Comment by michalvasko** [comment]
Please try again with the current `devel`, there were several improvements needed and it should now work much better.

**Comment by hjensas** [comment]
> Please try again with the current `devel`, there were several improvements needed and it should now work much better.

Thanks! I pulled `commit 34fb9e0f4771e67eb6018963697c7a8214711eb0 (HEAD -> devel, origin/devel)`
It made a difference. The error changed.

libyang err : No module with namespace "urn:ietf:params:xml:ns:netconf:base:1.0" in the context. (Line number 3.)
YANGLINT[E]: Failed to parse input data file "./yang4.xml".

Is there a YANG model defining `urn:ietf:params:xml:ns:netconf:base:1.0` that I need to load? (I'm not aware of one, and I looked.)
If not, it seems it would make sense to special case this namespace?

**Comment by hjensas** [comment]
> Is there a YANG model defining `urn:ietf:params:xml:ns:netconf:base:1.0` that I need to load? (I'm not aware of one, and I looked.) If not, it seems it would make sense to special case this namespace?

**facepalm** - I just did not look properly. It is right here - https://github.com/YangModels/yang/blob/main/standard/ietf/RFC/ietf-netconf.yang

Once I include that, I am left with a couple of pages of warnings, no errors.

**Comment by michalvasko** [comment]
Then I think it is working as it should. The warnings may or may not be affecting functionality of the modules, it depends.
