### ISSUE TITLE
How to get `lysc_type*`'s description and typedef name

### ISSUE THREAD

**Issue by syyyr** [CESNET/libyang#1649]
Hello,

I have `lysc_type*`. Is it possible to retrieve info about the type's description and typedef name?

Maybe it is not possible with just the compiled type info. I can see that the lysc_nodes can be connected to the original parsed tree with a flag in the context. Is it possible to get the parsed info anyway even if I don't use this flag?

**Comment by michalvasko** [comment]
You have found out everything on your own, I do not have much to add. Only that no, it is not possible to get the parsed info directly if you do not use the flag.

**Comment by syyyr** [comment]
Thanks.

**Comment by syyyr** [comment]
I have one more question. I have this kind of model:
```yang
module example-schema {
    yang-version 1.1;
    namespace "http://example.com/";
    prefix lol;

    typedef myTypeInt {
        type int32;
        description "An int32 typedef.";
    }

    leaf typedefedLeafInt {
        type myTypeInt;
    }
}
```
Now, I use the setPrivParsed flag, get a `lysp_node_leaf` of `typedefedLeafInt`. Then I can get the associated `lysp_type`. Now, I want to know the description of the type ("An int32 typedef."). I can see the `dsc` field in `lysp_type_enum`, but I see nothing for ints and other types. Is it possible to get the description of the typedef? I can see that there is the `lysp_tpdf` struct, which is probably where the description is, but I don't know how to get retrieve it.

**Comment by syyyr** [comment]
Thinking about this, I realized I could probably take the `name` and `module` from `lysp_type` and find that typedef definition with `lysp_node_typedefs`? I'm not that would work.

**Comment by michalvasko** [comment]
Well, in this case you can take `name` from the `struct lysp_type` and since it has no prefix, find it in the typedefs of the `struct lysp_module` module. But you are basically doing reverse-compilation this way and there may be chains of typedefs referencing foreign types, which is not trivial to find correctly.

**Comment by syyyr** [comment]
I see. My use-case is this: I'm currently porting netconf-cli to libyang2 and simultaneously developing libyang-cpp. netconf-cli has a command called "describe" which prints out info about nodes based on a schema path. For leafs it also prints information about the type of the leaf. Usually, knowing the base type (like `string` or `int32`) is enough for the user, but sometimes, there might be some value in showing the name of the typedef. For example: have a leaf called `ip` which has a `string` base type, but the typedef name is actually called `ipv4-type`. Then the user knows they should use ipv4.

This is the code I used with the original libyang:
```cpp
std::optional<std::string> YangSchema::leafTypeName(const std::string& path) const
{
    libyang::Schema_Node_Leaf leaf(getSchemaNode(path));
    return leaf.type()->der().get() && leaf.type()->der()->type()->der().get() ? std::optional{leaf.type()->der()->name()} : std::nullopt;
}
```
The method returned a typedef name of a leaf, if the leaf had a typedefed type. I understand that what I want to do is not easily done and the new libyang is not optimized for that (I like the new approach, with the compiled modules!).

Anyway, I will try your suggestion, hopefully I can get it right.

**Comment by michalvasko** [comment]
I guessed the use-case but as you said, it is not really supported with the new approach.
