### ISSUE TITLE
ly_ctx_get_node return NULL when data_path is relative and start is a node defined in a submodule

### ISSUE THREAD

**Issue by lyzliyuzhi91** [CESNET/libyang#1658]
https://github.com/CESNET/libyang/blob/3b2e24645ba001adf7e60e45c9b7ddfda08e30bf/src/resolve.c#L2354

is here should be 
```
module = lys_node_module(start)
```
？

otherwise, when calling lys_getnext in line 2393
```
while ((sibling = lys_getnext(sibling, start_parent, module, 0))) {
```
it will return NULL for module->type is true when lys_getnext checking input parameters
```
    if ((!parent && !module) || (module && module->type) || (parent && (parent->nodetype == LYS_USES) && !(options & LYS_GETNEXT_PARENTUSES))) {
        LOGARG;
        return NULL;
    }
```

thanks.

**Comment by michalvasko** [comment]
Yes, your fix is correct and should now be committed.

**Comment by lyzliyuzhi91** [comment]
OK
