### ISSUE TITLE
werid backslash in lyd_new_path

### ISSUE THREAD

**Issue by lyzliyuzhi91** [CESNET/libyang#1660]
https://github.com/CESNET/libyang/blob/3b2e24645ba001adf7e60e45c9b7ddfda08e30bf/src/resolve.c#L1158

when I call the lyd_new_path to set name with single backslash
```
(gdb) p lyd_new_path(NULL, g_schema_ctx, "/ietf-interfaces:interfaces/interface[name=\"\\\"]", NULL, 0,0)  
$11 = (struct lyd_node *) 0x0
```
It return NULL, and report an error
```
[ERROR] libyang[0]: Unexpected character(s) '\' ("\\""]"). 
```
It seems that the single backslash is used to escape the ending double quote. Well.
Then I put two slash inside the predicate
```
(gdb) p lyd_new_path(NULL, g_schema_ctx, "/ietf-interfaces:interfaces/interface[name=\"\\\\\"]", NULL, 0,0)         
$6 = (struct lyd_node *) 0xaaaae7952820
(gdb) p ((lyd_leaf_t *)($6->child->child))->value_str   
$7 = 0xaaaae79411b0 "\\\\"
(gdb) p lyd_print_mem(&req, $6, transformat, LYP_NETCONF)                                                           
$8 = 0
(gdb) p req
$9 = 0xaaaae7957b70 "<interfaces xmlns=\"urn:ietf:params:xml:ns:yang:ietf-interfaces\"><interface><name>\\\\</name></
interface></interfaces>"
```
The value is really two backslash. I think this is not right. How can i set name with single backslash ?
Thanks.

**Comment by michalvasko** [comment]
Yes, support for escaped characters was not correct so I have removed it, it should not be needed.

**Comment by lyzliyuzhi91** [comment]
But if remove it, is is right for me to call the function like such
```
lyd_new_path(NULL, g_schema_ctx, "/ietf-interfaces:interfaces/interface[name=\"\\\"\"]", NULL, 0,0) 
```
It seems that the double quote after the backslash will be treated as an ending double quote?

**Comment by michalvasko** [comment]
Yes, that is intentional and not supported in XPATH 1.0 that is used by YANG. You can always use `'` to put `"` in a value but there is a limitation that you cannot put both `'` and `"` in an XPath literal so this change reflects that.

**Comment by lyzliyuzhi91** [comment]
Hi, can you give the the link that specifying 【you cannot put both ' and " in an XPath literal so this change reflects that】？ thanks

**Comment by lyzliyuzhi91** [comment]
If user set <name>"'</name> by netconf
but he or she cannot write a valid xpath corresponding to the interface with such name ?
In other words, a user can configure such a list key but cannot query it by xpath  ?
emm, I don't think it is reasonable

**Comment by michalvasko** [comment]
> Hi, can you give the the link that specifying 【you cannot put both ' and " in an XPath literal so this change reflects that】？

Look at [XPath grammar](https://www.w3.org/TR/1999/REC-xpath-19991116/#exprlex), `Literal`.

> In other words, a user can configure such a list key but cannot query it by xpath ?
emm, I don't think it is reasonable

Seems that way. You can search the WG mailing list, I seem to remember this was discussed quite a long time ago. And there were other people thinking it was not "reasonable".
