### ISSUE TITLE
libyang When condition includes a self-reference

### ISSUE THREAD

**Issue by barbarost** [CESNET/libyang#1661]
Hi,

With libyang 2.0.48 when enabling `when` condition for `AlternateReturnTime` (or `AlternateBandwidth`, `AlternateFrequency`, `AlternatePrimary` of `RadioConfig` container) in [mimosa.yang](https://github.com/CESNET/libyang/files/6841473/mimosa.yang.txt), I get following error:
```
[INF]: Applying scheduled changes.
[INF]: No scheduled changes.
[INF]: Connection 47 created.
[ERR]: When condition includes a self-reference.
sysrepoctl error: Failed to install module "/mbr-multi/projects/a5x8/files/etc/_sysrepo/yang/mimosa.yang" (libyang error)
[INF]: No datastore changes to apply.
```
I didn't have this error for libyang 1.x so not sure if our when condition is problematic or this is a bug in libyang 2.

Attaching also [regulatory.yang](https://github.com/CESNET/libyang/files/6841510/regulatory.yang.txt) which is needed to install.

Thanks in advance!

**Comment by michalvasko** [comment]
Seems to be a false-positive, should load successfully now.

**Comment by barbarost** [comment]
Thanks Michal!
