### ISSUE TITLE
Why to change to input parameter when calling lyd_new_path_update ?

### ISSUE THREAD

**Issue by lyzliyuzhi91** [CESNET/libyang#1667]
https://github.com/CESNET/libyang/blob/1b4ded71ac86c5b1ae5392ec98e7c54793cc0c5b/src/tree_data.c#L1840

Is this should be
```
any->value_type &= ~LYD_ANYDATA_STRING; /* make const string from string */
```
?
I can't see the effect of change the input parameter.
thanks

**Comment by michalvasko** [comment]
I will answer you this time but these issues are meant to provide support with problems if something does not work the way it should or for some enhancements, certainly not for explaining the code.

So, just look at the description of the values ([`LYD_ANYDATA_JSOND`](https://github.com/CESNET/libyang/blob/libyang1/src/tree_data.h#L63)), it is explained there that they are actually bitmaps to certain extent.

**Comment by lyzliyuzhi91** [comment]
Actually, I wanna ask it is correct for this function to not update the any->value_type when the values are not equal (for example, the value was changed from A CONST STRING to A DATATREE.)?
I don't see the place to do such update.

**Comment by michalvasko** [comment]
Right, it seems updating the value type was missing.
