### ISSUE TITLE
The RPC format is not normal. The netopeer server is not responding

### ISSUE THREAD

**Issue by alenzhangzhen** [CESNET/libyang#1672]
![image](https://user-images.githubusercontent.com/29158663/128591126-7714f4fb-3a5d-48d8-94d2-8161903f8f76.png)

![image](https://user-images.githubusercontent.com/29158663/128591133-47b24f4a-54d4-4da3-bebd-b38f110c5fad.png)
![image](https://user-images.githubusercontent.com/29158663/128591165-8e4dc42b-0fc2-4185-a61e-a3357e2de6cb.png)

**Comment by lePici** [comment]
Hi, the bugfix was created and written in [PR](https://github.com/CESNET/libyang/pull/1676) here. Unfortunately, the merge of the PR will be performed in two weeks because the colleague has a vacation, so please apply bugfix in _src/validation.c_ by hand for now.

**Comment by lePici** [comment]
The PR is now merged, so everything should be fine.
