### ISSUE TITLE
identities with multiple base statements and multiple if-features

### ISSUE THREAD

**Issue by ericvoit** [CESNET/libyang#1674]
I believe there is an issue with yanglint in its handling of identity validation where there are with multiple base statements and multiple if-feature support.   Specifics are as follows, and attached.

In the ietf-tcg-algs.yang from draft-ietf-rats-yang-tpm-charra  is the identity:

  identity TPM_ALG_SHA1 {
    if-feature "tpm12 or tpm20";
    base hash;
    base tpm12;
    base tpm20;
    description
      "...";
    reference
      "...";
  }
 

In ietf-tpm-remote-attestation.yang from the same draft, this identity is used as a default value:

  import ietf-tcg-algs {
    prefix taa;
  }
  ...
  leaf tpm12-hash-algo {
      type identityref {
        base taa:hash;
      }
      must '...' {
        error-message "...";
      }
      default "taa:TPM_ALG_SHA1";
      description
        "...";
    }

However the following error comes out of the latest version of YANGLINT currently available at https://yangvalidator.com/validator
(Mahesh J. has seen something like this in his tests too.)

libyang err : Invalid default - value does not fit the type (Invalid identityref "taa:TPM_ALG_SHA1" value - identity not found in module "ietf-tcg-algs".). (Schema location /ietf-tpm-remote-attestation-yanglint:rats-support-structures/tpms/tpm/tpm12-hash-algo.)

This error suggests to me that yanglint either cannot process the dual if-feature of the: 
    if-feature "tpm12 or tpm20"; 
statement.   
Or cannot handle the multiple base statements of the identity.
As a result it doesn't believe the identity 'TPM_ALG_SHA1' is available when it should be.
 
Any suggestions appreciated. (Sadly, yanglint version isn't currently showing on https://yangvalidator.com/validator)

[yanglint run - yangvalidator current.tar.gz](https://github.com/CESNET/libyang/files/6957593/yanglint.run.-.yangvalidator.current.tar.gz)

**Comment by lePici** [comment]
I believe the _yangvalidator_ has an older version of our _yanglint_. I tried _yanglint_ ([with version](https://github.com/CESNET/libyang/commit/e8e37ae07cab89846dfb34e21fa358d76f6057be)) this way:

`./yanglint -p /home/lePici/hdd/conf/yang /home/lePici/hdd/conf/yang/experimental/ietf-extracted-YANG-modules/ietf-tcg-algs@2021-05-11.yang  /home/lePici/hdd/conf/yang/experimental/ietf-extracted-YANG-modules/ietf-tpm-remote-attestation@2021-05-11.yang`

(The "_yang_" directory contains models from [YangModels/yang](https://github.com/YangModels/yang))

And I didn't get the error message - _"... identity not found in the "ietf-tcg-algs" module..."_ .
I recently made changes to the identity statement, and when I switched to the version before those [changes](https://github.com/CESNET/libyang/commit/695092a771e7a4c6abb5283521f36708b6bceaf2), I got an _"identity not found"_ error message too.

**Comment by ericvoit** [comment]
I was hoping this bug was already caught :-)   Thanks for doing the check on this!

 

Eric
