### ISSUE TITLE
libyang[0]: Merging operation "create" failed.

### ISSUE THREAD

**Issue by berstrob** [CESNET/libyang#1675]
Hi,
i tried to switch to the newest libyang,sysrepo,netopeer Versions (devel last friday 06.08.2021), first i have to say way faster :-) (that was a main reason i wanted to switch form libyang v1). but i encountered a very strange bug, with my program after i ported all of it:
```
libyang[0]: Internal error (/home/bernd/projects/netconf/libyangnew/libyang/src/diff.c:1359).
libyang[0]: Merging operation "create" failed.
```

I tried Troubleshooting/condensing it down: it occurs within "openconfig-system" and there only with the dns-servers not with the nearly identical ntp-servers, it properly has todo with the type ( oc-inet:ip-address vs. oc-inet:host ) i would guess.

I wrote a minimal program(needs the openconfig yangmodels) , just need to run it two times, first is fine : it creates the config , the second time it fails. (with `char servertyp="dns"; `  but you can run it multiple time with the char `servertyp="ntp";` line ) . if you need me to write my own model instead of using the openconfig one i could try that as well.

Regards Bernd 

[oc_system_test.zip]

EDIT:  
sorry you might want to change those lines to that  below so it  does what it is supposed to do (and the compiler does not complain, i tested it manual changing the dns/ntp , but wanted to make it more easy :) )

 ```
// char servertyp[50]="ntp";     //####################### works!!!
    char servertyp[50]="dns";   //####################### does not work!!!

    snprintf(buffer,sizeof(buffer),"/openconfig-system:system/%s/servers",servertyp);
    sr_delete_item(session, buffer,SR_EDIT_ISOLATE);
```

EDIT2:
found the difference i think : dns is  `ordered-by user;`  but after that i am not sure how that all is supposed to work :(.

**Comment by michalvasko** [comment]
The attachment link got lost, please upload it again so that I can test it.

**Comment by berstrob** [comment]
[oc_system_test.zip](https://github.com/CESNET/libyang/files/7031391/oc_system_test.zip)

Hi, 
sure here you go (i fixed the lines from edit 1 already) , i also played a bit with it and  adding : 
```
           if (!orig_meta) {
                LY_CHECK_RET(lyd_diff_change_op(diff_match, LYD_DIFF_OP_NONE));
            } else {
```
into diff.c  (around 1360) ,closing the ` else` at 3180 does not crash/error, but not sure it works as intended then ;)

**Comment by michalvasko** [comment]
Should now work with the latest *sysrepo*.

**Comment by berstrob** [comment]
Thank you very much , works with no issues so far.
