### ISSUE TITLE
Facing pcre version issue 

### ISSUE THREAD

**Issue by rosy8** [CESNET/libyang#1677]
Hi Michal,

I have cloned the latest version of libyang and trying to build a libyang.a.
For doing so I have made the build static option ON as shown below and have added the  pcre2-devel  and pcre2 libs.
option(ENABLE_STATIC "Build static (.a) library" ON)

As per libyang doc the pcre2 version requirement should be > 10.21 
**(libpcre2 >= 10.21 (including devel package)**

In my case, the installed version is **(Version: 10.23)** 

However, while for the CMake command I am getting the following error

bash-4.2$ cmake ..
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  **Could NOT find PCRE2 (missing: PCRE2_LIBRARY) (found suitable version
  "10.23", minimum required is "10.21")**
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  CMakeModules/FindPCRE2.cmake:19 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:308 (find_package)

-- Configuring incomplete, errors occurred!
See also "/mnt/data0/hpatel/libyang_latest/libyang/build/CMakeFiles/CMakeOutput.log".
See also "/mnt/data0/hpatel/libyang_latest/libyang/build/CMakeFiles/CMakeError.log".
bash-4.2$

Would appreciate it if you could let me know If I am missing something here.

Thank you in advance.
Regards,

**Comment by michalvasko** [comment]
The error is confusing to say the least but perhaps the problem is that your installed PCRE2 library is shared instead of static? I do not have much experience with building static libraries so I do not know whether a static library can be compiled with some dynamic libraries as dependencies.

**Comment by Abrahamma97** [comment]
@rosy8 can you try with sudo apt-get install libpcre2-dev

**Comment by Tanco-K** [comment]
@michalvasko hi，excuse me. Can I use libyang 1.0.240  with pcre2?

**Comment by michalvasko** [comment]
No, *libyang* v1.x uses the predecessor PCRE.

**Comment by Tanco-K** [comment]
@michalvasko Thanks！
