### ISSUE TITLE
Incorrect LYB serialization on big endian platform

### ISSUE THREAD

**Issue by linnaea** [CESNET/libyang#1681]
https://github.com/CESNET/libyang/blob/e8e37ae07cab89846dfb34e21fa358d76f6057be/src/parser_lyb.c#L531
https://github.com/CESNET/libyang/blob/e8e37ae07cab89846dfb34e21fa358d76f6057be/src/parser_lyb.c#L828
https://github.com/CESNET/libyang/blob/e8e37ae07cab89846dfb34e21fa358d76f6057be/src/parser_lyb.c#L887
https://github.com/CESNET/libyang/blob/e8e37ae07cab89846dfb34e21fa358d76f6057be/src/printer_lyb.c#L664
These are enum values, and should be read/written with `lyb_read_number`/`lyb_write_number`

https://github.com/CESNET/libyang/blob/e8e37ae07cab89846dfb34e21fa358d76f6057be/src/printer_lyb.c#L582
This also seems to be problematic

**Comment by michalvasko** [comment]
Okay, thanks for pointing them all out, the correct functions should now be used.

**Comment by linnaea** [comment]
Confirm fixed on ppc64 and z390x
