### ISSUE TITLE
lyd_parse_data_mem returns NULL rpc arg.

### ISSUE THREAD

**Issue by sterlite-del** [CESNET/libyang#1684]
Hi,

I am calling the libyang API as follows:
if (lyd_parse_data_mem(ns_ly_ctx, get_data, LYD_JSON, 0, LYD_VALIDATE_PRESENT, &rpc_resp))

The call to lyd_parse_data_mem doesn't return error. But still the lyd_node *rpc_resp returns NULL.

I need the rpc_resp parameter to populate a netconf reply for the client of this server.

Can someone help me out with this problem ? Or if I am doing something wrong please advise.

**Comment by michalvasko** [comment]
Seems `get_data` is empy, are there really valid JSON data? If it is an RPC response (reply), you want to use `lyd_parse_op()` instead.

**Comment by sterlite-del** [comment]
Hi, I tried the lyd_parse_op function to populate the rpc_resp as follows:
            _printf("kc: 44 %s\n" , get_data);
            ly_in_new_memory(get_data, &in);

            /* Parse the json in get_data to give the response to the GET RPC. */
            if (lyd_parse_op(ns_ly_ctx, NULL, in, LYD_JSON, LYD_TYPE_RPC_YANG, &rpc_resp, &op)) {
                ERR("Call to lyd_parse_op module failed.");
                return NULL;
            }_

I get the following error output (lyd_parse_op failure) as follows:
kc: 44 {"openconfig-interfaces:config":{"description":"","mtu":9100,"name":"Ethernet4"}}
[ERR]: LY: Node "config" not found in the "openconfig-interfaces" module. (Line number 1.)
[ERR]: NC: Call to lyd_parse_op module failed.

Although I have loaded the openconfig-interfaces.yang file, it complains that it cannot find the "config" node.

Any ideas as to why this is ?

**Comment by sterlite-del** [comment]
I think I may have to get the topmost parent in the schema and somehow convert the json response to the entire
hierarchy of containers. How can one accomplish this from the input rpc ?

**Comment by michalvasko** [comment]
> Although I have loaded the openconfig-interfaces.yang file, it complains that it cannot find the "config" node.
Any ideas as to why this is ?

Well, can you show me where a top-level node named `config` is defined in `openconfig-interfaces`? I do not think it is there.

> I think I may have to get the topmost parent in the schema and somehow convert the json response to the entire
hierarchy of containers. How can one accomplish this from the input rpc and the get_data content ?

You want to parse non-top-level data? Not sure what use-case requires that but *libyang* v2 does support it. If you supply the parent of the parsed data for them to be connected to, it should be parsed successfully.

**Comment by sterlite-del** [comment]
"You want to parse non-top-level data? Not sure what use-case requires that but libyang v2 does support it. If you supply the parent of the parsed data for them to be connected to, it should be parsed successfully."

Into which API (and how) do I supply the parent of the parsed data so that non-top-level data gets parsed successfully ?

**Comment by michalvasko** [comment]
`lyd_parse_data()`

**Comment by sterlite-del** [comment]
And how do we get the parent node say of this type of string: 
"/openconfig-interfaces:interfaces/interface=Ethernet4/config" ?

**Comment by michalvasko** [comment]
There are several ways, but you can, for example, create it yourself using `lyd_new_*()` functions or even simpler using only `lyd_new_path()`.
