### ISSUE TITLE
libyang2 uses internal glibc header, and cannot be built against musl

### ISSUE THREAD

**Issue by qlyoung** [CESNET/libyang#1688]
Attempting to build libyang against musl libc results in:

```
/test/src/libyang-2.0.7/src/log.c:16:10: fatal error: sys/cdefs.h: No such file or directory
   16 | #include <sys/cdefs.h>
      |          ^~~~~~~~~
```

A cursory search yields:
https://wiki.musl-libc.org/faq.html#Q:-When-compiling-something-against-musl,-I-get-error-messages-about-%3Ccode%3Esys/cdefs.h%3C/code%3E

Until this is rectified, libyang2 cannot be built on Alpine or any other musl libc platform.	

https://github.com/CESNET/libyang/blob/master/src/log.c#L16, and many others.

This was introduced [here](https://github.com/CESNET/libyang/commit/32874e17e9d91e7505ceb386e0bc96a1189a0edb).

@choppsv1 ping

Edit:
Looks like there were already references to this header all over the place, wasn't introduced in the commit I linked.

**Comment by qlyoung** [comment]
Nevermind, looks like this was fixed at some point.

**Comment by linnaea** [comment]
Addressed in [this commit](https://github.com/CESNET/libyang/commit/8f4907590afbe3eafabcf5b461c0ae51b65c3a37) needs another 2.x release(#1673)

**Comment by qlyoung** [comment]
I don't see that commit on `master`. What branch is that on?

**Comment by linnaea** [comment]
> I don't see that commit on `master`. What branch is that on?
`devel` branch

**Comment by lucize** [comment]
@linnaea the same for netopeer2 ?

**Comment by michalvasko** [comment]
I did not find any include for `sys/cdefs.h` in the `master` branch of *netopeer2*.

**Comment by lucize** [comment]
ah, ok, I've used the release version

**Comment by michalvasko** [comment]
The latest release is `master`, perhaps you have used an older one.

**Comment by lucize** [comment]
https://github.com/CESNET/netopeer2/blob/8ec6d81d2a4991535c448e011e13380134d2bcfe/src/log.c#L18

**Comment by michalvasko** [comment]
Right, thanks, I properly searched for it now and found those. Should now be fixed in `devel`.
