### ISSUE TITLE
Question: why no longer use flex and bison to parse yang in libyang2?

### ISSUE THREAD

**Issue by lyzliyuzhi91** [CESNET/libyang#1696]
The yang modules are parsed through flex and bison in libyang1, but it seems that libyang2 no longer depend on such two tools.
Why? Is the performance not good enough ? Or the .y file too complicated to maintain ?
Out of curiosity. Thanks so much.

**Comment by michalvasko** [comment]
In short, because of complexity of the code and difficult maintenance. Also, it was required for the data to be terminated by 2 `\0` chars, which caused some ugly problems.

**Comment by lyzliyuzhi91** [comment]
OK, thanks!
