### ISSUE TITLE
"list" inside action output always requires "key" value to be specified

### ISSUE THREAD

**Issue by rharishkumar** [CESNET/libyang#1697]
```
  grouping abc-mount {
    description "abc-mount grouping";
    container state {
      description "state container";

      action def-action {
        description "def-action";
        input {
          leaf name {
            type string;
            description "name leaf";
          }
        }
        output {
          list output-list {
            description "output-list";
            leaf output {
              type string;
              description "output leaf";
            }
          }
        }
      }
```
When adding these YANG models, we could observe the below errors.
```
libyang[0]: Missing keyword "key" as a child to "list". (path: /abc:state/def-action/output/output-list)
libyang[0]: Module "abc" parsing failed.

```
As per RFC7950 (https://datatracker.ietf.org/doc/html/rfc7950#section-7.14.3), "Since the output tree is not part of any datastore, all "config" statements for nodes in the output tree are ignored". Hence, we expect that the above mentioned action should work without any errors.

**Comment by michalvasko** [comment]
I have failed to reproduce, what version of *libyang* are you using?

**Comment by rharishkumar** [comment]
Primarily, we have been using netopeer2-1.1.76 which uses libyang-1.0.240

https://github.com/CESNET/netopeer2/releases/tag/v1.1.76

**Comment by michalvasko** [comment]
Right, the grouping was the problem, should work now in latest `libyang1` branch.
