### ISSUE TITLE
Warnings when referencing to import-only module

### ISSUE THREAD

**Issue by rharishkumar** [CESNET/libyang#1720]
We observe warnings when referencing import-only modules. Could you please clarify if this is expected?

`ly WARNING: When condition "../temp-v1:type = type-1" check skipped because referenced module "temp-v1" is not implemented.
ly WARNING: Schema node "type-2" not found; in expr "../type = type-2" with context node "/temp-v2/profile".`

Here the leaf 'type' and enum values are defined in an import-only module 'temp-v1.yang'.

**Comment by rharishkumar** [comment]
Even after changing to "implement" module, I could observe the warnings.
This is specifically seen when using 'grouping' and 'uses' statement.
In our case, the grouping is defined in a different yang model. Below is an example.

```
first.yang:
...
typedef typedef-a {
    type enumeration {
         enum enum-a1;
         enum enum-a2;
    }
}
...
grouping group-a {
    leaf leaf-a {
        type typedef-a;
    }
...

```
```
second.yang:
...
grouping group-c {
    leaf leaf-c {
        type string;
    }
}
grouping group-b {
    list list-b {
        key "name";
        leaf name {
            type string;
        }
        uses first:group-a;
        uses group-c {
            when '../leaf-a = enum-a1';
        }
    }
}
...
uses group-b;
...
```

**Comment by michalvasko** [comment]
I will be guessing here but you should look at the error more carefully, you probably want to change the `when` to
```
            when "../leaf-a = 'enum-a1'";
```

**Comment by rharishkumar** [comment]
Thanks this was also one of the mistakes we had done. We also had another wrong reference which caused the warnings. The warnings were cleared when we tried changing as shown below.
`
            when "leaf-a = 'enum-a1'";
`
