### ISSUE TITLE
List of integers converted to list of strings when printing

### ISSUE THREAD

**Issue by pepa-cz** [CESNET/libyang#1729]
Leaf-list of integers represented by union types in a model is converted to a list of strings when printing data.

Using `yolo-system.yang` model from [libyang-python ](https://github.com/CESNET/libyang-python/tree/master/tests/yang/yolo ) repository.

Input data `tesdata.json`:
```
{
  "yolo-system:conf": {
    "number": [
      1000,
      2000,
      3000
    ]
  }
}
```
Print data instance using `yanglint` tool:
```
libyang-python/tests$ yanglint yang/yolo/yolo-system.yang -p yang/omg -p yang/wtf -d all -f json tesdata.json
{
  "yolo-system:conf": {
    "number": [
      "1000",
      "2000",
      "3000"
    ]
  }
}
```

A list of numbers is converted to a list of strings but I would expect no conversion at all. List items are modelled as a nested union type (see [wtf-types.yang](https://github.com/CESNET/libyang-python/blob/master/tests/yang/wtf/wtf-types.yang#L29)) including integers only.

**Comment by pepa-cz** [comment]
Libyang version
```
libyang-python/tests$ yanglint -v
yanglint 2.0.97
```

**Comment by michalvasko** [comment]
You are correct, this was simply a bug and now unions should be printed according to the type they were validated as.
