### ISSUE TITLE
Is there a way to get key order for list nodes from a YANG schema?

### ISSUE THREAD

**Issue by barbarost** [CESNET/libyang#1730]
Hi,

RESTCONF requires list key values are passed without specifying the key name so key names should be obtained from the corresponding YANG schema. Does libyang provide a way to learn the order of list keys as described in the YANG schema?

For the example below, if I iterate through the children of `l1` node and check for `LYS_KEY` flag, I get `a` first and then `b`. However since keys are defined in the order as `b` first and then `a`, I need to get the key node in that order.

```
list l1 {
    key "b a";
    leaf a {
        type string;
    }
    leaf b {
        type string;
    }
    leaf c {
        type string;
    }
}
```

Thanks.

**Comment by michalvasko** [comment]
Well, I have found no information about "key order" in RFC 7950 so the question is whether it is determined by the `key` statement or the actual order of the key schema leaves. *libyang* v2 (not sure if you are using v1 or v2, there is a difference) tries to store the keys in their correct order but it is determined simply from the actual order of the schema nodes so only if these are not the first descendants of the `list`, they are moved at the beginning.

**Comment by barbarost** [comment]
Right, there is no information about it in RFC 7950 but RFC 8040 (RESTCONF Protocol) has (section 3.5.3):
```
   o  If there are multiple key leaf values, the path segment is
      constructed by having the list name, followed by the value of each
      leaf identified in the "key" statement, encoded in the order
      specified in the YANG "key" statement.  Each key leaf value except
      the last one is followed by a comma character.
```
That's why I was trying to understand if learning that order from libyang v2 is possible.

Thanks.

**Comment by michalvasko** [comment]
I see, it seems the keys are already ordered based on the `key` statement, I did not even remember. I have added tests for it at least.
