### ISSUE TITLE
Support for unknown timezone in yang:date-and-time

### ISSUE THREAD

**Issue by syyyr** [CESNET/libyang#1734]
Hi, [RFC 6991](https://datatracker.ietf.org/doc/html/rfc6991) for yang:date-and-time says, that specifying "-00:00" as a timezone means that it is an unknown timezone. If the timezone is unknown, no correction for local time should be performed and the canonical format is with the "-00:00" timezone. However, libyang still performs this correction:
```cpp
#include <iostream>
#include <libyang/libyang.h>
#include <string>

const auto schema = R"(
module my {
    namespace "http://example.com";
    yang-version 1.1;
    prefix lol;
    import ietf-yang-types {
        prefix yang;
    }

    leaf myDateTime {
        type yang:date-and-time;
    }
}
)";

int main(int argc, char* argv[])
{
    ly_ctx* ctx;

    ly_ctx_new(nullptr, 0, &ctx);
    lys_parse_mem(ctx, schema, LYS_IN_YANG, nullptr);
    lyd_node* date_node;
    lyd_new_path(nullptr, ctx, "/my:myDateTime", "2017-02-01T00:00:00-00:00", 0, &date_node);
    // This prints a different value
    std::cerr << "lyd_get_value(date_node) = " << lyd_get_value(date_node) << "\n";

    lyd_free_all(date_node);
    ly_ctx_destroy(ctx);

    return 0;
}
```
The above example shows the current behavior. I'd like libyang to support the unknown timezone. The reason is that if the value changes based on the local machine's settings, tests break.

**Comment by michalvasko** [comment]
Right, this case was not handled specially but it should be. I made some changes and it seems to work now, let me know if it does not.

**Comment by syyyr** [comment]
Thanks.

**Comment by syyyr** [comment]
I got one more example, that doesn't work: setting `2015-05-19T00:00:00-00:00`, prints out `2015-05-19T01:00:00-00:00`, with the same code in the original example. I think it has something to the with DST.

**Comment by michalvasko** [comment]
It works fine for me so I am not able to determine where the problem is. Also, I do not really understand why `2017-02-01T00:00:00-00:00` and `2021-02-29T00:00:00-00:00` would work fine (they are in the tests) but your example not. In any case, I do not think the problem is related to DST based on this.

**Comment by syyyr** [comment]
I am not 100% sure it is based on DST, but it does depend on the value of the TZ variable. For example, Japan does not use DST and the bug does not happen with `Asia/Japan`:
```
$ TZ=America/New_York ./a.out 
input date               = 2015-05-19T00:00:00-00:00
lyd_get_value(date_node) = 2015-05-19T01:00:00-00:00
$ TZ=Asia/Japan ./a.out 
input date               = 2015-05-19T00:00:00-00:00
lyd_get_value(date_node) = 2015-05-19T00:00:00-00:00                                                                                                                                                  
$ 
```
"input date" is just the string i pass to `lyd_new_path`. It might only be that the bug happens on a new version of glibc/Linux/something-else? I am using Arch Linux. I didn't realize, but it does NOT actually happen on our CI with Fedora which also uses pretty new versions. I'll when exactly the bug happens.

**Comment by syyyr** [comment]
It seems like "Asia/Japan" is not a valid TZ, but it's all the same with "Asia/Tokyo".

**Comment by michalvasko** [comment]
You are right, DST needed to be taken into consideration. Should work now properly.

**Comment by syyyr** [comment]
Seems to work, thanks.
