### ISSUE TITLE
Internal error when validation RPC data

### ISSUE THREAD

**Issue by pepa-cz** [CESNET/libyang#1743]
When validating RPC internal error occurs.

`libyang[0]: Internal error (xxxxxx/libyang/src/validation.c:1315).`

Using yolo-system.yang model from [libyang-python](https://github.com/CESNET/libyang-python) repository.

```
#include <libyang/libyang.h>

int main()
{
    struct ly_ctx* ctx;
    struct lyd_node *dnode, *dnode1;
    struct lys_module* mod;

    ly_ctx_new(NULL, 0, &ctx);
    ly_ctx_set_searchdir(ctx, "yang");
    mod = ly_ctx_load_module(ctx, "yolo-system", NULL, NULL);
    lyd_new_path(NULL, ctx, "/yolo-system:format-disk", NULL, 0, &dnode);
    lyd_new_term(dnode, NULL, "duration", "42", 1, &dnode1);
    lyd_validate_all(&dnode, ctx, LYD_VALIDATE_NO_STATE, NULL);
    ly_ctx_destroy(ctx);
}
```

Libyang version

```
$ yanglint -v
yanglint 2.0.118
```

Thanks.

**Comment by michalvasko** [comment]
Right, a proper error message should now be printed. Note that you should use `lyd_validate_op()` instead when validating RPCs/actions/notifications.
