### ISSUE TITLE
libyang module features enabling

### ISSUE THREAD

**Issue by BogdanF01** [CESNET/libyang#1745]
Hi,

I have the following situation using libyang 2.0.112 :

Server connects first time.
**Client** sends:
```xml
<get-data>
  <datastore>ds:operational</datastore>
  <xpath-filter xmlns:yanglib="urn:ietf:params:xml:ns:yang:ietf-yang-library">/yanglib:*</xpath-filter>
  <config-filter>false</config-filter>
</get-data>
```

**Server** replies:
```xml
<data>
  <yang-library>
    ..........
    <module>
      <name>o-ran-hardware</name>
      <revision>2019-07-03</revision>
      <namespace>urn:o-ran:hardware:1.0</namespace>
      <location>file:///var/sysrepo/oran-v2/yang/o-ran-hardware@2019-07-03.yang</location>
    </module>
    ..........
  </yang-library>
  <modules-state>
    ..........
    <module>
      <name>o-ran-hardware</name>
      <revision>2019-07-03</revision>
      <schema>file:///var/sysrepo/oran-v2/yang/o-ran-hardware@2019-07-03.yang</schema>
      <namespace>urn:o-ran:hardware:1.0</namespace>
      <conformance-type>implement</conformance-type>
    </module>
    ..........
  </modules-state>
</data>
```
 
here no feature is enabled for module o-ran-hardware.
 
Then server is reset (client is not reset, context remains)
**Server** reconnects.
**Client** sends:
```xml
<get-data>
  <datastore>ds:operational</datastore>
  <xpath-filter xmlns:yanglib="urn:ietf:params:xml:ns:yang:ietf-yang-library">/yanglib:*</xpath-filter>
  <config-filter>false</config-filter>
</get-data>
```

**Server** replies:
```xml
<data>
  <yang-library>
    ..........
    <module>
      <name>o-ran-hardware</name>
      <revision>2019-07-03</revision>
      <namespace>urn:o-ran:hardware:1.0</namespace>
      <location>file:///var/sysrepo/oran-v2/yang/o-ran-hardware@2019-07-03.yang</location>
      <feature>ENERGYSAVING</feature>
    </module>
    <module>
    ..........
  </yang-library>
  <modules-state>
    ..........
    <module>
      <name>o-ran-hardware</name>
      <revision>2019-07-03</revision>
      <schema>file:///var/sysrepo/oran-v2/yang/o-ran-hardware@2019-07-03.yang</schema>
      <namespace>urn:o-ran:hardware:1.0</namespace>
      <feature>ENERGYSAVING</feature>
      <conformance-type>implement</conformance-type>
    </module>
    ..........
  </modules-state>
</data>
```

 now Server reports feature 'ENERGYSAVING' for module o-ran-hardware but for some reason when node data is parsed later this feature is seen as not enabled in the already implemented module.
 I have tried to enable that feature manually using ly_ctx_load_module() and checked with lys_feature_value() and feature gets enabled but again when it comes to parse node data the feature is found as not enabled.

I have to mention that if the Server reports the feature as enabled from the first connection it works fine.
Can you please share some thoughts of what might be wrong ?
Thank you.

**Comment by michalvasko** [comment]
I am really confused from this description and have no idea what you are doing and what the problem is. All I can tell you is that you are meant to enable features using `sysrepoctl`, calling `ly_ctx_load_module()` bypasses *sysrepo* so no wonder it does not work.

**Comment by BogdanF01** [comment]
Hi,
Thank you for clarification.
Forget the part where I used ly_ctx_load_module(), I just tried to manually force it and thanks for confirmation that it shouldnt work.

Those messages above are part of the module loading phase after hello exchange.
1. Client: Retrieving data for schema "ietf-datastores", revision "<latest>".
2. Server: Sends schema
3. Client: Retrieving data for schema "ietf-netconf-nmda", revision "<latest>".
4. Server: Sends schema
5. Client: Support for <get-data> from ietf-netcon-nmda found.
2. Client sends <get-data>  (message above)
3. Server replies: <data>    (message above)
And I was expecting that libyang is updating and rebuilding the module with enabled feature from the message.
Is my expectation wrong ? When is libyang updating a module with enabled features , based on what ?

**Comment by michalvasko** [comment]
Well, module features are not really updated. Meaning if you establish a NETCONF session, its capabilities (which includes enabled features) will not be changed during its lifetime. Like I said before, you change enabled features using *sysrepoctl*, *netopeer2-server* only reads the whole *libyang* context from *sysrepo*, in its current state.

**Comment by BogdanF01** [comment]
The problem I described is on client side.
And I tested it in v1 and it works there.
