### ISSUE TITLE
yanglint yin output generates broken XML

### ISSUE THREAD

**Issue by mzagozen** [CESNET/libyang#1746]
I used `yanglint` (latest version from *devel* branch) to convert a YANG module to XML. The resulting XML is broken - look at the `when` node (on line 2123. The `when` statement is used in the `container proxy` in `nokia-conf-aaa.yang` on line 2022:
```
   2123           <container name="proxy"            <when condition="../role = 'proxy'"/>
   2124 >
   2125             <status value="deprecated"/>
```

```
root@b8b3081a5955:/src# yanglint -f yin -s nokia-conf-aaa nokia-conf.yang > nokia-conf-aaa.xml
```

Please find attached the YANG modules:  [nokia-sros-20.10.tar.gz](https://github.com/CESNET/libyang/files/7659209/nokia-sros-20.10.tar.gz)

**Comment by michalvasko** [comment]
Okay, this bug should be fixed but it took me so long because a nasty memory leak was occurring for your use-case as well but I managed to fix that, too.

**Comment by mzagozen** [comment]
Excellent work @michalvasko, the XML now looks correct!
