### ISSUE TITLE
crash observed at yylex

### ISSUE THREAD

**Issue by kr234** [CESNET/libyang#1748]
Hello,

crash is observed at yylex during schema file read. This is seen few times. Can you please help to check this crash. 
libyang version used is libyang-1.0-r4.
[core.rumgr_834.11.1638964938.stacktrace.pdf](https://github.com/CESNET/libyang/files/7682993/core.rumgr_834.11.1638964938.stacktrace.pdf)

**Comment by michalvasko** [comment]
You can try using the latest 1.0 version, which is 1.0.249, it may be fixed. But even if it is not, you should be using *libyang* v2 by now where the YANG parser was written completely from scratch. Main reason for that was the huge complexity of maintenance of these generated parser files, so we will not be fixing it in v1.
