### ISSUE TITLE
Issue with identityref inside of an union

### ISSUE THREAD

**Issue by rwestphal** [CESNET/libyang#1752]
I'm trying to instantiate a node whose type is `mpls-label`, defined as follows in the _ietf-routing-types_ module:
```yang
  typedef mpls-label-special-purpose {
    type identityref {
      base mpls-label-special-purpose-value;
    }
    [snip]
  }

  typedef mpls-label-general-use {
    type uint32 {
      range "16..1048575";
    }
    [snip]
  }
  
  typedef mpls-label {
    type union {
      type mpls-label-special-purpose;
      type mpls-label-general-use;
    }
    [snip]
  }
```

The `lyd_new_path()` API works ok if I create a node of that type using a general purpose label (integer in the "16..1048575" range). However, if I try to create a special purpose label, like `ietf-routing-types:implicit-null-label` (namespace-qualified form as per RFC 7051), then it fails with the following error:
```
libyang[0]: Invalid union value "ietf-routing-types:implicit-null-label" - no matching subtype found. (path: Schema location /ietf-routing:routing/control-plane-protocols/control-plane-protocol/ietf-mpls-ldp:mpls-ldp/global/address-families/ipv4/bindings/fec-label/peer/label.)
identityref: lyd_new_path(): Invalid union value "ietf-routing-types:implicit-null-label" - no matching subtype found.
```

Here's a [small program](https://github.com/CESNET/libyang/files/7708664/identityref.c.zip) that can be used to reproduce the problem. Is this a bug or am I doing something wrong?

I'm using libyang v2.0.112. Any help would be appreciated.

**Comment by michalvasko** [comment]
Try to load also module `ietf-routing-types`, which must be implemented for its identities to be instantiated in data. I was looking at the error message but it would be difficult to improve, especially when the identityref is in an union, so you simply need to keep this in mind.

**Comment by rwestphal** [comment]
@michalvasko that makes sense. I was already loading `iana-if-type` to instantiate ethernet interfaces, but for some reason I forgot to do the same to instantiate MPLS labels. Thanks!
