### ISSUE TITLE
error: incompatible implicit declaration of built-in function ‘strndu p’ [-Werror]

### ISSUE THREAD

**Issue by lyzliyuzhi91** [CESNET/libyang#1756]
https://github.com/CESNET/libyang/blob/bfd6df6ce330e09d5c46ddc2dff7504a1f34baa2/src/xml.c#L15

I get compile error 
```
error: incompatible implicit declaration of built-in function ‘strndup’ [-Werror]
```
under a mips+uclibc environment on this file.
It should add a _GNU_SOURCE macro for using strndup.

thanks.

**Comment by michalvasko** [comment]
Fixed.
