### ISSUE TITLE
debian packaging migration issue

### ISSUE THREAD

**Issue by nickbroon** [CESNET/libyang#1759]
libyang2 is currently blocked from migrating from debian unstable to testing:
https://tracker.debian.org/pkg/libyang2

One of the error is reported by vcswatch:
`changelog package libyang does not match source libyang2`

libyang does not appear to live in salsa.debian.org, it appears the source packages are being generated from this repo using apkg, which I'm not familiar with, as compare to a regular debian source package in git.

However looking comparing:
https://github.com/CESNET/libyang/blob/master/distro/pkg/deb/control
https://github.com/CESNET/libyang/blob/master/distro/pkg/deb/changelog
both mention 'libyang2' so I'm unsure where the vscwatch error is coming from.

Though interestingly 
https://metadata.ftp-master.debian.org/changelogs//main/liby/libyang2/libyang2_2.0.112-6_changelog
differs from:
https://github.com/CESNET/libyang/blob/master/distro/pkg/deb/changelog
but also contains 'libyang2'. I'm sure the debian changelog is maintained.

It would good to get libyang2 migrated from unstable to testing.

**Comment by michalvasko** [comment]
Just so you know, we are not ignoring this but there is not much we can do right away. The official maintainer is being changed so it will take some time until things start moving again.

**Comment by michalvasko** [comment]
Actually, not sure what your interest in this is but if you had some official position in the Debian community you could perhaps help us.

**Comment by nickbroon** [comment]
Hi Michael,
Unfortunately I'm neither a Debian maintainer of Debian developer, so have no particular access for submitting/uploading packages. But I'm happy to help with packaging issues both here and in Salsa by submitting Merge-Requests where needed.
I'm just keen to be able to use libyang/libnetconf etc direct from Debian repo instead of having to build them myself from a git clone :-)

**Comment by michalvasko** [comment]
I see, then we should have it all covered once the new maintainer gets the required access, but until that happens we are stuck.
