### ISSUE TITLE
Printing metada of anyxml node is not correct

### ISSUE THREAD

**Issue by pepa-cz** [CESNET/libyang#1762]
Presenting xml attributes as metadata is not probably correct for anyxml nodes. 

Example data, successfully parsed by `lyd_parse_op()`:

```
 <rpc message-id="101"
      xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
   <get-config>
     <source>
       <running/>
     </source>
     <!-- get the user named fred -->
     <filter xmlns:el="urn:rdns:eu:test:yang:example:library"
             type="xpath"
             select="/el:library"/>
    </get-config>
 </rpc>
```

When printed by `lyd_print_mem()` in JSON format:

```
{
  "ietf-netconf:get-config": {
    "source": {
      "running": [null]
    },
    "filter": {
      "@": {
        "ietf-netconf:type": "xpath",
        "ietf-netconf:select": "/example-library:library"
      }
    }
  }
}
```
Once this output is parsed again by `lyd_parse_op()`, it throws error message:

```
libyang.util.LibyangError: failed to parse input data: Invalid metadata format - "@" can be used only inside anydata, container or list entries.
```

That's probably because `filter` item is `anyxml` and the annotation should be at the [same level](https://datatracker.ietf.org/doc/html/rfc7952#section-5.2.3) as `filter` item. Following is parsed correctly:

```
{
  "ietf-netconf:get-config": {
    "source": {
      "running": [null]
    },
    "@filter": {
      "ietf-netconf:type": "xpath",
      "ietf-netconf:select": "/example-library:library"
    },
    "filter": {
    }
  }
}
```

**Comment by michalvasko** [comment]
Right, it seems there were other problems as well, not just with the metadata but value as well. I have tried to fix all of it but the [specification](https://datatracker.ietf.org/doc/html/rfc7951#section-5.6) being quite vague, I had to decide some details myself.

**Comment by pepa-cz** [comment]
Okay, thanks!
