### ISSUE TITLE
Encoding anyxml data in JSON format

### ISSUE THREAD

**Issue by pepa-cz** [CESNET/libyang#1768]
Since commit bbdaddad5d36bf7ec69d2775099773dab3a40db7 there is an update that disallow to parse anyxml data encoded as a JSON object. However from [RFC7951](https://datatracker.ietf.org/doc/html/rfc7951#section-5.6):

> An anyxml instance is encoded as a JSON name/value pair.  The value  MUST satisfy I-JSON constraints.
>
>   Example: For the anyxml definition
>
>   anyxml bar;
>
>   the following is a valid JSON-encoded instance:
>
>   "bar": [true, null, true]

Now libyang expect anyxml data as name/value.

```
libyang[0]: The anyxml "config" is expected to be represented as JSON name/value, but input data contains name/object. (path: Schema location /ietf-netconf:edit-config, data location /ietf-netconf:edit-config, line number 1.)
```

In this case, there is also no chance to have reversible conversion between JSON and XML format because anyxml parsed in XML and printed in JSON cannot be parsed back as JSON.

What is you point of view on this please?

**Comment by michalvasko** [comment]
I am confused as to what exactly is the problem. The error is clear, it expects `name/value` but found `name/object`. Where did you get the input data? They are what is wrong and the current JSON printer should print it correctly.

**Comment by pepa-cz** [comment]
Here is an example of what I am trying to do

```
const char *op_data4 = " \
    {   \
        \"ietf-netconf:edit-config\": { \
            \"target\": { \
                \"ietf-netconf:running\": [null] \
            }, \
            \"config\": { \
                \"yolo-system:conf\": {  \
                    \"url\": [  \
                        { \
                            \"proto\": \"https\",  \
                            \"host\": \"github.com\",  \
                            \"fetch\": {\"timeout\": 42}  \
                        }  \
                    ]  \
                } \
            } \
        } \
    } \
";

int main()
{
    struct ly_ctx* ctx;
    struct lyd_node *dnode, *dnode1, *dnode2;
    struct ly_in *in;
    LY_ERR ret;

    ly_ctx_new(NULL, 0, &ctx);
    ly_ctx_set_searchdir(ctx, "yang");
    ly_ctx_load_module(ctx, "ietf-netconf", NULL, NULL);
    ly_ctx_load_module(ctx, "yolo-system", NULL, NULL);
    ly_in_new_memory(op_data4, &in);
    ret = lyd_parse_op(ctx, NULL, in, LYD_JSON, LYD_TYPE_RPC_YANG, &dnode, &dnode1);
}
```

```
$ gcc test.c -lyang -o test && ./test
libyang[0]: The anyxml "config" is expected to be represented as JSON name/value, but input data contains name/object. (path: Schema location /ietf-netconf:edit-config, data location /ietf-netconf:edit-config, line number 1.)
```

That worked before bbdaddad5d36bf7ec69d2775099773dab3a40db7. If I understand well a value of anyxml node should be a string?

```
anyxml bar;
---
"bar": "[true, null, true]"
```

**Comment by michalvasko** [comment]
Then like I said, the JSON input is wrong according to the [specs](https://datatracker.ietf.org/doc/html/rfc7951#section-5.6). It worked before simply because we have not noticed this problem until now. To add some context, the exact problem was that `anyxml` was handled exactly as `anydata` but it was not supposed to. So, to get the previous behavior, use `ietf-netconf-nmda:edit-data` instead of `ietf-netconf:edit-config`, the former uses `anydata` for the content.

**Comment by pepa-cz** [comment]
Okay I understand now. Anyxml definition in RFC7951 seems to be a bit confusing (at least for me) but the difference `anyxml` vs `anydata` is clear and they cannot be the same. Thanks.
