### ISSUE TITLE
Presence of list keys is not checked on subsequent entries when parsing JSON input

### ISSUE THREAD

**Issue by metaswitch-ak10** [CESNET/libyang#1772]
This is a bug that affects `libyang1` (hit on 1.0.224). I have not tested whether the same bug affects v2 as well.

List's keys are mandatory in YANG. There is currently a bug where the presence of keys is only checked on the first entry in a list when parsing JSON input.

I have made a fix for this in my fork of this repo and added a regression test. Please see the PR https://github.com/metaswitch-ak10/libyang/pull/1 for a detailed description of the issue and the fix. Could you please review my fix and help me get it merged in?

**Comment by jktjkt** [comment]
The PRs are usually opened against the "parent" or "upstream" repo, not against your own fork. You push to your fork, and then open a PR here.

**Comment by michalvasko** [comment]
Your PR looks fine to me but please do what @jktjkt said, create a clean fork of the current `libyang1` branch, commit the changes in your PR there and create a PR to our `libyang1` branch. Then I can merge it.

**Comment by metaswitch-ak10** [comment]
Thanks for the review and clarification - I've opened https://github.com/CESNET/libyang/pull/1775 as requested.
