### ISSUE TITLE
Cannot install module augmenting a uses statement with when condition

### ISSUE THREAD

**Issue by pfeige** [CESNET/libyang#1779]
Hi,

I'm trying to install the following three small YANG modules (using the stack with libyang v2):
~~~ 
module when-cnt {
  namespace "urn:when:cnt";
  prefix wc;

  container my-container {
    leaf my-type {
      type string;
    }
  }
}
 
module when-grp {
  namespace "urn:when:grp";
  prefix wg;

  grouping my-group {
    leaf my-leaf {
      type string;
    }
  }
}
 
module when {
  namespace "urn:when";
  prefix wh;          
  
  import when-cnt {
    prefix wc;
  }
  import when-grp {
    prefix wg;
  }

  augment "/wc:my-container" {
    uses wg:my-group {
      when "./wc:my-type = '42'";
    }
  }
}
~~~
The first two modules can be installed without any problems. But the third one is rejected with the libyang errors:
~~~
[ERR] Unknown/non-implemented module "wc"
[ERR] Invalid when condition "./wc:my-type = '42'"
~~~
From my point of view the when statement looks correct referencing my-type in the augmented my-container. Can you have a look at it?

BR,
Peter

**Comment by michalvasko** [comment]
Yes, there was a bug that should now be fixed, with this test included.

**Comment by pfeige** [comment]
It works! Thanks a lot!
