### ISSUE TITLE
Unable to obtain the xml attributes from the response

### ISSUE THREAD

**Issue by azeem0396** [CESNET/libyang#1782]
Hi 
I have implemented a netconf client using libnetconf2 and libyang1. Now i am trying to upgrade to latest libnetconf2 and libyang v2. But i am facing an issue in reading the xml attributes from netconf reply. 

```
<?xml version="1.0" encoding="UTF-8"?>
<notification xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0">
	<eventTime>2022-02-02T08:20:12Z</eventTime>
	<db-change xmlns="http://xyz.com/ne">
		<name>ABC</name>
		<notification-id>2203</notification-id>
		<changed-by>
			<user-name>abc</user-name>
			<session-id>1</session-id>
			<message-id>1</message-id>
		</changed-by>
		<change>
			<ne>
				<user operation="delete">
					<user-name>test</user-name>
				</user>
			</ne>
		</change>
	</db-change>
</notification> 
```

I would like to read the operation="delete" attribute of the **_user_** node. However i see the meta pointer of lyd_node (or lyd_node_inner )is always NULL. I was wondering if i am casting the lyd_node to the correct data structure to read the xml attributes or is there something else to use for this ? The same used to be present in the ly_xml attr pointer in libyang v1.

using libyang version - 2.13.7

Thank you.

**Comment by michalvasko** [comment]
The attribute is invalid so it is skipped. You can never have an XML without a namespace in YANG (except for `type` and `select` in filters because those were defined before YANG metadata were specified).

**Comment by azeem0396** [comment]
Hey. So would it be possible to get the raw data somewhere ? Without it being parsed ? Just the string.

**Comment by michalvasko** [comment]
No, *libnetconf2* does not provide this option so I do not think you can get this particular piece of information with *libnetconf2*/*libyang*.
