### ISSUE TITLE
Query: Is there any libyang API to duplicate the yang context?

### ISSUE THREAD

**Issue by starx1000** [CESNET/libyang#1784]
Hi,
  The scenario is like this, I want to get the libyang context from libnetconf2 client sessions, 

   and reuse it for other libnetconf2 client sessions to 
   Subscribe for the 2nd stream's notifications.

They connect to the same netopeer2-server,  and then the context should be the same and can be reused. 
I want to duplicate the lycontext after call

    struct ly_ctx  *lycontext =  nc_session_get_ctx(session1);
   // auto *bak_context = ly_ctx_dup(lycontext );
    struct nc_session* session2 = nc_connect_tls( ... , bak_context);
 
    then to keep the session2 have no relationship to session1.

Or:
   Will the ly_ctx still usable although the session1 is disconnected?( before call nc_session_free )

WHY do this: --
because that one client session can only subscribe one stream. so multiple client sessions need to be created. 

```
struct nc_rpc* nc_rpc_subscribe 	( 	const char *  	stream_name,
		const char *  	filter,
		const char *  	start_time,
		const char *  	stop_time,
		NC_PARAMTYPE  	paramtype 
	) 		

Create NETCONF RPC <create-subscription>

For details, see nc_rpc.

Parameters
    [in]	stream_name	Optional name of a NETCONF stream to subscribe to.
    [in]	filter	Optional filter data, an XML subtree or XPath expression (with JSON prefixes).
    [in]	start_time	Optional YANG datetime identifying the start of the subscription.
    [in]	stop_time	Optional YANG datetime identifying the end of the subscription.
    [in]	paramtype	How to further manage data parameters.

Returns
    Created RPC object to send via a NETCONF session or NULL in case of (memory allocation) error. 
```

Use of the xpath subscribe seems not feasible as it will also processing ietf-netconf ( edit-config events) and reduce the performance of edit-config actions pretty much.   

Or do you have other solutions for this?
   - subscribe multiple different streams from the same process.

**Comment by michalvasko** [comment]
Why not create the context yourself (it can be just default, all the required modules will be added when connecting) and use it for all `sr_connect_*()` calls?

> Or do you have other solutions for this?
    subscribe multiple different streams from the same process.

Actually, I do. Use the newer [notifications](https://github.com/CESNET/libnetconf2/blob/master/src/messages_client.h#L422) specification.

**Comment by starx1000** [comment]
Great! thanks! 
I will have a try.
