### ISSUE TITLE
Problem when installing schema modules

### ISSUE THREAD

**Issue by pfeige** [CESNET/libyang#1795]
Hi,

I found a strange problem when installing a couple of schema modules of our huge and complex object model. To be able to report this I tried to cut down the model and omitted all unnecessary parts. The result of that work can be found at the end of this message. Unfortunately, I was not able to make it even more simple, sorry.

There are two top level modules which are importing or including several others. When I install them in this order:
~~~
sysrepoctl -v 4 -s /local/yang -i /local/yang/issue-install-que.yang
sysrepoctl -v 4 -s /local/yang -i /local/yang/issue-install-cfm-ala.yang
~~~
all is fine and no error is reported. But when I install them in the reverse order the installation of  issue-install-que produces the following error output:
~~~
[ERR] Not found node "alarm-severity-profiles" in path.
[ERR] Internal error (/repo/libyang/src/tree_schema.c:1155).
sysrepoctl error: Failed to install module "/local/yang/issue-install-que.yang" (libyang error)
~~~   
When I was simplifying the model I found out that if the unnecessary import of ietf-interfaces in issue-install-cfm-mep 
is omitted the error disappears. However, in the original schema that import was necessary to acces a type.
Can you have a look at this?

BR,
Peter

Here are the mentioned schema modules:
~~~   
module issue-install-que {
  namespace "urn:issue:install:que";
  prefix iiq;
  
  import ietf-interfaces {
    prefix if;
  }
  
  augment "/if:interfaces/if:interface" {
    container queues {
    }
  }
}   

module issue-install-cfm-ala {
  namespace "urn:issue:install:cfm:ala";
  prefix iica;

  import issue-install-ala {
    prefix iia;
  }
  import issue-install-cfm {
    prefix iic;
  }

  augment "/iic:cfm" {
    leaf alarm-severity-profile {
      if-feature iia:alarm-severity-profiles;
      type iia:alarm-severity-profile-ref ;
    }        
  }
}

module issue-install-ala {
  namespace "urn:issue:install:ala";
  prefix iia;

  feature alarm-severity-profiles;
  
  typedef alarm-severity-profile-ref {
    type leafref {
      path 
        "/iia:alarming/iia:alarm-severity-profiles" +
        "/iia:alarm-severity-profile/iia:name";
    }
  }

  container alarming {
    container alarm-severity-profiles {
      if-feature alarm-severity-profiles;
      list alarm-severity-profile {
        key name;
        leaf name {
          type string;
        }
      }
    }    
  }
}

module issue-install-cfm {
  namespace "urn:issue:install:cfm";
  prefix iic;
  
  include issue-install-cfm-bas;
  include issue-install-cfm-ma;
  include issue-install-cfm-mep;
}

submodule issue-install-cfm-bas {
  belongs-to issue-install-cfm {
    prefix iic;
  }

  typedef admin-name {
    type string;
  }
  
  identity name-format;

  container cfm {
  }
}

submodule issue-install-cfm-ma {
  belongs-to issue-install-cfm {
    prefix iic;
  }

  grouping maintenance-association-name {
    leaf ma-name-format {
      type identityref {
        base name-format;
      }
    }
    choice ma-name {
      case ma-name-char-string {
        leaf ma-name-char-string {
          when "../ma-name-format="
             + "'adtn-oam-ecfm:name-format-char-string'" {
          }
          type string;
        }
      }
    }
  }
  
  grouping ma-parameters {
    leaf admin-name {
      type admin-name;
    }
    uses maintenance-association-name;
    leaf-list ma-mep-id {
      type mep-id;
    }
  }

  augment "/iic:cfm" {
    container associations {
      list association {
        key admin-name;
        uses ma-parameters;  
      }
    }
  }
}

submodule issue-install-cfm-mep {
  belongs-to issue-install-cfm {
    prefix iic;
  }

  /* import was necessary in the original schema
     without it the error disappears */
  import ietf-interfaces {
    prefix if;
  }

  typedef mp-direction {
    type enumeration {
      enum down;
      enum up;
    }
  }
  
  typedef mep-id {
    type uint16 {
      range "1..8191";
    }
  }

  grouping mep-config-parameters {
    leaf mep-id {
      type mep-id;
    }
    leaf direction {
      type mp-direction;
      mandatory true;
    }
  }
  
  augment "/iic:cfm/iic:associations/iic:association" {
    container meps {
      list mep {
        key mep-id;
        uses mep-config-parameters;          
      }    
    }
  }
}
~~~

**Comment by michalvasko** [comment]
Was not able to reproduce with [these](https://github.com/CESNET/libyang/files/8108255/yang.tar.gz) modules, please attach similarly all the used modules. Note that I was testing it on the current `devel` *libyang*/*sysrepo*.

**Comment by pfeige** [comment]
Please have a look at [this github repo](https://github.com/ADTRAN/netopeer2-integration-tests/tree/issues). It is a complete test environment based on docker. To build the docker image use 'make test-env'. To run the install testcase use
make test PYTEST_ARGS='-k test_issue_install'
The docker uses the latest stack sources by cloning them.

**Comment by michalvasko** [comment]
I will but I would strongly prefer being able to reproduce it locally, which seems you managed to.

**Comment by pfeige** [comment]
I tried it with the files from your tarball and the error is shown. I'm not sure whether I'm allowed to share the original modules because of confidentiality.

**Comment by michalvasko** [comment]
Are you starting with a clear SHM, no YANG modules installed? I would prefer the smaller test-case but it is importing `ietf-interfaces`, which may be implemented already or something, I really need the exact steps from 0 to reproduce it.

**Comment by pfeige** [comment]
As you can see in the above mentioned git repo there is a script yang/install.py which installs modules an enables features according to the file yang/manifest.json. This is executed before the tests.

**Comment by michalvasko** [comment]
Firstly, the files you provided did reproduce the problem but they had to be loaded in the opposite order than the code you posted (I know you wrote that but please, next time paste the problematic code, not the working one).

So, with latest *libyang* it should work, just another complex schema dependency not accounted for.
