### ISSUE TITLE
about create Non-Presence container with no default node

### ISSUE THREAD

**Issue by ostack** [CESNET/libyang#180]
in lyd_wd_add_subtree we found the following description
lyd_wd_add_subtree :
**/* always create empty NP container even if there is no default node,
* because according to RFC, the empty NP container is always part of
* accessible tree (e.g. for evaluating when and must conditions) */**

according to  the description we know even if there is no default node,we also create it .but in the RFC of yang it says "**existing only to contain child nodes**",so i wonder if we create node with out default node is against  the RFC? I think if we create this container, the when and must will give a wrong check to the the user,as the  NP container should not exist ,but we create it and use it to check

**7.5.1. Containers with Presence**
**In the first style, the container has no meaning of its own, existing
only to contain child nodes. This is the default style.
For example, the set of scrambling options for Synchronous Optical
Network (SONET) interfaces may be placed inside a "scrambling"
container to enhance the organization of the configuration hierarchy,
and to keep these nodes together. The "scrambling" node itself has
no meaning, so removing the node when it becomes empty relieves the
user from performing this task.**

**Comment by rkrejci** [comment]
It is not against but according to the RFC. And the reason is actually the evaluating of `must` and `when` conditions - check the `XPath Context` section in RFC:
```
If a node that exists in the accessible tree has a non-presence
container as a child, then the non-presence container also exists in
the accessible tree.
```

**Comment by ostack** [comment]
The accessible tree is made up of all nodes in the data tree, and all leafs with default values in use

**Comment by rkrejci** [comment]
I'm not getting the point of your comment.

**Comment by ostack** [comment]
if the user delete all leaves without default value，is the non-presence container node also exist to the user?

i think we should contact to the net-config  org to  make the non-presence container existence defination clear .

what about your opinion?

**Comment by rkrejci** [comment]
You can try to ask the working group, but I think the RFC is quite clear about it. NP containers have no meanings, and the server is allowed to remove them (if they are empty) or keep them, it is up to the implementation. If you check the presence of an NP container or depend somehow on its presence (or non-presence), it is wrong, its presence or non-presence has no meanings.
