### ISSUE TITLE
nested lists in lyplg_type_validate_instanceid

### ISSUE THREAD

**Issue by berstrob** [CESNET/libyang#1800]
Hi,

so i was trying to create my own change notification for my custom-data-store-plugin-project , and it worked great most of the time, but it seemed to not work with nested lists: i got a `Invalid instance-identifier  value - required instance not found. (path: Schema location /ietf-netconf-notifications:netconf-config-change/edit/target, data location /ietf-netconf-notifications:netconf-config-change/edit[1]/target.` if i tried .The attempt to send the notify `(sr_event_notif_send_tree)` even called my operational data callbacks , for a pure config change (with the correct request_path or NULL if i "deleted/created" multiple) .  

So i tried to find the root cause (and check if it is maybe fixed already, not keen on updating everything mid transition with half the stuff not working already :) )  on my local libyang with the utest for `instanceid.c`  with the attached patch, which doses fail with another error message so maybe i did something wrong : 
```

tests/utest_instanceid 
[==========] Running 2 test(s).
[ RUN      ] test_data_xml
[  ERROR   ] --- 0x2 != 0x4
[   LINE   ] --- /home/bernd/projects/netconf/libyangnew/libyang/tests/utests/types/instanceid.c:117: error: Failure!
[  FAILED  ] test_data_xml
[ RUN      ] test_plugin_lyb
[       OK ] test_plugin_lyb
[==========] 2 test(s) run.
[  PASSED  ] 1 test(s).
[  FAILED  ] 1 test(s), listed below:
[  FAILED  ] test_data_xml
```
[instanceid_test.zip](https://github.com/CESNET/libyang/files/8152830/instanceid_test.zip)

i will try to look into it more., when is find time.
Regards Bernd

**Comment by michalvasko** [comment]
You do not have to find and fix the problem, just provide the data to reproduce it and I will take a look. Your test case just needed a tweak and it worked.
```
const enum ly_path_pred_type val7[] = {LY_PATH_PREDTYPE_LIST, LY_PATH_PREDTYPE_NONE, LY_PATH_PREDTYPE_LIST,
            LY_PATH_PREDTYPE_NONE};
```
This list describes the predicate type for each node in the instance-identifier.

**Comment by berstrob** [comment]
thanks for explaining, now i have at least the trivial test-cases working. So "only" need to rebuild my complex model (with idref from another model `-` in names ,  `-` and  `:` in identity strings ... and other might be problematic stuff) so i can give you a "broken" example so far every simplified version worked (maybe i'll switch using sysrepo and models). I'll report back if i have it.

**Comment by berstrob** [comment]
i finally manged to track it down and not sure if its a bug or maybe even expected behavior , it is caused by something complete different (sorry for that, probably should have been under sysrepo):  `sr_oper_get_items_subscribe`  after doing that for the "list body" my notify will only call that and ignore the config data, the config changes will however create the same notifcation without a hitch (and without a call to the sub). i attached a small program to show (as i said not newest sysrepo but i can try to test it there too) . 

If i change the path to only the state it works (also in the test program), so i should be fine (not sure why it not was like that already), so the defect can be closed here, maybe add one to sysrepo if the ignoring of the config in that case is not intended.

Regards Bernd
[subtest.zip](https://github.com/CESNET/libyang/files/8168997/subtest.zip)
