### ISSUE TITLE
Unable to parse anyxml with no namespace

### ISSUE THREAD

**Issue by panmanio** [CESNET/libyang#1807]
Libyang rejects anyxml nodes that have no namespace defined. Such a situation is possible when no parent node defines a default namespace. For example:

```xml
<nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
    <nc:get>
        <nc:filter nc:type="subtree">
            <unconstrained/>
        </nc:filter>
    </nc:get>
</nc:rpc>
```

Yanglint output:

```console
> data -t rpc get.xml
libyang[0]: Unknown XML prefix "". (path: Schema location /ietf-netconf:get, data location /ietf-netconf:get, line number 4.)
YANGLINT[E]: Failed to parse input data file "get.xml".
```

It used to work with libyang1. As far as I know, it is the only way to request Netconf server to match any namespace.

**Comment by michalvasko** [comment]
Yes, parsing XML elements or using subtree filters without a namespace is not supported because it is inefficient and I was hoping unnecessary. If you really cannot do without it I may try to look at this whether it could be supported once I have some spare time. But it is possible it would require so much work it would not be worth it for this single use-case.

**Comment by panmanio** [comment]
@michalvasko I could live without this use case. It was a nice feature though and YANG RFC explicitly says there should be no restrictions imposed for the any-XML, but I see your point.

However, when storing the data in JSON, libyang also forces direct children of the `anyxml` nodes to be namespace-qualified. This one is a bigger issue for me as I need to switch from XML to JSON and from JSON to XML, as mentioned in #1827. Not sure if it is the same issue or should it be tracked separately? [RFC 7951 requirements for object member names](https://datatracker.ietf.org/doc/html/rfc7951#section-4) state the namespace-qualified for non-top-level nodes should only be used when the namespaces is changed. In other cases the simple form should be used.

**Comment by michalvasko** [comment]
Okay, module names should now be properly inherited.
