### ISSUE TITLE
libyang/src/parser_lyb.c:670: lyb_read_hashes: Assertion `hash[j - 1] & (LYB_HASH_COLLISION_ID >> (j - 1))' failed.

### ISSUE THREAD

**Issue by berstrob** [CESNET/libyang#1810]
Hi,

this is a strange one:

i have a openconfig-platform model, filled with like 900 components (most with 6 properties each, flat tree (but i do not see that this matters),  generic named "ABC-1-1:COMP", "ABC-1-2:COMP", mostly identical data) , if i do :  
```
~ #time /tmp/sysrepocfg -X -x "/openconfig-platform:components/component"  -d operational > /tmp/full.txt

real	0m9.605s
user	0m4.697s
sys	0m0.081s
~ # wc -l /tmp/full.txt 
79541 /tmp/full.txt
```
it works, but  if i do the same with the netopeer-server via rpc like:
```
<rpc message-id="81945" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <get-data xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-nmda"
               xmlns:ds="urn:ietf:params:xml:ns:yang:ietf-datastores">
       <datastore>ds:operational</datastore>
    <subtree-filter>
      <components xmlns="http://openconfig.net/yang/platform">
        <component>      
        </component>
      </components>
    </subtree-filter>
  </get-data>
</rpc>

```
 i get the
 ```
 libyang/src/parser_lyb.c:670: lyb_read_hashes: Assertion `hash[j - 1] & (LYB_HASH_COLLISION_ID >> (j - 1)) failed
 ```
   ( a `get request` has the same effect) .

If i do the same with only running it works with the server too (less data) : 

```
~ #time /tmp/sysrepocfg -X -x "/openconfig-platform:components/component"  -d running > /tmp/conf_full.txt

real	0m3.968s
user	0m3.362s
sys	0m0.118s
 ~ # wc -l /tmp/conf_full.txt 
48285 /tmp/conf_full.txt

```

And so i test : if i eliminate like 400 components (of those generic components),  i can do  all requests with the server, the operational have a similar amount of data the as the only config form the full test like 47k lines in the response . And it looks like it crashes after getting the data while preparing the rpc:

```
[INF]: SR: Published event "operational" "/openconfig-platform:components/component/state" with ID 9.
[INF]: SR: Event "operational" with ID 9 succeeded.
[INF]: SR: Published event "operational" "/openconfig-platform:components/component/properties/property/state" with ID 9.
[INF]: SR: Event "operational" with ID 9 succeeded.
[INF]: SR: Published event "operational" "/openconfig-platform:components/component/subcomponents/subcomponent/state" with ID 9.
[INF]: SR: Event "operational" with ID 9 succeeded.
[INF]: SR: Successful processing of "rpc" event with ID 2 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 2 priority 0 succeeded.
netopeer2-server: /home/bernd/projects/netconf/libyangnew/libyang/src/parser_lyb.c:670: lyb_read_hashes: Assertion `hash[j - 1] & (LYB_HASH_COLLISION_ID >> (j - 1))' failed.
Aborted (core dumped)
```

Best Regards

Bernd

**Comment by berstrob** [comment]
/tmp/netopeer2-server -V
netopeer2-server 2.0.21

 /tmp/sysrepoctl -V
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v2.0.47 (SO v6.4.13)

i cant try to make a new test program with a newer version if you think its fixed already, but i briefly looked  trough parser_lyb.c commits an did no see any related once.

**Comment by michalvasko** [comment]
No, there are no changes, I believe. Well, if you could provide the data/models for reproducing it I may be able to fix it although these problems are the worst.

**Comment by berstrob** [comment]
A short update;
`sysrepocfg -f lyb -X -x "/openconfig-platform:components/component"  -d operational`
does work as well (calling the same funtion, with i hope nearly the same data (- the stuff the server adds), so i am even more confused) . i am still unable to trigger it with a simple program , just using  most the data , not all of it because there are some unique parts, not so easy to duplicate , just the parts triggering the crash. it has nothing to do with the size (i tired like 4000 components all same pattern). 

Interestingly removing like 400 components before them, still crashes but on a different node while parsing. 

The one thing i noticed after adding some debug code, : 

```
  for (i = 0; !(hash[0] & (LYB_HASH_COLLISION_ID >> i)); ++i) {
        if (i > LYB_HASH_BITS) {
            LOGINT_RET(lybctx->ctx);
        }
        if (i>1) printf("++++++++++++++hash i %d ,%d %d %d\n ",
                i,hash[0],(LYB_HASH_COLLISION_ID >> i  ), (*hash_count));
    }

    /* move the first hash on its accurate position */
    hash[i] = hash[0];

    /* read the rest of hashes */
    for (j = i; j; --j) {
        lyb_read(&hash[j - 1], sizeof *hash, lybctx);
        if (i>1)printf("--------------------hash i %d j %d,%d %d, %d \n ",
                i,j,hash[i],hash[j - 1],LYB_HASH_COLLISION_ID >> (j - 1) );
        /* correct collision ID */
        assert(hash[j - 1] & (LYB_HASH_COLLISION_ID >> (j - 1)));
        /* preceded with zeros */
        assert(!(hash[j - 1] & (LYB_HASH_MASK << (LYB_HASH_BITS - (j - 1)))));
    }
```

it seems to me  the crash is the only time i>1 is true  (in all functioning case that print does not trigger) , here is the last part from the crash without the` if ` just print all, and some more debug info from the calling function (to find the place in the model)  : 

```
lyb_parse_schema_hash parent: component
sibling: cpu 1
lyb_parse_schema_hash parent: cpu
sibling: config 1
lyb_parse_schema_hash parent: cpu
sibling: state 1
lyb_parse_schema_hash parent: component
++++++++++++++hash i 0 ,66 128 0
--------------------hash i 1 j 1,66 141, 128
sibling: integrated-circuit 1
lyb_parse_schema_hash parent: integrated-circuit
sibling: config 1
lyb_parse_schema_hash parent: integrated-circuit
sibling: state 1
lyb_parse_schema_hash parent: state
++++++++++++++hash i 0 ,6 128 0
++++++++++++++hash i 1 ,6 64 0
++++++++++++++hash i 2 ,6 32 0
++++++++++++++hash i 3 ,6 16 0
++++++++++++++hash i 4 ,6 8 0
--------------------hash i 5 j 5,6 0, 8
netopeer2-server: /home/bernd/projects/netconf/libyangnew/libyang/src/parser_lyb.c:675: lyb_read_hashes: Assertion `hash[j - 1] & (LYB_HASH_COLLISION_ID >> (j - 1))' failed.
Aborted (core dumped)
```


the component it crashes is not always the same if i remove  some parts it changes. Components  i had it with are:
```
MCH-E1-B-47:PORT
MCH-1-62:PORT 
MCH-E1-A-46:PORT 
```
but all of those work fine alone and even together, if i do not add the 400 with names` MCH-E2-A-1:PORT - MCH-E2-H-48:PORT` , which are later in the config as the E1, but before the `MCH-1-62:PORT `.


i attached the output from both xml as well as lyb.
the models added (i could pack them, but they are straight from openconfig) :
 ```
openconfig-alarm-types        | 2018-11-21 | i     |           |             |            |                                                                        
openconfig-extensions         | 2018-10-17 | i     |           |             |            |                                                                        
openconfig-platform           | 2019-04-16 | I     | root:root | 600         |            |                                                                        
openconfig-platform-types     | 2019-06-03 | i     |           |             |            |                                                                        
openconfig-types              | 2019-04-16 | i     |           |             |            |                                                                        
openconfig-yang-types         | 2018-11-21 | i     |           |             |            |                      
```                                                  

[data.zip](https://github.com/CESNET/libyang/files/8302383/data.zip)

**Comment by michalvasko** [comment]
Loading the attached LYB reproduces the crash but loading the XML, printing it to LYB, and then parsing it does not. I am not sure what to make of that but I am using the latest `devel` *libyang* so maybe there were some fixes, I am not sure.

**Comment by berstrob** [comment]
That is at least halve good news, i should be able to upgrade all to the newest version,with some work and breaking some stuff i am sure, but  with some luck it works then , and the problem can be ignored/is fixed already. I will try that and report back.

**Comment by berstrob** [comment]
Even better news: after renaming a few functions to there new names , removing  SR_SUBSCR_CTX_REUSE , adapting all the install scripts, it seems to work now and not crash, at least with this set of data, i will keep a eye on it since we can't be sure there was a fix, maybe its just a stupid pointer somewhere and the new code/compiling it just moved the problem else where.

On a only slightly related note :
if i install with:
`/tmp/sysrepoctl -i /tmp/openconfig-platform\@2019-04-16.yang -m "running:DS TEST"  -s /tmp/ -v3`

getting running calls the right ds plugin and works but:

```
/tmp/sysrepocfg -X -x "/openconfig-platform:components/component" -d operational
[ERR] LYB DS file: Opening "/dev/shm/sr_openconfig-platform.running" failed (No such file or directory).
[ERR] Callback "load" of plugin "LYB DS file" for module "openconfig-platform" failed.
```

Doing this:
`/tmp/sysrepoctl -i /tmp/openconfig-platform\@2019-04-16.yang -m "running:DS TEST" -m "operational:DS TEST" -s /tmp/ -v3
`
(and not having any operational data stored, just the plugin saying there is none ) . Does work fine.

**Comment by michalvasko** [comment]
Okay, and as for the DS plugin error, should be fixed in the latest *sysrepo* `devel`.
