### ISSUE TITLE
How to access type information from lyd_node

### ISSUE THREAD

**Issue by pfeige** [CESNET/libyang#1811]
Hi,

this is no issue, I'm asking for advice. We have a small feature implemented which prevents cleartext passwords from being sent back in get replies without encryption. The corresponding function is called (via patch) in np2srv_rpc_get_cb() immediately before this line 
https://github.com/CESNET/netopeer2/blob/05d9ac47195345dcef35443980aa2a4390257f19/src/netconf.c#L304.
Here is the code which works with libyang1:
~~~
void
replace_all_cleartext_passwords(struct lyd_node *root)
{
    static pthread_mutex_t _lock = PTHREAD_MUTEX_INITIALIZER;
    struct lyd_node *iter_node;

    LYD_TREE_DFS_BEGIN(root, iter_node) {
        if (iter_node->schema && (LYD_NODE_TERM & iter_node->schema->nodetype)
            && (0 == strcmp("crypt-hash", ((lysc_node_leaf *)iter_node->schema)->type.der->name))
            && (0 == strcmp("iana-crypt-hash", ((lysc_node_leaf *)iter_node->schema)->type.der->module->name))
            && (0 == strncmp("$0$", lyd_get_value(iter_node), 3))) {
                pthread_mutex_lock(&_lock);
                lyd_change_term((struct lyd_node_term*)iter_node,
                                get_sha512_hashed_pw(&((struct lyd_node_term*)iter_node)->value_str[3]));
                pthread_mutex_unlock(&_lock);
        }
        LYD_TREE_DFS_END(root, iter_node)
    }
}
~~~
Do you see any chance to get this adapted to libyang2? The lyd_node contains a pointer to lysc_schema but in order to obtain the type's name and the type's module name I would need a lysp_schema. Would it be possible to get access to these information from lyd_node in any way?

BR,
Peter

**Comment by jktjkt** [comment]
What's the use case for storing cleartext passwords instead of their hashes?

**Comment by pfeige** [comment]
We cannot prevent customers of our product to use cleartext passwords.

**Comment by pfeige** [comment]
I see, but how can I access the data? Is there a type to be casted or an access function?
