### ISSUE TITLE
Latest release failing to load the ietf-isis module

### ISSUE THREAD

**Issue by rwestphal** [CESNET/libyang#1813]
Hi,

While updating yang2-rs to use the latest libyang release (v2.0.164), the unit tests found the following regression:
```
thread 'data_diff_reverse' panicked at 'Failed to load module: Error { errcode: 7, msg: Some("Missing key in list representing configuration data."), path: Some("/ietf-isis:{grouping='unknown-tlvs'}/unknown-tlvs/unknown-tlv"), apptag: Non
e }', tests/data.rs:181:14
```

In short, the error says that a rw list is missing the key statement. But it turns out that the referenced list represents a read-only (state) list, so the error is incorrect.

I've bisected the regression down to this commit: ecdc2222aea827975871e45b153ab9aaf3f8590d. The problem was found while trying to load the [ietf-isis](https://github.com/YangModels/yang/blob/master/experimental/ietf-extracted-YANG-modules/ietf-isis%402019-10-15.yang) YANG module.

**Comment by michalvasko** [comment]
Would not call it a regression, it worked only by chance. But now should be fixed.

**Comment by rwestphal** [comment]
@michalvasko You never fail to surprise me with your quick fixes :) Thank you!
