### ISSUE TITLE
Dynamic generate UI from yang file

### ISSUE THREAD

**Issue by berkaykirtillii** [CESNET/libyang#1817]
How can I use yang file to generate UI components with all yang model stuff (conditions,types,etc.) I convert to json from yang with opendayligth tools but I want to learn something. If yang model have import statements, converted json file hasn't include any content from imported file. It only gives reference. How can I use these references to generate uı? Or how can I include imported yang model content to  converted json model.

**Comment by michalvasko** [comment]
I failed to see the relevance to our projects. You have mentioned only OpenDaylight and some JSON generated from them. I suppose you can ask them for help.

**Comment by berkaykirtillii** [comment]
Actually I use your project and additionally use opendayligth tools. This issue is not about opendaylight. I am trying to make that I have talked with your application. When I try to install yang files via sysrepoctl -v3 -i it gaves me an error that


```
root@cf005ee489cc:/etc/sysrepo/yang# sysrepoctl -v3 -i basic-yangfile.yang
[INF]: Scheduled changes not applied because of other existing connections.
[INF]: Connection 9 created.
[ERR]: No resolvents found for leafref "../basic-types:basic-types/leaftry/st-name". (path: /basic-yangfile:basic-inp/name)
[ERR]: Module "basic-yangfile" parsing failed.
sysrepoctl error: Failed to install module "basic-yangfile.yang" (libyang error)
```



I could not installed yang file which is includes import another model.

You can see that basic-types model is installed successfully.

My models are



basic-yangfile.yang



```

module basic-yangfile {

yang-version 1;
namespace "basic-yangfile";
prefix "by";

import basic-types {
prefix "by-types";
revision-date 2022-02-02;
}

description
"This is basic yang example";

revision "2022-01-01" {
description "initial revision";
}

container basic-inp {
leaf percentage {
type by-types:percent;
}

leaf name {
type leafref {
path "/by-types:leaftry/st-name";
}
}
}
}


```

basic-types.yang

```


module basic-types {

yang-version 1;
namespace "basic-types";
prefix "by-types";

description
"This is basic types yang example";

revision "2022-02-02" {
description "initial revision";
}

typedef percent {
type uint16 {
range "0 .. 100";
}
description "Percentage";
}

container leaftry {
leaf st-name {
type string;
description
"leafref example";
}
}
}
```

```

root@cf005ee489cc:/etc/sysrepo/yang# sysrepoctl -l
Sysrepo repository: /etc/sysrepo
Module Name | Revision | Flags | Owner | Permissions | Submodules | Features
----------------------------------------------------------------------------------------------------------------------------------------------------------------
basic-types | 2022-02-02 | I | root:root | 600 | |
```

**Comment by ahmetoguz1** [comment]
Hello @michalvasko, my friend was asked this question but I want to explain actually what is the problem.

Firstly, I have two basic yang files.

First yang files includes a container and it includes a leaf. I installed basic-types module successfully.

```
module basic-types {
    
	yang-version 1;
	namespace "basic-types";
    prefix "by-types";
	
	description
	"This is basic types yang example";
	
	revision "2022-02-02" {
	  description "initial revision";
	}
	
	typedef percent {
     type uint16 {
     range "0 .. 100";
     }
    description "Percentage";
    }
	
	container leaftry {
	 leaf st-name {
        type string;
        description
          "leafref example";
     }
	}
}
```


Second yang files is importing basic-types module and I am trying to get leaf from it.

```
module basic-yangfile {
    
	yang-version 1;
	namespace "basic-yangfile";
    prefix "by";
	
	import basic-types {
	  prefix "by-types";
	  revision-date 2022-02-02;
	}
	
	description
	"This is basic yang example";
	
	revision "2022-01-01" {
	  description "initial revision";
	}
	
	container basic-inp {
	    leaf percentage {
		  type by-types:percent;
		}
		
		leaf name {
         type leafref {
          path "/by-types:leaftry/st-name";
         }
        }
}
}
```

It gaves me an error that

```
root@cf005ee489cc:/etc/sysrepo/yang# sysrepoctl -v3 -i pg.yang
[INF]: Scheduled changes not applied because of other existing connections.
[INF]: Connection 15 created.
[ERR]: No resolvents found for leafref "/basic-types:leaftry/st-name". (path: /basic-yangfile:basic-inp/name)
[ERR]: Module "basic-yangfile" parsing failed.
sysrepoctl error: Failed to install module "pg.yang" (libyang error)
```

I tried different path syntax according to https://ydkgen.readthedocs.io/en/latest/guides/howto_path.html but non of them was not successful. I could not figure out where is the problem. Could you give me a way to fix it?

Best Regards

Oguz

**Comment by michalvasko** [comment]
You are writing the argument for `path` statement of YANG `leafref` type, [this](https://datatracker.ietf.org/doc/html/rfc7950#section-9.9.2) is the specification for that. In short, you need to use explicit prefixes for foreign nodes
```yang
path "/by-types:leaftry/by-types:st-name";
```

**Comment by ahmetoguz1** [comment]
It solved. 

Thank you for your answer.
