### ISSUE TITLE
Missing lys_data_path_pattern

### ISSUE THREAD

**Issue by jeanseb6wind** [CESNET/libyang#1818]
Hello,
In the transition manual it is written:
```
lys_data_path_pattern() | - | Removed as useless
```

But we were using it and it was not useless for us.
Is it possible to put it again ?
Thanks

**Comment by michalvasko** [comment]
What exactly do you need it for, are you sure there is not a better way without using it? Seems a very specific function probably for some obsolete use-case and I would strongly prefer not supporting it.

**Comment by rjarry** [comment]
Hi Michal,

this is used by the python bindings to convert libyang trees to/from python objects. I understand this is quite specific but I did not find a better way to do fast conversions without resorting to custom C code (which I want to avoid in the python bindings).

Would that be OK to add a similar function for libyang 2?

**Comment by michalvasko** [comment]
Okay, I suppose I can add new schema node path format where it will work just like the description of this function, instead of specific key values there will be `%s`. Will that be fine?

**Comment by jeanseb6wind** [comment]
That would be fine !

**Comment by rjarry** [comment]
Hi Michal, yes that would work. Important detail: the bindings need a *data* path with key values replaced by `%s`, not a *schema* path.

**Comment by michalvasko** [comment]
Okay, try the latest *libyang*.

**Comment by rjarry** [comment]
Thanks Michal :+1:

**Comment by jeanseb6wind** [comment]
It works great !
