### ISSUE TITLE
Problem with grouping in RPC

### ISSUE THREAD

**Issue by lukasmacko** [CESNET/libyang#182]
There is an issue reported about yang model loading. https://github.com/sysrepo/sysrepo/issues/487
Could you take a look?

Thanks,
Lukas

**Comment by rkrejci** [comment]
Probably connected with #132, I'm going to look at it.

**Comment by rkrejci** [comment]
I have forgot to mention this issue in the bugfix commit, instead the original issue 487 was referred. Please verify that it works with the current libyang devel branch now and then close the issues.

**Comment by lukasmacko** [comment]
It works.
Thanks!
