### ISSUE TITLE
incorrect exit status code on error

### ISSUE THREAD

**Issue by kwatsen** [CESNET/libyang#1824]
Using today's build of the "devel" branch.  (yanglint 2.0.170)

Running a `yanglint` command produces an error:
```
# yanglint` -m  ../ietf-crypto-types@2022-03-25.yang ../ietf-truststore@2022-03-25.yang ../ietf-keystore@2022-03-25.yang ../ietf-ssh-common@2022-03-25.yang ./ietf-origin.yang ietf-ssh-client@2022-03-25.yang ex-ssh-client-keystore.xml ../../trust-anchors/refs/ex-truststore.xml ../../keystore/refs/ex-keystore.xml
libyang err : Invalid identityref "
          ct:ssh-public-key-format
        " value - unable to map prefix to YANG schema. (Schema location /ietf-truststore:truststore/public-key-bags/public-key-bag/public-key/public-key-format, data location /ietf-truststore:public-key[name='corp-fw1'], line number 103.)
YANGLINT[E]: Failed to parse input data file "../../trust-anchors/refs/ex-truststore.xml".
```

But the exit status code doesn't indicate an error occurred:
```
# echo $?
0
```

FWIW, the "error" is the presence of line-returns, which USED TO WORK with `yangling 1.x`:
```
OLD:
      <public-key-format>
          ct:ssh-public-key-format
      </public-key-format>

NEW:
      <public-key-format>ct:ssh-public-key-format</public-key-format>
```

I hope we can go back to allowing whitespace around `identity`-based values...

**Comment by michalvasko** [comment]
Okay, an error should now be returned on invalid data file. However, as for the `identityref`, I am not sure what to do about it. I understand the whitespaces are just formatting but the values need to be compliant with their specification and with the XML format. I suppose I could allow the whitespaces for `identityref` values but what about all the other types? Should leading and trailing whitespaces be ignored for all the values except for `string`? What about `empty`? In any case, is it really correct to ignore them for one type and not for others?

**Comment by kwatsen** [comment]
The essence of this bug (exit-status codes) is resolved - thanks!

Regarding whitespace, this may be something to raise on the NETMOD list, but my thoughts are:

- from a purity-perspective, validation may need to fail
- from a Postel-theorem perspective, it may be okay to say "whitespace before and/or after is okay if it is known that the value-space of the value cannot contain whitespace."

Thoughts?  Track using another issue, or maybe you want to make an "executive decision"  ;)

**Comment by michalvasko** [comment]
I do not mind asking on the mailing list as I do not want to make an "executive decision" :) However, I do generally try to prefer being strict because when problems arise, I can always justify the behavior. When it is the other way around, you have nothing relevant to back it up with. But like I said, consensus on the mailing list is fine and probably even better. Will you please start the discussion or should I?
