### ISSUE TITLE
Converting anyxml from XML to JSON leads to data loss

### ISSUE THREAD

**Issue by panmanio** [CESNET/libyang#1827]
Let's define a simple module:

```yang
module mod {
  namespace "x:example:mod";
  prefix "m";

  container root {
    anyxml any;
  }
}
```

And the data:

```xml
<root xmlns="x:example:mod">
    <any>
        <name>value</name>
        <container>
            <number>137</number>
        </container>
    </any>
</root>
```

Trying to convert it to json (`yanglint -f json mod.yang data.xml`) results with:

```json
{
  "mod:root": {
    "any": {
      "mod:name": [
                {}
      ],
      "mod:container": [
                {
          "number": [
                        {}
          ]
        }
      ]
      }
  }
}
```

The actual values are missing and we cannot apply backward conversion from JSON to XML.

I'd expect something like this:

```json
{
  "mod:root": {
    "any": {
      "mod:name": "value",
      "mod:container": {
        "number": 137
      }
    }
  }
}
```

Here, JSON -> XML conversion (`lint -f xml mod.yang data.json`) works and produces the same result as the XML input above.

Other thing is that libyang forces the child nodes of `any` node to be namespace-qualified as in `anydata` nodes, but that seems to be the same as #1807.

**Comment by michalvasko** [comment]
Converting `anyxml`/`anydata` from XML to JSON is a dangerous and undefined operation because JSON has more format options (has types) than XML so it is impossible to determine what type to use. However, I have added some best-effort print for this case and you will now get the output you expect. Just know that you will not always get the expected output because it is impossible.

**Comment by panmanio** [comment]
@michalvasko I agree it needs to be done carefully. I think I have inadvertently stressed out type conversion with the example I've provided while that was not so important, only the presence of the nodes and their values were. It works better now, thank you. But it does not handle lists, producing an invalid json with repeated items, for example:

```xml
<root xmlns="x:example:mod">
    <any>
        <leaflist>abc</leaflist>
        <leaflist>def</leaflist>
        <list>
            <item1>a</item1>
        </list>
        <list>
            <item2>b</item2>
        </list>
    </any>
</root>
```

produces:

```json
{
  "mod:root": {
    "any": {
      "leaflist": "abc",
      "leaflist": "def",
      "list": {
        "item1": "a"
      },
      "list": {
        "item2": "b"
      }
    }
  }
}
```

Can we bring lists support too? Before 23b51a8 libyang tried to make a json list even when there was a single container in the XML and I think that was perfectly acceptable as there is no model information.

**Comment by michalvasko** [comment]
Now you may understand the problem and why I wrote that it is impossible to do perfectly. How is *libyang* supposed to know it is a list if it has no schema information? In XML, there is no format information so everything is just an element, only in JSON you can distinguish between some node types without schema.

I suppose it can be improved to check for duplicate elements but if there is only a single (leaf-)list instance, it will still be interpreted as a container/leaf so I am not sure there is a point.

**Comment by panmanio** [comment]
That is all true, we don't know the schema so we can only make a simple analysis of the input. Determining if the node is a list by seeing multiple occurrences in the XML is all that can be done. Whether an XML container is a JSON object or a list of objects does not matter as long as a valid JSON is produced (I only mentioned that because that could simplify the algorithm and because it is justifiable in my opinion).

I would say producing a valid JSON that carries all input data is a perfect solution in these conditions (no matter the real types).
