### ISSUE TITLE
lyd_node_should_print is no more usable

### ISSUE THREAD

**Issue by jeanseb6wind** [CESNET/libyang#1828]
Hello,
In the `libyang-python` wrapper, we were using the function `lyd_node_should_print` in order to filter nodes with good performance.
In libyang 2, a similar function seems to exists `ly_should_print` but is not accessible outside in our wrapper.

Is-it possible to make this function accessible or to add again the `lyd_node_should_print` ?

Thanks
Jean-Sébastien

**Comment by michalvasko** [comment]
Fine, added, although I do not know what you can be using that function for. Also, it would be nice if you could learn all the missing functions and request them in a single issue.

**Comment by jeanseb6wind** [comment]
Thanks @michalvasko, I work in an iterative way so I don't know exactly what function is missing. I launch tests and I fix bug one by one, so sometimes I can't see a problem until I don't have fixed previous problem.
