### ISSUE TITLE
performance issue with many leafrefs

### ISSUE THREAD

**Issue by berstrob** [CESNET/libyang#1831]
Hi,

so the openconfig-platform model , has multiple `leafref`  to `components/component/config/name` , i do have` 862` components ( i in `lyplg_type_resolve_leafref `) in it and one validate of that module-data wants to do `7631` (count in` lyd_validate_unres` where `strcmp(type->plugin->id,"libyang 2 - leafref, version 1")==0`  from `node_types->count==12678` the rest are mostly unions and don't take more then one sec  )checks of that (its still mostly the same data, i had for the hash error)  , which on my embedded device takes roughly 1 minute, and that is not really practicable.

 I can properly "hack my way " to skip those checks (in fact i already tested a simple skip any leafref hack, but would need/want to refine it more if i have to use it) , since in my use case i restrict changing those components heavily anyway so if anyone tries to circumvent it , it will get caught /fixed later anyway. but maybe there is a way to speed it up,  like store those identity-values for the duration of one validation in a binarytree/hashmap  so its at least not in O(n²) checks  at least, maybe only needed if there are more then a few of the same identities. 

Would love to hear your thoughts about that.

Regards,

Bernd

**Comment by michalvasko** [comment]
Please provide the use-case in a stand-alone example so that I can just run it and reproduce the inefficiencies. Then I can optimize it and verify it is faster.

There are lots of possibly slow parts in *libyang* but I am not able to guess which are worth optimizing and which not so if you have a slow use-case, I will try to optimize it.

**Comment by berstrob** [comment]
nothing really need:
install standard openconfig-platform:
```
openconfig-alarm-types     | 2018-11-21 | i     |             |               |            |         
openconfig-extensions      | 2018-10-17 | i     |             |               |            |         
openconfig-platform        | 2019-04-16 | I     | bernd:bernd | 600           |            |         
openconfig-platform-types  | 2019-06-03 | i     |             |               |            |         
openconfig-types           | 2019-04-16 | i     |             |               |            |         
openconfig-yang-types      | 2018-11-21 | i     |             |               |            |   
```
subscripe with the ` application_changes_example openconfig-platform`

load the data (platform.xml)
`sysrepocfg --edit=platformdata.xml `
 do simple edits each should take the same time those are just so you have a diff every time : 
```
sysrepocfg --edit=edit.xml
sysrepocfg --edit=edit2.xml
```

on my workstation that take like 3 sec with most of the time between the` if(node_types && node_types->count ) while` : 

```
Mon Apr  4 13:43:27 2022
 : lyd_validate_unres 312 12678 
Mon Apr  4 13:43:29 2022
 : lyd_validate_unres 337 leaf_ref: 7631 union_typ:5047 instance_typ:0 xpath_typ:0
```

and on my embedded device same data (timestamps in utc , i did it 7 minutes later as on my workstation)  it is an ARMv7 dualcore :

```
Mon Apr  4 11:50:17 2022
 : lyd_validate_unres 312 12678 
Mon Apr  4 11:51:14 2022
 : lyd_validate_unres 337 leaf_ref: 7631 union_typ:5047 instance_typ:0 xpath_typ:0
```

just for reverence how i got those debugs (i did add more before/after so the line count is properly off) but that is the only validation taking anytime at all, and it did it before i added the counting, as well :) . I compiled the same src lib yang for both (2.18.8): 
```
    if (node_types && node_types->count) {
        /* finish incompletely validated terminal values (traverse from the end for efficient set removal) */
        i = node_types->count;
        ltime=time(NULL); /* get current cal time */
        printf("%s : %s %d %d \n",asctime( localtime(&ltime)),__func__,__LINE__,i );  
        int leaf_ref=0,union_typ=0,instance_typ=0,xpath_typ=0;   
        do {
            --i;

            struct lyd_node_term *node = node_types->objs[i];
            struct lysc_type *type = ((struct lysc_node_leaf *)node->schema)->type;
            if(strcmp(type->plugin->id,"libyang 2 - leafref, version 1")==0) { leaf_ref++;
//                  ly_set_rm_index(node_types, i, NULL);
//                  continue;
            }
            else if(strcmp(type->plugin->id,"libyang 2 - union,version 1")==0)union_typ++;
            else if(strcmp(type->plugin->id,"libyang 2 - instance-identifier, version 1")==0)instance_typ++;
            else if(strcmp(type->plugin->id,"libyang 2 - xpath1.0, version 1")==0)xpath_typ++;
            else printf("%s \n",type->plugin->id);
            /* resolve the value of the node */
            LOG_LOCSET(node->schema, &node->node, NULL, NULL);
            ret = lyd_value_validate_incomplete(LYD_CTX(node), type, &node->value, &node->node, *tree);
            LOG_LOCBACK(node->schema ? 1 : 0, 1, 0, 0);
            LY_CHECK_RET(ret);

            /* remove this node from the set */
            ly_set_rm_index(node_types, i, NULL);
        } while (i);
        ltime=time(NULL);
        printf("%s : %s %d leaf_ref: %d union_typ:%d instance_typ:%d xpath_typ:%d\n",asctime( localtime(&ltime)),__func__,__LINE__,leaf_ref,union_typ,instance_typ,xpath_typ ); 
    }
```
[example.zip](https://github.com/CESNET/libyang/files/8409562/example.zip)

**Comment by michalvasko** [comment]
So I have taken a brief look and ti seems there really are that many leafrefs, right? Also, not sure what do you refer to when talking about O(n²) complexity. Please add more details because I am not sure how I would optimize this, currently.

**Comment by berstrob** [comment]
yeah the number of leafref is the number of componets , that is by design of that model.

n is the number of components, so each added component adds one more possible leaf_ref and at least one more check ( its own name , but most even more for sub components/parent references ,but that is a mostly constant factor (k) and is limited to be a small number bound by <10 , i think ) .

 Both " loops "grow if n grows: 10 components have there name check it is `10*10*k`, for 100 components `100*100*k` and so on, so `n*n*k -> O(n²)`. i think the problem is that it does look up the leafrefs every time from scratch and then searches them linear , 

My  first though was it should be possible to store all those identities once( since they should not be able to change at that point) and if sorted they should be possible to check in way less time (simple binary tree would be log(n) for a compare which has any sort of `<=>` , or maybe  a hash map or something even more fancy, that properly even would help a bit if you do only that inset of a simple set/list ) . But of course it only makes sense to store them if there are a certain amount of leafref and checks, maybe the first time count the possible  leafrefs and if more then idk like 100 store them with the querry (lref->path) as reference , so the next check can first check is there a leafref-query stored  and then look there . And of course all of the lockups need to be destroyed after all models are verified (you could need the leaf ref to that path from another model as well, so maybe keep the until then, but not really necessary since you could create it then again for not that big of a cost ) , since the leaf-refs can change between to verification. 

I hope that helps. If not i can try to explain more.

**Comment by michalvasko** [comment]
You are right that the validation is always performed from scratch. This is a design decision that we have made based on experiences with with *libyang* v1 where there was some caching and leafref validation was performed only once except it caused freeing such data to take almost as long as a complete validation would. So, like I said, the way to make this faster are optimizations.

However, in this case I still do not see any reasonable way to do that. All the leafrefs are relative and in list instances so the evaluation must start from the specific instances and it is not possible to reuse the result of one instance for another. Note that you can easily "skip" all the checks by setting the leafrefs `require-instance` to `false`. That would mean the data are valid even if there are no targets of those leafrefs.

**Comment by berstrob** [comment]
Yeah as expected setting ` require-instance` to `false` , does the same speed up (to nearly instant, even on my embedded device) as my rough hack , but it is not so invasive.   I am not keen on changing the "official" yang-model, but i may found a way around that, my load function can just "skip" those nodes that way, which i know is not the right way and you can't help me if it goes wrong :

```
 if((elem->schema->nodetype & LYD_NODE_TERM) && ((struct lysc_node_leaf *)elem->schema)->type->basetype==LY_TYPE_LEAFREF) {
                           ( (struct lysc_type_leafref *) ((struct lysc_node_leaf *)elem->schema)->type)->require_instance=0;
             }
```

so all externally added should still get checked , since then i can justify the validation time, if someone actually does change any thing there , but  the stored data , after all checks is safe to be ignored in my case, since all changes have to be valid ones (i only allow delete/add of some nodes anyway and the groups have to be fix , like  there have to be always 48 for each on 1 and so on, so i need some stricter checks in the change-callback anyway, but that is not the case for every one, so this can't be used for a general solution )


Thank you for your effort trying to optimizes this  , maybe in the future there will be some better way, since i still do not fully understand why that` struct lyxp_set set = {0}` has to be a list instead of something "sorted" by  `lref->plugin->compare` in `lyplg_type_resolve_leafref` , but i don't have to . I am very happy working with  the workaround. 

Thanks again and  regards

Bernd

**Comment by michalvasko** [comment]
I do not understand the last paragraph. `struct lyxp_set` actually is sorted in the XPath order because it may affect the evaluation but not sure what that has to do with anything. Regarding the optimizations, I understood that you suggested to create some data structure of all the leafref targets for some efficient search or something. My point is that since all those leafrefs start with a list instance, every evaluation is different. It may still, perhaps, be possible to use a structure with pairs of starting node - leafref target, but creating it may take the same time as the current evaluation.

**Comment by berstrob** [comment]
Ok but the validation is  `for (i = 0; i < set.used; ++i) {`  ,  i am speaking only about that set in the  `lyplg_type_resolve_leafref fuction` for the compare , which if i did understand you correct means the first check should be found instant , if both sets are sorted by xpath : lets say for example `/components/component[name='a'] ` to  `/components/component[name='z'] ` so if we validate  `/components/component[name='a'] we find it by 0 and so on till z at 25. but if it where are "sorted binary tree" it would always be in `log` steps , in that case 5 . 

And yes i know that only works for list where the value is in the xpath, thats why i thought about "value sorting" that . But i am pretty sure that for loop there is not the one needing the time, so that optimization will not help much anyway sadly.

**Comment by michalvasko** [comment]
Oh, I understand now. I have collected performance info for the use-case as the first thing, traversing that set is negligible. So, yes, it could be optimized (I have 7 631 calls of `lyplg_type_resolve_leafref` and 378 722 of `lyplg_type_compare_leafref`, which take about 0.5% of all the instructions) but it would have no effect.
