### ISSUE TITLE
`yanglint -t rpc` and `yanglint -t notif` produce error

### ISSUE THREAD

**Issue by kwatsen** [CESNET/libyang#1834]
_FWIW, the behavior changed recently as my "crypto-types" draft's build-scripts have been validating `rpc` and `notif` statements for awhile, including for the NETCONF 113 session a few weeks ago..._

I don't think the particular example matters, so not including YANG module or data tree. 

```
# yanglint -t rpc ../ex-crypto-types-usage\@*.yang ex-crypto-types-gcsr-rpc.xml
libyang err : Missing the operation node. (Line number 20.)
YANGLINT[E]: Failed to parse input data file "ex-crypto-types-gcsr-rpc.xml".
```

**Comment by michalvasko** [comment]
Sorry about that but please do include an example, a simple test with an `rpc` or an `action` worked fine for me so I do not know what to look for.

**Comment by kwatsen** [comment]
Sure.  Here's an example where a "-t notif" fails:  (_I'll post the RPC files in a follow-up message_)
```
yanglint -m -t notif ietf-crypto-types@2022-04-19.yang ietf-keystore@2022-04-19.yang yanglint-notification.xml ex-keystore.xml
```

Where 3 files can be found here:
```
https://raw.githubusercontent.com/netconf-wg/keystore/master/ietf-keystore.yang
https://raw.githubusercontent.com/netconf-wg/crypto-types/master/ietf-crypto-types.yang
https://raw.githubusercontent.com/netconf-wg/keystore/master/refs/ex-keystore.xml
```

_**BE SURE TO replace the"YYYY-MM-DD" placeholder date in the YANG files to today's date (date +%Y-%m-%d).   For example: `sed s/YYYY-MM_DD/<today's date>/g ietf-crypto-types.yang > ietf-crypto-types@<today's date>.yang**_

And the `yanglint-notification.xml` file is:
```
<keystore xmlns="urn:ietf:params:xml:ns:yang:ietf-keystore">
  <asymmetric-keys>
    <asymmetric-key>
      <name>hidden-asymmetric-key</name>
      <certificates>
        <certificate>
          <name>my-ldevid-cert</name>
          <certificate-expiration>
            <expiration-date>2018-08-05T14:18:53-05:00</expiration-date>
          </certificate-expiration>
        </certificate>
      </certificates>
    </asymmetric-key>
  </asymmetric-keys>
</keystore>
```

**Comment by kwatsen** [comment]
Here's an RPC example.

Using the command ```yanglint -t rpc ex-crypto-types-usage@2022-04-19.yang refs/ex-crypto-types-gcsr-rpc.xml```, where the two files are here:

```
https://raw.githubusercontent.com/netconf-wg/crypto-types/master/ietf-crypto-types.yang
https://raw.githubusercontent.com/netconf-wg/crypto-types/master/refs/ex-crypto-types-gcsr-rpc.xml
```

_**Again, BE SURE TO replace the"YYYY-MM-DD" placeholder date in the YANG files to today's date (date +%Y-%m-%d). For example: `sed s/YYYY-MM_DD/<today's date>/g ietf-crypto-types.yang > ietf-crypto-types@<today's date>.yang**_

**Comment by michalvasko** [comment]
As for the notification, if that worked before, it was only by chance because the data tree for validation needs to be provided by `-O` parameter and not just as another data file. That was not working properly, anyway, but now should.

Regarding the RPC, there the problem is that `ietf-crypto-types` is not being implemented so its features are disabled and the action unavailable. If you include it explicitly as an input YANG module, it will work.

**Comment by kwatsen** [comment]
For the RPC, so easy!  I wish the error message was more intuitive, or is there documentation showing `yanglint` command line usage?   

That said, moving to the validation of the RPC-reply, the same trick doesn't work, could you help me figure this one out too?

```
yanglint -t reply ietf-crypto-types\@*.yang ex-crypto-types-usage\@*.yang ex-crypto-types-gcsr-rpc-reply.xml ex-crypto-types-gcsr-rpc.xml
libyang err : Missing the operation node. (Line number 8.)
YANGLINT[E]: Failed to parse input data file "refs/ex-crypto-types-gcsr-rpc-reply.xml".
```

Where all the files are here:
```
https://raw.githubusercontent.com/netconf-wg/crypto-types/master/ietf-crypto-types.yang (w/ YYYY-MM-DD replaced)
https://raw.githubusercontent.com/netconf-wg/crypto-types/master/ex-crypto-types-usage.yang (w/ YYYY-MM-DD replaced)
https://raw.githubusercontent.com/netconf-wg/crypto-types/master/refs/ex-crypto-types-gcsr-rpc.xml
https://raw.githubusercontent.com/netconf-wg/crypto-types/master/refs/ex-crypto-types-gcsr-rpc-reply.xml
```

**Comment by michalvasko** [comment]
> is there documentation showing yanglint command line usage?

Of course, just standard `yanglint -h` should be fine. I will take a look at your use-cases tomorrow, have no time left today.

**Comment by michalvasko** [comment]
When migrating `yanglint` to version 2, only the necessary changes were made and the result was hardly ideal. I have tried to add proper support for the changes and also improved the basic `yanglint -h` usage text with examples that should be more helpful, you can check them out.

So, to validate the RPC reply
```
yanglint -t nc-reply -R ex-crypto-types-gcsr-rpc.xml ietf-crypto-types.yang ex-crypto-types-usage.yang ex-crypto-types-gcsr-rpc-reply.xml
```
As for the notification, the command you posted worked so I am not sure what help were you asking of me.

**Comment by kwatsen** [comment]
Nice update to `yanglint -h`    👍    I got the RPC-reply working now too.   Thanks!

You're right about the notification example working - strange, as I can scroll up in my terminal and see where it didn't...

In any case, there is one last related issue, which is the the validation for the notification doesn't seem to work.  After doing https://github.com/CESNET/libyang/issues/1834#issuecomment-1103936419, edit the `yanglint-notification` file by introducing an invalid location in the data tree: `s/my-ldevid-cert/my-foobar-cert/`.  The validation still works even though the referenced data-node doesn't exist?

**Comment by michalvasko** [comment]
You are right, unless you provided the `operational` data file, operations were not being validated at all. I have fixed that but in this particular case the validation succeeds anyway. The reason is that *libyang* validates only the **body** of an operation (input/output/notification) and does not perform the separate check of existing parent for nested operations. Actually, any parents of a nested operation are not validated at all. I could add this into `yanglint` without much trouble but I am not sure whether I should. If I did, it would always be required to provide `operational` data for nested operation validation to pass.

**Comment by kwatsen** [comment]
Hi Michal, sorry for the delay (big deadline!)

I synched the latest "devel" code and now it seems that the RPC isn't validating anymore (even after ensuring the dependent module is implemented, so the action is defined).  I'm also having the same issue with the RPC-reply validation test.  Lastly, I found a segmentation fault.  All three of these issues are described below.

For all three issues, the following 5 files are needed:
```
1) https://raw.githubusercontent.com/netconf-wg/crypto-types/master/ietf-crypto-types.yang (w/ YYYY-MM-DD replaced)
2) https://raw.githubusercontent.com/netconf-wg/crypto-types/master/ex-crypto-types-usage.yang (w/ YYYY-MM-DD replaced)
3) https://raw.githubusercontent.com/netconf-wg/crypto-types/master/refs/ex-crypto-types-usage.xml
4) https://raw.githubusercontent.com/netconf-wg/crypto-types/master/refs/ex-crypto-types-gcsr-rpc.xml
5) https://raw.githubusercontent.com/netconf-wg/crypto-types/master/refs/ex-crypto-types-gcsr-rpc-reply.xml
```


ISSUE-1: RPC
```
yanglint -t nc-rpc -O ex-crypto-types-usage.xml ietf-crypto-types\@*.yang ex-crypto-types-usage\@*.yang ex-crypto-types-gcsr-rpc.xml
libyang err : Invalid argument !op_tree->parent (lyd_validate_op()).
YANGLINT[E]: Failed to validate input data file "ex-crypto-types-gcsr-rpc.xml" with operational datastore "ex-crypto-types-usage.xml".
```

ISSUE-2: RPC-reply
```
yanglint -t nc-reply -O ex-crypto-types-usage.xml -R ex-crypto-types-gcsr-rpc.xml ietf-crypto-types\@*.yang ex-crypto-types-usage\@*.yang ex-crypto-types-gcsr-rpc-reply.xml
libyang err : Invalid argument !op_tree->parent (lyd_validate_op()).
YANGLINT[E]: Failed to validate input data file "ex-crypto-types-gcsr-rpc-reply.xml" with operational datastore "ex-crypto-types-usage.xml".
```

ISSUE-3: segfault  (same command as in ISSUE-1 but `-t nc-rpc` changed to `-t rpc`)
```
yanglint -t nc-rpc -O ex-crypto-types-usage.xml ietf-crypto-types\@*.yang ex-crypto-types-usage\@*.yang ex-crypto-types-gcsr-rpc.xml
zsh: segmentation fault  yanglint -t rpc ietf-crypto-types\@*.yang ex-crypto-types-usage\@*.yang
```

**Comment by kwatsen** [comment]
Regarding:

> I could add this into yanglint without much trouble but I am not sure whether I should. If I did, it would always be required to provide operational data for nested operation validation to pass.

How about the other way around, only test parents exist when the `-O` flag is used to supply operational data?

FWIW, the notification-validation succeeds regardless if the `-O` flag is used:
```
# yanglint -t notif -O ex-crypto-types-usage.xml ietf-crypto-types\@*.yang ex-crypto-types-usage\@*.yang yanglint-notification.xml
# echo $?
0

# yanglint -t notif  ietf-crypto-types\@*.yang ex-crypto-types-usage\@*.yang yanglint-notification.xml
# echo $?
0
```

I guess because the notification doesn't contain a `leafref` to anything in <operational>?

**Comment by michalvasko** [comment]
Okay, so please try the latest `devel`. The errors and the crash should be fixed and nested operation parent validation added.

**Comment by kwatsen** [comment]
The crash is fixed (nice error message, thanks!)

But nested operation parent validation still doesn't work for RPC and some other issue arises for the RPC-reply.

1) For the RPC, all the files are the same as before, but edit the `ex-crypto-types-gcsr-rpc.xml` file to reference a non-existent key (i.e., `foobar-hidden-asymmetric-key` below):
```
<rpc message-id="101"
  xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <action xmlns="urn:ietf:params:xml:ns:yang:1">
    <asymmetric-keys
      xmlns="http://example.com/ns/example-crypto-types-usage">
      <asymmetric-key>
        <name>foobar-hidden-asymmetric-key</name>
        <generate-certificate-signing-request>
          <csr-info>BASE64VALUE=</csr-info>
        </generate-certificate-signing-request>
      </asymmetric-key>
    </asymmetric-keys>
  </action>
</rpc>
```

Gives this (though it should fail):
```
# yanglint -t nc-rpc -O ex-crypto-types-usage.xml ../ietf-crypto-types\@*.yang ../ex-crypto-types-usage\@*.yang ex-crypto-types-gcsr-rpc.xml

# echo $?
0
```

2) For the RPC-reply, all the files are exactly the same as before (not that it matters, but be sure to revert the `ex-crypto-types-gcsr-rpc.xml` file from above):

```
# yanglint -t nc-reply -O ex-crypto-types-usage.xml -R ex-crypto-types-gcsr-rpc.xml ../ietf-crypto-types\@*.yang ../ex-crypto-types-usage\@*.yang ex-crypto-types-gcsr-rpc-reply.xml

libyang err : Invalid opaque node "certificate-signing-request" found. (Data location /ex-crypto-types-usage:asymmetric-keys/asymmetric-key[name='ex-hidden-asymmetric-key']/generate-certificate-signing-request/certificate-signing-request.)
YANGLINT[E]: Failed to validate input data file "ex-crypto-types-gcsr-rpc-reply.xml" with operational datastore "ex-crypto-types-usage.xml".
```

Note that it you do NOT revert the `ex-crypto-types-gcsr-rpc.xml` file from above, the error message looks like this (note how `foobar` appears):

```
libyang err : Invalid opaque node "certificate-signing-request" found. (Data location /ex-crypto-types-usage:asymmetric-keys/asymmetric-key[name='foobar-hidden-asymmetric-key']/generate-certificate-signing-request/certificate-signing-request.)
YANGLINT[E]: Failed to validate input data file "ex-crypto-types-gcsr-rpc-reply.xml" with operational datastore "ex-crypto-types-usage.xml".
```

**Comment by michalvasko** [comment]
Right, 1. should be fixed and in 2. the problem is invalid `binary` value in `ex-crypto-types-gcsr-rpc-reply.xml`, the spaces are not allowed.

**Comment by kwatsen** [comment]
Much improved error message  +1

All my issues are resolved now (thanks!)

Now the entire suite of crypto-types based drafts are validating :)
