### ISSUE TITLE
Data parser option to automatically add ietf components

### ISSUE THREAD

**Issue by jeanseb6wind** [CESNET/libyang#1835]
Hello,

In libyang1, we had the possibility to complete datastore content with configuration as well as state data.
Like you can see [here](https://netopeer.liberouter.org/doc/libyang/libyang1/html/group__parseroptions.html#gac69e256cb524e4d80ce0fa8045c10d4d) with LYD_OPT_DATA.

Is it possible to get a similar behavior with libyang2 ? If yes, how can I do it ?

Thanks

**Comment by michalvasko** [comment]
The option was added to allow incomplete data (for a single YANG module) to be validated, which was failing without `ietf-yang-library` data. In *libyang* v2, there is `LYD_VALIDATE_PRESENT` that successfully validates such data without `yang-library` data. So, if you want these data, you have to generate and append them yourself. Get them using `ly_ctx_get_yanglib_data()`.
