### ISSUE TITLE
Calling lyd_free_withsiblings only frees user memory and not heap memory

### ISSUE THREAD

**Issue by sicongPang** [CESNET/libyang#1838]
hi

After I use libyang to create a lyd_node node, I call the lyd_free_withsibling function to release the node, but through the malloc_stat function, I find that the in use bytes are decreasing, but the system bytes have not changed. I don't know if there is a problem with my use. Here is the result I printed with malloc_stats:

Total (incl. mmap):
system bytes     = 1115590656
in use bytes     =  913782368
max mmap regions =          8
max mmap bytes   = 4265291776

（lyd_free_withsiblings is called in the middle to release the node）

Total (incl. mmap):
system bytes     = 1115590656
in use bytes     =  615857008
max mmap regions =          8
max mmap bytes   = 4265291776

Would love to hear your thoughts about that.

Regards.

**Comment by michalvasko** [comment]
Use `valgrind` to check for memory leaks, if it reports none, it works correctly. The observed numbers could perhaps be explained by the fact that `free()` does not immediately free the memory but instead waits for more calls to increase efficiency and return the memory to kernel in larger chunks. But this is just my guess, I have not looked up any specific information.
