### ISSUE TITLE
Not able to enable feature on a imported module

### ISSUE THREAD

**Issue by vijayck** [CESNET/libyang#1839]
Below is the schema details for your reference.
```yang
module  test_module {
     prefix "testModule";
     feature  TEST_MODULE_FEATURE {
            description   "Test feature";
     }

    grouping  testConfigGrp {
           ... leaf elements using the if-feature ...
    }
}
```
```yang
module test {
      import test_module {  prefix "testModule"; }

      container  testConfig {
            uses testConfigGrp;
       }
}
```
We are trying to check feature availability in the module (test) using lys_feature_value(). But this fails.
On checking the code, we see that lysp_feature_find() is called without verifying the prefix.
```C
    /* search for the specified feature */
    f = lysp_feature_find(module->parsed, feature, strlen(feature), 0);   <<< Last argument in the API.
```
Should we search for the prefix also in this API ? We think, it should, because it should search within imported modules also.
Could you please provide your inputs on this.

**Comment by michalvasko** [comment]
`lysp_feature_find()` searches the local features in `module->parsed` only, the documentation does not say anything about imports.

**Comment by rahkumar651991** [comment]
How should we enable the TEST_MODULE_FEATURE in this? 

sysrepoctl -l output is like below. 
```
Module Name                       | Revision   | Flags | Owner     | Permissions | Submodules
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_module                | 2018-07-31 | i     |           |             |
test                       | 2020-02-24 | I     | root:root |   600       |
```

We tried multiple commands like below but the feature doesn't get loaded properly. We need import statement and include statement will not work for our scenario. It works fine for include but not for import. 
```

sysrepoctl -e TEST_MODULE_FEATURE -c test 
sysrepoctl -e test_module:TEST_MODULE_FEATURE -c test 
```

**Comment by michalvasko** [comment]
Please, do not create duplicate issues.
