### ISSUE TITLE
yanglint - model loading when imports are used

### ISSUE THREAD

**Issue by hjensas** [CESNET/libyang#1842]
Trying to use yanglint to validate configuration datastore, the yang model is openconfig which is heavily using imports and includes.
Despite setting the search path I get the below error. If I add additional schemas, such as `./yang-models/public/release/models/mpls/openconfig-mpls-types.yang` the error changes.

Based on the manual page ` -p PATH, --path=PATH -- Specifies search path for getting imported modules or included submodules.` I would expect the imports and includes be loaded since they are all in the path?

```
yanglint --type config \
  --path ./yang-models \
 ./yang-models/public/release/models/network-instance/openconfig-network-instance.yang ./yang.xml
```

> libyang err : Invalid default - value does not fit the type (Invalid identityref "oc-mplst:LOCALLY_COMPUTED" value - identity found in non-implemented module "openconfig-mpls-types".). (Schema location /openconfig-network-instance:network-instances/network-instance/mpls/lsps/constrained-path/tunnels/tunnel/p2p-tunnel-attributes/p2p-secondary-paths/p2p-secondary-path/state/path-computation-method.)
Segmentation fault (core dumped)

```
yanglint --type config \
  --path ./yang-models \
  ./yang-models/public/release/models/mpls/openconfig-mpls-types.yang \
  ./yang-models/public/release/models/network-instance/openconfig-network-instance.yang \
  ./yang.xml
```

> libyang err : No module with namespace "http://openconfig.net/yang/vlan" in the context. (Schema location /openconfig-network-instance:network-instances/network-instance, data location /openconfig-network-instance:network-instance[name='default'], line number 7.)
YANGLINT[E]: Failed to parse input data file "./yang.xml".

**./yang.xml - I am trying to validate:**
```
  <network-instances xmlns="http://openconfig.net/yang/network-instance">
    <network-instance>
      <name>default</name>
      <config>
        <name>default</name>
      </config>
      <vlans xmlns="http://openconfig.net/yang/vlan">
        <vlan>
          <vlan-id operation="merge">113</vlan-id>
          <config operation="merge">
           <vlan-id>113</vlan-id>
            <name>5d3a9c397cb14bd3b67cbb471d01cbeb</name>
            <status>ACTIVE</status>
          </config>
        </vlan>
      </vlans>
    </network-instance>
  </network-instances>
```

I am using yanglint 2.0.164 - from the Fedora 35 RPM package - libyang-tools-2.0.164-1.fc35.x86_64
```
$ yanglint -v
yanglint 2.0.164
```

**Comment by jktjkt** [comment]
`--path` does not work recursively, and your (sub)modules are deep in some subdirectories. You will have to add all directories to `-p`, or change your on-disk layout with schemas.

However, keep in mind that the OpenConfig models are not IETF-compliant. Their understanding of regular expression syntax does not conform to the YANG standard. Data validation therefore won't work with libyang.

**Comment by michalvasko** [comment]
@jktjkt Actually, `--path` does work recursively.

The problem is that you are completely neglecting the difference between implemented and imported modules. You need to specify all the modules that should be implemented explicitly. In the first case it means adding `openconfig-mpls-types` and in the second case the module with namespace `http://openconfig.net/yang/vlan`.

**Comment by hjensas** [comment]
> > Regarding the regular expression syntax, I think I saw something in the issue tracker related to this. OpenConfig is escaping quotes in a non-compliant way if I remember correctly?
> 
> OpenConfig uses a different engine for regular expressions. The biggest difference is implicit anchoring, i.e., `^` and `$`.

ack, I just read trough https://github.com/openconfig/public/issues/44 ...
It looks like they are trying to improve the situation with the `oc-ext:posix-pattern` extension.

Thanks for the support, I managed to lint my config data with your suggestions
Close the issue with this comment.
