### ISSUE TITLE
Segmentation fault with a too small binary node

### ISSUE THREAD

**Issue by gotthardp** [CESNET/libyang#1846]
With `size_t size` (unsigned) the following causes an underflow of `size` when `size < 2` and consequently a segmentation fault:
https://github.com/CESNET/libyang/blob/34fb9e0f4771e67eb6018963697c7a8214711eb0/src/plugins_types/binary.c#L72

I believe the condition should rather be:
```c
for (i = 0; i + 2 < size; i += 3) { 
```

**Comment by michalvasko** [comment]
Right, fixed.
