### ISSUE TITLE
bbf-software-management.yang "when" statement validation failure in libyang-1.0.240

### ISSUE THREAD

**Issue by wdl2015** [CESNET/libyang#1847]
Hi experts,

I am using an old version of libyang-1.0.240 together with sysrepo-1.4.140 and netopeer2-1.1.76. 
On this libyang version when I trigger the download action of bbf-software-management@2022-03-01.yang (see attached for this yang model) sysrepo reports "Action input validation failed" error message. 
With some libyang code investigation the failure comes from libyang _lyd_validate() function which is trying to validate/resolve the related yang nodes along the action path (/ietf-hardware:hardware/component[name=\'olt1\']/bbf-software-management:software/software[name=\'exs1610app\']/revisions/download/download).
Search some tickets in this repo which may relate to my problem and add the code in my environment, but could not fix my problem. 
Could you advise if anything wrong in my usage or newer libyang version fixes this problem? Thanks very much.

The bbf software management yang model being used is attached. The suspected failure related parts are pasted here. From the libyang code flow it fails on the “when” statements resolving.
```yang
          container download {
            when "derived-from(../../bbf-swm:capability,'bbf-swm:download') and count(../bbf-swm:revision[bbf-swm:state='downloading'])=0" {
              description
                "Only applicable if downloading of revisions for this
                 software is supported and no other download of a
                 revision for this software is currently in
                 progress.";
            }
            description
              "Provides containment for the action 'download'.";
            action download {
              if-feature "software-management-actions";
              description
                "Download the specified software revision to this
                 component.
                  … …
                                  model.";
                  … …
                container target {
                  description
                    "The target of the download.";
                  choice target {
                    mandatory true;
                    description
                      "The target entry in the list 'revision' for
                       the download, including how the entry is to be
                       selected.";
                    case selected-by-user {
                      when "../../../../bbf-swm:capability='bbf-swm:download-target-selection-by-user'" {
                        description
                          "Only applicable if the software
                           supports the case 'selected-by-user'.";
                      }
```
The sysrepo operational DB is provisioned with below data.
```xml
   <hardware xmlns="urn:ietf:params:xml:ns:yang:ietf-hardware">
      <component>
        <name>olt1</name>
        <class xmlns:ianahw="urn:ietf:params:xml:ns:yang:iana-hardware">ianahw:chassis</class>
        <software xmlns="urn:bbf:yang:bbf-software-management">
          <software>
            <name>exs1610app</name>
            <capability>download-target-selection-by-user</capability>
            <capability>download-target-selection-by-system</capability>
            <capability>validate</capability>
            <capability>activate</capability>
            <capability>commit</capability>
            <capability>delete</capability>
            <capability>alias</capability>
            <revisions>
              <revision>
                <id>66</id>
                <state>available</state>
              </revision>
            </revisions>
        </software>
      </software>
   </component>
</hardware>
```
The xml script used to trigger a download action as follows:
```xml
  <action xmlns="urn:ietf:params:xml:ns:yang:1">
    <hardware xmlns="urn:ietf:params:xml:ns:yang:ietf-hardware">
        <component>
            <name>olt1</name>
            <software xmlns="urn:bbf:yang:bbf-software-management">
                <software>
                    <name>exs1610app</name>
                    <revisions>
                        <download>
                            <download>
                                <source>
                                    <url>http://10.254.23.115/exs1610_23.02.00.tar.gz</url>                                
                                </source>
                                <target>
                                    <selected-by-user>
                                        <operation>create</operation>
                                    </selected-by-user>
                                </target>
                            </download>
                        </download>
                    </revisions>
                </software>
            </software>
        </component>
    </hardware>
</action>
```

Br
George

[bbf-software-management@2022-03-01.txt](https://github.com/CESNET/libyang/files/8669283/bbf-software-management%402022-03-01.txt)

**Comment by wdl2015** [comment]
The sysrepo DB is provisioned with below data: `<hardware xmlns="urn:ietf:params:xml:ns:yang:ietf-hardware">
  <component>
    <name>olt1</name>
    <class xmlns:ianahw="urn:ietf:params:xml:ns:yang:iana-hardware">ianahw:chassis</class>
    <software xmlns="urn:bbf:yang:bbf-software-management">
      <software>
        <name>exs1610app</name>
        <capability>download-target-selection-by-user</capability>
        <capability>download-target-selection-by-system</capability>
        <capability>validate</capability>
        <capability>activate</capability>
        <capability>commit</capability>
        <capability>delete</capability>
        <capability>alias</capability>
        <revisions>
          <revision>
            <id>66</id>
            <state>available</state>
          </revision>
        </revisions>
      </software>
    </software>
  </component>
</hardware>
`

**Comment by wdl2015** [comment]
The sysrepo operational DB is provisioned with below data:

> <hardware xmlns="urn:ietf:params:xml:ns:yang:ietf-hardware">
  <component>
    <name>olt1</name>
    <class xmlns:ianahw="urn:ietf:params:xml:ns:yang:iana-hardware">ianahw:chassis</class>
    <software xmlns="urn:bbf:yang:bbf-software-management">
      <software>
        <name>exs1610app</name>
        <capability>download-target-selection-by-user</capability>
        <capability>download-target-selection-by-system</capability>
        <capability>validate</capability>
        <capability>activate</capability>
        <capability>commit</capability>
        <capability>delete</capability>
        <capability>alias</capability>
        <revisions>
          <revision>
            <id>66</id>
            <state>available</state>
          </revision>
        </revisions>
      </software>
    </software>
  </component>
</hardware>

**Comment by michalvasko** [comment]
The XMLs you pasted seem fine so I cannot rule out a problem in *sysrepo*/*libyang*. In any case, the version you are using is obsolete for quite some time now so I would definitely advise to use the latest released versions. I have been fixing some similar problems recently so it should definitely work fine in those version.

**Comment by wdl2015** [comment]
Hi Michal, 

Thanks a lot for your quick response on this issue. 
With more investigation looks like below change based on 1.0.240 can fix this issue. For sure the changes are just for trouble shooting, not solution. 
The 2.0.7 libyang version neighboring to 1.0.240 is very different from 1.0.240, the resolve.c file cannot find any more, and the functions in resolve.c in 1.0.240 cannot be found in 2.0.7 either. 2.0.7 must have a big restructure to the software. 
So would like to ask your suggestions if any ticket in 1.0.240 later provides this kind of fixes to this issue. Thanks much.

diff --git a/src/resolve.c b/src/resolve.c
index c7a6b063..c5e253ec 100644
--- a/src/resolve.c
+++ b/src/resolve.c
@@ -6433,7 +6433,7 @@ resolve_when_ctx_node(struct lyd_node *node, struct lys_node *schema, struct lyd
         for (sparent = schema, schema_depth = 0;
                 sparent;
                 sparent = (sparent->nodetype == LYS_AUGMENT ? ((struct lys_node_augment *)sparent)->target : sparent->parent)) {
-            if (sparent->nodetype & (LYS_CONTAINER | LYS_LEAF | LYS_LEAFLIST | LYS_LIST | LYS_ANYDATA | LYS_NOTIF | LYS_RPC)) {
+            if (sparent->nodetype & (LYS_CONTAINER | LYS_LEAF | LYS_LEAFLIST | LYS_LIST | LYS_ANYDATA | LYS_NOTIF | LYS_RPC | LYS_ACTION)) {
                 ++schema_depth;
             }
         }
@@ -8620,6 +8620,9 @@ resolve_unres_data(struct ly_ctx *ctx, struct unres_data *unres, struct lyd_node
             for (parent = unres->node[i]->parent;
                  parent && LYD_WHEN_DONE(parent->when_status);
                  parent = parent->parent) {
+                if(parent->parent) {
+                    parent->parent->when_status |= LYD_WHEN_TRUE;
+                }
                 if (!parent->parent && (parent->when_status & LYD_WHEN_FALSE)) {
                     /* the parent node was already unlinked, do not resolve this node,
                      * it will be removed anyway, so just mark it as resolved

Br
George

**Comment by michalvasko** [comment]
> So would like to ask your suggestions if any ticket in 1.0.240 later provides this kind of fixes to this issue.

I do not know about any, so probably not.

The first change seems like a bugfix that could be merged but the other one like a workaround that is not actually solving the problem. The core issue may be quite difficult to fix and since there is a new version, it makes no sense for us to spend time on that. So, yes, some effort will be required for updating but similarly so for fixing the bug in *libyang* v1. But sooner or later you most likely will need to migrate so you might as well now. Otherwise you risk finding new problems that you will have to fix by yourself.

**Comment by wdl2015** [comment]
Hi Michal, thanks a lot for all the help. Will upgrade. Close this ticket at your convenience. Br, George
