### ISSUE TITLE
Error when refining bits

### ISSUE THREAD

**Issue by jeanseb6wind** [CESNET/libyang#1848]
Hello @michalvasko,

I found a regression in `libyang2` about refining bits:
If you try to load this very simple module:

```
module test {
  namespace "urn:yang:test";
  prefix test;

  grouping alg {

    leaf alg2 {
      type bits {
        bit ftp;
        bit h323-q931;
        bit h323-ras;
        bit pptp;
        bit rtsp;
        bit sip-tcp;
        bit sip-udp;
        bit tftp;
        bit dns-udp;
      }
    }
  }

  container conf {
    description
      "Configuration.";
    uses alg {
      refine alg2 {
          default "dns-udp";
        }
      }
  }
}
```

You will get this error: `Invalid default - value does not fit the type (Duplicate bit "dns-udp".).`.

With `libyang1`, it works as expected.
Is this an error with `libyang2` ?

Thanks
Jean-Sébastien

**Comment by michalvasko** [comment]
Yes, a bug in the `bits` type, should be fixed.
