### ISSUE TITLE
lyd_parse_data_mem correct usage

### ISSUE THREAD

**Issue by tryshakti** [CESNET/libyang#1851]
Hi,

I'm trying to parse a JSON format string, of a IETF interface tree, as below:
```C
char *pdata = 
{"ietf-interfaces:interfaces":{"interface":[{"admin-status":"up","description":"Interface0","if-index":0,"name":"Ethernet0","oper-status":"up","statistics":{"in-broadcast-pkts":"0","in-discards":0,"in-errors":0,"in-multicast-pkts":"0","in-octets":"0","in-unicast-pkts":"0","out-broadcast-pkts":"0","out-discards":0,"out-errors":0,"out-multicast-pkts":"0","out-octets":"0","out-unicast-pkts":"0"},"type":"ianaift:ethernetCsmacd"}]}}

	if( LY_SUCCESS != lyd_parse_data_mem(ly_ctx, pdata, LYD_JSON, 0, 0, &data))
	{
    	SRPLG_LOG_ERR("plugin", "lyd_parse_data_mem failed.");
        }
```
I'm getting the following error: 

```
> [ERR] plugin: lyd_parse_data_mem failed.
> [ERR] plugin: error: List instance is missing its key "name".
> 
> [ERR] plugin: errorpath: Schema location /ietf-interfaces:interfaces/interface, data location /ietf-interfaces:interface, line number 1.
```

The 'name' is present in the string, but it still complains.
Any help is appreciated.

**Comment by michalvasko** [comment]
The error is not seen with the current *libyang*, what version are you using?

**Comment by tryshakti** [comment]
The version is 2.0.194

**Comment by michalvasko** [comment]
Right, please try the latest `devel`, there was a bug. However, note that not all the specified nodes will be parsed because some are disabled by their `if-features` and others have an invalid value (*libyang* will warn about the latter).

**Comment by tryshakti** [comment]
Tried with both **devel** & **master** branch, the issue is reproducible on both.

node= {"ietf-interfaces:interfaces":{"interface":[{"admin-status":"up","description":"santhu-Interface0","if-index":0,"name":"Ethernet0","oper-status":"up","statistics":{"in-broadcast-pkts":"0","in-discards":0,"in-errors":0,"in-multicast-pkts":"0","in-octets":"0","in-unicast-pkts":"0","out-broadcast-pkts":"0","out-discards":0,"out-errors":0,"out-multicast-pkts":"0","out-octets":"0","out-unicast-pkts":"0"},"type":"ianaift:ethernetCsmacd"}]}}

[ERR] bbf-plugin: lyd_parse_data_mem failed.
[ERR] bbf-plugin: error: List instance is missing its key "name".

**Comment by michalvasko** [comment]
Then you will need to provide the exact set of YANG modules you have loaded, it worked with the ones I have tried it with.

**Comment by tryshakti** [comment]
> Then you will need to provide the exact set of YANG modules you have loaded, it worked with the ones I have tried it with.

Output of "sysrepoctl -l" attached for reference. 

[loaded.zip](https://github.com/CESNET/libyang/files/8753733/loaded.zip)

**Comment by michalvasko** [comment]
Just to make sure, the problem and fix is in *libyang*, not *sysrepo*, so you have to update *libyang*. I have tried with the same set of modules but it worked fine.
