### ISSUE TITLE
replacement or equivalence for lyd_find_instance() API

### ISSUE THREAD

**Issue by Haititi** [CESNET/libyang#1852]
Hi,

I'm trying to upgrade my code to libyang2, but it seems that the `lyd_find_instance()` API that I was using with libyang1 has been removed in libyang2.
how can i reproduce the same result as `lyd_find_instance(data, schema);` with libyang2 ? may i have an example ?
Thanks a lot!

**Comment by michalvasko** [comment]
You can use the macro `LYD_LIST_FOR_INST` to directly iterate over them, for example.

**Comment by michalvasko** [comment]
That is exactly what the macro does for you.

**Comment by Haititi** [comment]
That's what i thought to begin with, but i was looking for a more direct solution haha.
I will just do that then.
Thanks for your help !

**Comment by michalvasko** [comment]
That is basically what `lyd_find_instance()` was doing internally so we decided to remove it to avoid duplicating functionality.
