### ISSUE TITLE
Can't refine an already refined leaf

### ISSUE THREAD

**Issue by jeanseb6wind** [CESNET/libyang#1854]
Hello,
I found a bug in `libyang2`. When you try to refine an already refined leaf you get an error.
It was working with libyang1.

To reproduce it, try to install the following yang:

```
module test2 {
  yang-version 1.1;
  namespace n;
  prefix test2;

  grouping testgroup {
    leaf testleaf {
      type boolean;
    }
  }

  grouping topgroup {
    uses testgroup {
      refine testleaf {
        default true;
      }
    }
  }

  grouping toptopgroup {
    container topcontainer {
      container subcontainer {
        uses topgroup;
      }
    }
  }

  container c2 {
    uses toptopgroup {
      refine "topcontainer/subcontainer/testleaf" {
        default false;
      }
    }
  }
}
```

You will get the error: `cannot load module: Refine(s) target node "testleaf" in grouping "testgroup" was not found.`
It was working with `libyang1`.

Thanks

**Comment by michalvasko** [comment]
Right, should work now.
