### ISSUE TITLE
New behavior for LYS_ORDBY_USER 

### ISSUE THREAD

**Issue by jeanseb6wind** [CESNET/libyang#1859]
Hello @michalvasko,
This issue is more a question than an issue.

In libyang2, there is a new define LYS_ORDBY_SYSTEM.
In libyang, there is only the define LYS_ORDBY_USER.

The problem I'm facing is that LYS_ORDBY_USER in libyang2 is always set for state like written in the doc ([here](https://netopeer.liberouter.org/doc/libyang/master/html/group__snodeflags.html#gaa1a13e8d1a4b13045487a3d7d6137ef5)).

So when I compare the same node in config and state, it is not equal since with the state, the flag LYS_ORDBY_USER is set whereas it is not set in config.
Is this a normal behavior ? Should I use LYS_ORDBY_SYSTEM flag instead ? What is the difference between theses two flags ?

Thanks,
Jean-Sébastien

**Comment by michalvasko** [comment]
I am not really sure what to tell you. The change is caused by the distinction between parsed and compiled nodes and the idea is that a compiled node is always either ordered by system or user, that is why either is always set.

**Comment by jeanseb6wind** [comment]
Thanks for your answer.
