### ISSUE TITLE
lyd_parse_data not working as expected

### ISSUE THREAD

**Issue by jeanseb6wind** [CESNET/libyang#1861]
Hello @michalvasko,

I found a bug with `lyd_parse_data` and the dependent functions like `lyd_parse_data_mem`.

Here the steps to reproduce it:

With this yang:

```
module coco {
  yang-version 1.1;
  namespace "urn:yang:coco";
  prefix coco;

  container thefirst {
    leaf dummy {
      type string;
    }
  }

  container config {
    leaf hostname {
      type string;
    }
  }

  container state {
    leaf hostname {
      type string;
    }
    config false;
  }
}
```

You want to parse data with this json:

```
{
   "coco:config": { 
     "hostname": "myhostname"
    }
} 
```

With libyang1, `lyd_parse_mem` will return the dnode `config` but with libyang2, `lyd_parse_data_mem` will return the dnode `thefirst`.
Indeed, with libyang2, it returns the first node of the top of the tree whereas with libyang1, it returns only what we parse.

I found that with libyang2, there is an option `LYD_PARSE_SUBTREE` which seems to be the solution to this problem but when I add this flag I got this error:
```
failed to parse data tree: Invalid character sequence "{
  "coco:config": {", expected a JSON object's member.
```

Thanks,
Jean-Sébastien

**Comment by michalvasko** [comment]
This is a feature but may be unexpected at first. It is all based on the *libyang2* feature of all the nodes always being in their schema order. When parsing your JSON data, they are then validated and all the NP containers created. It seemed most reasonable to always return the first top-level node. So not sure what exactly is the scenario where you consider this a bug but to get only the parsed data you can skip validation (which includes creating default data and NP containers) with `LYD_PARSE_ONLY`.

The flag `LYD_PARSE_SUBTREE` is quite specific and meant for partial data parsing, which in your case would be
```json
   "coco:config": { 
     "hostname": "myhostname"
   }
```

**Comment by jeanseb6wind** [comment]
Indeed @michalvasko , If I add the flag parse_only it works as expected.
Thanks
