### ISSUE TITLE
lysc_node_leaf/priv/type/compiled is NULL while lysc_node_leaf/type is not 

### ISSUE THREAD

**Issue by Haititi** [CESNET/libyang#1864]
Hi again :)
I have the following behavior (LY_CTX_SET_PRIV_PARSED is used on my context in order to retrieve the parsed node from `priv`) : 

```
struct lysc_node *snode;
...
assert(snode->nodetype & LYS_LEAF);     // OK

struct lysc_node_leaf *sleaf = (struct  lysc_node_leaf *)snode;
struct lysp_node_leaf *pleaf = (struct lysp_node_leaf *)sleaf->priv;

assert(sleaf->type != NULL);    // OK
assert(pleaf->type.compiled != NULL);    // KO
assert(pleaf->type.compiled == sleaf->type);    // KO
```

Is this behavior normal ? shouldn't the last 2 asserts be OK ?

**Comment by michalvasko** [comment]
This is intentional, only custom `typedef` types are stored in `compiled`, it is not used for built-in types.
