### ISSUE TITLE
Please tag releases in git

### ISSUE THREAD

**Issue by jktjkt** [CESNET/libyang#187]
I would like to have git tags for individual release in git. This would make it easy for the packaging scripts to identify a version of the current code  and how to call the resulting binaries. Having tags for the past releases would be nice, but even from now on, including the latest release, would make my workflow a bit easier.

For an example, check the result of ``git describe --tags`` between sysrepo/sysrepo and this.

Could you please do this for CESNET/Netopeer2, too?

**Comment by rkrejci** [comment]
done in libyang, in libnetconf2 and Netopeer2 the tags/releases will be created with the next releases
