### ISSUE TITLE
tree_schema.c Internal error for version tags/v2.0.164

### ISSUE THREAD

**Issue by m12wang** [CESNET/libyang#1872]
sysrepocfg -X
[ERR] Regular expression "\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[\+\-]\d{2}:\d{2})" is not valid ("\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[\+\-]\d{2}:\d{2})": unrecognised compile-time option bit(s)).
[ERR] Internal error (/usr/src/debug/libyang/2.0.164-1/git/src/tree_schema.c:1154).
sysrepocfg error: Failed to connect (libyang error)
For more details you may try to increase the verbosity up to "-v3".

**Comment by michalvasko** [comment]
Duplicate of sysrepo/sysrepo#2841.
