### ISSUE TITLE
Error when loading Cisco-IOS-XE-native.yang

### ISSUE THREAD

**Issue by rabhat31** [CESNET/libyang#1876]
Run into an error when loading Cisco-IOS-XE-native on yanglint v2.0.194. 
Loading module from here:
https://github.com/YangModels/yang/tree/main/vendor/cisco/xe/1781

Here is the output of loading the model:

libyang[1]: Argument #1 of xpath_contains is node "name", not of string-type.
…
libyang[1]: Argument #1 of xpath_contains is node "name", not of string-type.
libyang[1]: Argument #2 of xpath_concat is node "name", not of string-type.
libyang[1]: Argument #2 of xpath_concat is node "name", not of string-type.
libyang[1]: Schema node "name" for parent "/Cisco-IOS-XE-native:native/interface/ATM-subinterface" not found; in expr "/ios:native/ios:interface/*[concat(local-name(.), ios:name" with context node "/Cisco-IOS-XE-native:native/interface/vmi/physical-interface".
libyang[1]: Schema node "name" for parent "/Cisco-IOS-XE-native:native/interface/ATM-ACRsubinterface" not found; in expr "/ios:native/ios:interface/*[concat(local-name(.), ios:name" with context node "/Cisco-IOS-XE-native:native/interface/vmi/physical-interface".
libyang[1]: Argument #2 of xpath_concat is node "name", not of string-type.
libyang[1]: Argument #2 of xpath_concat is node "name", not of string-type.
libyang[1]: Argument #2 of xpath_concat is node "name", not of string-type.
libyang[1]: Schema node "name" for parent "/Cisco-IOS-XE-native:native/interface/L2LISP-subinterface" not found; in expr "/ios:native/ios:interface/*[concat(local-name(.), ios:name" with context node "/Cisco-IOS-XE-native:native/interface/vmi/physical-interface".
libyang[1]: Argument #2 of xpath_concat is node "name", not of string-type.
libyang[1]: Schema node "name" for parent "/Cisco-IOS-XE-native:native/interface/LISP-subinterface" not found; in expr "/ios:native/ios:interface/*[concat(local-name(.), ios:name" with context node "/Cisco-IOS-XE-native:native/interface/vmi/physical-interface".
libyang[1]: Argument #2 of xpath_concat is node "name", not of string-type.
libyang[1]: Argument #2 of xpath_concat is node "name", not of string-type.
libyang[1]: Argument #2 of xpath_concat is node "name", not of string-type.
libyang[1]: Schema node "name" for parent "/Cisco-IOS-XE-native:native/interface/Port-channel-subinterface" not found; in expr "/ios:native/ios:interface/*[concat(local-name(.), ios:name" with context node "/Cisco-IOS-XE-native:native/interface/vmi/physical-interface".
libyang[1]: Argument #2 of xpath_concat is node "name", not of string-type.
libyang[1]: Argument #2 of xpath_concat is node "name", not of string-type.
libyang[1]: Argument #2 of xpath_concat is node "name", not of string-type.
libyang[1]: Argument #2 of xpath_concat is node "name", not of string-type.
libyang[1]: Argument #2 of xpath_concat is node "name", not of string-type.
libyang[1]: Argument #2 of xpath_concat is node "name", not of string-type.
libyang[1]: Argument #2 of xpath_concat is node "name", not of string-type.
libyang[1]: Argument #2 of xpath_concat is node "name", not of string-type.
libyang[1]: Argument #2 of xpath_concat is node "name", not of string-type.
libyang[1]: Argument #2 of xpath_concat is node "name", not of string-type.
libyang[1]: Argument #2 of xpath_concat is node "name", not of string-type.
libyang[1]: Argument #2 of xpath_concat is node "name", not of string-type.
libyang[1]: Argument #2 of xpath_concat is node "name", not of string-type.
libyang[1]: Argument #2 of xpath_concat is node "name", not of string-type.
libyang[1]: Argument #2 of xpath_concat is node "name", not of string-type.
libyang[1]: Schema node "name" for parent "/Cisco-IOS-XE-native:native/interface/Serial-subinterface" not found; in expr "/ios:native/ios:interface/*[concat(local-name(.), ios:name" with context node "/Cisco-IOS-XE-native:native/interface/vmi/physical-interface".
libyang[1]: Schema node "name" for parent "/Cisco-IOS-XE-native:native/interface/MFR-subinterface" not found; in expr "/ios:native/ios:interface/*[concat(local-name(.), ios:name" with context node "/Cisco-IOS-XE-native:native/interface/vmi/physical-interface".
libyang[0]: A current definition "physical-interface" is not allowed to reference obsolete definition "TwentyFiveGigabitEthernet". (path: Schema location /Cisco-IOS-XE-native:native/interface/vmi/physical-interface.)

**Comment by michalvasko** [comment]
Right, it was a false-positive and now it should only be a warning and the YANG successfully loaded.
