### ISSUE TITLE
fail to retrieve leafref target consistently

### ISSUE THREAD

**Issue by Haititi** [CESNET/libyang#1888]
Hi :)

```
module test-base {
  yang-version 1.1;
  namespace "urn:test:test-base";
  prefix "test-base";

  container router {
    description "router container.";
  }
}
```
```
module test-augment {
  yang-version 1.1;
  namespace "urn:test:test-augment";
  prefix "aug";

  import test-base {
    prefix base;
  }

  augment /base:router {
    container leafref {
      description "Test leafref.";

      list interface {
        description "Interface list.";
        key "name";
        leaf name {
          description "Name of the interface.";
          type string;
        }
      }

      leaf test-leafref-iface {
        description "Select an interface.";
        type leafref {
          path "../interface/name";
        }
      }

      leaf test-leafref-iface2 {
	description "Select an interface.";
	type leafref {
	  path "/base:router/aug:leafref/interface/name";
	}
      }

    }
  }
}
```

I try to find how should i retrieve every leafref target in my code.
```
struct lysc_type_leafref * lref = /* ... */;
struct lyxp_expr * path = lref->path;
const char *xpath = lyxp_get_expr(path);
const struct lysc_node* target;

// OPTION 1:
target = lys_find_path(NULL, snode, xpath, 0);
if (!target) {
    goto fail;
}

// OPTION 2:
struct ly_set *set = NULL;
if (lys_find_xpath(NULL, snode, xpath, 0, &set) != LY_SUCCESS || set->count != 1) {
    ly_set_free(set, NULL);
    goto fail;
}
target = set->snodes[0];
ly_set_free(set, NULL);
```
depending on the option used, i have different problems occuring.

- Using Option 1
As mentioned in [issue #1877](https://github.com/CESNET/libyang/issues/1877#issuecomment-1192653774), this API does not work with the target path `"../interface/name"`, due to the usage of `ly_path_compile()` internally which does not handle the ddots `".."` part in the path. There actually is another API `ly_path_compile_leafref()` which handle it, but it's not used here.
 
- Using Option 2
Here, the path `"../interface/name"` is correctly resolved by `lys_find_xpath()`.
But when the path is `"/base:router/aug:leafref/interface/name"`, it fails with the following error:
> Unknown/non-implemented module "base".
I guess this is due because `lys_find_xpath()` doesnt know that `"base"` is the prefix of `"test-base"` module.

IMHO, I think there is three good ways to fix that.
- The first one would be during the nodes compilation, by making Libyang resolve the modules prefix in the leafref path. once resolved, the `struct lyxp_expr * path` in `struct lysc_type_leafref` would contains the modules name instead of their prefix, hence allowing us to use `lys_find_xpath()` correctly.
- The second one would be to update `lys_find_path()` to check if the node is a leafref, and to call `ly_path_compile_leafref()` instead of `ly_path_compile()` in this case.
- The third one would be a new API (for example `lys_find_leafref_target()`) which would be similar to `lys_find_path()` but would call `ly_path_compile_leafref()` instead.

any opinion about this ?
Thanks in advance for your help :)

**Comment by michalvasko** [comment]
Actually, you should be able to use `lys_find_expr_atoms()`, just take the last node in the set.

**Comment by Haititi** [comment]
`lys_find_expr_atoms()` could have been helpful if i knew about the compiled prefixes data.
But here i have no clue, i just try to retrieve a leafref target in a generic way.

**Comment by michalvasko** [comment]
The prefixes are stored in `lysc_type_leafref`.

**Comment by Haititi** [comment]
Perfect, i didn't realize it was there!
`lys_find_expr_atoms()` did the trick, so i guess it's the way to go!
Thank you very much!
