### ISSUE TITLE
question regarding compiled derived types

### ISSUE THREAD

**Issue by Haititi** [CESNET/libyang#1893]
Hi,
```
typedef myderived {
    type mybase;
}
```

Suppose `mybase` has a description and some extensions.
In libyang1, when doing this simple `typedef`, i had to go through the derived type to retrieve them.
In libyang2, there is no more derived type. does that mean the `lysc_type` for `myderived` inherits the description and these extensions? all data of the derived types can be found directly in the `lysc_type` for `myderived`?

I hope my question is understandable :)

**Comment by michalvasko** [comment]
I understand what you are asking and yes, the type is fully compiled into a single type. But note that only the required fields are compiled (`struct lysc_type`). Description, for instance, is not among them.

**Comment by Haititi** [comment]
yes, you are right, the description is not in the lysc_type.
any advice as to how to retrieve the last defined description in an inheritance tree?
for the moment, i do something like this :

```
const char * get_description(const struct lysc_type *type)
{
    const char *name = NULL;
    struct lysp_tpdf *tpdfs = type->exts->module->parsed->typedefs;

    while (type || name) {
        LY_ARRAY_COUNT_TYPE ii;
        struct lysp_tpdf *tpdf = NULL;

        LY_ARRAY_FOR(tpdfs, ii) {
            if (type && tpdfs[ii].type.compiled == type ||
                        name && strcmp(name, tpdfs[ii].name) == 0) {
                tpdf = tpdfs + ii;
                break;
            }
        }
        if (!tpdf) return NULL;
        if (tpdf->dsc) return tpdf->dsc;
        name = tpdf->type.name;
        type = NULL;
    }
    return NULL;
}
```
Is there any other way ? if not, is my solution valid ?
Thanks for your help.

**Comment by michalvasko** [comment]
Something along these lines will be required, there is not a better way. Whether this is correct I cannot say, for some reason you expect all the types to have an extension so your use-case must be specific.
```C
struct lysp_tpdf *tpdfs = type->exts->module->parsed->typedefs;
```

**Comment by Haititi** [comment]
well, is there any other way to retrieve the `typedefs` while having a `lysc_type` ? it would help haha

**Comment by michalvasko** [comment]
It is up to you to find some complicated way, whatever works for you. This use-case is not really supported, the compiled modules are meant to enable working with YANG data, you do not need description and other type information for that.

**Comment by Haititi** [comment]
thanks for your help! I'm closing this issue.
