### ISSUE TITLE
Missing installation of plugin directory?

### ISSUE THREAD

**Issue by nicolasmorini** [CESNET/libyang#1894]
While working on updating from `libyang v1.x` to `libyang v2.x`, I noticed the following:

- `PLUGINS_DIR` (along with `PLUGINS_DIR_EXTENSIONS` and `PLUGINS_DIR_TYPES`) paths are set, but never used ([here](https://github.com/CESNET/libyang/blob/master/CMakeLists.txt#L255)).
- after compiling and installing the latest `libyang`, I do not find the `/usr/local/lib64/libyang` directory containing the plugins

I am not familiar with these plugins (and I am not using them explicitly), but it seems to me that some `install()` statement is missing in the `CMakeList.txt`. Is this a bug?

**Comment by michalvasko** [comment]
There are no external plugins by default in *libyang* v2, they are all internal and linked directly into the library.

**Comment by nicolasmorini** [comment]
Thanks for the quick reply @michalvasko
