### ISSUE TITLE
Extension plugin validation callback not usable without nested nodes

### ISSUE THREAD

**Issue by Haititi** [CESNET/libyang#1908]
Hi,

trying to migrate my extensions plugins from libyang1 to libyang2, I stuck on how to validate a data node defined by the actual schema node where the extension is actually used.
I try to give a simple (but unreal) use case :
```
container my-pipe {
    my-ns:unique-values "in | out";

    leaf in {
        type uint32;
    }
    leaf out {
        type uint32;
    }
}
```

With libyang1, the `lyext_valid_data_clb valid_data` callback was called on the actual `my-pipe` data node so i could easily define some validation mechanism related to my extension there (for example, checking that the two leaves `in` and `out` have different values).

With libyang2, it seems that there is no way to get some callback called when validating my data node where my extension is used.
The `lyplg_ext_data_validate_clb validate` callback would be called only for nested data, which is not usable here.

My example might be too simple, but it's just a way to explain the problem.
Isn't the new implementation of these Extensions Plugins a bit limited here ?
Or maybe there is another way to implement this?

Thanks for your help!

**Comment by michalvasko** [comment]
Extensions are improved strictly only when needed because there are unlimited possibilities on what an extension may want to do and we had no use-case for this simple data node validation. Added.

**Comment by Haititi** [comment]
Amazing, thank you for reacting so quickly!

I just tried with the new version, but there is still a problem in my use case.
As i'm implementing a cli to generate the nodes, i have a _validate_ command which calls `lyd_validate_all()`.
In this case, the callback is not called.

From what i see, shouldn't the function `lyd_validate_subtree()` also get the `struct ly_set *ext_node_p` as a parameter in order to update the set?

**Comment by michalvasko** [comment]
Right, should be fixed with some more minor improvements.

**Comment by Haititi** [comment]
It seems it's working fine now, thank you very much for your help!
