### ISSUE TITLE
lyd_new_path() leaflist creation fails when path has predicate

### ISSUE THREAD

**Issue by Haititi** [CESNET/libyang#1909]
Hi,

```
const struct ly_ctx *ctx = /* ... */;
struct lyd_node *parent = /* ... */;
const char *path = /logging:show-log/logging:level/equal[.='warning']";

lyd_new_path(parent, ctx, path, NULL, LYD_NEW_PATH_UPDATE, NULL);
```

I get the following error :
> ERROR: Schema location "/logging:show-log/input/level/equal".:
> Invalid predicate for leaf-list "equal" in path "/logging:show-log/logging:level/equal[.='warning']".

the error is triggered from `lyd_new_path_check_find_lypath()` where `lysc_is_dup_inst_list(schema) == true` and `path[u].pred_type != LY_PATH_PREDTYPE_POSITION`, as our actual `pred_type` is `LY_PATH_PREDTYPE_LEAFLIST`.

It seems we can't use predicates here, while the documentation for `lyd_new_path()` says that we can :

> If `path` points to a list key, the key value from the predicate is used and `value` is ignored. Also, if a leaf-list is being created and both a predicate is defined in `path` and `value` is set, the predicate is preferred.

Is it a bug in the code, or an error in the doc, or maybe i'm misunderstanding something?
Thanks for your help.

**Comment by michalvasko** [comment]
It is intentional, you have not finished reading
```
For key-less lists and non-configuration leaf-lists, positional predicates should be used. If no predicate is used
for these nodes, they are always created.
```
You must specify the position and put the value into the separate argument.

**Comment by Haititi** [comment]
All good, thank you !
