### ISSUE TITLE
With latest libyang,netopeer2,sysrepo finding installation failures.

### ISSUE THREAD

**Issue by vinayhb012114** [CESNET/libyang#1910]
@michalvasko  With latest version of libyang,netopeer2,sysrepo, some of the yangs installation fails.(.i.e sysrepoctl -i  o-ran-processing-element.yang fails)
It gives following error:
ERR] Not found node "diffserv-markings" in path. (Schema location "/o-ran-processing-element:processing-elements/enhanced-uplane-mapping/uplane-mapping/up-markings/ipv4/upv4-dscp-name".)
[ERR] Target of leafref "upv4-dscp-name" cannot be referenced because it is disabled. (Schema location "/o-ran-processing-element:processing-elements/enhanced-uplane-mapping/uplane-mapping/up-markings/ipv4/upv4-dscp-name".)
sysrepoctl error: Failed to install module "/home/vinayhb/ps/yang_models/o-ran-beamforming.yang" (libyang error)

Looks like some links broken between following yangs--->o-ran-interfaces.yang.yang   o-ran-processing-element.yang ietf-interfaces.yang

So what is the reason for above installation failure???

**Comment by michalvasko** [comment]
It prints the problem exactly, a leafref target is disabled (its `if-feature` false). It means they have a dependency on different set of features, which is forbidden ([ref](https://www.rfc-editor.org/rfc/rfc7950.html#section-9.9), last paragraph).

**Comment by chendrashekarp** [comment]
Hi @michalvasko  , But this issue we are getting with new  library release branch versions only ? Any updates in new version related to these checks ?

**Comment by michalvasko** [comment]
Depends from which version were you updating but it seems there were some changes in this. There may, of course, be a bug causing this but first make sure the leafref target really is enabled.

**Comment by chendrashekarp** [comment]
@michalvasko  , so this applies to yang installation too or while configuring ?

**Comment by michalvasko** [comment]
It would cause problems when configuring data but it is detected when installing the YANG.

**Comment by vinayhb012114** [comment]
Thanks @michalvasko 
issue resolved.

**Comment by bmiabraham** [comment]
hi @vinayhb012114, how did you resolve the issue? did you just used a specific library version?

**Comment by michalvasko** [comment]
Um, no, there is no other way. And because of that fact the module is invalid, in addition to the explicitly broken requirement from the RFC about leafrefs and their targets.

**Comment by bam44555** [comment]
Thanks
