### ISSUE TITLE
Changes in the usermangemt in latest libyang.

### ISSUE THREAD

**Issue by vinayhb012114** [CESNET/libyang#1912]
@michalvasko: Is there any updation in the user management yang in the latest libyang.
Because I am facing installation issue.
We are trying to configure one user as it is mandatory but we are getting error as shown below:
![image](https://user-images.githubusercontent.com/104129749/186856423-7aa24fa9-af09-4f6c-9f25-69d654ac8ead.png)

But prefix and name space is given same as yang.
Can you please help me here?

**Comment by michalvasko** [comment]
What is the whole command you are executing? Make sure the module is implemented and namespaces match.

**Comment by vinayhb012114** [comment]
@michalvasko :
1) What is the whole command you are executing?
Below is the command which I used.
sysrepocfg -C o-ran-user.xml -m o-ran-usermgmt --datastore running -f "xml

2)Make sure the module is implemented and namespaces match.------> You mean whether that has installed??
here we have problem if we try install it asks us to enable at least one user account.

**Comment by michalvasko** [comment]
> if we try install it asks us to enable at least one user account.

Use the `sysrepoctl` `--init-data <path>` parameter (details in help `sysrepoctl -h`) to set any top-level mandatory data.

**Comment by vinayhb012114** [comment]
@michalvasko issue resolved.
Thanks a lot for your inputs.
