### ISSUE TITLE
libyang err : Invalid identityref

### ISSUE THREAD

**Issue by mjethanandani** [CESNET/libyang#1914]
In trying to validate a simple configuration with yanglint, I am running into this error:
```
$ yanglint --version
yanglint 2.0.243
$ yanglint -ii -t config iana-if-type@2020-01-10.yang ietf-interfaces@2018-02-20.yang example.xml
libyang err : Invalid identityref "
    xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:softwareLoopback" value - unable to map prefix to YANG schema. (Schema location "/ietf-interfaces:interfaces/interface/type", data location "/ietf-interfaces:interface[name='loopback0']", line number 7.)
YANGLINT[E]: Failed to parse input data file "example.xml".
```
The only thing I can think of is that softwareLoopback is of type ianaift:iana-interface-type, which itself is of type if:interface-type.

Please find attached the required files to reproduce the problem. The command used to reproduce the problem is shown above.

[example.tar.gz](https://github.com/CESNET/libyang/files/9447428/example.tar.gz)

**Comment by michalvasko** [comment]
The error may be a bit confusing but only because your XML is. The actual value of the identityref is `\n    xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:softwareLoopback` which is obviously wrong. Just fix your XML (it is not a well-formatted XML) and it will work, the `type` element should only have a text child.

**Comment by mjethanandani** [comment]
Thanks @michalvasko. That does seem to fix the problem. Do not know what the difference is between this and the following line is, where it did not complain about the first and not the second. Either ways, I got ride of the newline.
```
<interfaces 
  xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
```

and

```
<type
  xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type>ianaift:softwareLoopback</type>
```

**Comment by michalvasko** [comment]
Both are fine, in your XML you have
```xml
<type>
    xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:softwareLoopback</type>
```

**Comment by michalvasko** [comment]
Both are fine, in your XML you have
```xml
<type>
    xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:softwareLoopback</type>
```
