### ISSUE TITLE
Error: augment target node was not found

### ISSUE THREAD

**Issue by minhix** [CESNET/libyang#1916]
Hi!
I am trying to fix a problem that seems like a bug in Yanglint. Please help!

So I have a base model:
```
module base {
  namespace "urn:base";
  prefix "base";

  // Fields contact, description, revision, etc. are not shown
 
  container c {
    description "The container";
    leaf id {
      type uint8;
      description "Index";
    }

    leaf temp {
      type uint8;
      description "A temporary thing";
    }
  }
}
```

I then try to modify the base model
```
module mods {
  namespace "urn:mods";
  prefix "m";

  // Fields contact, description, revision, etc. are not shown

  import base {
    prefix b;
  }

  augment "/b:c/b:temp"
  {
    when "/base:c/base:id = 1";
    description "Enable temp only when ID=1";
  }
}
```

Although pyang can show the tree:
```
pyang -f tree base.yang mods.yang
mods.yang:13: error: node base::temp of type leaf cannot be augmented
module: base
  +--rw c
     +--rw id?     uint8
     +--rw temp?   uint8

```
Yanglint shows the leaf
```
> add base.yang 
> print -f info -P /base:c/base:temp
leaf temp {
  type uint8;
  config true;
  status current;
  description
    "A temporary thing";
}
```
But Yanglint shows error
```
> add mods.yang 
libyang[0]: Augment target node "/b:c/b:temp" from module "mods" was not found. (path: /mods:{augment='/b:c/b:temp'})
```

I checked out the Yang RFC (https://datatracker.ietf.org/doc/html/rfc6020), to my best knowledge, Yang models should be fine.

What is the problem here? Is it a bug?

Version: yanglint 2.0.231

**Comment by michalvasko** [comment]
And you just ignore `pyang` error
```
mods.yang:13: error: node base::temp of type leaf cannot be augmented
```
which is just a more specific message with the root cause being the same in `yanglint` as well, `augment` target node **cannot** be a leaf.

**Comment by minhix** [comment]
Thanks a lot for your answer!

Yes, I overlooked that detail. Source: https://datatracker.ietf.org/doc/html/rfc6020

> This node is called the augment's target node.  The
   target node MUST be either a container, list, choice, case, input,
   output, or notification node.  It is augmented with the nodes defined
   in the substatements that follow the "augment" statement.
