### ISSUE TITLE
if node name is hash conflict,  if will be lost when get dat

### ISSUE THREAD

**Issue by billykinggym** [CESNET/libyang#1917]
in lyb_parse_schema_hash, only search for hash. if 2 shema name 's hash is same, the last one will be lost .
create schema and data like below:
[examples_yang_and_data_with_hash_conflict.zip](https://github.com/CESNET/libyang/files/9474153/examples_yang_and_data_with_hash_conflict.zip)

when we do sysrepocfg -X  -m examples.  we will get:
```
...... ommit sth.
  <counter9098>16048</counter9098>
  <counter1525>16049</counter1525>     // wrong this line
  <counter16050>16050</counter16050>
</stats>
```
it is wrong for    **<counter1525>16049</counter1525>** , it should be    **<counter16049>16049</counter16049>**.
many schema is lost because of conflict.
and  "sr_get_items /examples:stats/counter16049 running"  will return nothing
 "sr_get_items /examples:stats/counter1525 running"   will return correct data.

it is very urgent issue, that once hash conflict happend, data must be wrong.
could someone help on this?  :(

and i try libyang1, it is no such issue.

**Comment by billykinggym** [comment]
```
static LY_ERR
lyb_parse_schema_hash(struct lyd_lyb_ctx *lybctx, const struct lysc_node *sparent, const struct lys_module *mod,
        const struct lysc_node **snode)
{
   .........
    while (1) {
        if (!sparent && lybctx->ext) {
            sibling = lys_getnext_ext(sibling, sparent, lybctx->ext, getnext_opts);
        } else {
             // always find from beginning
            sibling = lys_getnext(sibling, sparent, mod ? mod->compiled : NULL, getnext_opts);
        }
        if (!sibling) {
            break;
        }
       //when first hash matched, then return,  but currently, maybe we need second or third hash
        if (((sibling->module->ctx != lybctx->lybctx->ctx) || lyb_has_schema_model(sibling, lybctx->lybctx->models)) &&
                lyb_is_schema_hash_match((struct lysc_node *)sibling, hash, hash_count)) {
            /* match found */
            break;
        }
    }
```

**Comment by michalvasko** [comment]
Right, thanks for reporting this because there was quite a serious problem when not all the collisions were being checked leading to wrong hashes being written. It should work correctly now, with a test added.

**Comment by billykinggym** [comment]
@michalvasko   thanks for you quick response.  May I ask that when it could be merge to master and release?

**Comment by michalvasko** [comment]
Not sure, there is no specific plan. But I would guess at most in a month.
