### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by iraponomareva** [CESNET/libyang#1923]
Building C object tests/utests/CMakeFiles/utest_uint8.dir/types/uint8.c.o
In file included from /home/ira/libyang/tests/utests/types/../utests.h:26,
                 from /home/ira/libyang/tests/utests/types/uint8.c:17:
/usr/include/cmocka.h:2209:42: error: unknown type name ‘uintmax_t’
 2209 | typedef int (*CheckParameterValue)(const uintmax_t value,
...
/usr/include/cmocka.h:2486:32: error: unknown type name ‘uint32_t’
 2486 | void cmocka_set_message_output(uint32_t output);
      |                                ^~~~~~~~
make[2]: *** [tests/utests/CMakeFiles/utest_uint8.dir/build.make:76: tests/utests/CMakeFiles/utest_uint8.dir/types/uint8.c.o] Ошибка 1
make[1]: *** [CMakeFiles/Makefile2:523: tests/utests/CMakeFiles/utest_uint8.dir/all] Ошибка 2
make: *** [Makefile:146: all] Ошибка 2
Can you help me please?

**Comment by michalvasko** [comment]
What *libyang* version are you trying to compile?

**Comment by iraponomareva** [comment]
last version, clone from hear git clone https://github.com/CESNET/libyang.git

**Comment by michalvasko** [comment]
I see, what distribution are you on exactly? Maybe also include `gcc` and `cmocka` version.

**Comment by iraponomareva** [comment]
gcc 9.4.0
cmocka from hear https://github.com/clibs/cmocka.git

**Comment by iraponomareva** [comment]
udate cmake it`s help

**Comment by michalvasko** [comment]
Okay, the header is really missing there in the `master` branch. So please use the `devel` branch of *libyang* for now, it should get merged soon.
