### ISSUE TITLE
Error messages are unhelpful

### ISSUE THREAD

**Issue by Skepfyr** [CESNET/libyang#1930]
I'm getting an error message (in 2.0.164) that looks like:
> Invalid non-boolean-encoded boolean value "falsey". (path: Schema location /solutionconfig_v1:profiles/cvt_events/sending_enabled, data location /solutionconfig_v1:cvt_events, line number 1., tag: none

I don't understand the distinction between schema location and data location, however `profiles` is a list and this error doesn't indicate which element is causing the problem. It would be useful if it included the id element of the list so that it was simpler to locate the issue.

The line number should help for this but unfortunately the input in this case has had all newlines removed (it's JSON) which makes that irrelevant for us.

**Comment by michalvasko** [comment]
Okay, the latest version should print correct data paths.

**Comment by Skepfyr** [comment]
I've tested this and it's much better, thank you!
