### ISSUE TITLE
Confusing error message for incorrect JSON list

### ISSUE THREAD

**Issue by Skepfyr** [CESNET/libyang#1932]
If you provide a list as a JSON value where the schema is expecting a value then you get an error like:

> libyang[0]: Expected JSON name/[null], but input data contains name/string. (path: Data location "/schema_v1:foo", line number 1.)

from data like:
```json
"foo": {
  "bar": ["test"]
}
```

This is generated by this line: https://github.com/CESNET/libyang/blob/aee5fe365b8c6c4b79d634391bacbc736c2c31da/src/parser_json.c#L455-L456

This error is confusing because it says it expected `[null]` where the schema actually expected `string`, which is due to that bit of code knowing that the schema is expecting a value but not which type exactly. The data location is also `foo` rather than `bar`.

The best error message would look something like:
> libyang[0]: Expected JSON string, but input data contains a list of string. (path: Data location "/schema_v1:foo/bar", line number 1.)

I had a look at fixing this but got stumped by the partial knowledge of what the schema expected.

**Comment by michalvasko** [comment]
Okay, I did what I could to improve it but the exact expected data type is not really known when the message is being printed, just that it must fir the value of a leaf/leaf-list.

**Comment by Skepfyr** [comment]
That looks way better, thank you so much!
