### ISSUE TITLE
Assertion error: ly_dup_prefix_data: Assertion `!*prefix_data_p' failed

### ISSUE THREAD

**Issue by sampo-0** [CESNET/libyang#1937]
Hi,

I'm getting an assertion error when using these yang models: https://github.com/Huawei/yang/tree/0f50bc6f7ee0c7bd56f5bf9412ae0375d99eca24/network-router/8.21.0/ne40e-x8x16 (current master-branch) and loading huawei-mplsoam model.

```
$ yanglint --version && yanglint huawei-mplsoam.yang
yanglint 2.1.5
yanglint: /opt/CESNET/libyang/src/tree_data_common.c:1223: ly_dup_prefix_data: Assertion `!*prefix_data_p' failed.
zsh: abort (core dumped)  yanglint huawei-mplsoam.yang
```

**Comment by michalvasko** [comment]
Right, should work in the latest 2.1.6 in `devel`.

**Comment by sampo-0** [comment]
Thank you for a fix. This is working now.
