### ISSUE TITLE
Incorrect XPath processing

### ISSUE THREAD

**Issue by rwestphal** [CESNET/libyang#1938]
While upgrading yang2-rs to use the latest libyang version, I found what seems to be a regression in the `lys_find_xpath()` function. One unit test started failing and I had to make the following modification to make it pass: https://github.com/rwestphal/yang2-rs/commit/a368323d8b9e91d6eeae541de54d610a6631b3bc#diff-06218357fa16f0118e4acfe593e1e0ce4f889ac294bb0d34012a08c7743edbc5

My understanding is that searching for `/ietf-interfaces:interfaces/*` shouldn't return `/ietf-interfaces:interfaces-state` since `interfaces` and `interfaces-state` are different lists. What do you think?

**Comment by michalvasko** [comment]
Yes, a problem in the XPath, should be fixed.
