### ISSUE TITLE
libyang[0]: Invalid value problen

### ISSUE THREAD

**Issue by sourcema** [CESNET/libyang#1939]
Hello, this node failed to parse when I was getting the notification message.

this is yang module :
```yang
list epe-measurement-result {
  key "object-unit-id";
  config false;
  leaf object-unit-id {
	type leafref {
	  path "/hw:hardware/hw:component/hw:class";
	}
	description
	  "the hardware component type is used for the object-unit-id for the
	   EPE measurements. For example, the object-unit-id will be set to
	   or-hw:O-RAN-RADIO if the measurement applies to the complete O-RU
	   self-contained sub-system.
	   Other hardware-classes include: or-hw:O-RU-POWER-AMPLIFIER,
	   ianahw:power-supply, ianahw:fan, ianahw:cpu";
  }
  leaf min {
	type decimal64 {
	  fraction-digits 4;
	}
	description
	  "minimum value for the measurment-object";
  }
  leaf max {
	type decimal64 {
	  fraction-digits 4;
	}
	description
	  "maximum value for the measurment-object";
  }
  leaf average {
	type decimal64 {
	  fraction-digits 4;
	}
	description
	  "average value of the measurement-object";
  }
}
```
this is my notification message,:
```xml
<epe-stats>
    <start-time>2022-11-13T01:03:14Z</start-time>
    <end-time>2022-11-13T01:03:14Z</end-time>
    <epe-measurement-result>
      <object-unit-id>o-ran-hw:O-RAN-RADIO</object-unit-id>
      <min>27.46</min>
      <max>27.54</max>
      <average>8666</average>
    </epe-measurement-result>
  </epe-stats>
```
libyang parse error:
```
libyang[0]: Invalid value "o-ran-hw:O-RAN-RADIO" in "object-unit-id" element. (path: /o-ran-performance-management:measurement-result-stats/epe-stats/epe-measurement-result[object-unit-id='o-ran-hw:O-RAN-RADIO']/object-unit-id)
```

**Comment by michalvasko** [comment]
You have used XML prefix `o-ran-hw` but not defined it anywhere. If you do, it should work.

**Comment by sourcema** [comment]
> You have used XML prefix `o-ran-hw` but not defined it anywhere. If you do, it should work.

import o-ran-hardware {
    prefix "o-ran-hw";
  }
I have imported this module in the yang file, but the file is too big, not all posted,  need to post all？

**Comment by michalvasko** [comment]
You do not understand, there is **YANG prefix** and there are **XML prefixes**, something quite different. Hopefully, if I just post the correct XML, you will understand.
```xml
  <epe-stats>
    <start-time>2022-11-13T01:03:14Z</start-time>
    <end-time>2022-11-13T01:03:14Z</end-time>
    <epe-measurement-result>
      <object-unit-id xmlns:o-ran-hw="urn:o-ran:hardware:1.0">o-ran-hw:O-RAN-RADIO</object-unit-id>
      <min>27.46</min>
      <max>27.54</max>
      <average>8666</average>
    </epe-measurement-result>
  </epe-stats>

**Comment by sourcema** [comment]
> 
I've tried this method before and it still parse error, i wondering if other problems are causing it.

**Comment by sourcema** [comment]
> You do not understand, there is **YANG prefix** and there are **XML prefixes**, something quite different. Hopefully, if I just post the correct XML, you will understand.
> 
> ```
>   <epe-stats>
>     <start-time>2022-11-13T01:03:14Z</start-time>
>     <end-time>2022-11-13T01:03:14Z</end-time>
>     <epe-measurement-result>
>       <object-unit-id xmlns:o-ran-hw="urn:o-ran:hardware:1.0">o-ran-hw:O-RAN-RADIO</object-unit-id>
>       <min>27.46</min>
>       <max>27.54</max>
>       <average>8666</average>
>     </epe-measurement-result>
>   </epe-stats>
> ```


I've tried this method before and it still parse error, i wondering if other problems are causing it.

**Comment by michalvasko** [comment]
The error is the same, no more details? What *libyang* version are you using?

**Comment by sourcema** [comment]
> The error is the same, no more details? What _libyang_ version are you using?
same error，libyang 1.0.109.

**Comment by sourcema** [comment]
> > The error is the same, no more details? What _libyang_ version are you using?
> > same error，libyang 1.0.109.

**Comment by michalvasko** [comment]
Okay, that is a really old version so I do not think I can help you, it is no longer supported.

**Comment by sourcema** [comment]
> Okay, that is a really old version so I do not think I can help you, it is no longer supported.

/(ㄒoㄒ)/~~I'll see if I can update to the new version
