### ISSUE TITLE
LY_TREE_DFS_BEGIN and LY_TREE_DFS_END can't find grouping node outside rpc node

### ISSUE THREAD

**Issue by yanjunxi** [CESNET/libyang#194]
Use test_err.yang, it doesn't deal rpc nodes, while use test_ok.yang will deal all nodes.
Use LY_TREE_DFS_BEGIN macro, after deal the leaf fb, it can't get the next node which is rpc's child.

[issue.txt](https://github.com/CESNET/libyang/files/588733/issue.txt)

**Comment by rkrejci** [comment]
The 'LY_TREE_DFS_BEGIN` works as described in its description - the `start` node is the root and these macros does not process the `start`s siblings. To do so, you have to cover the `LY_TREE_DFS_` with `LY_TREE_FOR` macro.
