### ISSUE TITLE
crash when parsing xpath list key with sub-brackets in value  

### ISSUE THREAD

**Issue by Haititi** [CESNET/libyang#1940]
Hi,

After updating to libyang 2.0.267 we started to experience some crashes in our program.
After some research, the crash started to appear with the following commit: https://github.com/CESNET/libyang/commit/d59039d4466fb7c72f523af59d10f58ba3eb4d74 .

I analyzed this commit and it seems to be genuine, so i guess there was a "lucky" side effect to the previous erroneous code that made everything work before, but now that the commit is included, this side effect is gone, which make our code fails.

By deepening the analysis, i found the problem in `eval_name_test_try_compile_predicates()` at the following location: https://github.com/CESNET/libyang/blob/devel/src/xpath.c#L7756 .

When having an xpath similar to `/mod:name1/mod:name2[mod:keyname1=string(/mod:name1/mod:name3[mod:keyname2='foo']/mod:keyname2)]/mod:keyname1`, the parsing stops on early closing bracket, and the value parsed becomes `string(/mod:name1/mod:name3[mod:keyname2='foo'` instead of `string(/mod:name1/mod:name3[mod:keyname2='foo']/mod:keyname2)` .

I didn't check if the problem occurs with leaflists too, but it seems the case.

**Comment by michalvasko** [comment]
Nested predicates were simply not accounted for, should now be fixed. Also, not sure what analysis you did exactly but having a debug build, there was a failed assert that pointed to the problem immediately. Your use-case included in the tests as well.

**Comment by Haititi** [comment]
I was actually preparing a PR for you, but you solved it before i could push my code :)
my solution was similar to yours at first, but then i realized a problem, which your code also have.
in case we find the last `LYXP_TOKEN_BRACK2` token, we should not increment the `e_idx` variable.

i ended up adding `if (!nested_pred) break;` after decrementing `nested_pred` when finding the `LYXP_TOKEN_BRACK2` token.
Can you check that ?
thanks a lot!

**Comment by michalvasko** [comment]
I have included your use-case, which works fine so I am not sure what else to check. On line `xpath.c:7775` there is `e_idx - 1` so I think it is fine.

**Comment by Haititi** [comment]
If you look at the previous code, `e_idx` was incremented only when the token was not found.
So the `e_idx - 1` was referring to the last token before the closing bracket.

With the new code, `e_idx` is incremented twice on the first loop (once before the loop, and once when entering the loop), so you are actually skipping a token.

That's why, on my solution, i was incrementing only at the end of the loop, and i was adding a `break` when finding the last `LYXP_TOKEN_BRACK2` token to avoid incrementing again.

to fix your solution you should update the code just before the loop:
```
            // ++e_idx;       // <-- to remove

            /* value start */
            val_start_idx = e_idx + 1;   // +1 to set the correct value.
```


Moreover, shouldn't you also apply this fix to leaflists here ?
https://github.com/CESNET/libyang/blob/devel/src/xpath.c#L7811

**Comment by michalvasko** [comment]
> With the new code, e_idx is incremented twice on the first loop (once before the loop, and once when entering the loop), so you are actually skipping a token.

Yes, which means I do not consider an expression in the format `[key=]`. But such an expression is not syntactically valid and hence cannot appear in this function.

Other than that, the loop ends when `e_idx` equals the `LYXP_TOKEN_BRACK2` token, which was true before as well. Provide a non-working use-case to prove your point, otherwise I assume it is correct.

You are right about the leaf-list, fixed the same way.

**Comment by Haititi** [comment]
if it cannot appear in this function, then all is good.
forget about the rest, your solution is good as it is.

thanks for you help!
