### ISSUE TITLE
 How to define a namespace for an argument module insde of xml file

### ISSUE THREAD

**Issue by fei15115** [CESNET/libyang#1942]
Hi，
     I have a little doubt about the xml production of the augment module,Here is an example, can you explain it to me please.
     Here I got two yang model:the base one and the augment.
     I think we could just notice on the argument one,and the content is as bwloe:
 
 Here is the base one:==================================================
```yang
module ietf-interfaces {
  yang-version 1.1;
  namespace "urn:ietf:params:xml:ns:yang:ietf-interfaces";
  prefix if;
.....
```
 Here is the augment one:==================================================
```yang
module o-ran-interfaces {
  yang-version 1.1;
  namespace "urn:o-ran:interfaces:1.0";
  prefix "o-ran-int";

  import ietf-interfaces {
    prefix "if";
  }
.....
  augment "/if:interfaces/if:interface" {
    when "if:type = 'ianaift:l2vlan'";
    description "augments for VLAN definition";
    leaf base-interface {
      type if:interface-ref;
      must "/if:interfaces/if:interface[if:name = current()]"
            + "/o-ran-int:vlan-tagging = 'true'" {
        description
          "The base interface must have VLAN tagging enabled.";
      }
      description
        "The base interface for the VLAN sub-interafce.";
    }
    leaf vlan-id {
      type uint16 {
        range "1..4094";
      }
      description
        "The VLAN-ID.";
....
```
===================================================================================
So I need to declare the namespace inside the xml？
like：
```xml
<interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
  <interface>
    <name>XXXXXXXXXX</name>
    <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:l2vlan</type>
    <vlan-id xmlns="urn:o-ran:interfaces:1.0">1281</vlan-id>
  </interface>
</interfaces>
```
or：
```xml
<interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
  <interface>
    <name>XXXXXXXXXX</name>
    <type>ianaift:l2vlan</type>
    <vlan-id>1281</vlan-id>
  </interface>
</interfaces>
```
Thank you very much for taking the time to help me solve this doubt

**Comment by fei15115** [comment]
xml file is cut by github:
Please check below:
`<interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
  <interface>
    <name>XXXXXXXXXX</name>
    <type>ianaift:l2vlan</type>
    <vlan-id>1281</vlan-id>
  </interface>
</interfaces>
`
or this one
`<interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
  <interface>
    <name>XXXXXXXXXX</name>
    <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:l2vlan</type>
    <vlan-id xmlns="urn:o-ran:interfaces:1.0">1281</vlan-id>
  </interface>
</interfaces>
`

**Comment by michalvasko** [comment]
The first XML is correct.

**Comment by fei15115** [comment]
Is there any standard protocol that can be used as a basis or used for learning?

Thanks again for your help

**Comment by michalvasko** [comment]
Learning what exactly? In general there are YANG and NETCONF/RESTCONF, with lots of RFCs.

**Comment by fei15115** [comment]
Just about the yang,that is enough,Is there a protocol doc to reference?

**Comment by michalvasko** [comment]
YANG is not a protocol but a modelling language. It has its own [RFC](https://www.rfc-editor.org/rfc/rfc7950.html).

**Comment by fei15115** [comment]
ok，sorry about that。would you please share the rfc about yang?Thank you so much!

**Comment by michalvasko** [comment]
I mean, just click the `RFC` in my post...

**Comment by fei15115** [comment]
您好，我已经收到您的邮件，我会尽快查看回复，谢谢！
