### ISSUE TITLE
yanglint segment fault

### ISSUE THREAD

**Issue by sourcema** [CESNET/libyang#1943]
yanglint version：2.1.4
I have a segment fault problem when I do add new yang file in yanglint.

**Comment by michalvasko** [comment]
You will have to provide much more information for us to help. Firstly, I would try to use *libyang* v2.1.10 form the `devel` branch. If that is still crashing, attach the YANG module with all its imports that is causing the issue.

**Comment by sourcema** [comment]
> You will have to provide much more information for us to help. Firstly, I would try to use _libyang_ v2.1.10 form the `devel` branch. If that is still crashing, attach the YANG module with all its imports that is causing the issue.

I use the latest version 2.1.17 but still have problems, and this file I imported does not depend on other yang files, I have the core file here, do you need？

**Comment by michalvasko** [comment]
> I have the core file here, do you need?

No, I need the YANG file that causes the crash, please attach it.

**Comment by sourcema** [comment]
> > I have the core file here, do you need?
> 
> No, I need the YANG file that causes the crash, please attach it.

I send a email to you.

**Comment by michalvasko** [comment]
Thanks for that, should now be fixed.

**Comment by sourcema** [comment]
> Thanks for that, should now be fixed.

I updated the version, but I still have the same problem

**Comment by sourcema** [comment]
> Run `yanglint -v` first to make sure you have version 2.1.18.

yes, you can look at the pictures I sent email.

**Comment by michalvasko** [comment]
Please post the output of `ls -l $(ldd $(which yanglint) | grep libyang | cut -d' ' -f3)`.

**Comment by michalvasko** [comment]
Yes, you were still using the older dynamic library.
