### ISSUE TITLE
How to Solve the Error Reported？

### ISSUE THREAD

**Issue by xinghaiquedeng** [CESNET/libyang#1946]
I upgraded yanglint from yanglint SO 1.10.32 to yanglint 2.1.4
After, reported three errors, do not know how to solve.
1.A.yang err  :Input data contains submodule which cannot be parsed directly without its main module.
2.A.yang err :Unknown/non-implemented module "B". **
3.A.yang err :Invalid when condition "C"

module B and condition "C  are not used in module A。

**Comment by michalvasko** [comment]
1. You cannot parse and implement a submodule so do not attempt to. Just load the main module instead.
2. Would need to see the exact error and the modules. It may be an invalid prefix or just a non-implemented module that needs to be implemented explicitly.
3. Would need to see the condition and the module.

**Comment by xinghaiquedeng** [comment]
error：
huawei-oam-cfm-cfm.yang:libyang err : Unknown/non-implemented module "mpls". (Schema location "/huawei-l2vpn:l2vpn".)
huawei-oam-cfm-cfm.yang:libyang err : Invalid when condition "/mpls:mpls/mpls:common/mpls:global/mpls:mpls-enable='true'". (Schema location "/huawei-l2vpn:l2vpn".)
huawei-te-interface.yang:libyang err : Unknown/non-implemented module "mpls". (Schema location "/huawei-network-instance:network-instance/instances/instance/huawei-te:te/huawei-te-interface:interfaces/interface/mpls-te-enable".)
huawei-te-interface.yang:libyang err : Invalid when condition "/mpls:mpls/mpls-te:te/mpls-te:enable='true'". (Schema location "/huawei-network-instance:network-instance/instances/instance/huawei-te:te/huawei-te-interface:interfaces/interface/mpls-te-enable".)

There are many such errors in  https://github.com/Huawei/yang/tree/master/network-router/8.21.0/ne40e-x8x16

**Comment by michalvasko** [comment]
It should be enough to implement the module explicitly, *libyang* is not able to check the validity of those `hen` conditions without that. In `yanglint` you can request all the referenced modules (such as by `when` conditions) to be implemented using `-i` flag.

**Comment by xinghaiquedeng** [comment]
huawei-oam-cfm-cfm.yang  module  has enough reference modules,including  module  huawei-mpls and module huawei-y1731  and module huawei-l2vpn，but still reports " Unknown/non-implemented module ‘mpls‘ " and“ Invalid when condition  ...”.

Note: 
1.mpls is the prefix of module  huawei-mpls . Module  huawei-mpls exists.
2. The relationship between module huawei-oam-cfm-cfm and module  huawei-mpls  is that module huawei-oam-cfm-cfm import module huawei-y1731 , module huawei-y1731  import module huawei-l2vpn, and module huawei-l2vpn import module huawei-mpls.

In my opinion, the huawei-oam-cfm-cfm.yang should not report an error when the dependent model exists.

**Comment by michalvasko** [comment]
You seem not to have understood what I wrote. I am assuming you are loading the modules using `yanglint`. So, *huawei-mpls* is almost certainly **found** but to check the `when` condition, the module needs to be **implemented**. And it is not, hence the `yanglint` error. The obvious solution would be for `yanglint` to automatically implement the module but the cases where modules are automatically implemented are specified exactly and this particular case is not among them. So, `yanglint` instead provides flag `-i` that enables this functionality, specifically automatic implementation of referenced YANG modules, which is what you want.

**Comment by xinghaiquedeng** [comment]
Actually，the way we're using  it is yanglint -i, but it still reports errors.

Now, look at the error in this simple example:
huawei-l2vpn.yang:libyang err : Unknown/non-implemented module "**tnlm**". (Schema location "/huawei-l2vpn:l2vpn/instances/instance/vpls/ldp-signaling/pws/pw/hard-pipe-bandwidth".)
huawei-l2vpn.yang:libyang err : Invalid when condition "../../../hard-pipe='true' and ../signal-type='static' and ../tunnel-policy and /tnlm:tunnel-management/tnlm:tunnel-policys/tnlm:tunnel-policy[tnlm:name=current()/../tunnel-policy]/tnlm:ipv4-set/tnlm:nexthops". (Schema location "/huawei-l2vpn:l2vpn/instances/instance/vpls/ldp-signaling/pws/pw/hard-pipe-bandwidth".)
For details about modul huawei-l2vpn.yang, see the link.
https://github.com/Huawei/yang/blob/master/network-router/8.21.0/ne40e-x8x16/huawei-l2vpn.yang

**Comment by michalvasko** [comment]
Right, it was a specific unhandled case of multiple `when` depending on each other, should now work. Also note that simply using `-ii` works even without the fix and is faster because all the module are set implemented instead of the complex detection of what modules exactly need to be implemented (where the problem was).

**Comment by michalvasko** [comment]
We do not have any specific release plan but when you look at the release history it seems there are at least a few months between releases, so there will probably not be another release this year.
