### ISSUE TITLE
internal error while parsing LYB after disabling features

### ISSUE THREAD

**Issue by Haititi** [CESNET/libyang#1947]
Hi,

I have some yang models with some nodes with `if-features` set on them and having default values.

- Suppose i initialize a context with `LY_CTX_ENABLE_IMP_FEATURES|LY_CTX_ALL_IMPLEMENTED` set.
at the beginning, I have an empty config which I validate with `lyd_validate_all()`. This fills the my config with many default values, even the ones with `if-features`.
I then dump the config in a lyb file.

- I initialize a new context without the previous two flags in order to keep  some of my features disabled.
I parse the lyb file with `lyd_parse_data_path()` with flags `LYD_PARSE_NO_STATE` set.
I expect that due to some features being disabled, i should have some missing schema definition, but it should be fine, as stated in your documentation regarding the default parser behavior:
> parser silently ignores data without matching schema node definition

Instead of that, I'm having the following error:
> error: Internal error (/build/libyang/src/parser_lyb.c:549).

(My code is based on libyang 2.0.267. on last devel version, the error log comes from line 550).

I would be glad to get some help here.
Thank you!

**Comment by Haititi** [comment]
another info:
- if i add the flag `LYD_PARSE_OPAQ` to `lyd_parse_data_path()`, the parsing seems to go well.
- if i add the flag `LYD_PARSE_STRICT` to `lyd_parse_data_path()`, i receive the following error:
> LYB DS file: Failed to find matching hash for a child node of "container1".

Here, `container1` is a container which is part of a grouping (let say `grouping-container`), and contains some child container `child-container`.
It is used this way in another module:

```
  augment "/modname1:name1/modname1:name2" {
    uses grouping-container {
      refine "container1" {
        description
          "A container.";
      }    
      refine "container1/child-container" {
        if-feature "feature_that_wont_be_enabled";
      }
    }
  }
```

I hope it helps.

**Comment by michalvasko** [comment]
Actually, I have fixed the issue several days ago but it completely broke *sysrepo*, so I had to fix that, too, which took me until now. So, *libyang* should be fixed and it will now refuse to parse LYB data to a context with a different set of enabled features because there is a risk of parsing one node as another.

**Comment by Haititi** [comment]
This solution is really problematic in our use case.
This means we can't update our features without losing all the sysrepo configuration.
Moreover, now that you updated the LYB file version, won't it make us impossible to upgrade to your latest version without losing our configuration ?

Can't we try to find a better way to fix this issue ? 
At least `LYD_PARSE_OPAQ` allows the parsing to go well. so is it not possible just to parse them the same way and then delete the opaque node (if not possible to ignore it) ?

**Comment by jktjkt** [comment]
Regarding sysrepo upgrades and persistency of the `startup` DS, you might find these useful:
- sysrepo/sysrepo#2280
- sysrepo/sysrepo#2726

**Comment by michalvasko** [comment]
> Can't we try to find a better way to fix this issue ?

There is no better way, any other solution would be prone to wrong stored hash interpretation and hence parsing errors/corruption.

As for using *sysrepo*, I have actually changed the default data format from LYB to JSON to avoid these problems, so yes, to update *sysrepo* this one time and keep the configuration, you should first export and then after upgrade import it with `sysrepocfg`.
