### ISSUE TITLE
libyang-2.1.4 yanglint generate incorrect yin file

### ISSUE THREAD

**Issue by hatuomin** [CESNET/libyang#1948]
Trying to convert [o-ran-fm@2019-02-04.yang](https://wiki.onap.org/download/attachments/64007500/o-ran-fm@2019-02-04.yang?api=v2) to yin.

yanglint -f yin o-ran-fm.yang 
Conversion itself is executed without errors

In line 120 on generated yin file looks like this. list end tag is in wrong position
``
  <list name="affected-objects"      <min-elements value="1"/>
      <max-elements value="100"/>
     <
      <description>
        <text>List of affected-objects</text>
      </description>
      <leaf name="name">
        <type name="string">
          <length value="1..255"/>
        </type>
        <mandatory value="true"/>
        <description>
          <text>Represents the Object or source that is suspected to be affected by this fault</text>
        </description>
      </leaf>
    </list>
``

yang file at the same location
 list affected-objects {
      leaf name {
        type string {
          length "1..255";
        }
        mandatory true;

        description
          "Represents the Object or source that is suspected to be affected by this fault";
      }
      min-elements 1;
      max-elements 100;

      description
        "List of affected-objects";
    }

same conversion with pyang 2.5.3 will generate correct yin file
 ``
<list name="affected-objects">
            <leaf name="name">
                <type name="string">
                    <length value="1..255"/>
                </type>
                <mandatory value="true"/>
                <description>
                    <text>Represents the Object or source that is suspected to be affected by this fault</text>
                </description>
            </leaf>
            <min-elements value="1"/>
            <max-elements value="100"/>
            <description>
                <text>List of affected-objects</text>
            </description>
        </list>
``

**Comment by michalvasko** [comment]
Right, should be fixed now.
