### ISSUE TITLE
Invalid leafref value

### ISSUE THREAD

**Issue by sourcema** [CESNET/libyang#1951]
#1939 
I tested with a devel branch and still have problems, I don't know where the problem is.
yanglint version : 2.1.18
error message:
libyang err : Invalid leafref value "o-ran-hardware:O-RAN-RADIO" - no target instance "/hw:hardware/hw:component/hw:class" with the same value. (Data location "/o-ran-performance-management:measurement-result-stats/epe-stats/epe-measurement-result[object-unit-id='o-ran-hardware:O-RAN-RADIO']/object-unit-id".)
YANGLINT[E]: Failed to validate input data file "epe-notification.xml".

**Comment by sourcema** [comment]
I used this xml:
<epe-stats>
    <start-time>2022-11-13T01:03:14Z</start-time>
    <end-time>2022-11-13T01:03:14Z</end-time>
    <epe-measurement-result>
      <object-unit-id xmlns:o-ran-hw="urn:o-ran:hardware:1.0">o-ran-hw:O-RAN-RADIO</object-unit-id>
      <min>27.46</min>
      <max>27.54</max>
      <average>8666</average>
    </epe-measurement-result>
  </epe-stats>
 It parses o-ran-hw:O-RAN-RADIO into o-ran-hardware:O-RAN-RADIO

**Comment by michalvasko** [comment]
The error is quite exact and correct, I think you just lack understanding of what a [leafref] is, so please fix that.

**Comment by sourcema** [comment]
> The error is quite exact and correct, I think you just lack understanding of what a [leafref](https://www.rfc-editor.org/rfc/rfc7950.html#section-9.9) is, so please fix that.

thanks，I understand that the value of the referenced node does not exist now, how can I load the configured value in advance in yanglint and check it at the same time?

**Comment by sourcema** [comment]
[epe-notification.txt](https://github.com/CESNET/libyang/files/10175557/epe-notification.txt)

I wrote the xml node to a file, but the execution command reports an error：
libyang err : Unexpected sibling node. (Line number 10.)

I exec this command：yanglint -t notif iana-*.yang ietf-*.yang o-ran-*.yang tailf-common.yang   epe-notification.xml

**Comment by michalvasko** [comment]
I am not able to download the file but if you are validating a notification then you should actually have 2 files, In one, there is the notification and in the other the `operational` datastore used for resolving any references during validation, which is your case. You provide the latter using `-O` parameter.

**Comment by sourcema** [comment]
[epe-notification2.txt](https://github.com/CESNET/libyang/files/10182996/epe-notification2.txt)

**Comment by michalvasko** [comment]
I see, like I said, just put `measurement-result-stats` in the "main" data file and the `hardware` subtree into another passed using the `-O` parameter. Then the validation should pass.

**Comment by sourcema** [comment]
> I see, like I said, just put `measurement-result-stats` in the "main" data file and the `hardware` subtree into another passed using the `-O` parameter. Then the validation should pass.

Thank you very much, I solved the problem.
