### ISSUE TITLE
enum ly_stmt 

### ISSUE THREAD

**Issue by LiangGuoYu** [CESNET/libyang#1952]
Let me ask you why the ly_stmt enumeration in the header file plugins_exts.h always defines addresses that are doubled and incremented. Looking forward to your reply！

**Comment by LiangGuoYu** [comment]
> Let me ask you why the ly_stmt enumeration in the header file plugins_exts.h always defines addresses that are doubled and incremented. Looking forward to your reply！
This makes the compiled library take up a lot of memory space, can this be changed, how to change?

**Comment by michalvasko** [comment]
Because those first 16 values are sometimes used as bitmaps. But I am not sure I understand the problem, why does it matter what the values of those enums are? An enum should always actually be an `int`.

**Comment by LiangGuoYu** [comment]
> Because those first 16 values are sometimes used as bitmaps. But I am not sure I understand the problem, why does it matter what the values of those enums are? An enum should always actually be an `int`.

The enum "LY_STMT_YIN_ELEMENT = 0x350000" is placed in the struct array stmt_attr_info in the tree_schema_common.c file, which takes up a lot of memory (on 64-bit systems, The 24 bytes of two Pointers and an unsigned integer in the stmt_info_s struct (0x350000 * 0x18 = 0x4F80000 bytes) are approximately 79MB. Can you tell me why the enum is so large? Because I was compiling this libyang, I ran into trouble with this storage space when porting to an embedded device

**Comment by michalvasko** [comment]
Right, I did not notice that before, thanks. Should be fixed in the latest `devel` version.
