### ISSUE TITLE
Author complaint needs reference to problem

### ISSUE THREAD

**Issue by mcr** [CESNET/libyang#1956]
````
dyas-[anima/anima-brski-prm/yang](2.6.6) mcr 8091 %yanglint -f json ietf-async-voucher-request@2021-08-18.yang example1.json 
err : Invalid keyword "Author:".
err : Module "ietf-async-voucher-request" parsing failed.
````

I guess that this refers to the contact ""; contents.
I can't see "author" anywhere else in the yang module.
RFC6020 does not say anything but that it's a string.  I guess some other document (which I am unfamiliar with) provides some structure for that string?  If that's so, could the error message, if it's specific to parsing the contact info, mention what specification I am violating?

**Comment by mcr** [comment]
this might be useful google fodder for others whose yanglint is ancient.

**Comment by michalvasko** [comment]
Yes, in all likelihood (the ancient) `yanglint` is at fault here.
