### ISSUE TITLE
`anydata` XML gets printed with `xmlns=(null)`

### ISSUE THREAD

**Issue by jktjkt** [CESNET/libyang#1958]
I was investigating an unrelated breakage in the test suite of C++ bindings, and I noticed that when I create `anydata` from an XML string with no namespace, the result gets printed with a wrong namespace, probably due to a naked printf-like `"%s` of a `NULL` pointer. Here's a small test:
```c++
ctx.newPath2("/example-schema:myData", libyang::XML{"<something>lol</something>"});

std::cout << *std::get<libyang::DataNode>(xmlAnyDataNode.createdNode->asAny().releaseValue().value())
  .printStr(libyang::DataFormat::XML, libyang::PrintFlags::Shrink);
```
The result prints as:
```xml
<something xmlns="(null)">lol</something>
```

The interesting part is that when I construct the `anydata` from a JSON like this:
```c++
node.newPath2("/example-schema:myData", libyang::JSON{R"({"key": "value"})"}).createdNode;
```
...then the XML gets printed as:
```xml
<key>value</key>
```

The C++ bindings might obstruct the underlying bug a bit, but `newPath2` essentially simply calls `lyd_new_path2(node, ctx, path, value, 0, FORMAT, options, &newParent, &newNode)` where `FORMAT` depends on the wrapper which got used.

The original issue which I was investigating was a behavior change that `anydata` nodes are no more kept as JSON/XML entities, but they get transformed to a data node. I assume that that was intentional :), and it was not a big deal to adapt the test suite.

However, another change is that I cannot do this anymore:
```c++
ctx.newPath2("/example-schema:myData", libyang::JSON{"[1,2,3]"});
```
...which complains about the JSON value not being an object. Is that intentional, and is there some replacement?

**Comment by michalvasko** [comment]
I hope the empty namespace has been fixed.

> `anydata` nodes are no more kept as JSON/XML entities, but they get transformed to a data node.

Yes, after rereading all the relevant RFCs, that is the main difference between `anyxml` and `anydata`, the latter is technically a `container` but without corresponding YANG definitions.

> JSON value not being an object. Is that intentional, and is there some replacement?

That is the consequence of what I said before and I believe it was not behaving correctly before.

**Comment by jktjkt** [comment]
thanks, looks like our test suite was treating `anydata` as if it was `anyxml`, fixed now
