### ISSUE TITLE
use lyd_new_path get error parent and child relationship if we construct lyd nodes in mutilwall augment 

### ISSUE THREAD

**Issue by ostack** [CESNET/libyang#196]
`	
use lyd_new_path get error parent and child relationship

i print the node xpath,created node pointer and it's parent pointer as follow.
i found the xpath "/Ostack:Ostack/fox:fox/fireFox[nID='255'][sID='3']" 's children  parent node
( as dscpValue,mcc,mnc) does not pointer to the node[140715950820224] created by the xpath,
but pointer to another node [140715950467792],[140715950372688],[140715950832400].
And the xpath "/Ostack:Ostack/fox:fox/fireFox[nID='255'][sID='3']" key children (as nID,sID)  parent point to the same node as /Ostack:Ostack/fox:fox/fireFox[nID='255'][sID='3']

create xpath:/Ostack:Ostack/fox:fox/fireFox[nID='9'][sID='3'],lyd node:[140715950512016],parent[140715950808704]		
create xpath:/Ostack:Ostack/fox:fox/fireFox[nID='255'][sID='3'],lyd node:[**140715950820224**],parent[140715950808704]		
create xpath:/Ostack:Ostack/fox:fox/fireFox[nID='255'][sID='3']/nID,lyd node:[140715950598256],parent[140715950808704] **---real parent expect 140715950820224**
create xpath:/Ostack:Ostack/fox:fox/fireFox[nID='255'][sID='3']/sID,lyd node:[140715950595488],parent[140715950808704] **---real parent expect 140715950820224**	
create xpath:/Ostack:Ostack/fox:fox/fireFox[nID='255'][sID='3']/dscpValue,lyd node:[140715951069168],parent[140715950467792] **---real parent should be 140715950820224**	
create xpath:/Ostack:Ostack/fox:fox/fireFox[nID='255'][sID='3']/mcc,lyd node:[140715951023152],parent[140715950372688] **---real parent expect 140715950820224**
create xpath:/Ostack:Ostack/fox:fox/fireFox[nID='255'][sID='3']/mnc,lyd node:[140715951009360],parent[140715950832400] **---real parent expect 140715950820224**	

the used  functioin and input para is like follow:

    struct lyd_node* node = lyd_new_path(rootNode, lyCtx, change.xpath.c_str(), (void*) change.newValue.c_str(),
            LYD_ANYDATA_CONSTSTRING, LYD_PATH_OPT_UPDATE);
    struct lyd_node* inserted = node;
    struct ly_set* find = lyd_find_xpath(rootNode, change.xpath.c_str());
    if (find != NULL && find->number == 1) {
        inserted = find->set.d[0];
    }
    if (inserted == NULL) {
        LOG_INFO("can't get node inserted[%s]", change.xpath.c_str());
        return;
    }
    LOG_INFO("get node[%lu] for inserted[%s],parent[%lu]",inserted, change.xpath.c_str(),inserted->parent);	`

**Comment by ostack** [comment]
As the **model and the data is very big** ,if  i cut most of them ,it can not reproduce. If i use the original it can be reproduced again and again.

**Comment by ostack** [comment]
IT is my fault.

**Comment by ostack** [comment]
As my original model and data is much big ,if i cut most of them this issue not appear ,but if i use the original it appear every time.

**Comment by ostack** [comment]
Hi 
I reproduce the issue ,found it has no relation with the big data or module, it occurs  when we edit multiwall module.
you can reproduce this issue use the follow yang file and data file.

summery of module relation : **redfox** augment **fox**, **fox** augment **Ostack**
step to reproduce:
1. add the yang file to sysrepo
2. use edit-config to init data with **init.xml**  
3. use edit-config to reproduce the issue with **reproduce.xml** . In reproduce.xml ,element of **fox** and  **redfox** are modified.
4. receive sysrepo model change data,and use the xpath and value to construct lyd_node 

-------Ostack -----------

`module Ostack {
 namespace "urn:Ostack:params:xml:ns:yang:ran:Ostack";
  
  prefix "ME";
  
  revision "2016-09-14" {
    description
      "Initial Version.";
    reference
      "3gpp";
  }

  container Ostack {
    leaf meId {
        type    int32;
        mandatory true;
    }
    
  }
}
`
-------module fox -----------
`module fox {
  namespace "urn:Ostack:params:xml:ns:yang:ran:fox";
  prefix "fox";

  import Ostack{
    prefix Ostack;
  }

  description
      "fox Function";   

  revision "2016-10-21" {
    description
      "Initial Version.";
    reference
      "3gpp";
  }

  typedef user-label {
    type string {
      length "0..128";
    }
    description "User Label";
  }

  typedef mcc {
    type string {
      length "3";
      pattern "[0-9]*";
    }
    description "MCC";
  }

  typedef mnc {
    type string {
      length "2..3";
      pattern "[0-9]*";
    }
    description "MNC";
  }

  grouping mcc-mnc {
    leaf mcc {
      type mcc;
    }
    leaf mnc {
      type mnc;
    }
  }
  typedef arpSegmentId {
    type uint8 {
      range "1..15";
    }
    default 1;
    description
      "ARP is devided into serval segment to map different priority. arpSegmentId is the ID of the segments.";
  }
  typedef nID {
    type uint16 {
      range "0..256";
    }
    description
      "The parameter is nID.";
  }

  augment /Ostack:Ostack {
  
    container fox {
      leaf userLabel {
        type user-label;
      }
	  
	  list fireFox {
        description "nID and DSCP Mapping";
        key "nID sID";
        
        leaf nID {
          type nID;
        }
        
        leaf sID {
          type arpSegmentId;
          description
            "ARP is devided into serval segment to map different priority. sID is the ID of the segOstacknts.";
        }
        
        uses mcc-mnc;
        
        leaf dscpValue {
          type uint8 {
            range "0..63";
          }
          default 46;
          description "The paraOstackter is DSCP's ID, when processing mapping between nID and ARP.";
        }
      }  
    }
  }
}

`
-------module redfox-----------
`module redfox {
  namespace "urn:Ostack:params:xml:ns:yang:ran:redfox";
  prefix "redfox";

  import Ostack{
    prefix Ostack;
  }
  import fox{
    prefix fox;
  }

  augment /Ostack:Ostack/fox:fox { 
	  list redfox {
        description "nID and DSCP Mapping";
        key "id";
        leaf id {
          type uint8;
        }
        leaf name {
          type string;
        }
		container info {
		  leaf age {
            type uint8;
            description
            "ARP is devided into serval segment to map different priority. sID is the ID of the segOstacknts.";
          }
		  leaf sex {
            type uint8;
            description
            "ARP is devided into serval segment to map different priority. sID is the ID of the segOstacknts.";
          }
        }
      }  
    }
}

`
--------------init.xml-------------------

`<Ostack xmlns="urn:Ostack:params:xml:ns:yang:ran:Ostack" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
  <meId>121</meId>
  <fox xmlns="urn:Ostack:params:xml:ns:yang:ran:fox">
		<fireFox>
		  <nID>1</nID>
		  <sID>1</sID>
		  <dscpValue>46</dscpValue>
		  <mcc>460</mcc>
		  <mnc>01</mnc>
		</fireFox>
		<fireFox>
		  <nID>1</nID>
		  <sID>2</sID>
		  <dscpValue>46</dscpValue>
		  <mcc>460</mcc>
		  <mnc>01</mnc>
		</fireFox>
		<fireFox>
		  <nID>1</nID>
		  <sID>3</sID>
		  <dscpValue>46</dscpValue>
		  <mcc>460</mcc>
		  <mnc>01</mnc>
		</fireFox>
		<fireFox>
		  <nID>2</nID>
		  <sID>1</sID>
		  <dscpValue>32</dscpValue>
		  <mcc>460</mcc>
		  <mnc>01</mnc>
		</fireFox>
		<fireFox>
		  <nID>2</nID>
		  <sID>2</sID>
		  <dscpValue>32</dscpValue>
		  <mcc>460</mcc>
		  <mnc>01</mnc>
		</fireFox>
		<fireFox>
		  <nID>2</nID>
		  <sID>3</sID>
		  <dscpValue>32</dscpValue>
		  <mcc>460</mcc>
		  <mnc>01</mnc>
		</fireFox>
		<fireFox>
		  <nID>3</nID>
		  <sID>1</sID>
		  <dscpValue>32</dscpValue>
		  <mcc>460</mcc>
		  <mnc>01</mnc>
		</fireFox>
		<fireFox>
		  <nID>3</nID>
		  <sID>2</sID>
		  <dscpValue>32</dscpValue>
		  <mcc>460</mcc>
		  <mnc>01</mnc>
		</fireFox>
		<fireFox>
		  <nID>3</nID>
		  <sID>3</sID>
		  <dscpValue>32</dscpValue>
		  <mcc>460</mcc>
		  <mnc>01</mnc>
		</fireFox>
		<fireFox>
		  <nID>4</nID>
		  <sID>1</sID>
		  <dscpValue>24</dscpValue>
		  <mcc>460</mcc>
		  <mnc>01</mnc>
		</fireFox>
		<fireFox>
		  <nID>4</nID>
		  <sID>2</sID>
		  <dscpValue>24</dscpValue>
		  <mcc>460</mcc>
		  <mnc>01</mnc>
		</fireFox>
		<fireFox>
		  <nID>4</nID>
		  <sID>3</sID>
		  <dscpValue>24</dscpValue>
		  <mcc>460</mcc>
		  <mnc>01</mnc>
		</fireFox>
		<fireFox>
		  <nID>5</nID>
		  <sID>1</sID>
		  <dscpValue>40</dscpValue>
		  <mcc>460</mcc>
		  <mnc>01</mnc>
		</fireFox>
		<fireFox>
		  <nID>5</nID>
		  <sID>2</sID>
		  <dscpValue>40</dscpValue>
		  <mcc>460</mcc>
		  <mnc>01</mnc>
		</fireFox>
		<fireFox>
		  <nID>5</nID>
		  <sID>3</sID>
		  <dscpValue>40</dscpValue>
		  <mcc>460</mcc>
		  <mnc>01</mnc>
		</fireFox>
		<fireFox>
		  <nID>6</nID>
		  <sID>1</sID>
		  <dscpValue>30</dscpValue>
		  <mcc>460</mcc>
		  <mnc>01</mnc>
		</fireFox>
		<fireFox>
		  <nID>6</nID>
		  <sID>2</sID>
		  <dscpValue>28</dscpValue>
		  <mcc>460</mcc>
		  <mnc>01</mnc>
		</fireFox>
		<fireFox>
		  <nID>6</nID>
		  <sID>3</sID>
		  <dscpValue>26</dscpValue>
		  <mcc>460</mcc>
		  <mnc>01</mnc>
		</fireFox>
		<fireFox>
		  <nID>7</nID>
		  <sID>1</sID>
		  <dscpValue>38</dscpValue>
		  <mcc>460</mcc>
		  <mnc>01</mnc>
		</fireFox>
		<fireFox>
		  <nID>7</nID>
		  <sID>2</sID>
		  <dscpValue>36</dscpValue>
		  <mcc>460</mcc>
		  <mnc>01</mnc>
		</fireFox>
		<fireFox>
		  <nID>7</nID>
		  <sID>3</sID>
		  <dscpValue>34</dscpValue>
		  <mcc>460</mcc>
		  <mnc>01</mnc>
		</fireFox>
		<fireFox>
		  <nID>8</nID>
		  <sID>1</sID>
		  <dscpValue>14</dscpValue>
		  <mcc>460</mcc>
		  <mnc>01</mnc>
		</fireFox>
		<fireFox>
		  <nID>8</nID>
		  <sID>2</sID>
		  <dscpValue>12</dscpValue>
		  <mcc>460</mcc>
		  <mnc>01</mnc>
		</fireFox>
		<fireFox>
		  <nID>8</nID>
		  <sID>3</sID>
		  <dscpValue>10</dscpValue>
		  <mcc>460</mcc>
		  <mnc>01</mnc>
		</fireFox>
		<fireFox>
		  <nID>9</nID>
		  <sID>1</sID>
		  <dscpValue>0</dscpValue>
		  <mcc>460</mcc>
		  <mnc>01</mnc>
		</fireFox>
		<fireFox>
		  <nID>9</nID>
		  <sID>2</sID>
		  <dscpValue>0</dscpValue>
		  <mcc>460</mcc>
		  <mnc>01</mnc>
		</fireFox>
		<fireFox>
		  <nID>9</nID>
		  <sID>3</sID>
		  <dscpValue>0</dscpValue>
		  <mcc>460</mcc>
		  <mnc>01</mnc>
		</fireFox>
		<redfox xmlns="urn:Ostack:params:xml:ns:yang:ran:redfox">
		   <id>1</id>
		   <name>douki</name>
			<info>
			  <age>2</age>
			  <sex>1</sex>
			</info>
       </redfox>
    </fox>
</Ostack>`

---------reproduce.xml---------
`<Ostack xmlns="urn:Ostack:params:xml:ns:yang:ran:Ostack" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
  <fox xmlns="urn:Ostack:params:xml:ns:yang:ran:fox">
		<fireFox xc:operation="create">
		  <nID>255</nID>
		  <sID>3</sID>
		  <dscpValue>0</dscpValue>
		  <mcc>460</mcc>
		  <mnc>01</mnc>
		</fireFox>
		<fireFox xc:operation="delete">
		  <nID>9</nID>
		  <sID>3</sID>
		</fireFox>
		<redfox xmlns="urn:Ostack:params:xml:ns:yang:ran:redfox">
		  <id>1</id>
		  <info>
			<age>3</age>
		  </info>
		</redfox>
  </fox>
</Ostack>`

**Comment by michalvasko** [comment]
Hi,
I am quite confused about the actual issue here. I tried the steps you mentioned and the final configuration sysrepo returns is exactly as expected. If there is an issue with `lyd_new_path` then using both *sysrepo* and *netopeer2-server* is totally useless and please reproduce the issue using *libyang* (or *yanglint*) only.

Regards,
Michal

**Comment by ostack** [comment]
To reproduce this issue ,we should not deal xpath only one and check ,but gather all the xpaths in the reproduce.xml and then  construct these xpaths in to a lyd_node,you can have a try.

Regards,

**Comment by michalvasko** [comment]
Hi,
this is what I tried:
```C
#include <stdio.h>
#include <stdlib.h>
#include <libyang/libyang.h>


int main(int argc, char **argv)
{
  struct ly_ctx *ctx = ly_ctx_new(".");
  ly_ctx_load_module(ctx, "redfox", NULL);

  struct lyd_node *data;

  data = lyd_parse_path(ctx, "init.xml", LYD_XML, LYD_OPT_CONFIG);

  lyd_new_path(data, NULL, "/Ostack:Ostack/fox:fox/fireFox[nID='255'][sID='3']/dscpValue", "0", 0, 0);
  lyd_new_path(data, NULL, "/Ostack:Ostack/fox:fox/fireFox[nID='255'][sID='3']/mcc", "460", 0, 0);
  lyd_new_path(data, NULL, "/Ostack:Ostack/fox:fox/fireFox[nID='255'][sID='3']/mnc", "01", 0, 0);

  struct ly_set *set = lyd_find_xpath(data, "/Ostack:Ostack/fox:fox/fireFox[nID='9'][sID='3']");
  lyd_unlink(set->set.d[0]);

  lyd_new_path(data, NULL, "/Ostack:Ostack/fox:fox/redfox:redfox[id='1']/info/age", "3", 0, LYD_PATH_OPT_UPDATE);

  lyd_print_file(stdout, data, LYD_XML, LYP_FORMAT);

  lyd_free_withsiblings(data);
  ly_ctx_destroy(ctx, NULL);
  return 0;
}
```

It worked exactly as expected. It is also possible that it was fixed by some of my previous fixes. Nevertheless, please provide a reproducible example, otherwise I cannot help you and am just wasting my time, thank you.

Regards,
Michal

**Comment by ostack** [comment]
To reproduce  the issue you can use the following code.

the only difference with you is ,we create /Ostack:Ostack/fox:fox/redfox:redfox[id='1']/info/age first, this means we create child first. 

I  wonder if we use lyd_find_xpath to create node, we shold make sure the  input xpath parent-child order must strictly keep with the schema ? and the function can not reorder itself when create the node ?

To:@rastislavszabo if the function require the user to input the xpath strictly ,we should do something in our sysrepo code to make the model change callback returned xpath in schema order , what about you opinion.

`
#include <stdio.h>
#include <stdlib.h>
#include <libyang/libyang.h>


int main(int argc, char **argv)
{
	
	vector<pair<string, string>> changeInfo;
    changeInfo.push_back(make_pair("/Ostack:Ostack/fox:fox/redfox:redfox[id='1']/info/age", "3"));
    changeInfo.push_back(make_pair("/Ostack:Ostack/fox:fox/fireFox[nID='9'][sID='3']", ""));
    changeInfo.push_back(make_pair("/Ostack:Ostack/fox:fox/fireFox[nID='255'][sID='3']", ""));
    changeInfo.push_back(make_pair("/Ostack:Ostack/fox:fox/fireFox[nID='255'][sID='3']/nID", "255"));
    changeInfo.push_back(make_pair("/Ostack:Ostack/fox:fox/fireFox[nID='255'][sID='3']/sID", "3"));
    changeInfo.push_back(make_pair("/Ostack:Ostack/fox:fox/fireFox[nID='255'][sID='3']/dscpValue", "0"));
    changeInfo.push_back(make_pair("/Ostack:Ostack/fox:fox/fireFox[nID='255'][sID='3']/mcc", "460"));
    changeInfo.push_back(make_pair("/Ostack:Ostack/fox:fox/fireFox[nID='255'][sID='3']/mnc", "01"));

    struct ly_ctx* lyCtx;
    lyCtx = ly_ctx_new("../test/module");
    ly_ctx_load_module(lyCtx, "redfox", NULL);

    const struct lys_module* module = ly_ctx_get_module(lyCtx, "Ostack", NULL);
    struct lyd_node* rootNode = lyd_new(NULL, module, "Ostack");

    for (vector<pair<string, string>>::const_iterator it = changeInfo.begin(); it != changeInfo.end(); it++) {
        struct lyd_node* node = lyd_new_path(rootNode, lyCtx, it->first.c_str(), (void*) it->second.c_str(),
                LYD_ANYDATA_CONSTSTRING, LYD_PATH_OPT_UPDATE);

        struct lyd_node* finded = NULL;
        struct ly_set* find = lyd_find_xpath(rootNode, it->first.c_str());
        if (find != NULL && find->number == 1) {
            finded = find->set.d[0];
        }
        if (finded == NULL || node == NULL) {
            printf("can't get node inserted[%s]\n", it->first.c_str());
            continue;
        }
        printf("createdNode[%lu],parent[%lu];getedNode[%lu],parent[%lu];xpath[%s]\n", node, node->parent, finded,
                finded->parent, it->first.c_str());
    }

    char* buf = NULL;
    lyd_print_mem(&buf, rootNode, LYD_JSON, 0);
    printf("json data:%s\n", buf);
    free(buf);
    lyd_free_withsiblings(rootNode);
    ly_ctx_destroy(lyCtx, NULL);
}
`

the print log is : 
`
createdNode[20740736],parent[20737728];getedNode[20634080],parent[20736016];xpath[/Ostack:Ostack/fox:fox/redfox:redfox[id='1']/info/age]
createdNode[20632864],parent[20740736];getedNode[20632864],parent[20740736];xpath[/Ostack:Ostack/fox:fox/fireFox[nID='9'][sID='3']]
createdNode[20739024],parent[20740736];getedNode[20739024],parent[20740736];xpath[/Ostack:Ostack/fox:fox/fireFox[nID='255'][sID='3']]
can't get node inserted[/Ostack:Ostack/fox:fox/fireFox[nID='255'][sID='3']/nID]
can't get node inserted[/Ostack:Ostack/fox:fox/fireFox[nID='255'][sID='3']/sID]
createdNode[20739600],parent[20740736];getedNode[20693264],parent[20739600];xpath[/Ostack:Ostack/fox:fox/fireFox[nID='255'][sID='3']/dscpValue]
createdNode[20734112],parent[20740736];getedNode[20821632],parent[20734112];xpath[/Ostack:Ostack/fox:fox/fireFox[nID='255'][sID='3']/mcc]
createdNode[20734176],parent[20740736];getedNode[20823120],parent[20734176];xpath[/Ostack:Ostack/fox:fox/fireFox[nID='255'][sID='3']/mnc]
json data:{
    "Ostack:Ostack": {
        "fox:fox": {
            "redfox:redfox": [
                {
                    "id": 1,
                    "info": {
                        "age": 3
                    }
                }
            ],
            "fireFox": [
                {
                    "nID": 9,
                    "sID": 3
                },
                {
                    "nID": 255,
                    "sID": 3
                },
                {
                    "nID": 255,
                    "sID": 3
                },
                {
                    "nID": 255,
                    "sID": 3
                },
                {
                    "nID": 255,
                    "sID": 3,
                    "dscpValue": 0
                },
                {
                    "nID": 255,
                    "sID": 3,
                    "mcc": "460"
                },
                {
                    "nID": 255,
                    "sID": 3,
                    "mnc": "01"
                }
            ]
        }
    }
}
`

**Comment by michalvasko** [comment]
Hi,
I finally understood, reproduced, and hopefully fixed the problem.

Regards,
Michal

**Comment by ostack** [comment]
it works ,thanks very much
