### ISSUE TITLE
Debian symbols file out of date

### ISSUE THREAD

**Issue by nhathaway** [CESNET/libyang#1962]
The .deb in the latest (November 2022) release doesn't build due to a broken symbols file. I created this patch (based on my best guess):

[libyang.patch](https://github.com/CESNET/libyang/files/10294245/libyang.patch)

**Comment by michalvasko** [comment]
Thanks, but DEB packages should be fixed (and officially published) next year, hopefully. Then we will also fix the scripts and everything.
