### ISSUE TITLE
is there any reason to have ly_in_read() and ly_in_skip() not public?

### ISSUE THREAD

**Issue by Haititi** [CESNET/libyang#1969]
Hi,

I'm trying to implement a simple "auto-detect format" mechanism which would read the 3 first bytes of a file and check if i find the any relevant characters to guess the format ("{" for JSON format, "<" for XML format, "lyb" for LYB format).

As my data can be provided via a stdin file pipe (`mybinary < /path/to/file`) or a file path (`mybinary -f /path/to/file`), I'm instantiating a `struct ly_in *in` with `ly_in_new_fd(0, &in)` or `ly_in_new_filepath(path, 0, &in)`.

I wanted to use `struct ly_in` because of the mmap functionality already used, and in order to not `open()` the file manually, read the file without mmap, seek back to the beginning of the file, and then pass it to `ly_in_new_fd()` to create the mmap.

But here I'm stuck due to `ly_in_read()` API being private.
Is there a reason to that? Is it possible to make it public ?

I can see that `ly_in_reset()` is public, so I thought i could also read from it before resetting it.

Thanks for your help.

**Comment by michalvasko** [comment]
Fine, the function is public in the latest *libyang* `devel`.

**Comment by Haititi** [comment]
Amazing, thanks a lot!
