### ISSUE TITLE
Error while parsing ietf-netconf-notifications

### ISSUE THREAD

**Issue by lukasmacko** [CESNET/libyang#197]
```C
#include <stdio.h>
#include <stdlib.h>
#include <libyang/libyang.h>

int main(int argc, char **argv)
{

   struct ly_ctx *ctx = ly_ctx_new(".");
   const struct lys_module *module = ly_ctx_load_module(ctx, "ietf-netconf-notifications", NULL);
   ly_ctx_destroy(ctx, NULL);
   return 0;
}
```
Tested with libyang 0.11.60

```
libyang[0]: Schema node "confirm-event" not found (../confirm-event).
libyang[0]: Resolving when condition "../confirm-event != 'timeout'" failed. (path: /ietf-netconf-notifications:netconf-confirmed-commit/common-session-parms)
libyang[0]: Module "ietf-netconf-notifications" parsing failed.
```
https://github.com/YangModels/yang/blob/master/standard/ietf/RFC/ietf-netconf-notifications.yang
https://github.com/YangModels/yang/blob/master/standard/ietf/RFC/ietf-netconf%402011-06-01.yang

**Comment by michalvasko** [comment]
Hi,
the model is wrong, based on the (YANG RFC)[https://tools.ietf.org/html/rfc6020#section-7.19.5] the context node for the when expression is `notification netconf-confirmed-commit`.

Regards,
Michal

**Comment by lukasmacko** [comment]
ah, thanks. I've found https://www.rfc-editor.org/errata_search.php?rfc=6470
