### ISSUE TITLE
How to get data without namespace or module name by lyd_print_mem

### ISSUE THREAD

**Issue by guangjung** [CESNET/libyang#1972]
1. My main coding
```C
 sr_get_subtree(pstSess, pcYangPath, 0, &pstSubtreeData)
lyd_print_mem(&pcJsonStr, pstSubtreeData->tree, LYD_JSON, LYD_PRINT_WITHSIBLINGS | LYD_PRINT_SHRINK); 
```
the output is as following:
```json
{
        "openconfig-transport-line-protection:state":   {
                "name": "OLP",
                "revertive":    true,
                "wait-to-restore-time": 400000,
                "hold-off-time":        10,
                "primary-switch-threshold":     "-3.1",
                "primary-switch-hysteresis":    "1.6",
                "secondary-switch-threshold":   "-3.4",
                "secondary-switch-hysteresis":  "1.6",
                "relative-switch-threshold":    "4.1",
                "relative-switch-threshold-offset":     "0.3",
                "force-to-port":        "PRIMARY",
                "active-path":  "openconfig-transport-line-protection:PRIMARY",
                "com-ops-ext:switch-state":      "NR"
        }
}
```
3. I hope that the node name and value of json data without module name , example :
refer to "state", "active-path",  "switch-state"
```json
{
        "state":   {
                "name": "OLP",
                "revertive":    true,
                "wait-to-restore-time": 400000,
                "hold-off-time":        10,
                "primary-switch-threshold":     "-3.1",
                "primary-switch-hysteresis":    "1.6",
                "secondary-switch-threshold":   "-3.4",
                "secondary-switch-hysteresis":  "1.6",
                "relative-switch-threshold":    "4.1",
                "relative-switch-threshold-offset":     "0.3",
                "force-to-port":        "PRIMARY",
                "active-path":  "PRIMARY",
                "switch-state":      "NR"
        }
}
```
How to use lyd_print_mem ? or other function to realize my expectation.

**Comment by michalvasko** [comment]
You cannot get the output you want with *libyang*, it prints YANG data (in JSON) which require the module names of data.

**Comment by guangjung** [comment]
Hi Micha，Thank you. 
1) For libsysrepo,  have api interface to handle it?
2)  another question:
For yang node of double type,  the lyd_print_mem  output is sting type (example , "primary-switch-threshold":     "-3.1"). Have an method to output double number type?          when I call libyang some interface， invalid  for double type value and valid for string number type value for primary-switch-threshold node .

**Comment by michalvasko** [comment]
1. You mean if *sysrepo* is able to print the data without namespace like you wanted to? Certainly not, *sysrepo* has no low-level YANG functionality, it uses *libyang* for everything like that.
2. Decimal64 values must always be printed as strings per the [specs](https://www.rfc-editor.org/rfc/rfc7951#section-6.1).

**Comment by guangjung** [comment]
thanks!   I got it. Now I have no questions.
