### ISSUE TITLE
Is there an API to  iterate over an ly_node and get the content? 

### ISSUE THREAD

**Issue by MoshikaKarthesan** [CESNET/libyang#1974]
If NO, then how can we iterate over ly_node

**Comment by jktjkt** [comment]
You're probably looking for the `LYD_TREE_DFS_BEGIN` and `LYD_TREE_DFS_END` macros. Look through the source code for usage examples.

**Comment by michalvasko** [comment]
Not sure what exactly you want to iterate over but that @jktjkt mentioned is probably what you mean. To get string value of a `struct lyd_node`, use `lyd_get_value()`.

**Comment by MoshikaKarthesan** [comment]
Thankyou
