### ISSUE TITLE
Question: lyd_eval_xpath

### ISSUE THREAD

**Issue by lioyerar** [CESNET/libyang#1980]
Hello,

I have a question regarding the `lyd_eval_xpath` function, which calls `lyd_eval_xpath3`. Why does the output of this function is a `ly_bool` type? Would it be possible to retain the original value instead of converting it to a boolean by adding a parameter to the function?

**Comment by michalvasko** [comment]
There are 2 variants for the use-cases used in YANG, `lyd_find_xpath()`, which returns a `node-set` and `lyd_eval_xpath()`, which returns `boolean`. There are only `string` and `number` left, what exactly do you need those for?

**Comment by lioyerar** [comment]
My aim is to retrieve the output of the XPath function from my custom libyang plugin

**Comment by michalvasko** [comment]
You have not really answered. Do you really need XPath evaluation with the full variety of result type? It would require extending the API and there is no use-case for it in YANG, which is exactly why there are only those 2 functions.

**Comment by lioyerar** [comment]
In my custom libyang plugin, I'm using an XPath function as an argument, for example: `number(/path/to/leaf)`. My question is, how can I retrieve the returned number value from this function using libyang APIs?

I have tried using `lyd_find_xpath`, but it returns an empty node-set. I have tried using `lyd_eval_xpath`, but it returns a boolean value instead of the expected number value.

While I can use `lyd_find_xpath` on `/path/to/leaf` and then retrieve the value of the leaf using the `lyd_get_value` API, but I need a general solution.

**Comment by michalvasko** [comment]
I see. Then as I said, such a use case is not found in YANG so the API does not support it. I suppose it should not be too much trouble, to add it, so I may do so later, once I finish my current work.

**Comment by michalvasko** [comment]
You should now be able to use the new function `lyd_eval_xpath4()`.

**Comment by lioyerar** [comment]
Thanks, I will test it on my side.
