### ISSUE TITLE
erroneous validation of UNION type

### ISSUE THREAD

**Issue by Haititi** [CESNET/libyang#1981]
Hi,

I did an upgrade of libyang and now i have a problem with union types.
Here is a simple way to reproduce it.

```
module mymodule {
  yang-version 1.1;
  namespace "urn:mymodule";
  prefix mymodule ;

  revision 2023-02-15 {
    description
      "Initial version.";

    reference "";
  }
 
  container mycontainer {
    description
      "my test container.";

    leaf test_union {
      type union {
       type uint32 {
          range "0..1048575";
        }
        type enumeration {
          enum auto {
            description
              "auto enum value.";
          }
        }
      }

      description
        "an union leaf.";
    }
}
```

Then i try to set the following data with netopeer2-cli :
```
<mycontainer xmlns="urn:mymodule">
  <test_union>auto</test_union>
</mycontainer>
```

After setting it, the `test_union` leaf is stored as "0" instead of "auto".
The problem seems to be caused by the following commit : https://github.com/CESNET/libyang/commit/9372871ed84c46d0f7e1811a3062f0e878bd3c0d .
Reverting this commit did solve the problem.

Can you please look at it ?
Thanks !

**Comment by michalvasko** [comment]
Right, thanks for the reproducer. I have not managed to learn the origin of that commit but after I reverted it, all the tests continued to pass. I have also added a test for your use-case so it should never be broken again.

**Comment by Haititi** [comment]
thanks, it's fixed !
