### ISSUE TITLE
wrong parsed ext instance argument and missing inheritance

### ISSUE THREAD

**Issue by Haititi** [CESNET/libyang#1984]
Hi,

I have some problems using extensions.
I have something similar to the following configuration:

```
module my-extensions {
  namespace "urn:my-extensions";
  prefix my-ext;

  revision 2023-02-16 {
    description
      "Initial version.";

    reference ""; 
  }

  extension shortdesc {
    argument shortdsc;
    description
      "Extend a type to specify what should be displayed as short
       description.";
  }
}
```

```
module module-inet {
  yang-version 1.1;
  namespace "urn:module-inet";
  prefix mod-inet;

  import ietf-inet-types {
    prefix inet;
  }

  import my-extensions {
    prefix my-ext;
  }

  revision 2023-02-16 {
    description
      "Initial version.";

    reference "";
  }

  typedef domain-name {
    type inet:domain-name {
      my-ext:shortdesc "<host-name>";
    }
     description "a domain name";
  }

  typedef ipv4-address {
    type inet:ipv4-address-no-zone {
      my-ext:shortdesc "<A.B.C.D>";
    }
    description "An IPv4 address.";
  }
}
```
```
module module-a {
  yang-version 1.1;
  namespace "urn:module-a";
  prefix mod-a;

  import module-inet {
    prefix mod-inet;
  }

  import my-extensions {
    prefix my-ext;
  }

  revision 2023-02-16 {
    description
      "Initial version.";

    reference "";
  }

  typedef server-address {
    type union {
      type mod-inet:ipv4-address {
        my-ext:shortdesc "<ipv4-address>";
      }
      type mod-inet:domain-name {
        my-ext:shortdesc "<fqdn>";
      }
    }
    description "a server address";
  }
}
```
```
module main-module {
  yang-version 1.1;
  namespace "urn:6wind:main-module";
  prefix main;

  import module-a {
    prefix mod-a;
  }

  import module-inet {
    prefix mod-inet;
  }

  import my-extensions {
    prefix my-ext;
  }

  revision 2023-02-16 {
    description
      "Initial version.";

    reference "";
  }

  container config {
    leaf server {
      type mod-a:server-address {
        my-ext:shortdesc "<server-address>"
      }
      description "The address of the server to connect to.";
    }

    leaf hostname {
      type union {
        type mod-inet:domain-name;
        type string;
      }
      description "The hostname of the device.";
    }
  }
}
```

When trying to use this config, i realized few problems:
- I retrieved my module "module-inet" via `ly_ctx_get_module_lastest()` and i checked the list of `lysp_tpdf` typedefs in the parsed module to retrieve my "domain-name" typedef. Here i could find it, and i also found my extension instance in its base `type`, but I was surprised to see that the parsed extension instance had the argument "< fqdn >" instead of "< host-name >".
- the `lysc_node_leaf` "/config/hostname" is an union type, and when i loop over the different types that i find in its `lysc_type_union`, in can indeed find the two types "mod-inet:domain-name" and "string", but the "mod-inet:domain-name"  has no extension instances. Shouldn't i find my extension "my-ext:shortdesc" in it ?

It seems the extension instances are not inherited from the base type, while i believe it shoud ...?
Moreover, the arguments of the parsed extension instances seem to be overwritten/not updated.

Can you please look at it ?
Thanks a lot!

**Comment by Haititi** [comment]
After further analysis, i could find the problem in `lys_compile_type()` function.
You try to reuse the `lysc_type *base` whenever it is possible.
But in case of defined extensions in the `typedef`, this should not be allowed, because you would end up compiling these extensions in `base`, which would affect other nodes.

Moreover, i found out that `lysc_ext_instance_dup()` is not implemented and is marked as `TODO`.
This would be need as i think it should be used in `lys_compile_type_()` in order to duplicate the extension instances from base (`(*type)->exts = lysc_ext_instance_dup(ctx->ctx, base->exts);`).

The following (but incomplete) patch should help :
```
diff --git a/src/schema_compile_node.c b/src/schema_compile_node.c
index 0b64dcb9e1e7..66b9d1d98a42 100644
--- a/src/schema_compile_node.c
+++ b/src/schema_compile_node.c
@@ -2196,7 +2196,7 @@ preparenext:
         assert(plugin);
 
         if ((basetype != LY_TYPE_LEAFREF) && (u != tpdf_chain.count - 1) && !(tctx->tpdf->type.flags) &&
-                (plugin == base->plugin)) {
+                (plugin == base->plugin) && !(base->exts) && !(tctx->tpdf->type.exts)) {
             /* no change, reuse the compiled base */
             ((struct lysp_tpdf *)tctx->tpdf)->type.compiled = base;
             LY_ATOMIC_INC_BARRIER(base->refcount);
@@ -2234,7 +2234,7 @@ preparenext:
     ctx->tpdf_chain.count = ctx->tpdf_chain.count - tpdf_chain.count;
 
     /* process the type definition in leaf */
-    if (type_p->flags || !base || (basetype == LY_TYPE_LEAFREF)) {
+    if (type_p->flags || type_p->exts || !base || (basetype == LY_TYPE_LEAFREF)) {
         /* get restrictions from the node itself */
         (*type)->basetype = basetype;
         (*type)->plugin = base ? base->plugin : lyplg_type_plugin_find("", NULL, ly_data_type2str[basetype]);

```

I hope it helps !

**Comment by michalvasko** [comment]
No need for the patch but thanks for the effort, I knew where the problem was but it took time to successfully and properly fix and improve everything that needed it. Note that this exact use-case has been added to tests and is now supported but it is possible some fairly similar one would not work as expected. Let me know in that case, these extensions can only be implemented ad-hoc because it is impossible to support everything since extensions can do absolutely anything.
