### ISSUE TITLE
ietf-yang-types:date-and-time does not satisfy the constraint.

### ISSUE THREAD

**Issue by Sarathkv99** [CESNET/libyang#1992]
**I'm getting an error in yang type:date-and-time, even if the format is correct. I will leave the log file comments below 

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
ERR (SR_OP): DATE:TIME - 2000-11-04T02:47:38Z
[ERR]: Value "2000-11-04T02:47:38Z" does not satisfy the constraint "\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(Z|[\+\-]\d{2}:\d{2})" (range, length, or pattern). (path: /ietf-netconf-server:anchor-time)
[ERR]: Failed to create node "anchor-time" as a child of "periodic". (path: /ietf-netconf-server:netconf-server/call-home/netconf-client[name='default-client-1']/connection-type/periodic/anchor-time)
[ERR]: Invalid datastore edit.
ERR (SR_OP): Failed to set Anchor-Time for call-home
[ERR]: Unknown error
[WRN]: Event "change" with ID 1 priority 0 failed (Unknown error).
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
@michalvasko Can you please help me with this one.**

**Comment by michalvasko** [comment]
What *libyang* version are you using? I have successfully stored the date from your logs.

**Comment by Sarathkv99** [comment]
> What _libyang_ version are you using? I have successfully stored the date from your logs.

libyang (v2.1.30), 
libnetconf2 (v2.1.28) and sysrepo (v2.2.36).
netopeer2 Version 2.1.49

**Comment by Sarathkv99** [comment]
> That is still recent so it should work. Can you provide the steps to reproduce it?

I am trying to set the anchor-time as the current date of the system using sr_set_item_str API. But it is showing the pattern mismatch error.

**Comment by michalvasko** [comment]
Have actually reproduced the error but it is correct and it is my fault for not checking the message properly. In particular, `anchor-time` is restricted to minute-level granularity so you cannot set seconds.

**Comment by Sarathkv99** [comment]
> Have actually reproduced the error but it is correct and it is my fault for not checking the message properly. In particular, `anchor-time` is restricted to minute-level granularity so you cannot set seconds.
The pattern mentioned in ietf-yang-type.yang model and ietf-netconf-server.yang model are conflicting when trying to set the anchor-time. When try to follow the pattern as per the ietf-netconf-server.yang type, error is coming from the pattern of ietf-yang-type.yang and vice versa.

> typedef date-and-time {                                           
>     type string {                                                   
>       pattern '\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?'         
>             + '(Z|[\+\-]\d{2}:\d{2})';                              
>     }                                                               
>     leaf anchor-time {
>                   type yang:date-and-time {
>                     pattern "\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}(Z|[\\+\\-]\\d{2}:\\d{2})";
>                   }
Here are the logs.
libyang error: Unsatisfied pattern - "1985-04-12T23:20:50.52Z" does not conform to "\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(Z|[\+\-]\d{2}:\d{2})". (Data location "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='default-client-9']/connection-type/periodic/anchor-time", line number 42.)
libyang error: Unsatisfied pattern - "1985-04-12T23:20Z" does not conform to "\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[\+\-]\d{2}:\d{2})". (Data location "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='default-client-9']/connection-type/periodic/anchor-time", line number 42.)

**Comment by michalvasko** [comment]
Just letting you know that this turned out to be quite a serious issue in the standardized YANG modules and the new revisions will have this problem fixed. Once the update is official, I will probably just take that isolated change and fix the modules used by *netopeer2* to make it possible to set this value.

**Comment by saraaibak** [comment]
Hi @michalvasko, It would be appreciated if you could let us know when we can expect the fix for this issue.

**Comment by michalvasko** [comment]
Okay, should be fixed in latest *netopeer2* based on what has been said in the mailing list about the fix to this issue.
