### ISSUE TITLE
What came down to the interfaces-state callback functions changed

### ISSUE THREAD

**Issue by kqz2022** [CESNET/libyang#1993]
When we sent the same RPC into old and new netopeer2/libyang/libnetconf2/sysrepo releases, the arguments came down to the  interfaces-state callback functions changed.

The releases used were:
(1) https://github.com/CESNET/netopeer2/releases/tag/v2.1.23
(2) https://github.com/CESNET/netopeer2/releases/tag/v2.1.49 

The RPC used was:
`<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="21">`
`    <get>`
`        <filter type="xpath"`
`            xmlns:if="urn:ietf:params:xml:ns:yang:ietf-interfaces"`
`            select="/if:interfaces-state/if:interface[starts-with(if:name, 'abc')]">`
`        </filter>`
`    </get>`
`</rpc>`

The module_name and path came down to the interfaces-state callback function stayed the same.
`module_name=ietf-interfaces path=/ietf-interfaces:interfaces-state/interface`

But, the request_xpath changed:
(1) `request_xpath=/ietf-interfaces:*`
(2) `request_xpath=/ietf-interfaces:interfaces-state/interface[starts-with(name,'abc')]`

Question: is this change of behavior intentional?

In the past, we relied on libyang to do the filtering for "starts-with", "contains", etc. Although performance was not optimal, we avoided duplicating the filtering functionality into our application code.

**Comment by michalvasko** [comment]
> In the past, we relied on libyang to do the filtering for "starts-with", "contains", etc.

You can still do that, the filtering will occur no matter what you return. But by now having the exact filter passed to the callback, it has the option to not return redundant data making it possibly much faster. But the callback can return all the `ietf-interfaces` data just like before.
