### ISSUE TITLE
in lyxml_parse_elem function, the memcpy out-of-bounds read

### ISSUE THREAD

**Issue by olderqi** [CESNET/libyang#1996]
version ：1.0.240

When processing the xml message '<m:d></ddddddddddd:m>', in lyxml_parse_elem, the prefix is 'm',  line 1059, c is 'ddddddddddd:m>', e-c is 16, in memcmp(prefix, c, e - c), the prefix out-of-bounds read

**Comment by michalvasko** [comment]
Update your version, the one you are using is completely obsolete.
