### ISSUE TITLE
ly ERROR: Failed to resolve prefix "ietf-hardware".

### ISSUE THREAD

**Issue by peigaoxu** [CESNET/libyang#1998]
Hi,
I logged into netopeer2-server with root account in the same device and configured the ietf-netconf-acm module with the following xml to try to control the access rights of the netconfaccount.
 After that, I connect to netopeer2-server locally with dasUser account, and I can get the information by using get --filter-xpath /ietf-hardware:hardware/*, if I log out of netconf and reconnect at this point, I get the following error message using the same command.
error message:
```
> get --filter-xpath /ietf-hardware:hardware/*
ly ERROR: Failed to resolve prefix "ietf-hardware".
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  Storing value "" failed.

> 
```
Used xml:
```xml
<nacm xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-acm">
    <enable-nacm>true</enable-nacm>
    <read-default>deny</read-default>
    <write-default>deny</write-default>
    <exec-default>deny</exec-default>
    <enable-external-groups>false</enable-external-groups>
    <groups>
        <group>
            <name>sudo</name>
            <user-name>netconf</user-name>           
        </group>
     </groups>
     <rule-list>
        <name>SUDO_RULE</name>
        <group>sudo</group>
        <rule>
            <name>RULE1</name>
            <module-name>ietf-netconf</module-name>
            <access-operations>*</access-operations>
            <action>permit</action>
        </rule>
        <rule>
            <name>RULE2</name>
            <module-name>notifications</module-name>
            <access-operations>*</access-operations>
            <action>permit</action>
        </rule>
        <rule>
            <name>RULE3</name>
            <module-name>ietf-hardware</module-name>
            <access-operations>read</access-operations>
            <action>permit</action>
        </rule>
     </rule-list>
</nacm>
```
version:
netopeer2-2.0.35
libyang-2.0.112
libnetconf2-2.0.24
sysrepo-2.0.53

Do you have a way to solve this problem? Maybe I have an error somewhere? I don't know why libyang has this error....

Best Regards.

Peigao

**Comment by michalvasko** [comment]
The error message is definitely some internal problem but you are using a really old versions of our software so I do not think I can help you, you will have to update it first to the latest release.

**Comment by peigaoxu** [comment]
Okay, thank you for your reply!

**Comment by peigaoxu** [comment]
Hi,
I have deployed the latest version and am experiencing the same problem.

> 1, I first configured the ietf-netconf-server module with read access (deny)
<nacm xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-acm">
    <enable-nacm>true</enable-nacm>
    <read-default>deny</read-default>
    <write-default>deny</write-default>
    <exec-default>deny</exec-default>
    <enable-external-groups>false</enable-external-groups>
    <groups>
        <group>
            <name>sudo</name>
            <user-name>user</user-name>         
        </group>
     </groups>
     <rule-list>
        <name>SUDO_RULE</name>
        <group>sudo</group>
        <rule>
            <name>RULE1</name>
            <module-name>ietf-netconf</module-name>
            <access-operations>*</access-operations>
            <action>permit</action>
        </rule>
        <rule>
            <name>RULE2</name>
            <module-name>notifications</module-name>
            <access-operations>*</access-operations>
            <action>permit</action>
        </rule>
        <rule>
            <name>RULE8</name>
            <module-name>o-ran-delay-management</module-name>
            <access-operations>read</access-operations>
            <action>permit</action>
        </rule>
        <rule>
            <name>RULE9</name>
            <module-name>ietf-netconf-server</module-name>
            <access-operations>read</access-operations>
            <action>deny</action>
        </rule>
     </rule-list>
</nacm>

> 2, I logged in to the user account and queried the ietf-netconf-server module for information, and was prompted as follows.
![企业微信截图_16862143149097](https://github.com/CESNET/libyang/assets/104612620/5f987873-d8e9-488d-acc0-0efeaa79ea20)
This is as expected.

> 3, I logged out of my usr account and after logging back in, there was a problem.

![企业微信截图_16862144321133](https://github.com/CESNET/libyang/assets/104612620/f7ec5fa6-3aee-40f4-a5a3-29a78351da13)

Is this as expected?

**Comment by michalvasko** [comment]
> Is this as expected?

Yes, it is. Run `verb verbose` before connecting and it should print all the problems it encounters when creating the NETCONF session that result in all YANG 1.1 modules missing in the client context and the error you see.

**Comment by michalvasko** [comment]
> Sorry, I don't quite understand what you mean. Are you saying that it is caused by me running verb verbose? But actually I didn't run it, I just reconnected to the server.

No, I said you **should** enable verbose output to see the error that is causing your problem. You have too strict NACM rules and the client is not even able to download YANG modules from the server hence the error about a prefix being not known.

**Comment by peigaoxu** [comment]
Hi,
Here is some information I got after executing "verb verbose".

> root@9611c2ea3609:/# netopeer2-cli
> > verb verbose
> > connect --login dasuser
> nc VERBOSE: Trying to connect via IPv4 to 127.0.0.1:830.
> nc VERBOSE: Successfully connected to localhost:830 over IPv4.
> [2023/06/21 01:15:12.331740, 2] ssh_connect:  libssh 0.10.5 (c) 2003-2023 Aris Adamantiadis, Andreas Schneider and libssh contributors. Distributed under the LGPL, please refer to COPYING file for information about your rights, using threading threads_pthread
> [2023/06/21 01:15:12.331765, 2] ssh_connect:  Socket connecting, now waiting for the callbacks to work
> [2023/06/21 01:15:12.331776, 1] socket_callback_connected:  Socket connection callback: 1 (0)
> [2023/06/21 01:15:12.333919, 2] ssh_client_connection_callback:  SSH server banner: SSH-2.0-libssh_0.10.5
> [2023/06/21 01:15:12.333944, 2] ssh_analyze_banner:  Analyzing banner: SSH-2.0-libssh_0.10.5
> [2023/06/21 01:15:12.335428, 1] ssh_known_hosts_read_entries:  Failed to open the known_hosts file '/etc/ssh/ssh_known_hosts': No such file or directory
> [2023/06/21 01:15:12.335497, 2] ssh_kex_select_methods:  Negotiated curve25519-sha256,rsa-sha2-512,chacha20-poly1305@openssh.com,chacha20-poly1305@openssh.com,aead-poly1305,aead-poly1305,none,none,,
> [2023/06/21 01:15:12.337422, 2] ssh_init_rekey_state:  Set rekey after 134217728 blocks
> [2023/06/21 01:15:12.337448, 2] ssh_init_rekey_state:  Set rekey after 134217728 blocks
> [2023/06/21 01:15:12.337539, 2] ssh_packet_client_curve25519_reply:  SSH_MSG_NEWKEYS sent
> [2023/06/21 01:15:12.337562, 2] ssh_packet_newkeys:  Received SSH_MSG_NEWKEYS
> [2023/06/21 01:15:12.337670, 2] ssh_packet_newkeys:  Signature verified and valid
> [2023/06/21 01:15:12.339537, 1] ssh_packet_userauth_failure:  Access denied for 'none'. Authentication that can continue: publickey,password
> [2023/06/21 01:15:12.339591, 2] ssh_packet_userauth_failure:  Access denied for 'none'. Authentication that can continue: publickey,password
> nc VERBOSE: Publickey athentication.
> nc VERBOSE: No key pair specified.
> nc WARNING: Authentication denied.
> nc VERBOSE: Password authentication (host "localhost", user "dasuser").
> dasuser@localhost password:
> nc VERBOSE: Authentication successful.
> [2023/06/21 01:15:14.498301, 2] channel_open:  Creating a channel 43 with 64000 window and 32768 max packet
> [2023/06/21 01:15:14.498567, 2] ssh_packet_channel_open_conf:  Received a CHANNEL_OPEN_CONFIRMATION for channel 43:43
> [2023/06/21 01:15:14.498599, 2] ssh_packet_channel_open_conf:  Remote window : 32000, maxpacket : 35000
> [2023/06/21 01:15:14.498891, 2] grow_window:  growing window (channel 43:43) to 1280000 bytes
> [2023/06/21 01:15:14.498920, 2] channel_request:  Channel request subsystem success
> ly VERBOSE: Searching for "ietf-inet-types" in "/".
> ly VERBOSE: Newer revision than "ietf-inet-types@2013-07-15" not found, using this as the latest revision.
> ly VERBOSE: Searching for "ietf-yang-types" in "/".
> ly VERBOSE: Newer revision than "ietf-yang-types@2013-07-15" not found, using this as the latest revision.
> nc VERBOSE: Capability for <get-schema> support found.
> nc VERBOSE: Capability for yang-library support found.
> nc VERBOSE: Capability for XPath filter support found.
> nc VERBOSE: Capability for NMDA RPCs support not found.
> nc VERBOSE: Reading module "ietf-netconf@<latest>" from local file "/usr/local/share/yang/modules/netopeer2/ietf-netconf@2013-09-29.yang".
> nc VERBOSE: Reading module "ietf-netconf-acm@2018-02-14" from local file "/usr/local/share/yang/modules/netopeer2/ietf-netconf-acm@2018-02-14.yang".
> nc VERBOSE: Reading module "ietf-yang-metadata@2016-08-05" from local file "/usr/local/share/yang/modules/libyang/ietf-yang-metadata@2016-08-05.yang".
> nc VERBOSE: Reading module "ietf-yang-library@2019-01-04" from local file "/usr/local/share/yang/modules/libyang/ietf-yang-library@2019-01-04.yang".
> nc VERBOSE: Unable to identify revision of the import module "ietf-datastores" from the available server side information.
> nc VERBOSE: Reading module "ietf-datastores@<latest>" from server via get-schema.
> [2023/06/21 01:15:14.503597, 2] channel_rcv_change_window:  Adding 1248206 bytes to channel (43:43) (from 31782 bytes)
> nc WARNING: Received an unexpected reply to <get-schema>:
> <rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
>   <rpc-error>
>     <error-type>protocol</error-type>
>     <error-tag>access-denied</error-tag>
>     <error-severity>error</error-severity>
>     <error-path>/ietf-netconf-monitoring:get-schema</error-path>
>     <error-message xml:lang="en">Executing the operation is denied because "dasuser" NACM authorization failed.</error-message>
>   </rpc-error>
> </rpc-reply>
> 
> nc VERBOSE: Reading module "ietf-datastores@<latest>" from local file "/usr/local/share/yang/modules/netopeer2/ietf-datastores@2018-02-14.yang".
> nc WARNING: No data in reply to a <get> RPC.
> nc VERBOSE: Trying to use capabilities instead of ietf-yang-library data.
> nc VERBOSE: Reading module "sysrepo-plugind@2022-08-26" from local file "/usr/local/share/yang/modules/sysrepo/sysrepo-plugind.yang".
> nc VERBOSE: Reading module "ietf-netconf-with-defaults@2011-06-01" from local file "/usr/local/share/yang/modules/sysrepo/ietf-netconf-with-defaults.yang".
> nc VERBOSE: Reading module "ietf-netconf-notifications@2012-02-06" from local file "/usr/local/share/yang/modules/sysrepo/ietf-netconf-notifications.yang".
> nc VERBOSE: Reading module "nc-notifications@2008-07-14" from local file "/usr/local/share/yang/modules/netopeer2/nc-notifications@2008-07-14.yang".
> nc VERBOSE: Reading module "notifications@2008-07-14" from local file "/usr/local/share/yang/modules/netopeer2/notifications@2008-07-14.yang".
> nc VERBOSE: Reading module "ietf-x509-cert-to-name@2014-12-10" from local file "/usr/local/share/yang/modules/netopeer2/ietf-x509-cert-to-name@2014-12-10.yang".
> nc VERBOSE: Reading module "iana-crypt-hash@2014-08-06" from local file "/usr/local/share/yang/modules/netopeer2/iana-crypt-hash@2014-08-06.yang".
> nc VERBOSE: Reading module "iana-if-type@2017-01-19" from server via get-schema.
> nc WARNING: Received an unexpected reply to <get-schema>:
> <rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="3">
>   <rpc-error>
>     <error-type>protocol</error-type>
>     <error-tag>access-denied</error-tag>
>     <error-severity>error</error-severity>
>     <error-path>/ietf-netconf-monitoring:get-schema</error-path>
>     <error-message xml:lang="en">Executing the operation is denied because "dasuser" NACM authorization failed.</error-message>
>   </rpc-error>
> </rpc-reply>
> 
> nc WARNING: Failed to load module "iana-if-type@2017-01-19".
> nc WARNING: No data in reply to a <get> RPC.
> nc WARNING: Some modules failed to be loaded, any data from these modules (and any other unknown) will be ignored.
> >
> >
> > get
> DATA
> <data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"/>
> 
> > get --filter-xpath /ietf-netconf-server:*
> ly ERROR: Failed to resolve prefix "ietf-netconf-server".
> ERROR
>   type:     application
>   tag:      operation-failed
>   severity: error
>   message:  Storing value failed.

**Comment by michalvasko** [comment]
I have told you everything in my last reply, the log just confirms it, I have nothing more to add.
