### ISSUE TITLE
The number of ly_ctx is limited to PTHREAD_KEY_MAX (1024)

### ISSUE THREAD

**Issue by tieliao** [CESNET/libyang#2000]
As such it is not possible to open more than 1024 netconf connections if they do not use a shared yang context. High scalability is often necessary for network managers.

To deal with this issue, I propose 2 solutions:
**Solution 1**: add a shared or not-shared flag to ly_ctx_new(options), if (shared), call pthread_key_create(). After creation, use pthhread key or memory pointer according to that flag. By default it can be shared.
**Solution 2**:  add a hash table in ly_ctx to manage key/value locally, roughly
```C
    struct ly_ctx {
        struct thread_key {
           struct thread_key *next;
           pthread_t th_id;
	   void *value;
    } **key_hash_tab;
```
To store a value, hash pthread_id (need mutex)
```C
    void set_specific(ctx, eitem) {
        pthread_t th_id = pthread_self();
        int hash = hash_thread_id(th_id);
        struct thread_key *key = ctx->key_hash_tab[hash];

        for (key; key; key = key->next) {
            if (key->th_id == th_id)
                break;
        }
        if (key)
            key->value = eitem;
        else {
            allocate_entry();
            add_entry_to_hash_tab();
        }
    }
```
To destroy the context, free hash table entries.
What do you think about?

**Comment by michalvasko** [comment]
Fine, seems you were set on getting this fixed although I am still not convinced it was really needed. It should now be possible to create more than 1024 contexts in a process.

**Comment by tieliao** [comment]
Hi Michal,
> seems you were set on getting this fixed although I am still not convinced it was really needed.
There is a real need for high scalability in management servers, even for much more than 1k devices. I just want to give my 2 cents to your project. I wonder if I'm the only one who encountered this issue.

> It should now be possible to create more than 1024 contexts in a process.
Do you mean that is possible with the newer versions of libnetconf2 and libyang?
At the moment I use my dirty patches and can create more than 1024 contexts. There could be other solutions better than what I proposed above.

**Comment by michalvasko** [comment]
I have referenced the commit in *libyang* that allows creating more contexts, so just use the `devel` branch and it should work without any patches.

**Comment by tieliao** [comment]
Thanks, I'll try
