### ISSUE TITLE
libyang make failed

### ISSUE THREAD

**Issue by Sarathkv99** [CESNET/libyang#2001]
> [ 77%] Built target yangobj
> [ 78%] Linking C shared library libyang.so
> /usr/bin/ld: /usr/local/lib/libpcre2-8.a(pcre2_compile.c.o): warning: relocation against `_pcre2_callout_start_delims_8' in read-only section `.text'
> /usr/bin/ld: /usr/local/lib/libpcre2-8.a(pcre2_compile.c.o): relocation R_X86_64_PC32 against symbol `_pcre2_utt_size_8' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: final link failed: bad value
> collect2: error: ld returned 1 exit status
> make[2]: *** [CMakeFiles/yang.dir/build.make:224: libyang.so.2.29.2] Error 1
> make[1]: *** [CMakeFiles/Makefile2:164: CMakeFiles/yang.dir/all] Error 2
> make: *** [Makefile:136: all] Error 2

i came up with this error while installing the libyang. 
@michalvasko can you please help me with this one.

**Comment by michalvasko** [comment]
It seems you are trying to use static `libpcre2` library and compile it with a shared *libyang* library. That should be possible but probably requires some additional parameters, I have never tried it so I cannot really help. But if you want to create a static *libyang* library, just use `-DENABLE_STATIC=ON` and it should compile without problems with the static *libpcre2*.
