### ISSUE TITLE
Unknown module of node "is-router" error message

### ISSUE THREAD

**Issue by mblacksee** [CESNET/libyang#2002]
Hi Michal,
I've started to observe below error message right after switching new versions of libyang/sysrepo/libnetconf2/netopeer2 libraries;
```
sta:~$ sysrepocfg -X -f json -d operational -m ietf-interfaces -v3
[INF] Connection 1395 created.
[INF] Session 42511 (user "root", CID 1395) created.
[WRN] Schema node "v1" not found; in expr "snmp:v1" with context node "/ietf-snmp:snmp/target".
[WRN] Schema node "v2c" not found; in expr "snmp:v1 or snmp:v2c" with context node "/ietf-snmp:snmp/target".
[ERR] Unknown module of node "is-router". (Data location "/ietf-interfaces:interfaces/interface[name='br0']/ietf-ip:ipv6/neighbor[ip='fe80::539c:76bb:6ee5:7ece']".)
[ERR] Applying operation "merge" failed.
sysrepocfg error: Getting data failed (libyang error)
[INF] No datastore changes to apply.
sta:~$ 
```
Library versions are as below;
libyang: From 2.0.231 to 2.1.61
sysrepo: From 2.1.84 to 2.2.66
netopeer2: From 2.1.36 to 2.1.61
libnetconf2: From 2.1.18 to 2.1.31

What might be the problem here?

Thanks in advance.
BR.

**Comment by mblacksee** [comment]
Hi Michal,
As you said I've already exported startup configuration as below;
`sysrepocfg --verbosity 3 --datastore startup --format json --export=/<permenant_dir_path>/startup.json`
And then copied as below;
 `sysrepocfg -f json -d running -n -C /<permanent_dir_path>/startup.json -v3`
 `sysrepocfg -C running -d startup -v3`
 
 Actually there are two separate daemon in the system where one of them is capable to write the path `/ietf-interfaces:interfaces/interface[name='br0']/ietf-ip:ipv6/neighbor[ip='fe80::539c:76bb:6ee5:7ece']` even after libraries upgraded and the other one try to read from the same path. But the reader daemon complains with above libyang error message.

BR.

**Comment by michalvasko** [comment]
What *daemon* creates the `is-router` node in the `operational` datastore? Ideally, you can share the code creating it in a get oper data callback or setting it (probably using `sr_set_item_str()`) as stored operational data.

**Comment by michalvasko** [comment]
Right, should be fixed in the latest *libyang* `devel`.
