### ISSUE TITLE
yanglint spits "error libyang err : Internal error" when parsing an XPath expression

### ISSUE THREAD

**Issue by gertsvolf** [CESNET/libyang#2003]
Greetings, 
We have a model with reusable groupings and an XPath expression in a "when" constraint with a condition on the name of the enclosing model element. The "when" constraint is designed to suppress leaves in a grouping depending on where in the hierarchy the grouping is used.

When validating the model yanglint 2.1.30 throws an error:
libyang err : Internal error (xpath.c:155).

The following is the most simple model demonstrating the problem:
```
module test-simple {
  yang-version 1.1;
  namespace "http://cisco.com/ns/yang/test";
  prefix test-ns;

  revision 2020-07-01 {
    description
      "Initial revision";
    reference
      "1.0.0";
  }

  container test-data {
    leaf stamp {
      when "(current()[local-name() = 'stamp'])";
      type string;
    }
    leaf time-stamp {
      when "(parent::node()[local-name() = 'test-data'])";
      type string;
    }
  }
}
```

yanglint test-simple.yang
libyang err : Internal error (libyang/libyang-master/src/xpath.c:155).
libyang err : Internal error (libyang/libyang-master/src/xpath.c:155).

**Comment by michalvasko** [comment]
Fixed in the latest *libyang* `devel`.

**Comment by gertsvolf** [comment]
Thank you for your quick action, Michal.
I verified the fix with our more complex model and it works well.
