### ISSUE TITLE
libyang cores (asserts) on invalid xpath value.

### ISSUE THREAD

**Issue by choppsv1** [CESNET/libyang#2007]
Try and do a `lys_find_path()` using a key string value w/o quotes, code assumes correctly formatted xpaths and asserts when not the case.

```
#include <err.h>
#include <assert.h>
#include <libyang/libyang.h>


int main(int argc, char **argv)
{
	struct ly_ctx *ctx;
	struct lys_module *mod;
	const struct lysc_node *snode;
	LY_ERR err;
	const char *yang_data = ""
	    "module a {"
	    "  namespace urn:a;"
	    "  prefix a;"
            "  list l { "
	    "    key k;"
	    "    leaf k {"
	    "      type string;"
	    "    }"
	    "  }"
            "}";

	err = ly_ctx_new(NULL, 0, &ctx);
	assert(!err);
	err = lys_parse_mem(ctx, yang_data, LYS_IN_YANG, &mod);
        if (err)
		errx(1, "lys_parse_mem: %s", ly_errmsg(ctx));

	/* will assert/abort from lack of quotes around key value `foo` */
	snode = lys_find_path(ctx, NULL, "/a:l[k=foo]", 1);
        if (!snode)
		errx(1, "lys_find_path: %s", ly_errmsg(ctx));
	return 0;
}
```

**Comment by michalvasko** [comment]
Thanks, fixed, seems the code had not been updated when it should have and the wrong parsing function has been used.

**Comment by choppsv1** [comment]
Will this get into a release soonish? Right now I need to use `lys_find_xpath` which is taking up ~15.3% of my runtime whereas `lys_find_path` with this fix takes up ~9.3% (the older code was ~8% but it's not useful since it crashes :)

**Comment by michalvasko** [comment]
I would a release some time next month, the latest is still fairly recent. I have also used the opportunity to try to optimize a function that would make a difference, it seems it would to you. And there was an inefficiency with a fairly simple fix so it should now be somewhat faster.

**Comment by choppsv1** [comment]
FRR has a release feature freeze occurring on 5/23/23, so if you are planning on doing a release in May prior to that date it would certainly be very welcome by us. :)

**Comment by michalvasko** [comment]
We may do a release before that, it would fit the loose schedule we follow.

**Comment by choppsv1** [comment]
`lys_find_xpath(... &set);` is crashing for me when I compile Debug version of the library and I do not initialize the `struct lys_set *set;` to NULL.

**Comment by michalvasko** [comment]
There were some error paths that could result in that, should be fixed.
