### ISSUE TITLE
why json parser not support rpc/rpc-reply in libyang2?

### ISSUE THREAD

**Issue by lyzliyuzhi91** [CESNET/libyang#2014]
If json parser does not suppprt parsing rpc in libyang2, how restconf send rpcs such as lock/commit or self-defined operations like "reboot" ?

**Comment by michalvasko** [comment]
> If json parser does not suppprt parsing rpc in libyang2

It does support parsing everything in both XML and JSON. Use `LYD_TYPE_RPC_YANG` for `lyd_parse_op()`.

But yes, `LYD_TYPE_RPC_NETCONF` is specific for NETCONF and must use XML. The RESTCONF "extension" when the input/output parameters are enclosed in an `input`/`output` object/element is not supported so you would have to preprocess that before *libyang* is able to parse it. I may add new enum values and support these use-cases directly once I have some spare time.

**Comment by lyzliyuzhi91** [comment]
get, thank you
