### ISSUE TITLE
`anyxml`: different paths obtained from JSON and XML

### ISSUE THREAD

**Issue by jktjkt** [CESNET/libyang#2015]
These two inputs are equivalent; libyang can load either, and when asked to save in the other format, the exact same string is produced:
- `<ax xmlns="http://example.com/coze"><x>1</x><x>2</x><x>3</x></ax>`
- `{"example-schema:ax":{"x":[1,2,3]}}`

But when I iterate over the content of the resulting data nodes and call `lyd_path` on them, the version which was read from XML returns `/example-schema:x`, and the version read from JSON returns just `/x`. I think that both of these should behave in the same way.

**Comment by michalvasko** [comment]
Fine, the module name should now be inherited.
