### ISSUE TITLE
module yang is missing yang-version information

### ISSUE THREAD

**Issue by Zephyre777** [CESNET/libyang#2022]
I parse and store locally the module yang. I tried to use pyang to check the module correctness. But it raised some errors saying that:
```
yang.yang:80: error: the type "empty" (defined at yang.yang:81) cannot be part of a union
yang.yang:92: error: the type "empty" (defined at yang.yang:93) cannot be part of a union
yang.yang:158: error: the type "empty" (defined at yang.yang:159) cannot be part of a union
yang.yang:167: error: the type "empty" (defined at yang.yang:168) cannot be part of a union
```
I added ```yang-version 1.1;``` at the beginning of the module yang file and the error disappears. 
Maybe there is an issue with the specification of module?

**Comment by michalvasko** [comment]
Okay, hopefully adding the version will not cause too many problems.
