### ISSUE TITLE
Is it possible to use if-feature for ranges in yang?

### ISSUE THREAD

**Issue by MoshikaKarthesan** [CESNET/libyang#2025]
Suppose I have 3 features defined in yang. 
For the same leaf node( be it an integer) , I want 3 different ranges according to the feature which is defined.
Is it possible to use if-feature for ranges in yang, else is there any other option to implement this type of requirement.

**Comment by michalvasko** [comment]
No, you cannot use features directly this way. But with some creativity it should be possible to come up with a solution. One would be to define the leaf with the largest range in a grouping. Then, use this grouping at 3 different places with the corresponding `if-feature` statements and when needed, add a `refine` statement that adds a `must` statement that limits the range to the desired interval (or you do not even have to define any `range` and just use a `must` for all 3 cases). It is a bit cumbersome and maybe some other solutions would be possible. Generally, it should always be possible to enforce such limitations directly in the software handling the data, *sysrepo* allows to refuse data changes for any reason.

**Comment by MoshikaKarthesan** [comment]
Thanks for the solution
