### ISSUE TITLE
I think it should substitue prefix with snode->module->name when prefix is null inside lydjson_parse_instance function.

### ISSUE THREAD

**Issue by lyzliyuzhi91** [CESNET/libyang#2029]
https://github.com/CESNET/libyang/blob/9a4e5b2ce30b9696116d6e654ee55caab5aafed8/src/parser_json.c#L1491

I think it should substitue `prefix` with `snode->module->name` when prefix is null inside `lydjson_parse_instance` function, otherwise, when I call `lyd_parse_opaq_error` to check why it is opaq, it will go into 
```
    if (!opaq->name.module_ns) {
        LOGVAL(ctx, LYVE_REFERENCE, "Unknown module of node \"%s\".", opaq->name.name);
        return LY_EVALID;
    }
```
But actually, i can find schema node inside the call `lydjson_parse_instance`. That means `lyd_parse_opaq_error` reports an incorrect error info.
Thanks.

**Comment by michalvasko** [comment]
This was supposed to be handled but there was a bug causing it not to work, please try it with the latest *libyang* and it should work.

**Comment by lyzliyuzhi91** [comment]
OK, thanks
