### ISSUE TITLE
Missing forward declaration of struct ly_ht

### ISSUE THREAD

**Issue by rjarry** [CESNET/libyang#2032]
Hi all,

I noticed that `struct ly_ht` is only defined in `src/hash_table_internal.h` (not available for external programs that link against libyang). However it is referenced in multiple public API headers. I am puzzled that everything manages to compile without warnings.

I have gone over the C standards and it seems to me that referencing a struct pointer without a forward (or explicit) declaration produces a compilation warning:

```
$ cat warn.c 
int foo(struct pouet *p);
$ gcc -o warn.o -c warn.c
warn.c:1:16: warning: ‘struct pouet’ declared inside parameter list will not be visible outside of this definition or declaration
    1 | int foo(struct pouet *p);
      |                ^~~~~
```

Am I missing something?

Thanks

**Comment by michalvasko** [comment]
Hm, I am as confused as you are and the missing warning is the reason I have missed this initially and compiled other programs using this hash table without any problems. Should be fixed, in any case, I believe there should be a declaration.

**Comment by rjarry** [comment]
I'm glad I am not the only one confused then :)

Thanks Michal :+1:
