### ISSUE TITLE
lyd_parse_data_mem parse unit64 failed while using LYD_PARSE_ONLY | LYD_PARSE_OPAQ

### ISSUE THREAD

**Issue by zhuxiaoyun138159** [CESNET/libyang#2033]
```C
const char *string =
        "{"
           "\"ydb-test-common:interfaces\": {"
               "\"interface\":["
                   "{"
                       "\"name\": \"eth1\",\"uint64\":0,\"description\":\"test\""
                   "}"
               "]"
           "}"
       "}";
```
```yang
container interfaces {
    description
      "Interface parameters.";
    list interface {
      key "name";
      ordered-by user;
      leaf name {
        type string;
      }
      leaf uint64 {
        type uint64 {
          range "0..64";
        }
      }
      leaf description {
        type string;
      }
    }
  }
```
In earlier versions, the lyd_parse_mem(LYD_OPT_TRUSTED) interface of libyang1 can successfully parse character strings.However, now I use libyang2's lyd_parse_data_mem(LYD_PARSE_ONLY | LYD_PARSE_OPAQ) interface parsing fails.The following error message is displayed:
```
libyang[0]: Invalid non-num64-encoded uint64 value "0". (path: Data location "/ydb-test-common:interfaces/interface[name='eth1']/uint64", line number 1.)
```
How should I use the interface to parse successfully?

**Comment by michalvasko** [comment]
The error is quite exact and is derived from the [specification](https://www.rfc-editor.org/rfc/rfc7951.html#section-6.1).

**Comment by zhuxiaoyun138159** [comment]
I know this writing is not standard, but I want to be able to not verify it so that it can be parsed successfully as libyang1.

**Comment by zhuxiaoyun138159** [comment]
#define LYD_PARSE_ONLY      0x010000        /**< Data will be only parsed and no validation will be performed. When statements
                                                 are kept unevaluated, union types may not be fully resolved, and
                                                 default values are not added (only the ones parsed are present). */

I used this option, but the code still did the validation.

**Comment by michalvasko** [comment]
Okay, I misunderstood initially, opaque parsing did not take encoding into consideration, only values themselves. It should now, so this use-case is supported.
