### ISSUE TITLE
The creation and parsing of anydata does not meet expectations.

### ISSUE THREAD

**Issue by zhuxiaoyun138159** [CESNET/libyang#2035]
In earlier versions, LYD_ANYDATA_CONSTSTRING/LYD_ANYDATA_JSON/LYD_ANYDATA_STRING value is saved in any->value.str when create anydata，value is also saved in any->value.str when parsing anydata. But, now libyang2 is all saved as a data tree.

If I want to create anydata (value : "test1111" , type: LYD_ANYDATA_STRING), The following error message is displayed:
libyang[0]: Invalid string value of an anydata node.

**Comment by michalvasko** [comment]
It took us several tries to get it right, *libyang* v1 did not work correctly. Anydata value is supposed to represent [set of nodes](https://www.rfc-editor.org/rfc/rfc7950.html#section-7.10) meaning some nested data tree. This is supported by the [JSON encoding](https://www.rfc-editor.org/rfc/rfc7951.html#section-5.5), for example. So yes, the value you provided is not valid.

**Comment by zhuxiaoyun138159** [comment]
ok, thanks
