### ISSUE TITLE
lyd_diff_tree returns a NULL pointer if there are no differences between the data trees

### ISSUE THREAD

**Issue by willtoth** [CESNET/libyang#2036]
When running `lyd_diff_tree` on two identical trees (either separate data nodes, or the same data node), the diff parameter output is set to NULL. Is this the expected behavior? If this is expected, can the docs be updated to reflect this? Thanks!

**Comment by michalvasko** [comment]
Fine, the docs were updated but I am wondering what is surprising about this behavior, what exactly would you expect to be returned in this case, what is a sensible alternative to returning `NULL`?

**Comment by michalvasko** [comment]
Error is communicated by the return value just like for the great majority of the functions in *ibyang*.
