### ISSUE TITLE
Using the 'diff' functionality for ietf-netconf:operations instead of yang:operation

### ISSUE THREAD

**Issue by willtoth** [CESNET/libyang#2037]
I want to use the diff functionality to generate ietf-netconf operations to apply on a device. For example, lets say I have the two data trees

A
```xml
<native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
  <interface>
    <Vlan>
      <name>23</name>
      <mac-address>2C:3F:0B:00:45:11</mac-address>
    </Vlan>
    <Vlan>
        <name>24</name>
        <mac-address>2C:3F:0B:00:45:22</mac-address>
    </Vlan>
    <Vlan>
      <name>25</name>
    </Vlan>
  </interface>
  <ip>
    <routing-conf>
      <routing>true</routing>
    </routing-conf>
  </ip>
</native>
```

B
```xml
<native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
  <interface>
    <Vlan>
      <name>23</name>
      <mac-address>2C:3F:0B:00:45:C0</mac-address>
    </Vlan>
    <Vlan>
      <name>25</name>
      <mac-address>2C:3F:0B:00:45:25</mac-address>
    </Vlan>
  </interface>
  <ip>
    <routing-conf>
      <routing>false</routing>
    </routing-conf>
  </ip>
</native>
```

If I generate a diff with A as the source I get a good diff like this

```xml
<native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native" xmlns:yang="urn:ietf:params:xml:ns:yang:1" yang:operation="none">
  <ip>
    <routing-conf>
      <routing yang:operation="replace" yang:orig-default="false" yang:orig-value="true">false</routing>
    </routing-conf>
  </ip>
  <interface>
    <Vlan>
      <name>23</name>
      <mac-address yang:operation="replace" yang:orig-default="false" yang:orig-value="2C:3F:0B:00:45:11">2C:3F:0B:00:45:C0</mac-address>
    </Vlan>
    <Vlan yang:operation="delete">
      <name>24</name>
      <mac-address>2C:3F:0B:00:45:22</mac-address>
    </Vlan>
    <Vlan yang:operation="none">
      <name>25</name>
      <mac-address yang:operation="create">2C:3F:0B:00:45:25</mac-address>
    </Vlan>
  </interface>
</native>
```

However I don't see a clear way to go from this to what I want. The most simple approach would be to simply replace the `yang:operation` with `nc:operation` and remove all the `yang` tags. This generates what I want.

```xml
<native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
  <ip>
    <routing-conf>
      <routing xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="replace">false</routing>
    </routing-conf>
  </ip>
  <interface>
    <Vlan>
      <name>23</name>
      <mac-address xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="replace">2C:3F:0B:00:45:C0</mac-address>
    </Vlan>
    <Vlan xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="delete">
      <name>24</name>
      <mac-address>2C:3F:0B:00:45:22</mac-address>
    </Vlan>
    <Vlan>
      <name>25</name>
      <mac-address xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="create">2C:3F:0B:00:45:25</mac-address>
    </Vlan>
  </interface>
</native>
```

However the docs are quite clear that this is not the right approach
```
__!! Caution !!__ The diff tree should never be validated because it may easily not be valid! For example, when data from one case branch are deleted and data from another branch created - data from both branches are then stored in the diff tree simultaneously.
```

Okay thats fine. So my second approach was to instead _add_ the correct `nc:operation` while leaving the `yang:operation` though replacing `yang operation:delete` with `yang operation:create` as to make sure the node remains in the tree. Then run the apply operation. This was fine, except one of my nodes was duplicated in the result

```xml
<native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
  <ip>
    <routing-conf>
      <routing xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="replace">false</routing>
    </routing-conf>
  </ip>
  <interface>
    <Vlan>
      <name>23</name>
      <mac-address xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="replace">2C:3F:0B:00:45:C0</mac-address>
    </Vlan>
    <Vlan>
      <name>24</name>
      <mac-address>2C:3F:0B:00:45:22</mac-address>
    </Vlan>
    <Vlan>
      <name>25</name>
      <mac-address xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="create">2C:3F:0B:00:45:25</mac-address>
    </Vlan>
    <Vlan xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="delete">
      <name>24</name>
      <mac-address>2C:3F:0B:00:45:22</mac-address>
    </Vlan>
  </interface>
</native>
```
I read the part of the docs that mentions I must use LYD_DIFF_DEFAULTS, however this did not change the result.

Note: I used `yang operation:create` instead of `yang operation:none` as I was getting this error, not sure why though, since it is not in the data tree:

```
Operation "none" is invalid for node "switchport-conf" without children.
```

Any idea on the right way to approach this? Thanks!

**Comment by michalvasko** [comment]
> I want to use the diff functionality to generate ietf-netconf operations to apply on a device.

This is not directly supported so yes, you are left with coming up with some custom solution.

> The most simple approach would be to simply replace the yang:operation with nc:operation and remove all the yang tags. This generates what I want.
However the docs are quite clear that this is not the right approach

That is probably the simplest approach and the warning is there mainly to prevent users from validating the diff. An edit (which is what you are creating) does not have to be valid (based on valid YANG data restraints) either. So your first approach and the resulting edit seem fine to me.

**Comment by willtoth** [comment]
One more follow up on this. Any idea why I get this error when I try to make small modifications to the diff tree, even though this node is not in the data tree at all?

```
Operation "none" is invalid for node "switchport-conf" without children.
```

This happens with or without `LYD_DIFF_DEFAULTS` set, and the only modification to the diff tree was to replace `yang:operation:delete` with `yang:operation:create` and add `nc:operation:delete` tags to those nodes.

The reason I ask is I get this error if I try to manually create my own diff tree using the `yang:operation` tags. Thanks!

**Comment by michalvasko** [comment]
I do not know what you are doing exactly but the error means that there is a node in the diff that has operation `none` on it and no children meaning it is completely redundant and hence forbidden.

**Comment by willtoth** [comment]
Okay, I've found a better example to explain what I mean. Very simply, I want to do the following:

1. Create a diff
2. Save the diff to disk
3. Some time later, reload this diff
4. Apply this diff to a data tree

However this does not work, and gives various errors. Here is a concrete example.

Tree A
```xml
<native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
  <interface>
    <Vlan>
      <name>24</name>
      <mac-address>2C:3F:0B:00:45:C0</mac-address>
    </Vlan>
  </interface>
</native>
```

Tree B
```xml
<native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
  <interface>
    <Vlan>
      <name>25</name>
      <mac-address>2C:3F:0B:00:45:C0</mac-address>
    </Vlan>
    <Vlan>
      <name>24</name>
      <mac-address>2C:3F:0B:00:45:D0</mac-address>
    </Vlan>
  </interface>
</native>
```

When I diff Tree B with Tree A I get the following
```xml
<native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native" xmlns:yang="urn:ietf:params:xml:ns:yang:1" yang:operation="none">
  <interface>
    <Vlan yang:operation="delete">
      <name>25</name>
      <mac-address>2C:3F:0B:00:45:C0</mac-address>
    </Vlan>
  </interface>
</native>
```

Applying the diff of the above works as expected.

However, if I take the above text, and load it from a string using the same context, and print it, it matches the above as expected. But if I take this loaded tree, and try to apply it, I get the following error:

```
Node "/ietf-yang-schema-mount:schema-mounts" without an operation.
```

Its as if there are some nodes not in the data tree that are being compared, but they don't have some meta data or some state that is set when calling diff.

Is there some simple way to go through the data tree and fix this? The above would also allow supporting creating arbitrary diffs by simply adding annotations to a data tree.

**Comment by michalvasko** [comment]
> ... and load it from a string using the same context ...

Be careful, you are obviously validating the diff when parsing it, the diff may not even be valid and implicit nodes are added that are causing the problems. Use `LYD_PARSE_ONLY` flag when parsing a diff and it should work.

**Comment by willtoth** [comment]
That did it, thanks!
