### ISSUE TITLE
Faster loading or caching for YANG modules/context.

### ISSUE THREAD

**Issue by willtoth** [CESNET/libyang#2040]
When loading a large number of YANG modules, it takes quite some time due to the size and complexity of the models. The time it takes to load increases as the number of modules increases. I did not find anything in the docs, so I figured I would ask here. Is there any mechanism within libyang, or some recommendation for being able to improve this speed? Perhaps a way to load/save state to disk? Thanks!

For example, loading 35 YANG modules of various sizes takes ~38 seconds on a reasonable fast machine. Most modules are under the same tree and loading each new module take incrementally longer than the last.

**Comment by michalvasko** [comment]
> Is there any mechanism within libyang, or some recommendation for being able to improve this speed?

Yes, use the [`LY_CTX_EXPLICIT_COMPILE`](https://netopeer.liberouter.org/doc/libyang/master/html/group__contextoptions.html#ga17ce7b15b2b448860197416e48d62fd9) flag when creating the context and compile all of the modules at once with `ly_ctx_compile()`.

**Comment by 8bitDesigner** [comment]
I work with @willtoth and I believe this improved our loading times; can we close this issue out?
