### ISSUE TITLE
List keys are expected to be the first siblings, and in order

### ISSUE THREAD

**Issue by p-jean** [CESNET/libyang#205]
The function lyv_keys(), for example, expects the leaf objects for the keys to be the first siblings, and in the same order as the schema->keys[] array. If the keys are not defined in yang/yin to be the first leaves in the list, then validation fails. The Yang specification does not appear to put a limitation on the placement or order of keys in the yang definition, though the XML encoding does specify an order. 

Using lyd_sort() does not help in this case, because the leaves are sorted in the order as given by the yang/yin model (and keys not always in first slots).

As an illustration, consider the (valid?) list definition:
`
list l {
	key "d b";
	leaf a {
	}
	leaf b {
	}
	leaf c {
	}
	leaf d {
	}
}
`
The schema siblings will be [ a, b, c, d ] but the schema keys will be [ d, b ] which will fail to match in lyv_keys().

The XML encoding requires the keys to be first and in order, so it would need to be [ d, b, a, c ] or [ d, b, c, a ]

It seems like a good style to define the keys in order at the beginning of a list, however I inherited a model translated from a legacy system which does not have that restriction. The quick workaround is to re-order the yang definitions (if possible).

**Comment by rkrejci** [comment]
Having the keys in the data tree as the first children is kind of optimization and libyang parsers and manipulation/insertion functions should place the keys to the correct place. Can you please specify how you create the data tree which does not validate? Because just parsing the xml data with list content `[a,b,c,d]` works and libyang transforms it automatically into `[d,b,a,c]`, so I don't see any issue here.

**Comment by p-jean** [comment]
The problem is not in the parsing of data, but in the order of fields in the schema. If the yang list definition is order [ a, b, c, d ] then the schema is also in order [ a, b, c, d ] (as far as I can tell). If the keys are selected as [ d, b ], for example,  then the validation does not find them as the first two entries of the schema, as it expects to. You should be able to see this if, as a test, you add a new unused field to the beginning of  a list (before the keys). In my case, moving the keys to the start of the list was a workaround.

**Comment by p-jean** [comment]
I can try to create the issue in isolation. Probably I have something wrong. Thx
