### ISSUE TITLE
Invalid json output on Windows

### ISSUE THREAD

**Issue by pepa-cz** [CESNET/libyang#2056]
Using libyang on Windows generates different JSON output than on Linux platform, looks like it is specific bug only for backslash character stored in `anydata`.

Model:
```
module test {
  yang-version 1.1;

  namespace "test";
  prefix "tst";

  revision 2022-02-03 {
    description "Initial revision";
  }
  container parameters {
    anydata anytest {    
    }
  }
  container data {
    leaf wpath {
      type string;
    }
  }
}
```

Data:
```
{
    "test:parameters": {
        "anytest": {
            "tst:data": {
                "wpath": "C:\\Users"
            }
        }
    },
    "test:data": {
        "wpath": "C:\\Users"
    }
}
```

Source:
```C
#include <stdio.h>
#include "libyang/libyang.h"

int main(int argc, char *argv[]) {
   struct ly_ctx *ctx = NULL;
   struct lyd_node* n;
   char *strp, *strp1;

   ly_ctx_new(NULL, 0, &ctx);
   ly_ctx_load_module(ctx, "test", NULL, NULL);

   lyd_parse_data_path(ctx, "./test.json", LYD_JSON, 0, LYD_VALIDATE_PRESENT , &n);   
   lyd_print_mem(&strp, n, LYD_JSON,  LYD_PRINT_WITHSIBLINGS);
   printf("1== %s", strp);

   lyd_parse_data_mem(ctx, strp, LYD_JSON, 0, LYD_VALIDATE_PRESENT, &n);
   lyd_print_mem(&strp1, n, LYD_JSON, LYD_PRINT_WITHSIBLINGS);
   printf("2 === %s", strp1);
}
```

Output on Linux:
```
1== {
  "test:parameters": {
    "anytest": {
      "tst:data": {
        "wpath": "C:\\Users"
      }
    }
  },
  "test:data": {
    "wpath": "C:\\Users"
  }
}
2 === {
  "test:parameters": {
    "anytest": {
      "tst:data": {
        "wpath": "C:\\Users"
      }
    }
  },
  "test:data": {
    "wpath": "C:\\Users"
  }
}
```

Output on windows:
```
1== {
  "test:parameters": {
    "anytest": {
      "tst:data": {
        "wpath": "C:\Users"
      }
    }
  },
  "test:data": {
    "wpath": "C:\\Users"
  }
}
libyang[0]: Invalid character escape sequence \U. (path: Data location "/test:parameters/anytest", line number 5.)
2 === {}
```
On windows platform it looks like parser removes one backslash in `wpath` leaf nested in `anytest` anydata node. Thus generated output cannot be parsed again.

**Comment by lePici** [comment]
Hi,
I don't know how I can help you. On the `Windows` platform, I updated my project from the `devel` branch, compiled the code in `Debug` and also in `Release` configuration and I don't have the problem you mentioned. I get the same output as you would expect on `Linux`.
For myself, I modified your code minimally, I included `libyang` using `#include "libyang.h"` (because I was compiling the code directly in the project) but there should be no difference.

**Comment by pepa-cz** [comment]
Sorry I did not have current version of libyang. However, I switched to the current master now and it looks like the problem is also on Linux platform.

```
$ yanglint -v
yanglint 2.1.80
```
Data + model:
```
$ cat test.yang
module test {
  yang-version 1.1;

  namespace "test";
  prefix "tst";

  revision 2022-02-03 {
    description "Initial revision";
  }
  container parameters {
    anydata anytest {
    }
  }
  container data {
    leaf wpath {
      type string;
    }
  }
}
$ cat test.json
{
    "test:parameters": {
        "anytest": {
            "tst:data": {
                "wpath": "C:\\Users"
            }
        }
    },
    "test:data": {
        "wpath": "C:\\Users"
    }
}
```
Using yanglint:
```
$ yanglint test.yang test.json -f json
{
  "test:parameters": {
    "anytest": {
      "tst:data": {
        "wpath": "C:\Users"
      }
    }
  },
  "test:data": {
    "wpath": "C:\\Users"
  }
}
```

JSON output shows the first single backslash `\` but the second one is doubled `\\`. I would expect doubled both. If printed as XML there is correct output with one backslash on both places.

**Comment by lePici** [comment]
I tried your example on a `Linux` platform. I get this error in the `master` branch as well. However, in the `devel` branch, the program works correctly, so I assume that the issue has already been fixed. The easiest solution is to use the source code from the `devel` branch or wait until the `devel` branch with a patch is merged into `master`.

**Comment by pepa-cz** [comment]
Already fixed in devel branch.

**Comment by God-SEVEN** [comment]
Hello, I am trying to compile the Windows version of libyang library now, but I have some troubles. Can I teach you?
