### ISSUE TITLE
add error2str mapping functions

### ISSUE THREAD

**Issue by choppsv1** [CESNET/libyang#2057]
It would be very useful to have access to error-to-string functions for the error enum types. Without this the user application has to hand-code them and will be out-of-date as soon as a new value is added.

```
const char *ly_err_ecode_str(ecode)
{
        switch (ei->no) {
        case LY_EMEM:
                ecode = "out of memory";
                break;
        ...
}

const char *ly_err_vecode_str(vecode)
{
        switch(vecode) {
        case LYVE_SYNTAX:
                return "syntax";
    ...
}
```

**Comment by michalvasko** [comment]
Fine, added.

**Comment by choppsv1** [comment]
Thanks, I added code comments on the commit, not sure how those show up or get notified, but they boil down to "these functions should always return a printable string like strerror(3) does, so that they can be safely used in printf, et al., calls w/o arg checking".

**Comment by michalvasko** [comment]
I saw the comments and okay, I have adjusted the code. But it should be safe to use `NULL` for `printf`, for example, which prints `(null)`.

**Comment by choppsv1** [comment]
> I saw the comments and okay, I have adjusted the code. But it should be safe to use `NULL` for `printf`, for example, which prints `(null)`.

Thanks, and ok so printf works but some other random string using function won't be so nice :) Anyway thanks.

**Comment by choppsv1** [comment]
Need to include

```
default:
    return "Unknown error code"
```
or return the same from the end of the funciton. It really should be an invariant that can be trusted and never return NULL even if given incorrect error code values (as with strerror(3) :)

This will probably keep static analysis tools from complaining about NULL usage as well.

**Comment by michalvasko** [comment]
I suppose `""` can be included if you really want but I have not included `default` on purpose so that the compiler warns about a missing case when a new value is added.

**Comment by choppsv1** [comment]
> I suppose `""` can be included if you really want but I have not included `default` on purpose so that the compiler warns about a missing case when a new value is added.

Right that's why I mentioned return "Unknown error" from the end of the function instead of in the switch case. Please at leas say "Unknown" rather than "", why make work for poor developers triaging bugs?

**Comment by michalvasko** [comment]
You mean in case the function is not used on a proper value? It is really not that difficult to make sure it is not... But fine, changed to a valid string.
