### ISSUE TITLE
Getting the schema typedef associated to a type

### ISSUE THREAD

**Issue by samuel-gauthier** [CESNET/libyang#2059]
Hi,

I am trying to get the description of a typedef statement, given a type lysp_type struct using this typedef,
to add support for it in libyang-python.
I have been unable to do that, except by going back to the module where the typedef is defined, which is not too handy
when it is another module.

If I understood the code correctly, most of the information in the typedef is reported in the type except reference and description, and as the yang rfc does not define those fields for types, there is no such field in the lysp_type
structure where this information could be put.

I think that having a reference to lysp_typedef in lysp_type would make sense.

Or is there a way to do this more elegantly that I missed?

Regards,
Samuel

**Comment by michalvasko** [comment]
> I think that having a reference to lysp_typedef in lysp_type would make sense.

There are 2 relevant issues. The first is a practical one. Using an example
```yang
typedef type1 {
  type string;
  description "type1-desc";
}

typedef type2 {
  type type1;
}

leaf l {
  type type2;
}
```
It can be observed that your solution would not suffice to get the description. Instead, every type would need a pointer to its parent typedef, if any. So you get trees of typedefs referencing each other.

Which brings us to the other issue. Creating such a tree is not much of a problem. However, the way the library is designed and works internally is that the modules can often be recompiled when new ones are added. What that means is that all compiled modules are freed and the parsed modules are compiled again, without them being changed. But if there was this tree of pointers pointing at each other, they would need to be cleared or somehow updated for each recompilation. That does not fit the used design and it seems like adding another layer of complexity to the whole (re)compilation process. So, if you are able to find the information you need yourself, I would strongly prefer you stick with it. I think I have argued my case clearly.

**Comment by samuel-gauthier** [comment]
OK, I got your point. I'll try harder to make it work in libyang-python getting back to the typedef's module, then. Thanks!
