### ISSUE TITLE
var 'snode' should be var 'key' here

### ISSUE THREAD

**Issue by lyzliyuzhi91** [CESNET/libyang#2061]
https://github.com/CESNET/libyang/blob/ea94c8b9f513f8a6ddc6ce1540fa41eaf4c8922a/src/tree_data_common.c#L751C83-L751C83
```
    /* get all keys into a set */
    while ((key = lys_getnext(key, snode, NULL, 0)) && (snode->flags & LYS_KEY)) {
        LY_CHECK_GOTO(ret = ly_set_add(&key_set, (void *)snode, 1, NULL), cleanup);
    }
```
`snode-flags` -> `key->flags`
`snode` inside ly_set_add the same.
Thanks.

**Comment by michalvasko** [comment]
Yes, thanks.
