### ISSUE TITLE
yanglint validation of schema mount with -t data throws errors

### ISSUE THREAD

**Issue by alexandrustancu** [CESNET/libyang#2064]
Hi,

I am trying a simple scenario of validating data (containing status data as well) with **schema mount** with `yanglint`.

Tried with the latest `master` (`v2.1.80`) and the latest `devel` (`2.1.100`). 

Starting from the simple example in the `tools/lint/examples` ([here](https://github.com/CESNET/libyang/tree/devel/tools/lint/examples#yang-modules-with-the-schema-mount-extension)):

1. validating data with config only flag **(`-t config` flag)**: `yanglint -f json -t config -p . -Y sm-context-main.xml -x sm-context-extension.xml sm-data.xml`, works as expected:
```JSON
{
  "ietf-interfaces:interfaces": {
    "interface": [
      {
        "name": "eth0",
        "type": "iana-if-type:ethernetCsmacd"
      },
      {
        "name": "eth1",
        "type": "iana-if-type:ethernetCsmacd"
      }
    ]
  },
  "sm-main:root3": {
    "my-list": [
      {
        "name": "list item 1",
        "sm-extension:things": [
          {
            "name": "eth0",
            "attribute": 1
          }
        ]
      }
    ]
  }
}

```

2. validating data with status flag **( `-t data` flag)**: `yanglint -f json -t data -p . -Y sm-context-main.xml -x sm-context-extension.xml sm-data.xml` fails with the following errors:
```bash
libyang err : Mandatory node "content-id" instance does not exist. (Data location "/ietf-yang-library:yang-library".)
libyang err : Mandatory node "module-set-id" instance does not exist. (Data location "/ietf-yang-library:modules-state".)
YANGLINT[E]: Failed to parse input data file "sm-data.xml".
```

Expectation is that the `-t data` flag should work as wll, since the `content-id` and `module-set-id` files are there, like in the `-t config` case.

**Comment by jktjkt** [comment]
Can you please share full unedited content of `sm-context-main.xml`, `sm-context-extension.xml` and `sm-data.xml`, as well as all your YANG models?

**Comment by alexandrustancu** [comment]
Those are the exact files found under `tools/lint/examples`, I did not modify them in any way.

**Comment by lePici** [comment]
It looks like when running with the `-t data` option, the `content-id` and `module-set-id` must also be set in the `sm-data.xml` file. I don't know if it's a bug or simply a valid side effect of the selected parameters.

**Comment by michalvasko** [comment]
That is the difference between `config` and `data`, the latter expects all the defined data and there are missing mandatory state nodes so the data fail to load.

**Comment by alexandrustancu** [comment]
Ok, it's clear then. Adding the missing nodes into `sm-data.xml` works indeed.
