### ISSUE TITLE
Validating empty data

### ISSUE THREAD

**Issue by pepa-cz** [CESNET/libyang#2065]
Hi,

I have a question about how libyang approaches empty data (`{}` in JSON or an empty string in XML format). There is a `LYD_VALIDATE_PRESENT` flag for validating only data that are present. If this flag is not set I would expect that empty data will be validated across all modules that are loaded in libyang context, however an error is raised. In my point of view, empty data are valid until there is no mandatory item in the schema.

**Comment by jktjkt** [comment]
What error message are you getting, and what YANG modules with which features are loaded into the context?

**Comment by pepa-cz** [comment]
A mistake on our side, validating empty data is working as expected. Please mark this issue as invalid, thanks.

Thanks.
