### ISSUE TITLE
I think it should not report "Missing XML namespace." when no module respond to such namespace.

### ISSUE THREAD

**Issue by lyzliyuzhi91** [CESNET/libyang#2067]
https://github.com/CESNET/libyang/blob/ea94c8b9f513f8a6ddc6ce1540fa41eaf4c8922a/src/parser_xml.c#L539C16-L539C16

```
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="f1a54c92-09a3-49b6-af0f-483c77981d5a">
  <get-data xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-nmda" xmlns:ds="urn:ietf:params:xml:ns:yang:ietf-datastores">
  <datastore>ds:candidate</datastore>
  <subtree-filter>
	<sessions xmlns="urn:huawei:params:xml:ns:yang:huawei-omc-inside"/>
  </subtree-filter>
</get-data>
</rpc>
```
And I parse by `LYD_TYPE_RPC_YANG` option
```
lyd_parse_op(ly_ctx, NULL, in, format, LYD_TYPE_RPC_YANG, &tree, &action)
```
And it report `"Missing XML namespace."` in libyang error message. But I think It should report `"No module with namespace \"%s\" in the context."` inside the later label `unknown_module`.
Thanks.

**Comment by michalvasko** [comment]
My output
```
> ./test 
libyang[0]: No module with namespace "urn:ietf:params:xml:ns:netconf:base:1.0" in the context. (path: Line number 1.)
```
Files in an [archive](https://github.com/CESNET/libyang/files/12279098/test.zip).

**Comment by lyzliyuzhi91** [comment]
Sorry. Some bug in my other part code.
