### ISSUE TITLE
YANG extension nodes paths

### ISSUE THREAD

**Issue by peckato1** [CESNET/libyang#2069]
Hello,

I was recently trying to work with YANG nodes defined in extension instance. I was looking at [this libyang unit test](https://github.com/CESNET/libyang/blob/54bf9e2878eb14cb71fb992a0f3816d56e5abde2/tests/utests/data/test_new.c#L480) and I don't understand the format of the path for the `lyd_new_path` call. Why can't I use absolute path to the `z` leaf, i.e.,  `/ext:c/z`? The return is then `LY_EVALID` with a log message `Not found node "c" in path.`

Also, [documentation of `lyd_new_path`](https://github.com/CESNET/libyang/blob/838c6c6adb552964014de24c5d5b2aec448e0358/src/tree_data.h#L1516) that ` * If creating data nodes defined inside an extension instance, use ::lyd_new_ext_path().` which is not entirely true according to [this paragraph](https://github.com/CESNET/libyang/blob/838c6c6adb552964014de24c5d5b2aec448e0358/src/tree_data.h#L244) which states that only first node must be created using the `lyd_new_ext_*` functions.

**Comment by michalvasko** [comment]
> Why can't I use absolute path to the z leaf, i.e., /ext:c/z?

What if the module `ext` also defined
```yang
container c {
  leaf z {
    type string;
  }
}
```
You would then get an ambiguity, hence the special functions. The exact extension instance is required because you may even have several extension instances with the same data nodes.

> If creating data nodes defined inside an extension instance, use ::lyd_new_ext_path().

It does not say you must use the function for all the nodes but you can :)
