### ISSUE TITLE
feature request: more detailed error reporting for constraint validation below `union`

### ISSUE THREAD

**Issue by jktjkt** [CESNET/libyang#2071]
Consider the following definition:
```yang
leaf x {
  type union {
    type enumeration {
      enum off;
    };
    type decimal64 {
      fraction-digits 2;
      range "1 .. 10" {
        error-message "Reasonable value must be at least 1 and at most 10 because of foo bar baz";
      }
    }
  }
}
```
When I try to initialize it by value `0.25`, this gets correctly rejected. However, the custom error message from the `decimal64` `range` statement is lost, and I get back only `Invalid union value "0.250000" - no matching subtype found.`. Ideally, I would like to get an error message from *all* union types that were tried, but failed to match, just like I do when a simple scalar leaf that is range-limited fails to match: `Unsatisfied range - value "666.0" is out of the allowed range.`, or, in this case, a custom error text.

**Comment by michalvasko** [comment]
Alright, why not, a nice improvement.
