### ISSUE TITLE
To date-and-time type, does libyang2 not verify legality?

### ISSUE THREAD

**Issue by jiayinhaoran** [CESNET/libyang#2072]
To date-and-time type, does libyang2 not verify legality?
Such as：(Device TZ is +08:00)
input data is: (Both TZ and month are illegal)
2023-16-15T20:13:01+95:00
libyang print this value to:
2024-04-12T05:13:01+08:00

Libyang2 did not report an error but converted it, why libyang2 not report an error？Who should conduct a correctness check to date-and-time?
From https://datatracker.ietf.org/doc/html/rfc3339#section-5.6, and https://datatracker.ietf.org/doc/html/rfc3339#section-5.7, we can find date-and-time should have some grammer restrictions.

And I find that Libyang1 will return a error to above data.
And In libyang1, user can decide whether to use user-yang-types plugin, in libyang2 this is mandatory.

Can I do a new date_and_time plugin to replace this internal plugin?
I try to make a new date-and-time plugin to replace internal plugin, but it does not effective.
@michalvasko

**Comment by michalvasko** [comment]
Okay, some constraints are now checked manually, seems that `timegm(3)` has no problems with these values.
