### ISSUE TITLE
The irrelevant top level container under a module changes the data order when calling lyd_parse_op and then influence lyd_parse_opaq_error behavior

### ISSUE THREAD

**Issue by lyzliyuzhi91** [CESNET/libyang#2086]
modules:
```
module xxx-ifm {
  namespace "urn:xxx:yang:xxx-ifm";
  prefix ifm;

  typedef if-name {
      type string {
        length "1..63";
        pattern  '[0-9a-zA-Z_/:\.\-]*';
      }
  }

  container ifm {
    container interfaces {
      list interface {
        key "name";
        leaf name {
          type if-name;
        }
      }
    }
  }
}
```
```
module xxx-lldp {
  namespace "urn:xxx:yang:xxx-lldp";
  prefix lldp;


  import xxx-ifm {
    prefix ifm;
  }

  typedef port-id-sub-type {
    type enumeration {
      enum "other" {
        value 0;
        description
          "The Port id sub type is other.";
      }
    }
  }

  typedef chassis-id-sub-type {
    type enumeration {
      enum "other" {
        value 0;
        description
          "Other extended retention.";
      }
    }
  }

  typedef management-address-type {
    type enumeration {
      enum "other" {
        value 0;
      }
    }
  }

  typedef man-addr-if-sub-type {
    type enumeration {
      enum "other" {
        value 0;
      }
    }
  }

  grouping chassis-id {
    leaf chassis-id-sub-type {
      type chassis-id-sub-type;
    }
    leaf chassis-id {
      type string {
        length "1..765";
      }
    }
  }

  grouping port-id {
    leaf port-id-sub-type {
      type port-id-sub-type;
    }
    leaf port-id {
      type string {
        length "1..765";
      }
    }
  }

  grouping system-name {
    leaf system-name {
      type string {
        length "1..256";
      }
    }
  }

  grouping management-address {
     container management-addresss {
      list management-address {
        key "type value length";
        leaf type {
          type management-address-type;
        }
        leaf value {
          type string {
            length "1..93";
          }
        }
        leaf length {
          type int32 {
            range "0..2147483647";
          }
        }
        leaf if-sub-type {
          type man-addr-if-sub-type;
        }
      }
    }
  }

  grouping neighbor-common-info {
    uses chassis-id;
    uses port-id;
    uses system-name;
    uses management-address;
  }

  container lldp {
    leaf some {
      type string;
    }
  }

  augment "/ifm:ifm/ifm:interfaces/ifm:interface" {
    container lldp {
      container session {
        container neighbors {
          config false;
          list neighbor {
            key "index";
            leaf index {
              type uint32 {
                range "0..4294967295";
              }
            }
            uses neighbor-common-info;
          }
        }
      }
    }
  }
}
```

rpc-message:
```
"<get xmlns=\"urn:ietf:params:xml:ns:netconf:base:1.0\"><filter type=\"subtree\"><ifm xmlns=\"urn:xxx:yang:xxx-ifm\"><interfaces><interface><name/><lldp xmlns=\"urn:xxx:yang:xxx-lldp\"><session><neighbors><neighbor><index/><chassis-id-sub-type/><chassis-id/><port-id-sub-type/><port-id/><system-name/><management-addresss><management-address><type/><value/></management-address></management-addresss></neighbor></neighbors></session></lldp></interface></interfaces></ifm></filter></get>"
```

snippet code concerned:
```
LY_ERR err = lyd_parse_op(ly_ctx, NULL, in, format, LYD_TYPE_RPC_YANG, &tree, &action); // value of “in" come from the rpc-message above
...
err = lyd_parse_opaq_error(iter);  // iter refer to the "interface" list node
```
And it report errors:
```
Unexpected node container "lldp"
```
But once I remove the top level container `lldp`  (not the container `lldp` under augment) in module xxx-lldp, it will not report such error anymore.
I follow the process, and I found that, if there exists the top-level container `lldp` in module `xxx-lldp`, then when I call `lyd_parse_op`, it will move the data node `lldp` before the data node `name`, becasue when calling `lydxml_subtree_snode`, it will succeed to get the snode for the `lldp`, but actually, it get wrong(the data node `lldp` should relevant to the `lldp` under augment but not to the top level container `lldp`), and then it will move the data node `lldp` before the opaq data node `name`.
And then when I call `lyd_parse_opaq_error` -> `lyd_parse_opaq_list_error`, it will return error inside this if 
```
        if (child->schema) {
            LOGERR(LYD_CTX(node), LY_EINVAL, "Unexpected node %s \"%s\".", lys_nodetype2str(child->schema->nodetype),
                    LYD_NAME(child));
            ret = LY_EINVAL;
            goto cleanup;
        }
```
But once I remove the top level container `lldp` , the process of `lyd_parse_op` will not move the data node `lldp` before opaq data node `name`, so then it won't report error when calling `lyd_parse_opaq_error`. 
I don't think it is correct to let the irrelevant top level container make such different behavior.

version:
2.1.30

Thanks.

**Comment by michalvasko** [comment]
You generally cannot rely on particular order of the nodes, which is even in the specs of YANG and the XML format. *libyang* orders the data nodes in the same order as the schema nodes are in the YANG module and puts all opaque nodes after them. But you should always find the node you are looking for and not access a node on a fixed position. Within siblings you can generally find a specific node in constant complexity using `lyd_find_sibling_*()` or even use `lyd_find_xpath()` that will match opaque nodes as well.

**Comment by lyzliyuzhi91** [comment]
In this case, I have not reply on the order of the data nodes, but `lyd_parse_opaq_error` generates an error to me.
And once I remove the irrelevant top level container `lldp` in module, it no longer generates the error.
I thinks there exists problem in `lydxml_subtree_snode` or `lys_find_child`. 

For the example above, because value of `/ifm/interfaces/interface/name` is an empty string, not conform to the pattern restriction, so libyang will make data node `name` and its parent `interface` an opaq node. And then, after parsing `name` node, it parse the next node `lldp`, and then it will try call `lys_find_child` to get the schema, 
```
LIBYANG_API_DECL const struct lysc_node *lys_find_child(const struct lysc_node *parent, const struct lys_module *module,
        const char *name, size_t name_len, uint16_t nodetype, uint32_t options);
```
and at now, the `parent` parm is null because the data node parent `interface` is an opaq node which has not a schema mounted. And the `module` param is referring to the `xxx-lldp` module, `name`'s value is `lldp`, and exactly there exists a top node named `lldp` in module `xxx-lldp`, so `lys_find_child` will return such node. It is wrong! Because it happen to be of the same name!
