### ISSUE TITLE
Subscirbe failed on self-defined yang module.

### ISSUE THREAD

**Issue by Ray123456a** [CESNET/libyang#2094]
Hi , I defined two yang modules , they are same as o-ran-sync yang modules except name. I have installed them succesfully, and I can use "get"  "edit-config" &"subscribe"command  on these yang modules. But I can not subscribe these two yang modules at same netopeer2-cli session.
![Weixin Image_20230904170129](https://github.com/CESNET/libyang/assets/137867640/cbdf7d92-a369-4b5f-8ae4-07dd7881c7f3)

**Comment by michalvasko** [comment]
You can use `--filter-xpath /o-ran-sync-sh1:*|/o-ran-sync-sh2:*` or the command `establish-sub` instead, which supports multiple subscriptions.

**Comment by Ray123456a** [comment]
Got it , thanks!
