### ISSUE TITLE
Can not login in netopeer2-cli sometimes.

### ISSUE THREAD

**Issue by Ray123456a** [CESNET/libyang#2095]
Sometimes, when I  want to login in netopeer2-cli, it would showed EOF error as below:
![image_2023_09_05T12_50_32_249Z](https://github.com/CESNET/libyang/assets/137867640/bf1d8c7c-b990-40ed-8ab3-2e88aedda131)

**Comment by michalvasko** [comment]
Not sure why this would happen, what *netopeer2* version are you using?

**Comment by Ray123456a** [comment]
> version
Netopeer2 CLI 2.0.47

**Comment by michalvasko** [comment]
That is a really old version so I would suggest updating it. You may also try updating your *libssh* version, if you are not using the current one.

**Comment by Ray123456a** [comment]
OK , thanks.
