### ISSUE TITLE
how should  I distinguish the correct error-tag only by the error message in such two scene?

### ISSUE THREAD

**Issue by lyzliyuzhi91** [CESNET/libyang#2098]
module: 
```
module bla-st-config {
    namespace "urn:test:bla:bla-st-config";
    prefix bla-st-config;

    container c1 {
        leaf enum-leaf {
            type enumeration {
                enum admin;
            }
        }
       leaf v4 { type string; }
    }
}
```
message1:
```
{
        "ietf-netconf:edit-config": {
            "target": {"running": ""},
            "config": {
                "bla-st-config:c1": {
                   "enum-leaf": "remove1"
                }
            }
        }
    }
```
message2:
```
{
        "ietf-netconf:edit-config": {
            "target": {"running": ""},
            "config": {
                "bla-st-config:c1": {
                   "v4": ""
                   "@v4": { "ietf-netconf:operation":"remove1" }
                }
            }
        }
    }
```
Both message1 and message2 will report `Invalid enumeration value "xxx"` by libyang, but message1 should report `bad-element`  by netconf-server, and message2 should report `bad-attribute` by netconf server.
But how can I distinguish the correct error-tag only by the error message in libyang?

**Comment by michalvasko** [comment]
> But how can I distinguish the correct error-tag only by the error message in libyang?

I do not think your question really makes sense, you cannot, obviously. You have to get the app tag by using `ly_errapptag()`, for example.

**Comment by lyzliyuzhi91** [comment]
But what i need is `error-tag` not the `error-app-tag`

**Comment by michalvasko** [comment]
Right, sorry. `error-tag` is considered a NETCONF feature so it does not have direct support in *libyang*. Have you tried looking at the error path? It may be useful for this.

**Comment by lyzliyuzhi91** [comment]
the `error-path`  of messag1 is `/bla-st-config:c1/enum-leaf` , and of message 2 is `/bla-st-config:c1/v4`.
But they doesn't help, I still can't tell which situation it is in my program.

**Comment by michalvasko** [comment]
Fine, I have made some modifications and metadata should have their own path so you should be able to distinguish between these `error-tag`s.
