### ISSUE TITLE
Memory leak in function 'log_vprintf'

### ISSUE THREAD

**Issue by JoraGevorgyan** [CESNET/libyang#2105]
The memory leak is reported by a static analyzer tool developed at [CAST](https://www.linkedin.com/company/cast-center)
Specifically, memory is allocated in [here](https://github.com/CESNET/libyang/blob/8b0b910a2dcb7360cb5b0aaefbd1338271d50946/src/log.c#L664) and because it allocates during function call, after failure any assertion or exit in that function the memory may left without free

**Comment by michalvasko** [comment]
It is not the most readable code (quite old) but I could not find any memory leaks. Please describe the exact flow of the code resulting in a memory leak.

**Comment by JoraGevorgyan** [comment]
strdup(apptag) returns an allocated memory
in function log_store there's an assertion at line 537
so it may assert and memory will left w/o free

**Comment by michalvasko** [comment]
Usually every failed `assert()` causes memory leaks. It is present only in Debug build mode and should never fail, anyway. So this is not a relevant issue.
