### ISSUE TITLE
Getting Error as "Missing the operation node"

### ISSUE THREAD

**Issue by raman-in** [CESNET/libyang#2109]
I am new to the libyang usage.
I am having below xml data which i need to set for o-ran-fm.yang using sysrepocfg command as mentioned below:

oran_fm.xml:
```xml
<active-alarm-list xmlns="urn:o-ran:fm:1.0">
  <active-alarms>
   <fault-id>1</fault-id>
   <fault-source>Network Element X</fault-source>
    <affected-objects>
      <name>Radio Unit</name>
    </affected-objects>
    <fault-severity>MAJOR</fault-severity>
    <is-cleared>true</is-cleared>
    <fault-text>Equipment Power supply</fault-text>
    <event-time>2021-09-27T18:05:26Z</event-time>
  </active-alarms>
</active-alarm-list>
```
1.
```
> sysrepocfg --edit=oran_fm.xml --format=xml --datastore=running --module=o-ran-fm -v3
[INF] Connection 2 created.
[INF] Session 2 (user "root", CID 2) created.
libyang error: Unexpected data state node "active-alarm-list" found. (Schema location "/o-ran-fm:active-alarm-list", line number 2.)
sysrepocfg error: Data parsing failed
```
--> Not sure about this error 'Unexpected data state node'
```
3. When i try to run through yanglint in libyang i got below output.
> data -t reply /home/oran_fm_copy.xml
libyang[0]: Missing the operation node. (path: Line number 14.)
```
--> But there is no "operation" node available in "o-ran-fm.yang" file. 

Kindly help me on this issue.

**Comment by michalvasko** [comment]
You obviously want to "set" state data, which is not possible, you are trying to add them into the `running` datastore but they can only be in the `operational` datastore. [Here](https://netopeer.liberouter.org/doc/sysrepo/master/html/index.html#oper_data) you can learn how to populate the `operational` datastore with some data.

**Comment by raman-in** [comment]
Hi,
How you able to say that this can be only in operational datastore[Any keywords to identify that it goes to oper datastore??]. Because i thought this "oran_fm.xml" data can also be set similar to "ssh_callhome.xml" using below command:
sysrepocfg --edit=ssh_callhome.xml --format=xml --datastore=running --module=ietf-netconf-server

So you meant to say this can be set only using "sr_set_item_str()" APIs through the code but not using any "sysrepocfg" CLI commands? Please clarify.

**Comment by jktjkt** [comment]
You'll have to review the YANG definition to learn about the difference between the [data nodes and state nodes](https://datatracker.ietf.org/doc/html/rfc7950#section-4.2.3). The error message means that `/o-ran-fm:active-alarm-list` is not a data node, and as such it cannot be set like that. You might want to re-read the sysrepo's documentation which explains how these YANG-level concepts map to sysrepo functionality.

**Comment by raman-in** [comment]
ok thanks for clarification as the leaf is marked as config false hence it is considered as operational data. I am able to set the data for these leaf through the code using operational data callback.
