### ISSUE TITLE
request: lyd_new_list*() with list of keys

### ISSUE THREAD

**Issue by choppsv1** [CESNET/libyang#2115]
I've found the varargs variants of `lyd_new_list()` are not very useful in our application.  At least in our application we work with lists of keys. The number of keys is given by the schema and not a constant or hard codeable in the source. So to create a new list node we have to first loop on our key list creating an xpath predicate string to pass to lyd_new_list2(). This is pretty sub-optimal :)

Could you add `lyd_new_list_*_keys()` (or whatever) to public API that take `char **keys` input where `keys` is an array of c-strings of the correct length that node (perhaps also a `void **keys` variant to support binary key values)...

**Comment by michalvasko** [comment]
Fine, added.

**Comment by choppsv1** [comment]
Thanks!

**Comment by choppsv1** [comment]
Thanks!
