### ISSUE TITLE
a question about API lyd_dup for leafref node

### ISSUE THREAD

**Issue by qmm161** [CESNET/libyang#212]
Hi

I know the value.leafref of a leafref node is a pointer which point to another lyd_node on the same lyd_tree. The question is if the pointer of a duplicated leafref node should point to the lyd_node on the duplicated lyd_tree or on the original lyd_tree?

I got a sysrepo crush bug when testing with a specific model with notopeer2, I step the code and I think this maybe the key reason.

**Comment by michalvasko** [comment]
Hi,
the leafref reference should now be cleared and the documentation now explains that the duplicated tree needs to be validated separately.

Regards,
Michal
