### ISSUE TITLE
libyang1: what is the right way to free a node in the data tree 

### ISSUE THREAD

**Issue by sharath-arrcus** [CESNET/libyang#2120]
curently I have this; but calling `delete node` is crashing 
```
DataNodeImpl::~DataNodeImpl()
{
        lyd_free_withsiblings(m_node);
}
```

**Comment by michalvasko** [comment]
It is not that simple to write C++ bindings on your own, the memory management is different in C so you would have to do much more than this. My suggestion is to update to libyang v2 and use the existing [C++ bindings](https://github.com/CESNET/libyang-cpp/) for it.

**Comment by sharath-arrcus** [comment]
yes, we would want to update to libyang2 and use libyang-cpp. However we have limitations to upgrade our compiler to GCC 10.x+, clang 10+. In the meantime, can you suggest or share an example of how to do this ?

**Comment by jktjkt** [comment]
> we have limitations to upgrade our compiler to GCC 10.x+, clang 10+

what platform are you building for?

**Comment by sharath-arrcus** [comment]
limitations are not because of the platform, but older libraries

**Comment by jktjkt** [comment]
The last ABI change in GCC/libstdc++ was eons ago (in the 3.3 version IIRC), so it's actually safe to use a newer compiler for the C++ NETCONF/YANG stack. This has been widely demonstrated on, say, RHEL with their `devtoolset` add-on packages. Anyway, if you stick with pre-2x libyang and sysrepo, you're running code which had been already abandoned by its upstream, and which is not getting any fixes anymore. That's not a healthy situation to be in. But hey, it's your product and your resources, so do whatever is OK for you.

To give you a rough estimate, it took us about six month to design and build the C++ bindings and to port all of our internal code to the 2.x version, starting from scratch. IIRC two people worked on this part-time.
