### ISSUE TITLE
Argument #1 of xpath_contains is node "name", not of string-type.

### ISSUE THREAD

**Issue by hyberdk** [CESNET/libyang#2127]
Im trying to use the Cisco-IOS-XE-native.yang models. Im using yanglint to validate the models manually, but essentially Im trying to use YDK-GEN to automate my Cisco configurations with python.

Anyways, Im getting libyang errors when ydk-gen is validating the data, so I wanted to check that the models are valid and error free..

When I validate the Cisco-IOS-XE-native.yang model, I get a lot (like a lot lot) of these warnings.

```
libyang warn: Argument #1 of xpath_contains is node "name", not of string-type.
libyang warn: Argument #1 of xpath_contains is node "name", not of string-type.
libyang warn: Argument #1 of xpath_contains is node "name", not of string-type.
libyang warn: Argument #1 of xpath_contains is node "name", not of string-type.
```

I have narrowed it down to sections like this (in the Cisco-IOS-XE-interfaces.yang sub-module)

```yang
  grouping interface-vmi-grouping {
    leaf mode {
      type enumeration {
        enum bypass;
        enum aggregate;
      }
      default "aggregate";
    }
    leaf physical-interface {
      must '/ios:native/ios:interface/*[concat(local-name(.), ios:name) = current()]';
      type string;
    }
  }
```
ref for above code: https://github.com/YangModels/yang/blob/43f84815fdbf4b374ec58e7a424610bea8c492f1/vendor/cisco/xe/17121/Cisco-IOS-XE-interfaces.yang#L790-L802

If I comment out the must statement i get less errors, I can go though all the must statement that looks like this and it will be warning-free, but since pyang does not complain about this, I was wondering if this could be a bug?

My Yang skills in the must statement/xpaths are not great, that is why I am reaching out.. 

I am using the models here: https://github.com/YangModels/yang/tree/main/vendor/cisco/xe/17121

Any ideas?

Esben

**Comment by hyberdk** [comment]
I was reading a bit on this and testing.. 

it seems like this works better.. 

`must '/ios:native/ios:interface/*[concat(local-name(.), "ios:name") = current()]';`

does it have to be like that work be RFC compliant? as I said pyang does not complain about this :-)

**Comment by michalvasko** [comment]
You are free to ignore this, they are just warnings and in this case I think the XPath should work as intended.
