### ISSUE TITLE
Found a bug for the dec64 value validation

### ISSUE THREAD

**Issue by Gokouneko** [CESNET/libyang#2129]
in the file libyang/src/plugins_types.c:705

```
    case LY_TYPE_STRING:
    case LY_TYPE_DEC64:
    case LY_TYPE_ENUM:
    case LY_TYPE_BITS:
    case LY_TYPE_BINARY:
    case LY_TYPE_IDENT:
    case LY_TYPE_INST:
        if (!(hints & LYD_VALHINT_STRING)) {
            return ly_err_new(err, LY_EVALID, LYVE_DATA, NULL, NULL, "Invalid non-string-encoded %s value \"%.*s\".",
                    lys_datatype2str(type), (int)value_len, value);
        }
        break;
```
the hints of a dec64 value is LYD_VALHINT_DECNUM rather than LYD_VALHINT_STRING。
It would cause all of the dec64 value to be checked as invalid.

**Comment by michalvasko** [comment]
It depends on the encoding, but XML has no types and JSON actually requires a `decimal64` number to be encoded as a string so I believe this code is correct.

**Comment by Gokouneko** [comment]
In my case, for example, when parseing json like `{ "num" : 1.11 }`.
`lydjson_value_type_hint` would set the `type_hint_p` to LYD_VALHINT_DECNUM. 
Then, in `lyplg_type_check_hints`, `LYD_VALHINT_DECNUM & LYD_VALHINT_STRING == 0` and it would return LY_EVALID.

As you mentioned "JSON actually requires a decimal64 number to be encoded as a string", is it means in function `lydjson_value_type_hint` line 376, it should be 
```
} else if (*status_p == LYJSON_NUMBER) {
        *type_hint_p = LYD_VALHINT_DECNUM | LYD_VALHINT_STRING ;
```

**Comment by michalvasko** [comment]
No, it means JSON `{ "num" : 1.11 }` is not a valid representation of any YANG data. You have to write `{ "num" : "1.11" }` instead, read the [specs](https://www.rfc-editor.org/rfc/rfc7951.html#section-6.1).

**Comment by Gokouneko** [comment]
> No, it means JSON `{ "num" : 1.11 }` is not a valid representation of any YANG data. You have to write `{ "num" : "1.11" }` instead, read the [specs](https://www.rfc-editor.org/rfc/rfc7951.html#section-6.1).

I got it, thanks a lot 😊
