### ISSUE TITLE
can libyang support an API to mark some leaf/leaflist with "sensitive"-alike flag?

### ISSUE THREAD

**Issue by lyzliyuzhi91** [CESNET/libyang#2131]
Hi, I have some security restriction on my product for some special leaf like `password`:
1. When the memory of `password` is freed, the content should also be cleared;
2. The logs should not record the value. Now when libyang parse or validate value of such nodes with some error like `Unsatisfied length `, libyang will record the value in the log. Can libyang mask the value with something like `******` when the node has been set such "sensistive" flags?
Thanks.

**Comment by michalvasko** [comment]
1. You can achieve this by defining your own `typedef` and then using a custom plugin that will free the memory the way you want.
2. This does not seems like a good idea, the proper error should probably be sent to a NETCONF client, for example, if it makes an invalid edit. You have mentioned only logging so you should secure the access to the logs if an unauthorized users could view them.
