### ISSUE TITLE
Generate Windows version of libyang error

### ISSUE THREAD

**Issue by God-SEVEN** [CESNET/libyang#2133]
Hello, 
      as the title says, I compiled the Windows version of libyang according to the required environment, but many problems occurred. Can the author give more compilation guidance related to the Windows version? 
     Thank you so much.

**Comment by jktjkt** [comment]
It passes just fine in the CI, the build recipe is in https://github.com/CESNET/libyang/blob/master/.github/workflows/ci.yml
