### ISSUE TITLE
List instance is missing its key error while parse 

### ISSUE THREAD

**Issue by sicongPang** [CESNET/libyang#2136]
hi
When I try to use libyang 2.1.30 to parse the <get> rpc message, the error message "List instance is missing its key "OCSAddr" is displayed. My message is in XML format.
By analyzing the code, he reported an error in the lydxml_subtree_r->lyd_parse_check_keys function.

Here's the modeling information I've provided：
```yang
container OCSStatuss {
      list OCSStatus {
        key "HostName ResourceUnit LocAddr SubLocAddr OCSAddr";
        config false;
        description
          "OCS Status";
        leaf RecId {
          type uint32 {
            range "0..4294967295";
          }
          mandatory false;
          description
            "Record ID";
          mo:indexAssignMode "INC";
        }
        leaf HostName {
          type string {
            length "0..127";
          }
          mandatory false;
          description
            "OCS Host Name";
          mo:indexAssignMode "MIN";
        }
        leaf SpuGrp {
          type uint32 {
            range "1";
          }
          mandatory false;
          description
            "SPU Group ID";
          mo:indexAssignMode "MIN";
        }
        leaf ResourceUnit {
          type string {
            length "0..63";
          }
          mandatory false;
          description
            "RU Name";
          mo:indexAssignMode "MIN";
        }
        leaf LocAddr {
          type string {
            length "0..63";
          }
           mandatory false;
           description
             "Local Address";
           mo:indexAssignMode "MIN";
         }
         leaf SubLocAddr {
           type string {
             length "0..63";
           }
           mandatory false;
           description
             "Local Sub-Address";
           mo:indexAssignMode "MIN";
         }
         leaf OCSAddr {
           type string {
             length "0..63";
           }
           mandatory false;
           description
             "Peer Address";
           mo:indexAssignMode "MIN";
         }
         leaf LocalHostName {
           type string {
             length "0..127";
           }
           mandatory false;
           description
             "Local Host Name";
           mo:indexAssignMode "MIN";
         }
       }
    }
```
This is the get request message I sent:
![image](https://github.com/CESNET/libyang/assets/104370071/bce67d9a-8f23-48e0-850e-2bbec1e0202f)

According to the node parameter of the lyd_parse_check_keys function, the key field OCSAddr is behind a non-key. As a result, the function reports an error.
![image](https://github.com/CESNET/libyang/assets/104370071/730b58c2-67ce-41f0-becb-7ee32d399f50)

**Comment by sicongPang** [comment]
The libnetconf2 2.1.28 version is used.

I reconstructed another model, and it worked fine, as shown in the following figure.
![image](https://github.com/CESNET/libyang/assets/104370071/1e38edce-3474-4c24-813e-4c223103c5b8)

But once I used the above mentioned model "OCSStatuss", the problem revealed that none of my other behaviors changed, which I was puzzled by.
![image](https://github.com/CESNET/libyang/assets/104370071/09f2c934-3001-4e42-9e67-8e2d71279cf0)

**Comment by michalvasko** [comment]
You are free to go commit-by-commit and find the one that fixed it, but it is not part of the support we provide.

**Comment by sicongPang** [comment]
By printing the content in the lyd_insert_node function, I found that when the key is inserted into the third node or later, first_sibling->prev equals first_sibling->next. As a result, the key cannot be inserted into the first node.
![image](https://github.com/CESNET/libyang/assets/104370071/9678bab4-7bf0-49a4-84f0-1061584cb05c)
![image](https://github.com/CESNET/libyang/assets/104370071/c196c0b6-2e8a-4d3d-bb70-e8e8964faaaf)

The above part comes from the commit record:
https://github.com/CESNET/libyang/commit/6a0bb25952429185c42974d6dab31bbf39083925
Finally, the lyd_parse_check_keys function fails. The information about the node parameter is as follows:
![image](https://github.com/CESNET/libyang/assets/104370071/5d50e9c3-a754-473b-8216-19ce74525284)

**Comment by michalvasko** [comment]
Thanks for the example, it should be fixed in the latest *libyang*, test added into *netopeer2*.

**Comment by NextLitete** [comment]
@michalvasko @sicongPang 
I've had the same problem, but I don't think it's a bug.
According to RFC7950 7.8.5：
_The rest of the list’s child nodes are encoded as subelements to the
list element, after the keys._

**Comment by michalvasko** [comment]
Fair enough, I suppose it can be considered to be a minor extension but it is generally accepted that this should be supported in practice.
