### ISSUE TITLE
lyd_find_xpath() failed to parse rpc-reply leaf-ref node

### ISSUE THREAD

**Issue by OSHINRAJ** [CESNET/libyang#2137]
We are performing an rpc action for the following o-ran-ald.yang module

```sh
module: o-ran-ald
  rpcs:
    +---x ald-communication
       +---w input
       |  +---w port-id        -> /ap:ald-ports-io/ald-port/port-id
       |  +---w ald-req-msg?   binary
       +--ro output
          +--ro port-id                      -> /ap:ald-ports-io/ald-port/port-id
          +--ro status                       enumeration
          +--ro error-message?               string
          +--ro ald-resp-msg?                binary
          +--ro frames-with-wrong-crc?       uint32
          +--ro frames-without-stop-flag?    uint32
          +--ro number-of-received-octets?   uint32

```

On executing rpc, the reply obtained is as shown below;
```sh
<ald-communication xmlns="urn:o-ran:ald:1.0">
    <port-id>0</port-id>
    <status>REJECTED</status>
    <error-message>HDLC Rx failed!</error-message>
    <ald-resp-msg/>
    <frames-with-wrong-crc>0</frames-with-wrong-crc>
    <frames-without-stop-flag>0</frames-without-stop-flag>
    <number-of-received-octets>0</number-of-received-octets>
</ald-communication>
```
From the obtained lyd_node, we try to retrieve the port-id data  using `lyd_find_xpath()`

```sh 
lyd_find_xpath(root, xpath, &set)
```

Where root is the lyd_node corresponding to the rpc-reply we obtained, and xpath is `/o-ran-ald:ald-communication/port-id`
But the value for `set->count` obtained is 0, but the expected value is 1. So we are unable to get data corresponding to port-id since data is taken from `set->dnodes` as per this count. 

It works fine for all the other leaf node  xpath tested and the results are shown below;

![correct](https://github.com/CESNET/libyang/assets/28524977/1da20f4f-aa23-4327-8299-1132a5961569)

`Note : libyang version used is  v2.1.111`

**Comment by michalvasko** [comment]
That is rather strange, are you sure the node is there? You can verify by printing the whole RPC with `lyd_print_file()`.

**Comment by OSHINRAJ** [comment]
We have printed the rpc reply node using the `lyd_print_file()'

![print_lyd](https://github.com/CESNET/libyang/assets/28524977/c9f850cd-f0fb-4f07-b208-28b6e429057f)

and we got the output as follows;

```sh
<ald-communication xmlns="urn:o-ran:ald:1.0">
    <port-id>0</port-id>
    <status>REJECTED</status>
    <error-message>HDLC Rx failed!</error-message>
    <ald-resp-msg/>
    <frames-with-wrong-crc>0</frames-with-wrong-crc>
    <frames-without-stop-flag>0</frames-without-stop-flag>
    <number-of-received-octets>0</number-of-received-octets>
</ald-communication>
```

**Comment by OSHINRAJ** [comment]
![Screenshot from 2023-11-30 14-57-38](https://github.com/CESNET/libyang/assets/28524977/47abd2a1-8c3b-4cc5-b049-08fa1c3b1f7b)

This is the tree representation of the yang model;

If you check closely, the xpath `/o-ran-ald:ald-communication/port-id` can point to the port-id in rpc input as well as rpc output.
Also it is a leaf-ref to the another yang model. 

Do you think any of this causes the issue?

**Comment by michalvasko** [comment]
Okay, sorry, the name conflict actually caused the problem because of some optimizations that did not anticipate this. Should work in the latest `devel` version.
