### ISSUE TITLE
Broken links to documentation

### ISSUE THREAD

**Issue by Krisscut** [CESNET/libyang#2142]
Hi,

Not sure if this is the right repo, but it seems all the links **regarding the documentation** on  https://netopeer.liberouter.org/ **for the libyang section** are broken 

![image](https://github.com/CESNET/libyang/assets/8125922/f40c8080-2f8b-459a-95a8-d7ba69958b49)

For instance https://netopeer.liberouter.org/doc/libyang/master/html/

**Comment by michalvasko** [comment]
Sorry about that, `cron` keeps refusing to work properly but we are working on making sure it does. Currently, the docs are online and we are monitoring the situation.

**Comment by Krisscut** [comment]
yes indeed, sorry I didn't close this earlier.

Thanks !
