### ISSUE TITLE
Crash in get_node_pos when adding a second object

### ISSUE THREAD

**Issue by maxrossello** [CESNET/libyang#2144]
Hi,
I'm working with netopeer2 v2.1.71 and libyang 2.1.128 both current master (libnetconf2 v2.1.37, sysrepo master not tagged hash 0af1daaf36b4be7cafa58eda82b23927a9e027e1).
Tried to use all devel, but I was stuck in an installation problem.

Using O-RAN models v10.00.00 ([o-ran-uplane-conf@2022-08-15.yang.gz](https://github.com/CESNET/libyang/files/13651371/o-ran-uplane-conf%402022-08-15.yang.gz)), whenever I add a second carrier netopeer2-server crashes in get_node_pos (libyang/src/xpath.c:1445) because elem->schema is null

<pre>if ((root_type == LYXP_NODE_ROOT_CONFIG) && (elem->schema->flags & LYS_CONFIG_R)) {</pre>

Adding a single carrier works fine. Here is some example minimal edit-config contents:

```
<config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
    <user-plane-configuration xmlns="urn:o-ran:uplane-conf:1.0">
        <tx-array-carriers> <name>DL_carrier_1</name> <center-of-channel-bandwidth>3500000000</center-of-channel-bandwidth> <channel-bandwidth>20000000</channel-bandwidth> </tx-array-carriers>
        <tx-array-carriers> <name>DL_carrier_2</name> <center-of-channel-bandwidth>3550000000</center-of-channel-bandwidth> <channel-bandwidth>20000000</channel-bandwidth> </tx-array-carriers>
    </user-plane-configuration>
</config>
```
I have upgraded the software after long time, then my regression test suite discovered this. Former versions worked fine, with hashes:  libyang v2.0.31 0c609c3, netopeer2 v2.1.36 57396a1, libnetconf2 v2.1.18 1f50231, sysrepo v2.1.84 df89fc0.

This happens without any management plugin attached. I have not been able to reproduce with different type of objects though.

Glad to provide further information if needed. Thanks!

PS: when using devel, make install of netopeer2 returns
[ERR] Refine(s) target node "cert" in grouping "trust-anchor-cert-grouping" was not found. (Path "/ietf-truststore:truststore/{uses='truststore-grouping'}/certificates/certificate/{uses='ct:trust-anchor-cert-grouping'}".)

**Comment by maxrossello** [comment]
I used sysrepo from master because of upgrade installation problems which the master didn't show up. Reverting then to v2.2.105 as per official release goes as expected and regarding the issue it seems to work properly.
I therefore close my issue, sorry for bothering. Hope the feedback is at least useful for consolidating the next release.
Thanks for the great job!

**Comment by michalvasko** [comment]
Thanks, the last place a check was missing, should now be fixed.
