### ISSUE TITLE
incorrect comment for choice/cases

### ISSUE THREAD

**Issue by choppsv1** [CESNET/libyang#2151]
`lysc_node_choice` has the cases field with a comment that seems wrong.

```
    struct lysc_node_case *cases;    /**< list of the cases (linked list). Note that all the children of all the cases are linked each other
                                          as siblings. Their parent pointers points to the specific case they belongs to, so distinguish the
                                          case is simple. */
```

What I'm actually seeing is a linked list of cases (`lysc_node_case`), and each case has it's own children linked in isolation. The children of all the cases are not linked together as the comment indicates. This is too bad b/c it would have been better suited to my usecase too.

**Comment by michalvasko** [comment]
You are right, this change has been made a long time ago but the description was not updated. Whatever schema node iteration you need, `lys_getnext()` (with the correct flags) should cover it.
