### ISSUE TITLE
[Question] About lyd_create_inner

### ISSUE THREAD

**Issue by vc15air** [CESNET/libyang#2153]
Hi,

I have a question need confirm with you.

We check the lyd_create_inner API, the parameter `in` will calloc the memory.
But we did not find where will free the `in`, it only free the `in->node` if error.

```
LY_ERR
lyd_create_inner(const struct lysc_node *schema, struct lyd_node **node)
{
    struct lyd_node_inner *in;

    assert(schema->nodetype & LYD_NODE_INNER);

    in = calloc(1, sizeof *in);  <----------------------------------------------------------- calloc memory
    LY_CHECK_ERR_RET(!in, LOGMEM(schema->module->ctx), LY_EMEM);

    in->schema = schema;
    in->prev = &in->node;
    in->flags = LYD_NEW;
    if ((schema->nodetype == LYS_CONTAINER) && !(schema->flags & LYS_PRESENCE)) {
        in->flags |= LYD_DEFAULT;
    }

    /* do not hash list with keys, we need them for the hash */
    if ((schema->nodetype != LYS_LIST) || (schema->flags & LYS_KEYLESS)) {
        lyd_hash(&in->node);
    }

    *node = &in->node;
    return LY_SUCCESS;
}


static LY_ERR
lyb_parse_node_inner(struct lyd_lyb_ctx *lybctx, struct lyd_node *parent, const struct lysc_node *snode,
        struct lyd_node **first_p, struct ly_set *parsed)
{
    LY_ERR ret = LY_SUCCESS;
    struct lyd_node *node = NULL;
    struct lyd_meta *meta = NULL;
    uint32_t flags;

    /* read necessary basic data */
    ret = lyb_parse_node_header(lybctx, snode, &flags, &meta);
    LY_CHECK_GOTO(ret, error);

    /* create node */
    ret = lyd_create_inner(snode, &node);  <-------------------------------------------only use node
    LY_CHECK_GOTO(ret, error);

    assert(node);
    LOG_LOCSET(NULL, node, NULL, NULL);

    /* process children */
    ret = lyb_parse_siblings(lybctx, node, NULL, NULL);
    LY_CHECK_GOTO(ret, error);

    /* additional procedure for inner node */
    ret = lyb_validate_node_inner(lybctx, snode, node);
    LY_CHECK_GOTO(ret, error);

    if (snode->nodetype & (LYS_RPC | LYS_ACTION | LYS_NOTIF)) {
        /* rememeber the RPC/action/notification */
        lybctx->op_node = node;
    }

    /* register parsed node */
    lyb_finish_node(lybctx, parent, flags, &meta, &node, first_p, parsed);

    LOG_LOCBACK(0, 1, 0, 0);
    return LY_SUCCESS;

error:
    if (node) {
        LOG_LOCBACK(0, 1, 0, 0);
    }
    lyd_free_meta_siblings(meta);
    lyd_free_tree(node);  <----------------------------------------------------------- only free node if error
    return ret;
}
```
Could you tell me is the memory leak? or is the current design? 
thanks a lot.

**Comment by michalvasko** [comment]
Report only memory leaks found by tools such as `valgrind` or memory sanitizer. `in->node` actually points to `in` but differs in the type.

**Comment by vc15air** [comment]
> Report only memory leaks found by tools such as `valgrind` or memory sanitizer. `in->node` actually points to `in` but differs in the type.

ok, thanks a lot.

**Comment by vc15air** [comment]
Actually, we use libscan to check the memory leaks.
But we will detect this memory leaks if we subscribe another callback function(**sr_oper_get_subscribe**)
We only use lyd_new_path in our callback. (we following np2srv_oper_sub_ntf_streams_cb to subscribe the callback)

```
lyd_node *root = NULL;

if(lyd_new_path(NULL, sr_session_acquire_context(session), "/test-interfaces:interface-top", NULL, 0, &root))
{
    goto error;
}

return SR_ERR_OK;
error:
    lyd_free_tree(root);
    return SR_ERR_CALLBACK_FAILED;
```

Do you have ideas how to resolve this issue? thanks a lot.

**Comment by vc15air** [comment]
> If this is the whole code then yes, obviously, the `root` node will leak, it is not being returned or anything.

sorry, updated the example, thanks.

**Comment by michalvasko** [comment]
What is the `xpath` you have subscribed this callback for?

**Comment by vc15air** [comment]
We use the following xpath.
```
xpath =  /test-interfaces:interface-top/interface-status/interface
```

**Comment by michalvasko** [comment]
Then the nodes `/test-interfaces:interface-top/interface-status` are already provided in `*parent` and you are supposed to add only the `interface`. By writing into `*parent` you cause the leak.

**Comment by vc15air** [comment]
> Then the nodes `/test-interfaces:interface-top/interface-status` are already provided in `*parent` and you are supposed to add only the `interface`. By writing into `*parent` you cause the leak.

So in anther case,

if the xpath is `/test-system:system-top/memory-status`, we only create the `memory-status` node and add to `*parent` in callback function, then we will get current data?

**Comment by vc15air** [comment]
ok, thanks a lot, we will try it.

**Comment by vc15air** [comment]
Hi Michal,

We try the way that you provided, our memory sanitizer did not report the leaks.
Thanks a lot.
