### ISSUE TITLE
Error logging for acceptable result.

### ISSUE THREAD

**Issue by choppsv1** [CESNET/libyang#2156]
I'm calling the function `lys_find_path()` with an xpath. I may or may not have all the modules loaded that nodes in that xpath refer to

/foo:foo/bar/baz:baz

So e.g., say I don't have the module `baz` loaded. I would expect to get a NOT FOUND error back (or whatever), but I would not expect error level logging to be emitted by the library which is what happens:

```
2024/01/18 20:49:16 RIP: libyang: No module connected with the prefix "frr-zebra" found (prefix format JSON module names).
```

Is there some other API I can use that won't emit an error level log, or some way to suppress the error level log message during the above call?

**Comment by michalvasko** [comment]
You can always temporarily turn off logging using `ly_temp_log_options()`, which is also thread-safe. So I would suggest you use that.

**Comment by jktjkt** [comment]
Just for the record, we are also calling libyang with possibly non-existing paths in netconf-cli, and we had to add a workaround that simply discards this error in that particualr code path, https://github.com/CESNET/netconf-cli/blob/master/src/yang_schema.cpp#L84 . It isn't pretty.
