### ISSUE TITLE
Question regarding lyd_parse_data

### ISSUE THREAD

**Issue by idryzhov** [CESNET/libyang#2163]
The doc says the following about the `tree` param:
```
Full parsed data tree, note that NULL can be a valid tree. If @p parent is set, set to NULL.
```
Deeper into the code, the doc for `lyd_parse` says about the same argument:
```
Pointer to the first top-level parsed node, used only if @p parent is NULL.
```

The actual behavior is actually different - both functions support passing `parent` and `tree` simultaneously and actually return the correct `tree` even if the `parent` was passed.

I am wondering, is this just an outdated doc? Can I rely on the current behavior?

**Comment by michalvasko** [comment]
> actually return the correct tree even if the parent was passed.

That seems to be the problem, what exactly is the correct `tree`? And you are reading the code wrong, the docs is correct. `lyd_parse` set the value of `first_p` even if `parent` is set but only for convenience, the value of `*first_p` is not set so it is not modified on return.

**Comment by idryzhov** [comment]
By correct I mean pointing to the first top-sibling of a newly created data. I suppose the validation call sets the `*first_p`:
```
    if (!(parse_opts & LYD_PARSE_ONLY)) {
        /* validate data */
        r = lyd_validate(first_p, NULL, ctx, val_opts, 0, &lydctx->node_when, &lydctx->node_types, &lydctx->meta_types,
                &lydctx->ext_node, &lydctx->ext_val, NULL);
        LY_CHECK_ERR_GOTO(r, rc = r, cleanup);
    }
```
But it won't be set if I use `LYD_PARSE_ONLY`.

**Comment by michalvasko** [comment]
> By correct I mean pointing to the first top-sibling of the newly created data.

When you set `parent` the first top-level sibling will always be `parent`, that is the "problem". But you are right, the validation can move the pointer which is then returned, if it does not then it is not. So I think it should be cleared and always returned as `NULL` if `parent` is set.

**Comment by idryzhov** [comment]
That's not what I see. I receive a pointer to the node representing the parsed data (as I would expect).

Like, with the following model:
```
module test {
  yang-version 1.1;
  namespace "urn:test:test";
  prefix t;

  container c {
    list l {
      key "name value";

      leaf name {
        type string;
      }
      leaf value {
        type string;
      }
    }
  }
```
When I have the `c` node as `parent` and parse:
```
{
  "test:l": [
    {
      "name": "first",
      "value": "one"
    }
  ]
}
```
I receive back a pointer to the new instance of `l`.

And this is expected and convenient behavior - I parse the data and want to receive a node representing this data, regardless of parent being NULL or non-NULL.
So it would be much better to always return this pointer, instead of always returning NULL.

**Comment by michalvasko** [comment]
Whatever, if you think it is useful for anything, it can stay this way and is now documented.

**Comment by idryzhov** [comment]
Well, it's an easy way to get the parsed node. I could probably scan through all the `parent`'s children to find the one with `LYD_NEW` flag set, but this solution is much easier. Thanks for the update!
