### ISSUE TITLE
Why return failure when "deviate delete" a "mandatory" statement ?

### ISSUE THREAD

**Issue by lyzliyuzhi91** [CESNET/libyang#2165]
https://github.com/CESNET/libyang/blob/fc4dbd923e044006c93df020590a1e5a8656c09e/src/parser_yang.c#L3955

Why success for "must" but failure for "mandatory"/"min-element"/... ?
thanks

**Comment by michalvasko** [comment]
In short, because in [`deviate-delete-stmt`](https://www.rfc-editor.org/rfc/rfc7950.html#page-201) there is no `mandatory` in the YANG ABNF.
