### ISSUE TITLE
How to create lyd_node for a leaf with no value?

### ISSUE THREAD

**Issue by abhikeshav** [CESNET/libyang#217]
Hello,

I'm trying to create a lyd_node* like below, to be used, for example, in `<filter>` element of `<get-config>` RPC:
```
<parent>
   <number8/>
</parent>
```

```
container parent {
  leaf number8 {
    type int32;
  }
}
```

Looking at the libyang docs, I found ```lyd_new_output_leaf()``` and a couple other methods, but they do not accept empty value for the above leaf and produce an error:
```c++
struct lyd_node* child = lyd_new_output_leaf(parent, NULL,"number8", ""); // error occurs
struct lyd_node* child = lyd_new_output_leaf(parent, NULL,"number8", ""); // error occurs
struct lyd_node* child = lyd_new_leaf(cn, NULL, "number8", ""); // error occurs
...
```
```
libyang[3]: DICT: inserting "" with collision 
libyang[0]: Invalid value "" in "number8" element. (path: /test:parent/number8)
```

Is there any other API for the above in libyang?

**Comment by ostack** [comment]
I have the same questions.
before commit https://github.com/CESNET/libyang/commit/c113a69d2773bfa26f7f2f04e249b5472d3ff74a
use lyd_new_path can create lyd node with "null" value, and after this commit it reported errors

**Comment by michalvasko** [comment]
Hi,
whatever the case was before, if you have leaf of any numeral type, an empty value is not valid, so the error is correct.

Regards,
Michal

**Comment by rkrejci** [comment]
`<filter>` is defined as `anyxml` and because of the differencies like the selection nodes (empty node, whatever type of node it is in YANG module), using functions intended for building data tree is quite problematic in case of building subtree filter which differs from the data tree format..
