### ISSUE TITLE
How Do I Modify a Model Using a Hot Patch?

### ISSUE THREAD

**Issue by NextLitete** [CESNET/libyang#2184]
A model already exists in the current context.
I would like to modify this model to be implemented in a patch.
In libyang1, I can use ly_ctx_remove_module to uninstall a model and then reload a new version of the model. Does libyang2 provide similar functions?

**Comment by michalvasko** [comment]
You cannot directly do this anymore (the operation is simply too complex) and you may simply create a new context with the new module instead of the old one. YANG can have lots of inter-dependencies between the modules and to recheck them all is just not worth it.

**Comment by NextLitete** [comment]
fine
