### ISSUE TITLE
Remove state data from tree

### ISSUE THREAD

**Issue by Tobulus** [CESNET/libyang#2196]
Hi,

Is it currently possible to remove state data from a data tree? I can see that there are options for `validate` and `parse` which deal with state data but don't remove it.

Use case: for a client I return data from the operational datastore. He changes some config values and sends everything back, which might include state data. I want to filter it before writing to running.

**Comment by michalvasko** [comment]
No, there is no such functionality provided so you will have to that yourself (should be trivial).

**Comment by tbsuht** [comment]
Could you guide me to some useful functions to build this? In principal I want to setup an API like given with `parse_data`.

**Comment by michalvasko** [comment]
I can even write it for you.
```C
ly_set_new(&to_free);

LYD_TREE_DFS_BEGIN(root, elem) {
    if (elem->schema->flags & LYS_CONFIG_R) {
        ly_set_add(to_free, elem, 1, NULL);
        LYD_TREE_DFS_continue = 1;
    }
    LYD_TREE_DFS_END(root, elem);
}

for (i = 0; i < to_free->count; ++i) {
    lyd_free_tree(to_free->dnodes[i]);
}
ly_set_free(to_free, NULL);
```
I have not tried to compile it but I hope it is clear enough.

**Comment by Tobulus** [comment]
@michalvasko Great, works! Thanks for the example and fast reply!
