### ISSUE TITLE
Possibility to configure the below second precision of event time of notifications

### ISSUE THREAD

**Issue by alexandrustancu** [CESNET/libyang#2197]
Hello,

Currently, the precision of a notification was increased to nanoseconds, and e.g. it looks like this:
```
<notification xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0">
  <eventTime>2024-02-12T12:03:06.372283520+00:00</eventTime>
  <alarm-notif xmlns="urn:o-ran:fm:1.0">
```
We have seen that some NETCONF Clients (e.g. OpenDaylight) have some problems with such precision, e.g.:

```
2024-02-07T17:19:40,519 | TRACE | globalWorkerGroup-3-15 | NetconfDeviceCommunicator        | 324 - org.opendaylight.netconf.sal-netconf-connector - 5.0.7 |  -  | RemoteDeviceId[name=Adapter01, address=/172.60.0.36:830]: Notification received: <notification xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0">
    <eventTime>2024-02-07T17:19:40.508223593+00:00</eventTime>
    <supervision-notification xmlns="urn:o-ran:supervision:1.0"/>
</notification>

2024-02-07T17:19:40,520 | WARN  | globalWorkerGroup-3-15 | NetconfNotification              | 319 - org.opendaylight.netconf.notifications-api - 5.0.7 |  -  | Fraction of second is cut to three digits. Value that was cut 223593
```
i.e. it cannot handle such precision, and for notifications that come every second, the log is flooded because of this.

A corresponding issue was added in OpenDaylight as well, such that it can handle such precision, [here](https://jira.opendaylight.org/browse/NETCONF-1262).

Is there any possibility to configure the precision, such that the user can choose (whenever, at compile time, boot time etc.) the sub-second precision? If not, do you think it's worth adding such a capability?

**Comment by michalvasko** [comment]
> Is there any possibility to configure the precision, such that the user can choose (whenever, at compile time, boot time etc.) the sub-second precision? If not, do you think it's worth adding such a capability?

It cannot be configured and I see no reason for adding such a possibility. Tools must be able to parse any precision and then can round it (when printed) however they want.

**Comment by alexandrustancu** [comment]
Thanks, Michal, for the timely response!
