### ISSUE TITLE
YANG extensions support

### ISSUE THREAD

**Issue by rkrejci** [CESNET/libyang#220]
Hi,
some of the users already showed their willing to have YANG extensions support in libyang. Current code in master as well as in devel does not support extensions at all. They are actually removed from the module which then makes input and output modules different.

I already have code supporting extensions in a separate branch. But the problem with YANG extension is that they can contain anything and can appear anywhere. The current code limit this which helps quite a lot, but now I seen some modules used by confd (formely tail-f, now cisco) and they use extension in statements we didn't expect - e.g. path or argument, simply in usually text nodes which are currently represented in libyang as 'const char*'. So the question is if keep some limitations about the place where the extension can be instantiated or if we should have more generic implementation.

The issue with the generic approach is
a) more space for schema tree, which shouldn't be a big problem since the data tree space is more critical
b) we would have to change a lot in lys_* structures, e.g. description or module prefix, now being represented as 'const char *' would have to change to a structure which would contain the value and pointer to the possible extension instances.

So the question is if to do a big change in libyang API/ABI, or limit extensions support.

Regards,
Radek

**Comment by fanchanghu** [comment]
Hi,
I noticed that no one discussed about this, I want to give my opinion.
I think we should do a big change in libyang API/ABI, because we need support all YANG features as a YANG library. If we really need do something, to do it earlier is almost a better choose.
Thanks.

**Comment by rkrejci** [comment]
Hi, thanks for your contribution. We had some internal discussions about this and the intention is to support YANG extensions as they are defined - completely generic and in any other YANG statement. And yes, we have to do the change as soon as possible. 

However, we want to minimize the impact of the mentioned issues at the cost of a little bit more complicated work with the extensions instantiated in several statements like `description` or `default`. As mentioned in my initial comment, these statements are implemented in libyang as `const char *` and supporting a substatement (YANG extensions) in them would lead to changing it to structures. And such a change seems too big.

I have some initial implementation in a separate `extensions` branch. Extensions in the YANG statements that do not have any (other than extension instance) substatement, such as `description`, are actually stored in the parent structure. For example, if you have an extension in description of the module, the extension instance structure is actually stored in the module structure (`lys_module`) with the other extension instances of the module itself. There is a mechanism to be able to detect to which substatement the extension belongs to, so no information is lost, but it is not as straightforward as storing the extension instance directly in a statement structure.

The mentioned implementation in the `extension` branch is not done yet and many features are not yet implemented (extension instance are parsed only in several statements and even this works only in YIN parser for now). However, the schema tree structures are already changed, so you can see how the extension instances are going to be stored. Also the NACM extensions are already changed from the hardcoded flags into a generic plugin which is a way we want to implement all extensions. I will welcome any feedback to the ongoing work. The plan is to have it done within a month.

In some short term, I want to post here some numbers about changes of the memory consumption, but it seems that, with the described approach, the memory consumption increase is not as big as I was afraid of.

**Comment by rkrejci** [comment]
Here is the comparison of the schema structures. The change is not as big as we were afraid of.
![image](https://cloud.githubusercontent.com/assets/6471899/23400265/b68a3b68-fda3-11e6-8b55-26cf4a656777.png)

The extension support is currently implemented in devel branch, so I'm closing this issue.
