### ISSUE TITLE
Cyclic dependency in case of mutual exclussion

### ISSUE THREAD

**Issue by idumitrescu-dn** [CESNET/libyang#2210]
Hello,

I have a case that I believe to be a false positive. Based on the discussion [here](https://discuss.tail-f.com/t/xpath-negation/196/4), trying to have two leafs be mutually exclusive using the `when` statement, yanglint gives a cyclic dependency error.

Given the following yang:

```javascript
module test {
    namespace "http://test.com/ns/yang/test";
    prefix test;
    container in
    {
        leaf A {
            type empty;
        }
        leaf B {
            type string;
            when "not(../C)";
        }
        leaf C {
            type string;
            when "not(../B)";
        }
    }
}
``` 

Yanglint gives:
```
# yanglint -v
yanglint 2.1.148
# yanglint test.yang
libyang err : When condition cyclic dependency on the node "C". (Schema location "/test:in/B".)
```

I understand that 2 leafs must not have statements that both point to each other at the same time, and what is the case here is two leafs not accepting the other, i.e. mutual exclusivity.

Thank you

**Comment by michalvasko** [comment]
The spec ([RFC](https://datatracker.ietf.org/doc/html/rfc7950#page-137), second to last paragraph) is quite clear, this is not allowed. Note that you could express the same logic with a `choice`.

**Comment by idumitrescu-dn** [comment]
Hey Michal,

Thank you for the response.

What would be the correct way to handle the same issue when the leafs are on different levels, belonging to different containers?

For example:

```yang
module test {
    namespace "http://test.com/ns/yang/test";
    prefix test;
    container in
    {
        leaf A {
            type empty;
        }
	container inner_1 {
		leaf B {
			type string;
			when "not(../../inner_2/inner_2_1/C)";
		}
	}
	container inner_2 {
		container inner_2_1 {
			leaf C {
				type string;
				when "not(../../../inner_1/B)";
			}
		}
        }
    }
}
```

As far as I see, a choice won't help with such a situation.

Cheers

**Comment by michalvasko** [comment]
Yes, you cannot use a `choice` nor a `when`. There are some limitations to YANG but you usually can use a different solution for most of such problematic cases. You could use a `must` condition instead and add a special "unused" value for both the leaves, then check it in in the condition.

**Comment by idumitrescu-dn** [comment]
Thank you for the help
