### ISSUE TITLE
Allowance for `deviate replace` of other implicit properties like `config`

### ISSUE THREAD

**Issue by esmasth** [CESNET/libyang#2212]
CESNET/libyang#2114 has been resolved for `config` statements. It would be good to be consistent and apply the same principle to other implicit properties

- `mandatory` (default false)
- `max-elements` (default unbounded)
- `min-elements` (default 0)

**Comment by michalvasko** [comment]
Okay, I suppose, changed.

**Comment by esmasth** [comment]
Thanks a lot for the swift response, @michalvasko.
