### ISSUE TITLE
Disabled node is referenced as unique in the list

### ISSUE THREAD

**Issue by lorandt1** [CESNET/libyang#2217]
Hi,

After I upgraded to devel for both libnetconf2 and libyang I faced this error: 
`ly ERR: Disabled n ode "fs-offset" is referenced as unique in the list "dynamic-compression-configuration".()`
Could you please help in identifying whether it is a valid issue in YANG file or a bug in libyang ? 

Yang file and logs attached.
Thank you! 

[o-ran-uplane-conf.txt](https://github.com/CESNET/libyang/files/14883079/o-ran-uplane-conf.txt)
[Logs.txt](https://github.com/CESNET/libyang/files/14881286/Logs.txt)

**Comment by michalvasko** [comment]
The error was correct, in a way, but the module was also correct and could not be fixed, so I have removed the error and it should work normally now.

**Comment by lorandt1** [comment]
It works, thank you!
