### ISSUE TITLE
Facing error: When condition is accessing its own conditional node children

### ISSUE THREAD

**Issue by devanathan-krishnan** [CESNET/libyang#2221]
Hi,

I have following yang which is working fine for many years. We use yumapro netconf server and libnetconf1 client. Now, When I try to migrate to libnetconf2, which uses libyang2, I am getting "When condition is accessing its own conditional node children" error when libnetconf loads this yang from server capability. Similar errors seen on few other yangs as well which I have not listed here.

import ietf-interfaces { prefix "if"; }
augment "/if:interfaces" {
list interface-range {
  when "type = 'ianaift:l2vlan' or type = 'ianaift:l3ipvlan'";
  description
  ...
  ...
  leaf type {
    type identityref {
      base if:interface-type;
    }
    mandatory true;
    description
      "The type of interface range.";
  }
  ...
  ...

I am trying to understand more on this error from libyang2. It would be great if you could provide some insight on why is this restriction needed and how can I overcome this to achieve the existing functionality of my yangs.

Thanks

**Comment by michalvasko** [comment]
Please stop creating duplicate issues, the same issue as cesnet/libnetconf2#474.
