### ISSUE TITLE
'when' function parsing failed with namespace prefix

### ISSUE THREAD

**Issue by morganzhh** [CESNET/libyang#223]
I have two yang file, one is a, the other is b

a.yang

```yang
module a {

    namespace "http://www.test.com/a";
    prefix "testa";

    identity whoami {
    }

    typedef typewho {
        type identityref {
            base whoami;
        }
    }

    leaf-list who {
        type typewho;
    }
    
    container test {
        leaf first {
            type string;
        }
    }
}
```

b.yang

```yang
module b {
    namespace "http://www.test.com/b";
    prefix "testb";

    import a {prefix "testa"}

    identity iamb {
        base testa:whoami;
    }

    augment "/testa:test" {
        when "count(../testa:who[normalize-space(test())='iamb']) >0" {
        }

        leaf second {
            type string;
        }
    }
}
```

If I use this xml to do the validation, it's success, libyang 'when' return 'true'

```xml
<testa:who xmlns="http://www.test.com/b">iamb</testa:who>
<testa:test>
<second xmlns="http://www.test.com/b">abcd</second>
</testa:test>
```

And if I use namespace prefix, libyang 'when' return false

```xml
<testa:who xmlns:testb="http://www.test.com/b">testb:iamb</testa:who>
<testa:test>
<second xmlns="http://www.test.com/b">abcd</second>
</testa:test>
```

```
When condition "count(../testa:who[normalize-space(text())='testb'])>0" not satisfied
```

I am not sure this is the 'yang' file 'when' statement define mistake or a libyang issue?

Please advise, thanks a lot

**Comment by michalvasko** [comment]
Hi,
I will need much more information and the exact problematic use-case. Please provide full data files (or are the examples you posted full?) and steps to reproduce your problem, best if using `yanglint`. Because the XMLs you posted have undefined namespace prefixes and the namespaces defined without a prefix are wrong based on your models.

Regards,
Michal

**Comment by morganzhh** [comment]
Thanks for replying, please forgive me I didn't explain the problem well, I was trying to, :)
I am using netopeer2+sysrepo+libnetconf to acting a Netconf network element server.

The xml is what sysrepo sent to libyang for validation, I was tying to minimum my yang file, in the xml, namespace prefix testa is actually defined.

The key for this issue I think is the 'when' statement:

`` `
when "count(../testa:who[normalize-space(test())='iamb']) >0" 
```

When libyang get the text with 'iamb', it's working ok, 'resolve_when' return true

```xml
<testa:who xmlns="http://www.test.com/b">iamb</testa:who>
```

if libyang get the text with namespace prefix, 'resolve_when' return false

I also did another test, that I modified the module b yang file

```yang
module b {
    namespace "http://www.test.com/b";
    prefix "testb";

    import a {prefix "testa"}

    identity iamb {
        base testa:whoami;
    }

    augment "/testa:test" {
        when "count(../testa:who[normalize-space(test())='testb:iamb']) >0" {
        }

        leaf second {
            type string;
        }
    }
}
```

the 'when' statement changes from

```yang
when "count(../testa:who[normalize-space(test())='iamb']) >0" {
        }
```

to

```yang
when "count(../testa:who[normalize-space(test())='testb:iamb']) >0" {
        }
```

After this change, working case is

```xml
<testa:who xmlns="http://www.test.com/b">iamb</testa:who>
```

Not working case is


`` `
when "count(../testa:who[normalize-space(test())='iamb']) >0" 
``


Thanks a lot.

**Comment by morganzhh** [comment]
Hi, I also raised an issue in Sysrepo, one of their developer think this is a libyang issue.
https://github.com/sysrepo/sysrepo/issues/636

Could you help, thanks.

**Comment by michalvasko** [comment]
Hi,
I hope I have fixed it, but well done for finding this bug, we would have never come up with such a use-case.

Regards,
Michal
