### ISSUE TITLE
How to retrieve the name of a lyd_value variable using libyang 2.1.148

### ISSUE THREAD

**Issue by omarreng** [CESNET/libyang#2234]
Hi,

In the latest version of libyang it seems that the field [`name`](https://github.com/CESNET/libyang/blob/4c733412e7173219166be7053940326a92699765/src/tree_schema.h#L1284) has been to the `lysc_type` struct. In version 2.1.148 it seems this field is not available.

My question is if there is any way to retrieve the value of this field in some other way using version 2.1.148?

Best regards

**Comment by michalvasko** [comment]
No, which is exactly the reason it has been added.
