### ISSUE TITLE
lyd_create_any change caused a bug

### ISSUE THREAD

**Issue by 455596331** [CESNET/libyang#2238]
The bug has been raised as an issue, the link is as follows:
https://github.com/CESNET/libyang/issues/2236
In versions 2.1.30 and 2.1.128, the overall process change of the lyd_create_any function resulted in the same input message and inconsistent output parameters of struct lyd_node **node.
After thinking about it for a while, what is the background of the change of lyd_create_any function?
Change time: April 13, 2023 16:29:58
The change record is shown below:
![image](https://github.com/CESNET/libyang/assets/170012473/24dd98ed-1aec-41ef-87fb-5cee67565d34)

**Comment by michalvasko** [comment]
Not sure it is worth it going into any explanations. In short, I believe this changed the behavior to something one would naturally always expect, to have all the `anyxml` nested data parsed as YANG data.
