### ISSUE TITLE
Leaf-list values are not kept in descending order

### ISSUE THREAD

**Issue by lorandt1** [CESNET/libyang#2243]
Hi, 

I  create an rpc for edit-config using : 
```
struct nc_rpc *rpc = nc_rpc_edit(NC_DATASTORE_RUNNING, NC_RPC_EDIT_DFLTOP_UNKNOWN,
        NC_RPC_EDIT_TESTOPT_UNKNOWN, NC_RPC_EDIT_ERROPT_UNKNOWN,
        xml.c_str(), NC_PARAMTYPE_CONST);
```

and send it using `nc_send_rpc`

After this the xml contains the accepted-clock-classes in descending order: 
```
<accepted-clock-classes>
	<clock-classes>3</clock-classes>
</accepted-clock-classes>
<accepted-clock-classes>
	<clock-classes>2</clock-classes>
</accepted-clock-classes>
<accepted-clock-classes>
	<clock-classes>1</clock-classes>
</accepted-clock-classes>
```

But the server receives the clock-classes in ascending order 
```
<accepted-clock-classes>
	<clock-classes>1</clock-classes>
</accepted-clock-classes>
<accepted-clock-classes>
	<clock-classes>2</clock-classes>
</accepted-clock-classes>
<accepted-clock-classes>
	<clock-classes>3</clock-classes>
</accepted-clock-classes>
```

Based on yang definition 
```
list accepted-clock-classes {
        key clock-classes;
        leaf clock-classes {
          type uint8;
          description
            "PTP Clock Class accepted by the O-RU";
        }
        description
          "Contains list of PTP acceptable Clock Classes, sorted in the descending order.";
      }
```

The values must be in descending order.
This is a serious regression for me compared to older libraries as the server might reject the configuration due to not keeping the desired order.
Could you please help me how can I preserve the message as it was initially set by client using the provided APIs ?

Thank you!

**Comment by jktjkt** [comment]
Is your model using the [`ordered-by: user`](https://datatracker.ietf.org/doc/html/rfc7950#section-7.7.7) statement?

**Comment by michalvasko** [comment]
Based on your YANG your list is not, in fact, ordered by user. So you relying on the previous order was incorrect and you need to change the list by adding `ordered-by user` and then the order will get meaning and be preserved.

**Comment by lorandt1** [comment]
I added `ordered-by user;` statement and it works. Thank you @jktjkt! and @michalvasko
