### ISSUE TITLE
Fraction digit statement implementation

### ISSUE THREAD

**Issue by lorandt1** [CESNET/libyang#2249]
Hi,

I have a leaf defined as 

```
leaf gain {
        type decimal64 {
          fraction-digits 4;

        }
        units dB;
        mandatory true;
        description
          "description.";
      }
```
 I want to send 0.0000 to comply to fraction-digits statement but it will get 0.0 after it goes through libyang.
 
 Why it can't remain 0.0000 ?

**Comment by jktjkt** [comment]
The RFC [says](https://datatracker.ietf.org/doc/html/rfc7950#section-9.3.2) that the current behavior is the correct canonical form. The `ftaction-digits` statement does *not* mean that the on-the-wire format in either XML or JSON should use that many trailing zeros.

**Comment by lorandt1** [comment]
clear, thanks @jktjkt
