### ISSUE TITLE
Enumeration with hexadecimal values

### ISSUE THREAD

**Issue by rbu9fe** [CESNET/libyang#2250]
The [RFC 7950](https://datatracker.ietf.org/doc/html/rfc7950#section-9.6.4.2) simply states that an enumeration's value argument must be an integer in the range -2147483648 to 2147483647. For integers a hexadecimal notation is defined in [section 9.2.1](https://datatracker.ietf.org/doc/html/rfc7950#section-9.2.1). However, libyang seems not to support hexadecimal values in enumerations.

Can you please confirm whether that should or should not be supported?

**Comment by jktjkt** [comment]
Your reference to integers' lexical representation refers to how integers are represented in YANG-encoded data (XML or JSON documents, mainly). However, the lexical representation of enums in YANG data is not a number, but a [string with the enumeration's value name](https://datatracker.ietf.org/doc/html/rfc7950#section-9.6.1).

Maybe you're referring to the YANG model itself and the [`enum`'s `value` statement](https://datatracker.ietf.org/doc/html/rfc7950#section-9.6.4.2)? In that case hexadecimal numbers are not allowed, either; just follow the ABNF grammar which goes from `enum-stmt` via `value-stmt`, `integer-value-str`, `integer-value`, `non-negative-integer-value`, and `positive-integer-value` to `DIGIT`, which is defined as ASCII characters `0` to `9`.

**Comment by rbu9fe** [comment]
Yes I was referring to the Yang model and not to the data. Thanks for the clarification!
