### ISSUE TITLE
Can yanglint parse type leafref?

### ISSUE THREAD

**Issue by xinghaiquedeng** [CESNET/libyang#2252]
I have a warning.
huawei-evpn.yang:libyang warn: Incompatible types of operands "address" and "es-track-address" for comparison.
huawei-evpn.yang:libyang warn: Previous warning generated by XPath subexpression[90] "bgp:address=current(" with context node "/huawei-ifm:ifm/interfaces/interface/huawei-evpn:evpn-attribute/track-peers/track-peer/es-track-address".

yang：
-----------------------------------
        list interface-track-peer {
          key "es-track-address";
          description "Configure track peer information.";
          leaf es-track-address {
            type leafref {
              path "/ni:network-instance/ni:instances/ni:instance/bgp:bgp/bgp:base-process/bgp:peers/bgp:peer/bgp:address";
            }
            must "/ni:network-instance/ni:instances/ni:instance/bgp:bgp/bgp:base-process/bgp:peers/bgp:peer[bgp:address=current()]/bgp:afs/bgp:af[bgp:type='evpn']";
            description
              "Track peer address.";
          }
        }
----------------------------

Because the type of es-track-address references address through the path of leafref, the types of es-track-address  and address are the same。
There should be no warning.

**Comment by michalvasko** [comment]
Any `leafref` types should be handled correctly so if the target types are exactly the same, you should definitely not see a warning. Could you post (all) the modules so that I can reproduce it with `yanglint`?

**Comment by xinghaiquedeng** [comment]
all modules：https://github.com/Huawei/yang/blob/1a069483f2ba7213aa4858f799220734ac3eb0f2/network-router/8.22.0/ne40e-x8x16/huawei-evpn.yang

**Comment by michalvasko** [comment]
Thanks, should be fixed.
