### ISSUE TITLE
"Invalidated" union can lead to crash.

### ISSUE THREAD

**Issue by snar** [CESNET/libyang#2254]
Standalone test case in attach (tested against `devel` 3.0.18), scenario: 
- union is initialized with leafref, 
- referenced leaf removed, 
- validation reports that there are errors, 
- referenced leaf restored, 
- next validation run crashes.

Root cause: union value can lose realtype during validation and as there are no checks if it is still here libyang can dereference NULL pointer. 
Crash in validation can be easily fixed by making call to plugin->free optional (if (subvalue->value.realtype) { ... }) [here](https://github.com/CESNET/libyang/blob/devel/src/plugins_types/union.c#L448), but it looks like it's not the only problem: commented out `lyd_print_fd` in attached case can crash too :(

[invalidated-union.c.gz](https://github.com/user-attachments/files/15817679/invalidated-union.c.gz)

**Comment by michalvasko** [comment]
You are right, should be fixed.
