### ISSUE TITLE
XPath: Empty string should be NaN, not zero

### ISSUE THREAD

**Issue by koalo** [CESNET/libyang#2256]
In my understanding of '4.4 Number functions' of XML Path Language (XPath) Version 1.0:

a string that consists of optional whitespace followed by an optional minus sign followed
by a Number followed by whitespace is converted to the IEEE 754 number that is nearest
(according to the IEEE 754 round-to-nearest rule) to the mathematical value represented
by the string; any other string is converted to NaN

I would expect that an empty string is converted to NaN.

Currently, libyang converts it into 0 (see https://github.com/CESNET/libyang/blob/4c733412e7173219166be7053940326a92699765/src/xpath.c#L692 which uses strtold that returns 0 without error for an empty string).

Do you agree or do I read the standard wrong again (as in https://github.com/CESNET/libyang/issues/2140 that is remotely related)?

**Comment by michalvasko** [comment]
Yep, I think you are right and it should be fixed.

**Comment by koalo** [comment]
That was quick! Works as expected now, thanks!
