### ISSUE TITLE
Incorrect timezone offset -09:-30 when setting timezone to Pacific/Marquesas

### ISSUE THREAD

**Issue by jaraj369** [CESNET/libyang#2258]
I am encountering an issue with libyang where setting the timezone to Pacific/Marquesas results in an incorrect timezone offset of -09: -30. In event notification we observer this error:  libyang[0]: Unsatisfied pattern - "2024-06-05T23:26:05.060889838-09:-30" does not conform to "\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[\+\-]\d{2}:\d{2}.
[Libyang_error_material.docx](https://github.com/user-attachments/files/15922739/Libyang_error_material.docx)

**Comment by michalvasko** [comment]
Thanks, fixed.
