### ISSUE TITLE
resolve_when_relink_nodes function deadloop

### ISSUE THREAD

**Issue by morganzhh** [CESNET/libyang#226]
Hi,

I got a deadloop when using libyang, the deadloop happened in 
resolve.c

``static int
resolve_when_relink_nodes(struct lyd_node *node, struct lyd_node *unlinked_nodes, enum lyxp_node_type ctx_node_type)``

If ``unlinked_nodes`` is more than one, in my case it has four nodes, deadloop happens, looking the code function ``lyd_insert`` already iterate all the ``unlinked_nodes`` and insert them all if the first(header) node passes as the parameter, so the rest of the ''unlinked_nodes'' inserting will break the list.  

I remove the for loop in function ``resolve_when_relink_nodes``, and everything works fine.

The code change I made:

```diff
diff --git a/src/resolve.c b/src/resolve.c
index 0c032d8..35c8efc 100644
--- a/src/resolve.c
+++ b/src/resolve.c
@@ -5661,20 +5661,17 @@ resolve_when_unlink_nodes(struct lys_node *snode, struct lyd_node **node, struct
 static int
 resolve_when_relink_nodes(struct lyd_node *node, struct lyd_node *unlinked_nodes, enum lyxp_node_type ctx_node_type)
 {
-    struct lyd_node *elem;
+    struct lyd_node *elem = unlinked_nodes;
 
-    LY_TREE_FOR_SAFE(unlinked_nodes, unlinked_nodes, elem) {
-        if (ctx_node_type == LYXP_NODE_ELEM) {
-            if (lyd_insert(node, elem)) {
-                return -1;
-            }
-        } else {
-            if (lyd_insert_after(node, elem)) {
-                return -1;
-            }
+    if (ctx_node_type == LYXP_NODE_ELEM) {
+        if (lyd_insert(node, elem)) {
+            return -1;
+        }
+    } else {
+        if (lyd_insert_after(node, elem)) {
+            return -1;
         }
     }
-
     return EXIT_SUCCESS;
 }
 
@@ -7036,8 +7033,6 @@ resolve_unres_data(struct unres_data *unres, struct lyd_node **root, int options
                     unres->node[i] = parent;
 
                     /* auto-delete */
-                    LOGVRB("auto-delete node \"%s\" due to when condition (%s)", ly_errpath(),
-                                    ((struct lys_node_leaf *)unres->node[i]->schema)->when->cond);
                     if (*root && *root == unres->node[i]) {
                         *root = (*root)->next;
                     }
```

The second change above is because I hit a NULL pointer issue upon that logging, don't know why.

I raise this issue other than a pull request is because I haven't been fully understand the libyang code, that my changes might not be the better or even a right one, if not, please forgive me, :)

Thanks.
Morgan

**Comment by michalvasko** [comment]
Hi Morgan,

I committed what should be a fix for your first problem. Try it, without your modifications, and if the NULL pointer issue still occurs, please provide the module and data for me to reproduce the issue and fix it properly.

Regards,
Michal

**Comment by morganzhh** [comment]
Thanks for the fix, it's working, and NULL pointer issue is also gone.
