### ISSUE TITLE
yanglint tests fail for release build

### ISSUE THREAD

**Issue by labuwx** [CESNET/libyang#2264]
Hi,

Some tests in yanglint_interactive fail when are run on a release build.
The tests in `tests/yanglint/interactive/debug.test` are only meant to be run on a debug build but the [yanglint_debug](https://github.com/CESNET/libyang/blob/fba28260f382d81cf8f4b91b24cd717b52324fc2/tests/yanglint/interactive/ly.tcl#L71C6-L71C20) check in `tests/yanglint/interactive/ly.tcl` does not do its job since commit 34e2a55.
`yanglint_debug` looks for `--debug=` in the output of `yanglint -h`. However since 34e2a55, that string appears in release builds too.

**Comment by michalvasko** [comment]
Right, the test seems useless anyway, removed.
