### ISSUE TITLE
Substatements on extension instances

### ISSUE THREAD

**Issue by aronbergurj99** [CESNET/libyang#2265]
Is it possible to get the substatements on compiled extension instance.
For example on the list below i would like to be able to get the cli-display-joined statement under the cli-allow-join-with-key. However it seems that the exts on cli-allow-join-with-key is null. 
```yang    
    container interface {
        list HundredGigE {
            tailf:cli-allow-join-with-key {
                tailf:cli-display-joined;
            }
            key name;
            leaf name {
                type string;
                
            }
           
        }
    }
```

**Comment by michalvasko** [comment]
Right, this was most likely intentional but it could be improved and nested extensions should now be parsed.
