### ISSUE TITLE
How to parse the fellow xml with "lyd_parse_op" correctly?

### ISSUE THREAD

**Issue by NextLitete** [CESNET/libyang#2267]
How to parse the fellow xml with "lyd_parse_op" API correctly?

```
<?xml version="1.0" encoding="UTF-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1720076409907">
  <get-config>
    <source>
      <running />
    </source>
    <filter type="subtree">
      <list_two xmlns="urn:ietf:params:xml:ns:yang:netconf_sample">
        <type_uint8>0</type_uint8>
      </list_two>
      <list_two>
        <type_uint8>1</type_uint8>
      </list_two>
    </filter>
  </get-config>
</rpc>
```

This is how I use it. The parsed filter node has only one instance of list_two.
`lyd_parse_op(ctx, nullptr, in, LYD_XML, LYD_TYPE_RPC_NETCONF, &tree, &ntf)`

"ntf" result：
```
<get-config
    xmlns=\"urn:ietf:params:xml:ns:netconf:base:1.0\">
    <source>
        <running/>
    </source>
    <filter type=\"subtree\">
        <list_two
            xmlns=\"urn:ietf:params:xml:ns:yang:netconf_sample\">
            <type_uint8>0</type_uint8>
        </list_two>
    </filter>
</get-config>
```

libyang version:2.1.128

please, help!

**Comment by jktjkt** [comment]
There's no `xmlns` for the second `<list_two>`, and therefore from the YANG perspective it refers to a "completely different" node. Strange that you do not get any error because this function is supposed to use `PYD_PARSE_STRICT`.

**Comment by NextLitete** [comment]
How obvious! I didn't notice it. Thanks!
