### ISSUE TITLE
Parse rpc lyd_node and get operation , container with corresponding Leafs

### ISSUE THREAD

**Issue by afzalap** [CESNET/libyang#2274]
HI, i want to get the operation getconfig/editconfig and containers with corresponding leaf nodes from rpc lyd_node.
<get-config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <source>
    <startup/>
  </source>
  <filter type="subtree">
    <device xmlns="urn:onf:params:xml:ns:yang:tr-181-2-6-0-full">
      <device.device-info>
        <manufacturer/>
        <model-name/>
      </device.device-info>
      <device.device-info.process-status>
        <cpu-usage/>
      </device.device-info.process-status>
    </device>
  </filter>
</get-config>
like here i want to get that it is a getconfig operation trying to get values of manufactures, model-name and cpu-usage

**Comment by michalvasko** [comment]
So what is your question, how to traverse a tree of `struct lyd_node`? Those are all public structures, you should do that manually, look at `node->schema->name` for the node name, `node->schema->nodetype` for the node type and, where applicable, `lyd_get_value(node)` to get the value of a leaf or leaf-list.

**Comment by afzalap** [comment]
yes, i am trying void traverse_rpc(struct lyd_node *rpc) {
   struct lyd_node *child = NULL;

    // Print the name of the current node
    printf("Node name: %s\n", rpc->schema->name);

    // If the current node has children, traverse them
    LY_LIST_FOR(lyd_child(rpc), child) {
        traverse_rpc(child);
    }
}  like this and able to get :
Node name: get-config
Node name: source
Node name: startup
Node name: filter
but it is not traversing   this part 
<device xmlns="urn:onf:params:xml:ns:yang:tr-181-2-6-0-full">
      <device.device-info>
        <manufacturer/>
        <model-name/>
      </device.device-info>
      <device.device-info.process-status>
        <cpu-usage/>
      </device.device-info.process-status>
    </device>
  </filter>
</get-config>

**Comment by michalvasko** [comment]
Instead of the recursion, you can just use `LYD_TREE_DFS_BEGIN`/`END` macros. When you get to the `data` node, you need to cast it to `struct lyd_node_any` and access its `node->value.tree` member. That is another data tree with the nodes you are missing.

**Comment by afzalap** [comment]
![Screenshot 2024-07-30 164954](https://github.com/user-attachments/assets/1955efe4-7edd-44fe-96ac-cd4f79deadd9)

after device node it is not traversing

**Comment by afzalap** [comment]
LYD_TREE_DFS_BEGIN(node, iter) {
        // Print node details
        printf("Node Start\n");
        printf("  Node Name: %s\n", LYD_NAME(iter));
        printf("  Hash: %u\n", iter->hash);
        printf("  Flags: %u\n", iter->flags);

        // Print schema node details if available
        snode = iter->schema;
        if (snode) {
            printf("  Schema Node Name: %s\n", snode->name);
            printf("  Schema Node Module: %s\n", snode->module->name);
            printf("  Schema Node Type: %u\n", snode->nodetype);
        } else {
            printf("  Schema Node: (null)\n");
        }

        // Print parent node, next sibling, and previous sibling
        printf("  Parent Node: %s\n", iter->parent ? LYD_NAME(iter->parent) : "(root)");
        printf("  Next Sibling Node: %s\n", iter->next ? LYD_NAME(iter->next) : "(none)");
        printf("  Previous Sibling Node: %s\n", iter->prev ? LYD_NAME(iter->prev) : "(self)");
        printf("  Private Data: %p\n", iter->priv);

        // Print node value if applicable
        const char *value = lyd_get_value(iter);
        if (value && *value) {
            printf("  Value: %s\n", value);
        } else {
            printf("  Value: (none)\n");
        }

        // Print metadata if available
        if (iter->meta) {
            printf("  Metadata:\n");
            LY_LIST_FOR(iter->meta, meta) {
                printf("    %s = \"%s\"\n", meta->name, lyd_get_meta_value(meta));
            }
        } else {
            printf("  Metadata: (none)\n");
        }

        // Traverse child nodes if any
        LYD_TREE_DFS_END(node, iter);
        printf("Node End\n");

so in this my iter should be of struct lyd_node_any type??

**Comment by michalvasko** [comment]
Just add somewhere
```C
struct lyd_node_any *any;

if (snode->nodetype & LYD_NODE_ANY) {
    any = (struct lyd_node_any *)iter;
    LYD_TREE_DFS_BEGIN(any->value.tree, iter2) {
        ...
        LYD_TREE_DFS_END(any->value.tree, iter2);
    }
}
```

**Comment by afzalap** [comment]
Thank you,  this helped and printing first container and its leafs but problem with last leaf node
if (snode->nodetype & LYD_NODE_ANY) {
    const struct lyd_node *iter2;
    LYD_TREE_DFS_BEGIN(any->value.tree, iter2) {
        if (iter2 == NULL) {
            printf("Error: 'iter2' is null.\n");
            return;
        }
        if (iter2->schema == NULL) {
            printf("Error: 'iter2->schema' is null.\n");
            return;
        }
        if (iter2->schema->name == NULL) {
            printf("Error: 'iter2->schema->name' is null.\n");
            return;
        }
        printf("  Schema Node Name: %s\n", iter2->schema->name);
        LYD_TREE_DFS_END(any->value.tree, iter2);
    }
}
  Schema Node Name: device
  Schema Node Name: device.device-info
  Schema Node Name: manufacturer
  Schema Node Name: model-name
  Schema Node Name: device.device-info.process-status
Error: 'iter2->schema' is null.

**Comment by michalvasko** [comment]
Based on that the last leaf is not valid, which is why its `schema` is `NULL`. Actually, just use `LYD_NAME(iter2)` instead of `iter2->schema->name` and you will get all the node names.

**Comment by afzalap** [comment]
Thank you, great help Thanks a lot :)
