### ISSUE TITLE
List "parent-reference" with duplicate instances allowed found without required metadata

### ISSUE THREAD

**Issue by msuryarao2011** [CESNET/libyang#2279]
> edit-config  --target candidate --config=/root/package//mount-schema-2.xml
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  List "parent-reference" with duplicate instances allowed found without required metadata.

        type:     application
        tag:      operation-failed
        severity: error
        message:  User callback failed.

><schema-mounts xmlns="urn:ietf:params:xml:ns:yang:ietf-yang-schema-mount">
    <namespace>
      <prefix>_3gpp-common-subnetwork</prefix>
      <uri>urn:3gpp:sa5:_3gpp-common-subnetwork</uri>
    </namespace>
    <mount-point>
      <module>_3gpp-common-subnetwork</module>
      <label>children-of-SubNetwork</label>
      <config>true</config>
      <inline></inline>
      <shared-schema>
        <parent-reference>/_3gpp-common-subnetwork:SubNetwork</parent-reference>
      </shared-schema>
    </mount-point>
  </schema-mounts>

**Comment by jktjkt** [comment]
This bugreport doesn't include all the required information to see what exactly you're doing. Are you perhaps trying to send a NETCONF-level `edit-config` operation where you're setting some [state data](https://datatracker.ietf.org/doc/html/rfc7950#section-4.2.3)? That cannot work.

**Comment by msuryarao2011** [comment]
Hi , Yes i am trying to do something like this which is mentioned in the below ticket .https://github.com/sysrepo/sysrepo/issues/2842

**Comment by jktjkt** [comment]
This issue looks like a duplicate of #2277.

A bugreport needs much more information than a rather vague phrase "something like this". Let's continue this discussion in a single bugreport, and please provide all the information that's needed to reproduce the problem.

**Comment by msuryarao2011** [comment]
Thank you will provide the info in the other #https://github.com/CESNET/libyang/issues/2277.
