### ISSUE TITLE
After issue #223, cast_string_recursive assertion failed

### ISSUE THREAD

**Issue by morganzhh** [CESNET/libyang#228]
After applying the fix for https://github.com/CESNET/libyang/issues/223

I got another issue:

``assertion failed: value_str[strlen(lyd_node_module(node)->name)] == ':' (/3rd/external/libyang/src/xpath.c: cast_string_recursive: 395)``

I believe it's because the node's namespace is not the same as the values

``<testa:who xmlns:testb="http://www.test.com/b">testb:iamb</testa:who>``

Thanks.
Morgan

**Comment by morganzhh** [comment]
Forgot to mention, I used ``devel`` branch

**Comment by michalvasko** [comment]
Hi,
this was actually a separate bug and is fixed now (I just referenced a wrong issue and noticed it after push).

Regards,
Michal
