### ISSUE TITLE
The text in readme.md about libpcre2 seems to need an update

### ISSUE THREAD

**Issue by capiman** [CESNET/libyang#2282]
"libpcre2 >= 10.21 (including devel package)

    note, that PCRE is supposed to be compiled with unicode support (configure's options --enable-utf and --enable-unicode-properties)
"

See here:
https://github.com/PCRE2Project/pcre2/issues/436#issuecomment-2269467133

Perhaps note is obsolete at all and was only relevant for PCRE, but never for PCRE2?

**Comment by michalvasko** [comment]
Seems you are right, thanks, fixed.
