### ISSUE TITLE
Help on building rpm package

### ISSUE THREAD

**Issue by srikanths1** [CESNET/libyang#2283]
Hi, 

can anybody share the procedure to build rpm after we compile libyang? looking for a sample example for apkg template.

Thanks,
Srikanth

**Comment by michalvasko** [comment]
What more instructions do you need than what is in the [README](https://github.com/CESNET/libyang/tree/master/distro)? Using a full sentence, just download `apkg` using `pip` and then run `apkg build`, that will create the packages.
