### ISSUE TITLE
Help required new custom extension yang is not getting listed during capability exchange

### ISSUE THREAD

**Issue by msuryarao2011** [CESNET/libyang#2284]
Hi ,

1. custom extension yang defined and libyang built with the new yang and extension plugin  and loaded in sysrepo using sysrepoctl -l <custom>.yang 
2. yang is list in the sysrepoctl -list
3. netopeer server started , connected client using netopeer-cli .
4. In capabilities exchange the new yang was not listed hence not able to use the same .

I have rebuilt libyang , sysrepo, netopeer-server2 ,libnetconf2

drwxr-xr-x 12 root root     4096 Jul 31 13:22 libnetconf2-3.3.3
drwxr-xr-x 13 root root     4096 Jul 31 13:24 sysrepo-2.10.1
drwxr-xr-x 17 root root     4096 Jul 31 13:25 netopeer2-2.2.28
drwxr-xr-x 13 root root     4096 Aug  8 22:07 libyang-3.1.0

This is similar to structure extension defined as mentioned below .

I believe netopeer-server should automatically get sync from sysrepo . If sysrepo shows the yang module loaded and listed it should be listed in the capability exchange as well. Is there any seperate option in netopeer-server2 to specify the custom extension yang loading ??

If yang model is loaded in sysrepo i assume it is proper yang 
If custom extension code was compiled and libyang was built with yang model without error then i assume yang model is not having any issues .

Any clue , please let me know what else i can check 
Can you please suggest how to i make sure that this yang gets listed in the capability exchange 
 
module example-classtype {
  yang-version 1.1;
  namespace "urn:3gpp:sa5:example-classtype";
  prefix classmnt;
   revision 2024-08-08 {
    description
      "Initial revision.";
    reference
      "YANG Data Structure Extensions.";
  }
  extension classtype {
    argument classtypevalue {
    yin-element true;
      }
    description
      "The argument can take values ";
    }

  }

**Comment by jktjkt** [comment]
YANG 1.1 modules are not listed in the NETCONF server capabilities (that's a difference from YANG 1.0). Also, YANG extensions are not listed in there, either (and have never been IIRC). Finally, depending on what exactly your extension is doing, you might need to implement a [libyang plugin](https://netopeer.liberouter.org/doc/libyang/master/html/howto_plugins_extensions.html) for that.

**Comment by msuryarao2011** [comment]
Thanks a lot for your support
