### ISSUE TITLE
Question about issue #223

### ISSUE THREAD

**Issue by morganzhh** [CESNET/libyang#229]
After the latest change https://github.com/CESNET/libyang/commit/96c3e9e1e0153e2c7ec0db2bf4ffda3aecefa91a

I test our yang file which list in issue #223, now things change a little different.

If I define the 'when' statement with namespace prefix

```yang
when "count(../testa:who[normalize-space(test())='testb:iamb']) >0" {
        }
```

Everything works fine, both xmls below are working as expect, ``when`` validation passed

```xml
<testa:who xmlns:testb="http://www.test.com/b">testb:iamb</testa:who>
```

and

```xml
<testa:who xmlns="http://www.test.com/b">iamb</testa:who>
```

However if I remove the namespace prefix from the yang file:

```yang
when "count(../testa:who[normalize-space(test())='iamb']) >0" {
        }
```

Now, both XMLs above are not working, ``when`` validation return false.

My question is, should I use namespace prefix in the ``when`` or not? Because all my yang files come from 3rd party, if Libyang doesn't support ``when`` without namespace prefix, I have to push them to change the yang file.

Thanks for the quick fix~

Morgan

**Comment by michalvasko** [comment]
Hi,
just letting you know I am working on it, but it is a very specific use-case and I need to modify several things in order to fix it, so expect the fix at the beginning of next year.

Regards,
Michal

**Comment by morganzhh** [comment]
Ok, thanks.

**Comment by morganzhh** [comment]
Hi,

Is this issue solved, just notice it's been closed.

thanks,
Morgan.

**Comment by michalvasko** [comment]
Hi Morgan,
yes, it should be solved.

Regards,
Michal
