### ISSUE TITLE
query on yang

### ISSUE THREAD

**Issue by kr234** [CESNET/libyang#2292]
Hi Team,

There is one grouping defined in o-ran-uplane-conf.yang(uplane-conf-group) which has some  list types defined.(low-level-tx-links,low-level-rx-links)
I need to import this yang and want to use only 2 lists in the grouping(uplane-conf-group). Is there any way to cherry-pick the needed list from grouping.
Attached the grouping yang file..Pls help with this query.
grouping uplane-conf-group {
description
"Grouping for uplane configuration related parameters";

list low-level-tx-links {
[o-ran-uplane-conf.zip](https://github.com/user-attachments/files/16705588/o-ran-uplane-conf.zip)

**Comment by michalvasko** [comment]
No, you cannot select only some of the nodes in a grouping, you must use it as a whole. You could then only deviate the nodes you do not want to use with `not-supported` deviation but that is not a particularly good solution.

**Comment by kr234** [comment]
Thanks Michal..
