### ISSUE TITLE
32bit issue when casting

### ISSUE THREAD

**Issue by awesomenode** [CESNET/libyang#2293]
Hi!

When I used sysrepoctl on a 32bit machine using the latest libyang, it caused a segfault.
The backtrace pointed to libyang `plugic_exts.c:104`. A problematic part involving down an upcasting an integer containing a pointer.
My guess is, this part fails on 32bit, because `void*` is not 64 bit sized, and the casting changed the pointer value.

Changing `uint64_t` to `unsigned long` in the relevant parts (like the `storage` member in `struct lysp_ext_substmt`) might've fixed the issue.

It seems like 53eb6a1a58 is the commit that introduced this issue.

**Comment by michalvasko** [comment]
I do not think it can simple be changed to be smaller on 32b platforms, there are cases where there is actually a 64b value (number) stored. So I think I will need to reproduce this or you can attempt a fix yourself.

**Comment by michalvasko** [comment]
Actually, I have reproduced some issues on a 32b platform, which should be fixed now. Please check whether it solved this problem as well.

**Comment by awesomenode** [comment]
It's working now properly, thanks!
