### ISSUE TITLE
XML snippets with yanglint

### ISSUE THREAD

**Issue by CC-vga** [CESNET/libyang#2295]
Hi, 

It might be a stupid question, but how can I use XML snippets with yanglint?
I’m using yanglint version 3.1.0 and from the manual I couldn’t figure out how to validate an xML  snippet instead of an XML file.

All best
Voica

**Comment by michalvasko** [comment]
What is an XML snippet and what exactly should be validated assuming it is missing some parts that would make it fully valid?

**Comment by CC-vga** [comment]
Hi, 

An XML snippet is a string containing the content of the XML file and I would need to validate such string against some yang schemas. In other words, there is any option to input the XML as a string when trying to validating an XML against a YANG model?

All best
Voica

**Comment by CC-vga** [comment]
So there is no such option...? I have a context when I would need to do not save in memory all XMLs :) 

Thank you for the quick reaction
Voica

**Comment by michalvasko** [comment]
Okay, you should have made it clear what you want, `yanglint` to load XMLs from memory instead of files. But this does not make sense, how would you pass these data to `yanglint`, another process? Why don't you just use *libyang* for parsing the XMLs?

**Comment by CC-vga** [comment]
Hi,

I'm sorry, but libyang is not part of my workflow! Thank you for your time and suggestions :)

Keep-up the good work
Voica
