### ISSUE TITLE
A query regarding the test case test_lyd_new_path

### ISSUE THREAD

**Issue by fushion2018** [CESNET/libyang#2300]
Hello,
I have a question regarding the test case _`static void test_lyd_new_path(void **state)`_
The code snippet is as follows:

**node** = lyd_new_path(root, NULL, "/a:l[key1='11'][key2='22']/value", "val", 0, 0);
assert_non_null(node);
assert_ptr_not_equal(root->prev, root);
assert_string_equal(node->schema->name, "l");
assert_string_equal(node->child->schema->name, "key1");
assert_string_equal(node->child->next->schema->name, "key2");
assert_string_equal(node->child->next->next->schema->name, "value");

**node** = lyd_new_path(root, NULL, "/a:l[key1='1'][key2='2']/value", "val2", 0, 0);
assert_non_null(node);
assert_string_equal(node->schema->name, "value");

Why are not both **node** pointing to value?  Could you please help me with it? Thank you.

**Comment by michalvasko** [comment]
It seems you are referring to a really old version of *libyang* but I guess the return value was the **first** created node (should be documented).  So I would assume `/a:l[key1='1'][key2='2']` already existed in the `root` data tree before calling `lyd_new_path()`.

**Comment by fushion2018** [comment]
Indeed, as you mentioned, /a:l[key1='1'][key2='2'] already existed since it was created earlier. The log you pasted is incomplete.
I understand now, thank you!
