### ISSUE TITLE
Checking regex on value in lyd_find_path

### ISSUE THREAD

**Issue by srikanthsubbaramu** [CESNET/libyang#2305]
Hi Michal,

i do see for issue #466, we can have match on xpath with /xpath[.='value'] for matching any key with expected value, is there something similar to do for value, i know the key , but i want to check if we have match for key with any values. 
like 
lyd_find_path(root, "/xpath[id='.*'],0,&lyd_node);

Thanks,
Srikanth

**Comment by srikanthsubbaramu** [comment]
in my sr_rpc_subscribe_tree for /ietf-netconf:edit-config for candidate datastore, i have below code with log
Code
    snprintf(l_str_ver_ranid,256,"/test:/Data[id=.]");
    printf(" CMAGENTDEBUG: checking for managed element %s\n",l_str_ver_ranid);
    struct ly_set *l_ly_set = NULL;
    lyd_print_file(stdout, l_lyd_node_tree1, LYD_XML, LYD_PRINT_WITHSIBLINGS);
    LY_ERR l_ly_err;
    if( ! lyd_find_xpath(l_lyd_node_tree1,l_str_ver_ranid,&l_ly_set) )
    {
        if( l_ly_set != NULL )
          printf("ly_set is set\n");
        else
          printf("ly_set is NULL\n");
        l_bool_me_present = true;
        printf("setting l_bool_me_present to true");
    }
    else
    {
        l_bool_me_present = false;
        printf("setting l_bool_me_present to false");
        return SR_ERR_OK;
    }
Log
 CMAGENTDEBUG: checking for testdata /test:Data[id=.]
<day1 xmlns="urn:cAgent">
  <available>true</available>
</day1>


But somehow the lyd_find_xpath always returns success instead of failure, although the input lyd_node does not have this xpath, can you please point what is mistake i have done, basically i need to detect presence of xpath matching any value for key  on input, and if false , i just need to skip validation logic

**Comment by michalvasko** [comment]
The function `lyd_find_xpath()` returns success even if no nodes are found, only the resulting set is empty. Also, you can use regular expressions in XPaths, look at [`re-match`](https://www.rfc-editor.org/rfc/rfc7950.html#section-10.2.1).

**Comment by srikanthsubbaramu** [comment]
> The function `lyd_find_xpath()` returns success even if no nodes are found, only the resulting set is empty. Also, you can use regular expressions in XPaths, look at [`re-match`](https://www.rfc-editor.org/rfc/rfc7950.html#section-10.2.1).

Thank you michal, this is what i was looking for
