### ISSUE TITLE
Building and installing on macos Sequoia.

### ISSUE THREAD

**Issue by samans** [CESNET/libyang#2308]
I looked through the closed issues and tried several things there and also several hours worth of googling, but I still can't run yanglint.

I'm running Sequoia on an intel based mac, using zsh.
I cloned the repository, did the building thing, everything builds.
When I run yanglint...

I get:
% yanglint --version
dyld[35022]: Library not loaded: @rpath/libyang.3.dylib
  Referenced from: <3B24442F-38C6-3AB9-A4A0-C9C0CFDD7861> /usr/local/bin/yanglint
  Reason: no LC_RPATH's found
zsh: abort      yanglint --version

Any suggestions to how to get the RPATH set correctly?

thanks!

**Comment by michalvasko** [comment]
I cannot help you with that as I am not using MacOS at all.

**Comment by samans** [comment]
> I cannot help you with that as I am not using MacOS at all.

Ok, hopefully someone can.  If not I'll go back to parallels on the mac where it works fine on native ubuntu.  Advice appreciated.
thanks!

**Comment by samans** [comment]
I gave up trying to fix the CMake to find the dynamic libraries and just did this...

install_name_tool -add_rpath /usr/local/lib /usr/local/bin/yanglint

Things seem to be working now with yanglint version 3.4.2.

If there are others that have a better macos process, please let me know!

thanks!
