### ISSUE TITLE
Message parsing fails entirely when unknown element is present

### ISSUE THREAD

**Issue by lorandt1** [CESNET/libyang#2311]
Hi, 

Using libnetconf2 v3.0.17 and libyang v2.2.8:

Following notification is received:
```
<notification
	xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0">
	<eventTime>2024-10-10T13:44:00.848499Z</eventTime>
	<measurement-result-stats
		xmlns="urn:o-ran:performance-management:1.0">
		<epe-statistics>
			<measurement-object>TEMPERATURE</measurement-object>
			<start-time>2024-10-10T19:13:00+05:30</start-time>
			<end-time>2024-10-10T19:14:00+05:30</end-time>
			<epe-measurement-result>
				<object-unit-id
					xmlns:o-ran-hw="urn:o-ran:hardware:1.0">o-ran-hw:O-RAN-RADIO
				</object-unit-id>
				<min>52.4</min>
				<max>54.8</max>
				<average>53.6</average>
			</epe-measurement-result>
			<epe-measurement-resultv2>
				<object-unit-id>N75N3N1-G-RU</object-unit-id>
				<min>52.4</min>
				<max>54.8</max>
				<average>53.6</average>
			</epe-measurement-resultv2>
		</epe-statistics>
		<epe-statistics>
			<measurement-object>POWER</measurement-object>
			<start-time>2024-10-10T19:13:00+05:30</start-time>
			<end-time>2024-10-10T19:14:00+05:30</end-time>
			<epe-measurement-result>
				<object-unit-id
					xmlns:o-ran-hw="urn:o-ran:hardware:1.0">o-ran-hw:O-RAN-RADIO
				</object-unit-id>
				<min>249.49</min>
				<max>249.49</max>
				<average>249.49</average>
			</epe-measurement-result>
			<epe-measurement-resultv2>
				<object-unit-id>N75N3N1-G-RU</object-unit-id>
				<min>249.49</min>
				<max>249.49</max>
				<average>249.49</average>
			</epe-measurement-resultv2>
		</epe-statistics>
		<epe-statistics>
			<measurement-object>VOLTAGE</measurement-object>
			<start-time>2024-10-10T19:13:00+05:30</start-time>
			<end-time>2024-10-10T19:14:00+05:30</end-time>
			<epe-measurement-result>
				<object-unit-id
					xmlns:o-ran-hw="urn:o-ran:hardware:1.0">o-ran-hw:O-RAN-RADIO
				</object-unit-id>
				<min>52.97</min>
				<max>52.97</max>
				<average>52.97</average>
			</epe-measurement-result>
			<epe-measurement-resultv2>
				<object-unit-id>N75N3N1-G-RU</object-unit-id>
				<min>52.97</min>
				<max>52.97</max>
				<average>52.97</average>
			</epe-measurement-resultv2>
		</epe-statistics>
		<epe-statistics>
			<measurement-object>CURRENT</measurement-object>
			<start-time>2024-10-10T19:13:00+05:30</start-time>
			<end-time>2024-10-10T19:14:00+05:30</end-time>
			<epe-measurement-result>
				<object-unit-id
					xmlns:o-ran-hw="urn:o-ran:hardware:1.0">o-ran-hw:O-RAN-RADIO
				</object-unit-id>
				<min>4.71</min>
				<max>4.71</max>
				<average>4.71</average>
			</epe-measurement-result>
			<epe-measurement-resultv2>
				<object-unit-id>N75N3N1-G-RU</object-unit-id>
				<min>4.71</min>
				<max>4.71</max>
				<average>4.71</average>
			</epe-measurement-resultv2>
		</epe-statistics>
	</measurement-result-stats>
</notification>
```
Entire message won't be parsed due to **epe-measurement-resultv2**
```
ly_print_clb(): ly ERR: Node "epe-measurement-resultv2" not found as a child of "epe-statistics" node.(/o-ran-performance-management:measurement-result-stats/epe-statistics[measurement-object='POWER'])
lnc2_print_clb(): [127.0.0.1] nc ERR: Received an invalid message (Node "epe-measurement-resultv2" not found as a child of "epe-statistics" node.).

```

Based on 
[yangFile.zip](https://github.com/user-attachments/files/17361007/yangFile.zip)

only `epe-measurement-result` is defined.

1. Why not only the unknown part of the message is ignored (epe-measurement-resultv2) and the remainder valid part parsed ? 
2. Is there any existing NETCONF RFC spec that defines what should happen in such case ?

**Comment by michalvasko** [comment]
1. Actually, if the server reports implementing a module that the client fails to load for some reason, it still should be able to parse data for which it does have the correct YANG modules. Otherwise there is no reason for the server to send any data unknown to the client so why should this be ignored?
2. Not that I know of, but there is a [list of NETCONF errors](https://datatracker.ietf.org/doc/html/rfc6241#appendix-A), which includes `unknown-element` implying this is, in fact, an error.

**Comment by lorandt1** [comment]
Hi, 

In O-RAN where we use N/Y there's requirement for NETCONF client to ignore the unknown schema nodes but still use the valid part of the message that's according to its version of yang module.
As stated in the O-RAN specification:

> "The O-RU Controller can continue to use its current module version and any unknown schema nodes
> and/or unknown notifications
> received from the O-RU, i.e. those introduced in later revisions, should be ignored by the O-RU Controller."

NETCONF server doesn't know the client has an older version of a certain module that's what happens also in our case.

I will attempt modifying the library to comply to O-RAN spec.
Do you have any suggestion for it, can this be safely done ?

**Comment by michalvasko** [comment]
Then it goes against the YANG/NETCONF spec and you are, of course, free to make modifications as you see fit but we will not support this. In NETCONF, when the session is being established, the server communicates all the capabilities (or, in YANG 1.1 the client requests `yang-library` data) for the client to discover what YANG modules and in what revisions the server implements. Based on that the client is supposed to use the exact same set of YANG modules and hence receive no unknown data. So yes, the server does not know nor does it care that the client is using different YANG modules, it is not supposed to.

But like I said, this is supported for cases when the client, despite attempting to, fails to load some server YANG modules. There is a [flag](https://github.com/CESNET/libnetconf2/blob/master/src/session_client.c#L1139) set and then the client ignores received unknown data.

**Comment by michalvasko** [comment]
Okay, I have looked at it more and you are right, the *libnetconf2* flag currently does not do anything, that is a problem (that I will solve later). So the simplest change you can do is remove `LYD_PARSE_STRICT` from [here](https://github.com/CESNET/libyang/blob/master/src/tree_data.c#L313).

**Comment by lorandt1** [comment]
It works with that too. Thank you!
