### ISSUE TITLE
RPC validation error when leafref refer to a typedef profile name in Action, and such reference can pass validation in configuration. 

### ISSUE THREAD

**Issue by vcm-eric** [CESNET/libyang#2323]
RPC validation error when leafref refer to a typedef profile name in Action, such reference can pass validation in configuration. following is the YANG tree and RPC request, can someone shed some light on this issue? 

libyang version:  2.1.80
sysrepo version:  2.2.73
netopeer2 version:  2.1.62

Error message:
`Nov 12 16:27:58  netopeer2-server[364]: Invalid leafref value "p-1" - no target instance "/bbf-xpon:xpon/lref-1:test-profiles/lref-1:test-profile/lref-1:name" with the same value. (Data location "/ietf-interfaces:interfaces/interface[name='ct.1']/bbf-xpon:channel-termination/lref-1:test-b/profile".)
Nov 12 16:27:58  netopeer2-server[364]: Action input validation failed.
Nov 12 16:27:58  netopeer2-server[364]: Failed to send an RPC (Validation failed).

All RPC requests:
[leafref.txt](https://github.com/user-attachments/files/17714589/leafref.txt)

**Comment by michalvasko** [comment]
Could you please provide all the relevant YANG modules and the data so that I can actually reproduce it? But my guess is that if valid, it has been fixed in later versions.

**Comment by michalvasko** [comment]
Not sure why I have not realized before, but RPCs are always validated against the operational datastore, not running (based on the NMDA specs). So just make sure those data appear in the [operational DS](https://netopeer.liberouter.org/doc/sysrepo/devel/html/index.html#oper_ds) and the validation should pass.

**Comment by vcm-eric** [comment]
Yes, the validation can pass if refer typedef profile in operational datastore (refer to bbf-xpon wavelength profile in my experiment). Further question, how to make the test-profile in lref-1.yang existing in both running datastore and operational datastore? seems no difference from YANG definition with other profiles in both datastore, make this happen from application level?

**Comment by michalvasko** [comment]
Please look at the page I referenced in my previous post. I do not want to repeat everything written in sysrepo documentation.

**Comment by vcm-eric** [comment]
From sysrepo introduction for operational ds:
By default, this datastore is empty. From user perspective, this is how data becomes a part of this datastore:

- any subscribed running data (in-use concept) will appear in operational datastore;
- any [operational data](https://netopeer.liberouter.org/doc/sysrepo/devel/html/index.html#oper_data).
Note that all notification and RPC/action invocations are validated against this datastore.
