### ISSUE TITLE
leaf-list allows non unique entries when set as input parameter to RPC

### ISSUE THREAD

**Issue by mattiaswal** [CESNET/libyang#2327]
sysrepo-2.11.7
libyang-3.4.2

I have this RPC:
<pre>
  rpc set-boot-order {
    nacm:default-deny-all;
    description
      "Set order of boot-partions";
    input {
      leaf-list parameters {
        type string;

        ordered-by user;
        min-elements 1; 
        max-elements 3;
      }
    }
</pre>
but when calling the RPC from sysrepo:
<pre>
admin@ix-00-00-00:~$ sysrepocfg -f json -R
{
  "infix-system:set-boot-order": {
      "parameters": [ 
        "primary",
        "primary",
        "secondary"

      ]
    }
}
admin@ix-00-00-00:~$ 
</pre>

rfc6020#section-7.7 states: The values in a leaf-list MUST be unique.

does this not apply on RPCs according to any other RFC or is something wrong?

**Comment by michalvasko** [comment]
You conveniently left out the beginning of the sentence.
```
In configuration data, the values in a leaf-list MUST be unique.
```

**Comment by jktjkt** [comment]
Tricky. The YANG 1.1 spec [says this about the `input` nodes](https://datatracker.ietf.org/doc/html/rfc7950#section-7.14.2):

> Since the output tree is not part of any datastore, all "config"  statements for nodes in the output tree are ignored.

Also, the [summary of changes from YANG 1.0](https://datatracker.ietf.org/doc/html/rfc7950#section-1.1) says this:

> Allow non-unique values in non-configuration leaf-lists (see [Section 7.7](https://datatracker.ietf.org/doc/html/rfc7950#section-7.7)).

And finally, that section says:

> In configuration data, the values in a leaf-list MUST be unique.

As a result, I think that the current behavior is correct.

**Comment by mattiaswal** [comment]
Ok, thats make it a little clearer.

Thanks for the help @jktjkt  and @michalvasko
