### ISSUE TITLE
libyang is unable to print leafref value

### ISSUE THREAD

**Issue by milanlenco** [CESNET/libyang#233]
Sysrepo unit tests fail because libyang is unable to print value of a leafref with relative path:
```
<leafref-chain xmlns="urn:ietf:params:xml:ns:yang:test-module">
  <D>final-leaf</D>
  <C"(!error!)"
</leafref-chain>

```

The relevant part of the yang:
```
  container leafref-chain {
    leaf A {
        type leafref {
            path "../B";
        }
    }

    leaf B {
        type leafref {
            path "../C";
        }
    }

    leaf C {
        type leafref {
            path "../D";
        }
    }

    leaf D {
        type string;
    }
  }
```

The content of this particular part of the test-module startup datastore is constructed [here](https://github.com/sysrepo/sysrepo/blob/devel/tests/helpers/test_module_helper.c#L209-L215). Then it is validated and printed as usually.

**Comment by michalvasko** [comment]
Hi,
could you please try again and be sure to have the latest libyang? It works fine for me.

main.c
```C
#include <stdio.h>
#include <stdlib.h>
#include <libyang/libyang.h>

int main(int argc, char **argv)
{
    struct ly_ctx *ctx = ly_ctx_new(".");
    const struct lys_module *module = ly_ctx_load_module(ctx, "test-module", NULL);
    struct lyd_node *node;

    node = lyd_new(NULL, module, "leafref-chain");
    lyd_new_leaf(node, module, "D", "final-leaf");
    lyd_new_leaf(node, module, "C", "final-leaf");

    lyd_print_file(stdout, node, LYD_XML, LYP_FORMAT | LYP_WITHSIBLINGS);

    lyd_free_withsiblings(node);
    ly_ctx_destroy(ctx, NULL);
    return 0;
}
```

output
```xml
<leafref-chain xmlns="dhhdhd">
  <D>final-leaf</D>
  <C>final-leaf</C>
</leafref-chain>
```

Regards,
Michal

**Comment by milanlenco** [comment]
You are right, initially the config is loaded and printed correctly. All leafrefs break only after _any_ part of the configuration is edited through rp_dt_set_item_wrapper. I will try to find out why.

**Comment by michalvasko** [comment]
Leafrefs should only break after any part of configuration that can affect those leafrefs is modified, but it is possible something is wrong with it. If you could just provide an example of it happening it should be quick to find out what is wrong.

Regards,
Michal

**Comment by milanlenco** [comment]
I have found the culprit. If the datastore content hasn't changed since the last commit, the next commit will just print its content from the memory. If, however, the content was edited, the subsequent commit will do much more and at one point it will duplicate the datastore content using [this method](https://github.com/sysrepo/sysrepo/blob/devel/src/common/sr_utils.c#L674-L703) for certain reasons and later will print this duplicate to the file. It seems that lyd_dup breaks leafrefs (all of them).

**Comment by michalvasko** [comment]
Hi,
I think the whole problem is that the data tree is not validated. I made a mistake too, after finishing building the data tree, I should have validated it first and then print (it prints warnings, if they are visible). `lyd_dup()` breaks all leafrefs, because all of them need to be resolved again to point to the new tree. So, just validate the new tree and it should work.

Regards,
Michal

**Comment by milanlenco** [comment]
Confirmed that calling `lyd_validated` after `lyd_dup` solves the issue.

**Comment by michalvasko** [comment]
Well, it should always be possible to print the data now.
