### ISSUE TITLE
Fail to load ietf-yang-library - question

### ISSUE THREAD

**Issue by OrlySch** [CESNET/libyang#239]
I'm trying to connect a netopeer-gui cliect to a remote tail-f Confd server.
The server is using  ietf-yang-library@2016-04-09 version while the netopeer client seems to be working with  ietf-yang-library@2016-06-21.yang

Below are two /var/log/syslog outputs (in the first one the server does not include the ietf-yang-library in the get-schema rpc response for the ) 

(1)
Jan  5 16:08:24 ubuntu16 netopeerguid[2997]: lib VERBOSE: Reading module "ietf-yang-library".
Jan  5 16:08:24 ubuntu16 netopeerguid[2997]: lib VERBOSE: Module "ietf-yang-library" successfully parsed.
Jan  5 16:08:25 ubuntu16 netopeerguid[2997]: lib WARNING: Failed to load model "ietf-yang-library".
Jan  5 16:08:25 ubuntu16 netopeerguid[2997]: lib VERBOSE: Searching for "ietf-yang-library" in /usr/local/share/libnetconf2.
Jan  5 16:08:25 ubuntu16 netopeerguid[2997]: lib VERBOSE: Searching for "ietf-yang-library" in /.
Jan  5 16:08:25 ubuntu16 netopeerguid[2997]: lib ERROR: Data model "ietf-yang-library" not found.
Jan  5 16:08:25 ubuntu16 netopeerguid[2997]: lib WARNING: Failed to load model "ietf-yang-library".

(2)
Jan  5 16:25:53 ubuntu16 netopeerguid[2997]: lib VERBOSE: Reading module "ietf-yang-library".
Jan  5 16:25:53 ubuntu16 netopeerguid[2997]: lib VERBOSE: Module "ietf-yang-library" successfully parsed.
Jan  5 16:25:54 ubuntu16 netopeerguid[2997]: lib VERBOSE: Resolving "ietf-yang-library" unresolved schema nodes and their constraints...
Jan  5 16:25:54 ubuntu16 netopeerguid[2997]: lib VERBOSE: All "ietf-yang-library" schema nodes and constraints resolved.
Jan  5 16:25:54 ubuntu16 netopeerguid[2997]: lib ERROR: Module "ietf-yang-library" in another revision already implemented.
Jan  5 16:25:54 ubuntu16 netopeerguid[2997]: lib ERROR: Module "ietf-yang-library" parsing failed.
Jan  5 16:25:54 ubuntu16 netopeerguid[2997]: lib WARNING: Failed to load model "ietf-yang-library".
Jan  5 16:25:54 ubuntu16 netopeerguid[2997]: lib VERBOSE: Searching for "ietf-yang-library" in /usr/local/share/libnetconf2.
Jan  5 16:25:54 ubuntu16 netopeerguid[2997]: lib VERBOSE: Searching for "ietf-yang-library" in /.
Jan  5 16:25:54 ubuntu16 netopeerguid[2997]: lib ERROR: Data model "ietf-yang-library" not found.
Jan  5 16:25:54 ubuntu16 netopeerguid[2997]: lib WARNING: Failed to load model "ietf-yang-library".

How should I handle this?

Thanks,
Orly. 

A whole log of  /var/log/syslog is in:
[Log1.txt](https://github.com/CESNET/libyang/files/687578/Log1.txt)

**Comment by michalvasko** [comment]
Hi Orly,
unfortunately, because *ietf-yang-library* is used internally, in this case netopeer-gui is simply incompatible. We will try to think about a solution (not anytime soon), but it may be too complicated, so it may remain incompatible.

Regards,
Michal

**Comment by OrlySch** [comment]
Thank you Michal, it won't be necessary.
