### ISSUE TITLE
question：is there any way to find schema node in choice  by data tree format xpath?

### ISSUE THREAD

**Issue by ostack** [CESNET/libyang#244]
consider the model like the below, the data tree xpath may be like : "/ListModule:Root/leaf2"
,if we use  **ly_ctx_get_node**  to find schema node by this xpath ,it returns NULL,so i wonder is there any way to find schema node in choice  by data tree format xpath?

thanks very much
```
module ListModule{
	namespace "urn:ietf:params:xml:ns:yang:ostack:listmodel";
	prefix ListModule;
	container Root{
		choice transchoice {
			case choice1 {
				leaf leaf1 {
					type uint8;
				}
			}
			case choice2{
				leaf leaf2{
					type enumeration{
						enum one;
					}
				}
			}
		}
}
```

**Comment by michalvasko** [comment]
Hi,
to simply answer your question, yes, use `lys_find_xpath()`.

Regards,
Michal

**Comment by ostack** [comment]
* @param[in] node Context schema node if \p expr is relative, otherwise any node.

how to understand the description of the second parameter?  is any node means: no matter in same model or in different model?


**/**
 * @brief Search for schema nodes matching the provided XPath expression.
 *
 * @param[in] node Context schema node if \p expr is relative, otherwise any node.
 * @param[in] expr XPath expression filtering the matching nodes.
 * @param[in] options Bitmask of LYS_FIND_* options.
 * @return Set of found schema nodes. If no nodes are matching \p expr or the result
 * would be a number, a string, or a boolean, the returned set is empty. In case of an error, NULL is returned.
 */
struct ly_set *lys_find_xpath(const struct lys_node *node, const char *expr, int options);**

**Comment by michalvasko** [comment]
Hi,
the node can be from any model. I changed the parameters and their description in the devel branch to clarify them.

Regards,
Michal

**Comment by ostack** [comment]
if we can input any node of any node ,why not to support input NULL of first parameter?

regardes

**Comment by michalvasko** [comment]
Hi,
the problem is that `ly_ctx *ctx` is required, we need it to have a place to search for the node, so it cannot be NULL. But I agree that this API is kind-of confusing and it is already changed in `devel`.

Regards,
Michal
