### ISSUE TITLE
Libyang fails to parse ietf-netconf-acm

### ISSUE THREAD

**Issue by lukasmacko** [CESNET/libyang#246]
libyang in the latest devel branch fails to parse the `ietf-netconf-acm` yang

```C
#include <stdio.h>
#include <stdlib.h>
#include <libyang/libyang.h>

int main(int argc, char **argv)
{
   struct ly_ctx *ctx = ly_ctx_new(".");
   const struct lys_module *module = ly_ctx_load_module(ctx, "ietf-netconf-acm", NULL);

   ly_ctx_destroy(ctx, NULL);
}

```

```
libyang[0]: Invalid keyword "\*"".
libyang[0]: Module "ietf-netconf-acm" parsing failed.
```

**Comment by rkrejci** [comment]
libyang is correct, please apply the [ietf-netconf-acm errata](https://www.rfc-editor.org/errata_search.php?rfc=6536) to the model you are using.

**Comment by rkrejci** [comment]
I would like to cherry-pick this correction from devel to the libyang's master branch, so please fix the module also in the sysrepo master. The corrected module can be found also in [libyang source files](https://github.com/CESNET/libyang/blob/master/tests/schema/yang/ietf/ietf-netconf-acm.yang).

**Comment by lukasmacko** [comment]
ok, it shouldn't be a problem since `ietf-netconf-acm` is not installed in master branch.
