### ISSUE TITLE
ietf yang models no longer load via sysrepoctl

### ISSUE THREAD

**Issue by joanlandry** [CESNET/libyang#249]
I just updated to the latest master branch version of libyang,netopeer2, libnetcong, and sysrepo

I am now getting the following error when I try to load some of the yang models that use to load.
```
[root@landry tmp]# sysrepoctl --install --yang=/tmp/ietf-netconf-acm@2012-02-22.yang  
Installing a new module from file '/tmp/ietf-netconf-acm@2012-02-22.yang'...
[ERR] (srctl_ly_log_cb:479) libyang: Invalid keyword "\*"".
[ERR] (srctl_ly_log_cb:479) libyang: Module "ietf-netconf-acm" parsing failed.
Error: Unable to load the module by libyang.
Install operation failed.
[root@landry tmp]#
```
This is an ietf yang model : ietf-netconf-acm@2012-02-22.yang

```

module ietf-netconf-acm {
  namespace "urn:ietf:params:xml:ns:yang:ietf-netconf-acm";
  prefix "nacm";
  import ietf-yang-types {
    prefix yang;
  }
…
```

 ```
 typedef matchall-string-type {
    type string {
      pattern "\*";
    }
    description
      "The string containing a single asterisk '*' is used
       to conceptually represent all possible values
       for the particular leaf using this data type.";
  }

```

**Comment by rkrejci** [comment]
check the model's [errata](https://www.rfc-editor.org/errata_search.php?rfc=6536), this use of backslash in double-quoted string is invalid.

**Comment by joanlandry** [comment]
thanks for the info - not sure what is the solution to this - are we suppose to modify our local copy of this ietf yang mode?

**Comment by rkrejci** [comment]
yes, or you can download the already modified schema from [netconfcentral](http://netconfcentral.org/modulereport/ietf-netconf-acm) (see the Summary tab)

**Comment by joanlandry** [comment]
thank you
