### ISSUE TITLE
Validation always fails for empty Action/RPC output 

### ISSUE THREAD

**Issue by milanlenco** [CESNET/libyang#253]
After executing action "unload" from our [YANG module for tests](https://github.com/sysrepo/sysrepo/blob/devel/tests/yang/test-module.yang), I have observed that the validation fails for LYD_OPT_RPCREPLY if the data subtree for action output is empty (even if it is valid -- for action "unload" both output and input clauses are undefined in YANG).

For example, when validating action "/test-module:kernel-modules/kernel-module[name='vboxvideo.ko']/unload" with both input and output data being empty, the corresponding data tree is:
```
<kernel-modules xmlns="urn:ietf:params:xml:ns:yang:test-module">
  <kernel-module>
    <name>vboxvideo.ko</name>
    <unload/>
  </kernel-module>
</kernel-modules>
```
(this content is generated solely by the action's xpath)

For LYD_OPT_RPC I receive positive result, but for LYD_OPT_RPCREPLY I get libyang error "Not valid reply data".

I believe this is related to the issue: https://github.com/sysrepo/sysrepo/issues/712

**Comment by michalvasko** [comment]
Hi Milan,

yes, the problem is actually in libyang and so validating empty RPC reply will pass if valid according to the schema.

Regards,
Michal
