### ISSUE TITLE
Unable to install libyang (required for libnetconf2)

### ISSUE THREAD

**Issue by balavenkata** [CESNET/libyang#254]
All-

I'm trying to get libenetconf2 installed and as a pre-requisite it looks like
[libyang-install-fails.txt](https://github.com/CESNET/libyang/files/746946/libyang-install-fails.txt)
 I need to install libyang. While attempting that I saw errors with missing 'flex' and 'bison' executables. Is this expected ? I don't see them listed as pre-requisites for libyang (not [here ](https://github.com/CESNET/libyang/blob/master/README.md)at least). Thoughts ?  I've attached the console logs from my attempt

TIA

**Comment by jktjkt** [comment]
Yes, you'll need to install these developer tools. They are needed as parser generators.

**Comment by balavenkata** [comment]
Forgot to mention that libpcre is there in my host:

bvenkata@bvenkata-hope1:/usr$ find . -name *pcre*
./share/doc/libpcre3
./share/man/man3/clnt_pcreateerror.3.gz
./share/man/man3/clnt_spcreateerror.3.gz
./share/man/man3/pcrepattern.3.gz
./lib/libreoffice/program/resource/pcren-US.res
./lib/x86_64-linux-gnu/libpcreposix.so.3.13.1
./lib/x86_64-linux-gnu/libpcreposix.so.3
bvenkata@bvenkata-hope1:/usr$

**Comment by rkrejci** [comment]
flex/bison should not be needed until you change source codes.

**Comment by rkrejci** [comment]
Our cmake seems wrong to require them, I'm going to fix it.

**Comment by rkrejci** [comment]
ah, cmake is correct - the missing bison/flex are announced only as warnings. The problem in your case is missing libpcre (remember to install mainly its devel package). Seems a little weird for me that you have `libpcreposix.so` but you don't have any `libpcre.so`, what distro are you using?

**Comment by balavenkata** [comment]
To be fair, it was listed as a "warning". In my case it seems it goes ahead and fails at the point where it tries pcre:

> 
> -- Could NOT find FLEX (missing:  FLEX_EXECUTABLE) 
> -- Could NOT find BISON (missing:  BISON_EXECUTABLE) 
> **CMake Warning** at CMakeLists.txt:24 (message):
>   Missing Bison.
> 
>   Target bison does not exist.
> 
> 
> CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
>   Could NOT find PCRE (missing: PCRE_LIBRARY PCRE_INCLUDE_DIR)
