### ISSUE TITLE
libyang[0]: Internal error of lyd_parse_path with "grouping" and "uses" statement

### ISSUE THREAD

**Issue by KC-Su** [CESNET/libyang#259]
Hi,
I am still using libyang 0.11.105 version and meet the error described in title.
Here is my yang and json:

Yang schema:
```yang
module dump-data {
  yang-version 1.1;
  namespace "http://example.com/dump-data";
  prefix dtree;

  grouping grp_test {
    grouping grp_foo {
      leaf pri {
        type int32;
      }
    }

    leaf grp_test_leaf {
      type int32;
    }
    notification notif_in_grp;
  }

  container cont_test {
    uses grp_test {
      when "2>1";
      refine grp_test_leaf {
        default "0";
      }
    }
  }
}
```
Input JSON:
```json
{
  "dump_test:cont_test": {
    "grp_test_leaf": 1
  }
}
```

After trying, I found there are two way to make it valid:
1. Not to write `when` in `uses grp_test`
2. Neither `notification` or `grouping grp_foo` in `grouping grp_test`

Not found any explanation about this in RFC 7950, or maybe I missed.

thanks for attention

Best.

**Comment by michalvasko** [comment]
Hi,

it should be fixed and for future, you should never see an internal error, so you didn't need to try and make it valid.

Regards,
Michal

**Comment by KC-Su** [comment]
Appreciate!! :)
