### ISSUE TITLE
libyang error

### ISSUE THREAD

**Issue by betsyrosemanuel** [CESNET/libyang#261]
Hi,
     I used sysrepo as datastore and tried to perform edit-config on the profille vectors  and got the following libyang error and validation failed 

```
[DBG] (rp_dt_commit:688) Commit (1/9): process started
[DBG] (dm_ly_log_cb:850) libyang error: Leafref "/bbf-fast:fast/bbf-fast:service/bbf-fast:time-division-duplexing-profile/bbf-fast:name" of value "test_tdd_1" points to a non-existing leaf.
[DBG] (dm_ly_log_cb:850) libyang error: Leafref "/bbf-fast:fast/bbf-fast:service/bbf-fast:downstream-data-rate-profile/bbf-fast:name" of value "test_dsrp_1" points to a non-existing leaf.
[DBG] (dm_ly_log_cb:850) libyang error: Leafref "/bbf-fast:fast/bbf-fast:service/bbf-fast:upstream-data-rate-profile/bbf-fast:name" of value "test_usrp_1" points to a non-existing leaf.
[DBG] (dm_ly_log_cb:850) libyang error: Leafref "/bbf-fast:fast/bbf-fast:service/bbf-fast:low-power-data-rate-profile/bbf-fast:name" of value "test_lprp_1" points to a non-existing leaf.
[DBG] (dm_ly_log_cb:850) libyang error: Leafref "/bbf-fast:fast/bbf-fast:spectrum/bbf-fast:line-spectrum-profile/bbf-fast:name" of value "test_lsp_1" points to a non-existing leaf.
[DBG] (dm_ly_log_cb:850) libyang error: Leafref "/bbf-fast:fast/bbf-fast:spectrum/bbf-fast:upstream-power-back-off-profile/bbf-fast:name" of value "test_upbp_1" points to a non-existing leaf.
[DBG] (dm_ly_log_cb:850) libyang error: Leafref "/bbf-fast:fast/bbf-fast:spectrum/bbf-fast:radio-frequency-interference-profile/bbf-fast:name" of value "test_rfip_1" points to a non-existing leaf.
[DBG] (dm_ly_log_cb:850) libyang error: Leafref "/bbf-fast:fast/bbf-fast:quality/bbf-fast:noise-margin-profile/bbf-fast:name" of value "test_nmp_1" points to a non-existing leaf.
[DBG] (dm_ly_log_cb:850) libyang error: Leafref "/bbf-fast:fast/bbf-fast:quality/bbf-fast:fast-rate-adaptation-profile/bbf-fast:name" of value "test_frap_1" points to a non-existing leaf.
[DBG] (dm_ly_log_cb:850) libyang error: Leafref "/bbf-fast:fast/bbf-fast:quality/bbf-fast:retransmission-profile/bbf-fast:name" of value "test_rtxp_1" points to a non-existing leaf.
[DBG] (dm_ly_log_cb:850) libyang error: Leafref "/bbf-fast:fast/bbf-fast:quality/bbf-fast:fast-retrain-policy-profile/bbf-fast:name" of value "test_frpp_1" points to a non-existing leaf.
[DBG] (dm_ly_log_cb:850) libyang error: Leafref "/bbf-fast:fast/bbf-fast:quality/bbf-fast:vectoring-profile/bbf-fast:name" of value "test_vp_1" points to a non-existing leaf.
[DBG] (dm_validate_session_data_trees:2168) Validation failed for bbf-fast module
[ERR] (rp_dt_commit:694) Data validation failed: Leafref "/bbf-fast:fast/bbf-fast:quality/bbf-fast:vectoring-profile/bbf-fast:name" of value "test_vp_1" points to a non-existing leaf.
```

please refer the following links. In the first link, i have bbf-fast yang files. Also used some dependency yang files from 2nd link(IETF) . 

https://github.com/BroadbandForum/yang/tree/master/standard

https://github.com/YangModels/yang/tree/master/standard/ietf/RFC

Thank you

**Comment by michalvasko** [comment]
Hi,

please provide the `edit-config` configuration that you sent, the errors may be correct.

Regards,
Michal

**Comment by betsyrosemanuel** [comment]
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
  <edit-config>
    <target>
      <running/>
    </target>	
    <config>
<fast xmlns="urn:bbf:yang:bbf-fast" xmlns:ns0="urn:ietf:params:xml:ns:netconf:base:1.0" ns0:operation="merge">
  <vectors>
    <line-config-vector>
      <name>test_lcv_1</name>
      <time-division-duplexing-profile>test_tdd_1</time-division-duplexing-profile>
      <downstream-data-rate-profile>test_dsrp_1</downstream-data-rate-profile>
      <upstream-data-rate-profile>test_usrp_1</upstream-data-rate-profile>
      <low-power-data-rate-profile>test_lprp_1</low-power-data-rate-profile>
      <line-spectrum-profile>test_lsp_1</line-spectrum-profile>
      <upstream-power-back-off-profile>test_upbp_1</upstream-power-back-off-profile>
      <radio-frequency-interference-profile>test_rfip_1</radio-frequency-interference-profile>
      <noise-margin-profile>test_nmp_1</noise-margin-profile>
      <fast-rate-adaptation-profile>test_frap_1</fast-rate-adaptation-profile>
      <retransmission-profile>test_rtxp_1</retransmission-profile>
      <fast-retrain-policy-profile>test_frpp_1</fast-retrain-policy-profile>
      <vectoring-profile>test_vp_1</vectoring-profile>
    </line-config-vector>
</vectors>
</fast>
</config>
</edit-config>
</config>
</rpc>

**Comment by betsyrosemanuel** [comment]
hi,
 This is the xml for which i am getting yang error.
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
  <edit-config>
    <target>
      <running/>
    </target>	
    <config>
<fast xmlns="urn:bbf:yang:bbf-fast" xmlns:ns0="urn:ietf:params:xml:ns:netconf:base:1.0" ns0:operation="merge">
  <vectors>
    <line-config-vector>
      <name>test_lcv_1</name>
      <time-division-duplexing-profile>test_tdd_1</time-division-duplexing-profile>
      <downstream-data-rate-profile>test_dsrp_1</downstream-data-rate-profile>
      <upstream-data-rate-profile>test_usrp_1</upstream-data-rate-profile>
      <low-power-data-rate-profile>test_lprp_1</low-power-data-rate-profile>
      <line-spectrum-profile>test_lsp_1</line-spectrum-profile>
      <upstream-power-back-off-profile>test_upbp_1</upstream-power-back-off-profile>
      <radio-frequency-interference-profile>test_rfip_1</radio-frequency-interference-profile>
      <noise-margin-profile>test_nmp_1</noise-margin-profile>
      <fast-rate-adaptation-profile>test_frap_1</fast-rate-adaptation-profile>
      <retransmission-profile>test_rtxp_1</retransmission-profile>
      <fast-retrain-policy-profile>test_frpp_1</fast-retrain-policy-profile>
      <vectoring-profile>test_vp_1</vectoring-profile>
    </line-config-vector>
</vectors>
</fast>
</config>
</edit-config>
</rpc>

**Comment by betsyrosemanuel** [comment]
[xml_edit_err.txt](https://github.com/CESNET/libyang/files/759713/xml_edit_err.txt)

**Comment by betsyrosemanuel** [comment]
hi,
   any update on the issue????

**Comment by michalvasko** [comment]
Hi,

no, there is no update yet, but it is being worked on (it happens fairly often that one issue reveals other issues/possible upgrades when we first finish those, this is one such case). Nevertheless, it is going to be fixed only in the `devel` branch, so I hope that is not a problem, it is going to be merged into `master` at the end of February. There are simply too many changes in `devel` now and it would be a waste of time to fix anything in `master` now, sorry.

Regards,
Michal

**Comment by michalvasko** [comment]
Hi,

okay, I finally managed to load all the submodules in `devel` so I could print how the whole data tree looks. I assume the original configuration (`running` datastore) is empty (because you did not say otherwise) and then you sent this `edit-config`. If that is correct, the error is right and perfectly clear - you tried to create a new `line-config-vector` list with all its leafrefs. But the targets of these leafrefs do not exist, so the validation fails.

Regards,
Michal
