### ISSUE TITLE
validation failed 

### ISSUE THREAD

**Issue by betsyrosemanuel** [CESNET/libyang#266]
Hi,
  I tried to perform edit-config to the xml in the attached file
[error.txt](https://github.com/CESNET/libyang/files/770990/error.txt)
 but validation failed for the same.. could u please tell me what went wrong and how to resolve it?

log: 
[DBG] (sr_cbuff_dequeue:477) Circular buffer dequeue, new buffer head=4, count=0.
[DBG] (rp_commit_req_process:1113) Processing commit request.
[DBG] (rp_dt_commit:688) Commit (1/9): process started
[ERR] (md_get_module_info:1260) Module 'iana-if-type@2016-06-09@<latest>' is not present in the dependency graph.
[ERR] (dm_load_module:570) Module 'iana-if-type@2016-06-09:<latest>' is not installed.
[ERR] (dm_get_data_info:1735) Get module 'iana-if-type@2016-06-09' failed
[ERR] (dm_append_data_tree:1325) Get data info failed for module iana-if-type@2016-06-09
[ERR] (dm_load_dependant_data:1420) Failed to append data tree iana-if-type@2016-06-09
[ERR] (dm_validate_session_data_trees:2165) Loading dependant modules failed for ietf-interfaces
[ERR] (rp_dt_commit:694) Data validation failed: (no error)
[DBG] (sr_cbuff_enqueue:461) Circular buffer enqueue to position=5, current count=1.
[DBG] (rp_worker_thread_execute:2862) Thread id=1991988368 will wait.
[DBG] (cm_msg_enqueue_cb:1668) New message enqueued into CM message queue.
[DBG] (sr_cbuff_dequeue:477) Circular buffer dequeue, new buffer head=6, count=0.
[DBG] (cm_conn_out_buff_flush:505) Sending 28 bytes of data.
[DBG] (cm_conn_out_buff_flush:511) 28 bytes of data sent.
[DBG] (cm_conn_read_cb:1059) fd 6 readable
[DBG] (cm_conn_read_cb:1072) 26 bytes of data received on fd 6
[DBG] (cm_conn_read_cb:1082) fd 6 would block
[DBG] (cm_conn_in_buff_process:1011) New message of size 22 bytes received.
[DBG] (sr_cbuff_enqueue:461) Circular buffer enqueue to position=4, current count=1.
[DBG] (rp_msg_process:3146) Threads: active=0/4, 1 requests in queue
[DBG] (rp_worker_thread_execute:2874) Thread id=1966822544 signaled.
[DBG] (sr_cbuff_dequeue:477) Circular buffer dequeue, new buffer head=5, count=0.
[DBG] (rp_discard_changes_req_process:1184) Processing discard_changes request.
[DBG] (dm_data_info_free:224) Usage count ietf-interfaces decremented (value=0)
[DBG] (sr_cbuff_enqueue:461) Circular buffer enqueue to position=6, current count=1.
[DBG] (rp_worker_thread_execute:2862) Thread id=1966822544 will wait.
[DBG] (cm_msg_enqueue_cb:1668) New message enqueued into CM message queue.
[DBG] (sr_cbuff_dequeue:477) Circular buffer dequeue, new buffer head=7, count=0.
[DBG] (cm_conn_out_buff_flush:505) Sending 28 bytes of data.
[DBG] (cm_conn_out_buff_flush:511) 28 bytes of data sent.

**Comment by michalvasko** [comment]
Hi,
the error printed out by the client is perhaps a bit misleading, but *sysrepo* is totally clear. You are missing `iana-if-type` schema. Try adding it using `sysrepoctl`. If you have it imported in *sysrepo*, then there is some other issue, but in *sysrepo*, not *libyang*, so you will need to ask them for help.

Regards,
Michal
