### ISSUE TITLE
Support for case shorthand

### ISSUE THREAD

**Issue by arun11299** [CESNET/libyang#277]
Per yang rfc 6020 section 7.9.2

> As a shorthand, the "case" statement can be omitted if the branch
>    contains a single "anyxml", "container", "leaf", "list", or
>    "leaf-list" statement.  In this case, the identifier of the case node
>    is the same as the identifier in the branch statement.  The following
>    example:
> 
>      choice interface-type {
>          container ethernet { ... }
>      }
> 
>    is equivalent to:
> 
>      choice interface-type {
>          case ethernet {
>              container ethernet { ... }
>          }
>      }
> 

This is currently not supported. Any plans to support it sooner ?

Thanks!

**Comment by michalvasko** [comment]
Hi,
what exactly do you mean, it definitely should be supported. Please provide your schema that fails to parse.

Regards,
Michal

**Comment by arun11299** [comment]
Hi,
I will provide the test yang modules soon. The issue was seen when trying to augment from a case for which the case statement was not provided explicitly.

Thanks.

**Comment by michalvasko** [comment]
Hi,
in that case my guess is that you addressed the container directly like `interface-type/ethernet`. But that is wrong, because shorthand case is just a syntactic shortcut, you still have to address it with `interface-type/ethernet/ethernet`.

Regards,
Michal
