### ISSUE TITLE
Self-referencing extension crashes yanglint

### ISSUE THREAD

**Issue by iwanb** [CESNET/libyang#278]
A module using an extension before defining it crashes yanglint.
It is because the function `yang_use_extension` tries to access the module prefix which is still null at that point, in:
`if (!ns && !strcmp(module->prefix, prefix)) {`

[Minimal Yang module extmod.yang](https://github.com/CESNET/libyang/files/827606/extmod.yang.txt)
[Backtrace](https://github.com/CESNET/libyang/files/827607/bt.txt)

**Comment by rkrejci** [comment]
Hi, please check the current devel (0.12.110), I'm not able to reproduce the issue, it seems that it was already fixed.

**Comment by iwanb** [comment]
Hi, indeed my bad, I did not realise master was not the most current version, sorry for the wrong issue!
