### ISSUE TITLE
Leafref with default in submodule makes validation fail silently

### ISSUE THREAD

**Issue by iwanb** [CESNET/libyang#279]
With the following model, the leafref is not properly resolved which makes the validation fail (without any error printed).
[a.yang.txt](https://github.com/CESNET/libyang/files/831133/a.yang.txt)
[a-sub.yang.txt](https://github.com/CESNET/libyang/files/831134/a-sub.yang.txt)

The condition to get the issue seems to be both, 1) the leafref has a default, 2) the leafref is in a submodule.

I get this output with the verbose mode with yanglint:
> Validating a.yang schema file.
> verb: Searching for "a-sub" in /tmp/yangsubset.
> verb: Loading schema from "/tmp/yangsubset/a-sub.yang" file.
> verb: Resolving type default "�L�" failed, it will be attempted later.
> verb: Submodule "a-sub" successfully parsed.
> verb: Resolving "a" unresolved schema nodes and their constraints...
> err : Module "a" parsing failed.

If I include the content of the submodule in the main module manually, then the validation passes. Same if I remove the default statement.

Noticed on the last devel build.

**Comment by iwanb** [comment]
I still get the same issue if I add another level of indirection (submodule in a submodule)
[a.yang.txt](https://github.com/CESNET/libyang/files/831662/a.yang.txt)
[a-sub.yang.txt](https://github.com/CESNET/libyang/files/831663/a-sub.yang.txt)
[a-sub1.yang.txt](https://github.com/CESNET/libyang/files/831664/a-sub1.yang.txt)

Thanks for the fix!

**Comment by michalvasko** [comment]
Hi,
please try again, thanks.

Regards,
Michal

**Comment by iwanb** [comment]
It works now, thanks!
