### ISSUE TITLE
Segfault with leafref

### ISSUE THREAD

**Issue by abhikeshav** [CESNET/libyang#287]
Hi,
Getting a segfault when validating below instance data using `yanglint`
```
./yanglint 
> add ydktest-sanity@2015-11-17.yang 
> data leafref.xml 
Segmentation fault: 11
```

```xml
<runner xmlns="http://cisco.com/ns/yang/ydktest-sanity">
  <inbtw-list>

    <ldata>
      <number>21</number>
      <name>runner:inbtwlist[21]:name</name>
      <subc>
        <name>runner:inbtwlist[21]:subc:name</name>
        <number>121</number>
        <subc-subl1>
          <number>311</number>
          <name>runner:inbtwlist[21]:subc:subcsubl1[311]:name</name>
        </subc-subl1>
      </subc>
    </ldata>
  </inbtw-list>
  <leaf-ref>

    <ref-inbtw>runner:inbtwlist[21]:subc:subcsubl1[311]:name</ref-inbtw>
    <ref-two-sub1-number>21</ref-two-sub1-number>
  </leaf-ref>
  <one>
    <name>runner:one:name</name>
  </one>
  <three>
    <sub1>
      <sub2>
        <number>311</number>
      </sub2>
    </sub1>
  </three>
  <two>
    <sub1>
      <number>21</number>
    </sub1>
  </two>
</runner>

```
Here [is the yang model](https://github.com/CiscoDevNet/ydk-gen/blob/master/yang/ydktest/ydktest-sanity%402015-11-17.yang).

**Comment by rkrejci** [comment]
Hi, few notes before closing the issue:

- I'm not able to even parse the module you link, it has invalid string pattern:
```
> add ydktest-sanity@2015-11-17.yang 
libyang[0]: Invalid keyword "(([0\-9]\|[1\-9][0\-9]\|1[0\-9][0\-9]\|2[0\-4][0\-9]\|25[0\-5])\\.){3}([0\-9]\|[1\-9][0\-9]\|1[0\-9][0\-9]\|2[0\-4][0\-9]\|25[0\-5])(%[\\p{N}\\p{L}]+)?"".
libyang[0]: Module "ydktest-sanity" parsing failed.
```
so I had to fix the pattern first.
- I wasn't able to reproduce the segfault, which version are you using?
- your data are missing `ref-three-sub1-sub2-number` node with the value `311`, so I had to add it
- what I was fixing was incorrect comparison between the values refered in the path's predicates

**Comment by rkrejci** [comment]
I was able to reproduce the segfault, previously I was using `-t config` option to avoid printing status data. When yanglint is used without the option, seqfault appears.

**Comment by abhikeshav** [comment]
Thanks for fixing this!
