### ISSUE TITLE
Parsing fails with the latest master clone

### ISSUE THREAD

**Issue by arun11299** [CESNET/libyang#291]
I am having a small test program which just tries to load a module and exit. With the latest clone it fails to create a context and gives out below error:

> libyang[0]: Invalid keyword "type" as a child to "annotation". (path: /)
> libyang[0]: Module "yang" parsing failed.

For now, replacing `yang@2017-02-20.h` and `yang@2017-02-20.yang` with its previous version which is `yang@2016-02-11.yang` and `yang@2016-02-11.h` seems to work. 

Has something change w.r.t how modules should be loaded ?

**Comment by michalvasko** [comment]
Hi,
this change is connected to extensions, one fails to be parsed. The problem may be that annotation plugin cannot be found, did you install *libyang* properly? Does *yanglint* work fine, the first thing it does is that it creates a context.

Regards,
Michal

**Comment by rkrejci** [comment]
please check the [FAQ](https://github.com/CESNET/libyang/blob/master/FAQ.md)

**Comment by khanhn29** [comment]
Hello,
I meet the excact error when use nc_accept_callhome(), can you tell me how to fix it?
I'm using libyang1.0.230

**Comment by michalvasko** [comment]
It is still in [FAQ](https://github.com/CESNET/libyang/blob/libyang1/FAQ.md) except the branch has changed since *libyang* v1 is deprecated.

**Comment by khanhn29** [comment]
thank you for answering
