### ISSUE TITLE
Build failed due to unknown 'ssize_t

### ISSUE THREAD

**Issue by maixuanhan** [CESNET/libyang#292]
Hi,
I'm using __powerpc-linux-gcc__ to compile the source version 0.12-r1.

```CC=/usr/bin/ccache powerpc-linux-gcc```

When compiling with uclibc, it shows 2 errors like below.

```libyang-0.12-r1/src/extensions/../tree_schema.h:2329:19: error: unknown type name 'ssize_t'```

My temporary fix is including **unistd.h** in **tree_schema.h**

```c
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>

#ifdef __UCLIBC__
  #include <unistd.h>
#endif
```

You guys, please review what header file is needed for `ssize_t` type. Thanks.

**Comment by jktjkt** [comment]
According to POSIX, it appears to be [``<sys/types.h>``](http://pubs.opengroup.org/onlinepubs/7908799/xsh/systypes.h.html). Do you feel like sending a patch?

**Comment by michalvasko** [comment]
So it should be fixed, but you will need to compile it from the repository for now.

Regards,
Michal
