### ISSUE TITLE
API for resolving superior type not exposed ?

### ISSUE THREAD

**Issue by arun11299** [CESNET/libyang#295]
I have a need to traverse through the derived type field (`der`) inside the `type` information. Till now for testing I have been using `tree_internal.h` so as to get hands on `ly_types`. I now need an API to do that without the need for including the internal header file. I see on API to resolve superior types in `resolve.h`, but even that is not exposed.

Is there any other way to achieve the same ? The API can be as simple as answering whether it is the final resolved type or not.

**Comment by michalvasko** [comment]
Hi,
I don't think such a function is required, what exactly do you need it for? It may be possible to do it without this function.

Regards,
Michal

**Comment by arun11299** [comment]
Hi Michal,
Yes. I want something equivalent to:

```
static bool is_referring_type(const struct lys_type* type)
{
  for (int i = 1; i < LY_DATA_TYPE_COUNT; i++) {
    if (type->der == ly_types[i]) {
      return false;
    }
  }
  return true;
}
```
This checks whether the type is the final built-in type of a typedef.

Thanks.

**Comment by michalvasko** [comment]
It seems simple enough for you to use as your own function, no need to add it to *libyang* API.

Michal

**Comment by arun11299** [comment]
Yes, I am fine with that, but `ly_types` is not exposed to the users of the library. Its present in `tree_internal.h`. And if I include that, I need to change one function in it  which is using `new` as its argument name (that results in compilation failure for C++).

**Comment by michalvasko** [comment]
Right, you can actually skip the loop and just check that `module` is  `NULL`, that is true only for base types. 

Michal

**Comment by arun11299** [comment]
Ok. Hope its going to stay that way.
Thanks. Will use this check.

**Comment by rkrejci** [comment]
from the [docs](https://netopeer.liberouter.org/doc/libyang/devel/group__schematree.html#structlys__tpdf):
```
module - pointer to the module where the data type is defined (mandatory), 
         NULL in case of built-in typedefs
```
The internal code also count with this.
