### ISSUE TITLE
Parsing of refine fails in master

### ISSUE THREAD

**Issue by arun11299** [CESNET/libyang#296]
I have been using libyang-extensions branch for some time and have been using that to parse some 3rd party yang files which makes extensive use of refine statement. It used to work in that branch.

I have recently moved to the master branch and it fails to parse the refine statements now. 

The use of refine is something like below:
```
augment /if:interfaces/interfaces-bonding:bonding/interfaces-bonding:vif {
    uses bgroup {
      refine bgroup {
        configd:end "action.pl ${ACTION} $VAR(../../@).$VAR(../@)";
      }
    }
  }
```

The error is:
```
libyang[0]: Invalid value "bridge-group" of "refine". (path: /if:interfaces/interfaces-bonding:bonding/interfaces-bonding:vif /bridge-v1:bridge-group)
libyang[0]: Module "bridge-v1" parsing failed.
```

**Comment by rkrejci** [comment]
please provide something with which we will be able to reproduce the issue. Just a fragment of the schema is not enough.

**Comment by arun11299** [comment]
I have attached the set of yang files to reproduce the issue. The main yang file to parse is `vhost-bridge.yang`.

Error:

> libyang[0]: Invalid value "bridge-group" of "refine". (path: /tinterfaces:interfaces/interfaces-host:vhost/interfaces-host-vif:vif/vhost-bridge:bridge:bridge-group)
> libyang[0]: Module "vhost-bridge" parsing failed.

[refine.zip](https://github.com/CESNET/libyang/files/881270/refine.zip)

Thanks.

**Comment by rkrejci** [comment]
@michalvasko, please review your bigfix 24476fa. It made `resolve_descendant_schema_nodeid()` working incorrectly when resolving refine statement. Instead of start searchin the children of the uses statement, it goes through the uses to its parents.

**Comment by arun11299** [comment]
I don't think it's fixed. Will reopen it with a new set of reproducible schema. Could be a new issue as well.

**Comment by arun11299** [comment]
Have opened issue #301 for the above.
