### ISSUE TITLE
Augment parsing inside uses fails in master

### ISSUE THREAD

**Issue by arun11299** [CESNET/libyang#301]
Attached are two yang files. `augment-parse.yang` fails to parse with below error:

> libyang[0]: Unable to use search directory "/localdisk/amuralid/container/ub/rbac_new/rift/build/ub16_debug/install/usr/rift/usr/share/yuma/modules/ietf" (No such file or directory)
> libyang[0]: Failed to resolve augment "firewall". (path: /base-augment:cont1/{augment}[firewall])
> libyang[0]: Module "augment-parse" parsing failed.

[augment.zip](https://github.com/CESNET/libyang/files/889807/augment.zip)

**Comment by michalvasko** [comment]
Hi,
thanks, should be fixed.

Regards,
Michal

**Comment by arun11299** [comment]
Thanks for the quick fix. It is working now.
