### ISSUE TITLE
suggestion about extension feature

### ISSUE THREAD

**Issue by fanchanghu** [CESNET/libyang#307]
Hi,
I have used the extension feature in devel branch, then I found that I need store something in the struct `lys_ext_instance`, but it is not being supported now. How about adding a void pointer in `lys_ext_instance` for storing something by the plugin?

my use case is like this, I defined an extension with an argument about XPATH like below:
```
ex:path "/A:C1/f1"
```
I checked the `ex:path` in the plugin and found the schema node by its value, so I wish to save the node pointer in the extension instance for using it later.

**Comment by fanchanghu** [comment]
Hi,
Thanks for the fix. And it is more helpful if you can add a callback function to free the pointer when the extension instance is freed. (not in the case above, in some other cases.)

**Comment by rkrejci** [comment]
good point

**Comment by rkrejci** [comment]
The same `private_destructor` function passed via `ly_ctx_destroy()` should works for this as for other private data in schema nodes.
