### ISSUE TITLE
regex support issue 

### ISSUE THREAD

**Issue by rosy8** [CESNET/libyang#312]
Hi,
We have a  requirement where a string length should be only 0..255 and it should not support a special
char  `  in it. Based on that i have written a typedef in the yang file..
```
  typedef my-string {
    type string {
        length "0..255";
        pattern "[^`]";
      }
    description
      "Defines string types which does not accept ` and length is in the range of 0..255.";
  } 
```
No issue in compiling the yang file but while installing it I am getting the following error

[root@18-88 yang]# /usr/bin/sysrepoctl --install --yang=/ovn/etc/libnetconf/yang-models/XXX.yang
Installing a new module from file '/ovn/etc/libnetconf/yang-models/XXX.yang'...
[ERR] libyang: Value "" does not satisfy the constraint "[^`]" (range, length, or pattern).
[ERR] libyang: Value "" does not satisfy the constraint "[^`]" (range, length, or pattern).
[ERR] libyang: Value "" does not satisfy the constraint "[^`]" (range, length, or pattern).
[ERR] libyang: Value "" does not satisfy the constraint "[^`]" (range, length, or pattern).
[ERR] libyang: Value "default" does not satisfy the constraint "[^`]" (range, length, or pattern).
[ERR] libyang: Value "" does not satisfy the constraint "[^`]" (range, length, or pattern).
[ERR] libyang: Value "" does not satisfy the constraint "[^`]" (range, length, or pattern).
[ERR] libyang: Value "" does not satisfy the constraint "[^`]" (range, length, or pattern).
[ERR] libyang: Value "" does not satisfy the constraint "[^`]" (range, length, or pattern).
[ERR] libyang: Value "" does not satisfy the constraint "[^`]" (range, length, or pattern).
[ERR] libyang: Value "" does not satisfy the constraint "[^`]" (range, length, or pattern).
[ERR] libyang: Value "" does not satisfy the constraint "[^`]" (range, length, or pattern).
[ERR] libyang: Module "XXX" parsing failed.
Error: Unable to load the module by libyang.
Install operation failed.
[root@18-88 yang]#

Please let me know if I am missing anything here.

Regards,
Rosy

**Comment by rkrejci** [comment]
Hi,
IMO your pattern match only the single character strings (length 1), try the following pattern:
```
pattern "[^`]*";
```

**Comment by rosy8** [comment]
Hi,

Along with that it should also 
->reject newline and carriage return.
-> reject any string starting with #
So i changed to the following pattern..

 pattern "(^(?:((.*['].*)|(.*[\r\n].*)|(^#.*))).*$)";
With this I got the following compilation error

sh-4.1$ yangdump  XXX-ensemble-vnf.yang
*** Generated by yangdump 2.2-5
*** Copyright (c) 2008-2012, Andy Bierman, All Rights Reserved.
regexp error : failed to compile: xmlFAParseAtom: expecting ')'
regexp error : failed to compile: xmlFAParseAtom: expecting ')'
regexp error : failed to compile: xmlFAParseRegExp: extra characters

<b>XXX-ensemble-vnf.yang:35.17: error(313): invalid pattern </b>

And when I changed it to -  pattern "[^`\r\n].*$";
It compiles but getting the following error..

[root@18-88 ~]# /usr/bin/sysrepoctl --install --yang=/ovn/etc/libnetconf/yang-models/XXX-ensemble-vnf.yang
Installing a new module from file '/ovn/etc/libnetconf/yang-models/XXX-ensemble-vnf.yang'...
[ERR] libyang: Invalid keyword "[^`\r\n].*$"".
[ERR] libyang: Module "xxx-ensemble-vnf" parsing failed.
Error: Unable to load the module by libyang.
Install operation failed.
[root@18-88 ~]#

Regards,
Rosy

**Comment by rkrejci** [comment]
HI, I didn't check your pattern in details, but, in general, be careful about escaping - YANG allows to have only `\n`, `\t`, `\"` and `\\` in strings (quoted text), other characters cannot be used after backslash in YANG strings. Therefore, try to use `'regexp'` instead of `"regexp"`.

**Comment by michalvasko** [comment]
Hi,
I just want to point out the note in [this](https://www.w3.org/TR/2004/REC-xmlschema-2-20041028/#regexs) document (directly referenced in RFC 7950) about implicit anchoring, I don't think you are aware of it.

Regards,
Michal

**Comment by rkrejci** [comment]
so did that help? Can we close the issue?

**Comment by maixuanhan** [comment]
@rosy8 try the regex
```regex
[^#`\r\n][^`\r\n]*|[^#`\r\n]*
```
