### ISSUE TITLE
Query on "presence" containers 

### ISSUE THREAD

**Issue by rosy8** [CESNET/libyang#324]
Hi,

As per yang, presence containers are  explicitly created and deleted.

             +--rw connection-type
             |  +--rw (connection-type)?
             |     +--:(persistent-connection)
             |     |  +--rw persistent!    ====================>> Presence container
             |     |     +--rw idle-timeout?   uint32
             |     |     +--rw keep-alives
             |     |        +--rw max-wait?       uint16
             |     |        +--rw max-attempts?   uint8
             |     +--:(periodic-connection)
             |        +--rw periodic!
             |           +--rw idle-timeout?        uint16
             |           +--rw reconnect_timeout?   uint16

Suppose the input rpc contains only nodes as below (presence containers has not been created)
            <connection-type>
            </connection-type> 

Then what should be the behaviour during yang validation.
Does it through an error mentioning user has not created the presence containers or it should accept as it is ?
As per my understanding its not an error to not have presence containers ..and unless its not explicitly created it will not be present in the rpc request. 
Please let me know if I am missing something here.
Thanks in advance.

Regards,
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
yes, your understanding is correct, does *libyang* not behave this way?

Regards,
Michal

**Comment by rosy8** [comment]
Hi Michal,

Thanks for responding.
No, libyang is working in this way only :)

Regards,
Rosy
