### ISSUE TITLE
question:is leaf-list type can be defined as union?

### ISSUE THREAD

**Issue by ostack** [CESNET/libyang#326]
question:is leaf-list type can be defined as union?
In rfc7950 It says : "Where the "leaf" statement is used  to define a simple scalar variable of a particular type",so i think it is not allow to us union type on leaf-list, and what is your opinions?

**Comment by michalvasko** [comment]
Hi,
what you quoted is not really relevant, it is used just to show the difference between `leaf` and `leaf-list`, if you read the sentence to the end. So, I do not see anything that would directly or indirectly forbid defining `leaf-list` as a union.

Regards,
Michal
