### ISSUE TITLE
Number Predicates in a list of list parsed incorrectly.

### ISSUE THREAD

**Issue by mohitarora24** [CESNET/libyang#335]
Hi there,

First of all thanks for all the work.

Consider a following YANG hierarchy:
```
top
+-- alist [key1]
    +-- key1
    +-- leaf1
    +-- blist [key2]
        +--key2
        +--leaf2
```

Sample Data:
```xml
<top>
    <alist>
        <key1>1</key1>
        <blist>
            <key2>1</key2>
            <leaf2>abc1</leaf2>
        </blist>
        <blist>
            <key2>2</key2>
            <leaf2>abc2</leaf2>
        </blist>
        <blist>
            <key2>3</key2>
            <leaf2>abc3</leaf2>
        </blist>
    </alist>
    <alist>
        <key1>2</key1>
        <blist>
            <key2>11</key2>
            <leaf2>abc11</leaf2>
        </blist>
        <blist>
            <key2>21</key2>
            <leaf2>abc21</leaf2>
        </blist>
        <blist>
            <key2>31</key2>
            <leaf2>abc31</leaf2>
        </blist>
    </alist>
</top>
```

And the XPath filter applied over this: `/top/alist/blist[1]`

Note: I'm using **op_filter_get_tree_from_data()** from **op_generic.c** in Netopeer2 to apply the filter on the data.

Checking the xpath code, what I observed is:
Step 1:
Code first creates a set.
set contains 1 node "top"

Step 2:
It reaches alist in parsing the path
Modifies set to contatin 2 nodes - both the alist nodes

Step 3:
It reaches blist in parsing the path
Modifies set to contatin 6 nodes - 3 blist nodes from each alist

Step 4:
Now it evaluates the predicate (in **eval_predicate()**). Since it is just a number(i.e. LYXP_SET_NUMBER) - only the first blist in the set (`orig_pos == 1`) matches the number in the predicate (i.e. `1`).

So only 1st blist from 1st alist is returned in the output, when the expected output was the 1st blist from both the alist items.

Please check.

----

Possible fix in my mind in *eval_predicate()*:
to change
`if ((long long)set2.val.num == orig_pos) {`
to something like:
`if ((long long)set2.val.num == get_position_of_node_in_siblings(set->val.nodes[i].node)) {`
and
```c
static long long
get_position_of_node_in_siblings(const struct lyd_node *node)
{
  long long pos = 0;
  struct lyd_node *temp = (struct lyd_node *)node;
  
  if(!temp)
  { return 0; }

  for (; temp->prev->next; temp=temp->prev)
  {
    if(ly_strequal(temp->schema->name, node->schema->name, 0))
    {
      pos++;
    }
  }
  return pos;
}
```

Please confirm if the fix is valid as it is working for this case. I do not want to be breaking anything else. Also if you have something else in mind.

Regards.

**Comment by maixuanhan** [comment]
I think the response for `/top/alist/blist[1]` is only 1 node as libyang well done. `[1]` is the first node of the current context node. (not the first node of each blist).
https://www.w3.org/TR/2007/REC-xpath20-20070123/#id-predicates

**Comment by mohitarora24** [comment]
Hi @maixuanhan , Thanks for the reply.

Well I'm new to XPath so I maybe wrong. 
As per my understanding, the context node for each blist block is its parent alist block. Not the `/` which is the current node. I'm still confused :)

I think the output was valid if the XPath filter was `(/top/alist/blist)[1]`

For example, check this page: https://msdn.microsoft.com/en-us/library/ms256086(v=vs.110).aspx
Especially this part:

=========

Note that indexes are relative to the parent. Consider the following data:
```xml
<x>
  <y/>
  <y/>
</x>
<x>
  <y/>
  <y/>
</x>
```

Expression | Refers to
---------- | ---------
x/y[1] | The first `<y>` child of each `<x>`. This is equivalent to the expression in the next row.
x/y[position() = 1] | The first `<y>` child of each `<x>`.
(x/y)[1] | The first `<y>` from the entire set of `<y>` children of `<x>` elements.
x[1]/y[2] | The second `<y>` child of the first `<x>`.

=========

If what I think is correct, then there might be more changes with reference to **ctx_pos**/**ctx_size**. I'm not really sure.

**Comment by dmcpriv** [comment]
I think mohitarora24 is correct. The path refers to the first child of each parent, not the first child of the entire set. In the examples quoted from the Microsoft page, it would be correct if the entire expression was enclosed in brackets before the index was applied, but there are no brackets in the original example. 

There are many xpath engines that can be used to test and confirm xpath logic if in doubt.

**Comment by maixuanhan** [comment]
Agreed!

**Comment by michalvasko** [comment]
Hi,
after verifying with some online tools it really seems you are correct, so I will fix it.

Regards,
Michal
