### ISSUE TITLE
Issue with "and" in predicates.

### ISSUE THREAD

**Issue by mohitarora24** [CESNET/libyang#336]
Hi there,

Continuing with similar tests in #335 , I found another issue:

Consider following XML:
```xml
<top>
    <alist>
        <key1>1</key1>
        <attr1>Sad</attr1>
        <attr2>Panda</attr2>
        <blist>
            <key2>1</key2>
            <leaf2/>
        </blist>
        <blist>
            <key2>2</key2>
            <leaf2/>
        </blist>
    </alist>
    <alist>
        <key1>2</key1>
        <attr1>Cunning</attr1>
        <attr2>Fox</attr2>
        <blist>
            <key2>1</key2>
            <leaf2/>
        </blist>
        <blist>
            <key2>2</key2>
            <leaf2/>
        </blist>
    </alist>
        <alist>
        <key1>3</key1>
        <attr1>Sad</attr1>
        <attr2>Panda</attr2>
        <blist>
            <key2>1</key2>
            <leaf2/>
        </blist>
        <blist>
            <key2>2</key2>
            <leaf2/>
        </blist>
    </alist>
    <alist>
        <key1>4</key1>
        <attr1>Cunning</attr1>
        <attr2>Fox</attr2>
        <blist>
            <key2>1</key2>
            <leaf2/>
        </blist>
        <blist>
            <key2>2</key2>
            <leaf2/>
        </blist>
    </alist>
</top>
```

and the filter:
`/top/alist[blist[key2='1'] and attr1="Sad"]/attr2`

This should result in two nodes:
```xml
<top>
    <alist>
        <key1>1</key1>
        <attr2>Panda</attr2>
    </alist>
    <alist>
        <key1>3</key1>
        <attr2>Panda</attr2>
    </alist>
</top>
```

**But the result after the filter is same as the input.**

- While processing the predicate `[blist[key2='1'] and attr1="Sad"]` in **eval_predicate()** it searches for the ending bracket position.
The for loop used: `for (brack2_exp = orig_exp; exp->tokens[brack2_exp] != LYXP_TOKEN_BRACK2; ++brack2_exp);` ends at the inner closing bracket `]` not the one at the end.
This way it loses to make predicate backup of all the _repeats_ in the expression. In this case _repeat_ for `attr1` is lost. So it does not evaluate `="Sad"` second time onward it just checks for presence of `attr1` and not the equality operation.

- In **eval_and_expr()**, the code applies the first predicate `blist[key2='1']` to the set by calling:
`ret = eval_equality_expr(exp, exp_idx, cur_node, local_mod, set, options);`,
but then loses all the filtered set by converting it to boolean:
`lyxp_set_cast(set, LYXP_SET_BOOLEAN, cur_node, local_mod, options);`
Seems as if it is just verifying the condition and does not care about filtered output as a result of it.

- It does not process `/attr2` at the end of filter at all. Returns after processing the predicate incompletely.
At the end of initial **eval_expr()** in **lyxp_eval()**, `*exp_idx` is not at the end of the expression. It is not checked either. Do not know if it is a bug or otherwise.

PS: My XPath filter may seem weird, but my final query is part of union `|` with some other queries.

Regards.

**Comment by michalvasko** [comment]
Hi,
I believe it should be fixed, but I am not completely sure because I encountered different problems with this example than you. So, please update the library and try it again, get back if you still see a problem, best with an easily-reproducible example.

Regards,
Michal

**Comment by mohitarora24** [comment]
Thanks. Out of the 3 points listed - I guess I was wrong about the 2nd point.

After your fix for the 1st point in https://github.com/CESNET/libyang/commit/fff6098f2bb46ee18561ffe2de016669921b6a54, it seems 3rd was also a repercussion of the same and is also solved. I should have tested this easy fix myself :(. Did not know this would solve all the problems...

Checking using yanglint (libyang 0.13.21), the same example seems to be working fine now. Tested the patch with my code and it's working fine there too.
