### ISSUE TITLE
Help request: swig python bindings

### ISSUE THREAD

**Issue by iwanb** [CESNET/libyang#338]
I started writing [swig python bindings](https://github.com/iwanb/libyang/tree/devel/swig/python) but I am not familiar with Swig and if I continue this way I will need to write a lot of boilerplate code.
I wrote a very simple swig .i file and then made Python classes to wrap the swig API.

Do you see a better way to do it?

I would like to use libyang to load and generate schema aware XML, which would be the base for a configuration API.
I am also checking other libraries like pyang, pyangbind and ydk (Yang development kit by Cisco), but I prefer your approach of having the compiled schema in memory and linking the data to that schema.

**Comment by rkrejci** [comment]
Hi, check https://github.com/sartura/libyang/tree/cpp/swig/python3 - still work in progress, but it should be usable soon and merged into libyang devel.

@mislavn

**Comment by mislavn** [comment]
Hi @iwanb,

I started working on the libyang python bindings, I have done the sysrepo: C++, Lua5.x, Python2, Python3 and Java bindings.

My approach is to make C++ bindings with which I will make Python bindings, that way it is easier to make language bindings for multiple languages with minimal SWIG intervention. That has multiple advantages.

Currently all of my changes are at:
https://github.com/sartura/libyang/tree/cpp/swig

By the end of the week I will have support for the basic API.

Regards,
Mislav

**Comment by iwanb** [comment]
Hi,
Nice! I hadn't seen that repo, let me know if I can help.

Thank you
