### ISSUE TITLE
lys_child does not work with leaf node

### ISSUE THREAD

**Issue by chengdingshan** [CESNET/libyang#341]
I suggest add something like : 

if (node->nodetype == LYS_LEAF || node->nodetype == LYS_LEAFLIST) {
        return NULL;
}

**Comment by rkrejci** [comment]
`lys_child()` is not a public function, why do you want to change it?

**Comment by chengdingshan** [comment]
okey, in fact I called API lys_getnext(NULL, parent, module, 0) to get the first child of some node and get coredump, then I check the code of lys_getnext, and I think the lys_child should be fixed
