### ISSUE TITLE
lyd_validate_value() uint64 negative values

### ISSUE THREAD

**Issue by lajdzsi** [CESNET/libyang#345]
the function validates negative values up until -18446744073709551615, which is the highest positive value possible, times -1.
It possibly disregards the '-' symbol.

**Comment by lajdzsi** [comment]
The problem is still present, but I've noticed, that if I put a range restriction on uint64, it at least differentiates between positive and negative numbers:

libyang[0]: Value "-10" does not satisfy the constraint "10..20" (range, length, or pattern).

**Comment by maixuanhan** [comment]
have you checked the actual output of the parse function? I doubt it works like C/C++

**Comment by lajdzsi** [comment]
You mean this? 
 if (!lyp_parse_value(&sleaf->type, &leaf.value_str, NULL, &leaf, NULL, 0, 0)) {
            return EXIT_FAILURE;
        }

(This is from  lyd_validate_value() , found in tree_data.c.)

**Comment by maixuanhan** [comment]
No. I would recommend you use `lyd_new_leaf()` function as it is the old way to validate a node and it is a public API. The code will looks like

```C
/* not tested yet */
struct lyd_node_leaf_list* someLeaf = (struct lyd_node_leaf_list*)lyd_new_leaf(parent, module, name, val_str);

if (someLeaf)
{
    printf("OUTPUT: %lu \n", someLeaf->value.uint64);
}
```

**Comment by lajdzsi** [comment]
I think we misunderstand each other. My point was, that the new function works fine most of the time, but I've found this issue, so I just reported it, hoping that someone will know what causes this, and how it can be fixed, so that later it can be part of the new release.

Anyway, thanks for the suggestion, I will consider using lyd_new_leaf() in the future.
