### ISSUE TITLE
string pattern "invert-match" modifier - parsing failure

### ISSUE THREAD

**Issue by lajdzsi** [CESNET/libyang#346]
I've tried to validate strings, using lyd_validate_value(), and in my schema module I've used
`type string
{
pattern '[0-9]*'
{
modifier invert-match; 
} 
}` 
to define my own type with typedef, and a leaf of my newly defined type, but the function returns with:

`libyang[0]: Invalid keyword "modifier".
libyang[0]: Module "datatypes" parsing failed.
Segmentation fault`

I've basically used the syntax seen in the examples of https://tools.ietf.org/html/rfc7950#section-9.4.5
so I presume it's a problem from the parser, called by lyd_validate_value()

**Comment by rkrejci** [comment]
Hi, please provide the complete input file causing the error. Did you used the yanglint(1)?

**Comment by lajdzsi** [comment]
I parsed in a schema like this, with lys_parse_mem() :
```
module datatypes
{
namespace "ns:yang:datatypes";
prefix dtypes;
typedef my_type 
{ 
type string
{
length "1..max"; 
pattern '[0-9]*'
{ 
modifier invert-match;
} 
pattern '[a-f]*' ;
} 

leaf my_leaf
{
type my_type;
}
}
```
and then used lyd_validate_value(). 
That's it. I haven't used yanglint for this, I wanted to try the function by itself.

**Comment by rkrejci** [comment]
The problem seems to be in the schema - `invert-match` is feature of YANG 1.1 so you have to add `yang-version` statement with value `1.1` into your schema. 
The `lys_parse_mem()` should fail and provide appropriate error message.

**Comment by lajdzsi** [comment]
Yeah, that solved it. Thank you, my bad.
