### ISSUE TITLE
hexadecimal validation failure (lyd_validate_value())

### ISSUE THREAD

**Issue by lajdzsi** [CESNET/libyang#347]
I've checked the examples from https://tools.ietf.org/html/rfc7950#section-9.2.1 to see if **lyd_validate_value()** validates them. The octal numbers check out, but **hexadecimals dont,** they return EXIT_FAILURE with the following error messages like this:
libyang[0]: Invalid value "0xf00f" in "leaf_name" element. (path: /module_name:leaf_name)

**Comment by maixuanhan** [comment]
I think the hexa and octa are only allowed within yang definition itself. The document says clearly that 

>   In the XML encoding, an
>   integer is always interpreted as a decimal number, and leading zeros
>   are allowed.

**Comment by lajdzsi** [comment]
The same document also gives these examples:

> 0xf00f                      // legal positive hexadecimal value
> -0xf                        // legal negative hexadecimal value

So hexadecimal values should be allowed.

**Comment by rkrejci** [comment]
hexadecimal and octal numbers are not allowed for `lyd_calidate_value()`. The function is intended to check values for data, so the extension of the lexical representation for schemas do not apply here.

The reason you were able to validate "octal" number is that '052' is actually interpretted as decimal number with leading zeros, which is allowed in data. You can check it with the value '09' which is invalid octal number, but lyd_validate_value() should succeed.

To make this more clear, I have updated description of the 'lyd_validate_value()'
