### ISSUE TITLE
Question: Accessing the type of a leaf via the schema

### ISSUE THREAD

**Issue by lajdzsi** [CESNET/libyang#348]
I want to access the base of a lys_type* to get the type of a leaf in my schema.
I know that **lyd_leaf_type()** would be the standard function for that, but I want to avoid using data trees (the system I later wish to use it for will not have xml or json data) , and a **lyd_node_leaf_list**  parameter is needed for lyd_leaf_type(). 
Is there any way to get the type of a leaf from the yang schema without typedefs? (I noticed, that through the module's tpdf field it can be reached, but I just want the type of a simple leaf, with a base type.)

Thanks in advance.

**Comment by rkrejci** [comment]
Not sure if that is what you want, but you can get base type as `lys_node_leaf->type.base`. The problem with this item is in case of union, because to get the correct type you need the data value.

**Comment by lajdzsi** [comment]
That helped, thanks.
