### ISSUE TITLE
Require data validate callback in extension plugin

### ISSUE THREAD

**Issue by fanchanghu** [CESNET/libyang#349]
Hi,
I have a problem when using extension plugin, I defined a extension `ex:inst-path` which is used to restrict the nodes that are referred by type `instance-identifier`, for example:
```
leaf f1{
  type instance-identifier{
    ex:inst-path "/A/B/C";
  }
}
```
For validating the data tree according to the value of `ex:inst-path`, I hope libyang can support some callback funciton in the extension plugin, which is called when `lyd_validate` is called.

**Comment by rkrejci** [comment]
Good point, @PavolVican is currently working on some changes regarding the extensions and this could be another feature.
