### ISSUE TITLE
LY_TREE_DFS_*  "typeof" not declared

### ISSUE THREAD

**Issue by lajdzsi** [CESNET/libyang#350]
I'm using the 0.13.43 first release version, and I have the following function:

```
void myDFS(const struct lys_module* m)
{
	struct lys_node *start, *next, *elem;
	start = m->data;
	
	LY_TREE_DFS_BEGIN(start, next, elem)
	{
		printf("actual: %s\n", elem->name);
		
		LY_TREE_DFS_END(start, next, elem);
	}
	
}
```

m is my schema module, I just want to iterate through every schema node in it, and print out their names. The documentation said, that this macro can iterate through any tree, be it schema or data tree, the only prerequisite is that all three of the parameters need to be of the same type.

Is it some bug, or am I doing something wrong? I get the following error messages:

> main.cc: In function 'void myDFS(const lys_module*)':
> main.cc:921:3: error: 'typeof' was not declared in this scope
> main.cc:921:3: error: 'typeof' was not declared in this scope
> main.cc:921:3: error: 'typeof' was not declared in this scope

**Comment by michalvasko** [comment]
Hi,
what platform are you compiling on? Quick search on the web revealed that on certain embedded platforms there is no macro `typeof()` but `__typeof__()` instead.

Regards,
Michal

**Comment by lajdzsi** [comment]
It's a linux server. What kind of info do you need exactly?

**Comment by michalvasko** [comment]
Could you maybe post the output of `cmake` having a clean repository? That should contain some basic compiler info that may help.

Regards,
Michal

**Comment by lajdzsi** [comment]
Thanks. Hope this helps:
> The system is: Linux - 2.6.32-642.11.1.el6.x86_64 - x86_64
> Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
> Compiler: /usr/bin/cc

**Comment by michalvasko** [comment]
Hi,
that did not help too much, can you please download a clean *libyang* repository, execute
```
mkdir build
cd build
cmake ..
```
and post the output of that *cmake* command please?

Regards,
Michal

**Comment by lajdzsi** [comment]
Okay, sorry - I misunderstood first.
Here it is:

> -- The C compiler identification is GNU 4.4.7
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Found FLEX: /usr/bin/flex (found version "2.5.35")
> -- Found BISON: /usr/bin/bison (found version "2.4.1")
> CMake Warning at CMakeLists.txt:90 (message):
>   Missing tools (devscripts, debhelper package) for building deb package.
> 
>   You won't be able to generate deb package from source code.
> 
>   Compiling libyang should still works fine.
> 
> 
> -- Looking for include file pthread.h
> -- Looking for include file pthread.h - found
> -- Looking for pthread_create
> -- Looking for pthread_create - not found
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE
> -- Found PCRE: /usr/lib64/libpcre.so
> -- Found PkgConfig: /usr/bin/pkg-config (found version "0.23")
> CMake Warning at CMakeLists.txt:220 (message):
>   pkg-config will not detect the new package after installation, adjust
>   PKG_CONFIG_PATH using "export
>   PKG_CONFIG_PATH=${PKG_CONFIG_PATH}:/home/../lib64/pkgconfig"                                                                                                                                                             .
> 
> 
> -- Found Doxygen: /usr/bin/doxygen (found version "1.6.1")
> -- Could NOT find CMocka (missing:  CMOCKA_LIBRARIES CMOCKA_INCLUDE_DIR) (Requir                                                                                                                                                             ed is at least version "1.0.0")
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/../

**Comment by maixuanhan** [comment]
I faced the same and learned that `typeof` is not a standard C/C++ operator. I have to alias the operator to `__typeof__` before including any libyang headers.

https://gcc.gnu.org/onlinedocs/gcc/Typeof.html

**Comment by lajdzsi** [comment]
Yep, thanks, that fixed it.

**Comment by rkrejci** [comment]
Thanks for the hint, @maixuanhan. The alias shouldn't be necessary now.
