### ISSUE TITLE
config false flag 

### ISSUE THREAD

**Issue by lajdzsi** [CESNET/libyang#353]
I'm using the version 0.13.43 and I wrote the following simple function to check whether or not a leaf is "config false".

```
bool isConfig(struct lys_node_leaf* temp)
{
	printf("FLAG: %x \n", temp->flags);
	if(temp->flags == LYS_CONFIG_R) return false;
	else return true;
}
```
My leaf I wanted to check it on:
```
	leaf noConf
	{
		type uint32;
		config false;
	}
```

Since config false has been set in the yang schema, the flag should be LYS_CONFIG_R , so  0x02, but my function prints this:
FLAG: 6
But it should be 2, why is it like this?

**Comment by jktjkt** [comment]
These flags can be OR-ed together. You're getting `6` which is a result of `(LYS_CONFIG_R | LYS_CONFIG_SET`).

`LYS_CONFIG_SET`'s documentation says that the value has been set explicitly, i.e., it's not just a default value.

You might want to check `temp->flags & LYS_CONFIG_MASK`.

**Comment by lajdzsi** [comment]
Alright, thank you for the quick reply.
