### ISSUE TITLE
ly_ctx_new: add support for a list of directories in "search_dir" parameter

### ISSUE THREAD

**Issue by igortern** [CESNET/libyang#355]
Hi,

I'd like to contribute an enhancement in ly_ctx_new, to add support for a  list of search directories. It is especially useful for sysrepo[ctl] when it needs to resolve referenced models, whereas all models are in multiple directories (e.g., IANA, IETF, BBF, etc.).
If this enhancement is acceptable in general, could you advice how I can get permissions for creating a  branch & pull request?

Kind Regards,
Igor Ternovsky
Broadcom Limited

**Comment by rkrejci** [comment]
Hi, you don't need a permission to create branch and pull request. But I don't understand your request - libyang should support multiple searchdirs via `ly_ctx_set_searchdir()` so you can set as many search directories as you wish (which you can verify via `ly_ctx_get_searchdirs()`).

**Comment by igortern** [comment]
Hi it is a convenience feature. It makes ly_ctx_new() parse ':' delimited list of directories (like in PATH) and call ly_ctx_set_searchdir() for each of them. IN result, sysrepo starts supporting multiple search directories out of the box.

**Comment by igortern** [comment]
Regarding permission to push branch to github: apparently it is required. See log below. I used the same username & password that work to login to github.

igort@igort-vb-mint:~/OpenFlow/netconf/libyang/devel$ git push origin ly_ctx_new
Username for 'https://github.com': igortern
Password for 'https://igortern@github.com': 
remote: Permission to CESNET/libyang.git denied to igortern.
fatal: unable to access 'https://github.com/CESNET/libyang.git/': The requested URL returned error: 403

**Comment by rkrejci** [comment]
Ok, the PATH format with semicolons is acceptable, I just want to avoid API change.

Regarding the permission - you are not going to get permission to commit/push directly into our repository. The accepted way is to create your cloned repository, do the changes there and create pull request.

**Comment by igortern** [comment]
Ok,, thanks. Created pull request [https://github.com/igortern/libyang/pull/1/commits](url)

**Comment by rkrejci** [comment]
Please follow the docs - https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by rkrejci** [comment]
Merged based on pull request #357
