### ISSUE TITLE
should the XPATH predicates order be the same as the key node order defined in yang file?

### ISSUE THREAD

**Issue by ustcpxy** [CESNET/libyang#360]
a sample yang file like below:
model {
  container {
    list {
      key "key1  key2";
      leaf key1 {
      }
      leaf key2 {
      }
    }

  }
...
}
config-xml has an instance-identifier node, suppose its value is: /model:container/list[key1='a'][key2='b'] 
doing edit-config with the config-xml can be successful. 

but when I change the value (just swap the key order) to : /model:container/list[key2='b'][key1='a'], then do edit-config with the config-xml, libyang would say the "Required instance of "/model:container/list[key2='b'][key1='a']" does not exists.

should the XPATH predicates order be the same as the key node order defined in yang file?

**Comment by michalvasko** [comment]
Hi,
you are correct, we had this restriction even though it was not specified anywhere, should be fixed now.

Regards,
Michal

**Comment by ustcpxy** [comment]
Hi Michal, 
Got it. Thanks.
