### ISSUE TITLE
reslove instid predicate failed if the list has two keys

### ISSUE THREAD

**Issue by ustcpxy** [CESNET/libyang#363]
libyang version: 0.13.67

a sample yang file like below:
```yang
model {
container {
list {
key "key1 key2";
leaf key1 {
}
leaf key2 {
}
}

}
...
}
```
config-xml has an instance-identifier node, suppose its value is: /model:container/list[key1='a'][key2='b']
when doing edit-config with the config-xml, the netconf client would receive an error reply.
the error message is: Unexpected characters(s)  '['  ([key2='b']).

please note: the same case works well with libyang version 0.13.43

**Comment by michalvasko** [comment]
Hi,
I suppose you have used *sysrepo* for the `edit-config` operation, so please, next time open the issue in *sysrepo*.

I have tried your use case with libyang version 0.13.68 (which has only a change in `yanglint`) and it worked as expected so I must assume you have some invalid installation of something (likely an old version of some of the libraries or applications is used). Please, try to properly reinstall it all and try this use-case again. But note that you cannot use `/model:container/list[key1='a'][key2='b']` in an XML edit-config (you could if you used JSON). It is specified that `instance-identifiers` must have a prefix for all the node names so the correct value would be `/mod:container/mod:list[mod:key1='a'][mod:key2='b']` with `mod` being defined as an XML prefix of `model`. Still, when I tried your value, the error was different.

Regards,
Michal

**Comment by ustcpxy** [comment]
OK. Thanks.
it seems I use the error value. it works as expected now.

**Comment by ustcpxy** [comment]
Hi Michal,
I find the reproduction condition of the issue.
I just use yanglint to validation the data config-xml.
yanglint is built with libyang version 0.13.67.
test steps:
1. run yanglint
2. add test-instid.yang
3. data -t config -s config-instid.xml

results:
libyang[0]: Unexpected character(s) '[' ([key2="b"]). (path: /test-instid:cont1/instid)
Failed to parse data.

please note:
if I remove the second list1 instance in config-instid.xml, there is no error. parse data would be fine. 

attached is the test files (include yang file and config data xml )

[test-instid.tar.gz](https://github.com/CESNET/libyang/files/1339423/test-instid.tar.gz)

**Comment by ustcpxy** [comment]
my test shows that: if there are more than one list instance in data tree, the related instance-identifier node would be parsed failed.

**Comment by michalvasko** [comment]
Hi,
thanks for the nice example, it should be fixed, minor issue.

Regards,
Michal
