### ISSUE TITLE
problems with refine statement

### ISSUE THREAD

**Issue by mislavn** [CESNET/libyang#364]
Hi,

I have a problem with a refine statement (psid-offset) in the YANG model [ietf-softwire](https://github.com/Igalia/snabb/blob/lwaftr/src/lib/yang/ietf-softwire.yang).

The relevant part is:
```
    container port-set {
      description
        "For Lightweight 4over6, the default value
        of offset should be 0, to configure one contiguous
        port range.";
      uses port-set {
        refine psid-offset {
          default "0";
        }
      }
    }
```
```
  grouping port-set {
    description
      "Use the PSID algorithm to represent a range of transport layer
      ports.";
    leaf psid-offset {
      type uint8 {
        range 0..16;
      }
      mandatory true;
      description
        "The number of offset bits. In Lightweight 4over6, the default
        value is 0 for assigning one contiguous port range. In MAP-E/T,
        the default value is 6, which excludes system ports by default
        and assigns distributed port ranges. If the this parameter is
        larger than 0, the value of offset MUST be greater than 0.";
    }
```

Libyang complains about:
```
root@b26ca94cfb26:/# sysrepoctl -i -g /opt/snabb/src/lib/yang/ietf-softwire.yang 
Installing a new module from file '/opt/snabb/src/lib/yang/ietf-softwire.yang'...
[ERR] libyang: Invalid keyword "default" as a child to "refine".
[ERR] libyang: The "mandatory" statement is forbidden on leafs with the "default" statement.
[ERR] libyang: Module "ietf-softwire" parsing failed.
Error: Unable to load the module by libyang.
Install operation failed.
```

The issue is easy to resolve, I can just remove the default statement in the refine, but if I remove the mandatory statement libyang compiles it although it shouldn't based on [7.12.2.  The refine Statement](https://tools.ietf.org/html/rfc6020#section-7.12.1).

>    *  A leaf or choice node may get a default value, or a new default
>       value if it already had one.

Is this correct or am I missing something?

**Comment by rkrejci** [comment]
Hi, why it shouldn't pass when you remove `mandatory`? The problem is that you cannot have both, `mandatory` and `default` on the same node.

**Comment by mislavn** [comment]
> Hi, why it shouldn't pass when you remove mandatory? The problem is that you cannot have both, mandatory and default on the same node.

I'm aware of the reason why it does not compile and that is easy to fix but I think it should not compile when the mandatory statement is removed because according to the YANG documentation a refine leaf can have a default statement **only** if it already had one [7.12.2.  The refine Statement](https://tools.ietf.org/html/rfc6020#section-7.12.1).

**Comment by michalvasko** [comment]
Well, based on the text you cited, "node may get a default value, or a new default value if it already had one". So no, it does not have to have one first, right?

**Comment by mislavn** [comment]
OK, I wasn't sure how to interpret that part. I taught a refined leaf can have the same or new default value based on the original leaf but I wasn't sure.
