### ISSUE TITLE
lys_xpath_atomize works unexpectedly

### ISSUE THREAD

**Issue by fanchanghu** [CESNET/libyang#366]
Hi,
it seems `lys_xpath_atomize` can not work in latest devel branch, below is my test code:
```c
int main(void)
{
    struct ly_ctx *ly_ctx = ly_ctx_new(NULL, 0);

    const struct lys_module *module = lys_parse_path(ly_ctx, "a.yang", LYS_IN_YANG);
    printf("load a %s\n", module ? "success" : "failure");
    const struct lys_module *module2 = lys_parse_path(ly_ctx, "b.yang", LYS_IN_YANG);
    printf("load b %s\n", module2 ? "success" : "failure");

    struct ly_set *set = lys_xpath_atomize(module->data, LYXP_NODE_ELEM,
            "/a:A/A1/b:B[k1=1]/C[k2=1]", 0);
    assert(set);
    assert(set->number);
    printf("count: %d, last: %s\n", set->number, set->set.s[set->number - 1]->name);
    ly_set_free(set);

    ly_ctx_destroy(ly_ctx, NULL);
    return 0;
}
```
the output is 
```
load a success
load b success
exe: /root/svn/nfoam/libyang/src/xpath.c:6847: eval_predicate: Assertion `exp->tokens[*exp_idx] == LYXP_TOKEN_BRACK2' failed.
Aborted
```

[a.yang.txt](https://github.com/CESNET/libyang/files/1386078/a.yang.txt)
[b.yang.txt](https://github.com/CESNET/libyang/files/1386079/b.yang.txt)

**Comment by michalvasko** [comment]
Hi,
it should no longer fail with assert, but your expression is not correct. After the last XPath changes (they were bugfixes, actually) all nodes from different modules than the initial node must have a prefix. The correct expression would be `/a:A/A1/b:B[b:k1=1]/b:C[b:k2=1]`.

Regards,
Michal

**Comment by fanchanghu** [comment]
Hi,
Oh, it's also the documentation that made me thought it should use data path here. In fact, I got this issue from sysrepo, which also used `lys_xpath_atomize` with data path in JSON format. Have you already notified sysrepo guys about this change?

**Comment by fanchanghu** [comment]
I just want to tell sysrepo also used `lys_xpath_atomize` with data path like `/a:A/A1/b:B[k1=1]/C[k2=1]`. :)

**Comment by michalvasko** [comment]
Hi,
I was hoping for a more specific report, but I think I found the place where data paths were used instead schema ones and the pull request should fix it (recent `devel` of libyang is required). Please, try it again and let me know whether it works fine now or not, thanks.

Regards,
Michal

**Comment by fanchanghu** [comment]
Hi,
I have got latest libyang and your patch(sysrepo/sysrepo#964), and it fixed my issue. Thanks for your help.
