### ISSUE TITLE
how to use lyd_new_output for action

### ISSUE THREAD

**Issue by ostack** [CESNET/libyang#375]
struct lyd_node *lyd_new_output(struct lyd_node *parent, const struct lys_module *module, const char *name);
consider modules like below,there three questions when create "querydata" out node.
1. which lys_module should i use for the second input parameter? "MainModule" or "AugModule"?
2. which name should i use for the third input parameter? "querydata" or "Level2Con" or other?
3. I have use MainModule for the second para,"querydata" and "Level2Con" for the third ,but both of them do not work,the return value is null,but ly_errno is 0 ,is this a bug?
 

```yang
module MainModule {
    yang-version 1.1;
    namespace "urn:Main";
    prefix Main;
    container Level1Con {
        container Level2Con { 
		    leaf inA {type int8;}
	    }
    }
}


module AugModule {
    yang-version 1.1;
    namespace "urn:aug";
   import MainModule{prefix Main;}
    prefix aug;
    augment "/Main:Level1Con/Main:Level2Con"
    container Level1Con {
        container Level2Con {
            action querydata {
                input {
                    container inContainter {
                        leaf outA {type int8;}
                    }
                }
                output {
                    list outList {
                        key "name";
                        leaf name {type string;}
                        container outCascade {
                            leaf outA { type int8;}
                        }
                    }
                }
            }
		}	
    }
}
```

**Comment by michalvasko** [comment]
Hi,

 1. Depends on which node you are creating, use the module of the node (like the documentation says).
 2. Depends on the node you want to create, I cannot make it more clear.
 3. I will fix it so that `ly_errno` is always set if the function fails, but I think the problem is something else. When creating action data tree, the tree must include the whole path of parents from top until the action. That is why, in general, it is preferable to use `lyd_new_path` instead of all the other `lyd_new_*` functions (albeit it is a bit less efficient). That function creates all the parents if the do not exist so you can create the action node in one call
```C
lyd_new_path(NULL, ctx, "/MainModule:Level1Con/Level2Con/Level1Con/Level2Con/querydata", NULL, 0, 0);
```
When creating output parameters, do not forget to use the correct flag. Also, you can create the action container this way and then use other `lyd_new_*` functions to add the children nodes, it can be combined.

Regards,
Michal

**Comment by ostack** [comment]
just consider we  want 
 to create the node "/MainModule:Level1Con/Level2Con/AugModule:Level1Con/Level2Con/querydata" 
the second parameter should be "AugModule" and the third parameter should be "querydata"?

i don not think only module name and node name cat locate the action node uniquely ,as the action  node querydata can be defined both under AugModule's "Level1Con" and "Level2Con", like the model definition  below:

`module AugModule {
    yang-version 1.1;
    namespace "urn:aug";
   import MainModule{prefix Main;}
    prefix aug;
    augment "/Main:Level1Con/Main:Level2Con"
    container Level1Con {
	    action querydata {
            input {
                container inContainter {
                    leaf outA {type int8;}
                }
            }
            output {
                list outList {
                    key "name";
                    leaf name {type string;}
                    container outCascade {
                        leaf outA { type int8;}
                    }
                }
            }
        }

        container Level2Con {
            action querydata {
                input {
                    container inContainter {
                        leaf outA {type int8;}
                    }
                }
                output {
                    list outList {
                        key "name";
                        leaf name {type string;}
                        container outCascade {
                            leaf outA { type int8;}
                        }
                    }
                }
            }
		}	
    }
}`

**Comment by michalvasko** [comment]
Hi,
I take it you are talking about the function `lyd_new_output()`. These functions (from the older API, not `lyd_new_path()`) identify the node based on 3 parameters: **module name**, **node name**, and **parent**. If you do not set the parent, it is expected to be a top-level node.

Regards,
Michal
