### ISSUE TITLE
issue about lyd_parse_mem when parse action output

### ISSUE THREAD

**Issue by ostack** [CESNET/libyang#376]
when parse out put xpath:/ListLeaf:ListLeaf/setdata/interfaces/ifEntry[ifIndex='2'],
and  use out put json: 
```json
 {
	"interfaces": {
		"ifEntryOut": [{
			"ifDescr": "thisisone",
			"ifMtu": 2
		}]
	}
}
```
```
libyang  report errCode:5,errMsg:Unknown element "ifEntryOut".
```
 
 The module like below:
 ```yang
 module ListLeaf {
	namespace "http://example.net/list/leaf";
	prefix ListLeaf;
	yang-version "1.1";
	container ListLeaf{
    	leaf id{type uint32;}
    	action setdata{
    		input{
    			container interfaces {
    				list ifEntry {
    					key ifIndex;
    					leaf ifIndex {type uint32;}
    				}
    			}
    		}
    		output{
    			container interfaces {
    				list ifEntry {
    					key ifDescr;
    					leaf ifDescr {type string;}
    					leaf ifMtu {type int32;}
    				}
    			}
    		}
    	}
    }
}
```

**Comment by michalvasko** [comment]
Hi,
how exactly did you call `lyd_parse_mem()`, with what parameters? Carefully read the documentation, when parsing a `LYD_OPT_RPCREPLY` (both RPC and action reply - output) 2 variable arguments are expected and the first one is mandatory (cannot be NULL).

Regards,
Michal

**Comment by ostack** [comment]
i use the function like this:
lyd_node *root = lyd_parse_mem(lyCtx, jsonData, LYD_JSON, LYD_OPT_RPCREPLY,  inputNode, NULL);

**Comment by michalvasko** [comment]
Hi,
I have noticed just now, the output is perfectly fine, there is no node `ifEntryOut` in the schema. Fix that and get back if it still does not work.

Regards,
Michal
