### ISSUE TITLE
Container node validation is not proper

### ISSUE THREAD

**Issue by vikash-huawei** [CESNET/libyang#377]
[Docs.txt](https://github.com/CESNET/libyang/files/1453111/Docs.txt)

Data Model:
```yang
module yang-test {
    container test-container {
        list test-list 
        {    
              key "test-index test-key2";        
              leaf test-index 
              {
                      type uint32;
               }
               leaf test-key2 
               {
                    type string;
                }
           }
      }
}
```

RPC request and data model is attached in the file.
During parsing, container node should not have the any data.
But we have put data for the container node "test-container" as 122222222222222222222222222222222222222222222222222 ==> this is invalid, parsing should return error
But currently it is not returning error.
lyd_parse_xml should return error, as container should not have any text node. Please check.

**Comment by michalvasko** [comment]
Hi,
this is a feature, not a bug. The text element or any other unknown element is ignored by default. To change this behaviour use the `LYD_OPT_STRICT` flag.

Regards,
Michal

**Comment by vikash-huawei** [comment]
I have update the flag LYD_OPT_STRICT while parsing, but still lyd_parse_xml is not returning error.
I checked your  code there it seems that only when there are some attribute for the node, then you are returning error. But in my case container node does not have any attribute, so it is not returning error even if LYD_OPT_STRICT is set.

 /* process attributes */
    for (attr = xml->attr; attr; attr = attr->next) {        
        
        if (attr->type != LYXML_ATTR_STD) {
            continue;
        } else if (!attr->ns) {
            if ((*result)->schema->nodetype == LYS_ANYXML &&
                    ly_strequal((*result)->schema->name, "filter", 0) &&
                    (ly_strequal((*result)->schema->module->name, "ietf-netconf", 0) ||
                    ly_strequal((*result)->schema->module->name, "notifications", 0))) {
                /* NETCONF filter's attributes, which we implement as non-standard annotations,
                 * they are unqualified (no namespace), but we know that we have internally defined
                 * them in the ietf-netconf module */
                str = "urn:ietf:params:xml:ns:netconf:base:1.0";
                filterflag = 1;
            } else {
                /* garbage */
                goto attr_error;
            }
        } else {
            str = attr->ns->value;            
        }

        r = lyp_fill_attr(ctx, *result, str, NULL, attr->name, attr->value, xml, &dattr);
        if (r == -1) {
            goto error;
        } else if (r == 1) {
attr_error:
            if (options & LYD_OPT_STRICT) {
                LOGVAL(LYE_INMETA, LY_VLOG_LYD, *result, (attr->ns ? attr->ns->prefix : "<none>"), attr->name, attr->value);
                goto error;
            }

            LOGWRN("Unknown \"%s:%s\" metadata with value \"%s\", ignoring.",
                   (attr->ns ? attr->ns->prefix : "<none>"), attr->name, attr->value);
            continue;
        }

**Comment by rkrejci** [comment]
Hi, filter in `<get>` operation is defined as anyxml, so it can contain any XML document, it is out of the scope to validate its content in libyang until you process that anyxml node with some additional knowledge.

BTW, the content of the subtree filter in the provided RPC is wrong, there is no `yang-test` node in your schema. And even schema is not valid since it misses namespace and prefix statements.

Despite what I said, you are raid, that  there is some benevolence in having text data in empty container, I'm going to check what we can do with it. So far it fails only with the mixed content (so in your case if there would be a `test-list` node together with the text data.

**Comment by vikash-huawei** [comment]
<?xml version="1.0" encoding="utf-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="8">
  <get>
    <filter type="subtree">
      <yang-test xmlns="http://www.yang.com/netconf/vrp/-yang-test">
        <test-container>123334444444444444444444444444444444444444444</test-container>=> this is container node and the value is invalid here.
         </yang-test>
          </filter>
        </get>
      </rpc>

**Comment by rkrejci** [comment]
having test-container as grandchild of filter node is wrong, test-container is top-level node. yang-test node in your filter is nonsense, such a node does not exist.

Parser now checks for text data in lists, containers, notifications, rpcs and action nodes.

**Comment by vikash-huawei** [comment]
Fix is fine, but i am not able to get the correct element. Can you verify it once
$6 = (struct ly_err *) 0x81eb500
(gdb) p *(struct ly_err *) 0x81eb500
$7 = {no = LY_EVALID, code = LYVE_XML_INVAL, vlog_hide = 0 '\000', buf_used = 0 '\000', path_index = 982, errlist = 0x8208638, 
  msg = "Invalid node with text data.\000e-containers\".\000-or-any\".\000de \"/yang-test:yang-test/rfc6020-datatype/rfc6020-datatype-list/test-bits\".", '\000' <repeats 880 times>, 
  path = '\000' <repeats 941 times>, "yang-test:yang-test/rfc6020/yang-test/test-presence-container", apptag = '\000' <repeats 127 times>, 
  buf = "2\000tf-system:radius-pap", '\000' <repeats 918 times>, "/yang-test:yang-test/rfc6020-datatype/rfc6020-datatype-list/test-bits", bad_element = "\000est-presence-containers", '\000' <repeats 103 times>, 
  bad_attr = '\000' <repeats 127 times>}
(gdb) c
Continuing.
**msg should be "msg = "Invalid node with text data.test-presence-containers"
and bad_element should be same, but null character is present at the first bit.**

Output i am getting in rpc reply is
 <error-message xml:lang="en">Invalid node with text data.</error-message>

**Comment by michalvasko** [comment]
Hi,
what exactly is your use-case? I tried it in `yanglint` and it seems to work fine except the element is in `path`, not `bad_elem`. I do not consider that wrong, though.

Regards,
Michal

**Comment by vikash-huawei** [comment]
Hi,

**Comment by rkrejci** [comment]
`yang_vrp_lyerr_badelem' is not a libyang function, so we are not able to fix its output.
