### ISSUE TITLE
lyd_find_path returns nodes from different namespace

### ISSUE THREAD

**Issue by hanneskuettner** [CESNET/libyang#379]
When using `lyd_find_path(data, "/ietf-inet-types:*")` on the following data tree
```json
{
  "ietf-interfaces:interfaces": {
    "interface": [
      {
        "name": "eth0",
        "type": "iana-if-type:ethernetCsmacd"
      }
    ]
  }
}
```
the function returns a set of size one. 
I would expect it to return an empty set as the namespaces do not match at all. 
In fact the XPATH can contain any module name and the function still returns a set of size one.

I could not find any documentation regarding the expected behavior, but looking into the sysrepo source code and [documentation for XPATH](http://www.sysrepo.org/static/doc/html/xp_page.html) handling leads me to believe that the XPATH is valid and should return an empty set.

Is this a bug in libyang or am I misunderstanding the XPATH addressing?

**Comment by michalvasko** [comment]
Hi,
this kind of expressions were evaluated incorrectly, should be fixed now.

Regards,
Michal
