### ISSUE TITLE
lyd_find_path returning unexpected type of lyd_node*?

### ISSUE THREAD

**Issue by abhikeshav** [CESNET/libyang#388]
Hi,

Below is the XML data being used:
```xml
<ipv4-network xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-ipv4-io-oper">
    <interfaces xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-ipv4-ma-oper">
        <interface>
            <interface-name>Bundle-Ether10</interface-name>
            <vrfs>
                <vrf>
                    <vrf-name>default</vrf-name>
                    <detail>
                        <multi-acl>
                            <inbound><entry/></inbound> 
                            <inbound><entry/></inbound>
                            <inbound><entry/></inbound>
                            <inbound><entry/></inbound>
                        </multi-acl>
                    </detail>
                </vrf>
            </vrfs>
        </interface>
    </interfaces>
</ipv4-network>
```

Relevant yang models are : [1](https://github.com/YangModels/yang/blob/master/vendor/cisco/xr/631/Cisco-IOS-XR-ipv4-ma-oper-sub1.yang), [2](https://github.com/YangModels/yang/blob/master/vendor/cisco/xr/631/Cisco-IOS-XR-ipv4-ma-oper.yang), [3](https://github.com/YangModels/yang/blob/master/vendor/cisco/xr/631/Cisco-IOS-XR-ipv4-io-oper.yang)

Below is the test code:
```c
const char* xml = "<ipv4-network xmlns=\"http://cisco.com/ns/yang/Cisco-IOS-XR-ipv4-io-oper\"><interfaces xmlns=\"http://cisco.com/ns/yang/Cisco-IOS-XR-ipv4-ma-oper\"><interface><interface-name>Bundle-Ether10</interface-name><vrfs><vrf><vrf-name>default</vrf-name><detail><multi-acl><inbound><entry/></inbound> <inbound><entry/></inbound><inbound><entry/></inbound><inbound><entry/></inbound></multi-acl></detail></vrf></vrfs></interface></interfaces></ipv4-network>";

struct lyd_node *root =  lyd_parse_mem(ctx, xml, LYD_XML,  LYD_OPT_GET);   

 struct ly_set * set = lyd_find_path(root,"/Cisco-IOS-XR-ipv4-io-oper:ipv4-network/Cisco-IOS-XR-ipv4-ma-oper:interfaces/interface[interface-name='Bundle-Ether10']/vrfs/vrf[vrf-name='default']/detail/multi-acl/inbound");
 printf("number of results: %d\n",set->number);
 for(int i=0;i<set->number;i++)
 {
     printf("Name: %s, type: %s\n", set->set.d[i]->schema->name, set->set.d[i]->schema->nodetype==LYS_LIST?"LYS_LIST":"");
 }
```

Seeing the below output:
```
number of results: 4
Name: inbound, type: LYS_LIST
Name: inbound, type: LYS_LIST
Name: inbound, type: LYS_LIST
Name: inbound, type: LYS_LIST
```
Based on the above, it looks like the lyd_node* for `inbound` is a yang list of type `LYS_LIST `, but I was expecting `LYS_LEAFLIST` as, based on the yang model, it should be a leaf-list. See [here](https://github.com/YangModels/yang/blob/master/vendor/cisco/xr/631/Cisco-IOS-XR-ipv4-ma-oper-sub1.yang#L210).

In `yanglint`, the tree for the `Cisco-IOS-XR-ipv4-io-oper.yang` model looks like the below

```ssh
       +--ro Cisco-IOS-XR-ipv4-ma-oper:interfaces
          +--ro Cisco-IOS-XR-ipv4-ma-oper:interface* [interface-name]
             +--ro Cisco-IOS-XR-ipv4-ma-oper:vrfs
             |  +--ro Cisco-IOS-XR-ipv4-ma-oper:vrf* [vrf-name]
             |     +--ro Cisco-IOS-XR-ipv4-ma-oper:detail
...
             |     |  +--ro Cisco-IOS-XR-ipv4-ma-oper:multi-acl
             |     |  |  +--ro Cisco-IOS-XR-ipv4-ma-oper:inbound*                    Str
```
As seen above, "inbound" should be a leaf-list of typr "Str".

Any idea why this could be occurring?

**Comment by michalvasko** [comment]
Hi,
I think the problem may have been the values of the `inbound` leaf-list. However, I think this is no longer reproducible with the current libyang (both `devel` and `master`), there was a bugfix pushed a few days ago that also fixed this behavior.

Nevertheless, the problem now is likely the XML data you are using, `<entry/>` is not interpreted as a value but rather an XML child element of `<inbound>` (which is what probably confused libyang initially). You must encode such values properly according to XML specification, the value should be `&lt;entry/&gt;`.

Regards,
Michal

**Comment by abhikeshav** [comment]
Thanks for your reply. It looks like the nodetype is set to `LYS_LIST | LYS_LEAFLIST`. I should have been using the bitwise operator to check the value instead of the `==` operator.

Reason could be because there is another part of the schema tree with a similar path which is a list? See [here](https://github.com/YangModels/yang/blob/master/vendor/cisco/xr/631/Cisco-IOS-XR-ipv4-io-oper-sub2.yang#L192)

```xpath
module: Cisco-IOS-XR-ipv4-io-oper
    +--ro ipv4-network
       +--ro nodes
       |  +--ro node* [node-name]
       |     +--ro interface-data
       |     |  +--ro vrfs
       |     |  |  +--ro vrf* [vrf-name]
...
       |     |  |     +--ro details
       |     |  |     |  +--ro detail* [interface-name]
...
       |     |  |     |     +--ro multi-acl
       |     |  |     |     |  +--ro inbound*
       |     |  |     |     |  |  +--ro entry?   Str
```

**Comment by abhikeshav** [comment]
Reopening as I can reproduce on the `develop` branch

**Comment by michalvasko** [comment]
Hi,
you probably have not removed the previous versions of the library and they are still being used instead of the new ones, I am not able to reproduce this. I specifically looked at the nodetype and it was `LYS_LEAFLIST` for all the items in the set.

Regards,
Michal

**Comment by abhikeshav** [comment]
Thanks for your response @michalvasko ! Closing this for now
