### ISSUE TITLE
Cannot use negative number in must statement

### ISSUE THREAD

**Issue by iwanb** [CESNET/libyang#393]
This sample Yang is considered invalid:
```
module a {
  namespace "urn:a";
  prefix a_mod;

  container x {
    leaf bar-leaf {
      type int32;
    }
    leaf baz {
      type string;
      must "../bar-leaf = -1";
    }
  }
}
```

```
> yanglint a.yang 
err : Unexpected XPath token Operator(Math) (-1).
err : Invalid must restriction "../bar-leaf = -1" with context node "/a:x/baz". (/a:x/baz)
```
While the same must statement with 1 instead of -1 is considered valid.

I tried it with the latest revision from the dev branch.

**Comment by michalvasko** [comment]
Hi,
my recent optimizations were not completely finished, this unary minus was not handled properly, shoudl work now, thanks.

Regards,
Michal

**Comment by iwanb** [comment]
Great, thank you!
