### ISSUE TITLE
Exception happening while parsing deviation file

### ISSUE THREAD

**Issue by ghost** [CESNET/libyang#394]
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xf2e37b70 (LWP 86474)]
0xf7604185 in __strlen_sse2 () from /lib/libc.so.6
(gdb) bt
#0  0xf7604185 in __strlen_sse2 () from /lib/libc.so.6
#1  0xf2e95da2 in lydict_remove (ctx=0x81e50f0, value=0x656e2d66 <Address 0x656e2d66 out of bounds>) at dict.c:123
#2  0xf2f1b773 in lys_restr_free (ctx=0x81e50f0, restr=0x81e9240, private_destructor=0x0) at tree_schema.c:1321
#3  0xf2f1ba34 in lys_type_free (ctx=0x81e50f0, type=0x820b628, private_destructor=0x0) at tree_schema.c:1982
#4  0xf2f1a9e5 in lys_leaf_free (private_destructor=<optimized out>, leaf=<optimized out>, ctx=<optimized out>) at tree_schema.c:2183
#5  lys_node_free (node=0x820b5e8, private_destructor=0x0, shallow=1) at tree_schema.c:2434
#6  0xf2f1c6de in lys_deviation_free (private_destructor=<optimized out>, dev=<optimized out>, module=<optimized out>) at tree_schema.c:2321
#7  module_free_common (module=0x81fd510, private_destructor=0x0) at tree_schema.c:2668
#8  0xf2f1cdf2 in lys_free (module=0x81fd510, private_destructor=0x0, remove_from_ctx=1) at tree_schema.c:3430
#9  0xf2eda7d2 in yin_read_module_ (ctx=0x81e50f0, yin=0x8204548, revision=0x0, implement=1) at parser_yin.c:7089
#10 0xf2edd1b7 in yin_read_module (ctx=0x81e50f0, 
    data=0xf1ea4000 "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n\r\n<module xmlns=\"urn:ietf:params:xml:ns:yang:yin:1\" name=\"ietf-netconf-acm-deviations-cx\" xmlns:inet=\"urn:ietf:params:xml:ns:yang:ietf-netconf-acm-deviations-cx"..., revision=0x0, implement=1) at parser_yin.c:7106
#11 0xf2f21309 in lys_parse_mem_ (ctx=0x81e50f0, 
    data=0xf1ea4000 "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n\r\n<module xmlns=\"urn:ietf:params:xml:ns:yang:yin:1\" name=\"ietf-netconf-acm-deviations-cx\" xmlns:inet=\"urn:ietf:params:xml:ns:yang:ietf-netconf-acm-deviations-cx"..., format=LYS_IN_YIN, internal=1, implement=1) at tree_schema.c:961

Is it a valid issue..please check..

**Comment by michalvasko** [comment]
Hi,
you will need to provide the moduel that caused this or at least the part that caused this so I can reproduce it. Also, what libyang version did you use?

Regards,
Michal

**Comment by vikash-huawei** [comment]
I have defined one node like this:

**Comment by michalvasko** [comment]
Hi,
I have used this module
```xml
<?xml version="1.0" encoding="UTF-8"?>
<module name="dev"
        xmlns="urn:ietf:params:xml:ns:yang:yin:1">
    <namespace uri="urn:dev"/>
    <prefix value="d"/>
    <import module="ietf-netconf-acm">
        <prefix value="nacm"/>
    </import>
    <deviation target-node="/nacm:nacm/nacm:rule-list/nacm:name">
        <deviate value="replace">
            <type name="string">
                <length value="1..15"/>
            </type>
        </deviate>
    </deviation>
</module>
```
and did not find any problem so I will need your exact copy if I am to reproduce it. If it cannot be public, you can send it to me via email or try to isolate the problematic part.

Regards,
Michal
