### ISSUE TITLE
issue about lys_parent when the nodetype is LYS_AUGMENT

### ISSUE THREAD

**Issue by ustcpxy** [CESNET/libyang#396]
use API lys_parent can not get the node's parent if the nodetype is LYS_AUGMENT.

I think the lys_parent should handle the special case which the given node's type is LYS_AUGMENT.

below is my gdb test log. please refer it. 
713         LYS_INFORMAT yang_format = LYS_IN_YANG;
(gdb) n
720         char *yang_file = TESTS_DIR"/api/files/b.yang";
(gdb) 
722         module = lys_parse_path(ctx, yang_file, yang_format);
(gdb) 
723         if (!module) {
(gdb) 
728         set = lys_find_path(module, NULL, "/b:x/bar-y");
(gdb) 
729         assert_ptr_not_equal(set, NULL);
(gdb) 
730         node = set->set.s[0];
(gdb) 
731         ly_set_free(set);
(gdb) 
733         node = node->parent;
(gdb) p *node
$1 = {name = 0x5555557761c0 "bar-y", dsc = 0x0, ref = 0x0, flags = 1, ext_size = 0 '\000', iffeature_size = 0 '\000', 
  padding = "\000\000\000", ext = 0x0, iffeature = 0x0, module = 0x55555577eed0, nodetype = LYS_CONTAINER, 
  parent = 0x555555775df0, child = 0x0, next = 0x0, prev = 0x555555774540, priv = 0x0}
(gdb) p *node->parent
$2 = {name = 0x555555776140 "/x", dsc = 0x0, ref = 0x0, flags = 0, ext_size = 0 '\000', iffeature_size = 1 '\001', 
  padding = "\000\000\000", ext = 0x0, iffeature = 0x555555774d20, module = 0x55555577eed0, nodetype = LYS_AUGMENT, 
  parent = 0x0, child = 0x555555762ec0, next = 0x0, prev = 0x555555774120, priv = 0x0}
(gdb)

**Comment by ustcpxy** [comment]
#397

**Comment by ustcpxy** [comment]
#397

**Comment by michalvasko** [comment]
Hi,
we can discuss both the problem and solution in the pull request.

Regards,
Michal
