### ISSUE TITLE
Dumping data tree

### ISSUE THREAD

**Issue by randyrandhawa** [CESNET/libyang#4]
I've read/validated some data, and am trying to dump the data-tree into a file.

I read the initial data from file and register with the context:

lyd_parse(yctx, buf, LYD_XML, LYD_OPT_STRICT);

Then at a later point I try to dump the data:

struct lyd_node *root;
File *file;

root = ly_ctx_info(yctx);
file = fopen("/tmp/dummy", "w+");
lyd_print(file, root, LYD_XML);

I get the following error while trying to write the file:

libyang[0]: Internal error (/home/odluser/dev/devel/libyang/src/printer_xml.c:305).

288	    switch (node->schema->nodetype) {
(gdb) 
305	        LOGINT;
(gdb) print node->schema->name
$1 = 0x60a910 "module"
(gdb)

The node is listed as "GROUPING" and the node schema name is "module". This causes the print function to break .. how do I dump the entire data tree? Any help would be greatly appreciated!

**Comment by rkrejci** [comment]
Should be fixed in the devel branch (version 0.2.23), please verify.
