### ISSUE TITLE
ly_ctx_load_module crashes with invalid revision argument

### ISSUE THREAD

**Issue by lukasmacko** [CESNET/libyang#40]
when  invalid ```revision``` argument and existing ```module_name``` are passed ```ly_ctx_load_module```  program crashes.

Example:
example-module.yin is in search path

```C
const struct lys_module *module = ly_ctx_load_module(ctx, "example-module", "2016-08-08");
```

**Comment by michalvasko** [comment]
Hi,
please verify.

**Comment by lukasmacko** [comment]
Works OK, thanks.
