### ISSUE TITLE
XPath function "re-match" is not defined in the XPath context, in an "when" statement

### ISSUE THREAD

**Issue by redivo** [CESNET/libyang#401]
The compiler did not found the XPath function "re-match".

It's being used like this:

```
...

augment "/my-root-container" {
    when "re-match(./my-leaf, 'my-regex')";
    ...
}

...
```

The outputted error message is:

data/session/bfnfzxnh6xfswx72p5zj0g0zes7jebkr/_**\<my-yang-file-name\>**_@2016-08-25.yang:43: error: XPath function "re-match" is not defined in the XPath context

**Comment by michalvasko** [comment]
Hi,
is your module YANG 1.1? Otherwise you will get this error, I do not know what else could cause it.

Regards,
Michal

**Comment by redivo** [comment]
That's the problem.

The **_yang-version 1.1_** statement was missing.

Thanks
