### ISSUE TITLE
xpath parsing issue when xpath1.0 defined under typedef

### ISSUE THREAD

**Issue by rohitrranade** [CESNET/libyang#402]
In below NETCONF rpc, 'path' is of type-def xpath as defined in RFC 6536 NACM

Extracts from the RFC 6536 defined YANG file:
leaf path {
                 type node-instance-identifier;

typedef node-instance-identifier {
       type yang:xpath1.0;

If input for "path" is given as below:
![image](https://user-images.githubusercontent.com/34262988/33592838-c6c3240e-d9b2-11e7-8213-9216d224c604.png)

1. The namespace is invalid ("yang-library12"). But still parsing is success. 
2. The struct lyd_node_leaf_list *pstLeaf, for the "path" 
*pstLeaf = {schema = 0x816f1f8, validity = 0 '\000', dflt = 0 '\000', when_status = 0 '\000', attr = 0x0, next = 0x0, prev = 0x8191b58, parent = 0x8181480, value_str = 0x818b0a0 "/t:modules-state", value = {
    binary = 0x818b0a0 "/t:modules-state", bit = 0x818b0a0, bln = -96 '\240', dec64 = 135835808, enm = 0x818b0a0, ident = 0x818b0a0, instance = 0x818b0a0, int8 = -96 '\240', int16 = -20320, int32 = 135835808, int64 = 135835808, 
    leafref = 0x818b0a0, string = 0x818b0a0 "/t:modules-state", uint8 = 160 '\240', uint16 = 45216, uint32 = 135835808, uint64 = 135835808}, value_type = 10}
==> the value_str is not "expanding" the prefix to valid module-name even if valid namespace is given.

**Comment by michalvasko** [comment]
Hi,
yeah, it does not work because all *libyang* knows is that `xpath1.0` type is simply a renamed `string`, all the additional information is only in the description... So, I will add some specific handling of this type and then reference this issue in the commit.

Regards,
Michal
