### ISSUE TITLE
Wrong ERROR-TAG returned by libyang api

### ISSUE THREAD

**Issue by basavarajKrish** [CESNET/libyang#409]
Issue 1:
=======

For below RPC request 
EXPECTED `<error-tag>` in `<rpc-error>` is    `**“<error-tag>bad-attribute</error-tag>”**`
because of invalid operation="123" 

```
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="9">
  <edit-config>
    <target>
      <candidate/>
    </target>
    <config xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
      <interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
        <interface xc:operation="123">
          <name>Virtual-Template5</name>
          <description/>
          <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ppp</type>
          <enabled>true</enabled>
          <link-up-down-trap-enable>enabled</link-up-down-trap-enable>
        </interface>
      </interfaces>
    </config>
  </edit-config>
</rpc>
```

But the actual <error-tag> in received in <rpc-error> is  <error-tag>bad-element</error-tag>

```
<?xml version="1.0" encoding="utf-8"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="7">
  <rpc-error>
    <error-type>protocol</error-type>
    <error-tag>bad-element</error-tag>
    <error-severity>error</error-severity>
    <error-path xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0"
                xmlns:if="urn:ietf:params:xml:ns:yang:ietf-interfaces">/nc:rpc/nc:edit-config/nc:config/if:interfaces/if:interface</error-path>
    <error-message xml:lang="en">Operation failed. (Invalid value "123" in "operation" element.)</error-message>
    <error-info xmlns:nc-ext="http://www.huawei.com/netconf/vrp/huawei-netconf-extension">
      <bad-element>interface</bad-element>
      <nc-ext:error-info-code>334</nc-ext:error-info-code>
    </error-info>
  </rpc-error>
</rpc-reply>
```

**The libyang api  “ly_vecode_location()” returned the value LY_VECODE  =  41 which is  LYVE_INVAL,   /**< invalid value of an element (data) */

The libyang api must return the value LY_VECODE  =  42 which is     LYVE_INMETA,       /**< invalid metadata (attribute) value (data) */   , so that we can encode “<error-tag>bad-attribute</error-tag>” in <rpc-error>**

==================================================================

Issue 2:
=======
For below RPC request 
EXPECTED `<error-tag> in <rpc-error> is    “<error-tag>unknown-attribute</error-tag>”`
because of unknown attribute  a ="1" 
```
<?xml version="1.0" encoding="utf-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="8">
  <edit-config>
    <target>
      <candidate/>
    </target>
    <config xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
      <interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
        <interface xc:operation="create" a="1">
          <name>Virtual-Template5</name>
          <description/>
          <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ppp</type>
          <enabled>true</enabled>
          <link-up-down-trap-enable>enabled</link-up-down-trap-enable>
        </interface>
      </interfaces>
    </config>
  </edit-config>
</rpc>
```

But the actual <error-tag> in received in <rpc-error> is  <error-tag>bad-attribute</error-tag>

```
<?xml version="1.0" encoding="utf-8"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="8">
  <rpc-error>
    <error-type>protocol</error-type>
    <error-tag>bad-attribute</error-tag>
    <error-severity>error</error-severity>
    <error-path xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0"
                xmlns:if="urn:ietf:params:xml:ns:yang:ietf-interfaces">/nc:rpc/nc:edit-config/nc:config/if:interfaces/if:interface</error-path>
    <error-message xml:lang="en">Operation failed. (Invalid "&lt;none&gt;:a" metadata with value "1".)</error-message>
    <error-info xmlns:nc-ext="http://www.huawei.com/netconf/vrp/huawei-netconf-extension">
      <bad-attribute>a" metadata with value "1".</bad-attribute>
      <bad-element>interface</bad-element>
      <nc-ext:error-info-code>334</nc-ext:error-info-code>
    </error-info>
  </rpc-error>
</rpc-reply>
```

**From this the libyang api “ly_vecode_location()” returned the LY_VECODE  =  42 which is  LYVE_INMETA,       /**< invalid metadata (attribute) value (data) */

But it should return the LY_VECODE  =  43 which is    LYVE_INATTR,       /**< invalid attribute in an element (data) */
, so that we can encode “<error-tag>unknown-attribute</error-tag>” in <rpc-error>**

**Comment by michalvasko** [comment]
Hi,
it should be fixed in the latest *libyang* but I tested it with *netopeer2-cli* and for it to work there also *libnetconf2* needs to be updated.

Regards,
Michal

**Comment by basavarajKrish** [comment]
Hi, 
So you mean i need to get the latest libyang code and libnetconf2 code and try the scenarios?

**Comment by michalvasko** [comment]
Exactly.

**Comment by basavarajKrish** [comment]
But when i compare my code with the latest , its almost same

**Comment by michalvasko** [comment]
I am not sure what you mean by almost the same, I simply fixed what was wrong and strictly speaking, to fix the 2 issues you only need to use the referenced (5768db92bce58033247c16ecfeb6f9d71a1d0523) commit.

**Comment by basavarajKrish** [comment]
ok sure i will try with this
