### ISSUE TITLE
Error assembler messages when accross compile in arm linux

### ISSUE THREAD

**Issue by ehaibyu** [CESNET/libyang#410]
[root@tedge build]# make
[  2%] Building C object CMakeFiles/yangobj.dir/src/common.c.o
[  5%] Building C object CMakeFiles/yangobj.dir/src/context.c.o
[  8%] Building C object CMakeFiles/yangobj.dir/src/log.c.o
[ 10%] Building C object CMakeFiles/yangobj.dir/src/dict.c.o
[ 13%] Building C object CMakeFiles/yangobj.dir/src/resolve.c.o
/home/netconf2/libyang/src/resolve.c: In function 'resolve_len_ran_interval':
/home/netconf2/libyang/src/resolve.c:2690: warning: integer constant is too large for 'unsigned long' type
[ 16%] Building C object CMakeFiles/yangobj.dir/src/validation.c.o
[ 18%] Building C object CMakeFiles/yangobj.dir/src/xml.c.o
[ 21%] Building C object CMakeFiles/yangobj.dir/src/parser.c.o
/tmp/ccG70buw.s: Assembler messages:
/tmp/ccG70buw.s:8253: Error: operation combines symbols in different segments
/tmp/ccG70buw.s:8255: Error: operation combines symbols in different segments
make[2]: *** [CMakeFiles/yangobj.dir/src/parser.c.o] error 1
make[1]: *** [CMakeFiles/yangobj.dir/all] error 2
make: *** [all] error 2

Is there anybody who can tell me why ? thanks a lot.

**Comment by michalvasko** [comment]
Hi,
I am not sure about the errors but the warning is serious enough. It seems your platform does not support 64b unsigned integers and if it really is so, I do not think you can use *libyang* at all.

Regards,
Michal
