### ISSUE TITLE
lys_find_xpath() for choice statements is not selecting the case statements

### ISSUE THREAD

**Issue by rohitrranade** [CESNET/libyang#411]
RFC 6536 defines a CHOICE statement (choice rule-type )
When I tried using lys_find_xpath() on the choice of "path", it could not select the path node. Is it a bug ?

Run till exit from #0  lys_find_xpath (ctx=0xee7c3918, node=0xed626708, 
    expr=0xed6673dd "/ietf-netconf-acm:nacm/ietf-netconf-acm:rule-list/ietf-netconf-acm:rule/ietf-netconf-acm:rule-type/ietf-netconf-acm:protocol-operation/ietf-netconf-acm:rpc-name", options=0) at tree_schema.c:3841
Value returned is $16 = (struct ly_set *) 0x0

For a choice of RPC -name, lys_path() is giving a path.
(gdb) p lys_path(pstLysNode)
$14 = 0xf02bf7d8 "/ietf-netconf-acm:nacm/rule-list/rule/rule-type/protocol-operation/rpc-name"

If the input string format is incorrect, please provide a way of ensuring that  lys_find_xpath can find the cases in the choice.

**Comment by michalvasko** [comment]
Hi,
you are using some old version of *libyang*, there is no `lys_find_xpath()` function anymore but `lys_find_path()`. The functionality remained the same, though, so I have tried it and it worked as expected, with the path you have used. So, update your *libyang* and you should be fine.

Regards,
Michal

**Comment by rohitrranade** [comment]
Ok.. One more issue,

**Comment by michalvasko** [comment]
Hi,
we are not working here with filesystem paths so there is no trailing `/` that can simply be ignored, there is the XPath grammar that must be satisfied, which does not allow this. So, I will check it and make sure it is treated as an invalid path.

Regards,
Michal
