### ISSUE TITLE
New version of yanglint fails to parse augment identity reference

### ISSUE THREAD

**Issue by ygorelik** [CESNET/libyang#412]
We are facing issue parsing XML from Yang model with augments. The issue is reproducible with latest version of libyang and yanglint. This issue was not seen with the older version of libyang dated December 12, 2016.

Yang model repository could be found here:
https://github.com/CiscoDevNet/ydk-gen/tree/master/sdk/cpp/core/tests/models

Data model to parse (should be written into file test.xml):
```
<cpython xmlns="http://cisco.com/ns/yang/ietf-aug-base-1">
  <doc>
    <aug-5-identityref xmlns="http://cisco.com/ns/yang/yaug-five">aug-identity</aug-5-identityref>
  </doc>
</cpython>
```
The yanglint output:
```
yan@ubuntu-yan:~/ydk-workspace/libyang/build$ ./yanglint
> add /home/yan/ydk-workspace/ydk-gen/sdk/cpp/core/tests/models/ietf-aug-base-1.yang 
> add /home/yan/ydk-workspace/ydk-gen/sdk/cpp/core/tests/models/ydktest-aug-ietf-5.yang
> searchpath /home/yan/ydk-workspace/ydk-gen/sdk/cpp/core/tests/models
> data test.xml
libyang[0]: Failed to resolve identityref "aug-identity". (path: /ietf-aug-base-1:cpython/doc/ydktest-aug-ietf-5:aug-5-identityref)
Failed to parse data.
> 
```

**Comment by michalvasko** [comment]
Hi,
we did not implement it correctly before and it is fixed now, the identityref's value cannot be its base, only any derived identity from that base ([RFC](https://tools.ietf.org/html/rfc7950#section-9.10.2)).

Regards,
Michal
