### ISSUE TITLE
libyang for windows

### ISSUE THREAD

**Issue by harinathcheluri** [CESNET/libyang#413]
Is the json instance validation in windows supported?

**Comment by michalvasko** [comment]
Hi,
everything is as long as you manage to compile *libyang* for Windows. We have never tried and it likely wouldn't be easy.

Regards,
Michal

**Comment by harinathcheluri** [comment]
Thanks Michal.
Is there any other library/tools to validate json instance for windows?

**Comment by michalvasko** [comment]
Hi,
I do not know, never looked for them. You can look [here](http://www.yang-central.org/twiki/bin/view/Main/YangTools) or try searching the Internet.

Regards,
Michal
