### ISSUE TITLE
Behviour of using same node multiple times for leaf node.

### ISSUE THREAD

**Issue by vikash7325** [CESNET/libyang#421]
consider node1 which is a leaf, has valid values as value1, value2 and value3.
Let's say value3 is the default value.

Now during configuration, if we give node1 multiple times(as in case of leaf-list) then 
the current behavior is as follow:
Consider we are giving node1 two times:
Scenario 1:
1. First time we use value1 to configure
2. Second time we use value2 to configure
=> in this case libyang returns error.

Scenario 2:
1. First rime we use value1 to configure
2. Second time we use value1 to configure
=> Libyang returns ok.

Scenario 3:
1. First time we use value1 to configure
2. Second time we use default value, value3 to configure
==> libyang returns ok.

Scenario 4:
1. First time we use default value, value3 to configure.
2. Second time we use value1 or value2 to configure.
==> libyang returns error.

So i think the behavior is as follow:
Even if a node is not leaf-list, we can give same node multiple times.
If using same node multiple times, if we use same value for all the nodes, then libyang parses OK
If using same node multiple times, if we use default value for the last node, then libyang parses OK.
In all other sceanrio , libyang will return error.

Can you confirm if my understanding is correct?
Regards,
Vikash

**Comment by michalvasko** [comment]
Hi Vikash,
are you talking about something specific such as having a data tree with the **1.** and then calling `lyd_new_path()` with arguments from **2.**? If so, then the behaviour largely depends on the options you use for the function. Otherwise, please include more details.

Regards,
Michal

**Comment by vikash7325** [comment]
Hi Michalvasko,
In RPC edit-config request we are giving one leaf node multiple times
<name>value1</name>
<name>value2</name>

name is node of leaf type, not leaf-list.
So, when we do edit-config, then libyang parser should return error.
Right now, it is not returning error.
Regards,
Vikash

**Comment by michalvasko** [comment]
Hi Vikash,
you will have to be more specific because I have just tried sending a `edit-config` with 2 values of `interfaces/interface/description` and the server properly complained and returned an error.

Regards,
Michal
