### ISSUE TITLE
Empty container node is considered invalid when containing spaces

### ISSUE THREAD

**Issue by iwanb** [CESNET/libyang#429]
Given a Yang with a presence container:
```
module a {
  namespace "urn:a";
  prefix a_mod;

  container x {
    presence "Enables x";
    leaf bar-leaf {
      type int32;
    }
  }
}
```

And an instance with this empty container but with spaces:
```
<x xmlns="urn:a">
</x>
```

The instance is considered invalid:
```
$ yanglint --strict -f xml -t edit a.yang inst.xml
err : Invalid node with text data "
". (/x)
```

While this is not the best way to write this XML, shouldn't the spaces be ignored?

**Comment by michalvasko** [comment]
Hi,
it depends, if we are not to be **strict** about it, it can be ignored. Why did you use that parameter?

Regards,
Michal

**Comment by iwanb** [comment]
Hi,
I use it because otherwise data nodes might be discarded silently.
But indeed without the --strict it works fine (I thought it was discarding the empty container node, but it must have been when I forgot to add a presence statement to the schema).

I would still argue that container and list nodes should strip spaces even if they have no children, but I can also see why it is considered an error (containers cannot hold data).

Regards,
Iwan

**Comment by michalvasko** [comment]
Hi Iwan,
we have decided it probably makes sense to always ignore white-space characters as content in schema nodes with children (container, list, notification, RPC, ...) so the parameter will not affect it. I will reference this issue with the commit.

Regards,
Michal

**Comment by iwanb** [comment]
Great, thank you!

Iwan

**Comment by iwanb** [comment]
It works fine now, thanks!

Iwan

**Comment by kwatsen** [comment]
Strictly speaking, 

> <X></X>, which is the same as <X/>

and

> <X> </X>    (notice the single space between)

are different things.   Yanglint (on master branch) validates the first and errors on the second (same issue reported by the OP).  I guess that you fixed this on the "devel" branch?

Anyway, in the common case where there is a list of elements:

> <X><Y/><Y/><Y/></X>

it is very common to ignore the whitespace, so this is effectively the same:

> <X>
>     <Y/>
>     <Y/>
>     <Y/>
> </X>

So, I think this is the right choice.

**Comment by iwanb** [comment]
Just checking, any reason this has not been closed/merged in the stable branch?

**Comment by michalvasko** [comment]
Only that our policy is that if you want up-to-date library with all the recent changes and bugfixes, you should use `devel`. This fix does change XML parser behaviour, that is why we want to merge it to `master` on a new release and not sooner. Should not take too long now (few weeks probably).

Regards,
Michal

**Comment by iwanb** [comment]
Ok perfect, thank you!
