### ISSUE TITLE
There may be some code mistakes in "resolve.c"

### ISSUE THREAD

**Issue by corrollFang** [CESNET/libyang#434]
There may be some code mistake in "resolve.c".
**1. The input parameter "schema" is overwritten, it guess it's a mistake.**
```C
static int
resolve_when_ctx_node(struct lyd_node *node, struct lys_node *schema, struct lyd_node **ctx_node,
                      enum lyxp_node_type *ctx_node_type)
{
    struct lyd_node *parent;
    struct lys_node *sparent;
    struct lys_node *schema_ctxt = NULL;
    enum lyxp_node_type node_type;
    uint16_t i, data_depth, schema_depth;

    resolve_when_ctx_snode(schema, &schema, &node_type); //-----------I guess it's a mistake------------
...
```

-------------------------------------------
**2. error code is not set if failed to evaluate when state.**
```C
int
resolve_when(struct lyd_node *node, int ignore_fail, struct lys_when **failed_when)
{
....
check_augment:
        if ((sparent->parent && (sparent->parent->nodetype == LYS_AUGMENT) && (((struct lys_node_augment *)sparent->parent)->when))) {
            if (!ctx_node) {
                rc = resolve_when_ctx_node(node, sparent->parent, &ctx_node, &ctx_node_type);
                if (rc) {
                    LOGINT;
                    goto cleanup;
                }
            }

            unlinked_nodes = NULL;
            tmp_node = node;
            rc = resolve_when_unlink_nodes(sparent->parent, &tmp_node, &ctx_node, ctx_node_type, &unlinked_nodes);
            if (rc) {
                goto cleanup;
            }

            rc = lyxp_eval(((struct lys_node_augment *)sparent->parent)->when->cond, ctx_node, ctx_node_type,
                           lys_node_module(sparent->parent), &set, LYXP_WHEN);

            /* reconnect nodes, if ctx_node is NULL then all the nodes were unlinked, but linked together,
             * so the tree did not actually change and there is nothing for us to do
             */
            if (unlinked_nodes && ctx_node) {
                if (resolve_when_relink_nodes(ctx_node, unlinked_nodes, ctx_node_type)) {
                    rc = -1;
                    goto cleanup;
                }
            }

            if (rc) {
                if (rc == 1) {
                    LOGVAL(LYE_INWHEN, LY_VLOG_LYD, node, ((struct lys_node_augment *)sparent->parent)->when->cond);
                }
                goto cleanup;
            }

            lyxp_set_cast(&set, LYXP_SET_BOOLEAN, ctx_node, lys_node_module(sparent->parent), LYXP_WHEN);
            if (!set.val.bool) {
                node->when_status |= LYD_WHEN_FALSE;
                if ((ignore_fail == 1)
                        || ((((struct lys_node_augment *)sparent->parent)->when->flags & LYS_XPATH_DEP) && (ignore_fail == 2))) {
                    LOGVRB("When condition \"%s\" is not satisfied, but it is not required.",
                           ((struct lys_node_augment *)sparent->parent)->when->cond);
                } else {
                    LOGVAL(LYE_NOWHEN, LY_VLOG_LYD, node, ((struct lys_node_augment *)sparent->parent)->when->cond);
                    if (failed_when) {
                        *failed_when = ((struct lys_node_augment *)sparent->parent)->when;
                    }
                    rc = -1;  -------// It's missed, error-code is not returned to caller----------------------
                    goto cleanup;
                }
            }
...
```

**Comment by michalvasko** [comment]
Hi,
the code you mentioned is fine and behaving as expected (you can even find explanation for the second case in the function documentation, which you should have definitely have read before posting it here). Generally, please post issues only if you have some API problem - a function does not behave as documented. Leave the actual implementation to us.

Regards,
Michal

**Comment by corrollFang** [comment]
Hi, 
Thanks a lot for your response.
Yes, i agree it'm my mistake that i didn't use the API(resolve_when) correctly in the second case. I'll modify my code accordingly.

**Comment by michalvasko** [comment]
Hi,
okay, but you should not be using `resolve_when()` at all, it is not a public function.

Regards,
Michal

**Comment by corrollFang** [comment]
Hi,
Thanks for your reminder.
Actually I'm trying to evaluate when state during adding new nodes. I think it's necessary.

The code is as below:
static int
lyd_wd_add_subtree(struct lyd_node **root, struct lyd_node *last_parent, struct lyd_node *subroot,
                   struct lys_node *schema, int toplevel, int options, struct unres_data *unres)
{
    struct ly_set *present = NULL;
    struct lys_node *siter, *siter_prev;
    struct lyd_node *iter;
    int i, check_when_must;
...

    case LYS_CONTAINER:
        if (!subroot) {
            /* container does not exists, continue only in case of non presence container */
            if (((struct lys_node_container *)schema)->presence) {
                /* stop recursion */
                break;
            }
            /* always create empty NP container even if there is no default node,
             * because accroding to RFC, the empty NP container is always part of
             * accessible tree (e.g. for evaluating when and must conditions) */
            subroot = _lyd_new(last_parent, schema, 1);
            
            //Check if when is satisfied
            if(subroot)
            {
                ly_vlog_hide(255);
                int rc = resolve_when(subroot, 0, NULL); //-----Evaluate when state--------
                ly_vlog_hide(0);
                if(rc != 0 || subroot->when_status & LYD_WHEN_FALSE)
                {
                    char* node_data_xpath = lyd_path(subroot);
                    LOGDBG(LY_EINVAL, "%s: when is not satisfied for '%s', error-no=%d",
                        __func__, (node_data_xpath ? node_data_xpath : "NULL"), rc);
                    rc = lyd_unlink(subroot);
                    if(rc != 0)
                    {
                        LOGERR(LY_EINVAL, "%s: Failed to unlink node '%s', error-no=%d",
                            __func__, (node_data_xpath ? node_data_xpath : "NULL"), rc);
                    }
                    lyd_free(subroot);
                    free(node_data_xpath);
                    return EXIT_SUCCESS;
                }
            }
...

**Comment by michalvasko** [comment]
Hi,
it would seem it is necessary but we chose a different solution to this problem. Most of the functions modify the data tree whatever way the user wants but invalidate it. Then, once you are done with the changes, you must validate the final tree. This way it is more effective and all the validation tasks do not need to be performed after every small change. Also, this is written in the documentation of every affected function (**PARTIAL CHANGE** tag).

Regards,
Michal
