### ISSUE TITLE
Parsing regexp fails

### ISSUE THREAD

**Issue by jjastrze-ovh** [CESNET/libyang#441]
I receive following error:
```
[ERR] libyang error: Value "2006-01-02T15:04:05Z+07:00" does not satisfy the constraint "^[0-9]{4}\-[0-9]{2}\-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\.[0-9]+)?Z[+-][0-9]{2}:[0-9]{2}$" (range, length, or pattern).
[ERR] libyang error: Failed to create node "current-datetime" as a child of "state".
```

Manually testing this regexp works:
```bash
root@ubuntu:~# echo '2006-01-02T15:04:05Z+07:00' | egrep '^[0-9]{4}\-[0-9]{2}\-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\.[0-9]+)?Z[+-][0-9]{2}:[0-9]{2}$'
2006-01-02T15:04:05Z+07:00
```

Another example:

```
[ERR] libyang error: Value "2018-02-16T11:08:41.201353137Z-01:00" does not satisfy the constraint "^[0-9]{4}\-[0-9]{2}\-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\.[0-9]+)?Z[+-][0-9]{2}:[0-9]{2}$" (range, length, or pattern).
[ERR] libyang error: Failed to create node "current-datetime" as a child of "state".
```
```bash
root@ubuntu:~# echo '2018-02-16T11:08:41.201353137Z-01:00' | egrep '^[0-9]{4}\-[0-9]{2}\-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\.[0-9]+)?Z[+-][0-9]{2}:[0-9]{2}$'
2018-02-16T11:08:41.201353137Z-01:00
```

I am using newest libyang library.
Regexp is part of oc-yang:date-and-time

**Comment by michalvasko** [comment]
Hi,
the problem is that in YANG the regular expressions are implicitly anchored ([ref](https://www.w3.org/TR/2004/REC-xmlschema-2-20041028/#regexs)). Therefore, the dollar at the end is interpreted as a normal character and since your date-time string does not end with `$`, it does not match.

Regards,
Michal

**Comment by jjastrze-ovh** [comment]
When my date string is:
```
"2018-02-16T11:08:41.201353137Z+01:00$"
```
Indeed, it matches. However in get operation i receive:
```
<current-datetime>2018-02-16T11:08:41.201353137Z+01:00$</current-datetime>
```
Can it be done to omit this dollar at the end?

**Comment by michalvasko** [comment]
What I actually meant is that the model you are using is wrong, not that you should put the dollar there. But, to answer you, it cannot be omitted because it would not satisfy the pattern.

Regards,
Michal

**Comment by jjastrze-ovh** [comment]
@michalvasko Thank you for clarification!
