### ISSUE TITLE
Non-UTF8 characters appear in log when parsing Cisco NX-OS Yang model

### ISSUE THREAD

**Issue by ygorelik** [CESNET/libyang#446]
When running yanglint on [Cisco NX-OS Yang model](https://github.com/YangModels/yang/blob/8cd99f604abd0dfdd5a429ac7b3fa34926e5b0d9/vendor/cisco/nx/7.0-3-I7-2/Cisco-NX-OS-device.yang) in verbose mode, some messages contain non-UTF8 characters like this one:

verb: Resolving derived type "l2_VlanBitmap" failed, it will be attempted later.
verb: Resolving type default "`CÇ^A" failed, it will be attempted later.
verb: Resolving derived type "fc_VsanBitmap" failed, it will be attempted later.
verb: Resolving type default " fÉ^A" failed, it will be attempted later.

Full log attached: 
[libyang-issue.log](https://github.com/CESNET/libyang/files/1749583/libyang-issue.log)

**Comment by michalvasko** [comment]
Hi,
fixing this should also reduce message clutter and skip empty default type prints as was intended, thanks.

Regards,
Michal

**Comment by ygorelik** [comment]
Hi Michal

Thank you for quick turnaround.
It works now “like a charm”!

Best regards,
Yan
