### ISSUE TITLE
Create instance data with default values

### ISSUE THREAD

**Issue by rwestphal** [CESNET/libyang#447]
Hi,

I'm considering to use libyang to manage the running configuration of my application. The idea is to centralize all configuration data in a single place (a `lyd_node` for each loaded YANG module) and take advantage of `lyd_diff()` to implement a robust configuration reload mechanism based on CRUD callbacks and priorities. I'm aware that I could outsource the running configuration of the application to sysrepo or confd and let them do all the hard work for me, but that's not an option for me.

Overall my experience with libyang has been quite satisfactory, the documentation is great and the API is much more convenient compared to using libxml2 for the same purpose (storing instance data).

One thing I missed from the API though is the ability to create leaf nodes with their default values anytime a container is created using either `lyd_new()` or `lyd_new_path()`.

Example: `lyd_new_path(..., "/frr:ripd/instance", ...)`

Under `/frr:ripd/instance` I have several leafs with default values (e.g. timers, metrics, etc). What I'd like to do is to create these child nodes automatically when `/frr:ripd/instance` is created. Would it make sense to implement a flag in the API to support this use case (like `LYD_PATH_OPT_CREATE_DFLT`)?

One possibility for me would be to use `lys_find_path(..., "/frr:ripd/instance")`, loop through the child YANG leafs that have a default value and create the corresponding data nodes manually. The problem with this approach is that a single call to `lys_find_path()` can create multiple nested containers, which makes this solution a bit painful to implement (e.g. need to parse the XPath).

Another possibility would be to ignore all of this and fetch the default values from the schema when necessary. In this case the problem is that `lys_node_leaf` stores the default value using only a string and no binary representation. Which means that I'd need to convert from string to binary every time I need to fetch a configuration data, which is too expensive.

Any help would be appreciated.

**Comment by michalvasko** [comment]
Hi,
I am not sure I will answer what you want to know but you can create default values 2 ways, basically. The simplest one is calling `lyd_validate()` on the data tree, it will not only validate but also add default values. Or, you can create them manually with `lyd_new_path()` and its flag `LYD_PATH_OPT_DFLT`.

Regards,
Michal

**Comment by rwestphal** [comment]
Thanks a lot Michal, `lyd_validate()` does exactly what I was looking for. Problem solved :)
