### ISSUE TITLE
Support for user-defined types

### ISSUE THREAD

**Issue by rwestphal** [CESNET/libyang#448]
Hi,

It seems to me that libyang always resolves derived types (e.g. `inet:ipv6-address`) into YANG built-in types like `string` for storage in the `lyd_val` union (`lyd_node_leaf_list->value`). This of course makes a lot of sense but I wonder what it would take to implement support for user-defined types in libyang, if at all possible. What I'd like to do is to store types like `inet:ipv6-address` using a `in6_addr` structure instead of a string. I have strict performance requirements so this would be a big win for me, considering that functions like `inet_pton()` can be considerably expensive to be used in hot functions.

**Comment by michalvasko** [comment]
Hi,
we have been thinking about this at the very beginning of *libyang* implementation and decided to leave it out then. But we have nothing against adding it now, we just need to come up with a simple solution.

We have briefly discussed it and thought of 3 types of solutions. Firstly, there could be a compile-time mechanism handling this, which would require recompilation of *libyang* if a new type was supposed to be stored in a custom way. Then there are 2 types of run-time solutions. One would be using separate libraries (`*.so`) which would add support for custom storage of certain types and include callbacks that would handle the storing itself. The last idea was to allow these callbacks to be stored directly in `lys_type` (or `lys_typedef`, whatever) structures.

The first solution seems not flexible enough and the last would tie these custom storages to separate contexts plus require additional space for the callback itself. Therefore, the `*.so` libraries seem to be the best choice. What do you think?

Regards,
Michal

**Comment by rwestphal** [comment]
I'm glad to hear you're open to implementing this functionality.

Yes, I agree option <span>#</span>1 is not flexible enough.

Options <span>#</span>2 and <span>#</span>3 sound reasonable for me. Since I don't know very well the internals of libyang as of now, it's hard to give an opinion of what would be the best choice. Having separate `.so` libraries for the user-defined types sounds complicated but if you think this's the best solution then I'm all for it!

**Comment by michalvasko** [comment]
Hi,
what you wanted should be implemented and it would be great if you could test it more. Instructions are in the (`devel`) documentation `libyang/How to .../Schemas/YANG Extension and User Type Support`. You will need to build this documentation yourself.

Regards,
Michal

**Comment by rwestphal** [comment]
Wow, that was fast! I'll definitely test this later on today. Thanks a lot for working on this.

**Comment by rwestphal** [comment]
Fantastic, I did some preliminary tests and it's working like a charm for me. I'll do more extensive testing in the following days and give you more feedback later. Thanks again!

**Comment by rwestphal** [comment]
So I've been using user-defined types for a few days and your proposed solution is attending my needs just fine. The API for user-defined types couldn't be simpler to use, and the fact that multiple types can be defined in a single .so library is pretty convenient. I've implemented multiple user types and so far I didn't find any problem at all. I'm looking forward to see this feature merged into the master branch! :)

**Comment by michalvasko** [comment]
Hi,
glad to hear that, thanks for the feedback. Regarding the merge, I cannot really tell you more, it may take from a few weeks to a few months.

Regards,
Michal
