### ISSUE TITLE
Restriction on any operation

### ISSUE THREAD

**Issue by vikash7325** [CESNET/libyang#454]
Hi, 
Is there any statement in yang, where we can restrict a particular operation on a node.
For Ex: Delete operation
![image](https://user-images.githubusercontent.com/1485412/37137284-2b04414e-22cb-11e8-8864-c145232fa5bc.png)

I want to restrict delete operation on nacm node.
If any such statement is there..where libyang can return error, it will be great.

Regards,
Vikash Kumar

**Comment by michalvasko** [comment]
Hi Vikash,
it is not possible to restrict operations. Instead, you should probably use NACM  (as you can see, `nacm-deny-all` extension is actually used on the `nacm` container). You will achieve the same result, restricting certain operations for some (or all) users.

Regards,
Michal

**Comment by vikash7325** [comment]
Ok..got it..
Thanks.
