### ISSUE TITLE
yanglint fails to parse openconfig-network-instance.yang model

### ISSUE THREAD

**Issue by ygorelik** [CESNET/libyang#456]
Libyang version: 0.14.70

While working with IOS XR model, which is based on IETF standard and Openconfig models we got error message from libyang. Here is the model verification with yanglint:

yan@ubuntu-yan:~/ydk-workspace/ydk-gen/sdk/cpp/core/build$ project_libyang/src/project_libyang-build/yanglint 
> searchpath /home/yan/.ydk/10.30.110.84_830
> add /home/yan/.ydk/10.30.110.84_830/openconfig-network-instance.yang
libyang[0]: Failed to resolve identityref "oc-vlan-types:TPID_0x8100". (path: /openconfig-network-instance:tpid)
libyang[0]: Failed to resolve identityref "oc-vlan-types:TPID_0x8100". (path: /openconfig-network-instance:tpid)
libyang[0]: Module "openconfig-network-instance" parsing failed.

Note that libyang built wrong path to leaf tpid. Expected path: /openconfig-vlan/tpid

The models downloaded from device could be found here: 
[yang-model.tar.gz](https://github.com/CESNET/libyang/files/1795212/yang-model.tar.gz)

Note that pyang does not report any issue and produces correct model tree: 
[tree.txt](https://github.com/CESNET/libyang/files/1795191/tree.txt)

**Comment by michalvasko** [comment]
Hi,
it should work correctly now.

Regards,
Michal

**Comment by ygorelik** [comment]
Thank you Michal for quick turnaround.

Best regards,
Yan
