### ISSUE TITLE
should we change the definition from uint8_t to uint16_t in order to parse xpath success which key's value length is  255 

### ISSUE THREAD

**Issue by ostack** [CESNET/libyang#460]
should we change the definition from uint8_t to uint16_t in order to parse xpath success which key's value length is over 255 
if the xpath like the below ,it will parse failed in function lyxp_parse_expr
/Me:Me/Eq:Eq/Sr[name_key='1']/Sl[name_key='111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111']

struct lyxp_expr {
    enum lyxp_token *tokens; /* array of tokens */
    uint16_t *expr_pos;      /* array of pointers to the expression in expr (idx of the beginning) */
    uint16_t *tok_len;        /* array of token lengths in expr */
    enum lyxp_expr_type **repeat; /* array of expression types that this token begins and is repeated ended with 0,
                                     more in the comment after this declaration */
    uint16_t used;           /* used array items */
    uint16_t size;           /* allocated array items */

    char *expr;              /* the original XPath expression */
};

**Comment by michalvasko** [comment]
Hi,
already done in `devel` so I have cherry-picked it to `master`.

Regards,
Michal
