### ISSUE TITLE
How to parse output of action?

### ISSUE THREAD

**Issue by abhikeshav** [CESNET/libyang#464]
I have the below yang model:
```yang
container data {
    action action-node {
        input {
            leaf test {
                type string;
            }
        }
        output {
            leaf t {
                type string;
            }
        }
    }
```
Trying to parse the below xml from the `rpc-reply` as follows
```xml
<data xmlns="http://cisco.com/ns/yang/ydktest-action">
  <action-node/>
    <t>test</t>
  </action-node>
</data>
```

However, after parsing the data, if I try to print the data using `lyd_print_mem`, I see that the output leaf `t` is missing.
```c
    const char* p = "<data xmlns=\"http://cisco.com/ns/yang/ydktest-action\"><action-node><t>xyz</t></action-node></data>";

    struct ly_ctx* ctx = ly_ctx_new("/tests/models", LY_CTX_ALLIMPLEMENTED);
    ly_ctx_load_module(ctx, "ydktest-sanity-action", NULL);
    struct lyd_node* rpc = lyd_new_path(NULL, ctx, "/ydktest-sanity-action:data/action-node", NULL, LYD_ANYDATA_SXML, 0);
    assert_ptr_not_equal(rpc, NULL);

    struct lyd_node* root = lyd_parse_mem(ctx, p, LYD_XML, LYD_OPT_TRUSTED |  LYD_OPT_RPCREPLY, rpc, NULL);
    assert_ptr_not_equal(root, NULL);

    char* buffer; 
   lyd_print_mem(&buffer, root, LYD_XML, LYP_FORMAT|LYP_WD_ALL|LYP_KEEPEMPTYCONT);
    printf("%s\n\n", buffer); // here, the output of the action is missing
```
Produces below output:
```xml
<data xmlns="http://cisco.com/ns/yang/ydktest-action">
  <action-node/>
</data>
```
Any idea what could be wrong here?

**Comment by michalvasko** [comment]
Hi,
I see several problems.

1) You pasted one XML (where `t` is `test`) but you use another in the code (where `t` is `xyz`), it is quite confusing. Also, the one pasted is not a well-formed XML (on line 2, it should just be `<action-node>`).

2) You are generally missing validation (not validating `rpc` after it is created, parsing RPC reply with `LYD_OPT_TRUSTED`) and hence just asking for something not to work even though in this particular case it makes no difference.

3) Your RPC reply XML is wrong. If you used `LYD_OPT_STRICT` option in `lyd_parse_mem` you would know that actually no nodes from `p` are parsed and the output is simply the `rpc` action invocation without any output nodes. Action reply does not differentiate from RPC reply at all, that is why they are validated with the same option. Meaning you parse only the output nodes directly, the correct `p` is `<t xmlns=\"http://cisco.com/ns/yang/ydktest-action\">xyz</t>`. With it the output is as you would expect it to be.

Regards,
Michal

**Comment by abhikeshav** [comment]
Works now. Thanks @michalvasko !
