### ISSUE TITLE
Parse YIN schema with uniqe statement after fetching schema from sysrepo

### ISSUE THREAD

**Issue by frimpler** [CESNET/libyang#465]
Hi,

with the testcase test_parse_yin_with_unique() in this commit https://github.com/frimpler/libyang/commit/5d10ddeb2c2a1b46e58cc62ae1bc8879b7beb172 an issue of the YIN parser is triggered.

### Description

When netopeer2 fetches a schema from sysrepo with np2src_sr_get_schema() which contains a list with unique statement and this schema is then parsed with lys_parse_mem() an assertion occurs if the expressions in the unique statement contain prefixes: "resolve.c:1996: resolve_descendant_schema_nodeid: Assertion `nodeid && ret' failed". 

The reason for this problem is that the schema is parsed twice -- first time when sysrepo loads the YANG file which results in the YIN schema in memory and second time when the YIN schema in memory is parsed again by netopeer2. During the first parser run the prefixes in the unique statement are replaced by the corresponding module names using transform_schema2json(). This is tried again during the second parser run but then it fails because the prefixes have been replaced already.

### Proposed Solution

The proposed solution in parser_yin.c (https://github.com/frimpler/libyang/commit/ddaa91da3d47315892506bac018f59d9648006d8) checks whether the prefix replacement in transform_schema2json() returns NULL (i.e. the prefix could not be replaced) and uses the original expression in this case for further processing while assuming it contains already the replaced module name.

Regards,
Peter + Frank

**Comment by frimpler** [comment]
The same problem occurs when using the YANG parser. I guess it is not necessary to create another issue for this. Here are the corresponding commits:
Testcase: https://github.com/frimpler/libyang/commit/e8f9cde8b9850360d487499c2b94ccfed9d01b26
Solution: https://github.com/frimpler/libyang/commit/a2d2624a2f6fda5bfd5d5708e93c999541bf0165

**Comment by michalvasko** [comment]
Hi Peter & Frank,
the bugfix was a bit different and it should work now. I can still merge your test case if you create a pull request, thanks!

Regards,
Michal
