### ISSUE TITLE
Could NOT find PCRE/Pthread

### ISSUE THREAD

**Issue by totszwai** [CESNET/libyang#474]
Hello,

I build libpcre (https://github.com/vmg/libpcre) with the typical **configure** and **make** for **arm-linux**, now trying to compile libyang, however I get the following error:

> CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
>   Could NOT find PCRE (missing: PCRE_LIBRARY PCRE_INCLUDE_DIR)
> Call Stack (most recent call first):
>   /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
>   CMakeModules/FindPCRE.cmake:25 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
>   CMakeLists.txt:228 (find_package)

I am no expert in cmake, what is the proper way to tell libyang where to find what it needs?

**Comment by michalvasko** [comment]
Hi,
best is to install it somewhere `CMake` will find it but it also depends on the configuration of your system. But you can also specify the path manually by defining `PCRE_LIBRARY` and `PCRE_INCLUDE_DIR` just like the error says. So, on my system it would be
```
cmake -DPCRE_LIBRARY=/usr/lib64/lipcre.so -DPCRE_INCLUDE_DIR=/usr/include ..
```

Regards,
Michal

**Comment by totszwai** [comment]
This does the trick for now. Thanks. 

I am having a hard time making libyang to cross compile with the cmake 2.8, but I guess that's my separate issue. Do you have any tips on compiling libyang with Makefile (without cmake? i can't get it to load my arm-linux toolchain).

**Comment by totszwai** [comment]
@michalvasko 

```
export mytoolchain=/blah/tools/armv7-openwrt-linux-gnu-uClibc-0.9.33.2
mkdir build;
cd build;
cmake \
-DENABLE_BUILD_TESTS=OFF \
-DENABLE_VALGRIND_TESTS=OFF \
-DCMAKE_TOOLCHAIN_FILE=arm-linux-toolchain.cmake \
-DPCRE_LIBRARY=$mytoolchain/lib/lipcre.so \
-DPCRE_INCLUDE_DIR=$mytoolchain/include \
-DPTHREAD_LIBRARY=$mytoolchain/lib/libpthread.so \
-DPTHREAD_INCLUDE_DIR=$mytoolchain/include \
-DCMAKE_BUILD_TYPE:String="Release" ..;
```

It still try to look for the Pthread despite passing the path to it.

> CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
>   Could NOT find Threads (missing: Threads_FOUND)
> Call Stack (most recent call first):
>   /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
>   /usr/share/cmake/Modules/FindThreads.cmake:166 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
>   CMakeLists.txt:224 (find_package)
>
