### ISSUE TITLE
Description of the LYD_PATH_OPT_NOPARENT flag is wrong

### ISSUE THREAD

**Issue by rwestphal** [CESNET/libyang#475]
The documentation says the following about the `LYD_PATH_OPT_NOPARENT` flag: 
```
If any parents of the target node exist, return an error.
```

Shouldn't this be "If any parents of the target node **does not** exist, return an error"?

I did some testing here and confirmed that `lyd_new_path()` returns `Parent does not exist` when `LYD_PATH_OPT_NOPARENT` is used and I'm trying to create a node whose parent doesn't exist.

Thanks in advance.

**Comment by michalvasko** [comment]
Hi,
you are right, fixed.

Regards,
Michal

**Comment by rwestphal** [comment]
Thanks!
