### ISSUE TITLE
Issue with lys_find_path() and augmented nodes

### ISSUE THREAD

**Issue by rwestphal** [CESNET/libyang#476]
Hi,

I have the following two YANG files:
- frr-ripd.yang: https://gist.github.com/rwestphal/2fc93f3f928fee1127c2913977c00e8d
- frr-interface.yang: https://gist.github.com/rwestphal/2c411708e6002254610fc432965d5d1e

(both were written for experimentation purposes only, my goal is to use standard YANG modules in the future)

Notice that `frr-ripd` augments `/frr-interface:lib/interface` with RIP-specific options.

The problem I have now is that I can't get `lys_find_path()` to work with XPath expressions like this: `/frr-interface:lib/interface[name='eth1'][vrf='default']/frr-ripd:rip/split-horizon`.

What I want is to find the `lys_node` relative to `/frr-ripd:rip/split-horizon`, how can I do this without having to split the XPath expression myself? `lys_find_path()` returns a `ly_set` with zero elements regardless if I provide the `frr-ripd` or the `frr-interface` module for the `cur_module` parameter.

Any help would be appreciated.

**Comment by rwestphal** [comment]
Sorry for the noise, just found out that `ly_ctx_get_node()` does exactly what I was looking for.

Just one note, the documentation of this function says the following:
> This function is meant as a utility function to ease getting a specific schema node directly from context having data_path a const immutable string. Generally, it is better to use lyd_find_path(), lys_find_path(), or **ly_ctx_find_path()**. Also, it is possible to transform data paths into schema paths using ly_path_data2schema().

However this `ly_ctx_find_path()` function doesn't exist in libyang and apparently it never did. This seems like a minor documentation bug. Could you guys confirm?

**Comment by michalvasko** [comment]
Hi,
regarding your first problem, all these paths can be tricky so you must be careful to use the correct ones. If you read the documentation of `lys_find_path()` you will see it mentions a `schema path` with a reference to text with a more detailed description of what it exactly is.

About `ly_ctx_find_path()`, it is already in `devel` but the mention of it somehow got to `master`. Will remove it.

Regards,
Michal

**Comment by rwestphal** [comment]
Thanks for the explanation Michal :) I'll close this issue.
