### ISSUE TITLE
Request: expose the lys_is_key() function in the libyang API

### ISSUE THREAD

**Issue by rwestphal** [CESNET/libyang#477]
Hi,

Would it be possible to expose the `lys_is_key()` function in the libyang public API?

I find this function to be very useful. My program for example uses it to identify when a northbound agent is trying to delete or modify a list key, and in this case it marks the operation as invalid (the list itself should be modified/deleted instead).

I know this is a very trivial function and replicating it in my program is not a big deal, but I'd appreciate if I could get it from libyang instead. I believe other users might find it useful as well, but I'll leave it to your judgment :)

Regards,
Renato.

**Comment by michalvasko** [comment]
Hi Renato,
it is already in the API in `devel`, I suggest you use that branch instead. `master` is for when you want to deploy *libyang* somewhere and cannot be bothered to make small changes often as the API changes. For testing and learning about the library, `devel` is more suitable.

Regards,
Michal
