### ISSUE TITLE
Request: add a "priv" pointer in the lyd_node structure

### ISSUE THREAD

**Issue by rwestphal** [CESNET/libyang#478]
The `lys_node` structure contains a member called `priv`, as defined in `src/tree_schema.h`: 
```
void *priv;                      /**< private caller's data, not used by libyang */
```

Would it be possible to do something similar for `lyd_node`?

I store my program configuration inside `lyd_node` structures (one for each loaded module) and I'd like to be able to associate lists and presence containers with internal data structures of my program (e.g. map `/frr-interface:lib/interface[name='eth1'][vrf='default']` to a pointer of my own). Do you think this is a reasonable think to do?

**Comment by michalvasko** [comment]
Hi,
this seems like a reasonable thing to do but we try to minimize the size of data in the memory. Enlarge every node with a pointer (`8B` / `4B` based on your platform) is quite a lot for something most people would not use. However, having the attribute conditioned on a compile-time variable seems OK, what do you think?

Also, you can fairly easily create your own table where you will associate a data path with some structure of your own. Once you have the node, you easily get the path with `lyd_path()` and then use it as a key in your table. It would not be as elegant but maybe enough for your use-case without the need to modify *libyang*?

Regards,
Michal

**Comment by rwestphal** [comment]
Hi Michal,

I agree with you, most users wouldn't need this and it's something that can be done on the application side.

I'll implement a hash table to map paths to pointers. This will also give me faster configuration lookups, and I'll resort to `lyd_find_path()` only when I need to fetch multiple configuration options at the same time (e.g. to show the running configuartion).

I'll close this issue. Thanks for your input!

**Comment by rwestphal** [comment]
Please allow me to reopen this issue.

After analyzing my program more carefully, I realized I'd be able to make a considerable simplification if libyang provides a `priv` pointer in the `lyd_node` structure. I have lots of lookup callbacks that could simply be removed if I could store pointers in data nodes directly. The hash table solution is too cumbersome to implement since my program can now have multiple independent candidate configurations.

I was thinking if we could add a `priv` pointer in the `lyd_node` structure, but only after the `child` member, so the size of leaf nodes and leaf-list nodes are not affected. Would that be possible? If yes, I'd also need a `lyd_set_private()` function which would ensure that the given node is not a leaf nor a leaf-list.

I believe this change could benefit other libyang users in the future as well. I think the ability to associate lists and presence containers to private data structures can be useful in a variety of contexts.

Regards,
Renato.

**Comment by michalvasko** [comment]
Hi Renato,
it is not optionally supported, off by default.

Regards,
Michal

**Comment by rwestphal** [comment]
Thanks Michal!

Only issue I found is that `lyd_dup()` is not copying the `priv` pointer, but other than that it's all good. I've managed to make a huge simplification in my program as expected.

`ENABLE_LYD_PRIV` being off by default should not be a problem for now, since we'll probably embed libyang inside FRR packages (e.g. using a git submodule), and thus we'll have control over its build parameters. In the long run the idea is to have libyang as an external dependency, and in this case `ENABLE_LYD_PRIV` being off by defaul might be a problem for us (the libyang packages from upstream won't be compatible). I think we can discuss changing the default at a later point in the future.

Thanks again :)

**Comment by michalvasko** [comment]
Hi,
regarding `lyd_dup()`, I would consider not copying the pointer a feature because you can easily assign to it a dynamically allocated value in which case you would need a callback function for copying the pointer content. I do not feel like adding this function as a parameter for `lyd_dup()`. Do you have some other reasonable solution in mind?

Regards,
Michal

**Comment by rwestphal** [comment]
I get your point, doing a shallow copy of the private pointer instead of a deep copy can be dangerous if one is not careful enough. However, at least in my case, a shallow copy is exactly what I need.

In my opinion, doing a shallow copy by default would be the best solution. Here's my rationale:
1. If one wants a shallow copy of the `priv` pointers, then a simple `lyd_dup()/lyd_dup_withsiblings()` is enough;
2. If one wants to reset the `priv` pointers, it can be done afterwards by looping through all nodes in the data tree;
3. If one wants a deep copy of the `priv` pointers, it can be done afterwards by looping through all nodes in the data tree.

Regarding 1., it would be extremely cumbersome to do a shallow copy of the `priv` pointers manually. While iterating through the duplicated tree, for each node it would be necessary to find the corresponding node in the original tree to copy the `priv` pointer. For 2. and 3. the `priv` pointer would be already there in the duplicated nodes, and the user would be able to easily reset the pointer or do a deep copy if required.

Your callback solution would probably be more elegant and complete, but you mentioned you don't feel like doing it. You'd need to change the API just to address a very specific issue, so I understand your reluctance.

Regarding doing a shallow copy by default, we could just document this behavior and introduce a "copy callback" in the future if the need arises. What do you think?

**Comment by michalvasko** [comment]
Hi,
so you can set this duplication callback now for every context. Please, try that it works as expected (nothing will be copied if you do not set the callback), thanks.

Regards,
Michal

**Comment by rwestphal** [comment]
Thanks a lot, it's working perfectly!! :100:
