### ISSUE TITLE
Weird issue with augmentation

### ISSUE THREAD

**Issue by rwestphal** [CESNET/libyang#479]
Hi all,

Since I introduced one augmentation in my YANG module[1] I started to have some weird issues with libyang.

I wrote a simple test code that mimics on a very basic level the problem I'm facing in my program. Here is it: https://gist.github.com/rwestphal/16141e6d1b08dc549af574678c6560c5

This code does the following:
1. Creates a running configuration;
2. Creates a candidate configuration (dup from running);
3. Changes the candidate configuration (add presence container);
4. Validates the candidate configuration;
5. Replaces running by candidate;
6. Creates a candidate configuration (dup from running);
7. Changes the candidate configuration (delete previously added presence container);
8. Validates the candidate configuration;
9. Replaces running by candidate;
10. Repeat 2-9

Now here's the output of the program:
```
# ./libyang-issue
===========================================
ADDING CONTAINER:
===========================================
{
  "frr-ripd:ripd": {
    "instance": {

    }
  }
}
===========================================
DELETING CONTAINER:
===========================================
{

}
===========================================
ADDING CONTAINER:
===========================================
{
,
  "frr-ripd:ripd": {
    "instance": {

    }
  }
}
===========================================
DELETING CONTAINER:
===========================================
bug: couldn't find node
```

The first add/delete/add operations work ok. However the second delete doesn't work because `lyd_find_path()` can't find the container that was added before. After some investigation, I discovered that the `lyd_dup()` from step 6 is returning an empty node instead of a copy of the running configuration.

Removing the augmentation from my YANG module solves the problem. Other thing that solved the problem is avoid calling `lyd_validate()` if the configuration has only the top-level node.

I wrote this other program in an attempt to better understand the problem: https://gist.github.com/rwestphal/488b0041245c6ef88b334e5db1d9b3d8

This program is much simpler. It only adds and deletes a presence container to/from a `lyd_node`, calling `lyd_validate()` after each change and printing the `lyd_node` after each change or validation. Here's the output of this program:
```
# ./libyang-issue2
===========================================
ADDING CONTAINER:                          
===========================================
===========================================
CONFIG:
===========================================
{  
  "frr-ripd:ripd": {
    "instance": {
    }          
  }            
}                                          
Nodes: total(2)
 /frr-ripd:ripd                            
 /frr-ripd:ripd                            
===========================================
VALIDATING                                 
===========================================
===========================================
CONFIG:
===========================================
{                  
  "frr-ripd:ripd": {
    "instance": {                
,
      "allow-ecmp": false,
      "default-metric": 1,
      "distance": {
        "default": 0
      },
      "passive-default": false,
      "timers": {
        "flush-interval": 120,
        "holddown-interval": 180,
        "update-interval": 30
      },
      "version-recv": "1-2",
      "version-send": "2"
    }
  }
}
Nodes: total(15)
 /frr-ripd:ripd
 /frr-ripd:ripd
 /frr-ripd:ripd
 /frr-ripd:ripd
 /frr-ripd:ripd
 /frr-ripd:ripd
 /frr-ripd:ripd
 /frr-ripd:ripd
 /frr-ripd:ripd
 /frr-ripd:ripd
 /frr-ripd:ripd
 /frr-ripd:ripd
 /frr-ripd:ripd
 /frr-ripd:ripd
 /frr-ripd:ripd
===========================================
DELETING CONTAINER:
===========================================
===========================================
CONFIG:
===========================================
{
  "frr-ripd:ripd": {
  }
}
Nodes: total(2)
 /frr-ripd:ripd
 /frr-ripd:ripd
===========================================
VALIDATING
===========================================
===========================================
CONFIG:
===========================================
{

}
Nodes: total(2)
 /frr-interface:lib
 /frr-interface:lib
```

What I find weird in this output is the following:
- Why is `lyd_path()` printing only the top-level node instead of the full XPath?
- There's an out-of-place comma in the first JSON output, which makes it invalid JSON;
- After deleting `/frr-ripd:ripd/instance` (and before the validation), why does `lyd_find_path(running, "//*")` return two nodes instead of just one ("frr-ripd:ripd")? And why is `lyd_print_fd()` not printing the second node?
- After deleting `/frr-ripd:ripd/instance` (and after the validation), why does `lyd_find_path(running, "//*")` return two nodes from the augmented module ("/frr-interface:lib") which isn't being used?

It seems to me that my `lyd_node` is getting corrupted somewhere and I don't know if the problem is in my code or if I'm hitting a hidden bug inside libyang. I'll keep investigating but I'd really appreciate if anyone could give me a hand to know what's going wrong.

[1] frr-ripd.yang: https://gist.github.com/rwestphal/2fc93f3f928fee1127c2913977c00e8d

Best Regards,
Renato.

**Comment by michalvasko** [comment]
Hi Renato,
an interesting issue that needed but some fine-tuning in *libyang* and some modifications of your program.

For printing, try to use `LYP_FORMAT | LYP_KEEPEMPTYCONT | LYP_WITHSIBLINGS | LYP_WD_ALL` as flags. For duplicating, instead of `lyd_dup()` use a new (only `devel` for now) function `lyd_dup_withsiblings()`. That way it will behave as you expect and also the prints should make more sense.

In short, all (validated) *libyang* data trees always hold any default nodes present. Empty non-presence containers with existing parents (or top-level) are considered default and thus always exist. That should explain the other empty container. However, they are not visible when printing (as all default values) unless you use specific flags for the printer.

I hope it is clear now. If you have any other questions or issues, please reply. Also, the invalid comma in JSON output is not present in `devel` so use that branch and `lyd_path()` prints wrong paths because you have a bug in the loop using index `[0]` instead `[i]`.

Regards,
Michal

**Comment by rwestphal** [comment]
Hi Michal,

Thanks a lot, everything is working perfectly now and your explanation was really enlightening for me.

> and lyd_path() prints wrong paths because you have a bug in the loop using index [0] instead [i]

lol

I'll close this issue. Thanks again!
