### ISSUE TITLE
Possible issue with lyd_diff()

### ISSUE THREAD

**Issue by rwestphal** [CESNET/libyang#489]
Hi,

I wrote a small test program to illustrate a problem I'm having with `lyd_diff()` in my application. Here's the code: https://gist.github.com/rwestphal/fc29053e07fe22a1ccbaf7b455f88d97

And here's my YANG module: https://gist.github.com/rwestphal/2fc93f3f928fee1127c2913977c00e8d

What I'm trying to do is to compare an empty configuration with another configuration that has a top-level container, a presence container and a leaf element inside this container (xpath: `/frr-ripd:ripd/instance/allow-ecmp`) .

When I call `lyd_diff(config1, config2, LYD_DIFFOPT_WITHDEFAULTS)` to see the differences between the two configurations, I get this:
```
$ ./lyd_diff 
=================
RUNNING CONFIG:
=================
{
  "frr-interface:lib": {
  },
  "frr-ripd:ripd": {
  }
}
=================
CANDIDATE CONFIG:
=================
{
  "frr-interface:lib": {
  },
  "frr-ripd:ripd": {
    "instance": {
      "allow-ecmp": true,
      "default-metric": 1,
      "distance": {
        "default": 0
      },
      "passive-default": false,
      "timers": {
        "flush-interval": 120,
        "holddown-interval": 180,
        "update-interval": 30
      },
      "version-recv": "1-2",
      "version-send": "2"
    }
  }
}
=================
DIFF:
=================
LYD_DIFF_CREATED:
 xpath: /frr-ripd:ripd/instance
```

Note that `lyd_diff()` doesn't notify about the `allow-ecmp` leaf which is set to `true` in the second config (the default is `false`). Is this a bug or is there something wrong in my code?

When I call `lyd_diff()` without the `LYD_DIFFOPT_WITHDEFAULTS` flag I get this:
```
$ ./lyd_diff
=================
RUNNING CONFIG:  
=================
{
  "frr-interface:lib": {
  },
  "frr-ripd:ripd": {
  }              
}                        
=================         
CANDIDATE CONFIG:  
=================   
{       
  "frr-interface:lib": {       
  },             
  "frr-ripd:ripd": {          
    "instance": {                
      "allow-ecmp": true,    
      "default-metric": 1,
      "distance": {         
        "default": 0     
      },
      "passive-default": false,
      "timers": {
        "flush-interval": 120,
        "holddown-interval": 180,
        "update-interval": 30
      },         
      "version-recv": "1-2",   
      "version-send": "2"        
    }                            
  }                              
}                                
=================                
DIFF:                            
=================
LYD_DIFF_CREATED:
 xpath: /frr-ripd:ripd
```

In this case the situtation is even worse because `lyd_diff()` doesn't notify about the addition of the `instance` container.

EDIT: I'm using _libyang_ from the `devel` branch.

Any help would be appreciated.

**Comment by rwestphal** [comment]
Never mind about the first problem, I didn't pay much attention while reading the documentation but now I understand that `lyd_diff()` is working as expected.

Regarding the second issue though (when `LYD_DIFFOPT_WITHDEFAULTS` is not used) it seems to me that `lyd_diff()` should notify about the creation of the `instance` presence-container. Or am I missing something?

**Comment by michalvasko** [comment]
Hi,
please refer to the updated documentation, you should now understand why the output is the way it is. So, to get the output you probably expected, you need to traverse all the children of any `LYD_DIFF_CREATED` or `LYD_DIFF_DELETED` nodes and print them with the same operation as their parent.

Regards,
Michal

**Comment by rwestphal** [comment]
Thanks Michal, the documentation looks even better now.

Yes, I managed to get the behavior I need by traversing all children of the created nodes, it's working like a charm.

But what about the second issue I posted (when `LYD_DIFFOPT_WITHDEFAULTS` is not used)? In this case `lyd_diff()` notifies about the creation of the top-level `/frr-ripd:ripd` node which was already present in the first configuration. Isn't this a bug?

**Comment by michalvasko** [comment]
Hi,
I think it works fine, just look at the description of `LYD_DIFFOPT_WITHDEFAULTS` option. Simply put, without this option, default values are completely ignored meaning the implicit container `/frr-ripd:ripd` is treated as non-existent so it is created when it becomes explicitly created.

Regards,
Michal

**Comment by rwestphal** [comment]
Indeed, that makes sense. Thanks for the clarification!
