### ISSUE TITLE
Problem with lyd_dup() + user-defined types

### ISSUE THREAD

**Issue by rwestphal** [CESNET/libyang#492]
Hi, it's me again ^^

I did some testing here and noticed that `lyd_dup()` doesn't preserve the pointer used for user-defined types (leafs and leaf-lists) when copying a data tree.

This simple program shows the problem: https://gist.github.com/rwestphal/09a638213705c0398e7561eb44d07fe5

Output of the program:
```
$ ./dup_user_type 
===========================================
config1:
===========================================
address (from value_str): 1.1.1.1
address (from value.ptr): 1.1.1.1
===========================================
config2 (copy from config1):
===========================================
address (from value_str): 1.1.1.1
address (from value.ptr): 49.46.49.46
```

My YANG module (updated to use `inet:ipv4-address` instead of `string`): https://gist.github.com/rwestphal/2fc93f3f928fee1127c2913977c00e8d

I think that just copying the `lyd_val.ptr` pointer would eventually lead to a double free later. So I think the duplicated data tree should allocate separate copies of user-defined types for safety. Does that make sense?

One alternative would be to use refcounting, but IMHO that would be tricky to implement and error prone.

Any help would be appreciated.

**Comment by michalvasko** [comment]
Hi,
it should be just the way you proposed now. However, I have not managed to get the output you pasted here.

Regards,
Michal

**Comment by rwestphal** [comment]
Thanks again Michal! I have no words to express my gratitude. I'll close this issue.
