### ISSUE TITLE
Problem cross-compile and using the extensions

### ISSUE THREAD

**Issue by totszwai** [CESNET/libyang#496]
Hello,

We are cross-compiling libyang. We linked libyang to an executable and at run time we face the second issue mentioned in the FAQ.md (https://github.com/CESNET/libyang/blob/master/FAQ.md). We want to avoid touching the environment variables.

Questions:
1) Is there another way to tell libyang to find the extensions without setting the environment variable?
2) Is there a way to tell libyang to look for extensions at the SAME directory of libyang.so?
3) Is there a good way to just statically link libyang as well as the extensions .so?

The problem is that the staged environment we setup during the cross-compile process is different than the deployment. For example, in the staged environment, the library path could be /build/staging/lib, but the eventual deploy environment would be /lib. 

So setting -DPLUGINS_DIR on cmake, wouldn't work since the final location will be different.

**Comment by michalvasko** [comment]
Hi,
would it not be possible for you to use `-DPLUGINS_DIR=/lib` on `cmake` and start `yanglint` before installation with the variable just temporarily set like mentioned in FAQ `LIBYANG_EXTENSIONS_PLUGINS_DIR=/build/staging/lib ./yanglint`? To answer your questions, nothing else is possible and the build system currently does not support linking extensions statically. If you have some neat solution to this problem, we are willing to implement it as long as it is not too much additional code.

Regards,
Michal

**Comment by mohitarora24** [comment]
Hi, I'm not sure if this is the correct way to do it but I got to statically link plugins.c (and all usertypes/extensions) as shown in the diff file attached (appended .txt so that I could upload here). It's working fine for me.

Diff File: [plugins.c.diff.txt](https://github.com/CESNET/libyang/files/2000556/plugins.c.diff.txt)

**Comment by michalvasko** [comment]
Hi,
as long as it works, you are free to use it this way, of course, and maybe it will be useful for someone else, too.

Regards,
Michal
