### ISSUE TITLE
lyd_print doesn't work

### ISSUE THREAD

**Issue by randyrandhawa** [CESNET/libyang#5]
Calling lyd_print() dumps the loaded schemas not the data:
```
<libyang>
  <modules>
    <module>
      <name>ietf-inet-types</name>
      <revision>2013-07-15</revision>
      <namespace>urn:ietf:params:xml:ns:yang:ietf-inet-types</namespace>
      <conformance>implement</conformance>
    </module>
    <module>
      <name>ietf-yang-types</name>
      <revision>2013-07-15</revision>
      <namespace>urn:ietf:params:xml:ns:yang:ietf-yang-types</namespace>
      <conformance>implement</conformance>
    </module>
    <module>
      <name>ietf-yang-library</name>
      <revision>2015-07-03</revision>
      <namespace>urn:ietf:params:xml:ns:yang:ietf-yang-library</namespace>
      <conformance>implement</conformance>
    </module>
    <module-set-id>4</module-set-id>
  </modules>
</libyang>
```
How do I dump/parse/access the data which was added via lyd_parse()

**Comment by rkrejci** [comment]
Could you provide how you use lyd_print()? It prints just the data tree you pass via the `root` parameter, When you pass the data tree returned by ly_ctx_info(), it prints ietf-yang-library data.

**Comment by randyrandhawa** [comment]
// earlier
  lyd_parse(yctx, buf, LYD_XML, LYD_OPT_STRICT);

// later..
    root = ly_ctx_info(yctx);
    file = fopen("/tmp/dummy", "w+");
    lyd_print(file, root, LYD_XML);
    fflush(file);

**Comment by rkrejci** [comment]
try this:
```
root = lyd_parse(yctx, buf, LYD_XML, LYD_OPT_STRICT);
lyd_print(stdout, root, LYD_XML);
```

**Comment by randyrandhawa** [comment]
Still dumps the modules:

 $ ./bootstrap 
libyang[2]: reading module ietf-inet-types
libyang[2]: Resolving derived type "ipv4-address" failed, it will be attempted later (line 187).
libyang[2]: Resolving derived type "ipv6-address" failed, it will be attempted later (line 188).
libyang[2]: Resolving derived type "ipv4-address-no-zone" failed, it will be attempted later (line 251).
libyang[2]: Resolving derived type "ipv6-address-no-zone" failed, it will be attempted later (line 252).
libyang[2]: Resolving derived type "ipv4-prefix" failed, it will be attempted later (line 293).
libyang[2]: Resolving derived type "ipv6-prefix" failed, it will be attempted later (line 294).
libyang[2]: module ietf-inet-types successfully parsed
libyang[2]: reading module ietf-yang-types
libyang[2]: module ietf-yang-types successfully parsed
libyang[2]: reading module ietf-yang-library
libyang[2]: module ietf-yang-library successfully parsed
libyang[2]: reading module ietf-zerotouch-bootstrap-server
libyang[2]: module ietf-zerotouch-bootstrap-server successfully parsed
libyang[2]: reading module ietf-zerotouch-ownership-voucher
libyang[2]: module ietf-zerotouch-ownership-voucher successfully parsed

This is where a request is made ..

<libyang>
  <modules>
    <module>
      <name>ietf-inet-types</name>
      <revision>2013-07-15</revision>
      <namespace>urn:ietf:params:xml:ns:yang:ietf-inet-types</namespace>
      <conformance>implement</conformance>
    </module>
    <module>
      <name>ietf-yang-types</name>
      <revision>2013-07-15</revision>
      <namespace>urn:ietf:params:xml:ns:yang:ietf-yang-types</namespace>
      <conformance>implement</conformance>
    </module>
    <module>
      <name>ietf-yang-library</name>
      <revision>2015-07-03</revision>
      <namespace>urn:ietf:params:xml:ns:yang:ietf-yang-library</namespace>
      <conformance>implement</conformance>
    </module>
    <module>
      <name>ietf-zerotouch-bootstrap-server</name>
      <revision>2015-07-06</revision>
      <namespace>urn:ietf:params:xml:ns:yang:ietf-zerotouch-bootstrap-server</namespace>
      <conformance>implement</conformance>
    </module>
    <module>
      <name>ietf-zerotouch-ownership-voucher</name>
      <revision>2015-07-06</revision>
      <namespace>urn:ietf:params:xml:ns:yang:ietf-zerotouch-ownership-voucher</namespace>
      <conformance>implement</conformance>
    </module>
    <module-set-id>6</module-set-id>
  </modules>
</libyang>

**Comment by rkrejci** [comment]
libyang stores only schemas inside the context, data parsed by lyd_parse() are returned and under the control of the caller.

**Comment by rkrejci** [comment]
do not call `ly_ctx_info()` - its purpose is to get information about the schemas in context, it doesn't access any other data parsed by lyd_parse()

**Comment by randyrandhawa** [comment]
Ok, got it. Its working now. I misunderstood due to the following comment:

Context is used to hold all information about schemas. Usually, the application is supposed to work with a single context in which libyang is holding all data models and other internal information according to which the data will be processed and validated. <b>Therefore, both schema and data trees are connected with a specific context.</b>

**Comment by rkrejci** [comment]
ok, actually the data tree *is* connected with the context - strings are stored inside a dictionary that is part of the context and it points to the schema which is also inside the context. However, data tree is not as tightly connected with context as schemas which are internally stored as part of the context. I will try to clarify it more in documentation, thanks.
