### ISSUE TITLE
Does libyang have any plan to support the push method of parsing

### ISSUE THREAD

**Issue by nickylba** [CESNET/libyang#500]
Currently the libyang parser like **lyxml_parse_mem**(struct ly_ctx *ctx, const char *data, int options) only accept a entire string from memory for parameter **data**

This may be a problem for embeded devices which does not have continuous memory for holding the big string (for ex. the entire XML maybe 10Mb).   BTW, there are still enough small memory to hold such XML in that embeded device

So does libyang have any plan to implement the push method like the push method described for libxml2 in http://xmlsoft.org/library.html ?  Or any better way to implement that in libyang?

**Comment by jktjkt** [comment]
What exactly do you mean by "continuous memory"? Note that libyang targets operating systems which provide usable [virtual memory](https://en.wikipedia.org/wiki/Virtual_memory), such as Linux. On these systems, userspace applications do not really have to deal with physical memory fragmentation.

**Comment by michalvasko** [comment]
Hi,
we have no plans to support anything like the push method described, you are the first asking for it. Also, we are used to some devices having small storage space but most of them have more than enough operational memory so 10MB is not a problem for them.

Regards,
Michal

**Comment by nickylba** [comment]
I have mis-understanding about virtual-memory and memory fragementation, thanks for your explanation, sorry for reply too later as I m trying to understand that
