### ISSUE TITLE
Issue with yang and yin printers regarding typedefs in submodules

### ISSUE THREAD

**Issue by aweast** [CESNET/libyang#501]
There is an issue with the yang and yin printers regarding typedefs defined in submodules. Looking at the yang models below, model `E` imports `D` and uses `d-type` which is defined in `D`'s submodule.

```
module d {
  namespace "urn:d";
  prefix d_mod;

  include dsub;
}
```
```
submodule dsub {
  belongs-to d {
    prefix d_mod;
  }

  typedef d_type {
      type string;
  }
}
```
```
module e {
  namespace "urn:e";
  prefix e_mod;

  import d {
      prefix d_mod;
  }

  container top {
    leaf leaf {
      type d_mod:d_type;
    }
  }
}
```

When using `lys_print_mem`, the prefix for the type on `/e_mod:top/e_mod:leaf` is not correctly show. Below is the current output:
```
module e {
  namespace "urn:e";
  prefix e_mod;

  import d {
    prefix d_mod;
  }

  container top {
    leaf leaf {
      type (null):d_type;
    }
  }
}
```

The issue appears to occur in `yang_print_type()` in `printer_yang.c` (and it's yin counterpart).

**Comment by fredgan** [comment]
Since it's resolved, close the issue.
