### ISSUE TITLE
Announcement: devel branch data optimizations

### ISSUE THREAD

**Issue by michalvasko** [CESNET/libyang#508]
Hi everyone,
I just wanted to mention that starting from version 0.15.97 *libyang* includes optimizations of almost all important data tree API operations. This comes at the cost of somehow increased memory every data tree requires (around 20% more) but can be turned off using a compile-time variable `ENABLE_CACHE` (which is `ON` by default now). Specifically, `lyd_insert_*`, `lyd_diff`, `lyd_merge`, `lyd_find_path`, and  `lyd_new_path` were optimized (and, of course, other functions that internally used these ones, which comes to almost all data functions).

The bigger the data tree you work with, the bigger the optimization should be. I have worked with a data tree of 10 000 list instances and 10 000 leaf-list instances and the operations were faster from around 20 times to 300 times. I would now like to ask any of you that work with similarly large or even larger datastores to try the current *libyang* `devel` and report if you think some operations take longer than you think they should. To be specific, I am aware that a lot of `lyd_find_path` XPath expressions are not evaluated as effectively as they could be. However, I have optimized certain basic ones (used in *sysrepo*) and do not want to spend time on some expressions that will almost never be used. So, if you have some reasonable use-case that you think is fairly common, I will gladly take a look and see what I can do.

Best regards,
Michal

PS: I am mentioning only *libyang* on purpose. We are currently working on further *sysrepo* optimizations, which will still take some time, so *sysrepo* use-cases should get faster in the future and it is too soon for any public evaluation. Nevertheless, *sysrepo* naturally works much faster with large datastores with the recent *libyang* `devel`.

**Comment by rwestphal** [comment]
This is very interesting! Please give me a couple of days to test these optimizations :)
