### ISSUE TITLE
embedded notification with mandatory true descendent

### ISSUE THREAD

**Issue by kwatsen** [CESNET/libyang#512]
[This is using today's pull of the "devel" branch]

Copy/pasting the second example listed in RFC 7950 Section 7.16 into the files "example-interface-module.yang" and "notification.xml" ("interfaces" node extracted), and creating a file called "running.xml" as follows:
```
<interfaces xmlns="urn:example:interface-module">
  <interface>
    <name>eth1</name>
  </interface>
</interfaces>
```
and then running the commands:
```
# yanglint -s example-interface-module.yang running.xml
# yanglint -s -t notif -r running.xml example-interface-module.yang notification.xml
```
produces no errors (yeah!), but editing example-interface-module.yang by adding a "mandatory true" under the "by-user" leaf gives this:
```
# yanglint -s example-interface-module.yang running.xml
err : Missing required element "by-user" in "interface". (/example-interface-module:interfaces/interface[name='eth1'])

# yanglint -s -t notif -r running.xml example-interface-module.yang notification.xml
err : Missing required element "by-user" in "interface". (/example-interface-module:interfaces/interface[name='eth1'])
yanglint error: Failed to parse the running datastore file for RPC/Notification validation.
```

I believe this is an error.  RFC 7950 Section 7.16 clearly indicates that the notification tree is not part of any datastore (including running), and even explicitly says:
```
   If a leaf in the notification tree has a "mandatory" statement with
   the value "true", the leaf MUST be present in a notification
   instance.
```

When validating running datastore, the presence of the embedded notification should be ignored.

Thanks,
Kent

**Comment by michalvasko** [comment]
Hi Kent,
you are right, of course. It should be fixed now, thanks.

Regards,
Michal

**Comment by kwatsen** [comment]
Hi Michal,

Thanks!  But did this fix get committed into the "devel" branch?  - I don't see it in `git log`...

Kent

**Comment by michalvasko** [comment]
Hi Kent,
it is the commit referenced here (2414760360d82b4b3e19a0d16c47ccb0a6a19468), in `devel` branch.

Regards,
Michal

**Comment by kwatsen** [comment]
Hi Michal,

Sorry, my git-fu was mess up  (I don't work with branches much)  - I got 
it now, thanks!

FWIW, I think I there is a regression of some sort:

    # yanglint example-interface-module.yang
    err : Invalid keyword "type" as a child to "annotation". (/)
    err : Module "yang" parsing failed.


This is with the module from RFC 7950 Section 7.16.3:

    module example-interface-module {
       yang-version 1.1;
       namespace "urn:example:interface-module";
       prefix "if";

       container interfaces {
         list interface {
           key "name";
           leaf name {
             type string;
           }
           notification interface-enabled {
             leaf by-user {
               type string;
             }
           }
         }
       }
    }


Actually, the same error occurs even with the "notification" removed...

Kent

**Comment by michalvasko** [comment]
Hi Kent,
it should not be a regression but an issue described in [FAQ](https://github.com/CESNET/libyang/blob/master/FAQ.md).

Regards,
Michal
