### ISSUE TITLE
Comment of lys_parse_xxx functions should be updated

### ISSUE THREAD

**Issue by deemar** [CESNET/libyang#514]
https://github.com/CESNET/libyang/blob/f03a3d39fa7897de895c3367c5de4ae33c8c0080/src/tree_schema.h#L1993

It is declared YANG format is supported in README, which is conflict with this line of function description. I suppose this line is error. Is that right?

**Comment by michalvasko** [comment]
Hi,
a really old note, YANG is supported for quite some time now, thanks for noticing.

Regards,
Michal
