### ISSUE TITLE
Ability to consult the list of loaded plugins

### ISSUE THREAD

**Issue by rwestphal** [CESNET/libyang#516]
Hi,

During the initialization of my program, I need to ensure that the required libyang plugins (currently only one .so for user types) were loaded successfully, and abort execution if that doesn't happen.

The problem I see is that the list of loaded plugins doesn't seem to be exposed via the public API. `type_plugins` and `dlhandlers` are both static variables inside _src/plugins.c_ and I didn't find any public function to fetch the list of loaded plugins from these variables. Would it be possible to add a new helper function to expose this information?

Thanks in advance,
Renato.

**Comment by michalvasko** [comment]
Hi Renato,
`ly_get_loaded_plugins()` should do the trick.

Regards,
Michal

**Comment by rwestphal** [comment]
Thanks a lot, that did the trick :D
