### ISSUE TITLE
Test failure in sysrepo's nacm_test with libyang commit 35f46a8

### ISSUE THREAD

**Issue by alangefe** [CESNET/libyang#518]
When I run the latest sysrepo tests together with the latest libyang commit, sysrepo's `nacm_test` fails:

```
96% tests passed, 2 tests failed out of 55

Total Test time (real) = 1077.43 sec

The following tests FAILED:
	 35 - nacm_test (Failed)
	 36 - nacm_test_valgrind (Failed)
```

The tests are running fine with libyang commit 6623989, so 35f46a8 seems to have introduced the failure.

**Comment by michalvasko** [comment]
Hi,
sorry about that, it should be fixed now.

Regards,
Michal
