### ISSUE TITLE
Target set's number not updated in ly_set_merge

### ISSUE THREAD

**Issue by deemar** [CESNET/libyang#519]
https://github.com/CESNET/libyang/blob/323a8a5898c8605b95bb31fd9943ddc3677cdfb9/src/tree_data.c#L5712

Hi
Target set's size is updated, but the number is not. Is that on purpose?

**Comment by michalvasko** [comment]
Hi,
yes, already fixed in `devel`, merged into `master` as e014da0828915e90c843dc16bf1ed03ba25439b9.

Regards,
Michal
