### ISSUE TITLE
Support semantic check for yang model?

### ISSUE THREAD

**Issue by Choosue** [CESNET/libyang#521]
In case that my title doesn't explained itself. For example, I have a model say "example.yang" (has no meaning, only for demonstration). Its hierarchy is like this:

```yang
module: example
   +--rw config
   |  +--rw policy
   |  |  +--rw policies* [id]
   |  |     +--rw actions
   |  |     |  +--rw action-rule* [type]
   |  |     |  |  +--rw type                    identityref
   |  |     |  |  +--rw action-rule-group!
```

Where the `action-rule-group`  is a grouping node that augmented to node `action-rule`:

```yang
augment "/config/policy/policies/actions/action-rule" {
    when "/config/policy/policies/actions/action-rule/type = 'file' ";
    uses action-rule-group {
        description "action rule group";
    }
 }
```

However, the `when` statement in the augment node has semantic error, because the node `/config/policy/policies/actions/action-rule/type` cannot be set as value `file` (it's an identity type node, and it can only be set as `dir` or `cache`). Can libyang support such semantic check? If not, will you guys plan to do so? @rkrejci @michalvasko @PavolVican

**Comment by michalvasko** [comment]
Hi,
semantic check is supported now :) Actually, I have simply changed the default verbosity from **errors** to **warnings** because you are not the first person missing these checks even though they are already implemented (but written as warnings which were hidden by default).

Regards,
Michal

**Comment by Choosue** [comment]
Thanks!
BTW, since which version of libyang did it started to support semantic check? Will `yanglint` generate such **warnigs** and how can I see it?

**Comment by michalvasko** [comment]
Well, the very first checks were added on 17.08.2017 (version `0.13.44`) but they were updated/enhanced several times since then. In `yanglint` you simply need to increase verbosity like I said (to learn how to do that, use help).

Regards,
Michal

**Comment by Choosue** [comment]
Thank you, and in case others don't know exactly what happened. You simply use `help` in `yanglint` and find `verb` command which has four types of verbosity:

```c
verb (error/0 | warning/1 | verbose/2 | debug/3)
```

Then, have fun!
