### ISSUE TITLE
Support for new version of nacm

### ISSUE THREAD

**Issue by gitter-runner** [CESNET/libyang#533]
Hello,
Do you plan to support the new version of nacm  [RFC 8341](https://tools.ietf.org/html/rfc8341) which supports new capabilities from Yang 1.1 [RFC 7950](https://tools.ietf.org/html/rfc7950)? If yes, will it be implemented in sysrepo?

Best regards,
Tamas

**Comment by michalvasko** [comment]
Hi Tamas,
the module was updated in sysrepo, there are no functional changes, actions and nested notifications were already supported.

Regards,
Michal
