### ISSUE TITLE
edit-config operation fail for messages with nc prefix in <rpc> element

### ISSUE THREAD

**Issue by ctrl-l** [CESNET/libyang#535]
Hello. 
**Brief description**
edit-config requests fail if request message has nc prefix in `<rpc>` tag. I expect it not failing cause get-config requests with such prefix works fine with sysrepo.

**Details**
I found it while i was testing how ncclient works with sysrepo. For example, i want to change data for module ietf-interfaces with such xml (to be short next i will replace it with CHANGE_IETF_INTERFACE_XML):
```xml
<interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
  <interface>
    <name>eth0</name>
    <enabled>false</enabled>
 </interface>
</interfaces>
```
when i send this message from netopeer2-cli in netopeer2-server debug log i see this:
```
DEBUG: Session 1: received message:
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="17">
	<edit-config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
		<target><candidate/></target>
		<config>
			CHANGE_IETF_INTERFACE_XML
		</config>
	</edit-config>
</rpc>
```

when i send the same xml from ncclient in netopeer2-server debug output i see this:
```
DEBUG: Session 3: received message:
<?xml version="1.0" encoding="UTF-8"?>
<nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:6c90a1b4-5917-4904-8f6d-e69ddd48dd38">
	<nc:edit-config>
		<nc:target><nc:candidate/></nc:target>
		<config>
			CHANGE_IETF_INTERFACE_XML
		</config>
	</nc:edit-config>
</nc:rpc>
```
and get this error:
```
ERROR: Missing element's "namespace". (/nc:rpc/nc:edit-config/config)
```
So edit-config request  from ncclient fail. It will pass if i remove prefix nc before rpc(by changing ncclient library sources). I haven't found that it should be nc prefix for `<rpc>` in RFC, so maybe it's a  ncclient issue. But get-config requests from ncclient such as
```xml
<?xml version="1.0" encoding="UTF-8"?>
<nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:2de9604a-4cee-46b2-a570-f72bd8a95188">
    <nc:get-config>
        <nc:source><nc:candidate/></nc:source>
        <nc:filter type="subtree">
            <interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
            </interfaces>
        </nc:filter>
    </nc:get-config>
</nc:rpc>
```
works fine with sysrepo, so i think that it's maybe a bug with handling edit-config with `<nc:rpc>` on server side.

I can reproduce it on libnetconf2, libyang, netopeer2, sysrepo that i've git cloned today.
Server debug output after receiving edit-config message attached.

**Comment by ctrl-l** [comment]
[server.log](https://github.com/CESNET/libyang/files/2165151/server.log)

**Comment by michalvasko** [comment]
Hi,
this is, indeed, an *ncclient* issue. And the error displayed is the exact cause of the problem you just need to read it carefully. The error says that `/nc:rpc/nc:edit-config/config` element does not have a namespace. Looking at the received message, you see that the `config` element really does not have a namespace, it would need to be `nc:config` to work. Without the prefix it uses the parent's namespace which is none in your case.

Regards,
Michal

**Comment by ctrl-l** [comment]
Thank you for the explanation, i understand now. I've send bugreport to ncclient.
