### ISSUE TITLE
ENABLE_CACHE=ON causes improper date constraint regex match failure

### ISSUE THREAD

**Issue by GrumpyOldTroll** [CESNET/libyang#536]
# Broken behavior

If you read this error message carefully, you'll hopefully agree that the given string does satisfy the constraint.

I get this error when using -DENABLE_CACHE=ON to build, but it (properly) does not appear with the same code when using -DENABLE_CACHE=OFF, with no other differences.

~~~
libyang[0]: Value "1985-02-05T00:00:00-00:00" does not satisfy the constraint "\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[\+\-]\d{2}:\d{2})" (range, length, or pattern). (path: /example-sports:sports/person[name='Cristiano Ronaldo']/birthday)
yang-example.c:65: failed lyd_parse_path, json_file=example-data.json
~~~

# Version discovered

I checked this against v0.15-r1, master last week, and today (2018-07-06) on devel. The same problem appears in all 3 branches.

# Steps to reproduce

I have a repo with a simple example program that exhibits the broken behavior in a docker container.

The "bug-report1" branch reproduces the issue, while the "master" branch has the expected behavior. The difference between them is just the -DENABLE_CACHE flag passed to cmake in the Dockerfile.

## Building container with this bug

~~~
git clone https://github.com/GrumpyOldTroll/yang-example -b bug-report1
cd yang-example
docker build -t ybug .
docker run -it --rm --cap-add=SYS_PTRACE --security-opt seccomp=unconfined ybug
~~~

## Reproducing inside container

~~~
yangex@07086a00018c:~$ ./yex
libyang[0]: Value "1985-02-05T00:00:00-00:00" does not satisfy the constraint "\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[\+\-]\d{2}:\d{2})" (range, length, or pattern). (path: /example-sports:sports/person[name='Cristiano Ronaldo']/birthday)
yang-example.c:65: failed lyd_parse_path, json_file=example-data.json
~~~

# Expected behavior

## Building container without this bug

~~~
git checkout master
docker build -t yex .
docker run -it --rm --cap-add=SYS_PTRACE --security-opt seccomp=unconfined yex
~~~

## Expected results inside container

~~~
yangex@51a316e5c9d5:~$ ./yex
read data file example-data.json successfully
found 2 names with person/name
player 0: Cristiano Ronaldo played for 1:
  Real Madrid (scored 48 as #7 in Champions League 2014/2015)
player 1: Lionel Andrés Messi played for 1:
  FC Barcelona (scored 43 as #10 in Champions League 2014/2015)
~~~

**Comment by michalvasko** [comment]
Hi,
it should be fixed now with the latest *libyang*.

Regards,
Michal
