### ISSUE TITLE
yanglint improperly handling multi-line 'if-feature' statements

### ISSUE THREAD

**Issue by jboyd77** [CESNET/libyang#539]
Example:

    container things {
      if-feature "feature-1 and feature-2 and
                  feature-3";

When yanglint parses this, it causes a "Segmentation fault" in Linux. If this is changed to either of the following, yanglint parses successfully.

    container things {
      if-feature "feature-1 and feature-2 and feature-3";

    container things {
      if-feature "feature-1 and feature-2 and "
               + "feature-3";

According to the ABNF grammar in RFC 7950,

    if-feature-stmt     = if-feature-keyword sep if-feature-expr-str
                          stmtend

    if-feature-expr-str = < a string that matches the rule >
                          < if-feature-expr >

the expression is a string which should mean that the rules of quoted strings should apply and the original example, which fails, is valid. pyang parses this without throwing any error.

I am running yanglint 0.15.140.

**Comment by michalvasko** [comment]
Hi,
yep, there were some problems with handling `\n`, should be fixed now. Thanks.

Regards,
Michal
