### ISSUE TITLE
yanglint not handling feature dependencies correctly

### ISSUE THREAD

**Issue by jboyd77** [CESNET/libyang#540]
Example YANG:

    feature other-thing;

    container other-things {
      if-feature other-thing;
      list thing {
        key name;
        leaf name {
          type string;
        }
      }
    }

    container things {
    }

    augment "things" {
      container which-things {
        leaf which-thing {
          type leafref {
            path 'other-things/thing/name';
          }
        }
      }
    }

Since the leafref is referencing a node which depends on the feature ```other-thing```, I would expect an error since the leaf ```which-thing``` is not dependent on the same feature. If fact, yanglint does throw an error. 

yanglint error:

    err : Leafref is not conditional based on "other-thing" feature as its target.

To resolve this I appear to have 3 options, place ```if-feature other-thing``` on either the augment, the container or the leaf. All should more or less be functionally equivalent to resolve the issue (I realize they aren't exactly equivalent in scope.).

However, while placing the ```if-feature``` statement on either the container or the leaf resolves the error, it does not resolve it if I place it on the augment.

    augment "things" {
      if-feature other-thing;
      container which-things {
        leaf which-thing {
          type leafref {
            path 'other-things/thing/name';
          }
        }
      }

yanglint error:

    err : Leafref is not conditional based on "other-thing" feature as its target.

I would assume this should have worked as the container/leaf would not exist if the feature is not supported so the leafref does not apply.

I am using yanglint 0.15.140.

**Comment by michalvasko** [comment]
Hi,
good catch, fixed.

Regards,
Michal
