### ISSUE TITLE
where is the keystore daemon

### ISSUE THREAD

**Issue by feldi59** [CESNET/libyang#541]
Hi,

i just updated the whole toochain (libyang, libnetconf, sysrepo, netopeer) at master branch.

Now it seems that the ietf-keystore daemon is missing.
I have manually deleted it from /usr/local/lib/sysrepo/plugins/libkeystored.so otherwise the sysrepod produces errors.
Was that desired ?

Next is that the netopeer server does not start: 
ERROR: Module "ietf-netconf" not implemented in sysrepo.
ERROR: Server init failed.
VERBOSE: (cl_sm_cleanup:1796) Client Subscription Manager successfully destroyed.

could you please tell me what is wrong now

The whole log:
necxe@necxe:netconf_yang$ sudo netopeer2-server -d -v 3
[sudo] password for necxe: 
VERBOSE: (sr_connect:435) Connected to daemon Sysrepo Engine at socket=/tmp/sysrepod.sock
VERBOSE: Netopeer2 connected to sysrepod.
VERBOSE: Plugin "/usr/local/lib/libyang/extensions/libyang_ext_test.so" successfully loaded.
VERBOSE: Plugin "/usr/local/lib/libyang/extensions/metadata.so" successfully loaded.
VERBOSE: Plugin "/usr/local/lib/libyang/extensions/yangdata.so" successfully loaded.
VERBOSE: Plugin "/usr/local/lib/libyang/extensions/nacm.so" successfully loaded.
VERBOSE: Plugin "/usr/local/lib/libyang/user_types/user_date_and_time.so" successfully loaded.
VERBOSE: Reading module "ietf-yang-metadata".
VERBOSE: Module "ietf-yang-metadata@2016-08-05" successfully parsed as implemented.
VERBOSE: Reading module "yang".
VERBOSE: Resolving "yang" unresolved schema nodes and their constraints...
VERBOSE: All "yang" schema nodes and constraints resolved.
VERBOSE: Module "yang@2017-02-20" successfully parsed as implemented.
VERBOSE: Reading module "ietf-inet-types".
VERBOSE: Resolving derived type "union" failed, it will be attempted later.
VERBOSE: Resolving derived type "union" failed, it will be attempted later.
VERBOSE: Resolving derived type "union" failed, it will be attempted later.
VERBOSE: Resolving derived type "union" failed, it will be attempted later.
VERBOSE: Resolving "ietf-inet-types" unresolved schema nodes and their constraints...
VERBOSE: All "ietf-inet-types" schema nodes and constraints resolved.
VERBOSE: Module "ietf-inet-types@2013-07-15" successfully parsed as implemented.
VERBOSE: Reading module "ietf-yang-types".
VERBOSE: Module "ietf-yang-types@2013-07-15" successfully parsed as implemented.
VERBOSE: Reading module "ietf-datastores".
VERBOSE: Module "ietf-datastores@2017-08-17" successfully parsed as implemented.
VERBOSE: Reading module "ietf-yang-library".
VERBOSE: Module "ietf-yang-library@2018-01-17" successfully parsed as implemented.
VERBOSE: Loading schema "example-module" from sysrepo.
VERBOSE: Reading module "example-module".
VERBOSE: Module "example-module" successfully parsed as implemented.
VERBOSE: Loading schema "test-module" from sysrepo.
VERBOSE: Reading module "test-module".
VERBOSE: Reading module "referenced-data".
VERBOSE: Module "referenced-data" successfully parsed as imported.
VERBOSE: Resolving "test-module" unresolved schema nodes and their constraints...
VERBOSE: All "test-module" schema nodes and constraints resolved.
VERBOSE: Module "test-module" successfully parsed as implemented.
VERBOSE: Loading schema "referenced-data" from sysrepo.
VERBOSE: Module referenced-data already present in context.
VERBOSE: Module "referenced-data" now implemented.
VERBOSE: Loading schema "small-module" from sysrepo.
VERBOSE: Reading module "small-module".
VERBOSE: Module "small-module" successfully parsed as implemented.
VERBOSE: Loading schema "info-module" from sysrepo.
VERBOSE: Reading module "info-module".
VERBOSE: Reading module "small-module".
VERBOSE: Module "small-module@<latest>" already in context.
VERBOSE: Module "small-module" successfully parsed as implemented.
VERBOSE: Module "info-module" successfully parsed as implemented.
VERBOSE: Loading schema "id-ref-base" from sysrepo.
VERBOSE: Reading module "id-ref-base".
VERBOSE: Module "id-ref-base" successfully parsed as implemented.
VERBOSE: Loading schema "id-ref-aug" from sysrepo.
VERBOSE: Reading module "id-ref-aug".
VERBOSE: Reading module "id-ref-base".
VERBOSE: Module "id-ref-base@<latest>" already in context.
VERBOSE: Module "id-ref-base" successfully parsed as implemented.
VERBOSE: Reading module "id-def-base".
VERBOSE: Module "id-def-base" successfully parsed as imported.
VERBOSE: Module "id-ref-aug" successfully parsed as implemented.
VERBOSE: Loading schema "id-def-base" from sysrepo.
VERBOSE: Module id-def-base already present in context.
VERBOSE: Module "id-def-base" now implemented.
VERBOSE: Loading schema "id-def-extended" from sysrepo.
VERBOSE: Reading module "id-def-extended".
VERBOSE: Module "id-def-extended" successfully parsed as implemented.
VERBOSE: Loading schema "module-a@2016-02-10" from sysrepo.
VERBOSE: Reading module "module-a".
VERBOSE: Reading submodule "sub-a-one".
VERBOSE: Submodule "sub-a-one" successfully parsed.
VERBOSE: Reading submodule "sub-a-two".
VERBOSE: Submodule "sub-a-two" successfully parsed.
VERBOSE: Module "module-a@2016-02-10" successfully parsed as implemented.
VERBOSE: Loading schema "module-b@2016-02-05" from sysrepo.
VERBOSE: Reading module "module-b".
VERBOSE: Reading module "module-a".
VERBOSE: Reading submodule "sub-a-one".
VERBOSE: Submodule "sub-a-one" successfully parsed.
VERBOSE: Reading submodule "sub-a-two".
VERBOSE: Submodule "sub-a-two" successfully parsed.
VERBOSE: Module "module-a@2016-02-02" successfully parsed as imported.
VERBOSE: Module "module-b@2016-02-05" successfully parsed as implemented.
VERBOSE: Loading schema "module-a@2016-02-02" from sysrepo.
VERBOSE: Module module-a@2016-02-02 already present in context.
VERBOSE: Loading schema "ietf-interfaces@2014-05-08" from sysrepo.
VERBOSE: Reading module "ietf-interfaces".
VERBOSE: Module "ietf-interfaces@2014-05-08" successfully parsed as implemented.
VERBOSE: Loading schema "iana-if-type@2014-05-08" from sysrepo.
VERBOSE: Reading module "iana-if-type".
VERBOSE: Reading module "ietf-interfaces".
VERBOSE: Module "ietf-interfaces@2014-05-08" already in context.
VERBOSE: Module "ietf-interfaces@2014-05-08" successfully parsed as implemented.
VERBOSE: Module "iana-if-type@2014-05-08" successfully parsed as implemented.
VERBOSE: Loading schema "ietf-ip@2014-06-16" from sysrepo.
VERBOSE: Reading module "ietf-ip".
VERBOSE: Module "ietf-ip@2014-06-16" successfully parsed as implemented.
VERBOSE: Loading schema "state-module@2016-07-01" from sysrepo.
VERBOSE: Reading module "state-module".
VERBOSE: Module "state-module@2016-07-01" successfully parsed as implemented.
VERBOSE: Loading schema "top-level-mandatory" from sysrepo.
VERBOSE: Reading module "top-level-mandatory".
VERBOSE: Module "top-level-mandatory" successfully parsed as implemented.
VERBOSE: Loading schema "cross-module" from sysrepo.
VERBOSE: Reading module "cross-module".
VERBOSE: Resolving "cross-module" unresolved schema nodes and their constraints...
VERBOSE: All "cross-module" schema nodes and constraints resolved.
VERBOSE: Module "cross-module" successfully parsed as implemented.
VERBOSE: Loading schema "turing-machine@2013-12-27" from sysrepo.
VERBOSE: Reading module "turing-machine".
VERBOSE: Module "turing-machine@2013-12-27" successfully parsed as implemented.
VERBOSE: Loading schema "ietf-netconf-notifications@2012-02-06" from sysrepo.
VERBOSE: Reading module "ietf-netconf-notifications".
VERBOSE: Reading module "ietf-netconf".
VERBOSE: Reading module "ietf-netconf-acm".
VERBOSE: Module "ietf-netconf-acm@2012-02-22" successfully parsed as imported.
VERBOSE: Module "ietf-netconf@2011-06-01" successfully parsed as imported.
VERBOSE: Resolving "ietf-netconf-notifications" unresolved schema nodes and their constraints...
VERBOSE: All "ietf-netconf-notifications" schema nodes and constraints resolved.
VERBOSE: Module "ietf-netconf-notifications@2012-02-06" successfully parsed as implemented.
VERBOSE: Loading schema "ietf-netconf@2011-06-01" from sysrepo.
VERBOSE: Module ietf-netconf@2011-06-01 already present in context.
VERBOSE: Loading schema "ietf-netconf-acm@2012-02-22" from sysrepo.
VERBOSE: Module ietf-netconf-acm@2012-02-22 already present in context.
VERBOSE: Loading schema "nc-notifications@2008-07-14" from sysrepo.
VERBOSE: Reading module "nc-notifications".
VERBOSE: Reading module "notifications".
VERBOSE: Module "notifications@2008-07-14" successfully parsed as imported.
VERBOSE: Module "nc-notifications@2008-07-14" successfully parsed as implemented.
VERBOSE: Loading schema "notifications@2008-07-14" from sysrepo.
VERBOSE: Module notifications@2008-07-14 already present in context.
VERBOSE: Module "notifications@2008-07-14" now implemented.
VERBOSE: Loading schema "servers" from sysrepo.
VERBOSE: Reading module "servers".
VERBOSE: Module "servers" successfully parsed as implemented.
VERBOSE: Loading schema "swig-test-cpp-changes@2017-03-09" from sysrepo.
VERBOSE: Reading module "swig-test-cpp-changes".
VERBOSE: Module "swig-test-cpp-changes@2017-03-09" successfully parsed as implemented.
VERBOSE: Loading schema "swig-test-cpp-operations@2017-03-09" from sysrepo.
VERBOSE: Reading module "swig-test-cpp-operations".
VERBOSE: Module "swig-test-cpp-operations@2017-03-09" successfully parsed as implemented.
VERBOSE: Loading schema "swig-test@2017-03-09" from sysrepo.
VERBOSE: Reading module "swig-test".
VERBOSE: Module "swig-test@2017-03-09" successfully parsed as implemented.
ERROR: Module "ietf-netconf" not implemented in sysrepo.
ERROR: Server init failed.
VERBOSE: (cl_sm_cleanup:1796) Client Subscription Manager successfully destroyed.
necxe@necxe:~/netconf_yang$

**Comment by michalvasko** [comment]
Hi,
you just need to `make install` `keystored` (`netopeer2/keystored`) and `netopeer2-server`, then it should work.

Regards,
Michal

**Comment by feldi59** [comment]
Hi,
Thanks a lot - i forgot to do the make install :-(
But do you have a hint for my second question ?
ERROR: Module "ietf-netconf" not implemented in sysrepo.
ERROR: Server init failed.

**Comment by michalvasko** [comment]
Hi,
yeah, my hint is `make install` on `netopeer2-server`.

Regards,
Michal

**Comment by feldi59** [comment]
:+1: thanks !!!

**Comment by fredgan** [comment]
It seems this issue is solved, so close it.
