### ISSUE TITLE
yanglint improperly handling multi-line 'if-feature' statements with prefixes

### ISSUE THREAD

**Issue by jboyd77** [CESNET/libyang#542]
This is a follow up to #539. 

Now, an error occurs if the features are from an imported module which means the prefix must be used. This does not occur if the features are local with no prefix.

Example:

    container things {
      if-feature "other-mod:feature-a and
                  other-mod:feature-b";

yanglint throws an error similar to this:

    err : Unexpected character(s) '
    ' (
    other-mod:feature).

As before, defining it all on one line or using explicitly concatenated strings validates error free.

    container things {
      if-feature "other-mod:feature-a and other-mod:feature-b";

    container things {
      if-feature "other-mod:feature-a and"
               + "other-mod:feature-b";

**Comment by michalvasko** [comment]
Hi,
should work now.

Regards,
Michal
