### ISSUE TITLE
lyd_parse_xml parsing behavior

### ISSUE THREAD

**Issue by pathori** [CESNET/libyang#553]
Below are some of the examples for parsing behavior by the API **_lyd_parse_xml_** when used with option LYD_OPT_STRICT. Please clarify the behavior

1. leaf node has a child pasrsed successfully -- I think it should be an error.
```xml
<get xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <filter xmlns:t="urn:ietf:params:xml:ns:yang:ietf-netconf-acm"
          type="xpath" select="/t:nacm/t:enable-nacm[t:read-default='permit']"/>
</get>
```
2. Below xpath has codition at list level -- I think it should be an error.
```xml
<get xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <filter xmlns:t="urn:ietf:params:xml:ns:yang:ietf-netconf-acm"
          type="xpath"
          select="/t:nacm[t:rule-list='1']"/>
</get>
```
3. Same leaf provided as content match and selection -- I think it is valid case and should not be an error
but this report error saying "Too many instances"
```xml
<get-config>
  <source>
    <candidate/>
  </source>
  <filter type="subtree">
    <acm:nacm xmlns:acm="urn:ietf:params:xml:ns:yang:ietf-netconf-acm">
      <acm:rule-list>
        <acm:rule>
          <acm:name>1</acm:name>
          <acm:name>1</acm:name>
        </acm:rule>
      </acm:rule-list>
    </acm:nacm>
  </filter>
</get-config>
```

**Comment by michalvasko** [comment]
Hi,
`LYD_OPT_STRICT` applies only to data nodes, not to attributes.

 1. Like I said, during parsing the XPath is simply a string.
 2. Same explanation.
 3. This has nothing to do with the options used. 2 equal instances of one leaf were found, so an error was raised. It is true that no RFC requires this as far as I know, but does not forbid it either, so I think it is fine.

Regards,
Michal

**Comment by pathori** [comment]
So at which stage libyang process it as error? here I just mentioned the equivalent sub-tree, what would be the behavior?
```
<get-config>
<source>
<candidate/>
</source>
<filter type="subtree">
<nacm xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-acm">
<enable-nacm>
<read-default>permit</read-default>
</enable-nacm>
</nacm>
</filter>
</get-config>
```

```
<get-config>
<source>
<candidate/>
</source>
<filter type="subtree">
<nacm xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-acm">
<rule-list>1
</rule-list>
</nacm>
</filter>
</get-config>
```

**Comment by michalvasko** [comment]
Hi,
you mean when would those 2 XPaths cause an error? The answer is never, they would just always return empty data.

Regards,
Michal

**Comment by pathori** [comment]
Ok, What would be the behavior for the sub-tree provided in the filter element?
1. <read-default> is provided as child of <enable-nacm>
2. <rule-list> has some extra text after the start tag

**Comment by pathori** [comment]
I checked it but not return error. Could please confirm? I could not find code process that as error in API **_lyd_parse_xml_** .

**Comment by michalvasko** [comment]
Hi,
I currently have a lot of issues and other work I should do, so in order for me to help you, please provide the exact `lyd_parse_xml()` call (with all the parameters and flags), the exact XML you are trying to parse, and the result so that I can test and fix it quickly. Thank you.

Regards,
Michal

**Comment by pathori** [comment]
I have sample code like this, I have not mentioned loading of module in this code snippet.

```
    char *xml = "<get-config> \
<source> \
<candidate/> \
</source> \
<filter type=\"subtree\"> \
<nacm xmlns=\"urn:ietf:params:xml:ns:yang:ietf-netconf-acm\">
<enable-nacm>
<read-default>permit</read-default>
</enable-nacm>
</nacm>
</filter>
</get-config>";
    struct ly_ctx *ctx = NULL;
    struct lyxml_elem *root_xml = NULL;
    struct lyd_node *node = NULL;

    ctx = ly_ctx_new(yang_folder, 0);
    if (!ctx) {
        return -1;;
    }

    root_xml = lyxml_parse_mem(ctx, xml, 0);
    if (!root_xml) {
        return -1;
    }

   node = lyd_parse_xml(ctx, &root_xml, (LYD_OPT_GETCONFIG | LYD_OPT_STRICT));
   if (!node)
   {
     return -1;
   }

```

**Comment by michalvasko** [comment]
Hi,
most importantly, do not parse it with `LYD_OPT_GETCONFIG`, that is used for parsing `<get-config>` replies, not the RPC itself (so, you should use `LYD_OPT_RPC` because that is what you are parsing). Also, `filter` is defined as `anyxml` so *libyang* has no information about what it is, just a generic XML. That means it will not be validated at all.

Regards,
Michal

**Comment by pathori** [comment]
Sorry, By miskate I had mentioned the wrong xml. Please find the correct XML files.
1.  XML with leaf node has child
```
char *xml = "<nacm xmlns=\"urn:ietf:params:xml:ns:yang:ietf-netconf-acm\">
<enable-nacm>
<read-default>permit</read-default>
</enable-nacm>
</nacm>";
```
2. XML with non leaf node has extra content
```
char *xml = "<nacm xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-acm">\
<rule-list>1\
</rule-list>\
</nacm>";
```

**Comment by michalvasko** [comment]
Hi,
so I have tried loading both these files with your sample code and both failed to be parsed, with or without `LYD_OPT_STRICT` (contrary to what I thought, the errors are too severe). If your experience is different, try updating *libyang*.

Regards,
Michal

**Comment by michalvasko** [comment]
Hi,
sorry, you will have to find it yourself. We provide support only with up-to-date *libyang* versions so as not to waste time looking for issues that were already fixed, which just happened.

Regards,
Michal
