### ISSUE TITLE
Segfault when unloading module with deviations

### ISSUE THREAD

**Issue by rwestphal** [CESNET/libyang#554]
Hi,

I'm getting segfaults like this in my program whenever I unload a module that contains several YANG deviations:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6534cdb in lys_check_id (node=0x89f4d0, parent=0xa2d620, module=0x89afd0) at /mnt/renato/git/northbound/lang-c/libyang/src/tree_schema.c:694
(gdb) bt
#0  0x00007ffff6534cdb in lys_check_id (node=0x89f4d0, parent=0xa2d620, module=0x89afd0) at /mnt/renato/git/northbound/lang-c/libyang/src/tree_schema.c:694
#1  0x00007ffff65353fb in lys_node_addchild (parent=0xa2d620, module=0x89afd0, child=0x89f4d0) at /mnt/renato/git/northbound/lang-c/libyang/src/tree_schema.c:846
#2  0x00007ffff653f776 in lys_switch_deviation (dev=0x8abfa8, module=0x8ace60, unres=0x7be5c0) at /mnt/renato/git/northbound/lang-c/libyang/src/tree_schema.c:4163
#3  0x00007ffff653ff01 in remove_dev (dev=0x8abfa8, module=0x8ace60, unres=0x7be5c0) at /mnt/renato/git/northbound/lang-c/libyang/src/tree_schema.c:4321
#4  0x00007ffff654036b in lys_sub_module_remove_devs_augs (module=0x8ace60) at /mnt/renato/git/northbound/lang-c/libyang/src/tree_schema.c:4399
#5  0x00007ffff64b33bf in ly_ctx_remove_module (module=0x8ace60, private_destructor=0x0) at /mnt/renato/git/northbound/lang-c/libyang/src/context.c:1411
#6  0x00007ffff7b8d339 in yang_module_unload (module=0x8ace60) at lib/yang_module_translator.c:45
[snip]
```

Fortunately the problem can be reproduced using _yanglint_ (my favorite new tool, much more powerful than anything else):
```
$ yanglint
> add /usr/local/share/yang/ietf-rip@2018-02-03.yang
> add /usr/local/share/yang/frr-deviations-ietf-rip.yang
> exit
Segmentation fault
```

The segfault happen regardless if the _frr-deviations-ietf-rip_ module is unloaded using `ly_ctx_remove_module()` or `ly_ctx_destroy()`.

Here are the two modules used in this test:
* ietf-rip.yang: https://github.com/YangModels/yang/blob/master/experimental/ietf-extracted-YANG-modules/ietf-rip%402018-02-03.yang
* frr-deviations-ietf-rip.yang: https://gist.github.com/rwestphal/0a8caa319c570b712842ee8aa9a635df

I'm using the latest version of _libyang_ from _master_ (0.15.151).

Any help would be appreciated!

**Comment by michalvasko** [comment]
Hi,
should work now.

Regards,
Michal

**Comment by rwestphal** [comment]
Thanks a lot Michal :)

Unfortunately the same crash still happens when unloading other YANG modules:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6534fe2 in lys_check_id (node=0x89f4d0, parent=0xa2d620, module=0x89afd0) at /mnt/renato/git/northbound/lang-c/libyang/src/tree_schema.c:694
(gdb) bt
#0  0x00007ffff6534fe2 in lys_check_id (node=0x89f4d0, parent=0xa2d620, module=0x89afd0) at /mnt/renato/git/northbound/lang-c/libyang/src/tree_schema.c:694
#1  0x00007ffff6535702 in lys_node_addchild (parent=0xa2d620, module=0x89afd0, child=0x89f4d0) at /mnt/renato/git/northbound/lang-c/libyang/src/tree_schema.c:846
#2  0x00007ffff653fa7d in lys_switch_deviation (dev=0x8abfa8, module=0x8ace60, unres=0x7be5c0) at /mnt/renato/git/northbound/lang-c/libyang/src/tree_schema.c:4164
#3  0x00007ffff6540379 in remove_dev (dev=0x8abfa8, module=0x8ace60, unres=0x7be5c0) at /mnt/renato/git/northbound/lang-c/libyang/src/tree_schema.c:4341
#4  0x00007ffff65407e3 in lys_sub_module_remove_devs_augs (module=0x8ace60) at /mnt/renato/git/northbound/lang-c/libyang/src/tree_schema.c:4419
#5  0x00007ffff64b33bf in ly_ctx_remove_module (module=0x8ace60, private_destructor=0x0) at /mnt/renato/git/northbound/lang-c/libyang/src/context.c:1411
#6  0x00007ffff7b8d439 in yang_module_unload (module=0x8ace60) at lib/yang_module_translator.c:45
```

Once again I can reproduce the crash using _yanglint_:
```
$ yanglint
> add /usr/local/share/yang/ietf-interfaces@2018-02-20.yang
> add /usr/local/share/yang/ietf-routing@2018-03-13.yang
> add /usr/local/share/yang/ietf-rip@2018-02-03.yang
libyang[1]: Identity found, but in a non-implemented module "ietf-isis".
libyang[1]: Failed to resolve identityref "ietf-isis:isis". (path: /ietf-routing:source-protocol)
libyang[1]: Previous warning generated by XPath subexpression[0] "ietf-routing:source-protocol = 'ietf-isis:isis'".
libyang[1]: Identity found, but in a non-implemented module "ietf-isis".
libyang[1]: Failed to resolve identityref "ietf-isis:isis". (path: /ietf-routing:type)
libyang[1]: Previous warning generated by XPath subexpression[0] "ietf-routing:type = 'ietf-isis:isis'".
>
>
> add /usr/local/share/yang/frr-deviations-ietf-interfaces.yang
> add /usr/local/share/yang/frr-deviations-ietf-routing.yang
>
> exit
Segmentation fault
```

YANG modules:
* ietf-interfaces.yang: https://raw.githubusercontent.com/YangModels/yang/master/standard/ietf/RFC/ietf-interfaces%402018-02-20.yang
* ietf-routing.yang: https://raw.githubusercontent.com/YangModels/yang/master/standard/ietf/RFC/ietf-routing%402018-03-13.yang
* ietf-rip.yang: https://raw.githubusercontent.com/YangModels/yang/master/experimental/ietf-extracted-YANG-modules/ietf-rip%402018-02-03.yang
* frr-deviations-ietf-routing.yang: https://gist.githubusercontent.com/rwestphal/01fc2041955bd102e5ef8090764a88c9/raw/1641e99c6f9fbd5d264b85484d16def5e0b7807e/frr-deviations-ietf-routing.yang
* frr-deviations-ietf-interfaces: https://gist.githubusercontent.com/rwestphal/f44f9ec2badc0bc3d5bca6c2f6e1aeb2/raw/a808ee9796cbb1442976d37c42b916bd839e8226/frr-deviations-ietf-interfaces.yang

As a side note, I'm confused about the warnings when I load the ietf-rip module. The warnings can be silenced by loading the ietf-isis module before, but why is this necessary? I'd prefer to just import ietf-isis automatically instead of marking it as implemented.

**Comment by RavikumarTulugu** [comment]
hi , I picked up the commit but the same crash is happening for me as well, which was mentioned in the first comment. Please advise.   I am using the latest libyang from git and not any particular release. 
Thanks 
-rk

**Comment by michalvasko** [comment]
Hi,
@rwestphal The other case should also work now.

@RavikumarTulugu Please try it again with the current version. If a crash still occurs, it is enough if you provide list of models that you loaded and I can try to fix it.

Regards,
Michal

**Comment by rwestphal** [comment]
I confirm the issue was fixed, thanks a lot for the quick fix!
