### ISSUE TITLE
Issue with ENABLE_STATIC flag

### ISSUE THREAD

**Issue by amandeepsethi** [CESNET/libyang#558]
As we cmake using -DENABLE_STATIC=ON, then libnacm.a, libmetadata.a, libuser_date_and_time.a and libyangdata.a files gets compiled but the cmake_install doesn't have command to install them on the same path where the libyang.a is getting installed.

Probably I would prefer to include nacm.c, metadata.c and other C files from "extensions" and "user_types" directory to be compiled into libyang.a directly, if possible. That way, we can include only a single static lib named libyang.a and don't have to worry about including other aforementioned static libraries into our custom build for compilation.

**Comment by mislavn** [comment]
With the current plugin design it's not possible to directly compile the plugins and extensions into libyang.a.

**Comment by mislavn** [comment]
@rkrejci where do you want to put the extensions and user types?
Same as libyang.a!
