### ISSUE TITLE
C++ bindings return a std:vector<T> * instead of returning it by value

### ISSUE THREAD

**Issue by jktjkt** [CESNET/libyang#564]
(I would like to Cc Mislav, but his github account appears to not exist anymore (?).)

We're starting to use the C++ APIs around libyang (thanks for that!). During some debugging, I stumbled upon a widespread pattern where many functions return a `std::vector<std::shared_ptr<Something>> *`. I.e., apart from the regular reference-counted stuff `Something`, the entire vector is returned as a heap-allocated thing via a pointer.

What is the reason for that? I expect these methods to return a plain `std::vector` of refcounted items. The `std::vector` is very cheap to return by value in C++11 (move semantics). The current extra indirection is confusing because there's no code or documentation enforcing the ownership and lifetime. Apparently, the caller is currently expected to `delete` the result which complicates the user code.

Is there perhaps a SWIG/Python requirement for this? Will you accept a patch which simply makes these methods return a plain vector by value?

**Comment by mislavn** [comment]
(I'm not sure what's the issue with my github account, I'll take a look.)

Yes you are right, this is because of SWIG/Python. That was the only way to get a python list of PyObject's.

I think there is a way around this, I could override the method in the SWIG python interface file. Can you give me a day to test and implement this?

**Comment by jktjkt** [comment]
Yes, and thanks for looking into this. My random search suggested that this is something which should be doable by swig's typemaps for vectors, but I've never done that, I'm just offering random suggestions at this point.

**Comment by mislavn** [comment]
It's implemented on my local branch, I'm just waiting for #565 to get merged to make the pull request.

**Comment by jktjkt** [comment]
stuff has been merged, thanks!
