### ISSUE TITLE
Deletion of integer leaf fails beginning in libyang@15e3e61

### ISSUE THREAD

**Issue by alangefe** [CESNET/libyang#566]
When an edit-config is sent to delete a leaf whose type is integer, the server rejects the edit-config with an RPC error. The problem is that validation is incorrectly failing in libyang.

For example, given the following model:

```
container foo {
  leaf bar {
    type uint8;
  }
}
```

And assuming the leaf has been set in the running config, for example:

```
<foo>
  <bar>42</bar>
</foo>
```

When sending an edit-config with a delete operation like so:

```
<config>
  <foo>
    <bar operation="delete"/>
  </foo>
</config>
```

Then the server rejects the edit-config with an RPC error whose message reads: `Invalid value "" in "bar" element.`

The problem was introduced in 15e3e61. In previous commits, this operation succeeds as expected.

I've implemented a unit test at https://github.com/ADTRAN/Netopeer2/commit/4c85abd49fc2d8b705d0278540569ac4943efddb that demonstrates the problem.

**Comment by michalvasko** [comment]
Hi,
sorry about that, the commit is most likely not even needed so I reverted it. Anyway, we will have your use-case to test it in future.

Regards,
Michal
