### ISSUE TITLE
The merge issue when the leaf has default value

### ISSUE THREAD

**Issue by darcyllingyan** [CESNET/libyang#567]
Hi,
As it's difficult to describe the scenario, use one example to show it.
1.  One yang file merge.yang, in which p2 has the when condition ```../p3='true'```, p3 has default value 'false':
```
module merge {
        namespace "http://test/merge";
        prefix merge;

                container inner1 {
                  list b-list1 {
                    key p1;
                        leaf p1 {
                                type uint8;
                        }
                        leaf p2{
                                when "../p3 = 'true'";
                                type string;
                        }
                        leaf p3{
                                type boolean;
                                default false;
                        }
                        leaf p4{
                                type string;
                        }
                }
         }
}
```
2. The XML file merge.xml is:
```
<inner1 xmlns="http://test/merge">
    <b-list1>
         <p1>1</p1>
         <p2>a</p2>
         <p3>true</p3>
    </b-list1>
</inner1>
```
3. With the sysrepocfg, the data could be written successfully.
```
# sysrepocfg --merge=merge.xml merge --datastore=startup
The new configuration was successfully applied.
[root@cnet-netconf-c ~]# cat /etc/sysrepo/data/merge.startup
<inner1 xmlns="http://test/merge">
  <b-list1>
    <p1>1</p1>
    <p2>a</p2>
    <p3>true</p3>
  </b-list1>
</inner1>

```
4. Don't define the p3 and just define p4 in merge1.xml
```
<inner1 xmlns="http://test/merge">
    <b-list1>
         <p1>1</p1>
         <p4>b</p4>
    </b-list1>
</inner1>
```
5. With the sysrepocfg,  following error will be reported, and the sysrepod log shows the p3 will also be set:
```
# sysrepocfg --merge=merge1.xml merge --datastore=startup
[ERR] Commit operation failed with 1 error(s).
[ERR] Error returned from sr_commit: Validation of the changes failed.
[ERR] /merge:inner1/b-list1[p1='1']/p2 : When condition "../p3 = 'true'" not satisfied.
Errors were encountered during importing. Cancelling the operation.

[root@cnet-netconf-c ~]# sysrepod -l3 -d
[INF] Initializing Data Manager, schema_search_dir=/etc/sysrepo/yang/, data_search_dir=/etc/sysrepo/data/
[INF] Sysrepo daemon initialized successfully.
[INF] New session created successfully, real user=root, effective user=(null), session id=81770408.
[INF] Get items request startup datastore, xpath: /merge:*//., offset: 0, limit: 100
[INF] Data file /etc/sysrepo/data/merge.startup loaded successfully
[INF] Get items request startup datastore, xpath: /merge:*//., offset: 5, limit: 100
[INF] Set item request startup datastore, xpath: /merge:inner1/b-list1[p1='1']/p3
[INF] Set item request startup datastore, xpath: /merge:inner1/b-list1[p1='1']/p4
[INF] Data file /etc/sysrepo/data/merge.startup loaded successfully
[ERR] libyang error: When condition "../p3 = 'true'" not satisfied.
[ERR] Validation after merging failed
[INF] Unlock datastore request
[INF] Unlock datastore request
[INF] Dropping session id=81770408.
[INF] Closing the connection 0x1ad08b0.

```
6. If I remove the when condition, and run the sysrepocfg, the p3 will be changed to the default value:
```
sysrepocfg --merge=merge.xml merge --datastore=startup
The new configuration was successfully applied.
[root@cnet-netconf-c ~]# cat /etc/sysrepo/data/merge.startup
<inner1 xmlns="http://test/merge">
  <b-list1>
    <p1>1</p1>
    <p2>a</p2>
    <p3>false</p3>
    <p4>b</p4>
  </b-list1>
</inner1>
```
Seems the the default value will be used when the XML doesn't contain the p3(step 4). After check the RFC7950 [refer](https://tools.ietf.org/html/rfc7950#section-7.6.1),  the precondition is the data tree doesn't contain the leaf then the default value will be used, so I think the default value shouldn't be used here, right?

Thanks
Darcy

**Comment by michalvasko** [comment]
Hi Darcy,
please, write exactly what steps you took and at what point you did not like the result because I am quite confused from what you wrote. For instance, you are saying you created `b-list1` instance having set `p1` and `p4`, you removed the when condition and suddenly you also have nodes `p2` and `p3` created. You skipped some steps.

Regards,
Michal

**Comment by darcyllingyan** [comment]
Hi Michal,
Sorry for the confusing, I will list the steps exactly.
1.  Install a yang file:
1) The YANG file merge.yang content is:
```
module merge {
        namespace "http://test/merge";
        prefix merge;

                container inner1 {
                  list b-list1 {
                    key p1;
                        leaf p1 {
                                type uint8;
                        }
                        leaf p2{
                                when "../p3 = 'true'";
                                type string;
                        }
                        leaf p3{
                                type boolean;
                                default false;
                        }
                        leaf p4{
                                type string;
                        }
                }
         }
}
2) Install the yang
```
# sysrepoctl --install --yang=merge.yang --owner=root:root --permissions=666
Installing a new module from file 'merge.yang'...
Installing the YANG file to '/etc/sysrepo/yang/merge.yang'...
Installing data files for module 'merge'...
Notifying sysrepo about the change...
Install operation completed successfully.

```
2.  Write the XML data merge.xml to datastore
1) The merge.xml content is:
```
<inner1 xmlns="http://test/merge">
    <b-list1>
         <p1>1</p1>
         <p2>a</p2>
         <p3>true</p3>
    </b-list1>
</inner1>
```
2) Write the data, based on the merge.yang, the p2 exist when the p3=true, so the merge.xml could be written successfully:
```
# sysrepocfg --merge=merge.xml merge --datastore=startup
The new configuration was successfully applied.
# cat /etc/sysrepo/data/merge.startup
<inner1 xmlns="http://test/merge">
  <b-list1>
    <p1>1</p1>
    <p2>a</p2>
    <p3>true</p3>
  </b-list1>
</inner1>
```
3.  Merge the p4=b to the datastore, use another XML merge1.xml:
1) The content of merge1.xml
```
<inner1 xmlns="http://test/merge">
    <b-list1>
         <p1>1</p1>
         <p2>a</p2>
         <p3>true</p3>
    </b-list1>
</inner1>
```
2) Merge the p4=b
**The expected result of ** ```sysrepocfg --merge=merge1.xml merge --datastore=startup``` is:
```
<inner1 xmlns="http://test/merge">
    <b-list1>
         <p1>1</p1>
         <p2>a</p2>
         <p3>true</p3>
         <p4>b</p4>
    </b-list1>
</inner1>
```
**But now the result is:**
```
# sysrepocfg --merge=merge1.xml merge --datastore=startup
[ERR] Commit operation failed with 1 error(s).
[ERR] Error returned from sr_commit: Validation of the changes failed.
[ERR] /merge:inner1/b-list1[p1='1']/p2 : When condition "../p3 = 'true'" not satisfied.
Errors were encountered during importing. Cancelling the operation.
```
**The sysrepod log is:**
```
[root@cnet-netconf-c ~]# sysrepod -l3 -d
[INF] Initializing Data Manager, schema_search_dir=/etc/sysrepo/yang/, data_search_dir=/etc/sysrepo/data/
[INF] Sysrepo daemon initialized successfully.
[INF] New session created successfully, real user=root, effective user=(null), session id=81770408.
[INF] Get items request startup datastore, xpath: /merge:*//., offset: 0, limit: 100
[INF] Data file /etc/sysrepo/data/merge.startup loaded successfully
[INF] Get items request startup datastore, xpath: /merge:*//., offset: 5, limit: 100
[INF] Set item request startup datastore, xpath: /merge:inner1/b-list1[p1='1']/p3
[INF] Set item request startup datastore, xpath: /merge:inner1/b-list1[p1='1']/p4
[INF] Data file /etc/sysrepo/data/merge.startup loaded successfully
[ERR] libyang error: When condition "../p3 = 'true'" not satisfied.
[ERR] Validation after merging failed
[INF] Unlock datastore request
[INF] Unlock datastore request
[INF] Dropping session id=81770408.
[INF] Closing the connection 0x1ad08b0.
```

Based on the sysrepod log, though the merge1.xml doesn't contain p3, but it still sends the set request with p3's default value.

Not sure whether the steps are clear.

Thanks
Darcy

**Comment by michalvasko** [comment]
Hi Darcy,
I understood the problem now and I think it should be fixed (a problem in *sysrepocfg*, not *libyang).

Regards,
Michal

**Comment by darcyllingyan** [comment]
Hi Michal,
Thanks for the fix, it works now!

Thanks
Darcy
