### ISSUE TITLE
Loading all schemas from a directory

### ISSUE THREAD

**Issue by syyyr** [CESNET/libyang#568]
Hi, I'm trying to create a list of all top-level nodes from all schemas from a directory. Currently, I'm using Context::set_searchdir() to set the directory and Context::data_instantiables() to get the nodes. The problem is, that data_instantiables() returns nothing, until some schemas are loaded (looked up in the searchdir when using functions like find_path()). Is it possible for libyang to automatically load all schemas in a directory?
cc @jktjkt

**Comment by michalvasko** [comment]
Hi,
it is not directly supported and I think it is rightly so. Generally, you should not do this because there certainly are models that are only imports or some submodules, which should not be directly loaded. But you can always write this yourself, without too much effort.

Regards,
Michal

**Comment by syyyr** [comment]
I understand. Thanks for the explanation. We have come up with another solution.
