### ISSUE TITLE
Question: Milestones of libyang

### ISSUE THREAD

**Issue by kevinlinl** [CESNET/libyang#57]
Hi,
Very nice to see this C based YANG parser. Could you please disclose some information about milestone or roadmap ? Is libyang stable/ready to use ? 

Thank you so much.

**Comment by rkrejci** [comment]
Hi, libyang is already quite stable and it includes all major features we wanted to have. Currently, libyang is already being used in some other projects - [libnetconf2](https://github.com/CESNET/libnetconf2), [Netopeer2](https://github.com/CESNET/Netopeer2) and [sysrepo](https://github.com/sysrepo/sysrepo). We are not going to add new features for some time now (2-3 months) - we want to properly test and bugfix the current code and then it should be released as version 1.0.0. So, the current API should be (at least very close to) the final.

After that, we want to add support for YANG 1.1.
