### ISSUE TITLE
Ability to identify custom errors from "error-message" YANG statements

### ISSUE THREAD

**Issue by rwestphal** [CESNET/libyang#571]
Hi,

Recently I discovered the YANG "error-message" substatement which makes it possible to define custom validation error messages in the YANG modules themselves. Apparently this was designed for use by the NETCONF protocol but I think this construct can be used for other purposes as well. In my case, I want to be able to print more concise errors in the CLI of my program.

As an example, I added the following "error-message" substatement to my frr-ripd YANG module:
```diff
@@ -526,7 +526,9 @@ module frr-ripd {
           "Choose whether to use a simple password or a key-chain.";
         leaf authentication-password {
           type string {
-            length "1..16";
+            length "1..16" {
+              error-message "RIPv2 authentication string must be shorter than 16.";
+            }
           }
           description
             "Authentication string.";
```

Now I get this in my program's CLI when the the `length` constraint is violated:
```
ripd# conf t
ripd(config)# interface eth0
ripd(config-if)# ip rip authentication string XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
% Failed to edit candidate configuration.

Value "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" does not satisfy the constraint "1..16" (range, length, or pattern). (/frr-interface:lib/interface[name='eth0'][vrf='Default-IP-Routing-Table']/frr-ripd:rip/authentication-password)
RIPv2 authentication string must be shorter than 16. (/frr-interface:lib/interface[name='eth0'][vrf='Default-IP-Routing-Table']/frr-ripd:rip/authentication-password)
Failed to create node "authentication-password" as a child of "rip". (/frr-interface:lib/interface[name='eth0'][vrf='Default-IP-Routing-Table']/frr-ripd:rip/authentication-password)
```

And this is the behavior I'd like to implement instead (much less verbose):
```
ripd# conf t
ripd(config)# interface eth0
ripd(config-if)# ip rip authentication string XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
% Failed to edit candidate configuration.

RIPv2 authentication string must be shorter than 16.
```

I'm setting the `LY_LOSTORE` log option at startup since I need to have fine-grained control over libyang's error messages. One thing I'd like to do is the following: iterate over the list of libyang errors (returned by `ly_err_first()`) and check if any of them is a custom error message. If yes, print only that error and ignore the others. Otherwise print all errors. The problem is that the `ly_err_item` structure is defined like this:
```c
struct ly_err_item {                                                                                                   
    LY_LOG_LEVEL level;                                                                                                
    LY_ERR no;                                                                                                         
    LY_VECODE vecode;                                                                                                  
    char *msg;                                                                                                         
    char *path;                                                                                                        
    char *apptag;                                                                                                      
    struct ly_err_item *next;                                                                                          
    struct ly_err_item *prev; /* first item's prev points to the last item */                                          
};
```

There's no flag indicating whether the `msg` member is a custom error message or not. Is there a reason for not exposing this information to libyang users? For me it would be very useful to have access to this information, but I can understand if it's not possible to make it available through the public API.

Thanks in advance,
Renato.

**Comment by michalvasko** [comment]
Hi Renato,
there is no other reason for not exposing this information other than I found no use-case for it. However, I do not really feel like adding another flag to the whole structure. What if you also defined your own `error-app-tag` and identify these messages based on that?

Regards,
Michal

**Comment by rwestphal** [comment]
@michalvasko thanks for your input. Using `error-app-tag` I can indeed implement the behavior I want. I only think `error-message` would be more appropriate for my use case, but this shouldn't be a problem for now.

One other question: when a custom error is available (from a `error-message` statement), shouldn't it override the corresponding libyang generic error?

Taking the output below as an example, I'd prefer to not receive the first error since it's equivalent to the second one defined in the YANG model:
```
Value "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" does not satisfy the constraint "1..16" (range, length, or pattern). (/frr-interface:lib/interface[name='eth0'][vrf='Default-IP-Routing-Table']/frr-ripd:rip/authentication-password)
RIPv2 authentication string must be shorter than 16. (/frr-interface:lib/interface[name='eth0'][vrf='Default-IP-Routing-Table']/frr-ripd:rip/authentication-password)
Failed to create node "authentication-password" as a child of "rip". (/frr-interface:lib/interface[name='eth0'][vrf='Default-IP-Routing-Table']/frr-ripd:rip/authentication-password)
```

In the future it might be worth considering to add a new `LY_LO*` flag to define whether custom error messages should override generic error messages or not. This is far from critical for me at this point, just food for thought. I'll close this issue, thanks again!
