### ISSUE TITLE
Issue with ly_ctx_set_searchdir() and privdrop programs

### ISSUE THREAD

**Issue by rwestphal** [CESNET/libyang#573]
I'm getting the following error whenever I start my program (which uses libyang): `Unable to return back to working directory "/root" (Permission denied)`.

The problem is that my program needs superuser privileges to start, but it drops its privileges (by switching to a normal user) before calling `ly_ctx_set_searchdir()` and initializing libyang in general. The detail is that `ly_ctx_set_searchdir()` uses `chdir()` to change the working directory to the new libyang search path, and then uses `chdir()` again to return to the previous working directory. If the original working directory is _/root_, for example, the program fails to switch back to it since it dropped its privileges early on during initialization.

With that said, would it be possible to change `ly_ctx_set_searchdir()` in a way that `chdir()` doesn't need to be used? The current implementation of this function is problematic for privdrop programs since the working directory can never be restored.

Regards,
Renato.

**Comment by michalvasko** [comment]
Hi Renato,
`chdir()` is no longer used.

Regards,
Michal

**Comment by rkrejci** [comment]
That error is actually just a warning, so other directories should be searched then. But your point sounds fair, I'll add `LY_CTX_DISABLE_SEARCHDIR_CWD` to search only the directories explicitely set to be searched.

**Comment by rwestphal** [comment]
Thank you @rkrejci! The `LY_CTX_DISABLE_SEARCHDIR_CWD` flag is exactly what I was looking for :)
