### ISSUE TITLE
creating private yang module

### ISSUE THREAD

**Issue by rajgau11** [CESNET/libyang#577]
Hello Sir

I am new to netconf, I do have some idea about SNMP.
I have installed netconf and related packages and using Netopeer2 client.
Now, I want to write my own private yang modules.
I have one query about writing yang modules.
I want to write my own DHCP and DNS yang modules, what is good idea:
1) Should I import ietf related yang modules like ietf-dhcp, ietf-system, etc and augment related leafs groupings to my module as wrapper
OR
2) it will be better to write my own module considering the actual configurations files.

Point 1) Which approach will be more flexible and efficient?
Point 2) Isn't it that, using approach 1) I will end up [augment]ing every one and other information.
Point 3) Also, I may or may not require the groupings and order or information as already available, I want to categorize items some other way. Just for my understanding I went ahead and looked into how cisco and juniper have created yang modules for dhcp. I see, they have created modules of their own.

Please suggest.

Thanks
rajgau

**Comment by michalvasko** [comment]
Hi,
I think it is up to you and mostly comes down to whether you want to follow standards as much as possible or not. I think you should follow them (meaning use all the standard modules you can) but if you are writing a model only for testing or a small isolated use-case then it should not be a problem having proprietary models.

Regards,
Michal

**Comment by rajgau11** [comment]
Hello Michal
Thank you for the response and surely I want to follow the standards.
I am asking few more points, you may find them silly or childish, but this is for clarity, so that tomorrow I don't face any problems, even though I write bigger modules.

1) The reason why I wrote to you was to understand:

http://www.netconfcentral.org/modulereport/ietf-dhcp
(This is generic and definitely the standard)

vis-a-vis

https://github.com/YangModels/yang/blob/master/vendor/cisco/xe/1671/Cisco-IOS-XE-dhcp.yang
(This is customized because they have bigger scale of elements to handle, but does this follow the standards?)

2) In the situation when I use the standard module:

I can straightaway use this:
module ietf-dhcp {
}

and use xml directly for data get, set, etc, is it right?
These standard modules are open for private work also, no license issues?

No need to do like this:

module MY_module {
...
import ietf-dhcp {
prefix ietf_dhcp;
}
}

augment "/ietf_dhcp:server" {
container my_dhcp_server {
}
}
The way we write C wrappers for external or standard packages / functions.

**Comment by rajgau11** [comment]
Thank you for your support, Michal
They decided to take a common approach: use IETF or Openconfig generally, wherever fields does not satisfy the requirement, augment it.

Best Regards
Rajeev
