### ISSUE TITLE
Leafrefs point to already freed nodes after lyd_merge

### ISSUE THREAD

**Issue by pfeige** [CESNET/libyang#581]
Hi,

with the modified test in this commit https://github.com/ADTRAN/libyang/commit/82df0a30993b6e84fd2b01d44b37de4c29eae314 an issue concerning merged leafrefs is triggered.

### Description

When lyd_merge() is called with the option LYD_OPT_DESTRUCT the source nodes not yet contained in the target tree are unliked from source and linked to target. The remaining source nodes already contained in the target tree are freed afterwards. When there are leafrefs within the moved source nodes referring to not moved source nodes they point to freed memory after the merge if they are not set to NULL.

### Proposed solution

The proposed solution https://github.com/ADTRAN/libyang/commit/2c8ca48a90bbbfb74415d29464eb7531fd163133 ensures that all leafrefs referring to not moved source nodes are set to NULL before these source nodes are freed.

Best Regards,
Peter

**Comment by michalvasko** [comment]
Hi Peter,
thanks for the test and pull request, but I have merged only the test and decided for another fix (there was already a function doing something similar). I hope it works fine now.

Regards,
Michal
