### ISSUE TITLE
memleak in yang_read_node

### ISSUE THREAD

**Issue by rastislavszabo** [CESNET/libyang#60]
New memleak appeared in libyang v. 0.9.74:

==18490== 800 bytes in 4 blocks are definitely lost in loss record 3 of 10
==18490==    at 0x4C2CC70: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==18490==    by 0x56B7DE9: yang_read_node (parser_yang.c:469)
==18490==    by 0x56A7C64: yyparse (parser_yang_bis.c:4646)
==18490==    by 0x56BD032: yang_parse (parser_yang.c:2114)
==18490==    by 0x56BD14F: yang_parse_mem (parser_yang.c:2137)
==18490==    by 0x56BD285: yang_read_module (parser_yang.c:2169)
==18490==    by 0x56BFC7C: lys_parse_mem_ (tree_schema.c:1065)
==18490==    by 0x56C00B7: lys_parse_fd (tree_schema.c:1169)
==18490==    by 0x56BFE98: lys_parse_path (tree_schema.c:1125)

**Comment by PavolVican** [comment]
Hi Rastislav.

Could you tell me which yang module causes a memory leak?

Pavol

**Comment by rastislavszabo** [comment]
Hi, I'm not sure which one caused the issue, since I had many YANGs installed in sysrepo when the issue occurred. Anyway, I'm not able to reproduce it in the newest libyang version, so I'm closing the issue (it probably has been fixed with some recent change).
