### ISSUE TITLE
warning when rpc input contains must expression with count()

### ISSUE THREAD

**Issue by rjarry** [CESNET/libyang#610]
Hello,

I noticed that it is considered an error when an RPC `input` node contains a `must` expression with `count()`. It seems valid from a YANG point of view (looking at [RFC 7950](https://tools.ietf.org/html/rfc7950#page-69)).

I looked here: [src/xpath.c#L3330](https://github.com/CESNET/libyang/blob/master/src/xpath.c#L3330) but I'm not sure what should be done in order to support this.

Here is how to reproduce the problem:

```c
/* example.c */
#include <libyang/libyang.h>

static const char *yang =
        "module example {"
        "  yang-version 1.1;"
        "  namespace 'urn:example';"
        "  prefix 'ex';"
        "  rpc r {"
        "    input {"
        "      leaf a { type uint8; }"
        "      leaf b { type uint8; }"
        "      must 'count(*) = 1' {"
        "        error-message 'only one is allowed';"
        "      }"
        "    }"
        "  }"
        "}";

void main(void) {
        lys_parse_mem(ly_ctx_new(NULL, 0), yang, LYS_IN_YANG);
}
```

```
localhost:~$ gcc example.c -o example -lyang
localhost:~$ ./example 
libyang[1]: Argument #1 of xpath_count is a leaf node "b" without a list node parent.
libyang[1]: Previous warning generated by XPath function "count(*)".
```

**Comment by michalvasko** [comment]
Hi,
you are right, it was just a leftover from an old version when the XPath context was traversed incorrectly. I have removed the warning.

Regards,
Michal

**Comment by rjarry** [comment]
Thanks @michalvasko !

Faster than your own shadow, as always :)
