### ISSUE TITLE
deadloop occured when parse xpath expression whose length is more than 65535.

### ISSUE THREAD

**Issue by Amar0589** [CESNET/libyang#616]
Below is the callstack information:

Deadloop Time:              2018-09-11 08:07:36
Deadloop Tick:              0x000a7c25 (CPU Tick High) 0x5fd5c2f8 (CPU Tick Low)

Register Contents:          
Reg:  EDI,   0x114f1243   Reg:  ESI    0xa77bba43
Reg:  EBP    0xb0d61e58   Reg:  ESP    0xb0d61dc0
Reg:  EBX    0xae10e000   Reg:  EDX    0x0000005c
Reg:  ECX    0x00000003   Reg:  EAX    0x14ef7700
Reg:  TRAPNO 0x00000000   Reg:  ERR    0x00000000
Reg:  EIP    0xadeccfbb   Reg:  CS     0x00000073
Reg:  SS     0x0000007b   Reg:  DS     0x0000007b

Show CallStack:
Func:libyang.so()
Func:libyang.so(lyxp_parse_expr)
Func:libyang.so(transform_xml2json)
Func:libyang.so(lyp_parse_value)
Func:libyang.so()
Func:libyang.so()
Func:libyang.so()
Func:libyang.so()
Func:libyang.so(lyd_parse_xml)

We suspect below may be the issue.

![image](https://user-images.githubusercontent.com/35454282/45544552-44b09200-b835-11e8-8822-92cb81d978b5.png)

**Comment by michalvasko** [comment]
Hi,
an extreme use-case, but fine, it should finish with an error now.

Regards,
Michal
