### ISSUE TITLE
Leafref validations

### ISSUE THREAD

**Issue by anusha2508** [CESNET/libyang#622]
Hi,
I have used leafref to provide validation while inserting the data into datastores. Below are the sample yang files 
leafref_eg1.yang 
------
```yang
module leafref_eg1 {
    namespace "http://xyz.com/leafref_eg1";
    prefix lr1;

    import ietf-yang-types {
       prefix yang;
    }

    container  data {
        leaf test {
            type string;
            description "name ";
        }
    }

}
```
leafref_eg2.yang
----------------
```yang
module leafref_eg2 {
    namespace "http://xyz.com/leafref_eg2";
    prefix lr2;

    import leafref_eg1 {
        prefix lr1;
    }

    container new_container {
        leaf new_leaf {
             type leafref {
                path "/lr1:data/lr1:test";
             }
             description "name of the leaf";
        }

    }
}
```

I tried to delete the data of leafref_eg1.yang (/data/test=123) which is referred by one of the instance of leafref_eg2.yang and the deletion works. But how do I restrict the deletion of /data/test=123 instance of leafref_eg1.yang as it referred by some other module instance. Does yang library provide such validation while deletion? Can someone please provide some insights on this??.

**Comment by anusha2508** [comment]
Hi Michal,

Thanks for your time. I have verified with netopeer2/sysrepo, by subscribing for the candidate datastore changes for the module. Verified for the data tree for the dependencies, based on that ignoring/accepting the changes. Thanks for the input.

**Comment by katdiam** [comment]
Can you share some details how the leafref validations is done using sysrepo?

**Comment by katdiam** [comment]
Hi,  Michal:  

Thanks for your reply.

For example, we have above leafref_eg1.yang and leafref_eg2.yang,   and  a CLI that has add, delete and validate commands with callback functions in C     How to use sysrepo to implement the leafref validations (and other dependency validations) ?    Does sysrepo have APIs that do the validation that my CLI callback can call to validate the dependency so the CLI>validate or commit command will fail?

**Comment by michalvasko** [comment]
Hi,
I guess I should have been explicit, by `validate` I meant `sr_validate()` and by `commit` `sr_commit()`.

Regards,
Michal

**Comment by michalvasko** [comment]
Hi,
naturally, all YANG 1.1 constraints are validated as *sysrepo* simply uses *libyang* `lyd_validate()` function that does everything. For the other question, you would have to be much more specific, what should be the input and what the expected output. However, I think almost anything could be written using some *libyang* functions, *sysrepo* does not do much directly in this aspect.

Regards,
Michal

**Comment by katdiam** [comment]
Thanks a again.

input could be a leaf(/data/test or /data/test=123), output can be xpaths of all the data referencing to the input leaf,   or something that shows other data are depending on the input.

**Comment by michalvasko** [comment]
If you are fine with general schema information (no specific data nodes) then if a `leaf` or `leaflist` is referenced by some *leafref*, in the `struct lys_node_leaf` and `struct lys_node_leaflist` there is a set `backlinks` which holds all these referencing *leafrefs*. If you would want this information specific for a data node, you would still get this `backlinks` set of a schema node of a data node but you would have to find instances of these leafrefs yourself (for example, using `lyd_find_path()`).

Regards,
Michal

**Comment by katdiam** [comment]
Hi,  Michal:

Great, that's very helpful. Thanks a lot.

Just for Yang data model constraints  and dependency validation,  I can directly use libyang without sysrepo since sysrepo simply uses libyang for this purpose?

**Comment by michalvasko** [comment]
Yep.

**Comment by katdiam** [comment]
Thanks a lot!

**Comment by katdiam** [comment]
Hi,  Michael:

The lyd_validate works fine,  but I could not get the backlinks to work,  for the above example, leafref_eg1.yang and leafref_eg2.yang,  how do I get the backlink for instance: /data/test=123?   Appreciate your help.

**Comment by michalvasko** [comment]
Hi,
the way I described before but I can be more specific. Lets say you have a variable `leaf` of type `struct lyd_node *` of a leaf `/data/test` with value `123`. Now, you get the schema backlinks with `((struct lys_node_leaf *)leaf->schema)->backlinks`. That is a set through which you can iterate over all the schema nodes that are leafrefs pointing to this node. But you are looking for data nodes (the way I understood you) and you can get them by, for example, calling `lys_data_path()` on each of these backlinks and then call `lyd_find_path()` on the full data tree to get actual data instances.

Regards,
Michal

**Comment by katdiam** [comment]
Thanks,   the schema backlinks works fine with leaf->schema)->backlinks,  but it seems I could not get the backlinks with the set returned by lys_find_path() with the schema xpath,   lys_find_path() returns the schema node and should have the backlinks?

Yes,  I want the data node.  I have to search all the backlinks and compare each of the backlink's new_leaf value with the /data/test value 123?

**Comment by michalvasko** [comment]
Hi,
I have not mentioned any calls to `lys_find_path()` so I am not sure why you called it and what arguments you used for it. Anyway, yeah, once you get all the data nodes referencing your particular data leaf, you must manually compare their values to find out if any actually points to the data leaf.

Regards,
Michal
