### ISSUE TITLE
Package builds are failing since v0.16.29

### ISSUE THREAD

**Issue by rwestphal** [CESNET/libyang#626]
Hi,

The latest libyang packages available on the following link are referent to libyang v0.16.28 (the latest version on master is v0.16.45): https://software.opensuse.org//download.html?project=home%3Aliberouter&package=libyang-experimental

On this [link](https://build.opensuse.org/package/live_build_log/home:liberouter/libyang-experimental/Debian_9.0/x86_64) I found the following build log accusing an error:
```
[   79s] -- The CXX compiler identification is GNU 6.3.0
[   79s] -- Check for working CXX compiler: /usr/bin/c++
[   79s] -- Check for working CXX compiler: /usr/bin/c++ -- works
[   79s] -- Detecting CXX compiler ABI info
[   79s] -- Detecting CXX compiler ABI info - done
[   79s] -- Detecting CXX compile features
[   79s] -- Detecting CXX compile features - done
[   80s] CMake Error at /usr/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
[   80s]   Could NOT find SWIG: Found unsuitable version "3.0.10", but required is at
[   80s]   least "3.0.12" (found /usr/bin/swig3.0)
```

It seems the build failures were introduced by commit 1ec78bd0afce5. 

This other [link](https://build.opensuse.org/package/show/home:liberouter/libyang-experimental) shows that the package building is failing for all platforms/architectures.

Just reporting the issue as I have no idea on how to fix this :)

Regards,
Renato.

**Comment by mislavn** [comment]
I'll take a look tomorrow.

**Comment by rwestphal** [comment]
Maybe the problem can be fixed with the diff below:
```diff
--- a/packages/libyang.spec.in
+++ b/packages/libyang.spec.in
@@ -16,7 +16,7 @@ BuildRequires:  valgrind
 BuildRequires:  libcmocka-devel
 BuildRequires:  gcc
 BuildRequires:  gcc-c++
-BuildRequires:  swig >= 3.0.8
+BuildRequires:  swig >= 3.0.12
 
 %if 0%{?suse_version} + 0%{?fedora} > 0
 BuildRequires:  python3-devel
```

**Comment by mislavn** [comment]
The C++ namespace changes require SWIG >= 3.0.12, so it's not an option to downgrade the build requirement.

@michalvasko  is it possible to use the newer SWIG version in the build or if the Python bindings are not used we could disable them?

**Comment by michalvasko** [comment]
@mislavn We have looked at the problem and since we were using `swig 3.0.8` from our own package, we will just update it to `3.0.12`. However, it seems the build service has some problems currently so we will look at it a bit later. Specifically, @rkrejci will because I will be away.

Regards,
Michal

**Comment by rwestphal** [comment]
Any update on this?

**Comment by michalvasko** [comment]
We have forgotten about this a bit so I am looking at it currently.
