### ISSUE TITLE
heap-buffer-overflow reported by AddressSanitizer

### ISSUE THREAD

**Issue by Prasann1506** [CESNET/libyang#628]
**==18237==ERROR: AddressSanitizer: heap-buffer-overflow on address 0xe677d000 at pc 0xee6e5ce8 bp 0xf0a3ec48 sp 0xf0a3ec3c**
READ of size 1 at 0xe677d000 thread T11 (DefSch0300)
#0 0xee6e5ce7 in lyxml_parse_mem /usr1/code/code_R18C10_VRPV8/code/current/VRP/opensource/libyang/yang/xml.c:1130
#1 0xee5f9b45 in yin_read_module /usr1/code/code_R18C10_VRPV8/code/current/VRP/opensource/libyang/yang/parser_yin.c:7112
#2 0xee53cbdd in lys_read_import /usr1/code/code_R18C10_VRPV8/code/current/VRP/opensource/libyang/yang/parser.c:424
#3 0xee54905e in lyp_search_file /usr1/code/code_R18C10_VRPV8/code/current/VRP/opensource/libyang/yang/parser.c:661
#4 0xee52a95e in ly_ctx_load_sub_module /usr1/code/code_R18C10_VRPV8/code/current/VRP/opensource/libyang/yang/context.c:659
#5 0xee54b3d3 in lyp_check_import /usr1/code/code_R18C10_VRPV8/code/current/VRP/opensource/libyang/yang/parser.c:3070
#6 0xee5e7547 in fill_yin_import /usr1/code/code_R18C10_VRPV8/code/current/VRP/opensource/libyang/yang/parser_yin.c:3578
#7 0xee5e7547 in read_sub_module /usr1/code/code_R18C10_VRPV8/code/current/VRP/opensource/libyang/yang/parser_yin.c:6760
#8 0xee5f91f6 in yin_read_module_ /usr1/code/code_R18C10_VRPV8/code/current/VRP/opensource/libyang/yang/parser_yin.c:7020
#9 0xee5f9b5a in yin_read_module /usr1/code/code_R18C10_VRPV8/code/current/VRP/opensource/libyang/yang/parser_yin.c:7118
#10 0xee6dc42c in lys_parse_mem_ /usr1/code/code_R18C10_VRPV8/code/current/VRP/opensource/libyang/yang/tree_schema.c:961
#11 0xee6dc873 in lys_parse_fd /usr1/code/code_R18C10_VRPV8/code/current/VRP/opensource/libyang/yang/tree_schema.c:1115
#12 0xee6dcc76 in lys_parse_path /usr1/code/code_R18C10_VRPV8/code/current/VRP/opensource/libyang/yang/tree_schema.c:1052

Code snippet:
![image](https://user-images.githubusercontent.com/35322401/46198751-d38bd700-c32a-11e8-9959-383f10f261a5.png)

**Comment by michalvasko** [comment]
Hi,
I do not know what libyang version are you using, but update it and it should be fine.

Regards,
Michal
