### ISSUE TITLE
It raised error: array type has incomplete element type ‘struct CMUnitTest’ when installing libyang. How to resolve it? Thanks!

### ISSUE THREAD

**Issue by ehjizao** [CESNET/libyang#636]
zhaohongji@ubuntu:~/Downloads/libyang-0.14-r1/build$ make
[  1%] Built target yang2yin
[ 12%] Built target yangobj
[ 12%] Built target yang
[ 15%] Built target yanglint
[ 16%] Built target yangre
[ 17%] Built target metadata
[ 18%] Built target nacm
[ 18%] Built target libyang_ext_test
[ 19%] Built target test_sec9_13
[ 20%] Built target test_sec9_12
[ 20%] Building C object tests/CMakeFiles/test_sec9_11.dir/conformance/test_sec9_11.c.o
In file included from /home/zhaohongji/Downloads/libyang-0.14-r1/tests/conformance/test_sec9_11.c:24:0:
/home/zhaohongji/Downloads/libyang-0.14-r1/build/tests/config.h: In function ‘assert_ptr_equal’:
/home/zhaohongji/Downloads/libyang-0.14-r1/build/tests/config.h:18:30: warning: unused parameter ‘mod’ [-Wunused-parameter]
 void assert_ptr_equal(void * mod, void * ptr) {
                              ^~~
/home/zhaohongji/Downloads/libyang-0.14-r1/build/tests/config.h:18:42: warning: unused parameter ‘ptr’ [-Wunused-parameter]
 void assert_ptr_equal(void * mod, void * ptr) {
                                          ^~~
/home/zhaohongji/Downloads/libyang-0.14-r1/build/tests/config.h: In function ‘assert_ptr_not_equal’:
/home/zhaohongji/Downloads/libyang-0.14-r1/build/tests/config.h:22:34: warning: unused parameter ‘mod’ [-Wunused-parameter]
 void assert_ptr_not_equal(void * mod, void * ptr) {
                                  ^~~
/home/zhaohongji/Downloads/libyang-0.14-r1/build/tests/config.h:22:46: warning: unused parameter ‘ptr’ [-Wunused-parameter]
 void assert_ptr_not_equal(void * mod, void * ptr) {
                                              ^~~
/home/zhaohongji/Downloads/libyang-0.14-r1/tests/conformance/test_sec9_11.c: In function ‘TEST_EMPTY’:
/home/zhaohongji/Downloads/libyang-0.14-r1/tests/conformance/test_sec9_11.c:89:34: warning: passing argument 1 of ‘assert_ptr_equal’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
                 assert_ptr_equal(mod, NULL);
                                  ^~~
In file included from /home/zhaohongji/Downloads/libyang-0.14-r1/tests/conformance/test_sec9_11.c:24:0:
/home/zhaohongji/Downloads/libyang-0.14-r1/build/tests/config.h:18:6: note: expected ‘void *’ but argument is of type ‘const struct lys_module *’
 void assert_ptr_equal(void * mod, void * ptr) {
      ^~~~~~~~~~~~~~~~
/home/zhaohongji/Downloads/libyang-0.14-r1/tests/conformance/test_sec9_11.c:91:38: warning: passing argument 1 of ‘assert_ptr_not_equal’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
                 assert_ptr_not_equal(mod, NULL);
                                      ^~~
In file included from /home/zhaohongji/Downloads/libyang-0.14-r1/tests/conformance/test_sec9_11.c:24:0:
/home/zhaohongji/Downloads/libyang-0.14-r1/build/tests/config.h:22:6: note: expected ‘void *’ but argument is of type ‘const struct lys_module *’
 void assert_ptr_not_equal(void * mod, void * ptr) {
      ^~~~~~~~~~~~~~~~~~~~
/home/zhaohongji/Downloads/libyang-0.14-r1/tests/conformance/test_sec9_11.c: In function ‘main’:
/home/zhaohongji/Downloads/libyang-0.14-r1/tests/conformance/test_sec9_11.c:139:29: error: array type has incomplete element type ‘struct CMUnitTest’
     const struct CMUnitTest tests[] = {
                             ^~~~~
/home/zhaohongji/Downloads/libyang-0.14-r1/tests/conformance/test_sec9_11.c:140:9: warning: implicit declaration of function ‘cmocka_unit_test_setup_teardown’; did you mean ‘unit_test_setup_teardown’? [-Wimplicit-function-declaration]
         cmocka_unit_test_setup_teardown(TEST_EMPTY, setup_f, teardown_f),
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         unit_test_setup_teardown

I couldn't find struct CMUnitTest defination in the folder.
zhaohongji@ubuntu:~/Downloads/libyang-0.14-r1$ grep -rn "struct CMUnitTest"
tests/conformance/test_sec7_5_4.c:162:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec7_13_2.c:153:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec7_6_5.c:139:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec7_9_3.c:154:    const struct CMUnitTest tests[] = {
Binary file tests/conformance/.test_sec9_12.c.swp matches
tests/conformance/test_sec7_2.c:137:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec9_11.c:139:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec7_16_2.c:139:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec9_3.c:139:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec7_18_2.c:151:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec7_16_1.c:140:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec7_8_3.c:139:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec7_3.c:137:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec7_9_1.c:139:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec7_15.c:146:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec7_10.c:140:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec9_5.c:139:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec7_3_4.c:139:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec5_1.c:137:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec7_18_3_1.c:146:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec9_4_4.c:139:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec9_10.c:180:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec7_9_2.c:139:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec7_1.c:137:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec7_7_5.c:151:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec7_6_4.c:154:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec7_8_2.c:139:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec9_13.c:142:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec9_9.c:139:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec5_5.c:139:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec9_4_6.c:139:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec7_5_2.c:137:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec9_8.c:139:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec7_14.c:146:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec7_18_3_2.c:146:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec9_7.c:139:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec7_18_1.c:139:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec7_5_5.c:139:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec7_13_1.c:140:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec7_19_1.c:139:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec9_6.c:139:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec7_6_3.c:139:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec6_2_1.c:137:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec7_11.c:140:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec9_2.c:139:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec7_7_4.c:139:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec7_12_2.c:139:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec7_7_3.c:139:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec6_2.c:137:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec6_1_1.c:95:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec6_1_3.c:124:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec7_9_4.c:139:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec7_13_3.c:160:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec7_12_1.c:140:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec7_3_1.c:137:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec7_19_2.c:140:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec7_19_5.c:139:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec7_7_2.c:139:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec7_6_2.c:139:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec9_12.c:139:    const struct CMUnitTest tests[] = {
tests/conformance/test_sec7_8_1.c:139:    const struct CMUnitTest tests[] = {
tests/api/test_tree_data_dup.c:231:    const struct CMUnitTest tests[] = {
tests/api/test_tree_data_merge.c:494:    const struct CMUnitTest tests[] = {
tests/api/test_xml.c:441:    const struct CMUnitTest tests[] = {
tests/api/test_libyang.c:1181:    const struct CMUnitTest tests[] = {
tests/api/test_diff.c:565:    const struct CMUnitTest tests[] = {
tests/api/test_xpath_1.1.c:288:    const struct CMUnitTest tests[] = {
tests/api/test_tree_schema.c:1314:    const struct CMUnitTest tests[] = {
tests/api/test_tree_data.c:1547:    const struct CMUnitTest tests[] = {
tests/api/test_xpath.c:365:    const struct CMUnitTest tests[] = {
tests/api/test_dict.c:209:    const struct CMUnitTest tests[] = {
tests/schema/test_refine.c:83:    const struct CMUnitTest cmut[] = {
tests/schema/yin/test_print_transform.c:125:    const struct CMUnitTest cmut[] = {
tests/schema/test_extensions.c:4063:    const struct CMUnitTest cmut[] = {
tests/schema/test_feature.c:263:    const struct CMUnitTest cmut[] = {
tests/schema/test_import.c:136:    const struct CMUnitTest cmut[] = {
tests/schema/test_typedef.c:1243:    const struct CMUnitTest cmut[] = {
tests/schema/test_ietf.c:242:    const struct CMUnitTest cmut[] = {
tests/schema/test_augment.c:413:    const struct CMUnitTest cmut[] = {
tests/schema/test_deviation.c:83:    const struct CMUnitTest cmut[] = {
tests/schema/test_include.c:112:    const struct CMUnitTest cmut[] = {
tests/schema/test_leaflist.c:181:    const struct CMUnitTest cmut[] = {
tests/schema/test_status.c:315:    const struct CMUnitTest cmut[] = {
tests/schema/test_conformance.c:500:    const struct CMUnitTest cmut[] = {
tests/data/test_defaults.c:618:    const struct CMUnitTest tests[] = {
tests/data/test_when_1.1.c:239:    const struct CMUnitTest tests[] = {
tests/data/test_emptycont.c:134:    const struct CMUnitTest tests[] = {
tests/data/test_mandatory.c:166:    const struct CMUnitTest tests[] = {
tests/data/test_unique.c:168:    const struct CMUnitTest tests[] = {
tests/data/test_metadata.c:1431:    const struct CMUnitTest tests[] = {
tests/data/test_yangtypes_xpath.c:92:    const struct CMUnitTest tests[] = {
tests/data/test_leafref_remove.c:128:    const struct CMUnitTest tests[] = {
tests/data/test_must_1.1.c:185:    const struct CMUnitTest tests[] = {
tests/data/test_autodel.c:183:    const struct CMUnitTest tests[] = {
tests/data/test_json.c:299:    const struct CMUnitTest tests[] = {
tests/data/test_values.c:394:    const struct CMUnitTest tests[] = {
tests/data/test_instid_remove.c:96:    const struct CMUnitTest tests[] = {
tests/data/test_keys.c:208:    const struct CMUnitTest tests[] = {
tests/data/test_parse_print.c:748:    const struct CMUnitTest tests[] = {
tests/data/test_data_initialization.c:208:    const struct CMUnitTest tests[] = {
tests/data/test_when.c:168:    const struct CMUnitTest tests[] = {

**Comment by michalvasko** [comment]
Hi,
firstly, why are you using *libyang* `v0.14r1`? Most recent one is `v0.16r2`. Other than that, what *cmocka* version are you using? Can you also paste the output of *libyang* `cmake`? While having empty `build` directory, of course.

Regards,
Michal
