### ISSUE TITLE
The searchpath doesn't work, and I have to use the full directory

### ISSUE THREAD

**Issue by ehjizao** [CESNET/libyang#637]
》 help
Available commands:
  help            Display commands description
  add             Add a new model
  print           Print model
  data            Load, validate and optionally print instance data
  xpath           Get data nodes satisfying an XPath expression
  list            List all the loaded models
  feature         Print/enable/disable all/specific features of models
  searchpath      Set the search path for models
  clear           Clear the context - remove all the loaded models
  verb            Change verbosity
  debug           Display specific debug message groups
  quit            Quit the program
  ?               Display commands description
  exit            Quit the program

》 searchpath /home/zhaohongji/Downloads/libyang-0.16-r2/tools/lint/examples
》add module1.yang
libyang[0]: Opening file "module1.yang" failed (No such file or directory).
》add /home/zhaohongji/Downloads/libyang-0.16-r2/tools/lint/examples/module1.yang

I have add the folder "/home/zhaohongji/Downloads/libyang-0.16-r2/tools/lint/examples" into the searchpath, and the module1.yang is in it. But it doesn't work.

zhaohongji@ubuntu:~/Downloads/libyang-0.16-r2/tools/lint/examples$ pwd
/home/zhaohongji/Downloads/libyang-0.16-r2/tools/lint/examples
zhaohongji@ubuntu:~/Downloads/libyang-0.16-r2/tools/lint/examples$ ls
action-reply.xml             ietf-netconf-acm-when.yang
action.xml                   ietf-netconf-acm-when.yin
config-acm.xml               ietf-netconf-acm.yang
config-missing-key.xml       interface-ehjizao.xml
config-unknown-element.xml   module1b.yang
data-acm.xml                 module1.xml
data-ip.xml                  module1.yang
data-malformed-xml2.xml      module2.yang
data-malformed-xml.xml       module2.yin
data-missing-key.xml         module3.yang
data-out-of-range-value.xml  module4.yang
datastore.xml                nested-notification.xml
iana-if-type.yang            notification.xml
ietf-interfaces.yang         README.md
ietf-ip.yang                 rpc-reply.xml
ietf-netconf-acm-when2.yin   rpc.xml

**Comment by michalvasko** [comment]
Hi,
if you read `searchpath` command description, it says it is only for includes/imports of a model, not for the model itself. In short, it works as it should.

Regards,
Michal

**Comment by michalvasko** [comment]
Sorry, I was a bit hasty when writing the reply, the description was not too explanatory. That should be improved and there is also a new command `load` that does what you wanted to do.

Regards,
Michal
