### ISSUE TITLE
libyang[0]: Missing required element "checksum" in "yang-library". (path: /ietf-yang-library:yang-library)

### ISSUE THREAD

**Issue by ehjizao** [CESNET/libyang#638]
I use the libyang-0.16-r2/tools/lint/examples/datastore.xml to test the data function. 
When I use "data -t config -s /home/zhaohongji/Downloads/libyang-0.16-r2/tools/lint/examples/datastore.xml ", it is ok; 

But when I use "data -s", it raised the following error.

> list
List of the loaded models:
	i ietf-yang-metadata@2016-08-05
	I yang@2017-02-20
	i ietf-inet-types@2013-07-15
	i ietf-yang-types@2013-07-15
	i ietf-datastores@2017-08-17
	I ietf-yang-library@2018-01-17
	I ietf-interfaces@2017-08-17
	I iana-if-type@2014-05-08
	I module1
	I ietf-netconf-acm@2012-02-22
	I ietf-ip@2014-06-16
> data -t config -s /home/zhaohongji/Downloads/libyang-0.16-r2/tools/lint/examples/datastore.xml
> 
>  data -s /home/zhaohongji/Downloads/libyang-0.16-r2/tools/lint/examples/datastore.xml
libyang[0]: Missing required element "checksum" in "yang-library". (path: /ietf-yang-library:yang-library)
Failed to parse data.

I don't know whether it has something to do with yang-library. The datastore.xml doesn't refer to anything with yang-library.

**Comment by michalvasko** [comment]
Hi,
this is expected. In YANG you generally work with datastores, never single models, which means that mandatory elements of all loaded models are required. `ietf-yang-library` is an internal model that is **always** loaded. If you specify `-t config`, only configuration data are expected and it so happens that `checksum` is a state mandatory node of `ietf-yang-library`. So, when you do not specify `-t`, `data` is assumed, which is a full datastore where state data are required. Hence the validation error.

Regards,
Michal

**Comment by rwestphal** [comment]
@ehjizao please check the `LYD_OPT_DATA_NO_YANGLIB` option from `lyd_validate()`. It would probably be a good idea to make it possible to use this flag in _yanglint_ somehow since this is a very common issue.

**Comment by michalvasko** [comment]
Fair enough, this problem should no longer occur in *yanglint*, thanks for the suggestion. When it was written this option was not present and we forgot about it afterwards.

Regards,
Michal
