### ISSUE TITLE
Server failing with error "libyang[0]: Module not found or not implemented. (path: /ietf-netconf-monitoring"

### ISSUE THREAD

**Issue by vprasad** [CESNET/libyang#646]
Hi ,

I am trying to write a netconf server code using libnetconf2 and libyang.
While doing  a "ly_ctx_new" i am getting the below error while launching the server:-

libyang[0]: Module not found or not implemented. (path: /ietf-netconf-monitoring)
libyang[0]: Module not found or not implemented. (path: /ietf-netconf)

Can you please point out what i might be missing here .

Thanks,

**Comment by ZhaoGuangYue1986** [comment]
There are several models in dir of libnetconf2/schema ,you'd better to install  these models  into your search dir ,or use ly_ctx_set_module_imp_clb to regist  an model call back to tell libyang to load these models


/**
 * @brief Callback for retrieving missing included or imported models in a custom way.
 *
 * @param[in] mod_name Missing module name.
 * @param[in] mod_rev Optional missing module revision.
 * @param[in] submod_name Optional missing submodule name.
 * @param[in] submod_rev Optional missing submodule revision.
 * @param[in] user_data User-supplied callback data.
 * @param[out] format Format of the returned module data.
 * @param[out] free_module_data Callback for freeing the returned module data. If not set, the data will be left untouched.
 * @return Requested module data, NULL if the module is supposed to be loaded
 * using standard mechanisms (searched for in the filesystem), NULL and #ly_errno set if
 * the callback failed resulting in the module failing to load.
 */
typedef char *(*ly_module_imp_clb)(const char *mod_name, const char *mod_rev, const char *submod_name, const char *sub_rev,
                                   void *user_data, LYS_INFORMAT *format, void (**free_module_data)(void *model_data));

**Comment by vprasad** [comment]
> There are several models in dir of libnetconf2/schema ,you'd better to install these models into your search dir ,or use ly_ctx_set_module_imp_clb to regist an model call back to tell libyang to load these models
> 
> /**
> 
> * @brief Callback for retrieving missing included or imported models in a custom way.
> * @param[in] mod_name Missing module name.
> * @param[in] mod_rev Optional missing module revision.
> * @param[in] submod_name Optional missing submodule name.
> * @param[in] submod_rev Optional missing submodule revision.
> * @param[in] user_data User-supplied callback data.
> * @param[out] format Format of the returned module data.
> * @param[out] free_module_data Callback for freeing the returned module data. If not set, the data will be left untouched.
> * @return Requested module data, NULL if the module is supposed to be loaded
> * using standard mechanisms (searched for in the filesystem), NULL and #ly_errno set if
> * the callback failed resulting in the module failing to load.
>   */
>   typedef char *(*ly_module_imp_clb)(const char *mod_name, const char *mod_rev, const char *submod_name, const char *sub_rev,
>   void *user_data, LYS_INFORMAT *format, void (**free_module_data)(void *model_data));

Hi ,
So below is how i am trying to initialize libyang context :- 
    struct ly_ctx *ctx = NULL;
    ctx = ly_ctx_new("/tmp/vivek/files",0);

And in the path /tmp/vivek/files ,i have copied the models present in libnetconf2/schema to this dir.
/tmp/vivek/files
NE110:1-40*:/tmp/vivek/files # ls -lrt
total 270
-rw-rw-rw-  1 root      root          17319 Oct 29 14:48 ietf-inet-types.yin
-rw-rw-rw-  1 root      root          20686 Oct 29 14:49 ietf-netconf-monitoring.yin
-rw-rw-rw-  1 root      root          15230 Oct 29 14:49 ietf-netconf-acm.yin
-rw-rw-rw-  1 root      root           4738 Oct 29 14:49 ietf-netconf-with-defaults.yin
-rw-rw-rw-  1 root      root          12135 Oct 29 14:49 ietf-netconf-notifications.yin
-rw-rw-rw-  1 root      root           3221 Oct 29 14:49 notifications.yin
-rw-rw-rw-  1 root      root           3498 Oct 29 14:49 nc-notifications.yin
-rw-rw-rw-  1 root      root          33691 Oct 29 14:49 ietf-netconf.yin

Still when i launch the server binary i am getting the same prints :- 

libyang[0]: Module not found or not implemented. (path: /ietf-netconf-monitoring)
libyang[0]: Module not found or not implemented. (path: /ietf-netconf)

i am not able to figure out what i am doing wrong here .Please help .

Thanks,
Vivek prasad

**Comment by ZhaoGuangYue1986** [comment]
i write a test  use gtest frame-work ,it works well. do you have used ly_ctx_load_module to load your model?


TEST(TestNfoamTools, should_print_help_and_return_1_when_print_help)
{
    struct ly_ctx *ctx = NULL;
    ctx = ly_ctx_new("/home/szdev/z-conf/nfoam-depends/libnetconf2/schemas", 0);
    ASSERT_NE(ctx, (struct ly_ctx *)NULL);

    const struct lys_module *loadMode = ly_ctx_load_module(ctx, "ietf-netconf", "2011-06-01");
    ASSERT_NE(loadMode, (const struct lys_module *)NULL);

    const struct lys_module * getMode = ly_ctx_get_module(ctx, "ietf-netconf", "2011-06-01", 0);
    ASSERT_NE(getMode, (const struct lys_module *)NULL);
    ASSERT_EQ(strcmp("ietf-netconf",getMode->name),0);

    const struct lys_module * getModeIetfNetConfType = ly_ctx_get_module(ctx, "ietf-inet-types", "2013-07-15", 0);
    ASSERT_NE(getModeIetfNetConfType, (const struct lys_module *)NULL);
    ASSERT_EQ(strcmp("ietf-inet-types",getModeIetfNetConfType->name),0);
}

**Comment by vprasad** [comment]
Hi ,

After doing the ly_ctx_load_module of these yin files ,the error is resolved.
Appreciate a lot for help. 

Thanks,
Vivek Prasad
