### ISSUE TITLE
choice in augment cannot be handled properly

### ISSUE THREAD

**Issue by GuoyouZhang** [CESNET/libyang#651]
Hi, 

i'm trying to load ietf-interfaces model and ietf-microwave-radio-link to sysrepo, which use libyang.
ietf-microwave-radio-link has augment to the interface defined in ietf-interfaces.   

(https://tools.ietf.org/html/draft-ietf-ccamp-mw-yang-10)

augment "/if:interfaces/if:interface" {
    when "derived-from-or-self(if:type,"
       + "'mw-types:carrier-termination')";
...
   choice freq-or-distance {
      leaf rx-frequency {
        type uint32;
        units "kHz";
        description
          "Selected receiver frequency.";
      }
...

 The test result is that, even i create other type (not mw-types:carrier-termination ) of interface, the sysrepo still check radio-link (mandatory)attribute.
----------log like below----------------------
libyang error: Mandatory choice "freq-or-distance" missing a case branch.

 if we search the keyword LYE_NOMANDCHOICE,  it used in following code
Libyang/src/tree_data.c: 775

**Comment by michalvasko** [comment]
Hi,
I actually asked you for a smaller example with you providing the models and data so I can reproduce the issue without looking for any models and writing my own data. That saves me a considerable time so I do not have to spend it so much on these issues.

Anyway, it should work now properly.

Regards,
Michal

**Comment by GuoyouZhang** [comment]
@michalvasko 
Here is my steps to reproduce the issue:
1.	Put all file to some folder
sysrepoctl --install --yang= ietf-microwave-radio-link@2018-10-03.yang

2.	Build an app to subscribe yang sub tree
wget https://raw.githubusercontent.com/sysrepo/sysrepo/master/examples/application_example.c
gcc application_exmaple.c -lpthread -lsysrepo -o app
app ietf-microwave-radio-link

3.	Import config data to sysrepo
sysrepocfg --import=addif.xml

you can see that the “addif.xml” only add interface with type “ianaift:iana-interface-type”,  I assume libyang shouldn’t check the choice defined by 
  augment "/if:interfaces/if:interface" {
    when "derived-from-or-self(if:type,"
       + "'mw-types:carrier-termination')";

But it does check  “ choice freq-or-distance”.


[yangfile_config.zip](https://github.com/CESNET/libyang/files/2542302/yangfile_config.zip)

**Comment by michalvasko** [comment]
Hi,
alright, thank you, this is a much more helpful bug report. However, I have already fixed it as I have written in my previous reply so update *libyang* and try again, it worked fine for me.

Regards,
Michal

**Comment by GuoyouZhang** [comment]
just verified and it worked well!

thanks you very much:)

Regards
Guoyou
