### ISSUE TITLE
date-and-time type with centiseconds or more precision is not supported

### ISSUE THREAD

**Issue by iwanb** [CESNET/libyang#654]
The date-and-time type allows arbitrary precision on the fraction of seconds, but the libyang implementation only supports one digit in the fraction.

https://github.com/CESNET/libyang/blob/master/src/user_types/user_date_and_time.c#L211

It also seems the fraction is discarded when stored, it would also be good to instead save it and/or emit a warning for the loss of precision.

**Comment by michalvasko** [comment]
Hi,
you are right about the precision, I read the pattern hastily and did not realize there can be more fraction digits than one. It should now be validated correctly. However, this plugin (`user_date_and_time.c`) does **only** validation, it does not affect how the value is stored at all. The type is string and you will find that the original string is always stored in a *libyang* data node, no information is lost.

Regards,
Michal

**Comment by iwanb** [comment]
Hi Michal,

Ah ok, I thought it also stored in in binary form (I assumed that from the "store_clb" name).

Is there a way to disable the plugin at runtime (I use yanglint) or it's all done at compile time?

Regards,
Iwan

**Comment by michalvasko** [comment]
Hi Iwan,
you cannot really disable it, but if you remove the plugin file, it will no longer be used. By default it is found in `/usr/local/lib64/libyang/user_types/`.

Regards,
Michal

**Comment by iwanb** [comment]
Ok, thank you!
