### ISSUE TITLE
libyang version numbers are confusing

### ISSUE THREAD

**Issue by eqvinox** [CESNET/libyang#656]
Hi, I'm currently working on getting libyang into Debian and I've encountered 2 problems with the version numbers used in libyang:

* different version numbers are used for the package version in the code (`0.16.52`) and the github releases (`0.16-r2`).  This is confusing to the user and makes automatic updating / release watching difficult.

  I'm not sure what the reason is for the `0.16-r2` version numbers... if you just want to mark some versions as releases, could you use the same number as in the code?  I.e. `0.16-r1` => `0.16.41`, `0.16-r2` => `0.16.52` — the numbers inbetween are just skipped and don't exist as tags/releases.

  (Skipping version numbers is considerably less confusing than having 2 different version numbers.)

* ~the code version number is used as `libyang.so.X.Y.Z` DSO version number.  This is wrong; the X.Y.Z is the _ABI version_, not the project version.  Some documentation is at: https://github.com/asheplyakov/dsoabivers#soname-abi-versioning~

  ~Breaking the rules for Z is not a problem, but X and Y should be applied correctly.  You could use `0.0.${LIBYANG_MAJOR_VERSION}${LIBYANG_MINOR_VERSION}${LIBYANG_MICRO_VERSION}`...~

  Edit: I see 0.16.52 is actually the ABI version... normally the ABI version and the project version are different, I guess not here

**Comment by eqvinox** [comment]
Actually there still is a problem with the DSO version... it currently uses

```
set(LIBYANG_SOVERSION ${LIBYANG_MAJOR_VERSION}.${LIBYANG_MINOR_VERSION})
```

This doesn't work correctly because cmake uses SOVERSION for the ELF SONAME field, which must contain only the ABI version part without the revision/patchlevel.

**Comment by rkrejci** [comment]
Hi,
- The reason to replace the micro version number is to hide something not very important for naming a release. We increment the micro numbers quite often and only time to time the code is ready for release. It is just the name of a point in history. However, I'm not strongly against using the complete version number to name the releases. We just didn't see it as an important point.

I thought that we have some description about versioning somewhere, but I cannot find it. Sorry. So this is how it is:
- For simplicity, we didn't want to bother with multiple versions, so we've used only one version number for everything - packages/project as well as DSO. And this version number is increased with (almost) each git push (or PR merge).
- At the beginning, the API was quite unclear and it was changing quite often. We didn't wanted to get early to a high major version numbers, so we decided that actually the minor version number announces incompatible API/ABI changes. That's the reason why the combination of major and minor version is currently used as SONAME.

I'm open to discussion about better versioning. My idea is the following - as you maybe noticed, I'm working on some bigger changes in libyang2 (working name) branch. The main idea behind it is to keep functionality and basic mechanisms, but split the schema tree structures (for printing/providing schema info and for data validation) to simplify further maintenance and increase performance. I would like to preserve the described versioning schema for the current master (devel) branch. For libyang2, we can split the project and DSO versions starting both on version 1.0. Then, the project version can be increased independently (probably not so often) on DSO version which will correctly follow the schema with only major version number used for SONAME.

What do you think?

**Comment by eqvinox** [comment]
Hm. I'm not sure I can get the package into Debian with the `0.16` SONAME but I think I can try.  On a technical level it should work correctly, it just breaks the normal/common pattern.

For libyang2... @rwestphal will have "fun" updating FRR to use it, but for now we really need to get libyang1 into Debian... FRR 7.0 will have a dependency on it, and getting things into Debian takes time.

So... let me see if the `0.16` gets refused by the Debian people or not, I'll try to get it in as it is.

---

For the `0.16-r2` - it's really 2 things:

* it's confusing for the user because the version numbers are similar but different.  It would actually be less confusing if they didn't look similar :grin:
  * I don't see a problem with using the API version as the main project version, but the version numbers need to be understandable for humans... if a user sees `0.16-r2` and `0.16.52` they think the two numbers belong in the same "system" and they can't figure out which one is newer.
* automatically checking for updates becomes a problem if the Debian package uses `0.16.52` but github uses `0.16-r2`

If you can use the complete version number for future releases that would really make packaging a lot easier :)

**Comment by rkrejci** [comment]
> For libyang2... @rwestphal will have "fun" updating FRR to use it

We were already talking about it a bit - it will take some time to finish libyang2, we still want to support (bugfix) libyang1 and also provide some transition tutorial/howto. But, yeah, I know :)

> So... let me see if the `0.16` gets refused by the Debian people or not, I'll try to get it in as it is.

ok, please try. Another option is to split versioning now in master. I think we can say that we have currently version 1.0.0 (both project and DSO with SONAME 1) and because of work on libyang2 we don't want to do API/ABI incompatible changes in master code. libyang2 code then can be version 2.0.0 (probably again project as well as DSO with SONAME 2)

> If you can use the complete version number for future releases that would really make packaging a lot easier :)

ok, no problem

**Comment by jktjkt** [comment]
> We increment 
> the micro numbers quite often and only time to time the code is 
> ready for release. It is just the name of a point in history. 
> However, I'm not strongly against using the complete version 
> number to name the releases. We just didn't see it as an 
> important point.

I wonder what is the reason for these frequent manual version bumps. If 
this is only about clearly identifying a specific git commit from the 
version field, I have some cmake scripts which use the results of `git 
describe --tags --dirty` for this. I'll be happy to contribute these.

**Comment by rkrejci** [comment]
yes, I'd be interested (in some separate thread) - the reason is to identify the commit and simply get know if it is older/newer than some other version.

**Comment by eqvinox** [comment]
In a way, the manual version bumps are better than automatic git-based stuff because they can be more meaningful and useful to the user.  Also, the git tree is not always available, e.g. distro packages normally build from release `tar.gz` without git.

But, ultimately, the only thing that matters is that it is (a) consistent and (b) machine-readable without "backwards jumps" in the version number.
