### ISSUE TITLE
what type is the leaf in date tree if its schema's type is leafref? BASIC TYPE or LEAFREF ?

### ISSUE THREAD

**Issue by foxge** [CESNET/libyang#664]
https://github.com/CESNET/libyang/blob/e9701ba1274a2858885eb33396b3cc1242c353c0/src/tree_data.h#L248

Hi, I have such a question, for example,
```
container A {
      leaf name {type string;}
}

container B {
      leaf name {
           type leafref {path ../../A/name"   //what type in data tree ? string or leafref ?
      }
}
```

Thank you for help.

**Comment by michalvasko** [comment]
Hi,
in your case `LY_TYPE_STRING` should be stored there.

Regards,
Michal
