### ISSUE TITLE
Leafref with default in grouping gives "parsing failed" without any further error message

### ISSUE THREAD

**Issue by iwanb** [CESNET/libyang#665]
Given a Yang module like this:
```
module a {
  namespace "urn:a";
  prefix a_mod;

  container x {
    container y {
      uses refering;
      leaf referred {
        type string;
        default "value";
      }
    }
  }
  grouping refering {
      leaf bar-leaf {
        type leafref {
          path "../referred";
        }
        default "value";
      }
  }
}
```

Yanglint fails to parse it (even though AFAIK it's valid), and it only says:
```
err : Module "a" parsing failed.
```

It's only if the leafref has a default. It seems to be an issue in the `resolve_unres_schema_types` and `resolve_unres_schema_item` functions, but I could not find out what exactly.

Running with verbose messages gives this:
```
Validating a.yang schema file.
verb: Resolving uses "refering" failed, it will be attempted later.
verb: Resolving type default "value" failed, it will be attempted later.
verb: Resolving "a" unresolved schema nodes and their constraints...
err : Module "a" parsing failed.
```

I tried it on the latest devel branch. AFAIK it's a regression because it worked with an older version (0.15.38 on devel I think).

Iwan

**Comment by michalvasko** [comment]
Hi Iwan,
it should work properly now. Also, I do not think it is a regression, more likely default values in groupings were not checked in `0.15` at all.

Regards,
Michal

**Comment by iwanb** [comment]
Perfect it works, thank you!

Iwan
