### ISSUE TITLE
libyang Efficiency issues？

### ISSUE THREAD

**Issue by zyboy2000** [CESNET/libyang#669]
i run libnetconf2.0 in the embedded device (cpu is 1G), If you register too many nodes, it can be very time-consuming，A single function takes the following time (these funcitons will call libyang Library）。

dm_load_data_tree_file  -- 142ms 
2.dm_data_info_free        --  100ms 
3.dm_append_data_tree   --  92ms 
4.dm_validate_data_info   -- 179ms

Is there a way to increase speed ？Thanks!!

**Comment by michalvasko** [comment]
Hi,
I am not sure what exactly do you mean by "too many nodes" but those times seem fine to me and there is no way to make them better anyway (unless you have not used the default *libyang* or *sysrepo* `cmake` configuration).

Regards,
Michal

**Comment by zyboy2000** [comment]
register too many nodes means Creating too many Configuration Nodes,  Creating a configuration node takes hundreds of milliseconds, It takes a long time to create thousands of configuration nodes!

**Comment by michalvasko** [comment]
Hi,
it also depends how exactly are you creating them, whether one-by-one or all together in one commit. Other than that I do not know what to reply, there are many tasks that must be performed for every commit and they simply take some time.

Regards,
Michal
