### ISSUE TITLE
swig/python license confusion/mismatch

### ISSUE THREAD

**Issue by eqvinox** [CESNET/libyang#670]
Some files under `swig/python` indicate their license as:

```
__author__ = "Matija Amidzic <matija.amidzic@sartura.hr>"
__copyright__ = "Copyright 2018, Deutsche Telekom AG"
__license__ = "BSD 3-Clause"

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
```

Something is obviously wrong there because it says `BSD 3-Clause` in `__license__` but then `Apache 2.0` in the comment without any clarification.

This should be fixed in contact and agreement with the original author - @mamidzic?
(best would be to go with BSD 3-Clause so it matches the rest of the project...)

**Comment by mamidzic** [comment]
Thanks for pointing this out, I've made a pull request that fixes this.
