### ISSUE TITLE
Assert in printer_yin.c while loading submodule

### ISSUE THREAD

**Issue by bhart3** [CESNET/libyang#674]
When a submodule is loaded that has a grouping with an identityref that has a default value, this assert is thrown in printer_yin.c:
`/local/repo/libyang/src/printer_yin.c:1119: yin_print_leaf: Assertion `strchr(leaf->dflt, ':')' failed`

This seems to be caused by commit 7d89492

I will be submitting a PR with new cmocka tests that demonstrate this issue.

**Comment by michalvasko** [comment]
Hi,
thanks for the tests and it should work properly now.

Regards,
Michal
