### ISSUE TITLE
Sysrepo might fail with libyang error: 'Failed to find matching hash for child of ... "

### ISSUE THREAD

**Issue by przemekr** [CESNET/libyang#684]
Hi,

After updating to sysrepo 0.7.7 and libyang 0.16-r2 (previously I was running with 0.7.2 ) I am getting parsing errors for one configuration:
```
Dec 13 08:31:07 ubuntu sysrepod[15251]: [ERR] (dm_ly_log_cb:1617) libyang error: Failed to find matching hash for a child of "stProfile".
Dec 13 08:31:07 ubuntu sysrepod[15251]: [ERR] (dm_load_data_tree_file:1440) Parsing data tree from file /etc/sysrepo/data/Test.running failed: Failed to find matching hash for a child of "stProfile".
Dec 13 08:31:07 ubuntu sysrepod[15251]: [ERR] (dm_get_data_info_internal:3005) Getting data tree for Test failed.
Dec 13 08:31:07 ubuntu sysrepod[15251]: [ERR] (rp_dt_prepare_data:1209) Getting data tree failed (4) for xpath '/Test:*//.'
Dec 13 08:31:07 ubuntu sysrepod[15251]: [ERR] (rp_dt_get_values_wrapper_with_opts:1361) rp_dt_prepare_data failed
Dec 13 08:31:07 ubuntu sysrepod[15251]: [ERR] (rp_get_items_req_process:830) Get items failed for '/Test:*//.', session id=1366346345.
```
The problem is there for a specific data of 'Test' module.  After changing slightly one field of the config parameters the issue is not visible. 

I check also the latest commit for libyang (15baadb), and try building with ENABLE_CACHE ON or OFF, but it result in the same errors.

**Comment by michalvasko** [comment]
Hi,
it would be best if I could reproduce it. Could you provide your data in XML/JSON and their YANG model `Test`?

Regards,
Michal

**Comment by przemekr** [comment]
Yes, I know that would be the best way to troubleshoot, but unfortunately the model and data is copyright material and I am not allowed to post it. :(

The model looks something like this (just example names here):

module Test {

    grouping S_Profiles {
        leaf bProfile001 { type boolean;  }
        leaf bProfile002 { type boolean;  }
        leaf bProfile003 { type boolean;  }
        leaf bProfile004 { type boolean;  }
        leaf bProfile006 { type boolean;  }
    }

    grouping S_abc {
        leaf u16MaxAbc { type uint16; }
        container stProfile { uses S_Profiles;  }
    }

    container S_dConfig {
        list firstList {
            max-elements 10;
            key "idx"; leaf idx { type uint16; description "List index"; }
            uses S_abc;
        }
        leaf someData1 { type uint8;}

        list secondList {
            max-elements 10;
            key "idx"; leaf idx { type uint16; description "List index"; }
            uses S_abc;
        }
        leaf someData2 { type uint8;}
    }
}

From the debug printouts (see bellow) I added I could see that the hash for 'someData2'  is search as a child of StProfile. 
sparent S_dConfig sibling stRlcConfig, i 0, has_schema: 1 hash[0] 137, sibling_hash 190
....
sparent stProfile sibling bProfile0x0001, i 0, has_schema: 1 hash[0] 190, sibling_hash 157
sparent stProfile sibling bProfile0x0002, i 0, has_schema: 1 hash[0] 190, sibling_hash 147
sparent stProfile sibling bProfile0x0003, i 0, has_schema: 1 hash[0] 190, sibling_hash 196
sparent stProfile sibling bProfile0x0004, i 0, has_schema: 1 hash[0] 190, sibling_hash 200
sparent stProfile sibling bProfile0x0006, i 0, has_schema: 1 hash[0] 190, sibling_hash 233
[ERR] (dm_ly_log_cb:1617) libyang error: Failed to find matching hash for a child of "stProfile".

```
@@ -954,7 +955,27 @@ lyb_parse_schema_hash(const struct lys_node *sparent, const struct lys_module *m
 
     /* find our node with matching hashes */
     sibling = NULL;
     while ((sibling = (struct lys_node *)lys_getnext(sibling, sparent, mod, 0))) {
+
+    LYB_HASH sibling_hash = lyb_hash(sibling, 0);
+
+        printf("sparent %s sibling %s, i %d, has_schema: %d hash[0] %d, sibling_hash %d\n",
+                sparent? sparent->name: "NULL",
+                sibling? sibling->name: "NULL",
+                i,
+                lyb_has_schema_model(sibling, lybs->models, lybs->mod_count),
+                (int)hash[0],
+                (int)sibling_hash
+                );
+

         /* skip schema nodes from models not present during printing */
         if (lyb_has_schema_model(sibling, lybs->models, lybs->mod_count) && lyb_is_schema_hash_match(sibling, hash, i + 1)) {
             /* match found */
```

**Comment by michalvasko** [comment]
Hi,
it is possible there is a problem with handling `grouping` correctly. So, you cannot even send me the data and the model privately to my email (in my profile)? If not, then I will try to reproduce it somehow with this information.

Regards,
Michal

**Comment by przemekr** [comment]
I am afraid even sending/email the data/model wouldn't be possible.  

The model makes use of groupings, some of them appear in several places in the model (like the S_abc) in the example.  If that would be of any help I can build the libyang/sysrepo with additional debug traces run the failing test and post the output.

**Comment by przemekr** [comment]
Yes, I notice that the code is quite complex and I am still not very familiar with libyang implementation.

OK, I will try to reproduce the issue with example/test data or if that fails, I check if it would be possible to get approval for sending the original model to you.

**Comment by przemekr** [comment]
Hi,

Finally I manage to reproduce the issue on an example model and dummy data. 

 sudo sysrepoctl --install --yang=test.yang
 sysrepocfg --import=test_ok.json --format=json test --datastore startup
 sysrepocfg -x- test -f json -d startup > /dev/null
 # Works fine....

 sysrepocfg --import=test_failing.json --format=json test --datastore startup
 sysrepocfg -x- test -f json -d startup > /dev/null
 [ERR] (dm_load_data_tree_file:1440) Parsing data tree from file /etc/sysrepo/data/test.startup failed: Failed to find matching hash for a child of "tb1992452a".
[ERR] (dm_get_data_info_internal:3005) Getting data tree for test failed.
[ERR] (rp_dt_prepare_data:1209) Getting data tree failed (4) for xpath '/test:*//.'
[ERR] (rp_dt_get_values_wrapper_with_opts:1361) rp_dt_prepare_data failed
[ERR] (rp_get_items_req_process:830) Get items failed for '/test:*//.', session id=831362827.
[ERR] (cl_request_process:543) Error by processing of the get-items request (session id=831362827): Sysrepo-internal error.
[ERR] (sr_get_items_iter:1028) Sending get_items request failed '/test:*//.'
[ERR] (srcfg_get_module_data:248) Error by sr_get_items_iter: Sysrepo-internal error



[test_data_error_matching_hash.zip](https://github.com/CESNET/libyang/files/2686148/test_data_error_matching_hash.zip)

**Comment by michalvasko** [comment]
Hi,
thanks for the reproducible example although it was not too easy to debug with all those random names. But I believe it should work now, please try it again.

Regards,
Michal
