### ISSUE TITLE
Missing prefix when using lys_path to build path with schema node which augment from another module

### ISSUE THREAD

**Issue by mrdotchenke** [CESNET/libyang#690]
When the schema node is augment from another module, for example:
```yang
module test {
  namespace "urn:yang:testext";
  prefix tst;
  revision 2019-01-01;
  container test;
}
```
```yang
module testext {
  namespace "urn:yang:testext";
  prefix tstext;
  import test {
    prefix tst;
  }
  revision 2019-01-01;
  augment /tst:test {
    leaf node {
       type string;
    }
  }
}
```
Using /test:test/testext:node to lys_find_path will return right schema node
Then using the schema node to lys_path will return /test:test/node. Which is missing the node's own module name as prefix.

**Comment by michalvasko** [comment]
Hi,
I am not sure how you managed to load these 2 modules into *libyang* because they have the same namespace but a different name. When I changed the namespace of `test` into `urn:yang:test` and loaded it, the output of `lys_path()` was correct (`/test:test/testext:node`).

Regards,
Michal

**Comment by mrdotchenke** [comment]
Yes, the namespace of the module test should be urn:yang:test. 
Sorry I forgot to mention than the option to call lys_path should be LYS_PATH_FIRST_PREFIX to reproduce the issue.

**Comment by michalvasko** [comment]
Hi,
okay, it should work now correctly.

Regards,
Michal
