### ISSUE TITLE
Schema Mount Support

### ISSUE THREAD

**Issue by rohitrranade** [CESNET/libyang#691]
hi,

Does libyang have a plan to work on supporting schema mount ?

Reference for schema mount : draft-ietf-netmod-schema-mount-12
Link : https://datatracker.ietf.org/doc/draft-ietf-netmod-schema-mount/

**Comment by rohitrranade** [comment]
Reference for schema mount : draft-ietf-netmod-schema-mount-12
Link : https://datatracker.ietf.org/doc/draft-ietf-netmod-schema-mount/

**Comment by michalvasko** [comment]
Hi,
yes, we would like to support this at some point but not anytime soon (likely not this year). We are currently working on other things.

Regards,
Michal

**Comment by donaldsharp** [comment]
The FRRouting project would like to request that this feature get implemented.  We are at a point where this would make a huge difference in our work being done.

**Comment by michalvasko** [comment]
Hi,
sorry for not replying sooner but there is not much I can say anyway. The situation is the same as the last year, it is a nice-to-have feature for which we do not have a specific use-case making it not  a priority. We are not able to say when or even if this will be implemented.

Regards,
Michal

**Comment by peerst** [comment]
I'm working on it right now.  If anyone interested in this could provide me with realistic use case Schema Mount examples for testing that would be immensly  useful.

**Comment by venkukakumani** [comment]
@peerst 
suppose if have multiple devices configured by a single controller, we need schema mount to distinguish the different devices. please share the patch I will validate and let you know.

**Comment by masif-cs** [comment]
@peerst 

Did u by any chance completed this schema mount support and delivered to any branch? I am also looking for schema mount support.

**Comment by michalvasko** [comment]
Schema mount should be supported in current libyang `devel` branch, version 2.0.149 SO 2.16.0.
