### ISSUE TITLE
user type inet:host error with the new user_type

### ISSUE THREAD

**Issue by mislavn** [CESNET/libyang#695]
Hi,

with the new user_type the address leaf in ietf-netconf-server fails to parse.

```
    typedef host {
      type union {
        type ip-address;
        type domain-name;
      }
      description
        "The host type represents either an IP address or a DNS
      domain name.";
    }
```

The config file can be imported but it fails when libyang parses it with sysrepocfg or any other plugin. Libyang does not accept valid IP addresses like (0.0.0.0, 1.1.1.1) or a domain name.

**Comment by michalvasko** [comment]
Hi,
you have not provided much details so I fixed a bug I encountered that sound like what you described so I hope it is working now (fix merged into `user_types` branch as well).

Regards,
Michal

**Comment by mislavn** [comment]
Hi,

thank you, it works now.

Regards,
Mislav
