### ISSUE TITLE
ly ERROR: Internal error (libyang-0.16-r3/src/plugins.c:615).

### ISSUE THREAD

**Issue by mislavn** [CESNET/libyang#698]
When I put the [patch](https://github.com/CESNET/libyang/commit/717cb69c82004762158fc7a74574538278c2be9e) (patch for canonical format) on top of [v0.16-r3](https://github.com/CESNET/libyang/releases/tag/v0.16-r3) I get the error `ly ERROR: Internal error (libyang-0.16-r3/src/plugins.c:615).` when running get. And only on an ARM (OpenWrt) build.

It fails in the function "lytype_free" for module name `ietf-inet-types` and type name `host`.

@michalvasko do you have any advice how to debug this?

**Comment by michalvasko** [comment]
Hi Mislav,
what I would do is put a breakpoint on `plugins.c:615` and then manually try to use a debugger to perform `lytype_find()` with the specific parameters. Or, if you are able, step through this function directly and see why it does not find this type.

Regards,
Michal

**Comment by mislavn** [comment]
Hi Michal,

I managed to recreate the issue locally. The problem is in the type `host`:
```
    typedef host {
      type union {
        type ip-address;
        type domain-name;
      }
      description
        "The host type represents either an IP address or a DNS
      domain name.";
    }
```

libyang handles `inet:host` as type instead of a union of two types and tries to free `host` instead of `ip-address` in lytype_free.

tree_data.c needs logic to handle these kind of unions I think:
```
    /* otherwise the value is correctly freed */
    if (value_flags & LY_VALUE_USER) {
        assert(type->der && type->der->module);
        lytype_free(type->der->module, type->der->name, value);
```

@michalvasko what do you think?

**Comment by michalvasko** [comment]
Hi,
I do not really know what to do based on this information, can I reproduce it in the `user_types` branch simply by creating a node of type `host` and then freeing it?

Regards,
Michal

**Comment by michalvasko** [comment]
Hi Mislav,
when just issuing `<get>` I did not see any error.

Regards,
Michal

**Comment by mislavn** [comment]
Hi Michal,

the <get> commands executes as expected but on ARM the error message is displayed after <get> does it's thing while on desktop the error message is in sysrepod `[ERR]: Internal error (/opt/fork/libyang/src/plugins.c:617).`.

Regards,
Mislav

**Comment by michalvasko** [comment]
Hi,
well, like I said, I am not seeing any error in *sysrepod* when I execute `<get>` using *netopeer2-cli*. I have fresh *sysrepo* `debug` installation with *netopeer2-server* without configuration.

Regards,
Michal

**Comment by mislavn** [comment]
Hi,

sorry I forgot, I used the latest tags for sysrepo, libnetconf2 and Netopeer2 and for libyang I used the user_types branch.

Regards,
Mislav

**Comment by mislavn** [comment]
Hi Michal,

just tested with the latest devel branches for sysrepo, libnetconf2 and Netopeer2 and the bug does not appear. I'll close the issue.

Regards,
Mislav

**Comment by michalvasko** [comment]
Hi Mislav,
are you saying it got fixed in some commit between version `0.16.105` and `0.16.108`? That seems unlikely. I think you had some changes in the installed *sysrepo* and that made the bug manifest and when you did an update, you also removed these changes. Or did you update only *libyang*?

Regards,
Michal

**Comment by mislavn** [comment]
Hi Michal,

I'm trying to find what change fixed the issue, it will take me some time.
For the install, I used docker. In the dockerfile I used the devel branches or the git release tags.

Regards,
Mislav

**Comment by michalvasko** [comment]
Okay, thanks.

Regards,
Michal

**Comment by michalvasko** [comment]
Hi Mislav,
thanks for finding the use-case, I believe I was able to fix it.

Regards,
Michal

**Comment by mislavn** [comment]
Thanks.

Regards,
Mislav
