### ISSUE TITLE
Problem of subscribing notification with subtree filter

### ISSUE THREAD

**Issue by yangtian127** [CESNET/libyang#708]
1
Using subtree filter to subscirbe notifications, such as:
```xml
<netconf-config-change xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-notifications">
  <changed-by>
    <username>root</username>
  </changed-by>
 <datastore>running</datastore>
</netconf-config-change>
```
On netoperr2-cli, subscribe return OK, but can not receive the notifications.
On netopeer2-server, return an error:
```
   libyang: Internal error (../libyang-0.14-r1/src/tree_data.c 1984)
```
when use following subtree filter, on netopeer-cli can receive notification, but report mandatory element missing:
```xml
<netconf-config-change xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-notifications">
 <datastore>running</datastore>
</netconf-config-change>
```

**Comment by michalvasko** [comment]
Hi,
before I devote any time examining your problem, you will have to update your *libyang* to be at least [v0.16-r3](https://github.com/CESNET/libyang/releases/tag/v0.16-r3) (0.16.105) and verifying the problem is still present on this version.

Regards,
Michal

**Comment by yangtian127** [comment]
Thanks for reply so quickly.
I have try the libyang-0.16-r3, The problem remains.
 On netopeer2-server report:
   Internal error (../libyang-0.16-r3/src/tree_data.c 2672)

**Comment by michalvasko** [comment]
Hi,
could you please grab the current `devel` and try again? I did just a quick fix based on the updated line number error without any testing so the problem may or may not be fixed, thanks.

Regards,
Michal

**Comment by michalvasko** [comment]
Hi,
great and yeah, if you use a filter the `mandatory` node rules should no longer apply.

Regards,
Michal

**Comment by yangtian127** [comment]
OK. thanks.
