### ISSUE TITLE
Copy data between models

### ISSUE THREAD

**Issue by cromlegionar** [CESNET/libyang#710]
Hi everyone,

I have a very basic question about the creation and manipulation of data-trees and I could not find an answer in the existing pool of questions nor in the rfc for yang:  Below I have created two yang schemas which i am using in my program(names altered and structure simplified). A test-server module and a test-server-list module. I am recieving a data-tree with the type of test-server and want to copy it into an entry of the dummy-server-list.  I can create a test-server-list datatree and build a new list entry, then create the "name" leaf and server container, but when i try to insert the dummy-netconf-server container from the test-server into the server-container from the test-server-list, i get the error from the snapshot.

Server schema:

```
module test-netconf-server {
    namespace "urn:test:test-netconf-server";
    prefix "ncss";

    revision 2018-02-04 {
        description "initial test revision.";
    } 
    
        uses server-content;
    
    grouping server-content {
        container server{
            container dummy-netconf-server {
                config true;
                leaf dummy-variable {
                    type uint16;
                }
                leaf dummy-string {
                    type string;
                }
            }
        }
    }
}
```

Server-List schema:

```
module test-netconf-server-list  {
    namespace "urn:test:test-netconf-server-list";
    prefix "ncsl";
    
    import test-netconf-server {
        prefix ncss;
        revision-date 2018-02-04;
    
    revision 2018-02-04 {
        description "initial test revision.";
    }

    container netconf-server-list {
        config true;
        
        list server-list {
            key name;
            leaf name {
                type string;
                description
                    "client internal server name for addressing purposes inside this list and the netconf client";
            }
            
            uses ncss:server-content;
            
        }      
    }
}
```
In the snapshot you can see first the server data that is recieve, then the server list, which is created manually. The error message occures when trying to insert the dummy-netconf-server into the server container of the server-list

![yang_error](https://user-images.githubusercontent.com/30954308/52332982-59680f00-29fc-11e9-8fbb-74b2692181ac.png)

The error says, that the parents arent the same even though they have the same name and type, so I guess there are more syntax checks in the background - which are failing in this case.

My Question is, if it is even possible to do what i aim for or do I have to change my strategy completely?

**Comment by michalvasko** [comment]
Hi,
this is simply not possible to do. While these nodes may have the same name and type, they have a different namespace (module name) which makes them completely different nodes. To do this, you would have to read information from one subtree and manually create subtree from the other module with the same information.

Just a note, this would not work even if you used one grouping twice in the same module.

Regards,
Michal

**Comment by cromlegionar** [comment]
That makes sense, thank you for the answer.
