### ISSUE TITLE
"Reached limit" error with deviation model

### ISSUE THREAD

**Issue by abhikeshav** [CESNET/libyang#711]
Hi,

When running yanglint on this model: 

https://github.com/YangModels/yang/blob/master/vendor/cisco/xr/651/cisco-xr-openconfig-network-instance-deviations.yang

We are seeing the below error:

    Reached limit 65536 for storing typedefs

Any ideas about this?

Thanks

**Comment by michalvasko** [comment]
Hi,
we are sorry, but then this model is not supported by *libyang*. We are currently working on a new *libyang* version, which does not have this limit so you will have to wait for its release if you want to use this model.

Regards,
Michal

**Comment by abhikeshav** [comment]
Thank you for your reply, Michal. Strangely, this model just has 500 deviation statements which have nothing to do with typedefs. Not sure where the 65536 typedefs are coming from? I'm wondering if this is a real issue or has a parsing bug been exposed?

**Comment by michalvasko** [comment]
Hi,
you were partly right except only the message was completely wrong, now it should be correct. There is a limit of 256 deviations.

Regards,
Michal

**Comment by abhikeshav** [comment]
Thank you for your response
