### ISSUE TITLE
lyd_find_path with special xpath will cause endless loop

### ISSUE THREAD

**Issue by yangtian127** [CESNET/libyang#712]
Hi

When use lyd_find_path with xpath: '/ietf-interfaces:interfaces*' will cause the function cast_string_realloc endless loop.

Following operations will cause this problem:
1) Add module ietf-interfaces plugin;
2) Add 2000 interfaces to running datastore;
3) On netopeer2-cli, execute get-config command: 
    get-config --source running --filter-xpath /ietf-interfaces:interfaces*

In function cast_string_realloc, if *size is close to 65536, then the while loop will be endless.

**Comment by michalvasko** [comment]
Hi,
it should now correctly warn about the string length.

Regards,
Michal
