### ISSUE TITLE
Gentoo Repository

### ISSUE THREAD

**Issue by f0o** [CESNET/libyang#714]
Hi,

I'm part of the FreeRangeRouting (frr) Team and am responsible for maintaining the Gentoo repository and ebuilds.

Along frr we also have ebuilds for rtrlib as they lacked official ebuilds and were wondering if we could add libyang to our repo as well.

I've pro-actively already written ebuilds for all libyang releases (0.12-0.16-r3) and added it to our repository. I hope you're OK with that.

If you have any Gentoo maintainers, please let us connect so we can grant you write access to the repo for future ebuilds.

Best wishes from Stockholm,
/ f0o

**Comment by rkrejci** [comment]
Hi, we welcome any help with maintaining distro support, so Thanks! We don't have anyone who would currently do the job for Gentoo, so you seem to be the only one.

I you think that there is something which should be preferably in the main libyang repo, please feel free to open pull request.

**Comment by f0o** [comment]
Hi @rkrejci,

No changes are required in your repo :)

The repository is available via Layman (https://overlays.gentoo.org/) as frr-gentoo and the package is called `net-libs/libyang`.

If you want to provide installation instructions, they should reassemble:
```
layman -S
layman -a frr-gentoo
emerge net-libs/libyang
```

**Comment by f0o** [comment]
Hi again @rkrejci,

do you happen to know what the relation between the `-rN` releases relate to the subversion?

such as 0.16.7 would equal to 0.16-r1 or -r2?

**Comment by michalvasko** [comment]
Hi,
there is no specific relation, we were mostly releasing *libyang* because some other project dependent on it (*sysrepo*) was being released. We, then, just took the current version and released it. If the minor version matched the previous release, it became `-r2`.

Regards,
Michal
