### ISSUE TITLE
Need ability to disable implicit paths, or allow explicitly passed modules to override paths

### ISSUE THREAD

**Issue by kwatsen** [CESNET/libyang#716]
`yanglint` implicitly adds the CWD and the path of the module being added to the list of paths to be searched for modules:

```
  -p PATH, --path=PATH  Search path for schema (YANG/YIN) modules. The option can be used multiple times.
                        Current working directory and path of the module being added is used implicitly.
```

But [`xiax`](https://github.com/kwatsen/xiax), which I'm coding to use `yanglint`,  performs a number of module transformations, and the implicit paths are picking up the wrong versions of modules.

For instance, the command line might be:
```
yanglint -s -t rpc  ./ietf-crypto-types@2019-02-26.yang ./ex-crypto-types-usage.yang ./ietf-netconf-acm@2018-02-14.yang ./examples/ex-crypto-types-ghk-rpc.xml
```

But, inside the CWD, there's also a file called `ietf-crypto-types@YYYY-MM-DD.yang` (which `xiax` dynamically transformed into `ietf-crypto-types@2019-02-26.yang`), and the following error is generated:
```
Invalid date "YYYY-MM-DD.yang", valid date in format "YYYY-MM-DD" expected.
```

Two possible solutions:

1. add a flag to disable the addition of implicit paths
2. search user-passed modules before searching any paths (implicit or explicit)

**Comment by michalvasko** [comment]
Hi,
try to use the new `-D` option, should do what you need.

Regards,
Michal

**Comment by kwatsen** [comment]
Hi Machal,

Thanks for the super-speedy turnaround!  👍 

Couple issues:

1.  The -D option isn't accepted:

```
$ yanglint -D -s -t config  ./ietf-crypto-types@2019-02-27.yang ./ex-crypto-types-usage.yang ./ietf-netconf-acm@2018-02-14.yang ./refs/ex-crypto-types-usage.xml
Usage:
    yanglint [options] [-f { yang | yin | tree | tree-rfc | jsons}] <file>...
        Validates the YANG module in <file>, and all its dependencies.

    yanglint [options] [-f { xml | json }] <schema>... <file>...
        Validates the YANG modeled data in <file> according to the <schema>.

    yanglint
        Starts interactive mode with more features.

yanglint error: invalid option: -D
```


2. The --disable-cwd-search is accepted, but the result is the same:

```
$ yanglint --disable-cwd-search -s -t rpc  ./ietf-crypto-types@2019-02-27.yang ./ex-crypto-types-usage.yang ./ietf-netconf-acm@2018-02-14.yang ./refs/ex-crypto-types-ghk-rpc.xml
err : Invalid date "YYYY-MM-DD.yang", valid date in format "YYYY-MM-DD" expected.
```

Note that is I rename the file, then it works fine:

```
$ mv ietf-crypto-types\@YYYY-MM-DD.yang ietf-crypto-types\@YYYY-MM-DD.yang.hide
$ yanglint --disable-cwd-search -s -t auto  ./ietf-crypto-types@2019-02-27.yang ./ex-crypto-types-usage.yang ./ietf-netconf-acm@2018-02-14.yang ./refs/ex-crypto-types-ghk-rpc.xml
$ echo $?
0
```

Could it be that the second part, about `yanglint` implicitly adding the directory that the module came from is still in play?


Thanks again,
Kent

**Comment by michalvasko** [comment]
Hi Kent,
sorry about that, please try again, I was too hasty.

Regards,
Michal

**Comment by kwatsen** [comment]
Now -D and --disable-cwd-search produce consistent results, but still not-explicitly specified modules are being found/used?

I mentioned this also in my previous comment, but perhaps you only saw the -D issue?   My guess is that this is because`yanglint` is still implicitly adding the directory that the module came from, which happens to be my CWD in this case...

**Comment by michalvasko** [comment]
Hi Kent,
now you are asking for a different functionality, to disable not just CWD searchdir but also the directory where the module is (yes, they can match). Anyway, if you now specify `-DD`, no search directories should be used so you will have to specify all the modules explicitly, which is what you want if I understand it correctly.

Regards,
Michal

**Comment by kwatsen** [comment]
Boom, there it is, it works now - thanks!
The only surprise I found was that the modules must be passed to `yanglint` in dependency order.
Sorry if I was unclear before, I did mean all implicit paths in my first message...

**Comment by michalvasko** [comment]
Yes, I could have mentioned that, the modules are being loaded in the order you specify them so you must start with the dependencies in this case.

Regards,
Michal
