### ISSUE TITLE
`-t auto` works, but `-t rpc` doesn't ???

### ISSUE THREAD

**Issue by kwatsen** [CESNET/libyang#717]
Flipping "auto" to "rpc" gives different results:
```
$ yanglint -s -t auto  ./ietf-crypto-types@2019-02-27.yang ./ex-crypto-types-usage.yang ./ietf-netconf-acm@2018-02-14.yang ./refs/ex-crypto-types-ghk-rpc.xml

$ echo $?
0

$ yanglint -s -t rpc  ./ietf-crypto-types@2019-02-27.yang ./ex-crypto-types-usage.yang ./ietf-netconf-acm@2018-02-14.yang ./refs/ex-crypto-types-ghk-rpc.xml
err : Unknown element "rpc". (/)
```

Here's the file:
```
$ cat ./refs/ex-crypto-types-ghk-rpc.xml
<rpc message-id="101"
  xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <action xmlns="urn:ietf:params:xml:ns:yang:1">
    <keys xmlns="http://example.com/ns/example-crypto-types-usage">
      <key>
        <name>empty-key</name>
        <generate-hidden-key>
          <algorithm
           xmlns:ct="urn:ietf:params:xml:ns:yang:ietf-crypto-types">
              ct:rsa2048
          </algorithm>
        </generate-hidden-key>
      </key>
    </keys>
  </action>
</rpc>
```

Is it user error or something else?

In general, I like to never use `auto`, I always want my commands to be explicit.  Is it correct understanding that being explicit should always work, and that `auto` has no special behavior other than auto-sensing the data's "type"?

Thanks, 
Kent

**Comment by michalvasko** [comment]
Hi Kent,
your data is validated using `-t auto` because of a coincidence. `auto` detects what kind of data are supposed to be validated by the top-level XML element. For RPCs, this element name is, naturally, `rpc`. But it happens that NETCONF also encapsulates all RPC messages in an `rpc` element.

So, what *yanglint* generally expects is to validate YANG-only data without any NETCONF-specific constructs. Meaning, if you remove the top-level `rpc` element, it should validate. You may notice that there is similar problem with the `action` element, but it is supported mostly because the definition is in the [YANG RFC](https://tools.ietf.org/html/rfc7950#section-7.15.2) and not NETCONF RFC.

Regards,
Michal

**Comment by kwatsen** [comment]
Okay, removing the "rpc" envelop worked.

And I guess I agree with you that, from a tooling-perspective, you want to only validate the YANG-modeled data so that, e.g., it works equally well for RESTCONF messages...

However, this puts a small wrinkle into how standards are written.  At least to date, I've always included the envelop for reference.   I'll post a message to the NETMOD/NETCONF list regarding the preferred approach.   Tooling can always add or remove the envelop, I suppose...   

This applies to `yanglint` too, but I appreciate that you need to draw the line somewhere.    But I wonder is Postel's Robustness principle might not be a guide here...

**Comment by kwatsen** [comment]
I decided not to send email to the list, after convincing myself that drafts SHOULD include all and any protocol headers and/or envelopes.

From a draft-author perspective, I think that the source-input file SHOULD contain all the protocol headers and/or envelopes, as opposed to tooling trying to fabricate them.   That is, it's easier for tooling to remove than to add.

So, this brings us to which tooling should do the trimming...

Historically, my shell scripts have done it.  For instance:
```
printf "validating ex-api-get-bootstrap-data-rpc-reply-untrusted.xml..."
cat ex-api-get-bootstrap-data-rpc-reply-untrusted.xml | sed '1,5d' | grep -v "output" | grep -v "xmlns=" | sed 's/<conveyed-information>/<conveyed-information xmlns="urn:ietf:params:xml:ns:yang:ietf-sztp-bootstrap-server">/' | sed 's/<owner-certificate>/<owner-certificate xmlns="urn:ietf:params:xml:ns:yang:ietf-sztp-bootstrap-server">/' | sed 's/<ownership-voucher>/<ownership-voucher xmlns="urn:ietf:params:xml:ns:yang:ietf-sztp-bootstrap-server">/' > ex-api-get-bootstrap-data-rpc-reply-untrusted-4nc.xml
response=`yanglint -s -t rpcreply ../ietf-sztp-bootstrap-server\@*.yang ex-api-get-bootstrap-data-rpc-reply-untrusted-4nc.xml ex-api-get-bootstrap-data-rpc-untrusted-4nc.xml 2>&1`
rm ex-api-get-bootstrap-data-rpc-untrusted-4nc.xml
rm ex-api-get-bootstrap-data-rpc-reply-untrusted-4nc.xml
if [ $? -ne 0 ]; then
  printf "failed (error code: $?)\n"
  printf "$response\n\n"
  echo
  exit 1
fi
printf "okay.\n"
```

But, or course, this **only** ever worked for me.

Now I'm working on [`xiax`](https://pypi.org/project/xiax), so I could put the trimming-logic there, and hopefully `xiax` will be used by others, but wouldn't it be better (more generally useful) for the logic to be moved upstream (i.e. to `yanglint`) where it can have the most value?

Thoughts?

Kent


BTW, in case you're wondering what all that script-fu above does:
```
$ cat ex-api-get-bootstrap-data-rpc-reply-untrusted.xml 
HTTP/1.1 200 OK
Date: Sat, 31 Oct 2015 17:02:40 GMT
Server: example-server
Content-Type: application/yang.data+xml

<output
  xmlns="urn:ietf:params:xml:ns:yang:ietf-sztp-bootstrap-server">
  <conveyed-information>base64encodedvalue==</conveyed-information>
  <owner-certificate>base64encodedvalue==</owner-certificate>
  <ownership-voucher>base64encodedvalue==</ownership-voucher>
</output>
```
```
$ cat ex-api-get-bootstrap-data-rpc-reply-untrusted.xml | sed '1,5d'
<output
  xmlns="urn:ietf:params:xml:ns:yang:ietf-sztp-bootstrap-server">
  <conveyed-information>base64encodedvalue==</conveyed-information>
  <owner-certificate>base64encodedvalue==</owner-certificate>
  <ownership-voucher>base64encodedvalue==</ownership-voucher>
</output>
```
```
$ cat ex-api-get-bootstrap-data-rpc-reply-untrusted.xml | sed '1,5d' | grep -v "output" | grep -v "xmlns=" 
  <conveyed-information>base64encodedvalue==</conveyed-information>
  <owner-certificate>base64encodedvalue==</owner-certificate>
  <ownership-voucher>base64encodedvalue==</ownership-voucher>
```
```
$ cat ex-api-get-bootstrap-data-rpc-reply-untrusted.xml | sed '1,5d' | grep -v "output" | grep -v "xmlns=" | sed 's/<conveyed-information>/<conveyed-information xmlns="urn:ietf:params:xml:ns:yang:ietf-sztp-bootstrap-server">/' | sed 's/<owner-certificate>/<owner-certificate xmlns="urn:ietf:params:xml:ns:yang:ietf-sztp-bootstrap-server">/' | sed 's/<ownership-voucher>/<ownership-voucher xmlns="urn:ietf:params:xml:ns:yang:ietf-sztp-bootstrap-server">/'

  <conveyed-information xmlns="urn:ietf:params:xml:ns:yang:ietf-sztp-bootstrap-server">base64encodedvalue==</conveyed-information>
  <owner-certificate xmlns="urn:ietf:params:xml:ns:yang:ietf-sztp-bootstrap-server">base64encodedvalue==</owner-certificate>
  <ownership-voucher xmlns="urn:ietf:params:xml:ns:yang:ietf-sztp-bootstrap-server">base64encodedvalue==</ownership-voucher>
```

**Comment by rkrejci** [comment]
Hi Kent, I'm not sure what exactly you are proposing - you want `yanglint` to support (understand and skip) NETCONF and RESTCONF headers? I'm prefering to follow unix philosophy of doing small tools and be able to interconnect such tools (you also use `sed` and `grep` and you do not expect from `cat` to have filter option).

I understand what you want as a draft author. But `yanglint` is not validating draft's snippets, it validates YANG schema and data. I would like a tool (probably your xiax) able to process snippets from drafts and internally using `yanglint` to validate the data. But it is not directly `yanglint`. I believe that functionality of getting through the protocol headers should be kept outside `yanglint`

**Comment by kwatsen** [comment]
Yes, exactly, you understand the proposal.

As a final effort to persuade you, please consider the following:

1. `yanglint` already validates parts of the NETCONF protocol.  For instance, at top of this thread, it validate the `<action xmlns="urn:ietf:params:xml:ns:yang:1">` element and also (though not shown) validates `<ok/>` and `<rpc-error>` elements.

2. it's likely not an uncommon use-case, even for your traditional users (not even draft authors).  I mean, it's not that much of a stretch to think that someone wants to validate the entire protocol document, is it?   (FWIW, `pyang` validated whole messages, but for NETCONF only).  As I envision it, this only makes `yanglint` more useful (broader applicability), without the need for any new input parameters.

3) Adding onto (2), if I remember correctly, `yanglint` doesn't currently support validating RESTCONF messages.  However, if this is a goal (and I hope it is), then it seems that parsing the HTTP header would be necessary in order to know the name of the resource (node, RPC, action, etc.) being passed in the payload.

That said, I get where you're coming from. I was also going to mention the UNIX philosophy in my previous response too.   So I'll end with some pseudocode and, if you still don't want to do it, then I'll implement it in`xiax`.    Here's the pseudocode:

Preconditions:
  - an input document  (may include NETCONF/XML envelops or RESTCONF/HTTP header/envelopes)
  - the `--type` flag is passed and is NOT set to `auto`  (explicit is good!)

Pseudocode:
```
if first line of text contains an HTTP operation keyword (e.g., GET, PUT, POST, etc.):
      - strip off HTTP headers and assume potential need to strip off RESTCONF envelopes (e.g, input, output, etc.), floating any namespace declarations to descendants.    [Note: the payload MAY be XML or JSON.]
      - add missing ancestor nodes all the way up to the module's top-level node, filling in mandatory nodes with fake values as needed (this converts the RESTCONF payload into a NETCONF payload, which is only necessary because `yanglint` doesn't validate RESTCONF messages yet.

else if input is an XML document and begins with a NETCONF-namespaced element (i.e., rpc, rpc-reply, notification):
      - strip off NETCONF envelopes
      - if it is a "notification", remove the "eventTime" leaf as well

<perform normal  validation logic here>
```

Thoughts?


BTW, converting a RESTCONF payload to a NETCONF payload is really hacky.  It would be much better if `yanglint` could validate the passed resource in situ, without having to reconstitute a valid module-level document.    Is adding support for RESTCONF at all on your roadmap?   Searching the issue-tracker, I don't see anything...

Thanks,
Kent
