### ISSUE TITLE
Question: Thread safe of libyang

### ISSUE THREAD

**Issue by qmm161** [CESNET/libyang#718]
Hi,
If these tow api of libyang are thread safe?
lyd_diff
lyd_find_path

**Comment by michalvasko** [comment]
Hi,
`lyd_diff()` uses an internal flag in the data nodes so it is **not** thread-safe on the same data tree. `lyd_find_path()` **is** fully thread-safe.

Regards,
Michal

**Comment by qmm161** [comment]
Hi,
thanks for quickly answer. 
I have another question, if it is thread safe if one thread call lyd_find_path and another thread call lyd_diff on the same data tree.

**Comment by michalvasko** [comment]
Hi,
unfortunately no, the internal flag has also some (other) meaning for `lyd_find_path()`, it is just that this function does not change it, `lyd_diff()` does.

Regards,
Michal

**Comment by qmm161** [comment]
Hi,
is there any way to fix it?

**Comment by michalvasko** [comment]
Hi,
generally, you should not work with one data tree in several threads. Some functions will work fine, but most will not. You fix it simply by duplicating the data tree and then doing whatever you want with it in each thread.

Regards,
Michal

**Comment by qmm161** [comment]
OK, thanks
