### ISSUE TITLE
Merging config: lyd_node instances from <copy-config> rpc and user defined YANG model.

### ISSUE THREAD

**Issue by Meziden** [CESNET/libyang#719]
I was trying to merge the contents in the `<copy-config>` and the existing user defined one.
```c
//Global lyd_node instance for running datastore
extern struct lyd_node* g_node_config;
//lyd_node instance from <copy-config> rpc.
struct lyd_node* data = lyd_dup(nodeset->set.d[0], LYD_DUP_OPT_RECURSIVE);
...
lyd_merge(g_node_config, data, LYD_OPT_EXPLICIT);
```
The code shown above leads to:
```
libyang[0]: Cannot create rpc "copy-config" for the merge.
```
It seems that the problem is caused by the different `struct lys_node* schema` in these two lyd_node instances, but SIGSEGV shows up after adding `data->schema = g_node_config->schema`.
  
Is there any additional work (convert the lyd_node instances into lyd_node_anydata?) need to be done before the "merge" operation?

**Comment by michalvasko** [comment]
Hi,
first let me clear this, you have a `copy-config` RPC:
```xml
<copy-config>
  <target>
    <running/>
  </target>
  <source>
    <config>
      //anydata content
    </config>
  </source>
</copy-config>
```
Specifically, the `config` node is copied into your `data` node and you want to merge it into `g_node_config`, which is your *running* datastore.

As you correctly noted, you cannot just take the `anydata` node and merge it. You need to take the `anydata` [content](https://netopeer.liberouter.org/doc/libyang/master/group__datatree.html#unionlyd__node__anydata_8value), create a data tree from it (to get correct schema nodes) and then you can merge it. We are doing this in [netopeer2-server](https://github.com/CESNET/Netopeer2/blob/master/server/operations.c#L3184), for example.

Regards,
Michal
