### ISSUE TITLE
How about removing gcc-4.9+ dependence

### ISSUE THREAD

**Issue by shawvi** [CESNET/libyang#720]
Lots of devices are built over older gcc version tool chain. How about removing gcc-4.9+ dependence?
Thanks!

**Comment by michalvasko** [comment]
Hi,
actually, the current *libyang* is possible to build with GCC 4.8.4 (maybe even older, we have not tested) so I have updated requirements in the README. Is this dependency mentioned anywhere else?

Regards,
Michal
