### ISSUE TITLE
Segmentation fault when list unique statement contains characters that are not letters

### ISSUE THREAD

**Issue by jvijtiuk** [CESNET/libyang#722]
Hi,

this is one of the bugs I found while fuzzing libyang.
The following yang model crashes lys_parse_path:
```
module mod6 {
    prefix abc;
    namespace "http://www.example.com";

    list list1 {
        key "key1";
        unique "5niq1";
        leaf key1 {
            type string;
        }

        leaf uniq1 {
            type string;
        }
    }
}
```

The crash can be reproduced by running yanglint or yangfuzz:
```
$ libyang/build/yanglint ~/mod6.yang 
err : Unexpected character(s) 'n' (niq1).
Segmentation fault
```
The problem seems to be the character '5' in the unique value "5niq1".
Replacing the value with "uniq1" removes the segfault. The same issue appears for other characters like $, { and ~. The issue also appears with the unique value "uniq1 $"

If needed, i can provide additional info needed to reproduce the issue.

**Comment by michalvasko** [comment]
Hi,
should work now.

Regards,
Michal
