### ISSUE TITLE
File to parse hex value from xml(libyang error: Invalid value "0x20" in "node-hex" element.)

### ISSUE THREAD

**Issue by corrollFang** [CESNET/libyang#727]
### libyang version: 0.16-r3

According to RFC6020, hex/octet is supported for int/uint, but libyang fails to parse hex value from XML. 
When i use "lyd_parse_path()" to load the XML files, it returns error "**libyang error: Invalid value "0x20" in "node-hex" element.**"

I suppose there may be a mistake in **lyp_parse_value() calling parse_int()/parse_uint() in  parser.c , the parameter _\<base>_ should be 0**.
--------------------yang file--------------------------------

module test-hex{

    namespace "http://test-hex";
    prefix "test-hex";

    container c1
    {
        leaf node-base10
        {
            type uint8;
        }
        leaf node-hex
        {
            type uint8;
        }
    }
}

--------------XML file-----------------------------------

`
<c1 xmlns="http://test-hex">
   <node-base10>100</node-base10> 
   <node-hex>0x20</node-hex>
</c1>
`

**Comment by michalvasko** [comment]
Hi,
it should work exactly as specified, hexadecimal values are not allowed in XML instance data ([3rd paragraph, last sentence](https://tools.ietf.org/html/rfc6020#section-9.2.1)).

Regards,
Michal
