### ISSUE TITLE
lyd_dup will only copy the first xmlelem tree of anyxml node

### ISSUE THREAD

**Issue by mrdotchenke** [CESNET/libyang#729]
The test module was like this:
```
module test {
  namespace "urn:test:yang:test";
  prefix tst;
  revision 2019-01-01;
  container test {
    anyxml data;
  }
  container test2;
}
```

Then I build the node tree with this xml by lyd_parse_mem

```
<test xmlns="urn:test:yang:test">
  <data>
    <test />
    <test2 />
  </data>
</test>
```

The 'data' node in tree was fine. It store 'test' in the lyd_node_anydata.value.xml and the lyd_node_anydata.value.xml.next was pointed to 'test2'.

But when I use lyd_dup to copy the tree, the 'data' node will only has the lyd_node_anydata.value.xml pointed to 'test' and the next was null.

**Comment by michalvasko** [comment]
Hi,
check out `lyd_dup_withsiblings()`.

Regards,
Michal

**Comment by mrdotchenke** [comment]
> Hi,
> check out `lyd_dup_withsiblings()`.
> 
> Regards,
> Michal

Thanks for reply.
I have tried the lyd_dup_withsiblings. Unfortunately it didn't work.
I think the issue is located in tree_data.c:2579

`trg_any->value.xml = lyxml_dup_elem(ctx, src_any->value.xml, NULL, 1);`

Which only copied the xml and children, left the siblings behind.

**Comment by michalvasko** [comment]
Hi,
sorry, was too hasty when reading your issue. Try ti again, should work properly now.

Regards,
Michal
