### ISSUE TITLE
regular expression $ issue

### ISSUE THREAD

**Issue by TiejunShuang** [CESNET/libyang#736]
Hi, 
when we set a string is  described by regular expression and the tail with $. We need put $ to the string  if not, libyang will report error:

libyang error: Value "2019-06-06T12:34:56Z+08:00" does not satisfy the constraint "^[0-9]{4}\-[0-9]{2}\-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\.[0-9]+)?Z[+-][0-9]{2}:[0-9]{2}$"

We need send 2019-06-06T12:34:56Z+08:00**$**,  I think it is not correct. isn't it?

Regards,
Tiejun

**Comment by michalvasko** [comment]
Hi Tiejun,
you will find the explanation in the second paragraph in my reply in the referenced issue.

Duplicate #422

Regards,
Michal
