### ISSUE TITLE
Libyang parse success when "mandatory true" leaf is not provided in request.

### ISSUE THREAD

**Issue by nirmeshRathore** [CESNET/libyang#738]
For ietf-netconf-acm yang
```
/nacm/rule-list/rule/action

leaf action {
          type action-type;
          mandatory true;
          description
            "The ...";
        }
Corresponding yin definition: 

<leaf name="action">
  <mandatory value="true"/>
  <type name="action-type"/>
  <description>
    <text>The...</text>
  </description>
</leaf>
```

When below rpc request is given without "action" leaf, **libyang is not able to validate "mandatory" statement,** it is parsing rpc successfully even if mandatory leaf is not provided.
Expected behaviour  should be to return parsing error "missing-element".

```
<edit-config>
  <target>
    <running/>
  </target>
  <error-option>rollback-on-error</error-option>
  <config>
    <nacm xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-acm">
      <rule-list>
        <name>abc</name>
        <rule xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="create">
          <name>4</name>
        </rule>
      </rule-list>
    </nacm>
  </config>
</edit-config>
```

Please help to provide suggestion for the above problem.
Thanks.

**Comment by michalvasko** [comment]
Hi,
this RPC request is validated as an RPC, naturally. If you look at the definition, the `config` element is of type `anyxml` which means any XML tree is valid, including the one from your example.

Now for a less formal explanation, it often makes sense to use "invalid" data in not just `edit-config` operation so the validation of these config snippets is conderably more relaxed compared to validation of a datastore.

Regards,
Michal

**Comment by nirmeshRathore** [comment]
Ok, got it.
Thanks for the explanation :)
