### ISSUE TITLE
extension data validation

### ISSUE THREAD

**Issue by rjarry** [CESNET/libyang#744]
Hello,

I am trying to implement a custom extension backed by a libyang plugin to do some data validation.

Basically, I need to perform the validation of unicity amongst a set of nodes represented by an xpath. To make sure the condition is only evaluated once, I want to place the extension on a container and the xpath will reference children nodes of that container.

Here is an example:

```yang
module unicity {
  namespace "urn:test:unicity";
  prefix u;
  revision 2019-03-28 {
    description "";
    reference "";
  }

  extension unique-values {
    argument "xpath";
    description "All node values referenced by the xpath must be unique.";
  }

  container data {
    unique-values "*/name";
    list first {
      key name;
      leaf name {
        type string;
      }
    }
    list second {
      key name;
      leaf name {
        type string;
      }
    }
  }
}
```

I implemented a minimalist plugin:

```c
struct lyext_plugin unique_values = {
	.type = LYEXT_FLAG,
	.flags = LYEXT_OPT_VALID,
	.check_position = &unique_values_check_position,
	.check_result = &unique_values_check_result,
	.valid_data = &unique_values_valid_data,
};

struct lyext_plugin_list unicity[] = {
	{"unicity", "2019-03-28", "unique-values", &unique_values},
	{NULL, NULL, NULL, NULL} /* terminating item */
};
```

I copied the .so file into the "extensions" folder and I checked with gdb that my plugin is loaded. The `unique_values_check_position` and `unique_values_check_result` are indeed called when the yang schema is parsed.

However, the `unique_values_valid_data` callback is never called upon data validation with a data tree containing list elements that have identical "name" values in both lists. I'm not sure why.

Did I miss something? Could you help?

**Comment by michalvasko** [comment]
Hi,
what is important in this case is to know that there are some validation optimizations implemented, which can be summarized as whenever a change was performed that does not affect some other node, the node will not be validated again.

I am not sure how exactly are you working with the data but the callback should be called on the container `data` creation and modifications. Generally, there is no validation of *containers* needed so whatever changes you make to the list descendants of `data`, the callback will not be called even if it has an extension. So, you could instantiate the extension in either both lists `first` and `second` or even in their keys `name` and this way achieve that the callback will always be called.

Regards,
Michal

**Comment by rjarry** [comment]
Hi,

> what is important in this case is to know that there are some validation optimizations implemented, which can be summarized as whenever a change was performed that does not affect some other node, the node will not be validated again.

I am aware of that. However, when validating a large data tree which contains a large number (say 10000) list elements, it means running the validation at least once per leaf. If the validation condition is "checking that the value is unique" amongst all these list elements, we get a complexity of O(n^2).

> I am not sure how exactly are you working with the data but the callback should be called on the container `data` creation and modifications. Generally, there is no validation of _containers_ needed so whatever changes you make to the list descendants of `data`, the callback will not be called even if it has an extension. So, you could instantiate the extension in either both lists `first` and `second` or even in their keys `name` and this way achieve that the callback will always be called.

For now, the only solution I found with `must` conditions on leafs is as follows:

```yang
module unicity {
  namespace "urn:test:unicity";
  prefix u;
  revision 2019-03-28 {
    description "";
    reference "";
  }

  container data {
    list first {
      key name;
      leaf name {
        must "count(../../*/name[text()=current()]) = 1" {
          error-message "name must be unique.";
        }
        type string;
      }
    }
    list second {
      key name;
      leaf name {
        must "count(../../*/name[text()=current()]) = 1" {
          error-message "name must be unique.";
        }
        type string;
      }
    }
  }
}
```

But this does not scale at all when increasing the number of elements.

If the condition could go on a parent container, it will be evaluated only once. However, the `unique()` xpath function does not exist :) This is why I wanted to implement it with a custom extension.

It seems like there is a [distinct-values](http://www.xsltfunctions.com/xsl/fn_distinct-values.html) xslt function which could be used to achieve this. Unfortunately, it is part of the xpath 2.0 specification and [RFC 7950 only mentions xpath 1.0](https://tools.ietf.org/html/rfc7950#ref-XPATH).

**Comment by michalvasko** [comment]
Hi,
I thought you were just testing the extensions, not that it is a real use-case. In that case my advice is to try to modify the YANG model in some way so that it uses the YANG built-in `unique` statement, it is possible to enforce this constraint on nested lists. The reason is that *libyang* uses internal hash tables for this validation and that should scale nicely.

Regards,
Michal

**Comment by rjarry** [comment]
Unfortunately, the lists are not nested. They are all flat in the same container. Unless I'm mistaken, the YANG `unique` statement will not help here.

**Comment by rjarry** [comment]
To clarify, why I have multiple lists. In the YANG model, we have something along those lines:

```yang

container interface {
  list physical {
    key name;
    leaf name {
      type string;
    }
    /* other physical interfaces leafs */
  }
  list vlan {
    key name;
    leaf name {
      type string;
    }
    /* other vlan interfaces leafs */
  }
  list gre {
    key name;
    leaf name {
      type string;
    }
    /* other gre interfaces leafs */
  }
}
```

For clarity reasons, the interfaces are grouped by family. And for system restrictions, there may not be 2 interfaces with the same name.

**Comment by michalvasko** [comment]
Hi,
it will still not be as efficient as it could be with `unique` but now if a node has an extension validation callback and its (direct) child is created/deleted, the callback should be called. That should cover your original case as long as you only reference direct children in the `xpath` argument.

Regards,
Michal

**Comment by rjarry** [comment]
Thanks, I'll give this a try.

**Comment by rjarry** [comment]
Hi @michalvasko ,

I tried applying your patch and indeed it only works when the modified leaf is a direct child of the container/list that has the extension. This is a problem for my use-case so I made some changes, please see PR #748.
