### ISSUE TITLE
replace strtoll with strtoull

### ISSUE THREAD

**Issue by yonghuhaige** [CESNET/libyang#745]
uint64 range validate fail.
tmp_local_intv->value.uval.max = strtoll("18446744073709551615") is not 18446744073709551615.
please replace strtoll with strtoull in line 3087 and line 3143

https://github.com/CESNET/libyang/blob/ff02ecaed43523019411fd38309444786c4dbd52/src/resolve.c#L3087

https://github.com/CESNET/libyang/blob/ff02ecaed43523019411fd38309444786c4dbd52/src/resolve.c#L3143

**Comment by michalvasko** [comment]
Hi,
no problem, thanks.

Regards,
Michal
