### ISSUE TITLE
Regressions in 1.0-r2 on S390

### ISSUE THREAD

**Issue by cfra** [CESNET/libyang#747]
I was just informed by the Alpine Linux people that libyang's tests are failing on S390 for 1.0-r2 while they were passing fine for 0.16-r3.

Details can be found here: https://github.com/alpinelinux/aports/pull/6959

**Comment by michalvasko** [comment]
Hi,
I have just tried it on Ubuntu 14.04.6 32b (the closest I can get to that platform) and all the tests passed. So, we will need much more information if we are to fix this. For starters, the output of those failing tests.

Regards,
Michal

**Comment by tuan-hoang1** [comment]
Hello Michal @michalvasko,

There are 3 tests fail so far:
test_parse_print
test_yang_data
test_lyb

The (very long) of test log could be found here : http://tpaste.us/O1OX. Keyword 'FAILED'  might be useful.

It seems commit bd7b3145aff104d5d868795fd0657fcca06fd1ec causes the failures. If you need a s390x Alpine machine to test, please let me know.

Thanks Christian @cfra  for reporting !

**Comment by tuan-hoang1** [comment]
It's seems to be s390x bug in general, not just Alpine. I got Illegal Exception on Ubuntu 18.04 s390x on these 3 tests.

**Comment by michalvasko** [comment]
Hi,
thanks for the information, based on that it could have been a little-endian problem, can you please rerun the tests?

Regards,
Michal

**Comment by tuan-hoang1** [comment]
Yes, it's must be big endian problem. I'm on master and 3 tests still fail on Ubuntu s390x.

In fact commit bd7b3145aff104d5d868795fd0657fcca06fd1ec causes test_yang_data failure.
Commit ada77b7a379fbf01a628cfb159edc25770e30ba6 causes test_parse_print failure. I'm tracking down the one causing test_lyb.
