### ISSUE TITLE
Test failes on s390x v1.0-r2

### ISSUE THREAD

**Issue by tuan-hoang1** [CESNET/libyang#749]
As previously reported and discussed in https://github.com/CESNET/libyang/issues/747, the issues has not been fixed with latest commit https://github.com/CESNET/libyang/commit/5b3c324097fa3e122edb774213aeafd6eba137f9 so I create this new issue for further discussion.

Commit https://github.com/CESNET/libyang/commit/ada77b7a379fbf01a628cfb159edc25770e30ba6 breaks test `test_parse_print`.
Commit https://github.com/CESNET/libyang/commit/bd7b3145aff104d5d868795fd0657fcca06fd1ec breaks test `test_yang_data`.
Commit https://github.com/CESNET/libyang/commit/a343e1f3936e0276ef786b03d22b1ef662dfdfb1 breaks test `test_lyb`.

Without latest fix https://github.com/CESNET/libyang/commit/5b3c324097fa3e122edb774213aeafd6eba137f9, short log of running test : http://tpaste.us/wjVJ, long log : http://tpaste.us/O1OX.

With latest fix https://github.com/CESNET/libyang/commit/5b3c324097fa3e122edb774213aeafd6eba137f9,
short log : `/usr/bin/ctest --force-new-ctest-process --output-on-failure` at : http://tpaste.us/roM1.

Long log : `/usr/bin/ctest --force-new-ctest-process --output-on-failure -VV --debug` at : http://tpaste.us/P09e.

**Comment by michalvasko** [comment]
Hi,
we could have continued in the previous issue, I am just constantly switching between tasks so I did not manage to look at this more yesterday. You said you could give me access to an S390X machine and I would appreciate that. Does it also have any debugging tools? Plain `gdb` would do.

Regards,
Michal

**Comment by tuan-hoang1** [comment]
Hi Michal @michalvasko,

It could be either Alpine edge s390x or Ubuntu 18.04 s390x with all the required tools you need. Could you provide me your SSH keys ? https://github.com/michalvasko.keys doesn't return any SSH keys for me.

**Comment by michalvasko** [comment]
Hi,
if the Alpine has `gdb`, I will be fine with that. If not, Ubuntu will be better. I have also added an SSH key to my GitHub account, thanks.

Regards,
Michal

**Comment by tuan-hoang1** [comment]
Yes, Alpine has everything :) I added `strace, gdb, gcc, g++` for you. If you need something else, please run 
`$ sudo apk search pkgname`
`$ sudo apk add pkgname`

The credentials is : `libyang@148.100.88.56`. You have sudo.

Many thanks !

**Comment by michalvasko** [comment]
Hi,
so now it should work, the tests passed for me on the Alpine, in any case. Thanks again for the access, it made debugging much easier (I have not installed anything except for a few packages but I guess it was a virtual system, anyway).

Regards,
Michal

**Comment by tuan-hoang1** [comment]
Thank you !

Fyi, you could setup qemu s390x emulation (tcg mode) on x86 hardware if you ever need one (https://wiki.qemu.org/Documentation/Platforms/S390X#Debian_Install_Example_.28TCG.29). Or you could ping me anytime.

My pleasure, Michal.

**Comment by michalvasko** [comment]
Yeah, that may not be such a bad idea but I do not have much experience with QEMU so it would probably take me some time. Thanks for the link.

Regards,
Michal
