### ISSUE TITLE
User types collision

### ISSUE THREAD

**Issue by rwestphal** [CESNET/libyang#751]
I have a program that implements the following user types:
```c
struct lytype_plugin_list frr_user_types[] = {
	{"ietf-inet-types", "2013-07-15", "ipv4-address", ipv4_address_store_clb, free},
	{"ietf-inet-types", "2013-07-15", "ipv4-address-no-zone", ipv4_address_store_clb, free},
	{"ietf-inet-types", "2013-07-15", "ipv6-address", ipv6_address_store_clb, free},
	{"ietf-inet-types", "2013-07-15", "ipv6-address-no-zone", ipv6_address_store_clb, free},
	{"ietf-inet-types", "2013-07-15", "ipv4-prefix", ipv4_prefix_store_clb, free},
	{"ietf-inet-types", "2013-07-15", "ipv6-prefix", ipv6_prefix_store_clb, free},
	{NULL, NULL, NULL, NULL, NULL} /* terminating item */
};   
```

Using libyang v1.1.2, I get the following errors when starting my program:
```
2019/04/10 10:09:11 errors: RIP: libyang: Processing "user_inet_types" extension plugin failed,implementation collision for extension ipv6-address from module ietf-inet-types@2013-07-15.
2019/04/10 10:09:11 errors: RIP: libyang: Processing "user_inet_types" extension plugin failed,implementation collision for extension ipv6-address from module ietf-inet-types@2013-07-15.
```

The conflicts happen because libyang also implements more or less the same user types (_src/user_types/user_inet_types.c_):
```c
struct lytype_plugin_list user_inet_types[] = {
    {"ietf-inet-types", "2013-07-15", "ip-address", ip_store_clb, NULL},
    {"ietf-inet-types", "2013-07-15", "ipv6-address", ip_store_clb, NULL},
    {"ietf-inet-types", "2013-07-15", "ip-address-no-zone", ip_store_clb, NULL},
    {"ietf-inet-types", "2013-07-15", "ipv6-address-no-zone", ip_store_clb, NULL},
    {"ietf-inet-types", "2013-07-15", "ip-prefix", ip_prefix_store_clb, NULL},
    {"ietf-inet-types", "2013-07-15", "ipv4-prefix", ipv4_prefix_store_clb, NULL},
    {"ietf-inet-types", "2013-07-15", "ipv6-prefix", ipv6_prefix_store_clb, NULL},
    {NULL, NULL, NULL, NULL, NULL} /* terminating item */
};
```

Now I have a few questions:
* Is there a way to prevent libyang from loading the user types distributed with the library? Looking at `ly_load_plugins()` it doesn't seem like this is possible now. One hack would be create an empty dir under `/tmp` and set `LIBYANG_USER_TYPES_PLUGINS_DIR` to that dir, but this would be a bit convoluted.
* The same errors didn't happen when using libyang 0.16-r3. Any idea why? I suppose the conflicts were happening as well, but somehow the user types defined by my application were taking precedence over the libyang user types.
* In addition to `ipv6-address`, my program implements other user types that are also implemented by libyang. But libyang complains about `ipv6-address` only.
* The `free_clb` callback of the libyang user types are set to NULL. Can't this cause memleaks when data nodes are deleted?

Thanks in advance!

PS: I loved the API change that makes it possible to change the `value_str` of the user types. This way I can normalize prefixes according to their masks (e.g. 10.10.10.0/8 -> 10.0.0.0/8). Thanks for that!

**Comment by michalvasko** [comment]
Hi,
that is exactly it, the API was changed so that even the string value can change primarily so that the values can be transformed into their canonical format. All types needing this transformation are now implemented as user types. This is new for *libyang* 1.0. Also, they do not need `free_clb` because they are stored in the standard way, only canonization is performed.

As for your collisions, the simplest solution would probably be to replace the library plugin with your one, but then you should also always perform the canonization, otherwise *netopeer2-server* could reply with a non-canonical value which is not allowed in NETCONF. What do you think?

Regards,
Michal

**Comment by rwestphal** [comment]
> Hi,
> that is exactly it, the API was changed so that even the string value can change primarily so that the values can be transformed into their canonical format. All types needing this transformation are now implemented as user types. This is new for _libyang_ 1.0.

Awesome :)

> Also, they do not need `free_clb` because they are stored in the standard way, only canonization is performed.

Indeed, I didn't realize `value->ptr` wasn't being touched.

> As for your collisions, the simplest solution would probably be to replace the library plugin with your one, but then you should also always perform the canonization, otherwise _netopeer2-server_ could reply with a non-canonical value which is not allowed in NETCONF. What do you think?

Sure, I'm planning to perform canonization in my user types as well. But how can I replace the library plugin with my own? I'm using `ly_register_types()` to register my user types, but `ly_load_plugins()` (called from `ly_new_ctx()`) will still load the .so's from `LY_USER_TYPES_PLUGINS_DIR`, leading to the conflicts.

**Comment by michalvasko** [comment]
Hií,
I literally meant replace, the *libyang* user type plugin file with yours.

Regards,
Michal

**Comment by rwestphal** [comment]
Unfortunately this isn't a possibility for us. We're using `ly_register_types()` exactly because we don't want to have a separate .so for our libyang user types, as that has several implications (please see #666).

In my opinion it would be nice if the libyang user types distributed with library could be overwritten by the application. Example: if I have a custom implementation for "ipv4-address", then use it instead of using the libyang's one. Other user types that weren't overwritten (e.g. "ipv6-address") would still be available.

Other possibility would be to add a flag to `ly_ctx_new()` like `LY_CTX_DISABLE_STD_USER_TYPES`. But I think this wouldn't be the ideal solution as the user types distributed with the library perform canonization of the values as you said. So the ability to overwrite only a subset of the libyang user types would be the ideal solution in my opinion (without emitting a warning).

**Comment by rwestphal** [comment]
> In my opinion it would be nice if the libyang user types distributed with library could be overwritten by the application. Example: if I have a custom implementation for "ipv4-address", then use it instead of using the libyang's one. Other user types that weren't overwritten (e.g. "ipv6-address") would still be available.

I think this was the behavior implemented by libyang 0.16.x. Will check here now.

**Comment by rwestphal** [comment]
> > In my opinion it would be nice if the libyang user types distributed with library could be overwritten by the application. Example: if I have a custom implementation for "ipv4-address", then use it instead of using the libyang's one. Other user types that weren't overwritten (e.g. "ipv6-address") would still be available.
> 
> I think this was the behavior implemented by libyang 0.16.x. Will check here now.

So, libyang 0.16-r3 doesn't install the "user_ipv4" user type by default as it's considered as an example only. This is probably why I didn't have this conflict problem before.

I was thinking here and maybe there's no easy solution to this problem. Allowing `ly_register_types()` to overwrite existing user types would be dangerous as there might already exist `lyd_nodes` that were created using the overwritten user type implementation. So the application could get into a state where it doesn't know how to interpret the `value->ptr` of its data nodes.

For now I'll adapt FRR to avoid using user types since they are not strictly necessary for us at this point. I'll close this issue (I might reopen it in the future if necessary).

**Comment by michalvasko** [comment]
Hi,
you are right, there is the problem you mentioned and we will try to solve it somehow for the new *libyang*.

Regards,
Michal

**Comment by rwestphal** [comment]
So, thinking more about this issue, dropping custom user types in my application actually wouldn't be a good idea.

Maybe we can work around this problem by defining a special value like `none` for the `LIBYANG_USER_TYPES_PLUGINS_DIR` env variable which would mean that the library shouldn't look for user types in any directory.

I think this would help all users who want to implement their own user types, without risking having the same user types implemented by libyang. If you think this is a good idea I can open a PR for this tomorrow.

**Comment by michalvasko** [comment]
Hi,
right, so for your use-case you should be fine with simply changing `LIBYANG_USER_TYPES_PLUGINS_DIR` to either some random directory with no plugins (which is a bit weird solution, but should work) or to an invalid path (but you will get a warning). Is this not a suitable solution at least until new *libyang* is be finished?

Regards,
Michal

**Comment by rwestphal** [comment]
Yeah, not beautiful but it should work. I guess I can use `mkdtemp(3)` for that. This should be fine as an interim solution until libyang2 is released.

Thanks.
