### ISSUE TITLE
Issue parsing matching data in subtree filter for instance-identifier

### ISSUE THREAD

**Issue by amandeepsethi** [CESNET/libyang#754]
I am trying to parse data using matching subtree filter passed but getting issue in getting a match for instance-identifier.
I am using latest version (1.0.4) of libyang but the result is same. Though code used for Netopeer2 server is previous version of internal implemented filter APIs (my project limitation is not to use sysrepo library).
Attached are my code files for reference. Request you to please provide your inputs.

My Filter is:
```
<get>
    <filter type="subtree">
        <student:student-data
            xmlns:student="urn:test:params:xml:ns:yang:student">
            <student:resource
                xmlns:stream="urn:test:params:xml:ns:yang:stream">/stream:subject[stream:name='medical']
            </student:resource>
        </student:student-data>
    </filter>
</get>
```

My data is:
```
<student-data
    xmlns="urn:test:params:xml:ns:yang:student">
    <id>7</id>
    <resource
        xmlns:stream="urn:test:params:xml:ns:yang:stream">/stream:subject[stream:name=&apos;medical&apos;]
    </resource>
</student-data>
```
[Code.zip](https://github.com/CESNET/libyang/files/3079653/Code.zip)

**Comment by michalvasko** [comment]
Hi,
there are 2 problems. I have fixed one in https://github.com/CESNET/Netopeer2/commit/fd383513c14908da93762c8412007f03906b864d (support for `'` in the content). The other is JSON vs XML instance-identifiers. The filter is expected to be in the JSON format while the data are in XML format. *netopeer2* should handle this correctly, but for this use-case you need to change `/stream:subject[stream:name='medical']` to `/stream:subject[name='medical']`. Then it worked for me.

Regards,
Michal

**Comment by amandeepsethi** [comment]
Thanks Michal for the quick fix, filters generated are now working for me and able to fetch data.
