### ISSUE TITLE
--running param looks for `config false` nodes

### ISSUE THREAD

**Issue by kwatsen** [CESNET/libyang#763]
I'm getting this error message:
```
err : Missing required element "denied-operations" in "nacm". (/ietf-netconf-acm:nacm)
yanglint error: Failed to parse the running datastore file for RPC/Notification validation.
```

From running this command:
```
yanglint -s -t notif -r ex-crypto-types-usage.xml ../ietf-*\@20*.yang  ../ex-crypto-types-usage.yang yanglint-    notification.xml
```

Looking at `ietf-netconf-acm\@2012-02-22.yang` I see:
```
    leaf denied-operations {
      type yang:zero-based-counter32;
      config false;
      mandatory true;
      description
        "Number of times since the server last restarted that a
       protocol operation request was denied.";
    }
```

Yes, it is mandatory true, but it's also `config false`.

According to `yanglint --help`:
```
  -r FILE, --running=FILE
              - Optional parameter for 'rpc', 'rpcreply' and 'notif' TYPEs, the FILE contains running  
                configuration datastore data referenced from the RPC/Notification. The same data       
                apply to all input data <file>s. Note that the file is validated as 'data' TYPE.       
                Special value '!' can be used as FILE argument to ignore the external references.      
```

I think that the `config false` nodes should be ignored in <running>.   Perhaps you want another flag '--operational'?

**Comment by kwatsen** [comment]
PS: I can't believe that I'm the first to find this issue!   Perhaps NACM isn't used very often?  ;)

**Comment by michalvasko** [comment]
Hi Kent,
you are right that the parameter name `running` was misleading but in its description is written that it is parsed as `data` type meaning configuration and state data, so the error is correct. However, it is not necessary to validate this additional data, the notification validation is the point, so if you try ti again, it should work. Also, the parameter was renamed to `-O --operational` to better reflect what data are expected although the old parameter was kept hidden for compatibility, so it will still work.

Regards,
Michal
