### ISSUE TITLE
When use lyd_parse_path to parse json data,if the key is not at the first place of a list ,the error path not contains the key

### ISSUE THREAD

**Issue by ZhaoGuangYue1986** [CESNET/libyang#764]
When use lyd_parse_path to parse json data,if the key is not at the first place of a list ,the error path not contains the key
Think conditions like below ,all the list key is moId.

condition one:
moId of Test is at the first place ,when leaf_4 in is not define in yang model, when we use  lyd_parse_path to parse it ,the err-path is "/Me:Me/Test:Test[moId='1']/TestModel",not "/Me:Me/Test:Test[moId='1']/TestModel[moId='20']"
```json
{
	"Me:Me": {
		"Test:Test": [{
			"moId": "1",
			"TestModel": [
			{
				"leaf_4": "XX",
				"moId": "20"
			}]
		}]
	}
}
```
condition two:
both  moId  of Test and TestModel is not at the first place ,the err-path is "/Me:Me/Test:Test/TestModel",not"/Me:Me/Test:Test[moId='1']/TestModel[moId='20']"
```json
{
	"Me:Me": {
		"Test:Test": [{
			"TestModel": [
			{
				"leaf_4": "XX",
				"moId": "20"
			}],
                     "moId": "1"
		}]
	}
}
```

**Comment by michalvasko** [comment]
Hi,
could you please provide the YANG module and possibly other files and information so that I can reproduce it? Thanks.

Regards,
Michal

**Comment by ZhaoGuangYue1986** [comment]
------------------Me  module----------------------------------
module Me {
    namespace "urn:me:params:xml:ns:yang:ran:Me";
    prefix ME;

    container Me {
        leaf name {
            type string{
                length "1..49";
                pattern '[A-Za-z0-9\-]+';
            }
        }
    }
}





------------------Test  module----------------------------------
module Test {
    namespace "urn:me:params:xml:ns:yang:ran:Test";
    prefix t1;
 
    import Me{
        prefix Me;
    }
    grouping TestModel_List {
        list TestModel {
			key moId;
			leaf moId {
				type string;
			}
			leaf leaf_1 {
				type int8;
				default 1;
			}
			leaf leaf_2 {
				type string;
			}
        }
    }

	grouping Test_List {
        list Test {
			key moId;
			leaf moId {
				type string;
			}
			
			uses TestModel_List;
		}		
	}	
	
    augment "/Me:Me" {
        uses Test_List;
    }
}

**Comment by michalvasko** [comment]
Hi,
only when I reproduced it I understood what the issue is. The error messages are just fine, the problem is that the parser stops when it finds an unknown node meaning no following nodes are parsed. That is the reason the keys are missing in the errors, nothing to fix here.

Regards,
Michal
