### ISSUE TITLE
Is it better to judge ly_print and ly_print_flush result in  xml_print_data and json_print_data and others

### ISSUE THREAD

**Issue by ZhaoGuangYue1986** [CESNET/libyang#766]
In  function xml_print_data and json_print_data  and others ,we do not  judge  ly_print or ly_print_flush result. this is mean we do not deal  fail result which return by ly_print  and ly_print_flush , I think this is not safe and correct. what about your opinion?

**Comment by michalvasko** [comment]
Hi,
`ly_print_flush()` does not return any value, so there is nothing to check. `ly_print()` can fail only when something really fatal occurs (such as no memory), in which case there is little to do anyway. Checking it always would just add clutter into the code, it is fine the way it is.

Regards,
Michal

**Comment by ZhaoGuangYue1986** [comment]
1. ly_print_flush() not return value is because we do not return fflush() result, but fflush it may fail.

2.Not only Sysrepo but also our program is using  function lyd_print_fd() to  persist data to file. This is mean If  xml_print_data  or  json_print_data does not return correct vales ,the function  lyd_print_fd would not return correct vales too.And we do not known the fail result.
 If the disk is full, it can not write anything on it, in this condition, is lyd_print_fd also return success? if this, the file size may be zero, or partly of the lyd_data_tree. This is very seriously problem for the system, the system can not restart again ,as the data is not correct.

**Comment by michalvasko** [comment]
Hi,
should be fine now. Just a note, LYB printer should be used where possible for best efficiency and it checks return values everywhere.

Regards,
Michal
