### ISSUE TITLE
leaf-list nodes not matched by xpath  /test-module:*//*

### ISSUE THREAD

**Issue by milanlenco** [CESNET/libyang#77]
I have similar problem like last week when xpath `/test-module:*//*` wouldn't match all nodes. Previously I had outdated libyang version, this time I'm testing with the latest version.

Yang scheme:
```
module test-module {
  namespace "urn:ietf:params:xml:ns:yang:test-module";
  prefix tm;

  organization "organization";
  description
    "example yang module";
  contact
    "example@example.org";


  leaf-list ordered-numbers {
    ordered-by user;
    type uint8;
  }
}
```

Current data tree:
```
<ordered-numbers xmlns="urn:ietf:params:xml:ns:yang:test-module">1</ordered-numbers>
<ordered-numbers xmlns="urn:ietf:params:xml:ns:yang:test-module">2</ordered-numbers>
<ordered-numbers xmlns="urn:ietf:params:xml:ns:yang:test-module">3</ordered-numbers>
```

Running "lyd_get_node" with xpath `/test-module:*//*`, however, returns no nodes.

Stepping through the code it seems that eval_node_test() is called two times from eval_relative_location_path(). First eval_node_test() calls moveto_node() with `qname="test-module:*//*"` which fills the "set" with all three nodes, while second eval_node_test() calls moveto_node_alldesc() with `qname="*"` which removes everything here:
```
/* replace the original nodes (and throws away all text and attr nodes, root is replaced by a child) */
ret = moveto_node(set, cur_node, "*", 1, options);
```
and adds nothing.

**Comment by michalvasko** [comment]
Hi,
all of this is correct. To get all the nodes use just `/test-module:*`. Generally, to get all the nodes of a module you must use `/module:*//.`.

Regards,
Michal
