### ISSUE TITLE
Double free or corruption in lys_parse_path

### ISSUE THREAD

**Issue by jvijtiuk** [CESNET/libyang#774]
The following file causes a double free.
The value is freed at tree_schema.c:2891 and seems to be allocated at parser.c:624.

```
module state-lists {
    yang-version 1.1;
    namespace "urn:state-lists";
    prefix sl;

    container cont {
		config false;
		grouping group1 {
            leaf leaf3 {
     			type tdef2 {
      				length "3..9 | 30..40";
      				pattern "[ac
				}*";
    		}

    		units "none";
    		default "aaa";
  		}

		typedef tdef2 {
			type string {
				length "2..17 | 20..50";
				pattern "[ab]*";
			}
		}

  		container cont1 {
    		uses group1 {
      			if-feature "feat2";
      			refine "leaf1" {
        			if-feature "feat3";
				    must "24 - 4 = number('20')";
        			default "25";
        			config true;
        			mandatory false;
        			description "dsc";
        			reference "none";
      			}
    		}

			leaf leaf4 {
				type int64 {
					range "1000 .. 50000" {
						error-message
						"Special e        
					}
					.";
				}
			}
    	}

      }
    }
  }
}
```

**Comment by jvijtiuk** [comment]
This file also causes a hang in yanglint on the libyang2 branch.

**Comment by michalvasko** [comment]
Hi Juraj,
we have decided continuing to fuzz the current YANG parser does not make much sense, so it would be great if you could use the one from `libyang2` branch. Also, best way of sharing binary modules is to attach them here directly (zipped maybe).

Regards,
Michal

**Comment by jvijtiuk** [comment]
Ok, I will set up the fuzzer to fuzz the libyang2 parser, and test the remaining bugs the fuzzer found with the new parser.

Regards,
Juraj

**Comment by rkrejci** [comment]
should be fixed in libyang2

**Comment by jvijtiuk** [comment]
libyang2 now successfully reports that the input is not valid, so I'm closing the issue.
