### ISSUE TITLE
Question: why accept 10 decimal  in rpc message?

### ISSUE THREAD

**Issue by foxge** [CESNET/libyang#775]
https://github.com/CESNET/libyang/blob/d1ad4eed42be2f7328ea33c8ae46d3f740625683/src/parser.c#L1747

```
<rpc>
  <edit-config>
    <target><running/></target>
    <config>
      <test>
       <t1>0x1</t1> //t1 is a int8/int16/... leaf
      </test>
    </config>
  </edit-config>
</rpc>
```
For example, the above rpc message is invalid identified by libyang if the leaf t1 input is hexadecimal data.

**Comment by michalvasko** [comment]
Hi,
hexadecimal or octal number are accepted only as integer default values ([ref](https://tools.ietf.org/html/rfc7950#section-9.2.1)). If you can point me to another allowed use, I will change *libyang* accordingly.

Regards,
Michal

**Comment by foxge** [comment]
Hi,
You are very right.
Thanks.
