### ISSUE TITLE
enabling cache causes problem

### ISSUE THREAD

**Issue by gitter-runner** [CESNET/libyang#776]
Hi!

I recently ran into an issue with libyang, where the enabling the cache (ENABLE_CACHE
flag) changes the behavior of the lyd_parse_xml() function.

Namely, when the caching is turned OFF, lyd_parse_xml() returns with NULL when parsing an RPC which otherwise parsed successfully.

Is this a known issue, or the fault might be somewhere else and I'm just overlooking something?

Thanks for the help!

**Comment by michalvasko** [comment]
Hi,
it is not a know issue so please provide the RPC that fails to parse so I can reproduce it.

Regards,
Michal

**Comment by gitter-runner** [comment]
Hi,

RPC:

<?xml version="1.0" encoding="utf-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"
     message-id="1">
  <edit-config>
    <target>
      <running/>
    </target>
    <config>
      <basics xmlns="urn:com:test">
        <scalar>0</scalar>
      </basics>
    </config>
  </edit-config>
</rpc>

module:

module test {
  yang-version 1.1;
  namespace "urn:com:test";
  prefix test;

  organization "Test GmbH";

  contact
    "test@test.com";

  description
    "Test module";

  revision 2019-04-30 {
    description
      "Initial revision.";
    reference "";
  }

  container basics {
    description
      "Nothing too fancy here, just a couple of simple nodes.";

    leaf scalar {
      type int32;
      description
        "An int32 value.";
    }
  }
}

**Comment by michalvasko** [comment]
Hi,
thanks but I need much more information because when I simply tried to send this RPC using *netopeer2-cli* and *netopeer2-server* it worked just fine (having *libyang* installed without cache). So, what exactly is your use-case? Are you using *sysrepo*/*netopeer2* even? But it should not be possible to parse the RPC you pasted directly because it is NETCONF-specific, you can only parse the child `edit-config`, is that what you are doing?

Regards,
Michal

**Comment by gitter-runner** [comment]
Hi,
I'm trying to write my own Netconf server.
I first use lyd_find_path() to get the config (this is how Netopeer does it also), then try to parse it with lyd_parse_xml(). This worked fine when a libyang was compiled with the cache enabled. The libyang version should be the latest (1.0.4), although the architecture is PowerPC.

```
struct ly_set *nodeset;
nodeset = lyd_find_path(rpc, "/ietf-netconf:edit-config/config");
  if (nodeset->number) {
    struct lyd_node_anydata *nodeset_data = (struct lyd_node_anydata *)nodeset->set.d[0];
    node = lyd_parse_xml(nc_server.ly_context, &nodeset_data->value.xml, LYD_OPT_EDIT | LYD_OPT_STRICT);
    if (node == NULL) {
      struct nc_server_error *err = nc_err(NC_ERR_BAD_ELEM, NC_ERR_TYPE_RPC);
      return nc_server_reply_err(err);
    }
    ly_set_free(nodeset);
   ....
```

**Comment by michalvasko** [comment]
Hi,
I have tried this on my x86_64 and it worked just fine, as expected. So yes, having a different platform could easily be the problem. So, you should also check that `nodeset_data` value is in XML format, not some other, but that is probably not the problem now. What is the error when it fails to parse?

Regards,
Michal

**Comment by gitter-runner** [comment]
Hi,
I finally found out what was the problem.
My bad, I apparently forgot to install the headers too after turning off the cache and rebuilding libyang.

Regards
