### ISSUE TITLE
libyang2 lys_parse_path segmentation fault due to invalid character

### ISSUE THREAD

**Issue by jvijtiuk** [CESNET/libyang#777]
Hi,

the following file crashes yanglint due to the ¢ character.

```
module m0d0 {
    prefix a0c;
    namespace ¢0000000000000000000000";

    list list0 {
		key "key1";
		unique "0n000";
		leaf key1 {
			type string;
		}

		leaf uniq0 {
			type string;
		}
    }
}
```

**Comment by michalvasko** [comment]
Hi,
I have tried it with the current YANG parser in `libyang2` branch and it worked fine, can you recheck please?

Regards,
Michal

**Comment by jvijtiuk** [comment]
Right, it doesn't crash on my machine either, after pasting from github, sorry.
The original crash file however crashes yanglint on my side, and there are some differences when diffing the files. I guess that I've removed some unprintable characters when pasting to github.

I've attached the original crash file in a zip below.
[crash.zip](https://github.com/CESNET/libyang/files/3162308/crash.zip)

**Comment by jvijtiuk** [comment]
I'm closing this issue, I've tested locally and cc6a45c fixes this .
