### ISSUE TITLE
'must' to ensure descendent node in a list?

### ISSUE THREAD

**Issue by kwatsen** [CESNET/libyang#781]
First off, I'm note 100% sure if XPath supports this (my expectation for it to work may be unwarranted)

Given the YANG:
```
module test {
  yang-version 1.1;
  namespace "https://example.net/test";
  prefix "t";
  revision "2019-05-15" {
    description
     "Initial version";
  }
  container prefs {
    leaf vendor-required {
      type empty;
      must '/devices/device/vendor';
    }
    container vendors {
      list vendor {
        key name;
        leaf name {
          type string;
        }
      }
    }
  }
  container devices {
    list device {
      key serial-number;
      leaf serial-number {
        type string;
      }
      leaf vendor {
        type leafref {
          path "/prefs/vendors/vendor/name";
        }
      }
    }
  }
} 
```

the following XML:
```
<prefs xmlns="https://example.net/test">
  <vendor-required/>
  <vendors>
    <vendor>
      <name>foobar</name>
    </vendor>
  </vendors>
</prefs>
<devices xmlns="https://example.net/test">
  <device>
    <serial-number>111</serial-number>
    <vendor>foobar</vendor>
  </device>
  <device>
    <serial-number>222</serial-number>
  </device>
</devices>
```

validates with the command:
```
yanglint --verbose --strict test.yang test.xml
```

But somehow I thought that the 'must' expression would apply to every element in the list.  So, device "222" not having a `vendor` defined would be invalid.

Thoughts?

**Comment by kwatsen** [comment]
As a workaround, changing the YANG to this works:
```
module test {
  yang-version 1.1;
  namespace "https://example.net/test";
  prefix "t";
  revision "2019-05-15" {
    description
     "Initial version";
  }
  container prefs {
    leaf vendor-required {
      type empty;
    }
    container vendors {
      list vendor {
        key name;
        leaf name {
          type string;
        }
      }
    }
  }
  container devices {
    list device {
      key serial-number;
      must 'not(/prefs/vendor-required) or (/prefs/vendor-required and vendor)';
      leaf serial-number {
        type string;
      }
      leaf vendor {
        type leafref {
          path "/prefs/vendors/vendor/name";
        }
      }
    }
  }
} 

but it's not as pretty as the first solution...

**Comment by michalvasko** [comment]
Hi Kent,
this is the way I understand it, regarding your first YANG. It is defined for the leaf `vendor-required` so it is evaluated only once. When it is, the condition requires simply that `/devices/device/vendor` is a non-empty set, so as long as there is a single instance of `device` with a `vendor`, the `must` evaluates to true.

So I believe the condition would have to be modified and I am not sure there is a pretty way of doing it. If you want a condition to hold for every `list` instance, it is most natural to place it in the `list` itself, what you did. Alternatively, you could change the `must` in `vendor-required` to something like
```
must 'count(/devices/device/vendor) = count(/devices/device)'
```
but I am not sure it is nicer than your solution. In any case, I think *libyang* behaves correctly.

Regards,
Michal

**Comment by kwatsen** [comment]
Hi Michal,

I thought that it might be something like that; it's in a grey area, for me at least...

I'd close this issue now but, first, do you think it's worth asking the NETMOD WG?

Kent

**Comment by michalvasko** [comment]
Hi Kent,
I am certain enough, so it is up to you. I even seem to remember I was fixing some issue a long time ago when this worked a bit differently and it was not correct (I think the XPath was evaluated only once even for lists).

Regards,
Michal

**Comment by kwatsen** [comment]
Closing since Michal is certain enough.
