### ISSUE TITLE
"user_date_and_time" user type plugin wrong API version warning

### ISSUE THREAD

**Issue by wlupton** [CESNET/libyang#782]
Each invocation is outputting the following warning (as far as I know I don't have any of my own plugins):
```
warn: Processing "user_date_and_time" user type plugin failed, wrong API version - 1 expected, 0 found.
```

**Comment by michalvasko** [comment]
Hi,
yes, that is the result of updating and installing *libyang* from 0.16 version to 1.0. To fix, just remove the old plugin `user_date_and_time.so` (by default in `/usr/local/lib64/libyang/user_types`).

Regards,
Michal

**Comment by wlupton** [comment]
Thanks! I found it in /usr/local/lib/libyang/user_types/user_date_and_time.dylib on my Mac.
