### ISSUE TITLE
Transforming RFC 7952 metadata on empty leaves not supported

### ISSUE THREAD

**Issue by iwanb** [CESNET/libyang#786]
Trying to transform a netconf edit tree from XML/JSON to XML/JSON with metadata on an empty leaf does not work.

From XML, e.g. this gives an internal error:
```
<interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
  <interface>
    <name>test</name>
    <description nc:operation="remove"/>
  </interface>
</interfaces>
```

Output in yanglint:
```
> data --strict -t edit -f xml sample.xml 
<interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
  <interface>
    <name>test</name>
libyang[0]: Internal error (libyang-devel-git/src/libyang/src/printer_xml.c:420).
```

And from JSON, it's not possible to have metadata without the corresponding leaf having a value, e.g. this:
```
{
  "ietf-interfaces:interfaces": {
    "interface": [
      {
        "name": "test",
        "@description": {
          "ietf-netconf:operation": "remove"
        }
      }
    ]
  }
}
```

Output in yanglint:
```
> data --strict -t edit -f xml sample.json
libyang[0]: Missing element for the specified attribute "operation".
Failed to parse data.
```

The RFC does not seem to describe that case, but not allowing it means that it's not possible to transform some trees between XML and JSON.

In this case because it's a string leaf, you could give it an empty description, then it does the right thing:
```
{
  "ietf-interfaces:interfaces": {
    "interface": [
      {
        "name": "test",
        "description": "",
        "@description": {
          "ietf-netconf:operation": "remove"
        }
      }
    ]
  }
}
```

```
> data --strict -t edit -f xml sample.json
<interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
  <interface>
    <name>test</name>
    <description nc:operation="remove"/>
  </interface>
</interfaces>
```

But if you have e.g. an integer type, it's not possible as the JSON tree will be considered invalid.

E.g. this:
```
{
    "sample:sample": {
        "integer": "",
        "@integer": {
            "ietf-netconf:operation": "remove"
        }
    }
}
```

```
> data --strict -t edit -f xml sam2.json
libyang[0]: Invalid value "" in "integer" element. (path: /sample:sample/integer)
Failed to parse data.
```

I think the first example is a bug, for the other cases it's more tricky. I am using networking equipment which does not allow a value in the leaf of a remove operation, I use libyang to transform to and from netconf XML (and do some extra validation).

Iwan

**Comment by michalvasko** [comment]
Hi Iwan,
the XML printer internal error should be fixed so it should work fine when using only XML (NETCONF). 

As for the problem in JSON, that is, indeed, tricky. Firstly, we store attributes in the corresponding elements so you cannot have attribute without an element. This is natural for XML, but not for JSON. However, this
```xml
<parent>
  <node nc:operation="delete"/>
</parent>
```
is **not** equal to
```json
"parent": {
  "@node": {
    "ietf-netconf:operation": "delete"
  }
}
```
because `node` does not exist in JSON, it does in XML. Anyway, I do not see a nice way of fixing this and since `<edit-config>` in JSON is not even standardized, you should not need it.

Regards,
Michal

**Comment by iwanb** [comment]
Thank you Michal.

Indeed there is no true equivalent, maybe using `"node": null` could be a possible equivalent but it's not allowed/defined in the RFC.

Regards,
Iwan
