### ISSUE TITLE
response: warn: Processing "user_date_and_time" user type plugin failed, wrong API version - 1 expected, 0 found

### ISSUE THREAD

**Issue by kwatsen** [CESNET/libyang#790]
This message is generated in `plugins.c` on line 158, but I'm unsure why.  Apparently, it is data-model specific, as validating other modules doesn't produce the message.  

In the module I'm validating, I converted all the `yang:date-and-time` to `string`, but it didn't help.  And there is no "user_date_and_time" in any of the imported modules (plenty of "yang:date-and-time" though).

Any clue as to what might be causing this?

**Comment by michalvasko** [comment]
Hi Kent,
sorry about that, , fix is mentioned in #782.

Regards,
Michal
