### ISSUE TITLE
edit-config: 'Unterminated string delimited with' error

### ISSUE THREAD

**Issue by lpaulic** [CESNET/libyang#798]
When trying to specify an IPv6 address as a
source for getting an image file for flashing, the  following error is generated:
```
ERROR
	type:     application
	tag:      operation-failed
	severity: error
	message:  Unterminated string delimited with ' ('http://[2003:1).
```
The configuration used is as follows:
```
<system xmlns="urn:ietf:params:xml:ns:yang:ietf-system">
 <software xmlns="http://definition/path">
   <software>
     <source>http://[2002:1b0b:fffa:ffff::4005]:32380/image.y3</source>
     <checksum>
       <type>sha-256</type>
     <value>7923ec0956f92ff3483bd24d53eef60ff8aec9d5c77ee64cde6cc8b8be2169ef</value>
     </checksum>
     <preserve-configuration>true</preserve-configuration>
   </software>
 </software>
</system>
```
The command used for applying the configuration:

1. start the netopeer2-client
2. enter the following command: `edit-config --target running --config=/tmp/config.txt`
        - the config.txt holds the above xml for editing the running datastore
3. the edit-config is executed successfully
4. enter the command: `get`
5. the above mentioned error is produces when fetching the data

```NOTE: the data supplied by the edit-config command is applied successfully but the get command fails do to parsing errors```

The environment setup where this error occurs is:
```
libyang:	libyang.so.0.16.105
sysrepo:	sysrepo.so.0.7.7
```

**Comment by mikaabra** [comment]
The relevant part of the model used:

```
        leaf source {
          type inet:uri;
          description
            "URI of the software image including username. Depending on
            the supported protocols, the following formats are possible:
              - file://path
              - http://[username@]host[:port]/path
              - https://[username@]host[:port]/path
              - ftp://[username@]host[:port]/path
              - scp://[username@]host[:port]/path";
        }
```
The configuration above is accepted, but then when issuing "get" the above mentioned unterminated string error is thrown. We're using regular ascii file format to store the configuration.

So the edit-config is successfull, the configuration is accepted and acted on, and the problem only occurs after issuing for instance "get" in netopeer2-cli connected to netopeer2.

**Comment by rkrejci** [comment]
HI, is there any relevant content in the running repository before the edit-config or does the config.txt create just a new instance of the `software` list? I mean, does that edit-config create a new or modify an existing software record?

**Comment by lpaulic** [comment]
Hi, the ```edit-config``` creates a new ```software``` record.

**Comment by mikaabra** [comment]
For me the edit-config succeeds, it's only after reboot that I get this error and it occurs after issuing "get-config" (below in netopeer2-cli running locally on the device).

```
> get-config --source=running
ERROR
	type:     application
	tag:      operation-failed
	severity: error
	message:  Unterminated string delimited with ' ('http://[2a00:8).

root@Inteno:/etc/sysrepo/data# cat ietf-system.running
<system xmlns="urn:ietf:params:xml:ns:yang:ietf-system">
  <software xmlns="http://terastrm.net/ns/yang/terastream-software">
    <software>
      <source>http://[2a00:800:abcd:abcd::1]/DIRECTORY/DIRECTORY/FILENAME</source>
      <preserve-configuration>true</preserve-configuration>
      <checksum>
        <value>171f9defc8ddfeccd0af63e6217a54aea0bfbe5d4d20423723d3fe0280f67aed</value>
        <type>sha-256</type>
      </checksum>
    </software>
  </software>
...
```

**Comment by mikaabra** [comment]
This is working as intended in:

libyang.so.0.14.53
libsysrepo.so.0.7.3

**Comment by rkrejci** [comment]
The issue was caused by a bug in Netopeer2, please update netopeer2-server to version 0.7.12.
