### ISSUE TITLE
Bug of ip-prefix in ipv4_prefix_store_clb

### ISSUE THREAD

**Issue by yangtian127** [CESNET/libyang#799]
Hi
On 64-bits system, any ipv4 prefix convert to 0.0.0.0/n
In function ipv4_prefix_store_clb, use unsigned long int type var to store ipv4 binary value

libyang-devel

**Comment by michalvasko** [comment]
Hi,
can you be more specific? `unsigned long int` is [already used](https://github.com/CESNET/libyang/blob/devel/src/user_types/user_inet_types.c#L159).

Regards,
Michal

**Comment by yangtian127** [comment]
Hi, Michal
On 64-bits system, unsigned long int is 64-bits, after call inet_pton will convert ipprefix to network order, addr_bin high 4 bytes is 0.0.0.0. so addr_bin should be type of uint32_t. 

thxs

**Comment by michalvasko** [comment]
Hi,
right, should be fixed now.

Regards,
Michal
