### ISSUE TITLE
How to load module with multiple revisions properly?

### ISSUE THREAD

**Issue by milanlenco** [CESNET/libyang#80]
I have two revisions of the same module:

test-module@2016-06-17.yang:
```
module test-module {
    prefix "tm";

    yang-version 1;

    namespace
      "urn:ietf:params:xml:ns:yang:test-module";

    description
      "test module rev.1";

    revision "2016-06-17" {
      description "Initial revision.";
    }

    leaf some-data {
        type string;
    }

}
```

test-module@2016-06-23.yang:
```
module test-module {
    prefix "tm";

    yang-version 1;

    namespace
      "urn:ietf:params:xml:ns:yang:test-module";

    description
      "test module rev.2";

    revision "2016-06-23" {
      description "Second revision.";
    }
    revision "2016-06-17" {
      description "Initial revision.";
    }

    leaf some-data {
        type string;
    }

    leaf more-data {
        type string;
    }

}
```

But when I call:
```
lys_parse_path(ly_ctx, "test-module@2016-06-17.yang", LYS_IN_YANG);
lys_parse_path(ly_ctx, "test-module@2016-06-23.yang", LYS_IN_YANG);
```

The second call fails with errors:
```
Module "test-module" in another revision already implemented.
Module "test-module" parsing failed.
```

And the latest revision is not installed:
```
(gdb) set $pos = 0
(gdb) print ly_ctx->models->list[$pos++]->name
$17 = 0x618110 "yang"
(gdb) 
$18 = 0x616470 "ietf-inet-types"
(gdb) 
$19 = 0x613380 "ietf-yang-types"
(gdb) 
$20 = 0x612510 "ietf-yang-library"
(gdb) 
$21 = 0x611660 "dep-module"
(gdb) 
Cannot access memory at address 0x8
(gdb) print ly_ctx->models->list[4]->rev_size
$22 = 1 '\001'
(gdb) print ly_ctx->models->list[4]->rev[0].date
$23 = "2016-06-17"
```

What is the proper way of loading modules with multiple revisions, or is that a bug?

**Comment by rkrejci** [comment]
By explicit loading the module, you are marking it as "implemented" module. But libyang does not allow to have multiple "implemented" revisions of the same module. On the other hand, it should be possible to have one "implemented" revision, and some other revision(s) only "imported":
```
lys_parse_path(ly_ctx, "test-module@2016-06-17.yang", LYS_IN_YANG);
lys_parse_path(ly_ctx, "test-module1@2016-06-23.yang", LYS_IN_YANG);
```
In this example the `test-module1` is allowed to import `test-module@2016-06-23.yang` so the both `test-module` revisions wil be in the context. There are some exceptions, so when the module is imported, it is marked as "implemented" when:
- it contains `augment`
- it contains `deviation`

**Comment by milanlenco** [comment]
ah, ok, thanks.

What I really need is to process each revision of each module in a directory. By "process" I mean to traverse through the schema, get list of instance-identifiers, augments, imports etc. Simply to extract some metadata for use by sysrepo. Now since I cannot load multiple revisions of the same module into the same context, it seems I will have to load each schema into a newly-created context? I'm afraid that it could be a bit costly. Would it be possible to unload a module?

**Comment by rkrejci** [comment]
Yes, that could be costly. Unfortunatelly, due to all that possible interconnections between the modules in context (augments, deviations, ...), unloading the module is not possible.
