### ISSUE TITLE
stack-buffer-underflow in LOGVAL

### ISSUE THREAD

**Issue by gcbgitbub** [CESNET/libyang#800]
Command: ./netconf_nca_ctf_run, Time: 190609-12:26:42.906
==111840==ERROR: AddressSanitizer: stack-buffer-underflow on address 0xfffb143e at pc 0xf6e3b856 bp 0xfffb0e48 sp 0xfffb0a20
READ of size 81 at 0xfffb143e thread T0
    #0 0xf6e3b855 in printf_common ../../../sanitizer_common/sanitizer_common_interceptors_format.inc:543
    #1 0xf6e3c778 in __interceptor_vasprintf ../../../sanitizer_common/sanitizer_common_interceptors.inc:1132
    #2 0xf304f2cc in log_vprintf /opt/open_source/libyang/src/log.c:192
    #3 0xf30503dc in ly_vlog /opt/open_source/libyang/src/log.c:818
    #4 0xf30bfe38 in resolve_schema_nodeid /opt/open_source/libyang/src/resolve.c:1909
    #5 0xf30e944f in lys_find_path /opt/open_source/libyang/src/tree_schema.c:4843

r = parse_schema_nodeid(id, &mod_name, &mod_name_len, &name, &nam_len, &is_relative, NULL, NULL, 1);
    if (r < 1) {
        LOGVAL(ctx, LYE_PATH_INCHAR, LY_VLOG_NONE, NULL, id[r], &id[r]);
        return -1;
    }
id[r]-------should be id[-r] ? because r is negative value
example: nodeid is /ietf-netconf-acm:/!!!!!!!!!
r's value is -18

**Comment by rkrejci** [comment]
Thanks for reporting the issue!
