### ISSUE TITLE
libyang reports validation failure in container which is disabled by if-feature 

### ISSUE THREAD

**Issue by igortern** [CESNET/libyang#810]
Hi,

edit-config request validation fails reporting validation error in container, conditional by if-feature, whereas the feature is disabled.

- libyang-1.0-r2
- sysrepo-0.7.7
The schema is bbf-xpon.yang from BBF TR-385.
The relevant fragment from bbf-xpon-channel-group-body.yang is

  grouping channel-group-config-data {
...
    container pon-pools {
      **if-feature "pon-pools";**
      list pon-pool {
        key "name";
        **min-elements 1;**
        max-elements 8;
....
Attempt to create a channel-group using configuration that does NOT contain pon-pools leaf fails

**[ERR] (dm_ly_log_cb:1617) libyang error: Too few "pon-pool" elements.**

sysrepo content is below. pon-pools feature is not enabled. The expectation is that validation for disabled container should not be performed. Could you advise and/or suggest a workaround? I prefer not to enable the feature in question.
### Module Name                | Revision   | Conformance | Data Owner          | Permissions | Submodules                    | Enabled Features
-----------------------------------------------------------------------------------------------------------------------------------------------
ietf-netconf-notifications | 2012-02-06 | Installed   | igort:igort         | 666         |                               |
ietf-netconf               | 2011-06-01 | Installed   | igort:igort         | 666         |                               | writable-running candidate rollback-on-error validate startup xpath
ietf-netconf-acm           | 2018-02-14 | Imported    |                     |             |                               |
nc-notifications           | 2008-07-14 | Installed   | igort:igort         | 666         |                               |
notifications              | 2008-07-14 | Installed   | igort:igort         | 666         |                               |
ietf-netconf-with-defaults | 2011-06-01 | Installed   |                     |             |                               |
ietf-netconf-monitoring    | 2010-10-04 | Installed   | igort:igort         | 666         |                               |
ietf-yang-library          | 2018-01-17 | Installed   | igort:igort         | 666         |                               |
ietf-datastores            | 2017-08-17 | Imported    |                     |             |                               |
ietf-interfaces            | 2014-05-08 | Installed   | igort:igort         | 666         |                               | arbitrary-names pre-provisioning if-mib
bbf-yang-types             | 2018-07-13 | Installed   |                     |             |                               |
bbf-if-type                | 2018-12-03 | Installed   |                     |             |                               |
iana-if-type               | 2017-03-30 | Imported    |                     |             |                               |
bbf-xpon-types             | 2019-02-25 | Installed   |                     |             |                               |
bbf-xpon-if-type           | 2019-02-25 | Installed   |                     |             |                               |
**bbf-xpon                   | 2019-02-25 | Installed   | igort:igort         | 666         |  bbf-xpon-base bbf-xpon-wavelength-profile-body bbf-xpon-multicast-gemport-body bbf-xpon-channel-group-body bbf-xpon-channel-partition-body bbf-xpon-channel-pair-body bbf-xpon-channel-termination-body bbf-xpon-multicast-distribution-set-body|**
ietf-x509-cert-to-name     | 2014-12-10 | Installed   |                     |             |                               |
ietf-keystore              | 2016-10-31 | Installed   | igort:igort         | 666         |                               |
ietf-netconf-server        | 2016-11-02 | Installed   | igort:igort         | 666         |                               | listen ssh-listen tls-listen call-home ssh-call-home tls-call-home
ietf-ssh-server            | 2016-11-02 | Imported    |                     |             |                               |
ietf-tls-server            | 2016-11-02 | Imported    |                     |             |                               |
ietf-system                | 2014-08-06 | Installed   | igort:igort         | 666         |                               | authentication local-users
iana-crypt-hash            | 2014-08-06 | Imported    |                     |             |                               |

Thank you,
Igor Ternovsky

**Comment by michalvasko** [comment]
Hi Igor,
what would greatly help me and should be quite simple for you is to have all the models, any relevant preset configuration, and the failing configuration snippet directly available without having to look for it/write it myself. Could you please provide it (zip it all and attach here)? Thanks.

Regards,
Michal

**Comment by igortern** [comment]
Hi Michal,
Models and edit-config netopeer2-cli script are attached.
Regards,
Igor

[sysrepo.zip](https://github.com/CESNET/libyang/files/3325204/sysrepo.zip)
[add-interfaces.txt](https://github.com/CESNET/libyang/files/3325205/add-interfaces.txt)

**Comment by michalvasko** [comment]
Hi Igor,
thanks for the files. I have tried it with them having `application_example bbf-xpon ietf-interfaces` running so that *running* configuration for these modules is editable. Then. I sent the attached `add-interfaces` as *edit-config* content and it succeeded. However, I have used most recent *libyang*, *sysrepo*, and *netopeer2-server*, so using them is my suggestion.

Regards,
Michal

**Comment by igortern** [comment]
Hi Michal,
Thank you for testing. I'm using 
- sysrepo 0.7.7
- libyang 1.0.r2
- libnetconf2 0.12.r2
- netopeer2 0.7
Everything seems to be the latest releases. When do you plan to release what is currently in development branches?

Thanks,
Igor

**Comment by michalvasko** [comment]
Hi Igor,
right, I meant I used the version from current `devel`/`master` branch, not the latest release. We are planning next release during upcoming weeks.

Regards,
Michal

**Comment by igortern** [comment]
Thanks Michal
