### ISSUE TITLE
Attempt to install model containg "action" element fails

### ISSUE THREAD

**Issue by igortern** [CESNET/libyang#812]
Hi,

Attempt to install module bbf-xponvani.yang to sysrepo database fails with error.
If block "action in-service-onu-tune-request" in bbf-xponvani-v-ani-body.yang commented out, the same operation succeeds. There is nothing obviously wrong with this block and the same module passes "compilation" with pyang.

Could you advise?

[ERR] (srctl_ly_log_cb:506) libyang: Cannot check leafref "/ietf-interfaces:interfaces/ietf-interfaces:interface/ietf-interfaces:name" if-feature consistency because of an unresolved augment.
[ERR] (srctl_ly_log_cb:506) libyang: Cannot check leafref "/ietf-interfaces:interfaces/ietf-interfaces:interface/ietf-interfaces:name" if-feature consistency because of an unresolved augment.
[ERR] (srctl_ly_log_cb:506) libyang: Cannot check leafref "/ietf-interfaces:interfaces/ietf-interfaces:interface/ietf-interfaces:name" if-feature consistency because of an unresolved augment.
[ERR] (srctl_ly_log_cb:506) libyang: Invalid keyword "action" as a child to "(sub)module".
[ERR] (srctl_ly_log_cb:506) libyang: Invalid value "v-ani-config-data" of "uses".
[ERR] (srctl_ly_log_cb:506) libyang: Copying data from grouping failed.
[ERR] (srctl_ly_log_cb:506) libyang: Submodule "bbf-xponvani-v-ani-body" parsing failed.
[ERR] (srctl_ly_log_cb:506) libyang: Including "bbf-xponvani-v-ani-body" module into "bbf-xponvani" failed.
[ERR] (srctl_ly_log_cb:506) libyang: Module "bbf-xponvani" parsing failed.

Used packages: 
- sysrepo 0.7.7
- libyang 1.0.r2

Data models are attached.

Regards,
Igor
[yang-models.zip](https://github.com/CESNET/libyang/files/3328602/yang-models.zip)

**Comment by michalvasko** [comment]
Hi Igor,
my experience is again the same, it worked just fine with the latest (unreleased) versions.

Regards,
Michal

**Comment by igortern** [comment]
Thanks again.
Regards,
Igor

**Comment by brchiu** [comment]
@igortern & @michalvasko ,

I use the latest commit of libyang : 3a9098c7b80e6b50f3d4128173aa7e02f64bec5d
I get the same error message so it might not have been solved yet !!
```
$ yanglint -p common -p equipment -p interface -p networking -p ../../../../IETF_IANA/ interface/bbf-xponvani.yang
err : Cannot check leafref "/ietf-interfaces:interfaces/ietf-interfaces:interface/ietf-interfaces:name" if-feature consistency because of an unresolved augment. (/bbf-xponvani:{augment}[/ietf-interfaces:interfaces/ietf-interfaces:interface/bbf-xponvani:v-ani])
err : Cannot check leafref "/ietf-interfaces:interfaces/ietf-interfaces:interface/ietf-interfaces:name" if-feature consistency because of an unresolved augment. (/bbf-xponvani:{augment}[/ietf-interfaces:interfaces/ietf-interfaces:interface/bbf-xponvani:v-ani])
err : Cannot check leafref "/ietf-interfaces:interfaces/ietf-interfaces:interface/ietf-interfaces:name" if-feature consistency because of an unresolved augment. (/bbf-xponvani:{augment}[/ietf-interfaces:interfaces/ietf-interfaces:interface/bbf-xponvani:v-ani])
err : Invalid keyword "action" as a child to "(sub)module". (/)
err : Invalid value "v-ani-config-data" of "uses". (/ietf-interfaces:interfaces/ietf-interfaces:interface/bbf-xponvani:v-ani/v-ani-config-data)
err : Copying data from grouping failed. (/ietf-interfaces:interfaces/ietf-interfaces:interface/bbf-xponvani:v-ani/v-ani-config-data)
err : Submodule "bbf-xponvani-v-ani-body" parsing failed.
err : Including "bbf-xponvani-v-ani-body" module into "bbf-xponvani" failed.
err : Module "bbf-xponvani" parsing failed.
```

**Comment by michalvasko** [comment]
Hi,
okay, I was able to load `bbf-xpovani` into *sysrepo* but using `yanglint` I got the error. It should work now, though.

Regards,
Michal
