### ISSUE TITLE
My application enter the following branch, could you tell me what appened?

### ISSUE THREAD

**Issue by foxge** [CESNET/libyang#814]
Hi, 

https://github.com/CESNET/libyang/blob/3defd82abbdc082b947343e9e7e78952144f39a5/src/resolve.c#L7927

In my application, I sent a large <edit-config> request with many list instance, such as
```
<container-A>
   <container-B>
     <list-C>
     ......
  </container-B>
</container-A>
```
the module looks like
```
container container-A {
   container-B {
      list list-C {
         key ...;
      }
  }
}
```

then we send <edit-config> to delete all list-C instance, but unlikely, the server returns: Too many instances of  "container-A" in "data tree". 
Could you tell me what appened ? 

Thanks.

**Comment by michalvasko** [comment]
Hi,
what exactly do you mean by "delete all list-C instance"? NETCONF does not allow this, can you tell me more about your setup, are you using *netopeer2* and *sysrepo*? How exactly are you deleting these list instances?

Regards,
Michal

**Comment by foxge** [comment]
Hi,
I do not use netopeer2 and sysrepo, but libnetconf2 and libyang in my app.
the test include more steps with more modules, and I can not find out the reason by GDB,
and so, i want to know what situation in this case. 
may you give me an example like this?

**Comment by michalvasko** [comment]
Hi,
if an example is enough, this error is caused by having an `instance-identifier` value in data that matches more than one node.

Regards,
Michal

**Comment by foxge** [comment]
OK, thanks.
