### ISSUE TITLE
Query: Is libyang supporting edit-data with url right now in latest version?

### ISSUE THREAD

**Issue by vikash7325** [CESNET/libyang#818]
I am using some old version, there only edit-data with config node is supported..but edit-data with <url> is returning null in lyd_parse_xml
I wanted to know whether it is supported in the latest version or not?

`
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="3">
  <edit-data xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-nmda"
              xmlns:ds="urn:ietf:params:xml:ns:yang:ietf-datastores">
  <datastore>ds:running</datastore>
  <url>ftp://root:root@1.1.1.1/url.cfg</url>
</edit-data>
</rpc>`

**Comment by michalvasko** [comment]
Hi,
*libyang* itself supports any YANG 1.0 or YANG 1.1 module. You are probably asking about `netopeer2-server` and the answer is no, it does not support this operation but it will soon (matter of weeks).

Regards,
Michal

**Comment by vikash7325** [comment]
OK..thanks
