### ISSUE TITLE
Incorrect uniqueness enforcement in case of list of lists

### ISSUE THREAD

**Issue by szabolcsszekely** [CESNET/libyang#820]
I am using yanglint version 1.1.30.

Yanglint incorrectly enforces uniqueness on list elements that are part of different parent list elements.

unique-error.yang to reproduce the error:
```
module unique-error {
  yang-version 1;
  namespace "http://unique";
  prefix uni;

  revision 2019-07-17 {
    description
      "Initial revision.";
  }

  container top-level-list {
      list top-level-element {
          key identifier;
          leaf identifier {
              type string;
          }
          container elements {
              list element {
                  key key-element;
                  unique unique-element;
                  leaf key-element {
                      type string;
                  }
                  leaf unique-element {
                      type string;
                  }
              }
          }
      }
  }
}
```
test-unique-error.xml to reproduce the issue:
```
<?xml version='1.0' encoding='UTF-8'?>
<config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <top-level-list xmlns="http://unique">
    <top-level-element>
      <identifier>tl1</identifier>
      <elements>
        <element>
          <key-element>e1</key-element>
          <unique-element>u1</unique-element>
        </element>
      </elements>
    </top-level-element>
    <top-level-element>
      <identifier>tl2</identifier>
      <elements>
        <element>
          <key-element>e1</key-element>
          <unique-element>u1</unique-element>
        </element>
      </elements>
    </top-level-element>
  </top-level-list>
</config>
```
The used validation command:
`yanglint -s -t auto unique-error.yang test-unique-error.xml`
This results in the following error, which is not correct:
`err : Unique data leaf(s) "unique-element" not satisfied in "/unique-error:top-level-list/top-level-element[identifier='tl1']/elements/element[key-element='e1']" and "/unique-error:top-level-list/top-level-element[identifier='tl2']/elements/element[key-element='e1']". (/unique-error:top-level-list/top-level-element[identifier='tl2']/elements/element[key-element='e1'])`

The uniqueness should be enforced only in the separate `element` lists and not across all the `element` lists.
Pyang/yang2dsdl accepts this xml as valid.
```
yang2dsdl -t config -v test-unique-error.xml unique-error.yang
== Generating RELAX NG schema './unique-error-config.rng'
Done.

== Generating Schematron schema './unique-error-config.sch'
Done.

== Generating DSRL schema './unique-error-config.dsrl'
Done.

== Validating grammar and datatypes ...
test-unique-error.xml validates

== Adding default values... done.

== Validating semantic constraints ...
No errors found.
``` 

Thanks,
Szabolcs

**Comment by michalvasko** [comment]
Hi Szabolcs,

from [RFC 7950](https://tools.ietf.org/html/rfc7950#section-7.8.3):
> MUST be unique within **all** list entry instances

You have 2 list `element` instances with the same `unique-element` value that should be unique. I think *libyang* correctly returns an error.

Regards,
Michal

**Comment by szabolcsszekely** [comment]
Hi,

But my 2 list `element` instances are not the same, they are different lists, their full data tree path is different, their XPATH is different.

ConfD also doesn't enforce uniqueness across multiple parent list elements.

Thanks,
Szabolcs

**Comment by szabolcsszekely** [comment]
Hi,

I checked the NETMOD mail archive and this question was answered there, that the intention was not to enforce global uniqueness:
https://mailarchive.ietf.org/arch/msg/netmod/vPdKHLJiAILBtqgcvXzBY5Buaxs

I only mentioned pyang and ConfD as these were implemented by the YANG authors and in my experience pyang was handled as a kind of reference implementation before.

Thanks,
Szabolcs

**Comment by michalvasko** [comment]
Hi,
fair enough, it was changed, but at least an errata could have been added to the RFC.

Reverts #612

Regards,
Michal
