### ISSUE TITLE
lys_leaf_free when free leaf, how to rm the point from leafref target sets

### ISSUE THREAD

**Issue by gcbgitbub** [CESNET/libyang#825]
A module define one leaf "name_node_A"
B module  augment A and have one leaf node"name_node_B"  leafref A module's  "name_node_A" node
when load B module deviation yin file, will delete its leaf node  "name_node_B"
will call lys_augment_free, then call lys_leaf_free
but can not find where rm leaf point from backlinks

**Comment by michalvasko** [comment]
Hi,
it is possible the backlinks do not get deleted, so please provide the models so I can check and fix it.

Regards,
Michal
