### ISSUE TITLE
yanglint and regex anchors

### ISSUE THREAD

**Issue by Mokon** [CESNET/libyang#828]
I'm running into an issue and I am trying to understand if it is a problem in yanglint or in the model I am using. Consider the following example model:
```
module example {
    yang-version 1.1;
    namespace "urn:ietf:params:xml:ns:yang:example";
    prefix ex;

    leaf mac {
        type string {
            pattern '^[0-9a-fA-F]{2}(:[0-9a-fA-F]{2}){5}$';
        }
    }
}
```

I then have this json file:
```
{
   "example:mac" : "00:11:22:33:44:55"
}
```

I run lint `yanglint example.yang example.json` and I get the following error
`err : Value "00:11:22:33:44:55" does not satisfy the constraint "^[0-9a-fA-F]{2}(:[0-9a-fA-F]{2}){5}$" (range, length, or pattern). (/example:mac)`

If I remove the start and end anchors in the regex this passes `pattern '[0-9a-fA-F]{2}(:[0-9a-fA-F]{2}){5}';`

This likewise fails with a simplier pattern:
`err : Value "00:11:22:33:44:55" does not satisfy the constraint "^.*$" (range, length, or pattern). (/example:mac)`

I believe this is a problem in yanglint as those anchors should match at the start and end of the string but I am not 100% sure if those shouldn't be used in the regex of the yang model.

**Comment by michalvasko** [comment]
Hi,
yet again, look into #422.

Regards,
Michal
