### ISSUE TITLE
whether LIBYANG_EXTENSIONS_PLUGINS_DIR is not set?

### ISSUE THREAD

**Issue by foxge** [CESNET/libyang#831]
Hi
I do not use any yang plugins, can I not config the LIBYANG_EXTENSIONS_PLUGINS_DIR  env var?

Thanks.

**Comment by Alanscut** [comment]
I do not configure LIBYANG_EXTENSIONS_PLUGINS_DIR here, libyang can be compiled and used normally.
 If you do not configure this parameter, will you report an error?

**Comment by foxge** [comment]
Hi,
```
Invalid keyword "type" as a child to "annotation". in libyang-0.15-r1/src/resolve.c(7396)
 "yang" parsing failed. in libyang-0.15-r1/src/parser_yin.c(7391)
```

error messages above.

**Comment by michalvasko** [comment]
Hi,
no, extensions directory must always be set/found because there are internal extensions that are always used.

Regards,
Michal

**Comment by dota17** [comment]
I find the ENV variable in function `ly_load_plugins()` in file `src/plugins.c` :
```
    pluginsdir = getenv("LIBYANG_EXTENSIONS_PLUGINS_DIR");
    if (!pluginsdir) {
        pluginsdir = LYEXT_PLUGINS_DIR;
    }
```
So, if env variable `LIBYANG_EXTENSIONS_PLUGINS_DIR` is not set, it will use the default dir value. And it won't report error.

**Comment by foxge** [comment]
Thanks, I would try.
