### ISSUE TITLE
JSON empty type encoding issue

### ISSUE THREAD

**Issue by kwatsen** [CESNET/libyang#840]
I have a YANG module with a `leaf` of type `empty`:

```
module: ietf-http-server
  +--rw http-server
     +--rw client-authentication!
        +--rw (required-or-optional)
           +--:(required)
              +--rw required?                        empty
```

When validating instance documents (e.g., `yanglint -m -s ietf-http-server.yang ex-http-server.json`), everything is okay if the `required` leaf is encoded as:

```
    "required": [null]
```

That is, with no whitespace between the `[`, `null`, and `]`.  However, there is an error if whitespace is introduced:

```
    "required": [  null  ]

$ yanglint -m -s ietf-http-server.yang ex-http-server.json
err : Invalid JSON data (unexpected value). (/ietf-http-server:http-server/client-authentication/required)
```

I want to impress upon you that JSON is not whitespace sensitive.  For instance, using Python on the example from https://tools.ietf.org/html/rfc7951#section-6.9:

```
$ python
Python 3.7.2 (default, Jun  2 2019, 16:42:40) 
>>> import json
>>> str = '{ "foo": [null] }'
>>> obj = json.loads(str)
>>> print(json.dumps(obj))
{"foo": [null]}
>>> print(json.dumps(obj, indent=4))
{
    "foo": [
        null
    ]
}
```

All I've done above is to ask Python to "pretty print" the JSON document.  Notice how it added whitespace...

Technically, RFC 7951 encodes empty types as an list containing the value "null".  It's a bit odd, and the text in the document doesn't help explain the oddity:

```
   This encoding of the "empty" type was chosen instead of using simply
   "null" in order to facilitate the use of empty leafs in common
   programming languages where the "null" value of a member is treated
   as if the member is not present.
```

But I'm sure JSON is not whitespace sensitive, which is are that matters to understand this issue.

**Comment by rkrejci** [comment]
You are right, it should be fixed in 1.1.39. Thanks fro reporting!
