### ISSUE TITLE
Does libyang have any plan to support golang in the swig?

### ISSUE THREAD

**Issue by open520** [CESNET/libyang#843]
I find that there are C++/Java/Python/Javascript support in libyang.  Yes, the four languages is very popular. It's very wise to do this.

But now, golang is also very popular.  I wonder that whether libyang will support golang in the future?

**Comment by michalvasko** [comment]
Hi,
we are sorry, but we do not have the capacity to write such bindings. If, however, someone else added the support for it, we would be happy to merge it into *libyang* repository.

Regards,
Michal

**Comment by open520** [comment]
OK， I will try it ^_^
