### ISSUE TITLE
yanglint's parameter --type=auto doesn't work

### ISSUE THREAD

**Issue by open520** [CESNET/libyang#844]
Hello, when I try to use tool `yanglint`, I found that the parameter --type=auto doesn't work for me in the following case.
```
./yanglint --format=json --type=auto ./module1.yang ./a.xml
```

**the output is:**
```
yanglint error: invalid top-level element "module1" for data type autodetection.
```

**The content of `a.xml` is :**

```
<module1 xmlns="urn:yanglint:module">
  <m>123456</m>
</module1>
<module2 xmlns="urn:yanglint:module">
  <m1>1235544896</m1>
</module2>
```

**the content of `module1.yang` is :**
```
module module1 {
  namespace "urn:yanglint:module";
  prefix m;
  container module1 {
          leaf m { type string; }
  }
  container module2 {
          leaf m1 { type string; }
  }
}
```

I try to read the help message but not get solved. Can you give me some tips?

**Comment by michalvasko** [comment]
Hi,
if you read help, it is written there that this works just like it does for `pyang`. Specifically, you can enclose the whole data in `<config>` or `<data>`, but it is best to not use auto and rather specify `--type config` or `--type data` manually, the former being the right one for 90% of use-cases.

Regards,
Michal
