### ISSUE TITLE
There are no test_jsontoxml testcases in the test_value.c

### ISSUE THREAD

**Issue by dota17** [CESNET/libyang#846]
I find that there are no jsontoxml testcases in the test_value.c file. Are there any plans to add some cases? If needed, I'm pleased to do the job.

**Comment by rkrejci** [comment]
Please do. From our point of view, JSON is just additional encoding without a clear definition of several things (such as. RPC/Notification encoding) and we don't use it regularly. But any contribution is welcomed.
