### ISSUE TITLE
may  libyang provide a hook for GBK encoding?

### ISSUE THREAD

**Issue by foxge** [CESNET/libyang#847]
Hi
We have to accept sessions with GBK encoding from some devices for special reason, but I know the NETCONF protocol only permits UTF-8. Can it provide a hook such as pututf8, copyutf8 to caller to import other encoding ?

I try to construct a shell to translate but be afraid of reducing performance.

Thanks.

**Comment by rkrejci** [comment]
Not only the NETCONF protocol, but YANG is strictly UTF-8. I don't think that it is a good idea to hook the encoding. Internally, the data are supposed to be stored/handled as UTF-8 anyway (for compatibility reasons). So, in the hooks you would have to do the translation from GBK to UTF-8 anyway. I believe that there can be a (C, not shell) wrapper around libyang functions which can do the same - translate input data from GBK to UTF-8 and pass them then to libyang, so the performance shouldn't be worse than havink a hook in libyang. What do you think?
