### ISSUE TITLE
ly_ctx_new failed

### ISSUE THREAD

**Issue by hubenchang0515** [CESNET/libyang#849]
The function **ly_ctx_new** failed and return `NULL`.
It seems to happened while parsing internal module `{"yang", "2017-02-20", (const char*)yang_2017_02_20_yin, 1, LYS_IN_YIN},`.

The code : 
```C
#include <libyang/libyang.h>
#include <stdio.h>

int main(int argc, char* argv[])
{
	struct ly_ctx* ctx = ly_ctx_new(NULL, 0);
	if(ctx == NULL)
	{
		printf("ly_ctx_new reutrn NULL\n");
	}
}
```

The running result
```
libyang[0]: Invalid keyword "type" as a child to "annotation". (path: /)
libyang[0]: Module "yang" parsing failed.
ly_ctx_new reutrn NULL
```

**Comment by fredgan** [comment]
I tried your example in my Ubuntu 16.04 LTS, but I can't reproduce it.

What's your runing environment? 

And Have you modify the files in ${ROOT}/models before you make install?

**Comment by hubenchang0515** [comment]
I run it at Windows with msys2 
I commented `{"yang", "2017-02-20", (const char*)yang_2017_02_20_yin, 1, LYS_IN_YIN},` out to avoid it

**Comment by hubenchang0515** [comment]
This problem is very metaphysical. 
Text parsing is unlikely be influented by OS，and I had never changed `models` and try `git reset --hard` many times.

**Comment by rkrejci** [comment]
Hi, please uncomment back that line and see the [FAQ](https://github.com/CESNET/libyang/blob/master/FAQ.md) document. The issue is cause by having troubles to find plugins.
