### ISSUE TITLE
about  variable(bits) define in tree_schema.h (line 367 master branch),moved to c file from h file?thanks

### ISSUE THREAD

**Issue by ZhaoGuangYue** [CESNET/libyang#85]
hi 
we found there is variable(bits) define in **tree_schema.h** (line 367 master branch). I wonder if this variable can be moved to c file from h file?
thanks

_/**
 * @brief Container for information about bits types (#LY_TYPE_BINARY), used in ::lys_type_info.
 */
struct lys_type_info_bits {
    struct lys_type_bit *bit;/**< array of bit definitions */
    int count;               /**< number of bit definitions in the bit array */
} **bits;**_

**Comment by michalvasko** [comment]
Hi,
this variable was just leftover junk from previous reorganization of that union definition so I removed it. Nice find, thanks.

Regards,
Michal
