### ISSUE TITLE
libyang does not preserve new line character in JSON encoded string data

### ISSUE THREAD

**Issue by ygorelik** [CESNET/libyang#850]
When JSON encoded string includes data nodes, which string values contain new line characters '\n', the libyang gets confused and instead of preserving these characters, it inserts some trash value UTF-16 characters.

My JSON encoded string:
```
(ydk81) yan@ubuntu-yan:~$ cat banner.json 
{
	"Cisco-IOS-XR-infra-infra-cfg:banners": {
		"banner": [{
			"banner-name": "motd",
			"banner-text": ";\n------------------------------------------\n  Programmability Testbed\n  Santiago Alvarez - saalvare@cisco.com\n------------------------------------------\n;"
		}]
	}
}(ydk81) yan@ubuntu-yan:~$ 
```

Applying this data in yanglint:
```
(ydk81) yan@ubuntu-yan:~/ydk-workspace/ydk-gen/sdk/cpp/core/build/project_libyang/src/project_libyang-build$ ./yanglint 
> searchpath /home/yan/ydk-workspace/ydk-gen/scripts/repository/10.30.110.84
> add /home/yan/ydk-workspace/ydk-gen/scripts/repository/10.30.110.84/Cisco-IOS-XR-infra-infra-cfg.yang
> data -f json -o /home/yan/o.json /home/yan/banner.json 
```
Resulting output contains some UTF-16 characters, which are not related to 'new line' characters:
```
(ydk81) yan@ubuntu-yan:~$ cat o.json
{
  "Cisco-IOS-XR-infra-infra-cfg:banners": {
    "banner": [
      {
        "banner-name": "motd",
        "banner-text": ";\u0001------------------------------------------\u002C  Programmability Testbed\u0046  Santiago Alvarez - saalvare@cisco.com\u006E------------------------------------------\u0099;"
      }
    ]
  }
```
There are no issues when string is XML encoded.

**Comment by rkrejci** [comment]
Hi, I;m not able to find the banner definition in the referenced module (probably different version). Anyway, I just tried that with a simple string type in `yanglint 1.1.39` and I'm getting this:
```
{
  "test:t": ";\u000A------------------------------------------\u000A  Programmability Testbed\u000A  Santiago Alvarez - saalvare@cisco.com\u000A------------------------------------------\u000A;"
}
```
which seems fine (btw, it is supposed to be UTF-8, not UTF-16). Which version of yanglint are you using?

**Comment by fredgan** [comment]
I tried your example, made the yang model, and used your banner.json data, following is the result:
```
SZX1000520372:~/download$ ./libyang-master/build/yanglint -f json -t config ./cisco.yang ./cisco.json
{
  "Cisco-IOS-XR-infra-infra-cfg:banners": {
    "banner": [
      {
        "banner-name": "motd",
        "banner-text": ";\u000A------------------------------------------\u000A  Programmability Testbed\u000A  Santiago Alvarez - saalvare@cisco.com\u000A------------------------------------------\u000A;"
      }
    ]
  }
}
```

**Comment by rkrejci** [comment]
Maybe try to upload the real json file, not just its content, to let me to analyse the problem better.

**Comment by ygorelik** [comment]
I have repeated the same command line in my installation of latest master branch of libyang and still getting the same bad result!?

(ydk81) yan@ubuntu-yan:~/ydk-workspace/libyang$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
(ydk81) yan@ubuntu-yan:~/ydk-workspace/libyang$ git fetch
(ydk81) yan@ubuntu-yan:~/ydk-workspace/libyang$ git pull
Already up-to-date.
(ydk81) yan@ubuntu-yan:~/ydk-workspace/libyang$ cd build/
(ydk81) yan@ubuntu-yan:~/ydk-workspace/libyang/build$ make
[ 61%] Built target yang_static
[ 65%] Built target yangre
[ 81%] Built target yanglint
[ 86%] Built target yang2yin
[ 90%] Built target nacm
[ 95%] Built target metadata
[100%] Built target libyang_ext_test
(ydk81) yan@ubuntu-yan:~/ydk-workspace/libyang/build$ sudo make install
[sudo] password for yan:
[ 61%] Built target yang_static
[ 65%] Built target yangre
[ 81%] Built target yanglint
[ 86%] Built target yang2yin
[ 90%] Built target nacm
[ 95%] Built target metadata
[100%] Built target libyang_ext_test
Install the project...
-- Install configuration: "Debug"
-- Installing: /usr/local/lib/libyang.a
-- Installing: /usr/local/include/libyang/tree_schema.h
-- Installing: /usr/local/include/libyang/tree_data.h
-- Installing: /usr/local/include/libyang/extensions.h
-- Installing: /usr/local/include/libyang/xml.h
-- Installing: /usr/local/include/libyang/dict.h
-- Installing: /usr/local/include/libyang/libyang.h
-- Installing: /usr/local/lib/pkgconfig/libyang.pc
-- Installing: /usr/local/bin/yanglint
-- Up-to-date: /usr/local/share/man/man1/yanglint.1
-- Installing: /usr/local/bin/yangre
-- Installing: /usr/local/lib/libyang/nacm.so
-- Installing: /usr/local/lib/libyang/metadata.so
(ydk81) yan@ubuntu-yan:~/ydk-workspace/libyang/build$ ./yanglint -f json -t config ../../ydk-gen/scripts/repository/10.30.110.84/Cisco-IOS-XR-infra-infra-cfg.yang ../../../banner.json
{
  "Cisco-IOS-XR-infra-infra-cfg:banners": {
    "banner": [
      {
        "banner-name": "motd",
        "banner-text": ";\u0001------------------------------------------\u002C  Programmability Testbed\u0046  Santiago Alvarez - saalvare@cisco.com\u006E------------------------------------------\u0099;"
      }
    ]
  }
}
ydk81) yan@ubuntu-yan:~/ydk-workspace/libyang$ cat ~/banner.json
{
      "Cisco-IOS-XR-infra-infra-cfg:banners": {
            "banner": [{
                  "banner-name": "motd",
                  "banner-text": ";\n------------------------------------------\n  Programmability Testbed\n  Santiago Alvarez - saalvare@cisco.com\n------------------------------------------\n;"
            }]
      }
}

Why is it working in your environment and not in mine? Is your code based on different libyang branch?

Thanks and regards,
Yan

**Comment by rkrejci** [comment]
Please, upload the banner.json file itself. The control characters can be invisible when printing or something else can be in the file hidden. Also your Cisco-IOS-XR-infra-infra-cfg schema could be helpful (just for sure, I don't know how the type could affect this, but what if). Also please share the version of Ubuntu, is it 64b or 32b? Again - no specific idea what could be a reason, I'm just trying to gather information to reproduce the issue.

**Comment by ygorelik** [comment]
I am running libyang based application on Ubuntu 16.04 LT 64bit.
Attached requested files.

[banner.json.txt](https://github.com/CESNET/libyang/files/3535339/banner.json.txt)
[Cisco-IOS-XR-infra-infra-cfg.yang.txt](https://github.com/CESNET/libyang/files/3535340/Cisco-IOS-XR-infra-infra-cfg.yang.txt)

**Comment by ygorelik** [comment]
The issue appears only in my fork, which is very 6-8 months behind the master. Hence closing the issue.
