### ISSUE TITLE
Unable to strictly validate get-config data

### ISSUE THREAD

**Issue by amandeepsethi** [CESNET/libyang#851]
Hi,

I am currently working on a scenario where on getting Netconf get-config request, fetching data from backend applications and then validating the same to be YANG compliant. I found that the data is parsed successfully without reporting any error irrespective of the strict flag is in use. Using the latest libyang code (version:1.0.46). The command used is as follows:

`result = lyd_parse_mem(ly_ctx, data, LYD_XML, LYD_OPT_GETCONFIG | LYD_OPT_STRICT);`

I observed that if the LYD_OPT_EDIT option is passed then the error is reported. Can't we pass the `LYD_OPT_GET/LYD_OPT_GETCONFIG` option to validate the data when preparing response for get/get-config request? And, if we can only validate using `LYD_OPT_EDIT` flag then how can we validate the get request data as that might contain non-configurational data (where element has config false set) as it will be reported as an error while parsing.

Attached is the snippet of code, I am using and validating the data against.

[Code.zip](https://github.com/CESNET/libyang/files/3529163/Code.zip)

**Comment by rkrejci** [comment]
I'm actually not sure about your question. As described in the documentation:
- `LYD_OPT_GET` - Data content from a NETCONF reply message to the NETCONF <get> operation
- `LYD_OPT_GETCONFIG` - Data content from a NETCONF reply message to the NETCONF <get-config> operation

In both cases, list's keys (as `id` in your code snippet) can be omitted. In contrast to:
- `LYD_OPT_EDIT` - Content of the NETCONF <edit-config>'s config element

where the list's key is required. So, what is wrong? Or what do you expect?

**Comment by amandeepsethi** [comment]
Hi Radek,

The key is a mandatory part of the list, a response having list without keys is an incomplete data.

As per RFC 6020,
```
7.8.2.  The list's key Statement
   The "key" statement, which MUST be present if the list represents configuration, and MAY be present otherwise, takes as an argument a string that specifies a space-separated list of leaf identifiers of this list.  A leaf identifier MUST NOT appear more than once in the key.  Each such leaf identifier MUST refer to a child leaf of the list.  The leafs can be defined directly in substatements to the list, or in groupings used in the list.
```

I think get/get-config response should be validated accordingly and not omitting the list's keys.

In my scenario, the user is fetching the get-config response and then replaying this configuration back to the system which fails in edit-config request due to strict checking (LYD_OPT_EDIT | LYD_OPT_STRICT). Can you please provide a workaround/fix for this.

**Comment by rkrejci** [comment]
That's not true due to filters. Using xpath or subtree filters, you can actually remove list's keys from the data returned by `get-config` or `get`. That's why they are not checked in this mode and that's actually a reason to have such a mode.
If you expect complete datastore to be the result of the `get-config` request, validate the received data as `LYD_OPT_CONFIG`.

**Comment by amandeepsethi** [comment]
Hi Radek,

Is there any parser option or a combination of options that can be used in `lyd_parse_mem` API to ignore the errors encountered in parsing get/get-config response data so that the server is able to successfully send response to Netconf client?

For example: If there is an unknown element present in the data whose Yang is not loaded in the libyang context or if the value of the leaf in the data, not adhering to the its type defined in Yang model.

**Comment by amandeepsethi** [comment]
Hi,

Can you please respond to above raised query.

**Comment by michalvasko** [comment]
Hi,
I am not sure what exactly are you asking, if there is an unknown element it is skipped **by default** in *libyang*. You can also try to use `LYD_OPT_TRUSTED`.

Regards,
Michal

**Comment by amandeepsethi** [comment]
Thanks Michal for the response. Yes, I am using the same parsing option.

The issue is that when we fetch XML format data from backend apps and try to parse using the `lyd_parse_mem` API then failure is reported, resulting in lyd_node pointer having NULL value due to which, we are unable to send data to Netconf client and instead rpc-error response is sent.
So my query is there any parsing option available that can be used to prevent such failures and still send the data to client.

Following are the scenarios where error is observed:
1. If data is not matching the type of the element defined in Yang model. For example, if an element is of `int32` type and the data contains a string value for the same element. 
2. In Yang model, if an element is of type identityref and data contains the value defined in another Yang file which is not loaded in the libyang context.

For example: YANG model is following:
```
module model {
namespace "urn:test:params:xml:ns:yang:model";
prefix model;

  container con {
    leaf id {
      type uint32;
    }
  }
}
```
Case 1: Data is:
```
<con xmlns="urn:test:params:xml:ns:yang:model">
    <id>1</id>
    <haha>abc</haha>
</con>
```
Yes, in this case the unknown leaf <haha> is skipped by using TRUSTED flag.

Case 2: Data is:
```
<con xmlns="urn:test:params:xml:ns:yang:model">
    <id>abc</id>
</con>
```
In this case, <id> has invalid value of abc. In this case I would like this leaf to be skipped as well, i.e. the final XML would be something like `<con xmlns="urn:test:params:xml:ns:yang:model" />`

**Comment by michalvasko** [comment]
Hi,
in the first case, `haha` element is not skipped because of using `LYD_OPT_TRUSTED` but because of **not** using `LYD_OPT_STRICT`. Regarding the second case, this simply is not supported and I do not see much point in supporting it.

Regards,
Michal
