### ISSUE TITLE
augmenting 'if-feature' statements in 'notification' statements

### ISSUE THREAD

**Issue by kwatsen** [CESNET/libyang#854]
[RFC 7950, Section 7.16.1](https://tools.ietf.org/html/rfc7950#section-7.16.1) shows that `notification` statements may have `if-feature` statements.  And [RFC 7950, Section 7.17.1](https://tools.ietf.org/html/rfc7950#section-7.17.1) shows that `notification` statements may be augmented.  Thus it should be possible to augment an `if-feature` statement into a `notification` statement.

Using this module:
```
module test {
  yang-version 1.1;
  namespace "https://example.net/test";
  prefix "t";

  feature f;

  notification n1;
  notification n2 {
    if-feature f;
  }

  grouping g {
    notification n3;
    notification n4 {
      if-feature f;
    }
  }

  container c1 {
    uses g;
  }

  container c2 {
    uses g {
      augment n3 {
        if-feature f;
      }
    }
  }
}
```

One gets:  (note that `c2/n3` does NOT show `{f}?`)

```
$ yanglint -f tree --tree-print-groupings test.yang

module: test
  +--rw c1
  |  +---n n3
  |  +---n n4 {f}?
  +--rw c2
     +---n n3
     +---n n4 {f}?

  notifications:
    +---n n1
    +---n n2 {f}?

  grouping g:
    +---n n3
    +---n n4 {f}?
```

and:  (note that `c2/n3` continues to appear)

```
$ yanglint --features=test: -f tree --tree-print-groupings test.yang

module: test
  +--rw c1
  |  +---n n3
  +--rw c2
     +---n n3

  notifications:
    +---n n1

  grouping g:
    +---n n3
```

**Comment by fredgan** [comment]
I think you misunderstand the meaning of augment.

augment statement means that you can add some new nodes into the target node.
for example:
```
<user>
       <name>jerryr</name>
       <full-name>Jerry K. Roma</full-name>
       <class>wheel</class>
     </user>
```

if you write an augment statement as follow,
```
augment user {
         leaf uid {
             type uint16 {
                 range "1000 .. 30000";
             }
         }
     }
```
then, you will get `user` node as follow
```
<user>
       <name>alicew</name>
       <full-name>Alice N. Wonderland</full-name>
       <class>drop-out</class>
       <other:uid>1024</other:uid>
</user>
```
`if-feature` for the augment just determins add the nodes(`uid` in this case) in the augment statement or not. Not determins the node(`user` in this case) exist or not.

In your case, you have no nodes in your augment statement, so your if-feature in your augment is useless.

**Comment by kwatsen** [comment]
RFC 7950 Section 7.17 is unclear, it neither says that it isn't possible nor asserts that augments must contain specific nodes.  

That said, the ABNF in Section 14, under `uses-augment-stmt` includes `1*(data-def-stmt / case-stmt / action-stmt / notification-stmt)`, for which I'll close this issue.
