### ISSUE TITLE
libyang2: YANG extensions support

### ISSUE THREAD

**Issue by rkrejci** [CESNET/libyang#857]
Prepare a plugin mechanism to process YANG extension instances. In general, libyang2's support of the YANG extension is supposed to be somewhat more simple from the library point of view than originally - more work and responsibility is expected from the extension plugins and being hidden from libyang itself (until the support is integrated into libyang itself, e.g. in case of annotations). The plugins are supposed at least to
* validate correct use of the instance in a YANG schema (compile extension instance from the parsed representation into the compiled schema representation)
* validate instance data if the data follows the extensions definition

In the first phase, API and the selcted extensions ([NACM](https://tools.ietf.org/html/rfc8341), [Annotations](https://tools.ietf.org/html/rfc7952)) will be implemented. In contrast to libyang 1, these internal plugins will not be available as a standalone dynamically linkable files, but they will be integral part of the library itself to simplify installation. In the second phase, the plugin's API will be made public and a mechanism to dynamically load third-party plugins will be implemented.

**Comment by rkrejci** [comment]
NACM and Annotations are implemented - still some more testing is needed, but they are prepared.

It will be needed to implement support for parsing all the possible extension instance's substatements - currently only the set required for annotation is done.

**Comment by fredgan** [comment]
@rkrejci Hi Radek,  I have encounted a question when I am writing the part of `printer_yin` about this.
I don't know how to print the extension instance's substatements in YIN format. 
I try to use the yanglint of master branch, but the substatements are ignored in the result.
So can you give me some tips or reference?  Or I just leave this part `TODO` right now then modify them later? Thanks very much!

**Comment by rkrejci** [comment]
It differs from libyang 1.0 since now we have parsed and compiled schema structures. The YIN printer should print the parsed structure so all the substatements are stored generically as `struct lysp_stmt` and it should be quite simple to print it. 

You can see into YANG printer (in libyang2), but note that there is an issue with having enough information about the argument in case the source is from different format than printing (YANG printer need the compiled schema in case the source was YIN and probably similar problem will be with printing YIN in case the schema was parsed from YANG). The problem for YIN is probably the thing that without the extension specification (which is found by the compilation process in libyang), you do not know the argument's name and if it is defined with `yin-element` so you don't have enough information to print. So you can do the same as YANG printer - check for the presence of the compiled tree. If it is not present just print the extension name with a comment about missing additional information to print the substatements and skip it. If the compiled tree is present, you can use it to get information about the extension to print the extension instance correctly.

**Comment by rkrejci** [comment]
The rest of the work was splitted into the following issues:
#1333 - statements parser
#1334 - yang-data extension
#1336 - cleanup of the extensions API
#1332 - cleanup of the type API
#1335 - loading external plugins
