### ISSUE TITLE
Retrieving all nodes: ly_ctx_get_node() vs. lyd_get_node()

### ISSUE THREAD

**Issue by milanlenco** [CESNET/libyang#86]
Some time ago we were discussing that in order to get all the nodes of a module, the xpath `/test-module:*//.` should be used rather than `/test-module:*//*`.
But after we replaced `*` with `.` in our test applications, we started to observe the following error:
`libyang: Unexpected character(s) '*' (*//.).`
It turned out that while lyd_get_node() processes this xpath just fine, ly_ctx_get_node() returns this error. Is there a difference between these two functions related to the input xpath that we should be aware of?

Thanks,
Milan

**Comment by michalvasko** [comment]
Hi Milan,
if you read the function documentation carefully, you will notice that `ly_ctx_get_node()` accepts "schema node identifier in JSON format", while `ld_get_node()` an "XPath expression". The difference is explained in more detail in the general documentation, which is available if you execute `make doc`. Look into the HTML documentation **libyang/How To.../XPath Addressing**. Very briefly, the reason for the difference is that `ly_ctx_get_node()` is evaluated on schema.

Regards,
Michal
