### ISSUE TITLE
libyang: Validation takes significant time when 'must' expression is present in schema

### ISSUE THREAD

**Issue by dutta-partha** [CESNET/libyang#865]
Hello Radek/Michal, 

We are using libyang for configuration validation in SONiC (https://github.com/Azure/SONiC/). We found that the time it takes for validating large data (2.1 MB file with 1000 ACL list instances and 8000 ACL rule list instances) is significantly high, around 278 sec. After profiling using perf we found that it takes 78% of time itself in 'must' expression evaluation. If we remove the must expression from the schema, then it takes 38 sec. We need to validate even bigger data (4K  VLAN related data etc.) in seconds only where multiple must expressions should be evaluated. 

Could please tell me if evaluating Xpath generally takes high time or has it any limitation in terms of performance.

Please refer to the attached profile data, schema and C code.
[libyang profile.zip](https://github.com/CESNET/libyang/files/3567536/libyang.profile.zip)

Any help in this regard is highly appreciated.

Regards,
Partha.

**Comment by michalvasko** [comment]
Hi Partha,
there is not much more you can do with generic XPath evaluations. They will always be slow and scale badly especially for expressions on `list`s that require all other list instances (O(n^2)).

Nevertheless, it would be possible to allow custom callbacks to be set for every `must` expression that would handle its validation. That way it could be much more efficient. Would this work for you?

Regards,
Michal

**Comment by dutta-partha** [comment]
Hi Michal,

Thank you for your response.

Yes, we are facing scalability issue due to (O(n^2)) complexity. All our must expressions will involve multiple 'list's  where thousands of list instances will be there.

We can't have custom validation code for every 'must' expression. Validation code should be common generic code.

I see that current XPath engine first selects all nodes in a set and then try to apply predicate, if it does not match, it deletes the node from set. Out of 1000  entries it may match with only one list instance (assuming one key is there in list, rest 999 entries are just discarded). Is it possible to only add the instance matching the predicate criteria in set and then perform required operation (like count() etc.). I understand that current algorithm is generic though.

Another observation is that we parse the must expression every time it is executed. Can we keep the expression parsed say compiled expression and then evaluate with different list instance ?

Are we planning to add any optimization in XPath engine in "libyang2" apart from adopting to new data structure ?

Regards,
Partha

**Comment by michalvasko** [comment]
Hi Partha,
what you suggested regarding predicate evaluation is probably possible but I am not sure it would save much time (you would only save adding and discarding those instances - memory operations).

In the new *libyang* the expression is already parsed only once but other than that there will be no optimizations.

Just a note, you have used *libyang* `Release` build mode for your measurements, right? There are some quite expensive checks performed in XPath that are skipped if not build in `Debug`.

Regards,
Michal

**Comment by dutta-partha** [comment]
Hi Michal,

Yes, we wanted avoid mainly sorting and check the performance by using Release mode. BTW, those checks are skipped in RelWithDebInfo as well ?

In our performance report, we observed that set_remove_node() took around 40% of time to perform only memmove(). So we were thinking if can we optimize by adding only the required nodes needed in the set.

So in new libyang, are we going to keep the parsed expression in any special data structure ?
Are we building sort of xpath expression tree ?

Regards,
Partha

**Comment by michalvasko** [comment]
Hi Partha,

> Yes, we wanted to avoid mainly sorting and check the performance by using Release mode. BTW, those checks are skipped in RelWithDebInfo as well ?

I believe so (as long as `NDEBUG` is defined).

> In our performance report, we observed that set_remove_node() took around 40% of time to perform only memmove(). So we were thinking if can we optimize by adding only the required nodes needed in the set.

Fair enough, I can take a look at this once I finish what I am currently doing.

> So in new libyang, are we going to keep the parsed expression in any special data structure ?
Are we building sort of xpath expression tree ?

Not really, the exact same structure is used as in the current *libyang*, it is just stored in the schema and not created for every evaluation.

Regards,
Michal

**Comment by dutta-partha** [comment]
Thanks Michal.

**Comment by michalvasko** [comment]
Hi Partha,
it turns out that it would be quite difficult to implement exactly what you suggested, in the current *libyang*. I will try to do it in the new *libyang*. However, I have optimized removing the nodes that do not satisfy a predicate and in my use-case (similar to yours) all the time taken by removing the nodes previously has disappeared, so there seems to be no need to optimize that more.

Regards,
Michal
