### ISSUE TITLE
libyang[0]: Internal error (/opt/libyang/src/plugins.c:632)

### ISSUE THREAD

**Issue by vladique00** [CESNET/libyang#868]
Hi,
We are trying to load the config using **ietf-inet-types:ipv6-address** in our model which is present in user_inet_types.c, but we get an error **libyang[0]: Internal error (/opt/libyang/src/plugins.c:632)**. So far this does not lead to any problems.
We don`t get this error if we redefine type ipv6-address in our own model.

We also use **ietf-yang-types:mac-address** which is present in user_yang_types.c, but we don’t see such a problem.

Checked in version 1.0.48

**Comment by michalvasko** [comment]
Hi,
could you maybe provide the exact steps how to reproduce this error? It would make fixing it much easier, thanks.

Regards,
Michal

**Comment by michalvasko** [comment]
Hi,
thanks for providing the test files, the error should no longer be displayed.

Regards,
Michal

**Comment by vladique00** [comment]
Now we get an error **libyang[0]: Invalid value "" in "fake-leaf" element. (path: /itmh-cpe-firewall:fake-leaf) Segmentation fault** using swig python bindings.

```
ccnf =  ctx.parse_data_mem(first, ly.LYD_JSON, ly.LYD_OPT_CONFIG)
ucnf =  ctx.parse_data_mem(second, ly.LYD_JSON, ly.LYD_OPT_CONFIG)
ccnf.merge(ucnf, ly.LYD_OPT_EXPLICIT)
ccnf.print_mem(ly.LYD_JSON, ly.LYD_OPT_CONFIG)
```

**Comment by michalvasko** [comment]
Hi,
okay, please try again.

Regards,
Michal

**Comment by vladique00** [comment]
Yes, All right. Thanks!

I apologize for multithread issue, but this all applies to ipv6-address type.
Can you change in my examples source-ip from ipv6 to ipv4? 
We get crash libyang instead of validation errors:

```
[FIREWALL] Проверяем корректность модели с набором правил ipv4/6 фильтра. ... libyang[0]: Invalid value "8.8.8.8" in "source-ip" element. (path: /itmh-cpe-firewall:firewall/firewall-ipv6-config/services[sid='PARENT_CONTROL']/rules[rule-id='1']/source-ip)
python3: /home/illumin/gorgona/libyang/src/tree_data.c:490: _lyd_unlink_hash: Assertion `0' failed.
xargs: nosetests: terminated by signal 6
```

**Comment by michalvasko** [comment]
Hi,
of course not, it was a bug and I hope it is fixed now and it is the last.

Regards,
Michal

**Comment by vladique00** [comment]
Works fine.
Thank you.
