### ISSUE TITLE
Can I replace the old yang schema represented by struct lys_module by new one?

### ISSUE THREAD

**Issue by foxge** [CESNET/libyang#869]
Hi
In run-time, if the old yang module are not satisfied or takes some defects,  May I use one new yang file to replace it in run time for hot-patch case ? 

In my application, I use lys_parse_path to parse yang file:
```
const struct lys_module *lys_parse_path(struct ly_ctx *ctx, const char *path, LYS_INFORMAT format);
```

I expected
```
step1: remove or disable old module object
step2: get new module object with new file

```

Thanks.

**Comment by fredgan** [comment]
>  if the old yang module are not satisfied or takes some defects

There are two situations cause this:
1 the data is wrong(e.g. somebody send error data)
2 the demand of the module changed

It's hard to distinguish. So if you want to hot-patch automatically by this, it will be hard.

But if you just want to hot-patch manually, I think you can do the logics in your application:
1 Detect the whether the files is changed in the path.
2 If yes, call lys_parse_path again to reload the module.

**Comment by michalvasko** [comment]
Hi,
there is a function for [removing a module](https://netopeer.liberouter.org/doc/libyang/master/group__context.html#ga5c705baf1f10d37c09550a5f96d76914) so just use it and you should be fine. Note, however, that there cannot be any data existing for the module when you remove it.

@fredgan You cannot call `lys_parse_path()` again to reload an existing module.

Regards,
Michal

**Comment by foxge** [comment]
"2 If yes, call lys_parse_path again to reload the module." means that the lys_parse_path can be called multiple times ?

**Comment by foxge** [comment]
@michalvasko 
In last version, ly_ctx_remove_module is not exposed.

**Comment by fredgan** [comment]
@michalvasko  @foxge Sorry for that. Allow me to rephrase it:

If you just want to hot-patch manually, You can do the logics in your application:
1 Detect the whether the files is changed in the path.
2 If yes, reload your module correctly.(For example: stop your data handling, remove your old module, load your new module, start your data handling)

**Comment by rkrejci** [comment]
@foxge, what do you mean by "last version"? I see it in API - https://github.com/CESNET/libyang/blob/master/src/libyang.h.in#L1621

**Comment by foxge** [comment]
@rkrejci 
Yes, you are right.
