### ISSUE TITLE
Issue with leafref + require-instance + typedef

### ISSUE THREAD

**Issue by rwestphal** [CESNET/libyang#881]
Hi,

I think I've found a problem in the handling of the leafref "require-instance" substatement.

libyang honors "require-instance" in normal conditions. However, when the leafref is defined inside of a typedef, libyang seems to ignore "require-instance" altogether.

I wrote this small YANG module to demonstrate the issue:
```yang
module testmod {
  yang-version 1.1;
  namespace "http://frrouting.org/yang/test";
  prefix testmod;

  list interface {
    key "name";

    leaf name {
      type string {
        length "1..16";
      }
    }
  }

  typedef interface-ref {
    type leafref {
      require-instance false;
      path "/interface/name";
    }
  }

  leaf interface1 {
    type interface-ref;
  }
  leaf interface2 {
    type interface-ref {
      require-instance false;
    }
  }
}
```

Test file 1 (a.json):
```json
{
    "testmod:interface1": "eth0"
}
```

Test file 2 (b.json):
```json
{
    "testmod:interface2": "eth0"
}
```

The problem can then be reproduced using _yanglint_:
```
$ yanglint 
> add /usr/local/share/yang/testmod.yang
> 
> 
> data -f json -t config /mnt/renato/git/yang/leafref/a.json 
libyang[0]: Leafref "/interface/name" of value "eth0" points to a non-existing leaf. (path: /testmod:interface1)
Failed to parse data.
> 
> 
> data -f json -t config /mnt/renato/git/yang/leafref/b.json 
{
  "testmod:interface2": "eth0"
}
```

Notice how libyang complains about `interface1` pointing to a non-existing leaf, ignoring the `require-instance false` statement used in the typedef.

The second test file is loaded without problems because the `interface2` leaf overwrites the `require-instance` value.

I'm using the latest libyang 1.x version as of today (1.1.56).

**Comment by michalvasko** [comment]
Hi,
it should work properly in the latest version.

Regards,
Michal

**Comment by fredgan** [comment]
@michalvasko  I test the same case in your last commit, 
the `require-instance false`  works, but `require-instance false` or `require-instance true` in `leaf interface1` and `leaf interface2` doesn't work.

```
module testmod {
  yang-version 1.1;
  namespace "http://frrouting.org/yang/test";
  prefix testmod;

  list interface {
    key "name";

    leaf name {
      type string {
        length "1..16";
      }
    }
  }

  typedef interface-ref {
    type leafref {
      require-instance false;
      path "/interface/name";
    }
  }

  leaf interface1 {
    type interface-ref {
      require-instance true;
    }
  }
  leaf interface2 {
    type interface-ref {
      require-instance false;
    }
  }
}
```

**Comment by michalvasko** [comment]
Hi,
as it turned out ([ref](https://tools.ietf.org/html/rfc7950#section-9.9.3)), you cannot put `require-instance` into a derived type and *libyang* should no longer accept such a type. But the original problem was there except a module to test it with would be
```yang
module testmod {
  yang-version 1.1;
  namespace "http://frrouting.org/yang/test";
  prefix testmod;

  list interface {
    key "name";

    leaf name {
      type string {
        length "1..16";
      }
    }
  }

  typedef interface-ref {
    type leafref {
      require-instance false;
      path "/interface/name";
    }
  }

  leaf interface1 {
    type interface-ref;
  }
}
```
`interface1` was incorrectly considered `require-instance` `true`.

Regards,
Michal
