### ISSUE TITLE
dependent features + leafrefs: yang parsing error

### ISSUE THREAD

**Issue by rjarry** [CESNET/libyang#888]
Hello,

When a `leafref` is defined in a container which has an `if-feature b`, we get a yang parsing error if the target leaf has an `if-feature a` even if `b` depends on `a`. As far as I understand, this is valid since if the leafref is active (i.e. only if the `b` feature is enabled) then the leafref target must also be active since `b` depends on `a`.

I have the following test program to reproduce the problem:

```c
/* features-test.c */
#include <stdlib.h>
#include <string.h>
#include <libyang/libyang.h>

static char *yang =
	"module test1 {"
	"  yang-version 1.1;"
	"  namespace 'urn:yang:test1';"
	"  prefix test1;"
	"  feature a;"
	"  feature b {"
	"    if-feature a;"
	"  }"
	"  container conf {"
	"    container c1 {"
	"      if-feature a;"
	"      leaf xxx {"
	"        type string;"
	"      }"
	"    }"
	"    container c2 {"
	"      if-feature b;"
	"      leaf yyy {"
	"        type leafref {"
	"          path '/test1:conf/test1:c1/test1:xxx';"
	"          require-instance false;"
	"        }"
	"      }"
	"    }"
	"  }"
	"}";

int main(int argc, char **argv)
{
	struct ly_ctx *ctx;

	ctx = ly_ctx_new(NULL, 0);
	lys_parse_mem(ctx, yang, LYS_IN_YANG);

	return 0;
}
```

Here is the trace:

```
$ gcc test-features.c -o test-features -l yang
$ ./test-features 
libyang[0]: No resolvents found for leafref "/test1:conf/test1:c1/test1:xxx". (path: /test1:conf/c2/yyy)
libyang[0]: Leafref is not conditional based on "a" feature as its target. (path: /test1:conf/c2/yyy)
libyang[0]: Module "test1" parsing failed.
```

Thanks in advance for your help.

**Comment by fredgan** [comment]
The [RFC7950 Chapter 9.9](https://tools.ietf.org/html/rfc7950#page-158) said
> If the leaf that the leafref refers to is conditional based on one or
   more features (see Section 7.20.2), then the leaf with the leafref
   type MUST also be conditional based on at least the same set of
   features.

In your case, yes, `feature b` is based on `feature a`.

But, I don't think `feature b` is the same as `feature a`, so the feature set [b] is not the subset of [a]. I think the library just need to check the names of the set. If not, the semantic check would be very complicate, it would be hard to calculate the feature dependencies. How do you understand `at least the same set of features`?

**Comment by rkrejci** [comment]
I agree with @fredgan. Formally, it can be said that the model is incorrect. However, logically, it is correct. What we can do now is to change the error to warning, so it will be possible to load such module (even in case it wil be wrong even logically). In libyang 2, I would like to do a semantic check to cover even the complicated expresisons and follow how it should be logically.

What do you think, is this approach ok?

**Comment by rjarry** [comment]
@fredgan, @rkrejci, that makes sense. Thanks for the link in the rfc.

Indeed it would be a nice addition if libyang could resolve the dependency but it is a rather complex task depending on the `if-feature` expressions complexity. I can live with explicit dependencies for now.

**Comment by rkrejci** [comment]
The mechanism of features was redesigned in libyang2 and the example above is now working correctly, so I'm closing the issue.
