### ISSUE TITLE
Error for unknown data in schema when strict is not set for json files

### ISSUE THREAD

**Issue by samuel-gauthier** [CESNET/libyang#895]
Parsing data containing unknown nodes results in an error even when strict is not set, for json files. It works for xml files.

I checked with version 1.0.71.
To reproduce, create those files:
test.yang:
```
module test {
  yang-version 1.1;
  namespace "test";
  prefix test;

  leaf hostname {
    type string;
    description
      "The hostname of the device -- should be a single domain
       label, without the domain.";
  }
}
```

test.json:
```
{
        "test:hostname": "myname",
        "test:hostname2": "myname"
}
```

test.xml:
```
<hostname xmlns="test">myname</hostname>
<hostname2 xmlns="test">myname</hostname2>
```

Then, using yanglint:
```
> add test.yang
> data test.xml
> data -s test.xml
libyang[0]: Unknown element "hostname2". (path: /)
Failed to parse data.
> data test.json
libyang[0]: Unknown element "hostname2".
Failed to parse data.
> data -s test.json
libyang[0]: Unknown element "hostname2".
Failed to parse data.
```

I expected data test.json to pass, like is does for data test.xml, but it fails.
After checking with gdb, the code apparently stops here, in src/parser_json.c:944 (json_parse_data function):
```
    module = lys_node_module(schema);
    if (!module || !module->implemented || module->disabled) {
        LOGVAL(ctx, LYE_INELEM, (*parent ? LY_VLOG_LYD : LY_VLOG_NONE), (*parent), name);
        goto error;
    }
```

**Comment by michalvasko** [comment]
Hi,
this is rather a feature than a bug. JSON and XML parsers are quite different and skipping unknown elements in JSON is simply not supported.

Regards,
Michal

**Comment by samuel-gauthier** [comment]
Hi Michal,

So this would mean that LYD_OPT_STRICT must always be passed when using the JSON parser, right? As there are two paths of code in json_parse_attr if this option is set or not, it seemed that there was a will to support it.

```
        if (options & LYD_OPT_STRICT) {
            LOGVAL(ctx, LYE_INMETA, LY_VLOG_NONE, NULL, prefix, name, value);
            free(value);
            goto error;
        }

        LOGWRN(ctx, "Unknown \"%s:%s\" metadata with value \"%s\", ignoring.",
               (prefix ? prefix : "<none>"), name, value);
        free(value);
        goto next;
```

Regards,
Samuel

**Comment by rkrejci** [comment]
I believe that it is a bug. Michal, why the JSON parser would not be able to skip unknown elements?

**Comment by rkrejci** [comment]
The problem is that it is not just an easy fix, we need to skip the input data related to the unknown element. Is there something else I don't see?

**Comment by samuel-gauthier** [comment]
Thanks a lot for this.
