### ISSUE TITLE
lyd_find_path  low efficiency

### ISSUE THREAD

**Issue by lumanyu180** [CESNET/libyang#899]
Hi：
    I found lyd_find_path use too many time when my configuration is too large。Is there any way to improve it efficiency ?

    thanks very much

**Comment by michalvasko** [comment]
Hi,
`lyd_new_path()` executes XPath on a data tree so it will always take some time. There were some optimizations in version 1.0.66 (SO 1.1.60) so if you are using that or newer, it is as good as it gets.

Regards,
Michal

**Comment by lumanyu180** [comment]
Thanks for your reply very much。I will try version 1.0.66。
I have another question,  LY_ENABLED_CACHE, what is its effect ?  If it can improve lyd_find_path‘s efficiency ?

**Comment by lumanyu180** [comment]
OK , i know. Thans very much!
