### ISSUE TITLE
Installing o-ran-beamforming yang module failed

### ISSUE THREAD

**Issue by brchiu** [CESNET/libyang#901]
Installing `o-ran-beamforming.yang` failed : 
```
$ sudo sysrepoctl -i o-ran-beamforming.yang
libyang[1]: Missing status in deprecated subtree (/o-ran-beamforming:{grouping}[beamforming-config]/per-band-config/per-band-config-element), inheriting.
libyang[0]: A current definition "coarse-fine-beam-relation" references deprecated definition "beam-id". (path: /o-ran-beamforming:beamforming-config/per-band-config/beam-information/beamforming-properties/beam-id)
libyang[0]: Invalid value "beamforming-config" of "uses". (path: /o-ran-beamforming:beamforming-config/beamforming-config)
libyang[0]: Copying data from grouping failed. (path: /o-ran-beamforming:beamforming-config/beamforming-config)
libyang[0]: Module "o-ran-beamforming" parsing failed.
sysrepoctl error: Failed to install module "o-ran-beamforming.yang" (libyang error)
```
This can be reproduced by `make sr_clean` then execute `reproduce.sh` inside [minimal reproduce set 2 of yang modules](https://drive.google.com/open?id=1lMAhLxQuFEwAsQuaCmOVTZQck3_XsG3C)

**Comment by michalvasko** [comment]
Hi,
so after wrapping my head around the module and all those groupings, I believe the error is correct and there really is a `current` leafref referencing a `deprecated` leaf. That is [forbidden](https://tools.ietf.org/html/rfc7950#section-7.21.2).

Regards,
Michal

**Comment by JoemonChittilapilly** [comment]
how do i resolve this issue

**Comment by jktjkt** [comment]
> how do i resolve this issue

By talking to the organization which produced the malformed YANG model. It's up to them to fix the non-conformance.
