### ISSUE TITLE
Can xpath concat function accept 5 parameters ?

### ISSUE THREAD

**Issue by brchiu** [CESNET/libyang#902]
During installing `o-ran-operations.yang`, I got the following error message : 
```
libyang[0]: Invalid number of arguments (5) for the XPath function concat.
libyang[0]: Module "o-ran-operations" parsing failed.
sysrepoctl error: Failed to install module "o-ran-operations.yang" (libyang error)
```
I could simply change line  2121 to `max_arg_count = 5;` to eliminate this error
```
        if (!strncmp(&exp->expr[exp->expr_pos[*exp_idx]], "concat", 6)) {
            min_arg_count = 2;
-           max_arg_count = 3;
+           max_arg_count = 5;
```
but I do not know whether there is foreseeable side effect for this change ?

**Comment by michalvasko** [comment]
Hi,
it can have even more parameters and it should be fixed now.

Regards,
Michal
