### ISSUE TITLE
How to load a submodule from A directory, and main module with a same submodule in B directory.

### ISSUE THREAD

**Issue by longjianglzt** [CESNET/libyang#906]
HI, I have two directorys, A directory may exist or not, submodule or deviation yang(eg. aaa-sub.yang) in this directory. B directory must exist and with main module(aaa.yang), and it's submodule(aaa-sub.yang) same with A directory's.How to load aaa-sub.yang if A directory exist but from B directory? Thanks.

**Comment by michalvasko** [comment]
Hi,
this is not really the way the modules should be loaded. But, I believe you should be able to do this by setting dir `B` in the searchpath before dir `A`. Use [this function](https://netopeer.liberouter.org/doc/libyang/master/group__context.html#ga77b85d2a88fd4b3e0e0e20071ea7acc6) or some of the later ones in the documentation to achieve this.

Regards,
Michal

**Comment by longjianglzt** [comment]
I main if A dir exists and aaa-sub.yang(diffrent from aaa-sub.yang in B dir) is modified, when load aaa.yang(it includes aaa-sub.yang) how could libyang find aaa-sub.yang from A dir but B. Whether libyang will load aaa-sub.yang from dir A If I set dir A to searchpath before dir B?

**Comment by longjianglzt** [comment]
> Hi,
> this is not really the way the modules should be loaded. But, I believe you should be able to do this by setting dir `B` in the searchpath before dir `A`. Use [this function](https://netopeer.liberouter.org/doc/libyang/master/group__context.html#ga77b85d2a88fd4b3e0e0e20071ea7acc6) or some of the later ones in the documentation to achieve this.
> 
> Regards,
> Michal

I main if A dir exists and aaa-sub.yang(diffrent from aaa-sub.yang in B dir) is modified, when load aaa.yang(it includes aaa-sub.yang) how could libyang find aaa-sub.yang from A dir but B. Whether libyang will load aaa-sub.yang from dir A If I set dir A to searchpath before dir B?

**Comment by longjianglzt** [comment]
> > Hi,
> > this is not really the way the modules should be loaded. But, I believe you should be able to do this by setting dir `B` in the searchpath before dir `A`. Use [this function](https://netopeer.liberouter.org/doc/libyang/master/group__context.html#ga77b85d2a88fd4b3e0e0e20071ea7acc6) or some of the later ones in the documentation to achieve this.
> > Regards,
> > Michal
> 
> I main if A dir exists and aaa-sub.yang(diffrent from aaa-sub.yang in B dir) is modified, when load aaa.yang(it includes aaa-sub.yang) how could libyang find aaa-sub.yang from A dir but B. Whether libyang will load aaa-sub.yang from dir A If I set dir A to searchpath before dir B?
> 
> Thanks

I test the way to set dir B in the searchpath before dir A, it works, Thanks.
