### ISSUE TITLE
YANG 1.1 implementation issues (devel)

### ISSUE THREAD

**Issue by milanlenco** [CESNET/libyang#91]
I have started implementing support for some features from YANG 1.1 into the sysrepo against the latest libyang devel version. I realize that this is still under development so you may be aware of these problems or their presence is just an effect of in-progress work. Take this as a feedback, we won't merge anything related to YANG 1.1 into sysrepo until libyang supports it in master anyway.

1. YANG 1.1 is more specific about notifications, it seems they can be connected to a container or a list, i.e. not only on the top level. But if I try to parse yang with a nested notification I get:
```
libyang: Invalid keyword "notification".
libyang: Module parsing failed.
```

2. validation of Action (i.e. nested RPC) _output_ fails with "Subtree is not a single RPC/reply." here:

```
lyd_check_topmandatory():
....
  85|     } else if (options & (LYD_OPT_RPC | LYD_OPT_RPCREPLY)) {
  86|         if (!data || data->parent || (data->prev != data) || !(data->schema->nodetype & (LYS_RPC | LYS_ACTION))) {
  87|             LOGERR(LY_EINVAL, "Subtree is not a single RPC/reply.");
  88|             return EXIT_FAILURE;
  89|         }
...
```
Condition `data->schema->nodetype & (LYS_RPC | LYS_ACTION)` fails since Action is defined inside container/list.
For `input` parameters it takes the branch for Actions (which doesn't yeld error) as the bitmask of options gets modified in lyd_validate:

```
2687|    if ((options & LYD_OPT_RPC) && *node && ((*node)->schema->nodetype != LYS_RPC)) {
2686|         options &= ~LYD_OPT_RPC;
2687|         options |= LYD_OPT_ACTION;
2688|     }
2689|
2690|     if (lyd_check_topmandatory(*node, ctx, options)) {
2691|         goto error;
2692|     }

```
Btw, I have been using LYD_OPT_RPC and LYD_OPT_RPCREPLY for validation of Action parameters, is that correct?

**Comment by michalvasko** [comment]
Hi Milan,
our yang1.1 branch supports very little from all the new YANG 1.1 features. Specifically, only actions (creating, parsing, validating, ...) and new if-feature expressions, please report errors only with these. So yes, inner notification is not supported yet. Also, please look at the [action section](https://tools.ietf.org/html/draft-ietf-netmod-rfc6020bis-14#section-7.15) example, action output does not differ from RPC output, so action node is correctly expected to be the top. You have used correct flags for validation.

Regards,
Michal

**Comment by milanlenco** [comment]
Thanks for the quick reply.

re 2.) that was my mistake indeed. I would pass container containing the _action_ child node to lyd_validate rather than the action node itself, hence it complained about the type of the top-most node.

I'm closing this for now and will re-open in case I found any issue related to YANG 1.1 in the scope of features that you have listed.
