### ISSUE TITLE
Can't find libpcre while trying static build

### ISSUE THREAD

**Issue by gli-spirent** [CESNET/libyang#911]
I was trying build a static library of libyang. I met the same issue of #474.
CMake Warning at CMakeLists.txt:171 (message):
  Missing tools (devscripts, debhelper package) for building deb package.

  You won't be able to generate deb package from source code.

  Compiling libyang should still works fine.

CMake Warning at CMakeLists.txt:271 (message):
  Tests are disabled in case of static build

CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PCRE (missing: PCRE_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  CMakeModules/FindPCRE.cmake:25 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:305 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/gli/netconf/libyang/build/CMakeFiles/CMakeOutput.log".
See also "/home/gli/netconf/libyang/build/CMakeFiles/CMakeError.log".

I tried to use the static build of libpcre from(ftp://ftp.pcre.org/pub/pcre/) by command below but still failed with the error message above

cmake .. -DENABLE_STATIC=on -DPCRE_LIBRARY=/home/gli/netconf/pcre-8.43/build/libpcre.so -DPCRE_INCLUDE_DIR=/home/gli/netconf/pcre-8.43/build/

**Comment by fredgan** [comment]
If you are using ubuntu, you can install pcre by command 
`apt-get install libpcre3-dev libpcre3`

**Comment by gli-spirent** [comment]
Thanks for your suggestion, @fredgan. However, I'm doing a project that needs cross compiling libyang. So, I have to compile all the libs needed.

**Comment by fredgan** [comment]
1  You are attemp to build static libyang package, But you are using dynamic pcre library. I think it will not work.
2 `PCRE_LIBRARY` should be `PCRE_LIBRARIES` , `PCRE_INCLUDE_DIR` should be `PCRE_INCLUDE_DIRS`
3 If you are using your uninstalled pcre library, you should modify the `CMakeLists.txt` file in the project root, comment line 305: `find_package(PCRE REQUIRED)`

So, after you modify the `CMakeLists.txt`, then your cmake command is:
```
cmake  -DPCRE_LIBRARIES=/home/gli/netconf/pcre-8.43/build/libpcre.so -DPCRE_INCLUDE_DIRS=/home/gli/netconf/pcre-8.43/build/  ..
```

**Comment by gli-spirent** [comment]
Actually, the .so is a copy of the .a which I tried to cheat cmake. I did compile libpcre to a static one. 

Thanks for your help. I commented out the line you mentioned and it passed the libpcre issue. Now I moved a step ahead.

**Comment by michalvasko** [comment]
Hi,
you can create a static package without commenting any lines. It is done periodically in [travis](https://travis-ci.org/CESNET/libyang/jobs/600924549).

Regards,
Michal

**Comment by gli-spirent** [comment]
Thanks. I'll look into travis again. 
I tried it but did not figure out how after I googled and found libyang had static build with travis.

**Comment by gli-spirent** [comment]
Looks it still used the library from the OS.
-- Found PCRE: /usr/lib/x86_64-linux-gnu/libpcre.a  

I'll not have one on the system in runtime. So, looks I have to comment out the line and specify them on command line of cmake.

**Comment by michalvasko** [comment]
If it could be found automatically on the system I see no reason why it could not be found in your case. It will be just the matter of setting correct paths. And you do not have to have it in runtime, just for the compilation, so I am not sure why have you mentioned that.

Regards,
Michal

**Comment by gli-spirent** [comment]
I'm trying cross-compling libyong so the one in the local system is not the correct one. And I really don't have one on my Fedora(there are lot of dynamic ones, aka, libpcre....so found).

Actually, I think it's the bug of the CMakeList file because it should not try to find one when the user specified a customized one.

**Comment by michalvasko** [comment]
So you are cross compiling *libyang* to be used as a static library on another system? And you just have problems to make `CMake` find the static *libpcre* compiled for the target platform instead of the dynamic *libpcre* found on your local system?

Regards,
Michal

**Comment by gli-spirent** [comment]
Yes. It should always use the one specified instead of the local one, dynamic or not.

**Comment by michalvasko** [comment]
I see. Maybe you also need to define `-DPCRE_FOUND`?

**Comment by brchiu** [comment]
@gli-spirent 
you can refer to this article [CrossCompiling](https://gitlab.kitware.com/cmake/community/wikis/doc/cmake/CrossCompiling#the-toolchain-file) that you have to set `CMAKE_FIND_ROOT_PATH` to designate the path of root file system for target (not host).

**Comment by gli-spirent** [comment]
> I see. Maybe you also need to define `-DPCRE_FOUND`?

No, I did not. I'll try it.

**Comment by gli-spirent** [comment]
> @gli-spirent
> you can refer to this article [CrossCompiling](https://gitlab.kitware.com/cmake/community/wikis/doc/cmake/CrossCompiling#the-toolchain-file) that you have to set `CMAKE_FIND_ROOT_PATH` to designate the path of root file system for target (not host).

Thanks for your information. Will study it more latter. However, I found I could not follow it after I browsed the instructions roughly.

I don't even have cmake in my cross-compling environment. So, I have to do things ugly to let cmake generate Makefile for me and change the Makefile to cross-compling. :(

Thanks for the information anyway.

**Comment by brchiu** [comment]
@gli-spirent , `cmake` is on your host for compiling, mostly a linux or similar system,
so you don't need to have `cmake` on arm/mips/risc-v/..... platform.

If you are using yocto, you can refer to this wonderful [meta-sysrepo](https://github.com/sartura/meta-sysrepo), which is a little out-of-date but is easily adapted to newest `libyang` repository.

**Comment by gli-spirent** [comment]
> I see. Maybe you also need to define `-DPCRE_FOUND`?

Got the same error:
cmake .. -DENABLE_STATIC=on -DPCRE_FOUND=on -DPCRE_LIBRARIES=/home/gli/netconf/pcre-8.43/build/libpcre.a -DPCRE_INCLUDE_DIRS=/home/gli/netconf/pcre-8.43/build/
CMake Warning at CMakeLists.txt:171 (message):
  Missing tools (devscripts, debhelper package) for building deb package.

  You won't be able to generate deb package from source code.

  Compiling libyang should still works fine.


CMake Warning at CMakeLists.txt:271 (message):
  Tests are disabled in case of static build


CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PCRE (missing: PCRE_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  CMakeModules/FindPCRE.cmake:25 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:305 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/gli/netconf/libyang/build/CMakeFiles/CMakeOutput.log".
See also "/home/gli/netconf/libyang/build/CMakeFiles/CMakeError.log".

**Comment by michalvasko** [comment]
Well, it was just an idea, I have never even cross-compiled *libyang* myself. This module (`FindPCRE`) was not written by us and maybe it is not possible to force it to use a specific library but I would expect it is. Anyway, you should look into the CMake module yourself and go from there, I am not able to further help you.

Regards,
Michal

**Comment by gli-spirent** [comment]
> Well, it was just an idea, I have never even cross-compiled _libyang_ myself. This module (`FindPCRE`) was not written by us and maybe it is not possible to force it to use a specific library but I would expect it is. Anyway, you should look into the CMake module yourself and go from there, I am not able to further help you.
> 
> Regards,
> Michal

Thanks anyway. "Comment out the line" works for me.
