### ISSUE TITLE
Special character(Tab/LF) are print as different type in YIN and YANG format

### ISSUE THREAD

**Issue by fredgan** [CESNET/libyang#912]
Hi, Radek/Michal,

I use yanglint to parse the following mod.yang and print as  `yin` and `yang` format, 
Then I find some differences about the escaped character `'\t'`、`'\n'`.

mod3.yang

```
module mod3 {
  namespace "aa\tbb\nmod3";
  prefix "m3";
}
```

The result:

`yanglint -f yang mod3.yang`

```
module mod3 {
  namespace "aa\tbb
   mod3";
  prefix m3;
}
```

`yanglint -f yin mod3.yang`

```
<?xml version="1.0" encoding="UTF-8"?>
<module name="mod3"
        xmlns="urn:ietf:params:xml:ns:yang:yin:1"
        xmlns:m3="aa    bb
mod3">
  <namespace uri="aa    bb
mod3"/>
  <prefix value="m3"/>
</module>
```

As we can see, 
in the yang format, `'\t'` is shown as escaped character, but `'\n'` is shown as LF character, 
but in the yin format, `'\t'` is shown as TAB character and `'\n'` is shown as LF character

It's not a serious problem, But I want to know, should  the same conversion rule is used for the special character regardless of output format.
If yes, which rule should be used? If you wish, I would like to submit a PR for fixing this.

**Comment by rkrejci** [comment]
I believe that difference between output formats is fine. `pyang` prints YANG the same way and YIN format is printed with character codes of LF/TAB. I didn't find any specification what is correct (I believe that any of them).

**Comment by fredgan** [comment]
Hi, @rkrejci 
Well, as it happens, I also tried `pyang` today for comparing this. It's the same as you said. 

Besides, I try to read the RFC7950, it just says the two types express the same meaning.  So is it a coinsidence that libyang and pyang do the same output? ^_^

By the way,  the LF and TAB in the `namespace` statement in `pyang`'s YIN format output is shown as `&#10;` and `&#9;`
