### ISSUE TITLE
static code analysis by scan-build (utility program of clang-tools)

### ISSUE THREAD

**Issue by brchiu** [CESNET/libyang#915]
Use `scan-build` to perform static code analysis for commit :  36044bc625e715a819bbd932bab9d0ed8d85f2d4

```
sudo apt-get install clang-tools -y
cd libyang
mkdir build
cd build
scan-build cmake -DENABLE_BUILD_TESTS=0 ..
scan-build -o ~/tmp make -j16
scan-view ~/tmp/<output directory at end of build>
```

[result of scan-build](https://drive.google.com/open?id=1P5juBJairEHzHfVPbcpsusu26w-c5ATP) can be view by unzip the result and execute `scan-view 2019-10-23-234219-10433-1`

There might be false alarms but worthy of checking.

![summary-of-static-code-anaylsis-result-by-scan-build](https://user-images.githubusercontent.com/6227912/67411438-387a3500-f5f0-11e9-872e-0258c26ceeb0.png)

**Comment by fredgan** [comment]
I recomment that you attach the result with the "Attach files" by this page. @brchiu  Thanks

**Comment by brchiu** [comment]
@fredgan , I have already uploaded the [result of scan-build](https://drive.google.com/open?id=1P5juBJairEHzHfVPbcpsusu26w-c5ATP), however, I re-upload file to 
[2019-10-23-234219-10433-1.zip](https://github.com/CESNET/libyang/files/3775375/2019-10-23-234219-10433-1.zip)

**Comment by fredgan** [comment]
Thanks. You know, someone(include me) may not able to access Cloud Storage Website.
I downloaded your file, In fact, your zip file is empty.

**Comment by brchiu** [comment]
@fredgan , my bad, re-upload file again. [2019-10-23-234219-10433-1.zip](https://github.com/CESNET/libyang/files/3778581/2019-10-23-234219-10433-1.zip)
