### ISSUE TITLE
parser: question about status inheritance

### ISSUE THREAD

**Issue by rjarry** [CESNET/libyang#916]
Checking the following module with `yanglint` produces warnings:

```yang
module test-deprecation {
  namespace "urn:test:deprecation";
  prefix td;

  container data {
    container deprecated-thing {
      status deprecated;
      leaf child1 {
        type int8;
      }
      container child2 {
        list grand-child2 {
          key k;
          leaf k {
            type string;
          }
          leaf size {
            type uint32;
          }
        }
      }
    }
    container conf {
      leaf val {
        type string;
      }
    }
  }
}
```

```
$ LIBYANG_EXTENSIONS_PLUGINS_DIR=`pwd`/src/extensions LIBYANG_USER_TYPES_PLUGINS_DIR=`pwd`/src/user_types ./yanglint -V -f yang test-deprecation.yang 
warn: Missing status in deprecated subtree (/test-deprecation:data/deprecated-thing/child1), inheriting.
warn: Missing status in deprecated subtree (/test-deprecation:data/deprecated-thing/child2), inheriting.
warn: Missing status in deprecated subtree (/test-deprecation:data/deprecated-thing/child2/grand-child2), inheriting.
warn: Missing status in deprecated subtree (/test-deprecation:data/deprecated-thing/child2/grand-child2/k), inheriting.
warn: Missing status in deprecated subtree (/test-deprecation:data/deprecated-thing/child2/grand-child2/size), inheriting.
module test-deprecation {
  namespace "urn:test:deprecation";
  prefix td;

  container data {
    container deprecated-thing {
      status deprecated;
      leaf child1 {
        type int8;
        status deprecated;
      }

      container child2 {
        status deprecated;
        list grand-child2 {
          key "k";
          status deprecated;
          leaf k {
            type string;
            status deprecated;
          }

          leaf size {
            type uint32;
            status deprecated;
          }
        }
      }
    }

    container conf {
      leaf val {
        type string;
      }
    }
  }
}
```

Indeed, there is no explicit "deprecated" status on children of the deprecated `/test-deprecated:data/deprecated-thing` container.

I don't see any mention about specific behaviour in [RFC 7950](https://tools.ietf.org/html/rfc7950#section-7.21.2). However, in my opinion, when a container or list is marked as deprecated, all its children should be marked as deprecated as well (unless their status is explicitly specified). This is what libyang does but it makes quite a fuss about it.

Would it be acceptable to change these warnings:

https://github.com/CESNET/libyang/blob/36044bc625e715a819bbd932bab9d0ed8d85f2d4/src/parser_yang.c#L2475
https://github.com/CESNET/libyang/blob/36044bc625e715a819bbd932bab9d0ed8d85f2d4/src/parser_yin.c#L4027

to `LOGVRB` or `LOGDBG`?

Or do I need to silence all warnings not to see them?

**Comment by rkrejci** [comment]
Hi, there was a discussion about this in [NETMOD mailing list](https://mailarchive.ietf.org/arch/msg/netmod/KcNkupq5AL5NMJhmA3-RDfGYl8w). Specification says that if the status statement is not present, the status is `current`. So, formally, status is not inherited. 
To avoid the warnings, you are supposed to fix the schema by adding explicit status statements to the whole subtree (as done in IETF schemas). On the other hand, since there is no meaning of a current node under a deprecated one, libyang does not report this as an error (and loads the schema), but it is reported as warning and status is implicitely inherited.

**Comment by rjarry** [comment]
ok thanks for the clarification.
