### ISSUE TITLE
Loading of data failed because of constrain in other module

### ISSUE THREAD

**Issue by lukasmacko** [CESNET/libyang#92]
While debugging #89 I come across this error
```C
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <libyang/libyang.h>

int main(int argc, char **argv)
{
   struct lyd_node *root = NULL;
   struct ly_ctx *ctx = ly_ctx_new(".");
   if (!ly_ctx_load_module(ctx, "ietf-interfaces", NULL)) return 2;
   if (!ly_ctx_load_module(ctx, "ietf-ip", NULL)) return 3;
   if (!ly_ctx_load_module(ctx, "iana-if-type", NULL)) return 4;
   const struct lys_module *module = ly_ctx_load_module(ctx, "StaticScopeTest", NULL); 
   if (!module) return 1;

   int fd = open("ietf-interfaces.data.xml", O_RDONLY);
   if (-1 == fd) return 5;

   root = lyd_parse_fd(ctx, fd, LYD_XML, LYD_OPT_CONFIG);
   if (!root) return 6;
   ly_ctx_destroy(ctx, NULL);
   return 0;
}
```

I got `libyang[1]: Too few "leaflistField" elements. (path: /)`

If the model with leaf-list constraint is not loaded everything works as expected.

ietf-interfaces.data.xml
```XML
<interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
  <interface>
    <name>eth0</name>
    <description>Ethernet 0</description>
    <type>ethernetCsmacd</type>
    <enabled>true</enabled>
    <ipv4 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip">
      <enabled>true</enabled>
      <mtu>1500</mtu>
      <address>
        <ip>192.168.2.100</ip>
        <prefix-length>24</prefix-length>
      </address>
    </ipv4>
  </interface>
  <interface>
    <name>eth1</name>
    <description>Ethernet 1</description>
    <type>ethernetCsmacd</type>
    <enabled>true</enabled>
    <ipv4 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip">
      <enabled>true</enabled>
      <mtu>1500</mtu>
      <address>
        <ip>10.10.1.5</ip>
        <prefix-length>16</prefix-length>
      </address>
    </ipv4>
  </interface>
</interfaces>
```
Yangs:

StaticScopeTest.yang
```
module StaticScopeTest{
  namespace "urn:ietf:params:xml:ns:yang:zte:staticscopetest";
  prefix StaticScopeTest;

  container Mo{
        leaf-list leaflistField{
            type string;
            max-elements 3;
            min-elements 1;
        } 
    }
}
```
[iana-if-types](https://github.com/sysrepo/sysrepo/blob/master/tests/yang/iana-if-type.yang)
[ietf-interfaces](https://github.com/sysrepo/sysrepo/blob/master/tests/yang/ietf-interfaces%402014-05-08.yang)
[ietf-ip](https://github.com/sysrepo/sysrepo/blob/master/tests/yang/ietf-ip%402014-06-16.yang)

**Comment by michalvasko** [comment]
Hi,
this is actually not an error. Specifying `LYD_OPT_CONFIG` in `lyd_parse_fd()` means that you are parsing configuration data (what whould one expect to receive from get-config). It must be valid for the whole context, but the error is telling it is not, correctly.

I understand that this may be annoying sometimes, but there is not much sense in allowing to load a data subtree which is actually invalid. Add to context only the schemas that you want to work with.

Regards,
Michal

**Comment by rkrejci** [comment]
just a note to the mentioned data received from `get-config` - there is a special option for this data, `LYD_OPT_GETCONFIG`, since there can be specified a filter and the data can be incomplete. The `LYD_OPT_CONFIG` says that you are loading complete configuration datastore. The complete means, that it contains at least all mandatory data according to the schemas in the context.
