### ISSUE TITLE
Does libYang support parsing of extensions?

### ISSUE THREAD

**Issue by pathori** [CESNET/libyang#93]
Need the information about whether libYang support parsing of extension ? if yes please give some information. I can see the code for extension handling only for below extensions
get-filter-element-attributes
default-deny-write
default-deny-all

I would like to write some new extensions, Please help me how i can do that?

**Comment by michalvasko** [comment]
Hi,
libyang currently does not support any other extensions than the ones you mentioned and we do not plan to support generic extension at all (it would be very ineffective). What extensions did you have in mind?

Regards,
Michal

**Comment by pathori** [comment]
Because we need some extra information to interact with database. For example only ifname is available in rfc7223, but in database we store index. so the extension is required to add another leaf in interface container. Please let me know if u have any other suggestion.
Also need some information to identify the table and field in database.

**Comment by michalvasko** [comment]
Hi,
if you want to add another leaf in the `interface` list, you need to use augments, not extensions. You can add database identification this way as well. Look at the [ietf-ip](https://tools.ietf.org/html/rfc7277) module.

Regards,
Michal

**Comment by pathori** [comment]
Hi,
ifIndex is not visible to the user. So this can not be encoded in the rpc response. And the database access need table id and field id. I think this information i can not add as augment, It is internal to the device.

**Comment by michalvasko** [comment]
In that case it may not even have to be in the configuration. What if you stored this information internally, some kind of a map interface tied with table id and field id. Only problem is that this information would have to be build somehow during the startup of the daemon managing this configuration or stored separately. What do you think?

Regards,
Michal

**Comment by pathori** [comment]
That is one option to create mapping and load during the device startup. Could you please explain me the libnetconf implementation for database operations?

**Comment by michalvasko** [comment]
I am not sure what are we talking about, there is no implementation of database operations in libnetconf. You need to implement all this yourself in the daemon (or whatever else) managing your interfaces using the database.

Regards,
Michal

**Comment by pathori** [comment]
may be I got confused with below statement from the libnetconf2 readme. Here it says that libnetconf2 does not implement the datastore but libnetconf has.
![image](https://cloud.githubusercontent.com/assets/19666544/17139796/745f8602-5363-11e6-9863-5bde0a71e050.png)

**Comment by michalvasko** [comment]
Yeah, libnetconf implements **datastore**, not a **database**. Datastore is defined in the [NETCONF RFC](https://tools.ietf.org/html/rfc6241#section-5.1). In libnetconf is in great majority of cases reduced simply to a file for every module that holds its *running*, *startup*, and *candidate* datastore configuration content. We use sysrepo for storing the configuration, that is what that description is trying to warn about, you cannot use libnetconf/libnetconf2 without a datastore implementation.

Regards,
Michal

**Comment by pathori** [comment]
Hi, 
Thanks a lot for providing the information. By the way how can I test end to end using libYang and libNetconf/libNetconf2? Can you please provide me some information.

**Comment by michalvasko** [comment]
Hi,
for libnetconf there is netopeer-server and netopeer-cli (netopeer project) and for libnetconf2/libyang you need [sysrepo](https://github.com/sysrepo/sysrepo), netopeer2-server, and netopeer2-cli (netopeer2 project).

Regards,
Michal

**Comment by pathori** [comment]
ok, in case of get operation let us say the data model is like 
a(parent)
 b(child)
  c(grandchild)

now i give the rpc like below
<rpc>
 <a>
  <fd>10</fd>
 </a>
</rpc>

lyd_parse_xml 
a
 all other fields of 'a' as selection
 b
  all fields of 'b' as selection
  c
  all fields of 'c' as selection

**Comment by michalvasko** [comment]
Hi,
I am not sure what you are asking, what will be the result of a get with the filter you mentioned? If so, just try it or look into the RFC.

Regards,
Michal

**Comment by pathori** [comment]
Basically I want to understand how the subtree filtering happens in
libyang. How the data tree is retrieved from a data store in above example.

**Comment by rkrejci** [comment]
Hi, this issue was named "Does libYang support parsing of extensions?" Please keep the discussion on topic - this is issue tracker, not a chat. Also note, that your post is unreadable, please follow the GitHub markdown to format your posts.
