### ISSUE TITLE
python wrapper crashes when listing enum values in a schema

### ISSUE THREAD

**Issue by ishidawataru** [CESNET/libyang#937]
The following python script causes a segmentation fault. It happens with both the latest [master](https://github.com/CESNET/libyang/commit/ac3427b10e532eaee877a52a71c1efdeece8411a) and [devel](https://github.com/CESNET/libyang/commit/ac3427b10e532eaee877a52a71c1efdeece8411a) branch. 

I checked it works fine with the C++ swig library.

Am I misusing the python wrapper? or is this a bug?

### code

```python
import yang as ly

schema = '''module a {
    namespace "a";
    prefix "a";

    leaf test {
        type enumeration {
        enum A;
        enum B;
        enum C;
        enum D;
        }
    }
}'''

ctx = ly.Context()
ly.set_log_verbosity(ly.LY_LLDBG)
m = ctx.parse_module_mem(schema, ly.LYS_IN_YANG)
d = m.data()
s = d.find_path('/a:test')
t = s.schema()[0]
v = t.subtype()
if v.type().base() == ly.LY_TYPE_ENUM:
    enums = v.type().info().enums()
    count = enums.count()
    e = enums.enm()
    print('count() = {}, len(e) = {}'.format(count, len(e)))
    for i in range(count):
        print(e[i].name())
```

### result

```
libyang[2]: Module "a" successfully parsed as implemented.
count() = 4, len(e) = 5
A
B
C
Segmentation fault
```

**Comment by michalvasko** [comment]
Hi,
we have tested it and it seems the problem is in SWIG. I have used swig 4.0.1 and managed to reproduce the bug. However, this example worked just fine with SWIG 3.0.12 (on 2 systems). So, you should probably downgrade your SWIG and it would be best to report the problem to them but I do not consider myself qualified for that, I know little Python and almost nothing about SWIG.

Regards,
Michal

**Comment by ishidawataru** [comment]
Thank you very much for taking the time.
Actually I was using swig 3.0.12. I tried swig 4.0.1.
It didn't cause segfault but the output is still invalid.

Tried Python 3.6.8 and Python 2.7.15 but the result was the same.

When you get the example working, what was the value of `len(e)`? Was it `4` or `5` ?

```
# python test.py
libyang[2]: Module "a" successfully parsed as implemented.
count() = 4, len(e) = 5
A
B
C

#
```

**Comment by michalvasko** [comment]
Hi,
I see. When it was working `len(e)` was `4`. What distribution are you using? I reproduced the problem on OpenSUSE Tumbleweed and Ubuntu 18.04 but it worked fine on Ubuntu 14.04.

Regards,
Michal

**Comment by ishidawataru** [comment]
I was using Ubuntu 18.04 (docker).
I tried Ubuntu 14.04 (docker) with swig 4.0.2 and it's working fine.

```
root@ubuntu-bionic:/data# cat /etc/issue
Ubuntu 14.04.6 LTS \n \l
root@ubuntu-bionic:/data# swig -version

SWIG Version 4.0.2

Compiled with g++ [x86_64-unknown-linux-gnu]

Configured options: +pcre

Please see http://www.swig.org for reporting bugs and further information
root@ubuntu-bionic:/data# ./test.py
libyang[2]: Module "a" successfully parsed as implemented.
count() = 4, len(e) = 4
A
B
C
D
```

Ubuntu 16.04 (docker) didn't work.

```
root@ubuntu-bionic:/data# cat /etc/issue
Ubuntu 16.04.6 LTS \n \l

root@ubuntu-bionic:/data# swig -version

SWIG Version 4.0.2

Compiled with g++ [x86_64-pc-linux-gnu]

Configured options: +pcre

Please see http://www.swig.org for reporting bugs and further information
root@ubuntu-bionic:/data# ./test.py
libyang[2]: Module "a" successfully parsed as implemented.
count() = 4, len(e) = 5
A
B
C
Z
```

I'll try to find the root cause when I have time.
