### ISSUE TITLE
ly_ctx_get_node2() fails to return child node added by augment

### ISSUE THREAD

**Issue by milanlenco** [CESNET/libyang#94]
I have two models, one augmenting the other:

```
module small-module {
  namespace "urn:ietf:params:xml:ns:yang:small-module";
  prefix sm;

  organization "organization";
  description
    "example yang module";
  contact
    "contact@example.com";

  container item{
    leaf name {
      type string;
    }
  }
}
```

```
module info-module {
  namespace "urn:ietf:params:xml:ns:yang:info";
  prefix ie;
  import small-module {
    prefix sm;
  }

  organization "organization";
  description
    "example yang module";
  contact
    "contact@example.com";

  augment "/sm:item" {
    leaf info {
      type string;
    }
  }
}
```

I have loaded them both into one context.
A variable `parent` `(struct lys_node *)` points to container `item`. If I run `ly_ctx_get_node2(ctx, parent, "info", 0)` I get an error:
`libyang[0]: Schema node not found. (path: info)`

I have checked that the info module is loaded properly (small-module schema is augmented):
```
(gdb) print ctx->models->list[5]->name
$23 = 0x64ade0 "info-module"
(gdb) print parent
$24 = (const struct lys_node *) 0x64b790
(gdb) print parent->child->name
$25 = 0x64bfd0 "name"
(gdb) print parent->child->next->name
$26 = 0x64f760 "info"
```

**Comment by michalvasko** [comment]
Hi,
I do not see anything wrong here. You have forgotten to include the module name, `info` leaf is from another module, what you asked to retrieve is the child of `item` in the same module (small-module) with the name `info`, there is none.

Regards,
Michal

**Comment by milanlenco** [comment]
Hi,
you are right, my bad, closing this issue as invalid.
