### ISSUE TITLE
Unknown element error when a list is augmented with a leafref 

### ISSUE THREAD

**Issue by RavikumarTulugu** [CESNET/libyang#942]
we are seeing an error when a list is augmented with a leafref referencing the leaf defined already. please find the example yang files below, yanlint would throw "Unknown element" error for the leafref inside augment even when the module is loaded.  we are using libyang-1.0-r4 version latest. 
please advise. 
Thanks 

a.yang:
======
```yang
module a {
yang-version 1.1;
namespace "urn:example:a";
prefix "a";
import b {
prefix b;
}
augment "/b:x/b:y" {
leaf w {
type leafref {
path "/b:x/b:y/b:z";
}
must "re-match(current(),'[a-zA-Z0-9][a-zA-Z0-9\\.\\-_]{0,253}[a-zA-Z0-9]')" {
error-message "Name must match pattern and length.";
}

}
}
}
```
b.yang:
======
```yang
module b {
yang-version 1.1;
namespace "urn:example:b";
prefix "b";
container x {
list y {
key z;
leaf z {
type string;
}
}
}
}
```
data.xml
=========
```xml
<?xml version='1.0' encoding='UTF-8'?>
<x xmlns="urn:example:b">
<y>
<z>ABC</z>
<w>ABC</w>
</y>
</x>
```

**Comment by fredgan** [comment]
I can not reproduce this issue when I use the latest master branch. Maybe you can try it.

**Comment by RavikumarTulugu** [comment]
here are the steps to reproduce, 
 ```
#./yanglint
> add /data/storage/snehal/yang/a.yang
> add /data/storage/snehal/yang/b.yang
> data -t config -s /data/storage/snehal/yang/c.xml
libyang[0]: Unknown element "w". (path: /b:x/y[z='ABC'])
Failed to parse data.
```

**Comment by michalvasko** [comment]
Hi,
that seems to me is the correct behavior, the data are invalid. These are the correct data
```xml
<x xmlns="urn:example:b">
  <y>
    <z>ABC</z>
    <w xmlns="urn:example:a">ABC</w>
  </y>
</x>
```
and they can be successfully validated.

Regards,
Michal

**Comment by RavikumarTulugu** [comment]
Thanks for clarifying ,  am closing the bug.
