### ISSUE TITLE
'When' condition is not satisfied if calling an action

### ISSUE THREAD

**Issue by gitter-runner** [CESNET/libyang#945]
Hi!

It seems to me that if an action is part of a conditional augment (using 'when'), the libyang will not recognize properly if the condition is met, and fails with "When condition <condition> not satisfied.>".

I checked it with gdb and it seems to me - at first glance - that the
resolve_when_ctx_node() function (called from resolve_when(), in the check_augment block) doesn't set a valid context for the action (the actual context will be only the scope of the RPC).

I attached 3 test models (they augment each other). If you add them, use the conditional_action action, and you should see the issue.

Tested it with libyang version 1.0.93.

Thanks!

[test_yangs.zip](https://github.com/CESNET/libyang/files/3851883/test_yangs.zip)

**Comment by michalvasko** [comment]
Hi,
it seems validation of nested notifications/actions with additional data tree was not working at all so I have rewritten it, making it less efficient, but definitely more correct (and less prone to further errors). So, it should work with the current *libyang*.

Regards,
Michal

**Comment by gitter-runner** [comment]
Thanks for the quick fix!

Regards

**Comment by michalvasko** [comment]
Hi,
I have probably not seen your edit or I thought it worked fine. Anyway, in the latest version (1.0.99, after 3 iterations of fixes) it should work fine. By that I mean that this particular `when` should not be validated when the action is parsed. I have also added a test case with stripped versions of your models.

Regards,
Michal
