### ISSUE TITLE
Unknown element error with 2 levels of typedef resolution 

### ISSUE THREAD

**Issue by Snehal1107** [CESNET/libyang#949]
We are seeing an error when a typedef is resolving to another typedef which resolves to a POD type. the hierarchy is as below , 
typedef-----> typedef ----> type. 
I am pasting example yangs which are throwing an error when loaded in yanglint. please take a look. 

a.yang
```
module a {
        yang-version 1.1;
        namespace "urn:example:a";
        prefix "a";
        typedef counter32 {
                type uint32;
        }
        typedef zero-based-counter32 {
                type a:counter32;
                default "0";
        }
}

```
b.yang
```
module b {
        yang-version 1.1;
        namespace "urn:example:b";
        prefix "b";
        import a {
                prefix a;
        }
        container x {
                        leaf z {
                                type a:zero-based-counter32;
                                config false;
                                mandatory true;
                        }
        }
}
```
c.xml
```
<x xmlns="urn:example:b">
    <y>0</y>
</x>
```

> ./yanglint
> add a.yang
> add b.yang
> data -t config -s c.xml
libyang[0]: Unknown element "y". (path: /b:x)
Failed to parse data.
>

**Comment by rkrejci** [comment]
And where is the definition of the 'y'? The problem is not with the typedefs, but with missing definition of y.

**Comment by Snehal1107** [comment]
hi , it was a typo, I corrected it now. please take a look. please reopen the issue.

**Comment by fredgan** [comment]
@Snehal1107 
Hi，your `container x` is config,  but `leaf y` is `config false` in `b.yang` .

So, if you use `-t config` for checking `c.xml`, `config false` data will be ignored.

If you want to check, you should use command like: `data -t data -s c.xml`

Regards
