### ISSUE TITLE
Pattern parsing doesn't support \]

### ISSUE THREAD

**Issue by mkk-dev** [CESNET/libyang#950]
Hi, according to W3 `]` should be escaped. libyang doesn't seem to like it that way.

working pattern:`"^[^!#;+/\"\t][^+/\"\t]{4,30}";`
non-working pattern: `"^[^!#;+/\]\"\t][^+/\"\t]{4,30}"`

Libyang error message:
[ERR]: Encountered invalid character sequence `"\]\"\t][^+".`

thank you!

**Comment by fredgan** [comment]
Hi, 
    As description in [RFC7950, Chapter 6.1.3](https://tools.ietf.org/html/rfc7950#page-45)
   ```
   Within a double-quoted string (enclosed within " "), a backslash
   character introduces a representation of a special character, which
   depends on the character that immediately follows the backslash:

    \n      newline
    \t      a tab character
    \"      a double quote
    \\      a single backslash
   The backslash MUST NOT be followed by any other character.
```
   your re string contains some special characters `\]` should be escaped in re, not in YANG, the correct string in YANG should be  `\\]`.

So, you should rewrite your regular expression as one of follows :
1. double-quoted string: `"^[^!#;+/\\\"\\t][^+/\\\"\\t]{4,30}"`
2. single-quoted string: `'^[^!#;+/\"\t][^+/\"\t]{4,30}'`

**Comment by mkk-dev** [comment]
Thank you, double quotations were indeed my mistake here.
