### ISSUE TITLE
Help on link errors

### ISSUE THREAD

**Issue by LiMinggang** [CESNET/libyang#955]
I'm compiling libnetconf2 test examples but failed with such errors below: 

[ 55%] Linking C executable test_init_destroy_server
/home/gli/netconf/libyang/build/libyang.a(plugins.c.o): In function `static_load_lyext_plugins':
/home/gli/netconf/libyang/build/src/plugin_config.h:98: undefined reference to `nacm'
/home/gli/netconf/libyang/build/src/plugin_config.h:98: undefined reference to `metadata'
/home/gli/netconf/libyang/build/src/plugin_config.h:98: undefined reference to `yangdata'
/home/gli/netconf/libyang/build/src/plugin_config.h:107: undefined reference to `nacm'
/home/gli/netconf/libyang/build/src/plugin_config.h:108: undefined reference to `metadata'
/home/gli/netconf/libyang/build/src/plugin_config.h:109: undefined reference to `yangdata'
/home/gli/netconf/libyang/build/libyang.a(plugins.c.o): In function `static_load_lytype_plugins':
/home/gli/netconf/libyang/build/src/plugin_config.h:117: undefined reference to `user_yang_types'
/home/gli/netconf/libyang/build/src/plugin_config.h:117: undefined reference to `user_inet_types'
/home/gli/netconf/libyang/build/src/plugin_config.h:126: undefined reference to `user_yang_types'
/home/gli/netconf/libyang/build/src/plugin_config.h:127: undefined reference to `user_inet_types'
collect2: error: ld returned 1 exit status
make[2]: *** [tests/CMakeFiles/test_init_destroy_server.dir/build.make:114: tests/test_init_destroy_server] Error 1
make[1]: *** [CMakeFiles/Makefile2:274: tests/CMakeFiles/test_init_destroy_server.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

Did I miss any libraries required by libyang?

**Comment by michalvasko** [comment]
Hi,
it seems you have som incompatibility between these libraries. You have compiled *libyang* statically and I do not think *libnetconf2* can be compiled statically (of course it can, but there is no nice CMake option for that) so it cannot be linked properly.

Regards,
Michal
