### ISSUE TITLE
validation doesn't warn/error when refining a node limited by an feature

### ISSUE THREAD

**Issue by kwatsen** [CESNET/libyang#956]
`yanglint` typically issues warnings (or maybe errors) when it detects a `uses` statement that contains an `augment` statement that augments a node limited by an `if-feature` statement without itself having the same `if-feature` statement.

However, it seems that the same logic isn't applied when a `refine` statement is used instead of an `augment` statement.  It would be great if `yanglint` could be updated to catch this validation issue as well...

Roughly something like this:
```
module A {
  feature f;
  grouping g {  // FWIW, I actually have: grouping/choice/case/if-feature
    if-feature "f";
    container c { ... }
    ...
  }
}

module B {
  import A { prefix a; }
  uses a:g {
    refine "c" {
      must 'some-expr';
      // if-feature "f";    <--- this line is missing, but no warning/error msg issued
    }
```

Hopefully that's clear enough!

**Comment by fredgan** [comment]
Sorry for not understanding.
Maybe you can provide the inputdata and output info(warning messages as you described).

**Comment by kwatsen** [comment]
Closing, the issue was in another tool thinking that there was an issue when there wasn't.  That tool has since been fixed and hence this issue is no more.
