### ISSUE TITLE
Unable to retrieve and print augment model data

### ISSUE THREAD

**Issue by amandeepsethi** [CESNET/libyang#959]
Hi,

I came across a scenario where a structure is used as an augment to other structure.
Using version 1.0.97 of libyang to validate the same.
I am passing the data but unable to retrieve the values of the model augmented.
My model in tree format is as follows:
```
module: model
    +--rw class
       +--rw student* [name]
          +--rw name       string
          +--rw section
             +--rw stream?            string
             +--rw section:subject
                +--rw section:name?   string
```
The corresponding yang files for above tree structure is as follows:
`model.yang`
```
module model {
namespace "urn:test:params:xml:ns:yang:model";
prefix model;

  container class {
    list student {
      key "name";
      leaf name {
        type string;
      }

      container section {
        leaf stream {
          type string;
        }
      }
    }
  }
}
```
While the other yang file having the augment is as below:
`section.yang`
```
module section {
namespace "urn:test:params:xml:ns:yang:section";
prefix section;

  import model {
    prefix model;
  }

  grouping section-top {
    container subject {
      leaf name {
        type string;
      }
    }
  }

  augment "/model:class/model:student/model:section" {
    uses section-top;
  }
}
```
And the data passed is as follows:
```
<class xmlns="urn:test:params:xml:ns:yang:model">
    <student>
        <name>Test</name>
        <section>
            <stream>medical</stream>
            <subject>
                <name>biology</name>
            </subject>
        </section>
    </student>
</class>
```
Now, I am using the `lyd_parse_mem` API to convert the XML data to get parsed according to model and then display its result which is as follows:
```
<class xmlns="urn:test:params:xml:ns:yang:model">
  <student>
    <name>Test</name>
    <section>
      <stream>medical</stream>
    </section>
  </student>
</class>
```
As observed in the output the `subject` container data is missing in output.
Further the same observation is experienced when filtering the data to retrieve the augment model values (Change the #if 0 flag to 1 to enable the filter code).

Attached is the code for reference.
[Code.zip](https://github.com/CESNET/libyang/files/3891036/Code.zip)

**Comment by michalvasko** [comment]
Hi,
the tree format output should be a hint but this mistake still happens quite often. Do not forget, augment data keep their namespace! So, these are the data you want to use
```xml
<class xmlns="urn:test:params:xml:ns:yang:model">
    <student>
        <name>Test</name>
        <section>
            <stream>medical</stream>
            <subject xmlns="urn:test:params:xml:ns:yang:section">
                <name>biology</name>
            </subject>
        </section>
    </student>
</class>
```

Also, you would get an error from *libyang* about this if you used `LYD_OPT_STRICT` for `lyd_parse_mem()`.

Regards,
Michal

**Comment by amandeepsethi** [comment]
Thanks Michal, for the quick response. Tried both the scenarios with/without filter and is working correctly. I guess namespace was the stuff that was missing.
