### ISSUE TITLE
libyang2: the order of refine's nodes can produce some errors. 

### ISSUE THREAD

**Issue by fredgan** [CESNET/libyang#961]
@rkrejci
Hi Radek,
I encounter an error when I use the yang file as follows in libyang2:
`mod2.yang`
```
module mod2 {
  namespace "urn:mod2";
  prefix m2;
  
  grouping gg {
    container con {
      config false;
      leaf le1 {
        type string;
        description "aaa";
      } 
      leaf le2 {
        type string;
      }
      container con2 {
        leaf le3 {
          type int8;
        }
      }
    }
  }

  uses gg {
    refine con/le1 {  //the first refine (1)
      config true;
      description "bbb";
    }

    refine con {  //the second refine (2)
      config true;
    }
  }
}
```
The result is that:
```
err : Invalid refine of config - configuration node cannot be child of any state data node. (/mod2:{uses='gg'}/{refine='con/le1'})
```
However,the error will be lost if I change the order of `the first refine (1)` and `the second refine (2)`.

In addition, I use the pyang and libyang-master to verify it with the same yang file, regardless of the order of `the first refine (1)` and `the second refine (2)`, it does't make any error.

**Comment by rkrejci** [comment]
closing since it seems working in the current libyang2.
