### ISSUE TITLE
Unable to import module from a submodule

### ISSUE THREAD

**Issue by milanlenco** [CESNET/libyang#97]
Hi,

I'm not sure if I follow yang RFC properly here, but it should be possible to import module from a submodule (different from a  "belongs-to" module). But I get an error if I try to parse this module:

_module-a@2016-02-02.yang:_ 
```
module module-a {
  namespace "ns:yang:module-a";
  prefix moda;

  include sub-a {
     revision-date "2016-02-02";
  }
  revision 2016-02-02 {
    description
      "Initial revision.";
  }

  container cont_a {
    leaf l_a {
      type string;
    }
    uses sub-a-group;
  }
}
```

_sub-a@2016-02-02.yang_
```
submodule sub-a {
  belongs-to module-a {
    prefix moda;
  }

  import test-module {
    prefix tm;
  }

  revision 2016-02-02 {
    description
      "Initial revision.";
  }

  identity sub_a_id {
    base tm:id_1;
  }

  grouping sub-a-group {
    container something {
      leaf an-integer {
        type int32;
      }
      leaf a-string {
        type string;
      }
    }
  }
}
```

_test-module.yang:_
```
module test-module {
  namespace "urn:ietf:params:xml:ns:yang:test-module";
  prefix tm;

  identity base_id;

  identity id_1 {
    base base_id;
  }

  identity id_2 {
    base base_id;
  }
}
```
The error I get is:
libyang: Module name "tm" refers to an unknown module.
libyang: Submodule "sub-a" parsing failed.
libyang: Including "sub-a" module into "module-a" failed.
libyang: Module "module-a" parsing failed.

On the other hand, pyang does compile module-a.

**Comment by milanlenco** [comment]
Another possible and maybe related issue that I just found: 
In a situation with two submodules, one including the other and both importing the same module using the same prefix, I get an error:
`libyang[1]: Duplicated prefix identifier "tm".`

While pyang does not complain about this.

So, for example:

```
module module-a {
  namespace "ns:yang:module-a";
  prefix moda;

  include sub-a1;
  include sub-a2;
....
}
```

```
submodule sub-a1 {
  belongs-to module-a {
    prefix moda;
  }

  include sub-a2;

  import test-module {
    prefix tm;
  }
  ...
}
```

```
submodule sub-a2 {
  belongs-to module-a {
    prefix moda;
  }

  import test-module {
    prefix tm;
  }
  ...
}
```
And try to compile `module-a`.

**Comment by michalvasko** [comment]
Hi,
the first problem should be fixed, but the second problem was known and we fixed it in the devel branch by rewriting how imports are handled in the whole library. This change will remain in devel until we merge it, which will not be that soon. I hope it's okay.

Regards,
Michal
