### ISSUE TITLE
libyang2: null dereference in moveto_scnode when parsing XPath

### ISSUE THREAD

**Issue by jvijtiuk** [CESNET/libyang#970]
Hello,

the following file causes a null pointer dereference for yanglint in src/xpath.c:5544, as start_parent is NULL. 

```
module p{
	namespace "";
	prefix p;

	container ports{
		list port {
			key name;
			leaf name{	
				type string;}	
		}	
	}	
	augment "/ports/port" {
		when "0</*=0";
		leaf i {
			type int32;
		}
	}
}
```

The issue appears due to the ```when "0</*=0"``` statement.
start_parent is set to NULL from set->val.scnodes[1].sconde, which was previously set to NULL in moveto_root in src/xpath.c:5271, while parsing the absolute location path.

I would have opened a PR with a fix, but I have already spent a decent amount of time debugging the issue up to this point, and am still not sure of a semantically correct fix. However, I assume someone more familiar with the code could fix this quickly.

I guess that a similar problem could appear in the case when a NULL node is added from src/xpath.c:5274.

Regards,
Juraj

**Comment by michalvasko** [comment]
Hi Juraj,
you should not bother with fixes unless it is a trivial problem. There were actually 3 separate minor problems and int the one you were trying to fix, the node was supposed to be NULL but its type was not meant to be 0. Thanks anyway.

Regards,
Michal

**Comment by jvijtiuk** [comment]
Ok, thanks.
588112f fixes this, so I'm closing the issue.
