### ISSUE TITLE
lyd_parse_xml assert when list's key duplicate exist in xml

### ISSUE THREAD

**Issue by mrdotchenke** [CESNET/libyang#971]
The test module was like this:
```
  module test {
    namespace "urn:test:yang:test";
    prefix tst;
    revision 2019-01-01;
    container test {
      list test-list {
        key "test-key";
        leaf test-key {
          type uint8;
        }
        leaf test-value {
          type uint8;
        }
      }
    }
  }
```

Then I use this xml call lyd_parse_xml with 0 options

```
  <test xmlns="urn:test:yang:test">
    <test-list>
      <test-key>1</test-key>
      <test-key>2</test-key>
    </test-list>
  </test>
```

This assert was raised:

lyd_hash: Assertion `!node->hash || ((node->schema->nodetype == LYS_LIST) && !((struct lys_node_list *)node->schema)->keys_size)' failed.

Test with libyang-1.0-r5 release

**Comment by michalvasko** [comment]
Hi,
should no longer fail those asserts because I have simply removed them. Unfortunately, nothing better to do really.

Regards,
Michal
