### ISSUE TITLE
libyang2: null pointer dereference in src/xpath.c:warn_get_scnode_in_ctx

### ISSUE THREAD

**Issue by jvijtiuk** [CESNET/libyang#975]
Hello,

this file causes a segmentation fault when parsed with yanglint.

```
module example-ietf-interfaces {
  yang-version 1.1;

  namespace "urn:ietf:params:xml:ns:yang:example-ietf-interfaces";

  prefix if;
  import ietf-yang-types {
    prefix yang;
  }

  container interfaces-state {
    config false;
    list interface {
      key "name";
      leaf name {
        type string;
      }
      container statistics {
        leaf in-broadcast-pkts {
          when "derived-from(if:type, 'ianaifp:multicast')" {
          }

          type yang:counter64;
        }
      }
    }
  }
}
```

The issue is that in src/xpath.c:2865, set->val.scnodes[i] dereferences a null pointer, as set->used is 0. As i is 0 as well, this then accesses set->val.scnodes[-1].  A check for whether set->used is larger than 0 would catch this, but after debugging this, it looks like it might be a deeper issue, caused by something to do with the in_ctx variable, as the set that was copied to the one used in warn_get_scnode_in_ctx wasn't empty, so I haven't opened a PR with the fix.

Regards,
Juraj

**Comment by michalvasko** [comment]
Hi,
there was a problem with creating temporary sets for XPath functions. But to actually make libyang print the correct warnings required several other fixes. Should work properly now.

Regards,
Michal

**Comment by jvijtiuk** [comment]
Great, ba71654 fixed this and some other bugs I've yet had to report, so I'm closing the issue.
