### ISSUE TITLE
libyang2: null pointer dereference in lys_feature_precompile_revert

### ISSUE THREAD

**Issue by jvijtiuk** [CESNET/libyang#976]
Hello,

this file causes yanglint to crash.
```
module a{
  yang-version 1.1;
  namespace "ns1";
  prefix a;

  import b{
    prefix acl;
  }

  augment "/acl:acls/acl:acl/acl:aces/acl:ace/acl:matches" {
  }
}
```

Here is the b.yang module:
```
module b {
  yang-version 1.1;
  namespace "ns2";
  prefix acl;

  container acls {
    list acl {
      key "name";
      leaf name {
        type string;
      }
      container aces {
        list ace {
          key "name";
          leaf name {
            type string {
              length "1..64";
            }
          }
          container matches {
            leaf egress-interface {
              type if:interface-ref;
            }
            leaf ingress-interface {
              type if:interface-ref;
            }
          }
        }
      }
    }
  }
}
```

The crash occurs because mod->compiled is NULL in src/tree_schema_compile.c:1321.
The module is passed to lys_feature_precompile_revert from ctx.ctx->list.objs[5] in lys_compile, which is also NULL. However, that pointer is set to NULL when mod->compiled is set to NULL, so I guess that this is caused by the pointers being somehow invalidly shared.

Regards,
Juraj

**Comment by michalvasko** [comment]
Hi,
it seems to me the `compiled` module can be `NULL` when several dependent modules are compiled like this so that is the fix I have made.

Regards,
Michal

**Comment by jvijtiuk** [comment]
2947ce1 fixed this so I'm closing the issue.
