### ISSUE TITLE
libyang2: null dereference in lys_module_find_prefix due to NULL module

### ISSUE THREAD

**Issue by jvijtiuk** [CESNET/libyang#979]
Hello,

these files crash yanglint on the libyang2 branch.

```
module a {
  namespace "a";
  prefix a;

  import b{
    prefix b;
  }

  typedef HexOffset {
    type string;
  }

  grouping group {
    container action {
      config false;
      container register {
        config false;
        list location {
          key "location";
          config false;
          leaf location {
            type string;
          }
          b:action "write" {
            input {
              leaf reg-addr {
                type HexOffset;
                mandatory true;
              }
            }
            output {
              leaf result {
                type string;
              }
            }
          }
        }
      }
    }
  }
}
```

```
module b {
  namespace "b";
  prefix b;

  extension action {
    argument name {
      b:arg-type {
        type b:identifier;
      }
    }
  }
}
```

The cause of the crash is the null dereference in src/tree_schema_helpers.c in lys_module_find_prefix. There is a check for mod->compiled, but if mod is NULL, that causes a NULL dereference. I've looked into adding a simple !mod check, but the NULL value propagates from above the call stack, so I'm not sure if a null check and error reporting should be done earlier.

Regards,
Juraj

**Comment by michalvasko** [comment]
Hi Juraj,
should work properly now, there was an additional problem except for the crash.

Regards,
Michal

**Comment by jvijtiuk** [comment]
b541af0 fixes this so I'm closing the issue.
