### ISSUE TITLE
Verification of error in git config

### ISSUE THREAD

**Issue by masif-cs** [CESNET/libyang#981]
Hi,

I want to test the functionality of edit-config RPC with tag [--error stop|continue|rollback]

So below are the steps what I tried:
1. for --error stop, it is default functionality, so need to test anything
2. for ---error continue, I registered two modules oven1 and oven2. Registered and subscribed it using two example application. Edited one application example to return failure all the time from the callback function. But my values were getting aborted instead of storing for one application and rejecting for another application. Thats what is expected from "continue" I think? Let me know if my understanding is not correct or I am not testing properly.
3. for --error rollback, can you give some input how to verify this?

**Comment by fredgan** [comment]
Is this an issue about yanglint or libyang? I don't see this tag

**Comment by michalvasko** [comment]
Hi,
firstly, as @fredgan mentioned, why is this issue in *libyang*, did you not try it with *netopeer2-server*? I will assume you did and just say that it does not support other error handling than `rollback`. It informs about this if you set logging to verbose.

Regards,
Michal

**Comment by masif-cs** [comment]
Hi,

Sorry, by mistake I posted it in libyang instead of netopeer2. Yes I tested with netopeer2-server. So continue-on-error and stop-on-error is not supported. Is it going to be supported in future?

**Comment by michalvasko** [comment]
Hi,
no, it is not. All those other modes are basically deprecated and it does not make much sense to use them anyway. The new NMDA [edit-data](https://www.rfc-editor.org/rfc/rfc8526.html#section-3.1.2) (which *netopeer2* supports) operation does not define this option at all.

Regards,
Michal
