### ISSUE TITLE
A yang version 1 module or submodule should not import a yang-version 1.1 module by revision 

### ISSUE THREAD

**Issue by fredgan** [CESNET/libyang#984]
As described in [RFC7950 Chapter 12](https://tools.ietf.org/html/rfc7950#section-12)

```
   A YANG version 1 module or submodule MUST NOT import a YANG
   version 1.1 module by revision.
```

I find that yanglint doesn't conform this rule.

The examples is as following:

`mod7.yang`

```yang
module mod7 {
  namespace "urn:cesnet:mod7";
  prefix abc;

  import mod7_1 {
    prefix m;
    revision-date 2018-08-11;
  }
}

```

`mod7_1.yang`

```yang
module mod7_1 {
  namespace "urn:cesnet:mod7_1";
  prefix m;
  yang-version 1.1;

  revision 2018-08-11 {
    description "test";
  }
}
```

I use the command `yanglint -f yang mod7.yang`, but this doesn't report an error. Maybe this is an issue.

**Comment by michalvasko** [comment]
Hi,
you are right and now this should fail with an error.

Regards,
Michal

**Comment by fredgan** [comment]
Hi,
it works now. Thanks.

Regards,
Fredgan
