### ISSUE TITLE
Grouping statement should not reference itself

### ISSUE THREAD

**Issue by fredgan** [CESNET/libyang#986]
Hi,
As is described in [RFC7950 Chapter 7-12](https://tools.ietf.org/html/rfc7950#page-104)

```
 Once a grouping is defined, it can be referenced in a "uses"
 statement (see Section 7.13).  A grouping MUST NOT reference itself,
 neither directly nor indirectly through a chain of other groupings.
```
I define many "grouping" statements in current module, and `gg3` references itself indirectly by `gg1`. However, yanglint(version 1.3.7) can't find this error in some case. The module `mod.yang` is as following:
```yang
module mod {
  yang-version 1.1;
  namespace "urn:mod";
  prefix aa;

  grouping gg3 {
    leaf le3 {
      type string;
    }
    leaf le4 {
      type string;
    }
    uses gg1;
  }

  grouping gg1 {
    grouping gg2 {
      leaf le2 {
        type string;
      }
      uses gg3;
    }
  }
}

```
Actually the yanglint result is:
```yang
$ yanglint -f yang mod.yang
module mod {
  yang-version 1.1;
  namespace "urn:mod";
  prefix aa;

  grouping gg3 {
    leaf le3 {
      type string;
    }
    leaf le4 {
      type string;
    }
    uses gg1;
  }

  grouping gg1 {
    grouping gg2 {
      leaf le2 {
        type string;
      }
      uses gg3;
    }
  }
}

```
The expected result is that yanglint should report an error like  "Exist a circular dependency.".

**Comment by michalvasko** [comment]
Hi,
in this case grouping `gg2` is not instantiated and that is why *libyang* is not able to detect this. In an ideal situation it should be detected even in this case but it would be too much additional code without much value for the old *libyang*.

Regards,
Michal

**Comment by fredgan** [comment]
Yeah，you are right. libyang can detect it if `gg2` is used.
