### ISSUE TITLE
libyang2:The input or output statement should not be empty

### ISSUE THREAD

**Issue by fredgan** [CESNET/libyang#988]
The same with issue #987 but in libyang2 branch.

As the description of the ABNF [in RFC7950](https://tools.ietf.org/html/rfc7950#page-199)
```
   input-stmt          = input-keyword optsep
                         "{" stmtsep
                             ;; these stmts can appear in any order
                             *must-stmt
                             *(typedef-stmt / grouping-stmt)
                             1*data-def-stmt
                         "}" stmtsep
```

We can know that one or more data-def-stmt should be included in the input/output statement.

But yanglint doesn't conform this rule.

The example is as follow:

```yang
module mod4 {
  yang-version 1.1;
  namespace "urn:cesnet:mod4";
  prefix abc;

  list aa {
    key "name";
    leaf name {
      type string;
    }
    action act {
      input {}
      output {
        leaf l {
          type string;
        }
      }
    }
  }
}

```
yanglint doesn't report any error for this module.

The expected result is that yanglint can report an error like 'input statement cannot be empty'.

**Comment by michalvasko** [comment]
Hi,
it should now correctly print the error.

Regards,
Michal

**Comment by fredgan** [comment]
Hi,
it works now. Thanks.

Regards,
Fredgan
