### ISSUE TITLE
The decimal places of data value should not be exceeded by the restricting "fraction-digits" statemate's value

### ISSUE THREAD

**Issue by fredgan** [CESNET/libyang#990]
Hi, As described in the [RFC9.3.4 Chapter 9.3.4](https://tools.ietf.org/html/rfc7950#section-9.3.4) 

```
   The "fraction-digits" statement, which is a substatement to the
   "type" statement, MUST be present if the type is "decimal64".  It
   takes as an argument an integer between 1 and 18, inclusively.  It
   controls the size of the minimum difference between values of a
   decimal64 type by restricting the value space to numbers that are
   expressible as "i x 10^-n" where n is the fraction-digits argument.
```

I think the multiple trailing zeros can not be ignored and a "0" represents one decimal places.For example,I set the default value "3.140000" when the fraction-digits value is 2, expect failure and error msg. We can only write "3.14" as the default value.

But when I run the command "yanglint -f yang mod6.yang" with yanglint(v1.3.7), its result is successful,there is no error or msg. 

yang module(mod6.yang) is as follow:

```
module mod6 {
  namespace "urn:cesnet:mod6";
  prefix abc;
  yang-version 1.1;

  typedef my-decimal {
    type decimal64 {
      fraction-digits 2;
    }
  }

  leaf l {
    type my-decimal;
    default "3.14000";
  }
}
```

**Comment by michalvasko** [comment]
Hi,
I believe this is just a matter of interpretation and we decided to be lenient. The specs are "restricting the value space" which can be understood as the semantic meaning of the number. `3.14000` differs from `3.14` only in the syntax, semantics is the same. So, I would just keep it the way it is.

Regards,
Michal
