### ISSUE TITLE
Can the node be the deviate target node in the own module?

### ISSUE THREAD

**Issue by fredgan** [CESNET/libyang#992]
I write a module like this:

`mod1.yang`

```yang
module mod1 {
  yang-version 1.1;
  namespace "urn:mod1";
  prefix aa;

  container cc {
    leaf le2 {
      type string;
      default "Hello";
    }
  }

deviation "/cc/le2" {
    deviate delete {
        default "Hello";
    }
  }
}
```

The actual result:

```sh
$ yanglint -f yang mod1.yang
err : Invalid value "/cc/le2" of "deviation".
err : Deviating own module is not allowed.
err : Module "mod1" parsing failed.
```

I don't find a rule like 'Deviating own module is not allowed.' in the RFC specification. Pyang doesn't report this error. So I am not sure whether is this an issue or not. Thanks.

**Comment by michalvasko** [comment]
Hi,
this is a "feature" of *libyang* because it simplified things a bit when deviating your own module was forbidden. It makes no sense and there cannot possible be a relevant use-case so it should not matter.

Regards,
Michal

**Comment by fredgan** [comment]
Seems reasonable. Closing
