### ISSUE TITLE
The equal symbol is '=' not '==' in XPath in must expression

### ISSUE THREAD

**Issue by fredgan** [CESNET/libyang#993]
Hi,
As is described in in the  [XML Path Language Version1.0 chapter 3.4](https://www.w3.org/TR/1999/REC-xpath-19991116/#booleans)

> Second, comparisons that do not involve node-sets are defined for = and !=.

So the equal symbol is "=" not "=="

The example is as follow:

`mod1.yang`

```yang
module mod1 {
  yang-version 1.1;
  namespace "urn:mod1";
  prefix aa;

  container con {
      leaf le1 {
          type string;
      }
  }
  container cc {
      leaf le2 {
          type string;
      }
      must "/con/le1 == 'aaa'" {
          error-message "value must be aaa";
      }
  }
}
```

Actually the result of yanglint is:

```yang
$ yanglint -f yang mod1.yang
module mod1 {
  yang-version 1.1;
  namespace "urn:mod1";
  prefix aa;

  container con {
    leaf le1 {
      type string;
    }
  }

  container cc {
    must "/con/le1 == 'aaa'" {
      error-message
        "value must be aaa";
    }
    leaf le2 {
      type string;
    }
  }
}
```

The expected result is that yanglint should report an error like 
> XPath syntax error: syntax error before '='.

**Comment by michalvasko** [comment]
Hi,
any XPath errors are not considered fatal errors in the old *libyang*. Try
```
$ yanglint -f yang mod1.yang -V
```

Regards,
Michal
