### ISSUE TITLE
Performance regression since 222476c due to lyht_dbgprint_ht/lyht_dbgprint_value

### ISSUE THREAD

**Issue by jktjkt** [CESNET/libyang#995]
During an update from November 20th versions to today's versions (still on the legacy branch), we've hit a performance regression which I eventually traced to new `lyht_*` debugging which was added in 222476c. @syyyr's application, an [interactive NETCONF console client](https://gerrit.cesnet.cz/plugins/gitiles/CzechLight/netconf-cli/), uses libnetconf2 + libyang to connect to a NETCONF server (Netopeer2 via a Unix socket in this test case). The failing test, [`test_setting_values_netconf`](https://gerrit.cesnet.cz/plugins/gitiles/CzechLight/netconf-cli/+/2da1cc5364d0b6c493deea658bb3e82e1d506c08/tests/setting_values.cpp), basically just connects, retrieves the YANG schema for a local libyang context, and attempts to set a few variables -- doing all this 16 times in a row for different test cases.

Previously, the whole test finished in about [12 seconds](https://object-store.cloud.muni.cz/swift/v1/ci-logs-public/66/2166/2/check/f29-gcc/81fc496/job-output.txt), now [it's hitting (our internal) timeout after 15 minutes](https://object-store.cloud.muni.cz/swift/v1/ci-logs-public/69/2169/1/check/f29-gcc/990f195/job-output.txt). We are *not* setting libyang's debugging levels explicitly, but we're calling `nc_verbosity(NC_VERB_DEBUG)` which results in `ly_verb(LY_LLDBG)` behind the scenes -- and therefore the extra debug logging of hash table manipulation gets activated by accident.

Just for a reference, here's profiler's output from my development setup (with ASAN):

![image](https://user-images.githubusercontent.com/2631925/71838375-91664f00-30b0-11ea-80a8-473785711f7c.png)

Note that we're hitting this problem on all build configurations, not just on ASAN-enabled builds (but ASAN does make it worse, of course).

If you would like to reproduce this in a controlled environment, do:
- `git clone https://gerrit.cesnet.cz/CzechLight/netconf-cli.git`,
- `git fetch origin refs/changes/69/2169/1`
- `git reset --hard FETCH_HEAD`
- and then proceed as per the [`README.md`](https://gerrit.cesnet.cz/plugins/gitiles/CzechLight/netconf-cli/+/refs/heads/master/README.md), there are a few C++ dependencies you probably do not have installed.

The **TL;DR** version is that a `git revert 222476c6d89093788d92c929489c14c3ee5f59cf` on top of CESNET/libyang@a948fe4f (current libyang `master`) makes everything work again. Please consider either nuking that hash table debugging, or hiding it behind a preprocessor macro.

**Comment by michalvasko** [comment]
Hi,
it should be fixed now. But you could have simply called
```C
nc_verbosity(NC_VERB_DEBUG);
ly_verb(LY_LLVRB);
```

Regards,
Michal

**Comment by jktjkt** [comment]
Can you please cherry-pick this to master as well?

**Comment by jktjkt** [comment]
> Can you please cherry-pick this to master as well?

Ah, never mind, I assumed that this was just on the "unstable here by dragons" branch. My bad.
