### ISSUE TITLE
LIBYANG_EXTENSIONS_PLUGINS_DIR default

### ISSUE THREAD

**Issue by miroslavKovacPantheon** [CESNET/libyang#997]
Hi,

isn t it possible to set this env variable by default to <build directory>/src/extensions so one doesn t have to set it before using yanglint?

Thank you
Miroslav Kovac

**Comment by michalvasko** [comment]
Hi,
you mean
```
export LIBYANG_EXTENSIONS_PLUGINS_DIR=/src/extensions
```

Regards,
Michal

**Comment by miroslavKovacPantheon** [comment]
no sorry.. the coding removed part of the text. I meant to \<build directory\>/src/extensions

**Comment by michalvasko** [comment]
Right, it makes no difference. Just `export` once the specific correct path and that is it. Or install *libyang*.

Regards,
Michal

**Comment by levkowetz** [comment]
It seems that setting LIBYANG_EXTENSIONS_PLUGINS_DIR is necessary even after running install.  I think this should not be necessary?

**Comment by michalvasko** [comment]
Hi,
no, that [should not](https://github.com/CESNET/libyang/blob/master/FAQ.md) be necessary. What is the error when you are not setting this evn variable? What is your `make install` output?

Regards,
Michal

**Comment by miroslavKovacPantheon** [comment]
Hi,

Seemes that we figured things out. Although I have received some strange error after make install.
`yanglint: error while loading shared libraries: libyang.so.1: cannot open shared object file: No such file or directory
`
but when I used `ldconfig` command it started to work.

thank you

**Comment by michalvasko** [comment]
Hi,
that actually makes sense.

Regards,
Michal
