### ISSUE TITLE
err: Must condition not satisfied (shouldn't be evaluated at all)

### ISSUE THREAD

**Issue by kwatsen** [CESNET/libyang#999]
My understanding is that `must` expressions should only be evaluated if their parent node exists.

Using this YANG module:

```
module test {
  yang-version 1.1;
  namespace "https://example.net/test";
  prefix "t";

  container c {
    must "a or b";
    leaf a {
      type string;
    }
    leaf b {
      type string;
    }
  }

  leaf z {
    type string;
  }
}
```

and either of these instance files:

test.xml:
```
<z xmlns="https://example.net/test">hello</z>
```

test.json
```
{ "test:z": "hello" }
```

produces the error messages:
```
$ yanglint test.yang test.json
err : Must condition "a or b" not satisfied. (/test:c)

$ yanglint test.yang test.xml 
err : Must condition "a or b" not satisfied. (/test:c)
```

However, note that `yangson` is okay with it.
```
yangson -p ./ -v test.json test_yl.json 
<no output>
```

where test_yl.json is:
```
{
  "ietf-yang-library:modules-state": {
    "module-set-id": "",
    "module": [
      {
        "name": "test",
        "revision": "",
        "conformance-type": "implement"
      }
    ]
  }
}
```

**Comment by michalvasko** [comment]
Hi,
yet again a problem of interpretation and the existence of NP containers. Mostly based on [this](https://tools.ietf.org/html/rfc7950#page-51):

> If a node that exists in the accessible tree has a non-presence
   container as a child, then the non-presence container also exists in
   the accessible tree.

we generally consider all NP containers with existing parents and top-level NP containers to exist, both in the data tree and for any XPath evaluation. This seemed like the only sensible conclusion after reading and implementing the whole YANG specification and I do not know of any specification part that such an implementation would not be compliant with. Also, there is the basic problem that [this](https://tools.ietf.org/html/rfc7950#section-7.5.1):

> In particular, the presence of the
   container node with no child nodes is semantically equivalent to the
   absence of the container node.

is simply not true for many cases, your use-case being one of them. Not sure what more to add.

Regards,
Michal

**Comment by kwatsen** [comment]
Hi Michal,

Yes, this is again the issue with the underspecified NP-container behavior in RFC 7950.  There are a number of YANG-next issues regarding it.   

It's very concerning to me that `yanglint` and `yangson` differ on this, as I use both heavily.

Hmmm, would be possible to introduce a flag to toggle the NP-container behavior?  Of course, such a flag should be added to `yangson` as well.  Then uses could choose - makes sense?

Regards,
Kent

**Comment by michalvasko** [comment]
Hi Kent,
so what exactly would this option do? Would it be fine for it to just cause all `must` and `when` on NP containers to not be evaluated? That seems possible and it should not break anything but I would still prefer to keep it the way it is, this could cause a significantly different data to be returned by validation.

Also, to our knowledge `yangson` development is not really active anymore so I am not sure any new flags can be added.

Regards,
Michal

**Comment by kwatsen** [comment]
Hi Michal,

What exactly such a flag would do is a good question.  Disabling `must` and `when` expressions would address all (I think) validation needs as, when validating an instance document, it's not possible for a node to exist without its ancestor also existing.  That said, for those using the `libyang` API, there MAY be an additional desire to fail trying to add a descendent node when the ancestor NP-container is missing; though I imagine this last bit being a low-priority item.

Regarding `Yangson` current status, it is true that commits are slow, but I believe that this is mostly because the code is effectively done and in maintenance-only mode.  Looking at [it's GitHub page](https://github.com/CZ-NIC/yangson), the last commit was ~6 weeks ago (driven by a private exchange I had with Lada), though I see activity on a PR submitted just 4 days ago.  Furthermore, `Yangson` is used by `Jetconf`, which is a RESTCONF server that CZ-NIC is using for in-house management of their networks.  However, to address your point and close the circle, I just sent an email to Lada pointing to this issue here.

Cheers,
Kent

**Comment by michalvasko** [comment]
Hi Kent,
I am glad you prefer our implementation now because it is the one that made more sense. Based on one place that did [specify their behavior](https://tools.ietf.org/html/rfc7950#page-51), they seemed like a special default value so we treated them that way. And yes, we are also hoping for the next specification to be clear about their existence because it is the only way to ensure interoperability and uniform behavior.

Regards,
Michal
